### ISSUE TITLE
amp-date-picker validation valueMissing not working

### ISSUE THREAD

**Issue by kakha13** [ampproject/amphtml#20734] opened 2019-02-08 09:31 UTC
This is my code
`<amp-date-picker
                 type="single"
		 class="tohide"
                 mode="overlay"
                 layout="container"
                 input-selector="[name=submiter_date]" >
               <input name="submiter_date"
                class="input tohide"
                id="submiter_date"
                placeholder="აირჩიეთ თარიღი"
		readonly="true"
		type="date"
		required>	
               </amp-date-picker>`

## What's the issue?

I have problem about amp date picker validation 
when i submit post its not showing error
i have another input form and it working normally 
`<form class="sample-form"
               method="post"
               target="_top"
               name="chawera" 
               id="chawera" action-xhr="/chawera1"
               custom-validation-reporting="as-you-go"
               >
               <input type="text"
                  class="input tohide"
                  id="as-you-go-submiter_name"
                  name="submiter_name"
                  placeholder="სახელი და გვარი"
                  required>
               <span visible-when-invalid="valueMissing"
                  validation-for="as-you-go-submiter_name"></span>
               <span visible-when-invalid="patternMismatch"
                  validation-for="as-you-go-submiter_name">
               გთხოვთ მიუთითოთ სრული სახელი დაგვარი
               </span>`

## How do we reproduce the issue?

I tried many thinks but nothing. it this my problem or AMP is not supporting amp-date-picker validation?

## Which AMP version is affected?

This is my version : amp-date-picker-0.1.js

**Comment by cvializ** [comment] 2019-02-08 20:05
Hi @kakha13 thanks for letting us know about your issue. It looks like it's not getting validated because the input is readonly. I'm going to close this issue, since it's a duplicate of https://github.com/ampproject/amphtml/issues/17687

**Closed by cvializ** 2019-02-08 20:05 UTC
Labels: Category: User Input, Type: Bug

**Comment by rajdri** [comment] 2019-08-02 13:45
Required--validation is not working
