### ISSUE TITLE
`describes.` tests weird namespace error

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#34642] opened 2021-06-01 20:56 UTC
![image](https://user-images.githubusercontent.com/6694512/120389125-ffd92c00-c2f9-11eb-9170-0a6ec3193127.png)

`math - LayoutRect` is in `test/core/math/test-layout-rect.js`, but for some reason (locally and in CI) it seems like the test context is still active for other tests that run. I believe I've seen this bug with other tests, but I don't recall which ones. Seems like maybe the `describes` infra isn't cleaning up after the context closes?

https://app.circleci.com/pipelines/github/ampproject/amphtml/10273/workflows/abca5c6f-254a-4d1a-ba82-262a612b5a83/jobs/159979

/cc @ampproject/wg-infra

**Comment by rsimha** [comment] 2021-06-01 21:06
Looks like a dupe of #34580. I think there's merit in the theory about `describes`. Will investigate.

**Closed** 2021-06-02 15:28 UTC
Labels: P3: When Possible, Related to: Flaky Tests, Type: Bug, Type: Testing, WG: infra
