### ISSUE TITLE
How can I disable amp-accordion state being saved to session storage?

### ISSUE THREAD

**Issue by weeblr** [ampproject/amphtml#6194] opened 2016-11-15 09:39 UTC
Hi

Currently amp-accordion saves its state ("expanded" or not basically) to Session storage. It's done on a per-URL basis, so when one comes back to a page where they opened an accordion on a previous visit, the accordion will be displayed expanded.
It's nice in many situations, but a major problem in others. I use an accordion to display menus and search boxes, and I definitely don't want the menu/search box to be displayed when user comes back t the page. It's all done and works great, but I can't release it to public because of that state being saved.

I checked the source for amp-accordion, and there is option to not save the state. Can such option be added as an attribute to amp-accordion element, to avoid saving state?

Thanks for consideration.

Rgds

**Comment by jridgewell** [comment] 2016-11-15 17:59
Dupe of https://github.com/ampproject/amphtml/issues/3813, PR at https://github.com/ampproject/amphtml/pull/3852.

**Closed by jridgewell** 2016-11-15 17:59 UTC

**Comment by weeblr** [comment] 2016-11-15 18:06
Hi @jridgewell 

I did search for amp-accordion, but probably not that far back. This PR seems stuck though. Very unfortunate now that we start wanting adding real-life features to AMP sites (as described in my OP).
Code is written but end result is not usable because accordion just save its state.

Any way to push this?

Thanks

**Comment by jridgewell** [comment] 2016-11-15 18:08
Just pinged her on the PR.

**Comment by weeblr** [comment] 2016-11-15 18:13
Thanks, fingers crossed

**Comment by zhouyx** [comment] 2016-11-22 00:42
@camelburrito What do you think of getting #3852 in?

**Comment by soilysound** [comment] 2016-11-27 23:17
I have to agree with weeblr, this component is severely impaired until this issue is fixed.

**Comment by camelburrito** [comment] 2016-11-28 17:07
@zhouyx can you get #3852 today and fix this.

**Comment by zhouyx** [comment] 2016-11-28 19:10
will work on #3852.
