### ISSUE TITLE
Error: Object function Number() { [native code] } has no method 'parseFloat'

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#21109] opened 2019-02-26 21:18 UTC
Error: Object function Number() { [native code] } has no method 'parseFloat'
    at parseFloat (https://raw.githubusercontent.com/ampproject/amphtml/1902191749350/node_modules/@ampproject/animations/dist/animations.mjs:2:526)
    at https://raw.githubusercontent.com/ampproject/amphtml/1902191749350/node_modules/@ampproject/animations/dist/animations.mjs:2:684
    at u (https://raw.githubusercontent.com/ampproject/amphtml/1902191749350/node_modules/@ampproject/animations/dist/animations.mjs:2:956)
    at w (https://raw.githubusercontent.com/ampproject/amphtml/1902191749350/node_modules/@ampproject/animations/dist/animations.mjs:4:2451)
    at prepareImageAnimation (https://raw.githubusercontent.com/ampproject/amphtml/1902191749350/node_modules/@ampproject/animations/dist/animations.mjs:4:1962)
    at innerHeight (https://raw.githubusercontent.com/ampproject/amphtml/1902191749350/src/service/viewport/viewport-impl.js:832:25)
    at enterFullOverlayMode (https://raw.githubusercontent.com/ampproject/amphtml/1902191749350/src/service/viewport/viewport-impl.js:761:6)

Seems new to me. @choumx @jridgewell could you please take a look. Thank you

go/amp-error/CMmK7_mMtpLITg

**Comment by jridgewell** [comment] 2019-02-26 21:36
Dupe of https://github.com/ampproject/amphtml/issues/20927.

**Closed by jridgewell** 2019-02-26 21:36 UTC
Labels: P1: High Priority, Type: Bug
