### ISSUE TITLE
🚨 Error: null is not an object (evaluating 'a.__AMP_TOP') / from timer-impl.js

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#29648] opened 2020-08-03 20:41 UTC
Note that this error is only in canary not in RC so it's very likely from the ampdoc-fie experiment running in canary starting from from the 0724 build.

Details
---

**Error report:** [link](https://pantheon.corp.google.com/errors/CNmNkYT1wobKcQ?service=CDN%201%25&time=P7D&project=amp-error-reporting)
**First seen:** <First seen date> 
**Frequency:** ~ <Daily occurrences>/day

Stacktrace
---
```
Error: null is not an object (evaluating 'a.__AMP_TOP')
    at win (https://raw.githubusercontent.com/ampproject/amphtml/2007242032001/src/service.js:325:9)
    at win (https://raw.githubusercontent.com/ampproject/amphtml/2007242032001/src/service.js:199:21)
    at defaultView (https://raw.githubusercontent.com/ampproject/amphtml/2007242032001/src/service.js:354:31)
    at elementOrAmpDoc (https://raw.githubusercontent.com/ampproject/amphtml/2007242032001/src/service.js:251:27)
    at elementOrAmpDoc (https://raw.githubusercontent.com/ampproject/amphtml/2007242032001/src/services.js:766:6)
    at https://raw.githubusercontent.com/ampproject/amphtml/2007242032001/src/service/resource.js:635:45
    at https://raw.githubusercontent.com/ampproject/amphtml/2007242032001/src/service/resource.js:690:8
    at r (https://raw.githubusercontent.com/ampproject/amphtml/2007242032001/src/service/resources-impl.js:1411:25)
    at callback (https://raw.githubusercontent.com/ampproject/amphtml/2007242032001/src/finite-state-machine.js:72:6)
    at https://raw.githubusercontent.com/ampproject/amphtml/2007242032001/src/service/resources-impl.js:812:42
    at https://raw.githubusercontent.com/ampproject/amphtml/2007242032001/src/service/resources-impl.js:150:42
    at https://raw.githubusercontent.com/ampproject/amphtml/2007242032001/src/pass.js:109:4
    at https://raw.githubusercontent.com/ampproject/amphtml/2007242032001/src/pass.js:55:6
    at callback (https://raw.githubusercontent.com/ampproject/amphtml/2007242032001/src/service/timer-impl.js:76:10)
```

/cc @ampproject/release-on-duty

**Comment by rsimha** [comment] 2020-08-03 20:45
Thanks for providing context, @lannka. Looks like this was created twice. Closing this as a dupe of #29647.

**Comment by lannka** [comment] 2020-08-03 20:46
@rsimha same error with different stack trace. re-opening.

**Closed** 2020-08-04 22:32 UTC
Labels: Type: Error Report
