### ISSUE TITLE
AMP Call Tracking Error Not Reported

### ISSUE THREAD

**Issue by dakkad** [ampproject/amphtml#9162] opened 2017-05-05 14:51 UTC
During testing of the AMP call tracking https://www.ampproject.org/docs/reference/components/amp-call-tracking the module does not report errors but does not function.

Go to URL: https://amp-demo-landing-page.appspot.com/static/amp-page.html#development=1

The call tracking component does not substitute the phone number provided but does not report errors on the console. 

Sebastian Benz was able to see an error the first time he loaded the page that the CORS setup is missing. 

The documentation needs updating to include details of the security headers needed to enable this to work and the validator should throw an error to explain if the data is invalid.

## What browsers are affected?
Chrome 58.0.3029.81

## Which AMP version is affected?
Powered by AMP ⚡ HTML – Version 1493855940942

**Comment by jridgewell** [comment] 2017-05-05 18:50
> Sebastian Benz was able to see an error the first time he loaded the page that the CORS setup is missing.

We should probably make it clear that this XHR was initiated from `<amp-call-tracking>`. 

> The documentation needs updating to include details of the security headers

"Important - Your XHR endpoint needs to follow and implement [CORS Requests in AMP spec](../../spec/amp-cors-requests.md)."

Are you reading the GitHub markdown, or the ampproject rendered docs? The GitHub markdown is definitely muddled because of our callout code. /cc @bpaduch

**Comment by dakkad** [comment] 2017-05-09 13:42
The issue is related to the fact that there are no errors reported on the console when the endpoint doesn't implement the CORS request AMP spec.

**Comment by jridgewell** [comment] 2017-05-09 17:18
I see the CORS message every time, are you not?

**Comment by alanorozco** [comment] 2017-06-01 19:05
Can't reproduce. Do you not see the errors when setting the URL fragment to `development=1`?

**Comment by alanorozco** [comment] 2017-06-16 18:15
Closing this. We can reopen if we have repro steps.

**Closed by alanorozco** 2017-06-16 18:15 UTC
Labels: Type: Feature Request
