### ISSUE TITLE
Error: viewport has zero dimensions

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#24074] opened 2019-08-20 16:40 UTC
The error is added in #8061 . We are still seeing [10K errors per day](https://pantheon.corp.google.com/errors/CPSA3a_89vCGkQE?time=P30D&filter=text:%22viewport%20has%20zero%20dimensions%22&project=amp-error-reporting) right now. 

The error is sampled at 1%, so it's actually 1M errors per day.
https://github.com/ampproject/amphtml/blob/1aa3fefac0da7c971e233975b4ed180282d9770c/src/service/viewport/viewport-impl.js#L293-L295

Is this expected? @dvoytenko

**Comment by dvoytenko** [comment] 2019-08-20 17:25
@lannka generally, no, not expected. But it's not a very bad error. Do you know which viewer though?

**Comment by lannka** [comment] 2019-08-20 17:42
I scanned through a couple of examples, they are all from one of the following:

**amp_js_v=0.1**
https://www-wattpad-com.cdn.ampproject.org/v/s/www.wattpad.com/amp/665419892?amp_js_v=0.1&usqp=mq331AQEKAFwAQ%3D%3D 

**amp_js_v=a2&amp_gsa=1**
https://www-cittaceleste-it.cdn.ampproject.org/v/s/www.cittaceleste.it/notizie/calciomercato/calciomercato-inter-vidal-rakitic-milinkovic-ce-anche-qualcosaltro/amp/?amp_js_v=a2&amp_gsa=1&usqp=mq331AQEKAFwAQ%3D%3D 

**web_view=1**
https://news-tut-by.cdn.ampproject.org/c/s/news.tut.by/amp/society/650256.html?web_view=1&preload=1&audio_bridge=1&photo_view=1&can_infinite_scroll=1 

**Canonical**
https://www.esto.com.mx/445124-video-raul-jimenez-wolverhampton-manchester-united-premier-league-ultimas-noticias/amp/

**Comment by dvoytenko** [comment] 2019-08-20 17:45
Do we have any sample URL fragments?

**Comment by lannka** [comment] 2019-08-20 17:48
Here is [one](https://pantheon.corp.google.com/errors/CPSA3a_89vCGkQE?time=P30D&filter=text:%22viewport%20has%20zero%20dimensions%22&project=amp-error-reporting).

POST /r?v=011908162035200&noAmp=0&m=viewport%20has%20zero%20dimensions&a=0&ex=0&dw=0&rt=1p&ca=0&bt=production&rvu=https%3A%2F%2Fwww-express-co-uk.cdn.ampproject.org%2Fv%2Fs%2Fwww.express.co.uk%2Flife-style%2Fscience-technology%2F1167465%2Fgoogle-chrome-login-how-to-reset-password-checkup-online-leak%2Famp%3Famp_js_v%3D0.1&jse=IE&exps=pump-early-frame%3D1%2Cchunked-amp%3D1%2Camp-ad-ff-adx-ady%3D0%2Camp-list-load-more%3D1%2Camp-consent-v2%3D1%2Ccanary%3D0%2Camp-story-v1%3D1%2Chidden-mutation-observer%3D1%2Ca4aProfilingRate%3D0%2Cversion-locking%3D1%2Camp-auto-ads-adsense-holdout%3D0%2Cas-use-attr-for-format%3D0%2Cblurry-placeholder%3D1%2Camp-playbuzz%3D1%2CflexAdSlots%3D0%2Cfixed-elements-in-lightbox%3D1%2Camp-access-iframe%3D1%2Cios-scrollable-iframe%3D0%2Camp-list-viewport-resize%3D1%2CdoubleclickSraExp%3D0%2CdoubleclickSraReportExcludedBlock%3D0%2Campdoc-closest%3D1%2Camp-story-responsive-units%3D1%2Cios-fixed-no-transfer%3D0&el=u&s=Viewport%3A%20viewport%20has%20zero%20dimensions%0A%20%20%20%20at%20Sa%20(https%3A%2F%2Fcdn.ampproject.org%2Frtv%2F011908162035200%2Fv0.js%3A14%3A336)%0A%20%20%20%20at%20Oa.f.Ea%20(https%3A%2F%2Fcdn.ampproject.org%2Frtv%2F011908162035200%2Fv0.js%3A9%3A288)%0A%20%20%20%20at%20Oa.f.error%20(https%3A%2F%2Fcdn.ampproject.org%2Frtv%2F011908162035200%2Fv0.js%3A9%3A398)%0A%20%20%20%20at%20Fm.f.getSize%20(https%3A%2F%2Fcdn.ampproject.org%2Frtv%2F011908162035200%2Fv0.js%3A484%3A197)%0A%20%20%20%20at%20Fm.f.eg%20(https%3A%2F%2Fcdn.ampproject.org%2Frtv%2F011908162035200%2Fv0.js%3A502%3A224)%0A%20%20%20%20at%20Fm.f.tg%20(https%3A%2F%2Fcdn.ampproject.org%2Frtv%2F011908162035200%2Fv0.js%3A482%3A224)%0A%20%20%20%20at%20Y.f.fire%20(https%3A%2F%2Fcdn.ampproject.org%2Frtv%2F011908162035200%2Fv0.js%3A187%3A824)%0A%20%20%20%20at%20ul.f.Mc%20(https%3A%2F%2Fcdn.ampproject.org%2Frtv%2F011908162035200%2Fv0.js%3A403%3A466)%0A%20%20%20%20at%20wl%20(https%3A%2F%2Fcdn.ampproject.org%2Frtv%2F011908162035200%2Fv0.js%3A406%3A339)%0A%20%20%20%20at%20ul.f.bg%20(https%3A%2F%2Fcdn.ampproject.org%2Frtv%2F011908162035200%2Fv0.js%3A406%3A112)&r=https%3A%2F%2Fnews.google.com%2F&ae=viewport%20has%20zero%20dimensions&fr=%23webview%3D1%26cap%3Dswipe  

If I remember correctly, it's in the above string. I'm not sure how to parse it though. Are you able to read?

You can find all those examples in [stackdriver](https://pantheon.corp.google.com/errors/CPSA3a_89vCGkQE?time=P30D&filter=text:%22viewport%20has%20zero%20dimensions%22&project=amp-error-reporting).

**Comment by dvoytenko** [comment] 2019-08-20 19:51
The fragment is the `fr=` parameter. That doesn't give us much, except that it's a webview. Given the referrer, I believe this is GNews.

Can you check if this is Android or iOS?

**Comment by jridgewell** [comment] 2019-11-01 21:04
Dupe of https://github.com/ampproject/amphtml/issues/8926.

**Closed by jridgewell** 2019-11-01 21:04 UTC
Labels: P2: Soon, Type: Bug, WG: infra
