### ISSUE TITLE
[BUG] amp-youtube not loading properly inside amp-carousel

### ISSUE THREAD

**Issue by ybentz** [ampproject/amphtml#17380] opened 2018-08-09 03:32 UTC
## What's the issue?

My AMP pages have a decent amount of embedded YouTube videos (~30-40 on the heavier pages) nested in multiple `<amp-carousel>`. Since a placeholder image is loaded (and not lazy-loaded) for each player my pages take a long time to load + the first few videos are above or close to the fold so potentially 4-5 iframes are loaded.

To mitigate the performance hit, on page load I'm hiding the `<amp-youtube>` element and showing a thumbnail in a regular `<amp-image>`, and switch their visibility on click.

The problem is that the `<amp-youtube>` visibility change does not trigger the loading of the embedded iframe until the user scrolls the carousel, which finally causes the player to load.

Seems like the issue is caused by the lazy loading mechanism not triggering a check when an element changes its visibility which I would expect to happen.

## How do we reproduce the issue?

Codepen that reproduces the issue:
https://codepen.io/ybentz/pen/oMQeGp

Minimal code to reproduce the issue (basically describing the codepen):
1. Create a `<amp-carousel>` with a `<div>` that has a nested `<amp-youtube>` and `<amp-img>` in it.
2. Give some ids to the youtube player (e.g. `id="v1"`) and image (e.g. `id="img1"`)
3. To the player add a `hidden` attribute.
4. To the image add the click action: `on="tap:v1.show,img-1.hide"`

Steps to reproduce the issue:
1. On page load the image should be shown and the player hidden.
2. Click the image, a loading state will be shown but player is not loaded - the iframe is not present in the DOM.
3. Click the carousel navigation button, the player will now load.

## What browsers are affected?

All browsers

## Which AMP version is affected?

AMP version: 1533253141109
No idea if this is new or not, I just started working on AMP.

**Comment by aghassemi** [comment] 2018-08-09 16:47
@ybentz Thanks for the report. Root cause of this issue is: https://github.com/ampproject/amphtml/issues/17389 

For now, I suggest the following work-around based on the https://ampbyexample.com/advanced/click-to-play_overlay_for_amp-video/ sample.

I created a CodePen that applies that pattern in amp-carousel you can use as reference: 
https://codepen.io/aghassemi/pen/mjaVGG

**Comment by aghassemi** [comment] 2018-08-09 16:47
Closing as dup of #17389. Workaround documented above.

**Closed by aghassemi** 2018-08-09 16:47 UTC

**Comment by ybentz** [comment] 2018-08-09 18:02
Hey @aghassemi, thanks for the quick response!

Unfortunately the workaround you posted does not solve my problem, as my issue is related to performance where even if the user didn't click on any of the videos the `amp-youtube`'s iframes are still loaded into the DOM and since I have a few of them in or close to the fold the page takes too long to load.

What I tried to do is to have all the `amp-youtube` elements hidden by default, that way since they are lazy loaded the iframe should only load on user interaction and on page load/scroll only images are loaded giving the user a much faster and smoother experience.

If you have any other ideas I'd love to hear! Otherwise I guess I'll have to find a compromise for now and follow the root issue until it's fixed.

**Comment by aghassemi** [comment] 2018-08-09 18:14
@ybentz `amp-carousel` lazy-loads the iframes for amp-youtube. So only 1 or 2 would initially have the iframe and as user scrolls more would be loaded. I guess it is still not exactly what you want since as user scrolls without clicking, more and more iframes would load.

Another workaround to try (not sure if it will fix the issue but might be worth giving  a try) is using `amp-bind` to change the `class` on the elements instead of calling `.show .hide` to toggle visibility. It is possible that `amp-bind` does not suffer from the #17389 bug.

**Comment by ybentz** [comment] 2018-08-20 17:41
@aghassemi just wanted to update that I tried your `amp-bind` workaround suggestion with both `class` and `hidden` attributes and looks like it's also affected by the #17389 bug.
You can check it out in these 2 pens:
- changing the `hidden` attribute: https://codepen.io/ybentz/pen/eLYvWz
- changing the `class` attribute: https://codepen.io/ybentz/pen/mGdWQv
