### ISSUE TITLE
Allow `amp-list` to render from `amp-state` initially

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#15647] opened 2018-05-29 21:16 UTC
See https://github.com/ampproject/amphtml/pull/15613#issuecomment-392893925 for some background.

We should allow `amp-list` to render from `amp-state` data on load. This can help with showing "stale" data until remote data is available. It would be nice to also prefetch the endpoint so when a user-interaction ( e.g. "refresh" button) switches the `src` from `amp-state` to real endpoint, we would have fetched the data already and swap would be quick.

/cc @choumx  @ericlindley-g

**Comment by choumx** [comment] 2018-05-30 05:34
FYI #12002 is a dupe. Also https://github.com/ampproject/amphtml/issues/12372#issuecomment-351829104 has some related discussion. 

Basically we're wading deeper into client-side rendering -- might want to do some instrumentation on worst case scenarios. I'd hope you don't end up like I did with the amp-list binding evaluation thing. 😅

**Comment by pancham348** [comment] 2018-09-19 18:12
Hi, has this been implemented already ? If not, is there a workaround we could use for the time being ?

**Comment by aghassemi** [comment] 2018-09-19 20:37
@pancham348 Note yet, you could potentially use `<div placeholder>` to render some slate items until amp-list loads, similar to https://ampbyexample.com/components/amp-list/#using-a-placeholder-animation but imagine placeholder were real items.

**Comment by pancham348** [comment] 2018-09-20 17:17
ah that works! Thanks @aghassemi !

**Comment by demianrenzulli** [comment] 2019-01-31 18:04
This FR, in combination with [this bug](https://github.com/ampproject/amphtml/issues/14153), produces the following the following unintended effect:

[This demo page](https://amp-comm-snippets.glitch.me/cart/amp-list-test/) is a simplified version of a shopping cart page:

- amp-list loads an initial a list of items, that should refresh when "shoppingCart.items" changes.
- Clicking the "delete" button updates another state object: "cartItem", to save the user selection, before showing a confirmation dialog (and triggering a form POST request if the user accepts).
- When the state object is updated, a global re-render is triggered and, since "shoppingCart" object hasn't been initialized, the list is refreshed with an empty value.

To avoid this behavior, e-commerce sites initialize the shoppingCart object with a client-side request, therefore, duplicating the request made by amp-list to load the initial list of items.

Wondering if there have been any updates on this FR or the bug, and if is there any workaround to avoid this.

// cc @morsssss

**Comment by alanorozco** [comment] 2019-02-11 23:29
@aghassemi Should we close this in favor of static rendering per #20752? There's nowhere to track synchronization between the static tree and an `amp-state`, so maybe we could change this issue to track that instead?

@demianrenzulli It's possible that synchronizing bound state from an initial static render covers your use case. Leaving to @aghassemi to follow up.

**Comment by aghassemi** [comment] 2019-02-12 20:15
Idea here was that all the data is managed to `amp-state` and `src` of amp-list is never changed. This means changing the `src` of `amp-state` to fetch fresh data.

```
<amp-state src="example.com/data" [src]="example.com/data?[filters] id=myState>
<amp-list src="amp-state://myState">
```

**Comment by dbarcosb** [comment] 2019-03-08 21:14
+1 to have this. It would make things much easier

**Comment by cathyxz** [comment] 2019-03-08 22:34
We've slated this for a version 2 of amp-list and amp-render. If you have any sample code / use cases related to this FR, it would be very helpful to have them on this thread. =) 

Thank you!

**Comment by morsssss** [comment] 2019-03-11 16:00
Yay! @demianrenzulli do you have time to link to our code etc?

**Comment by demianrenzulli** [comment] 2019-03-11 23:04
1. On this [test page](https://amp-comm-snippets.glitch.me/cart/amp-list-test/empty-state.html), amp-list declares: [src]="shoppingCart.items". When you click on "Delete Item", it updates another state object: "cartItem", which triggers a global re-render. 
Since  shoppingCart.items is empty, when the list refreshes, it disappears.

2. This [test page](https://amp-comm-snippets.glitch.me/cart/amp-list-test/empty-state.html), is the same example, except that the "shoppingCart" sate object is initialized, with the same endpoint url as amp-list. 
In this case, clicking "Delete Item", updates "cartItem", which should trigger a global re-render, but the content of amp-list remains (as the "shoppingCart" has been initialized).

What's interesting of the last demo, is that I'm seeing only one request to the [endpoint url](https://amp-comm-snippets.glitch.me/cart/amp-list-test/list-response.json?__amp_source_origin=https%3A%2F%2Famp-comm-snippets.glitch.me), even when it's being called both by amp-list and amp-state. I'm wondering if this has been solved on another issue.

Let me know if you need anything else.

**Comment by demianrenzulli** [comment] 2019-03-16 00:10
Just to add more details to the previous comment, which sounds unrelated to this issue (but it's actually not):

If you have  amp-list with something like: [src]="shoppingCart.items", if this variable is not initialized, any state change in the page, will trigger a global re-render (due to #14153), which will make the list refresh with no content ([see demo](https://amp-comm-snippets.glitch.me/cart/amp-list-test/empty-state.html)).

We brought this example here, because if amp-list could be initialized from amp-state, that would be a way to avoid this.

On this [other demo](https://amp-comm-snippets.glitch.me/cart/amp-list-test/non-empty-state.html), though, both amp-list are initialized with the same url, but only one request is being sent. This also works for us. We were wondering if there was any recent change, to make only one request to be sent on cases like this.

**Comment by morsssss** [comment] 2019-03-20 11:16
By the way, we'd very much like it if AMP supported richer client-side rendering. I've heard that is a nongoal... is it still?

**Comment by alanorozco** [comment] 2019-03-20 17:58
@morsssss It's definitely a goal. We're trying to strike a good balance between UX (ie fastest rendering possible) and DevX (ie easiest model to code for). The assumption on #20752 about this approach being scrapped doesn't consider possible third alternatives. We're not set on the design for `amp-list`/`amp-render` yet.

**Comment by dritter** [comment] 2019-05-15 08:50
Our use case is slightly different from having the opportunity to display a better placeholder. We want to render the final state of the component based on a local state (that is currently only possible with a dummy request, just to trigger re-rendering the component).

To provide some more context:
We have several Microservices, and sometimes have the situation that we have the information for a component in one and the component itself lives in another one. Previously we transported that information/state across ESI-URLs, but that leads to a lot of cache buckets (which we want to to avoid).

Abstract example:
We have a header that contains a search input field. That input is the component I am talking about and lives in Microservice `A`.
Then we have a search results page (Microservice `B`) that embeds the header via ESI.
When the user searches for something, we send that request to the backend (so far, so good). That request comes back and we want to show the search query in the search box. Our previous approach resulted in a lot of cache buckets, as the search query is transported via ESI into Microservice `A`.

**Comment by aghassemi** [comment] 2019-06-19 23:30
related: https://github.com/ampproject/amphtml/issues/20752

**Comment by alankent** [comment] 2019-07-22 21:16
Example use case: The current amp-list causes page flicker as it refreshes the page after it is rendered. This is bad UX as the eyes are drawn the such flicker. You really want say a product list page to be pre-rendered server side so first display renders instantly, while still using an amp-list so you can change the sort order easily later.

You can do a trick like have two divs, one hidden one not, so the pre-rendered page is displayed first then hidden when the user changes sort order. But this adds developer maintenance overhead. Extra code is required, but worse two sections of the code have to stay in sync: you have to render the page server side plus create an amp-template that renders IDENTICAL markup (and keep both code in sync forever).

Using amp-state gets rid of the duplication. You inject the initial data into the amp-state, you render using amp-list and display the result on page load (zero duplicate code to render server side + via amp-template), then you can update sort orders and filtering easily. Ideally you update the amp-state, which triggers all amp-bind expressions and all amp-list templates on the page to update from a single API call.

**Comment by choumx** [comment] 2019-07-22 21:19
Good timing, #23465 will help with the flicker. :)

**Comment by alankent** [comment] 2019-07-22 21:30
Nice! But the flicker I was referring to is the delay in the amp-list going to the origin to do the API call to get the data to render the amp-list. I assume that is being looked at in amp-list v2...

**Comment by alankent** [comment] 2019-07-22 21:47
Oh, also, I quite like the idea of being able to bind fields out of amp-state to a cookie. The cookie then sets the amp-state on page load, and updates to the amp-state field update the cookie. Gives you state persistence across page boundaries (like a shopping cart, personalization preferences etc). That would then link in with amp-list using amp-state on page load as well. "Welcome back {username}".

**Comment by morsssss** [comment] 2019-10-21 16:53
Is there any news on this, @cathyxz or maybe @nainar ? I've heard this requested by one of the largest makers of AMP sites in the U.S., as they want to render content without the delay caused by a server call. And I heard it again today at the AMP Roadshow in Warsaw, from another sophisticated AMP site developer.

**Comment by alankent** [comment] 2019-10-21 22:39
One observation, https://amp.dev/documentation/examples/components/amp-list/?format=websites#rendering-amp-state documents how amp-list can be rendered from amp-state, but the documentation says that the amp-list is only rendered on state change. (The demo shows clicking a button updates AMP state which amp-list then renders.)

However, amp-list can fetch initial state using `src="https://..."` on page load from a URL, right? So on page load it will do the URL API call, return the content, render the template. But you cannot do this with AMP state. It treats "src=..." always as a URL.

It feels inconsistent that you can render URLs on page load but cannot render from AMP state on page load. But it also feels wrong inserting a bind expression into a `src=` attribute.

I understand there may be some race conditions to ensure the initial AMP state is initialized before bind expressions are evaluated on page load, but just wanted to suggest having a mode for: "trigger amp-list bind expressions on page load after AMP state has been initialized using `[src]=...` (and ignoring `src=...`)".

**Comment by choumx** [comment] 2019-10-22 15:32
That's right. The original syntax proposal was in #12002. 

```html
<amp-list src="amp://foo.bar">
<amp-state id="foo">{ bar: ... }</amp-state>
```

This way we'd keep the semantics of `[src]` to "only applied during state change".

**Comment by morsssss** [comment] 2019-10-23 19:37
That syntax strikes me as somewhat unnatural, since it looks to me like `amp://` is a protocol like HTTP. If only we had some sort of character or string that implied "this is a state variable", like `$` signals "this is a variable" in shell scripts or PHP. 

I'm sure you've already considered this, but the other option would be to provide another attribute for this. I see how that could be messier.

In any case, I trust that you've thought about the options already.  if people would like to prioritize this, however it's done, I think it would be a great feature!

**Comment by alankent** [comment] 2019-10-24 18:11
I agree Ben, the syntax is unusual. Normally URLs are `protocol`://`domainname` - and foo.bar looks like a domain name but is not. It may also violate URL syntax rules if a full expression goes there. 

I also think having to specify `src="amp://foo.bar"` and `[src]="foo.bar"` in this case is not intuitive. I was the same expression in both cases (that is, I really only want to specify `[src]=`). 

I would consider other options like "if [src]= is bound to state and the amp-list has no default markup specified, evaluate it on page load". Or an extra attribute to trigger load on page load.

I think also potentially related is if AMP State was ever connected to cookies (mentioned above). E.g. I would love to fetch a cookie via AMP state and set a cookie by setting AMP state. Allow something like `<amp-state id="blah" cookie="cookiename">` - this would allow state sharing across pages. (Alternatively, if an `<amp-script>` could be used to read or write cookies.) The relevant part to this request is it may be another reason to want to initialize the amp-list from state based on page load, as the cookie value can only be injected into the amp-list client side, and you want it on first page load.

**Comment by choumx** [comment] 2019-10-25 23:00
Linking a related FR for amp-state error UI (#16011).

**Comment by morsssss** [comment] 2019-10-30 21:23
We got another request for this feature from an experienced AMP developer for AndroidPolice in Warsaw last week!

Would we consider adding an attribute? Something like `<amp-list src-var="foo.bar">`? `<amp-list src-state="foo.bar">`?

If a new attribute makes `<amp-list>` too complex, I wonder about a convention like `<amp-list src="#foo.bar">` - since at least `#foo` feels a bit like an HTML selector that finds the object with ID `foo`, which is what we're actually doing.

**Comment by morsssss** [comment] 2019-11-18 22:11
Another way this request sometimes gets phrased is: "Allow <amp-list> JSON to load before the <amp-list> JS does." That way, when <amp-list> was ready to go, it could just use data that's already present.

**Comment by dritter** [comment] 2019-11-18 22:30
@morsssss Nailed it!

Trying to clarify my abstract example: We have that situation all the time, where we render an `amp-state` in the backend (rendered by Service `A`), and need to pick up that state in an `amp-list` (rendered by Service `B`). It is this way, because the information needed to generate the state are only known in Service `A`, but not `B`.
Our options with this Scenario are either choose to create an endpoint to provide that state (which is kinda odd), or to create an dummy request in the `amp-list` to being able to trigger rendering from a local state (ugly workaround). We went with the latter one..

So for my part, it is not necessary to have a special syntax to access the local state. It would be enough to take the state (which should already be present) to populate the list.

**Comment by choumx** [comment] 2019-11-19 01:28
> It may also violate URL syntax rules if a full expression goes there.

In this case, limiting the initial expression to only JSON paths (e.g. `foo.bar`) might be desirable. This means the `amp-list` only needs to wait for the corresponding `amp-state` element to be initialized before beginning rendering.

OTOH, binding expressions (e.g. `[text]="foo + bar"`) are not evaluated on page load. We could implement this, though it would mean an even slower initial render. 

However, expressions do allow rendering from a multiple `amp-state` data sources instead of just one (e.g. `[src]="foo.concat(bar)"`). Is this desired or overkill?

> That syntax strikes me as somewhat unnatural, since it looks to me like amp:// is a protocol like HTTP.

Correct, this would be a custom scheme/protocol. :) I think this is not too uncommon on the web. We can also drop the `//`.

```html
<amp-list src="amp-state:foo.bar">
```

**Comment by alankent** [comment] 2019-11-19 04:04
Good question on whether full expressions are overkill. For amp-list I would *suspect* yes. I can put the work into creating the JSON in the right format (using amp-script for complex logic). I am going to pull an array or similar out and pass that complex data structure to the amp-list.

I may even be happy with a single top level state name (no dots). As soon as you allow dots, do you allow `[n]` as well for arrays? The mustache template can pull apart the data structure.

    `data-amp-src-linkage="foo"` ?

That might also make it easier to find the `<amp-state id="foo">` to be loaded before evaluating the amp-list.

Would you support `[src]=` at the same time? I probably wouldn't. You specify a src (including using bind expression) or directly link it to a state member - one or the other.

(Side note, my understanding of URLs is even custom protocols are meant to follow the URI syntax. https://en.wikipedia.org/wiki/URL near the top documents the grammar. This is why `file:///` uses three leading slashes - first two are the authority prefix, the authority is an empty string (localhost), then the next slash starts the path.)

**Comment by choumx** [comment] 2019-11-19 15:59
> I may even be happy with a single top level state name (no dots). 

Only element IDs or JSON paths sound good.

> As soon as you allow dots, do you allow [n] as well for arrays?

amp-list does support non-array data via the `single-item` attribute.

> `data-amp-src-linkage="foo"` ?

I think I still prefer the plain `src` attribute since the semantics are clearer:

- `src`: The one and only data source.
- `[src]`: Only changes the value of `src` with `setState`. Otherwise, inert.

It also avoids combinatorial complexity introduced by a new attribute e.g. what happens when `src` and `data-amp-src-linkage` are both provided? What happens when there's a `[data-amp-src-linkage]` binding?

I think Ben's suggestion of a hash URL (e.g. `src="#foo"`) could work too. We can discuss in design review, of course.

**Comment by choumx** [comment] 2019-11-19 16:00
/to @samouri The first step to protocol adapters. :)

**Comment by alankent** [comment] 2019-11-19 17:00
Just musing out loud. If dot is supported but not `[n]` it feels kind of inconsistent - you cannot specify a path into all structures. (JSON can have nested arrays etc.) If a single identifier, then using the `src="#foo"` is not bad. I cannot think of anything better.

**Comment by choumx** [comment] 2019-11-19 20:11
I think we already support array indexing via dot syntax in JSON paths. E.g. `object.array.1.foo`.

Thanks for the discussion all.

**Comment by morsssss** [comment] 2019-11-19 20:22
Reading said discussion... I do still like this syntax:

`<amp-list src=#foo.bar">`

But I also like the latest from @choumx :

`<amp-list src="amp-state:foo.bar">`

as its verbosity decreases ambiguity.

**Comment by samouri** [comment] 2020-04-20 18:43
This feature landed in https://github.com/ampproject/amphtml/pull/27180.
Documentation is available at: https://amp.dev/documentation/components/amp-list/?format=websites#initialization-from-amp-state

**Closed by samouri** 2020-04-20 18:43 UTC
Labels: P2: Soon, Type: Feature Request, UI: Component: amp-list, UI: Customer: Developer, UI: Type: DevX, WG: ui-and-a11y
