### ISSUE TITLE
Rendering artefact from next slide on page

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#28922] opened 2020-06-17 14:03 UTC
- [Repro URL](https://www-inquirer-com.cdn.ampproject.org/c/s/www.inquirer.com/health/visual/philadelphia-yellow-phase-what-does-it-mean/?outputType=amp-story)
- Repros on Chrome on Android (not on Desktop)
- Happens on multiple pages of the Story
- See the square overlapping the text that looks like a window into the next page.
![Screenshot_20200617-070042](https://user-images.githubusercontent.com/89679/84907961-b51ebf80-b068-11ea-8deb-ed5a115b32bc.png)

**Comment by Ichigo3d** [comment] 2020-06-17 15:44
Hello. I tried to reproduce it under AMP v. 2006050512000, Android 7.1.1, real device: Motorola G play, Chrome 83.0.4103.101, but I can't reproduce it. Could you send me more information about under which versions it was happened?
<img width="1178" alt="Screen Shot 2020-06-17 at 8 43 04 AM" src="https://user-images.githubusercontent.com/37351864/84919290-9a534780-b076-11ea-9c33-7ead5a7e1004.png">

**Comment by gmajoulet** [comment] 2020-06-17 16:12
cc @ampproject/wg-stories 
@Enriqe can you look into this one?

**Comment by cramforce** [comment] 2020-06-17 17:00
I'm on almost the same Chrome (.106) on a Pixel 4XL

**Comment by Enriqe** [comment] 2020-12-16 21:56
Sorry for the delay, didn't have access to an Android. Just tried on a Pixel 4a with Chrome 87.0.4280.101 and I'm not able to repro.

Is someone still able to repro this?

**Comment by processprocess** [comment] 2020-12-16 22:08
> Sorry for the delay, didn't have access to an Android. Just tried on a Pixel 4a with Chrome 87.0.4280.101 and I'm not able to repro.
> 
> Is someone still able to repro this?

Not able to repro.
Tested on Pixel3 and iPhone11

**Comment by Enriqe** [comment] 2020-12-16 22:09
Closing for now, feel free to reopen if you are able to repro!

**Closed by Enriqe** 2020-12-16 22:09 UTC
Labels: P1: High Priority, Type: Bug, WG: stories
