### ISSUE TITLE
amp-next-page bugs - fallback/placeholder rendering

### ISSUE THREAD

**Issue by andyblackwell** [ampproject/amphtml#30641] opened 2020-10-13 17:18 UTC
## What's the issue?

We first noticed yesterday that pages pulled in via amp-next-page (both v0.1 and v1.0) are rendering very buggy. Ad placeholders are behind and stretched across the entire length of the article, and image fallback/placeholders are not being removed and stacked above the image. In one case a modal is also auto-popping (which shouldn't), and isn't dismissable. This all only seems to happen when hosted on google's cdn.

## How do we reproduce the issue?

emulate mobile and load these urls and scroll down until the first amp-next-page loads to reproduce:

https://www.google.com/amp/s/amp.travelawaits.com/2547955/The-Best-Greek-Islands-To-Visit/
v0.1 ^ can see the ad/image issue here

https://www.google.com/amp/s/www.eastmojo.com/nagaland/2020/10/05/manipur-covid-19-death-count-climbs-to-74-with-3-more-cases
v1.0 ^ found in the wild, also can see the ad/image issue

https://www.google.com/amp/s/amp.cinemablend.com/news/2556691/why-one-matrix-4-actor-thinks-lana-wachowski-will-change-the-industry
v0.1 ^ ad/image issues, and this one also oddly auto-pops a modal on next-page (which shouldn't happen) that you also can't dismiss

## What browsers are affected?

All browsers

## Which AMP version is affected?

We first noticed yesterday, unsure if it was happening prior to yesterday.
current AMP version: 2009252320001

**Comment by andyblackwell** [comment] 2020-10-13 17:20
You can see below the grey ad placeholder expands outside the ad div to the top and bottom of the article, rendering behind it. 

![Screen Shot 2020-10-13 at 12 17 25 PM](https://user-images.githubusercontent.com/372590/95894111-428bcb00-0d4e-11eb-9d92-433454c68d0e.png)

**Comment by andyblackwell** [comment] 2020-10-13 20:16
Looks like the amp version I'm getting is different now: 2010010034001
And things are looking normal again for me as well

Any chance the buggy version is just running at a percent of traffic and will come back? Like it's being tested and may be merged in later?
Or does this newer version # mean we're good moving forward?
Is there a way to see if 2009252320001 is still being used on live traffic?

**Comment by zhouyx** [comment] 2020-10-13 20:42
I'm not aware of any [changes](https://github.com/ampproject/amphtml/compare/2009252320001...2010010034001) to `<amp-next-page>` or ad placeholder between 2009252320001 and 2010010034001

While 2010010034001 is the new Stable version, 2009252320001 will be promoted to our [LTS](https://github.com/ampproject/amphtml/blob/master/contributing/lts-release.md) version soon, so it will be used on live traffic by sites that choose to use LTS. 

Let me test with 2009252320001 version

**Comment by zhouyx** [comment] 2020-10-13 23:44
@andyblackwell I tried again with `2009252320001` version, still couldn't reproduce the issue.

As shown, the ad size is correct, and the fallback placeholder has size 0. 

![image](https://user-images.githubusercontent.com/5419904/95927320-3e25d900-0d73-11eb-9889-85c89de62535.png)

**Comment by zhouyx** [comment] 2020-10-13 23:45
If possible, can you opt in to `012009252320001` version via the Advanced tab in https://www-eastmojo-com.cdn.ampproject.org/experiments.html
And verify if that issue still exist. Thank you

**Comment by andyblackwell** [comment] 2020-10-14 14:33
Getting the same as you, is working fine now on both v0.1 and v1.0. Is strange that it was broken for a day, but fixed itself within a couple hours of my report 🤷 
We had several reports of the broken behaviour, so it wasn't just me. Maybe there was a bad cached version out there or something that happened to get cleared?

Guess we can close this out

**Comment by zhouyx** [comment] 2020-10-15 16:42
Glad to hear the issue is gone. Agreed this very strange. I checked our release history, only `2009190410000` was out for only one day (from 9/29-9/30), but the time didn't match. 

Definitely let us know if we're seeing this again. Thanks

**Comment by Cauchon** [comment] 2020-12-10 17:07
@zhouyx We are seeing this pop up on CNET, ZDNet and Gamespot sites.

**Comment by zhouyx** [comment] 2020-12-10 18:57
Hi @Cauchon it looks like the placeholder has the correct size in the screenshot. Could you clarify the issue. Thanks

**Comment by Cauchon** [comment] 2020-12-10 19:30
Thanks for the reply, Yuxuan. @andyblackwell is probably best to explain the issue we're both seeing with amp-next-page. He put more details in #23983 - basically all ad placeholders are the entire height of the amp-next-page doc.

**Comment by zhouyx** [comment] 2020-12-10 20:17
@andyblackwell do you see the issue consistently? I couldn't reproduce the issue, the ad size seems correct to me. 
Could you provide a url or the steps to reproduce. Thanks

**Comment by andyblackwell** [comment] 2020-12-10 20:21
It looks to be fixed for me now and seeing it fixed on CNET, was there any chance an amp deploy in the last few hours? That's what fixed it last time, and I'm suspicious there's an underlying caching issue that a fresh deploy fixes.

**Comment by zhouyx** [comment] 2020-12-10 20:27
@estherkim any thoughts?

**Comment by Cauchon** [comment] 2020-12-10 20:36
For me, it does seem to be mostly fixed on CNET but some of my coworkers are still seeing the issue.

I am able to reproduce on ZDNet inconsistently: https://www.google.com/amp/s/www.zdnet.com/google-amp/article/safer-networks-at-home-working-remotely-in-2021/

**Comment by estherkim** [comment] 2020-12-10 20:38
Re: fresh deploys - we didn't release anything today.

The CNET screenshot shows `cdn.ampproject.org/rtv/012011252111002` which matches the stable version that was deployed yesterday, `2011252111002`

**Comment by zhouyx** [comment] 2020-12-10 20:50
Hmm this is really weird. 

>I'm suspicious there's an underlying caching issue that a fresh deploy fixes.

I agree this could be the reason. Another thing I realize is that the amp-loader script was loaded lazily, wonder if there could be a race condition between the two scripts. 
Have we tried disabling cache in browser and can we reproduce the issue?

**Comment by Cauchon** [comment] 2020-12-11 21:12
@zhouyx Confirming that if I do still see the issue occurring if I disable cache via the Chrome DevTools --> Network tab --> Disable cache.

<img width="600" alt="Screen Shot 2020-12-11 at 1 11 27 PM" src="https://user-images.githubusercontent.com/3600309/101955340-79e1f100-3bb2-11eb-9f97-361ea383984b.png">

**Comment by andyblackwell** [comment] 2020-12-17 21:20
we started seeing this again today, FYI

**Comment by Cauchon** [comment] 2021-01-05 20:46
Seeing it again on CNET as well.

**Comment by andyblackwell** [comment] 2021-01-05 21:20
Same, happening again for us as well

**Comment by amclarenRV** [comment] 2021-01-05 22:23
hey @andyblackwell I read this related/ connected post and wanted to check if its a possible cause in our case

https://github.com/ampproject/amphtml/pull/25629

**Comment by colintdf** [comment] 2021-01-06 15:20
We have had big problems with AMP Next Page on our sites as we've rolled out starting at the end of last year. The Google Cached version of the pages seem to be ignoring the next-page-hide tags in some instances and removing/changing styles on next pages causing lead images to break outside of the site rails.

The functionality is fine on our own hosted versions of the pages so something in the Google Caching is breaking the functionality. The problem also doesn't appear viewing the pages via desktop browsers but does affect iPhone Safari and Android Chrome in the same way.

We're on version 1.0 and noticed the problems mostly yesterday (5th January) as we rolled it out to our biggest site. The problems were also present on our initial launch site and we're unsure as to when they started happening.

We have now disabled amp-next-page while this is investigated however here are a couple of screen recordings of the issue.

Hosted: https://user-images.githubusercontent.com/23098228/103785056-a9a9da80-5032-11eb-8a5b-5e31a35cef36.mp4

Google Cached: https://user-images.githubusercontent.com/23098228/103785081-b0385200-5032-11eb-9aab-de9fb20166e3.mp4

**Comment by andyblackwell** [comment] 2021-01-06 17:06
@amclarenRV since I first saw this in early/mid October, I'd guess those later changes aren't related. I'm still leaning more toward caching issues, since the bugs only happen on the google cdn and seem to disappear for a while after a new amp deploy.

**Comment by kristoferbaxter** [comment] 2021-01-14 15:17
Closing issue in favor of #31951.

The Google team has temporarily rolled back a release of module scripts from the Google AMP Cache, we'll use #31951 to track fixing the underlying issue.

**Closed by kristoferbaxter** 2021-01-14 15:17 UTC
Labels: Component: amp-next-page, Type: Bug
