### ISSUE TITLE
amp-list causes line-break when used in text block (paragraph)

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amphtml#18920] opened 2018-10-24 13:56 UTC
We have a tool tip that is an `amp-lightbox` inside a text block, such as a paragraph. Here are two examples that we emulate.

A. Inline lightbox
See "Blake Bortles"
https://www.washingtonpost.com/sports/2018/10/21/jaguars-bet-blake-bortles-lost/?utm_term=.c05062fec866

B. Inline footnote
see "1" after this text: "Google constantly talks about the pile of money it’s paying to Apple and others,"
https://www.bloomberg.com/view/articles/2018-09-28/apple-looks-down-on-ads-but-takes-billions-from-google?srnd=premium
with this target:
https://www.bloomberg.com/view/articles/2018-09-28/apple-looks-down-on-ads-but-takes-billions-from-google?srnd=premium#footnote-2

Here are two solutions.

1. **Single** `amp-list` and **multiple** `templates`:
https://afdsi.org/test/_amp-list-tooltip-2/

2. **Multiple** `amp-list` and **single** `template`
https://afdsi.org/tooltip/tooltip-23/

the preferred solution is #2.
A single template uses less space, and multiple lists are easier to maintain and reuse than a single hierarchical list.

The issue is that each `amp-list` generates a `<div>` that causes a line break when used in a text block like a paragraph `<p></p>`.

For example, when using amp-mustache with amp-list, a `{{term}}` in `<span>` forces a line-break, as shown in #2.

We have tried various CSS methods to keep-together but all fail.
The consequence is that we cannot create a `<p>` using multiple `<span>` for different URLs loaded from multiple `amp-list`.

Our request is that `amp-list` generate an inline span block rather than the div block that forces the new-line-break.

/to @aghassemi @choumx @cathyxz @sebastianbenz

**Comment by aghassemi** [comment] 2018-10-25 17:16
@jaygray0919 It is possible to make the inline case work by setting the parent of `amp-list` to `display:inline-block` and giving it a fixed `width`.

`amp-list` never resizes `width` by design (would cause content shifting) so either its `inline-block` parent must have a set width or list itself must have one.

For your example, I understand why the dynamic part of the overlay needs to be in the `amp-list` but why do the links (1, 2,  etc..) are in an amp-list? You can reuse teh same amp-lightbox and amp-list for the overkays and change the source based on what footnote was clicked dynamically via amp-bind.

Hope this helps.

**Comment by aghassemi** [comment] 2018-10-25 17:16
Closing per comment above.

**Closed by aghassemi** 2018-10-25 17:16 UTC

**Comment by jaygray0919** [comment] 2018-10-25 20:02
@aghassemi we'll try your approach and share results.
The numbers (1, 2, 3 ...) are the links to the `amp-lightbox`.
Alternatively, we may take the approach used on the Washington Post where the `{{term}}` is the link to the `amp-lightbox`.
In either case, we need to make certain that each **item** - from an `amp-list` and displayed in an `amp-lightbox` - does not cause a line-break.
we'll try your suggestion and report back.
