### ISSUE TITLE
Add iBILLBOARD Adserver in AMP

### ISSUE THREAD

**Issue by Internet-BillBoard** [ampproject/amphtml#3278] opened 2016-05-20 12:12 UTC
Hi,
According to the technical specifications we're able to implement iBILLBOARD AdServer to the AMP registered subjects, and so we want to proceed with it.
Can we move on to signature of the CLA, or is there some further information required?

**Comment by rudygalfi** [comment] 2016-05-23 17:31
@Internet-BillBoard If you are planning to contribute an implementation according to https://github.com/ampproject/amphtml/blob/master/ads/integration-guide.md, then please submit a pull request. You can sign the CLA and the travis check on the pull request should go green once you've signed.

/cc @kashyapnitin

**Comment by jasti** [comment] 2016-09-03 15:41
Dupe of #4628. closing.

**Closed by jasti** 2016-09-03 15:41 UTC
Labels: 3P, INTENT TO IMPLEMENT, Related to: Ads, Type: Feature
