### ISSUE TITLE
amp-form does not set class "user-valid" unless a field is first invalid

### ISSUE THREAD

**Issue by devvercer** [ampproject/amphtml#11710] opened 2017-10-17 03:26 UTC
## What's the issue?

I have a form with two required fields. When the user fills both fields the form does not have the "user-valid" class added.

## How do we reproduce the issue?

This pen shows the issue:

https://codepen.io/vercer/pen/eGQeBz

1 - Enter text in both fields and the inputs turn green but the form does not.
2 - Remove text from one field and the input and the form become green.
3 - Add text again and both the input and the form turn green.

I would expect step one to result in the form turning green.

## What browsers are affected?

Macbook Chrome 61

## Which AMP version is affected?

Not sure.

**Comment by cvializ** [comment] 2017-10-17 20:48
This is the intended behavior, since the `.user-valid` `.user-invalid` classes polyfill the user-pseudos feature in the [future CSS Selectors 4 spec](https://drafts.csswg.org/selectors-4/#user-pseudos). If you want validity state regardless of user interaction, you can use the CSS3 `:valid` and `:invalid` selectors.

I'll close this for now. Feel free to comment again if I misunderstood your use-case.

**Closed by cvializ** 2017-10-17 20:48 UTC
