### ISSUE TITLE
AMP Validator reporting Issue on <script src="https://cdn.ampproject.org/v0/amp-ad-0.1.js" custom-element="amp-ad" async></script>

### ISSUE THREAD

**Issue by amans1690** [ampproject/amphtml#3807] opened 2016-06-28 16:35 UTC
## Short description of your issue:
AMP Validator reporting Issue on `<script src="https://cdn.ampproject.org/v0/amp-ad-0.1.js" custom-element="amp-ad" async></script>`

The error message as reported by AMP Validator is 

> The tag 'script' is disallowed except in specific forms

.

## How do we reproduce the issue?
URL: http://m.timesofindia.com/amp_articleshow_test/52948167.cms#development=1
See the console tab in developer tools in chrome

@Gregable You can open the url on chrome 
1. for opening the url you have to first set the user agent in chrome dev tools to iphone4 or nexus4/5
2. Then try to access the url

I have already looked to the advice provided by in the previous issues but that wasn't the issue here. Please look into this.

FYI: I have included the `<script src="https://cdn.ampproject.org/v0/amp-ad-0.1.js" custom-element="amp-ad" async></script>` in the head. 
If I remove this piece of code the AMP Validator successfully validates the amp document.

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 1466185787499

**Comment by jridgewell** [comment] 2016-06-28 17:55
`<amp-ad>` is special in that you do not have to explicitly include it on the page for it to be loaded.

@cramforce, should we allow users to explicitly include it? If so, @zhouyx, we'll need to detect if it's already included.

**Comment by rudygalfi** [comment] 2016-06-28 18:20
The current documentation calls for this in usage of `amp-ad`. Seems like the validator needs to accept this?

**Comment by amans1690** [comment] 2016-06-28 19:03
@rudygalfi You are correct. That is why I included `<script src="https://cdn.ampproject.org/v0/amp-ad-0.1.js" custom-element="amp-ad" async></script>` in the head tag.

@jridgewell It is mentioned in [https://www.ampproject.org/docs/reference/amp-ad.html](https://www.ampproject.org/docs/reference/amp-ad.html) under **Required Script** field.
This confuses the developers.

I have removed the explicit include i.e. `<script src="https://cdn.ampproject.org/v0/amp-ad-0.1.js" custom-element="amp-ad" async></script>` in the head tag and ran the validator with ad units. AMP Validator successfully validates and ad units also rendered.

Please clear this confusion out in docs.
 
@jridgewell @rudygalfi Thanks for helping out

**Comment by jridgewell** [comment] 2016-06-28 19:48
Dupe of https://github.com/ampproject/amphtml/issues/3802#event-706841605.

**Closed by jridgewell** 2016-06-28 19:48 UTC
Labels: Related to: Documentation, Type: Discussion

**Comment by Gregable** [comment] 2016-06-28 19:49
Copying my comment from the other thread:

> Ah, yes. The validator doesn't know about the amp ad extension. In the past, the code was built into the main runtime, but it appears that it was refactored recently into a separate file (https://github.com/ampproject/amphtml/pull/2902).
> 
> As a temporary workaround, removing the `<script src="https://cdn.ampproject.org/v0/amp-ad-0.1.js" custom-element="amp-ad" async></script>` for now should work. It would appear that the runtime will late load the extension anyway.

**Comment by Gregable** [comment] 2016-06-28 19:50
Oops, I misread which one you duped where.
