### ISSUE TITLE
Web Vitals: tracking LCP using amp-analytics not working well

### ISSUE THREAD

**Issue by buihoanghai** [ampproject/amphtml#37072] opened 2021-11-30 03:57 UTC
### LCP was sent to GA less than CLS
Expected LCP and CLS should be the same amount of events but they are not(2mil vs 12mil)
![image](https://user-images.githubusercontent.com/6602376/143982876-5f9d4558-6e5a-4503-97e4-cb19c0b4ab18.png)

The tracking for LCP send to GA is usually in pending status. 
![image](https://user-images.githubusercontent.com/6602376/143982617-58dc3d29-fe71-4408-8d5b-9ec0553accc3.png)

When I try to add LCP into extraUrlParams in the CLS tracking also got same issue
`
        "cls": {
                  "on": "visible",
                  "request": "event",
                  "vars": {
                    "eventCategory": "cwv",
                    "eventAction": "cwv_discovery_cls",
                    "eventLabel": "cumulative_layout_shift",
                    "eventValue": "$CALC(${cumulativeLayoutShift}, 1000, multiply)"
                    },
                    "extraUrlParams": {
                          "ni":"true",
                          "lcp": "$CALC(${largestContentfulPaint}, 1, multiply, true)"
                    }
                },
`

### LCP spike
The average event value for LCP has been jumped up a lot since Nov 16
![image](https://user-images.githubusercontent.com/6602376/143977958-bdfecaae-a49c-489b-a5a5-75071d88065e.png)

I think only Chromium-based browsers are impacted
![image](https://user-images.githubusercontent.com/6602376/143983068-318ba626-553a-42fb-a37e-c0e280928825.png)

### Reproduction Steps

Our config JSON for CWV tracking

`              "cls": {
                  "on": "visible",
                  "request": "event",
                  "vars": {
                    "eventCategory": "cwv",
                    "eventAction": "cwv_discovery_cls",
                    "eventLabel": "cumulative_layout_shift",
                    "eventValue": "$CALC(${cumulativeLayoutShift}, 1000, multiply)"
                    },
                    "extraUrlParams": {"ni":"true"}
                },
                "lcp": {
                  "on": "visible",
                  "request": "event",
                  "vars": {
                    "eventCategory": "cwv",
                    "eventAction": "cwv_discovery_lcp",
                    "eventLabel": "largest_contentful_paint",
                    "eventValue": "$CALC(${largestContentfulPaint}, 1, multiply, true)"
                  },
                    "extraUrlParams": {"ni":"true"}
                },
                "fid": {
                  "on": "visible",
                  "request": "event",
                  "vars": {
                    "eventCategory": "cwv",
                    "eventAction": "cwv_discovery_fid",
                    "eventLabel": "first_input_delay",
                    "eventValue": "$CALC(${firstInputDelay}, 1, multiply, true)"
                    },
                    "extraUrlParams": {"ni":"true"}
                }
    `

### Browser(s) Affected

Chrome

**Comment by samouri** [comment] 2021-12-02 19:32
cc @jridgewell

**Comment by jridgewell** [comment] 2021-12-02 21:54
There are two parts to this

> Expected LCP and CLS should be the same amount of events but they are not(2mil vs 12mil)

This should be fixed by https://github.com/ampproject/amphtml/pull/37007. The issue is that we didn't mark the LCP signal until the document became invisible (either tab in the background, or closed the AMP viewer, etc). Now, we mark the signal immediately, making it available for analytics.

> The average event value for LCP has been jumped up a lot since Nov 16

The graph looks to me to show an increase on Nov 18, which has increased. We didn't make any changes on Nov 18th (though we did on the 16th, but that's not how I'm reading your graph). Chrome 96 was also released on Nov 16th, which I think is the more likely suspect. It takes a few days for Chrome users to upgrade their browsers, which means it's possible we saw this starting to affect metrics on the 18th+.

**Comment by jridgewell** [comment] 2021-12-07 22:58
I think I've tracked this down to https://github.com/ampproject/amphtml/pull/36273, which change the `timeOrigin` we use to calculate the LCP value. I mistakenly changed a `Date.now()` to `performance.now()`, but this creates an issue when we calculate an epoch-relative delta against a pageload-relative `timeOrigin`. Fix in #37144.

**Closed** 2021-12-07 23:35 UTC
Labels: Type: Bug, WG: performance

**Comment by jridgewell** [comment] 2021-12-10 17:25
The fix was rolled out to stable in 2111242025001, see #37076
