### ISSUE TITLE
Events to distinguish bookend share providers in amp story

### ISSUE THREAD

**Issue by Princetp634** [ampproject/amphtml#28574] opened 2020-05-26 16:37 UTC
## Describe the new feature or change to an existing feature you'd like to see
Hi currently It become to difficult to track which share provider user clicked on bookend amp story.Please mark some events for the same

## Describe alternatives you've considered
If events for those are not possible, then do developers create custom share providers so that we can manually set tracking data for them by binding the share provider element with "data-vars-variableName".Which later can be consumed when event fires.

**Comment by gmajoulet** [comment] 2020-06-01 22:39
@Enriqe do you know if we have any way to track sharing from the bookend or even the desktop sharing menu?

cc @ampproject/wg-stories

**Comment by gmajoulet** [comment] 2020-06-02 15:22
@zhouyx confirmed that using `data-vars` would work, Enrique do you know if we could automatically add `data-vars=<provider>` attribute for people to track which sharing option was clicked?

**Comment by zhouyx** [comment] 2020-06-03 00:13
Somewhat related to #28636

The `data-vars-*` attribute needs to be applied to the event target for analytics to recognize. 
Not sure how the share button is implemented in AMP, but I think this can be a generic <amp-social-share> feature to auto generate the `data-vars-*` attribute if not present.

**Comment by Enriqe** [comment] 2020-06-03 15:25
I think we should be able to add the `data-vars-*` attribute when we are building the share providers, although I don't think this will be possible when using native system sharing (we use whatever providers the OS provides, which would be out of our reach, I think).

**Comment by gmajoulet** [comment] 2020-06-03 18:49
That sounds good, it would still work for bookend sharing. Do you know how to work around the fact that these sharing elements are in a shadow DOM?

**Comment by tarun7886** [comment] 2020-12-22 08:51
Is native sharing button trackable using amp-analytics? 
Since it's inside the shadow DOM, how can I get the selector string for that share button to add it into amp-analyitcs. 
Current selector for native share button
`document.querySelector(".i-amphtml-system-layer-host").shadowRoot.querySelector("button.i-amphtml-story-share-control")`

**Comment by mszylkowski** [comment] 2021-12-14 19:00
Given that the bookend is deprecated, I'll close this issue. The desktop sharing providers allow you to add `data-vars` as explained above.

**Closed by mszylkowski** 2021-12-14 19:00 UTC
Labels: P3: When Possible, Type: Feature Request, WG: stories

**Comment by AlinaaDri** [comment] 2021-12-15 10:08
Heu guys! I have problev with amp story after reloading page.

I don't have  document.querySelector('.i-amphtml-system-layer-host');/ It equals to null.

I work with Angular 11. And I try ti find this element in ngAfterViewChecked.

I repeat that this bug appears ONLY after reloading/

PLS help me to fix it
