### ISSUE TITLE
amp-form how to remove <div submit error>

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#7688] opened 2017-02-21 16:06 UTC
I am using amp-form and amp-bind to realize a [quiz](https://github.com/ampproject/amp-by-example/pull/640). 

I have an amp-form with 4 amp-selectors. If all the answers are right, I am showing a comment. If one or more answers are wrong, I am showing a button:
```
<div submit-error>
    <template type="amp-mustache">
      <input type="reset" value="Try again" on="tap:AMP.setState(currentQuestion=1)">
    </template>
  </div>
```
by clicking on this button, the first question is shown (via amp-bind) and that works, but the "Try again" button doesn't go away. 
Once a form has gone into error, by showing `<div submit-error>`, there is no way of starting again and remove that tag. I could achieve this by `amp-bind` and a variable but I feel like this is a pattern and there should be a way to solve it.

@mkhatib WDYT?
@ericlindley-g @choumx FYI

**Comment by sebastianbenz** [comment] 2017-02-21 16:08
+1 I've encountered this problem also a few times.

**Comment by aghassemi** [comment] 2017-02-21 18:53
I think a feature request such as `amp-form should remove rendered failure and success messages on form onreset event` makes sense and should solve your use-case. If there are cases that this does not cover, then we can also consider exposing a method in addition.

If you agree with the above, let's file an issue.

**Comment by jridgewell** [comment] 2017-02-21 19:07
Don't we already have a request for a form `clear` action? This sounds like clear should take some initial state.

**Comment by aghassemi** [comment] 2017-02-22 01:45
@jridgewell https://github.com/ampproject/amphtml/issues/7368
If we do the "hide rendered messages on `onreset` event" then `clear` action can just call the `form.reset()` (which also handles initial state case - e.g. goes back to whatever `value` was before user changed it). We should probably call it `reset` instead of `clear`.

**Comment by jridgewell** [comment] 2017-02-22 18:46
Closing as a dupe of #7368.

**Closed by jridgewell** 2017-02-22 18:46 UTC
Labels: Category: User Input, Type: Feature Request
