### ISSUE TITLE
amp-carousel does not accept self-closing amp-img

### ISSUE THREAD

**Issue by zipswich** [ampproject/amphtml#17456] opened 2018-08-12 03:45 UTC
## What's the issue?
Using self-closing amp-img passes AMP validation, but makes prev and next buttons disappear.

## How do we reproduce the issue?
Use a self-closing amp-img like the following:
`<amp-img layout="responsive" height="300" width="450" src="~/Content/images/foo.png"/>
`
## What browsers are affected?
Chrome on Windows 10 PC.

## Which AMP version is affected?
The latest: amp-version="1533253141109"

**Comment by nainar** [comment] 2018-08-14 18:30
https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#html-tags - dictates that `<amp-img>` is not a self closing tag. 

However you are right https://thread-dibble.glitch.me/ currently validates. 

Paging @Gregable and @honeybadgerdontcare for thoughts?

Which of the following makes sense:
1. Allow `<amp-img>` to be self closing?
2. Invalidate self closing `<amp-img>`?
3. Retain the current status quo?

**Comment by zipswich** [comment] 2018-08-14 20:05
Edited the original post to show the code be cause I have just realized that the code was no shown because the line was not marked as code.

**Comment by Gregable** [comment] 2018-08-14 20:10
> Which of the following makes sense:
> 1. Allow `<amp-img>` to be self closing?

HTML5 specifies that self-closing tags don't exist. HTML5 parsers that see `<foo />` parse this as an error and treat it the same as `<foo>`, so it will have no effect.

> 2. Invalidate self closing `<amp-img>`?

I would have liked for our validator to require strict html parsing, but amp made a decision early on to try to accept parsing errors and correct them, rather than rejecting the document. We do so as closely as possible to HTML5 error-handling rules. Plenty of existing currently valid documents use self-closing notations on tags. If we invalidated such a syntax, it would break a lot of pages, which makes this largely impossible.

> 3. Retain the current status quo?

I think that's about all we can reasonably do at the validation phase.

**Comment by nainar** [comment] 2018-08-14 20:14
@Gregable thanks for the insight here. In that case `<amp-carousel>` not working properly with a self closed `<amp-img>` is working as intended. 

I am closing the issue as such. Thank you for filing the issue @zipswich. Unfortunately, this doesn't seem like something we can fix realistically.

**Comment by Gregable** [comment] 2018-08-14 20:15
I'll add the other possibility:

Have the AMP Cache error rewrite `<foo />` as `<foo></foo>`, effectively taking a different error-handling strategy than HTML5 spec and what browsers implement.
 
This won't work either, because it will mean that the browser will see the document on origin as different from cache, and this can cause rendering issues. Most developers test documents on origin, and if the cache behavior differs, they consider this a cache bug (which it is).

**Closed by nainar** 2018-08-14 20:14 UTC
Labels: Category: Presentation, Type: Bug

**Comment by zipswich** [comment] 2018-08-14 21:48
Thanks a lot for looking into this.  It seems <amp-carousel> does abide by  "a decision early on to try to accept parsing errors and correct them, rather than rejecting the document." if I understand it correctly.
