### ISSUE TITLE
amp-img fails to load within amp-list within amp-carousel

### ISSUE THREAD

**Issue by 10xjs** [ampproject/amphtml#10706] opened 2017-07-28 23:00 UTC
## What's the issue?

`amp-img` elements can't be nested within `amp-list` within `amp-carousel`. It appears that an `amp-img` tag is never detected as visible in this structure and is therefore never loaded.

## How do we reproduce the issue?

The following markup reproduces the issue
```html
  <amp-carousel width="auto" height="200" layout="fixed-height" type="slides">
    <div>
      <amp-list width="auto" height="200" layout="fixed-height" src="https://ampbyexample.com/json/examples.json" class="m1">
        <template type="amp-mustache" id="amp-template-id">
          <amp-img src="https://unsplash.it/200" width="200" height="200"></amp-img>
        </template>
      </amp-list>
    </div>
  </amp-carousel>
```

See: https://jsbin.com/beyoruz/edit?html,output

## What browsers are affected?

All browsers appear to be affected.

## Which AMP version is affected?

Discovered on version 1501206447946. I don't suspect this is version-specific.

**Comment by aghassemi** [comment] 2017-07-29 04:00
@10xjs, duplicate of https://github.com/ampproject/amphtml/issues/4405
Pleas see https://github.com/ampproject/amphtml/issues/4405#issuecomment-318204399 for a work-around.

**Closed by aghassemi** 2017-07-29 04:00 UTC
