### ISSUE TITLE
DoubleClick implementation ignoring A4A attribute

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#6061] opened 2016-11-07 19:01 UTC
The "data-use-beta-a4a-implementation=true" attribute when used with the (Doubleclick)[https://github.com/ampproject/amphtml/blob/master/ads/google/doubleclick.md] implementation worked fine last week but starting today an error message is instead thrown:
"Uncaught Error: Unknown attribute for doubleclick: useBetaA4aImplementation"

**Comment by tdrl** [comment] 2016-11-07 19:09
The issue is the CDN check.  The [repro URL](http://www.mynet.com/haber/amp/guncel/asit-yagmuru-tehlikesi-yasanan-mardinde-toz-firtinasi--2697795-1) is at www.mynet.com.  The A4A initialization code looks at that and says, "not on cdn.ampproject.org; sorry" and it kicks responsibility back to 3p.  The 3p `doubleclick.js` doesn't recognize the `data-use-beta-a4a-implementation` attribute, so reports an error. If you load the repro page via https://cdn.ampproject.org/c/www.mynet.com/haber/amp/guncel/asit-yagmuru-tehlikesi-yasanan-mardinde-toz-firtinasi--2697795-1 it will execute the A4A path correctly. 

The question is whether this is the correct behavior?  The CDN check is in there to protect ad networks and advertisers from publishers running self-served and non-compliant AMP runtimes.  A publisher running a hacked AMP runtime could reach into a creative and modify it, synthesize clicks, etc.

We _could_, potentially, give that up for beta testers.  (Or for all of Doubleclick.)  What's the desired behavior?

**Comment by jasti** [comment] 2016-11-07 19:14
Thanks @tdrl. I think we should stick with 'let's only make this valid when served from the CDN' option - especially since all ad requests will be delivered via the A4A path starting next year and this is just a temporary workaround.

**Comment by tdrl** [comment] 2016-11-07 19:16
SGTM.  Closing as 'Working as Intended', then.

**Closed by tdrl** 2016-11-07 19:16 UTC
Labels: Related to: Ads
