### ISSUE TITLE
Images in an amp-carousel sometimes fail to load when using goToSlide()

### ISSUE THREAD

**Issue by DannySaltire** [ampproject/amphtml#30309] opened 2020-09-19 02:25 UTC
## What's the issue?

Using `<amp-carousel>` with type "slides", a slide with an `<amp-img>` can get stuck in a loading animation after switching slides with goToSlide(). The same images will load after switching slides using carousel buttons.

## How do we reproduce the issue?

This can be reproduced on the "Image gallery with a preview carousel" example here:

https://amp.dev/documentation/examples/multimedia-animations/image_galleries_with_amp-carousel/?format=websites#image-gallery-with-a-preview-carousel

The issue is intermittent. It seems more frequent on slower machines, and on larger carousels. After a fresh reload, it either consistently works or consistently doesn't.

## What browsers are affected?

I've reproduced in Chrome and Safari. Safari seems more likely to reproduce the issue.

## Which AMP version is affected?

2009040024003 is affected.
2009040024001 seems unaffected (although the nature of the bug makes it hard to be certain).

**Comment by jridgewell** [comment] 2020-09-21 20:22
Hi @DannySaltire, thanks for reporting this!

After investigating, I'm convinced this is caused by a bug in newly launched experiment. The bug fix was merged in #30188, and will rollout to production tomorrow.

**Closed by jridgewell** 2020-09-21 20:22 UTC
Labels: Type: Bug
