### ISSUE TITLE
Multipe result pages from same site showing AMP on dektop

### ISSUE THREAD

**Issue by ramikh86** [ampproject/amphtml#6409] opened 2016-11-30 15:45 UTC
Hi,

## Short description of your issue:
Using a desktop browser if you search for an article and it shows multiple result from the same domain(bna.com in our case), the first one will open in regular desktop view but the following result pages will open in amp view.

## How do we reproduce the issue?
Some examples to reproduce (please search for these articles in google)
"Stride Rite to Pay $1 Million to Illinois Under Tax Settlement"
"Ueland, Grady Said to Be in Running for Top OMB Job"

1. Click the first article in the result page, it will open in desktop view
2. click the 2nd or 3rd they will open in amp view
3. they all should open in desktop none amp view

## Which AMP version is affected? we are using https://cdn.ampproject.org/v0.js

**Comment by jridgewell** [comment] 2016-11-30 20:34
I'm unable to reproduce. Can you make a screencast?

**Comment by ramikh86** [comment] 2016-12-01 00:51
Searching for "Stride Rite to Pay $1 Million to Illinois Under Tax Settlement" in google, Im using chrome in windows 7(the issue happens in all browsers)

Search result shows multiple articles from bna.com
![_search result](https://cloud.githubusercontent.com/assets/10948292/20777596/fe484454-b735-11e6-81b6-2c272467120f.png)

Click on first link from search result
![1st from result](https://cloud.githubusercontent.com/assets/10948292/20777593/fe473faa-b735-11e6-8014-4cd692bb30cc.PNG)

Click on 2nd link from search result
![2nd from result](https://cloud.githubusercontent.com/assets/10948292/20777594/fe47725e-b735-11e6-963f-8d638ba6b207.PNG)

Click on 3rd link from search result
![3rd from result](https://cloud.githubusercontent.com/assets/10948292/20777595/fe4782ee-b735-11e6-935e-38c035714bea.PNG)

**Comment by rudygalfi** [comment] 2016-12-01 17:44
Can you try in an incognito window or without browser extensions enabled? I'm currently only seeing the first non-AMP result showing up.

**Comment by jridgewell** [comment] 2016-12-01 17:51
@rudygalfi: I was able to reproduce last night at home. It might be some issue with using Google's internal network vs external.

**Comment by ramikh86** [comment] 2016-12-01 18:09
That's weird, it seems that its showing one result for each article now, the other results disappeared which is the expected behavior as the other articles don't event share any related search terms.
If it continue to behave this way i guess its fine, but i hope its not a problem with how google indexes the amp view vs regular view.
I did more testing with the term "Trump site:www.bna.com" which shows multiple articles, they all open in dektop view which is fine.

**Comment by ericlindley-g** [comment] 2016-12-08 00:52
How strange — closing this bug for now (but please feel free to re-open if it crops up again). I will pass this info on to the Google Search team.

**Closed by ericlindley-g** 2016-12-08 00:52 UTC
Labels: Related To: Google Search
