### ISSUE TITLE
Fix flaky base-carousel e2e test

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#22845] opened 2019-06-14 21:33 UTC
https://github.com/ampproject/amphtml/pull/22809 skips a flaky BaseCarousel e2e test. I can't figure out why the changes would cause any failures, the carousel itself uses native APIs to get the bounding client rect.

**Comment by nainar** [comment] 2019-09-20 20:22
Dupe of https://github.com/ampproject/amphtml/issues/24195

**Closed by nainar** 2019-09-20 20:22 UTC
Labels: P1: High Priority, Related to: Flaky Tests, Type: Bug, UI: Component: amp-base-carousel, UI: Type: Testing, WG: ui-and-a11y
