### ISSUE TITLE
template tag is currently required under the submit-success or submit-error tags in amp-form

### ISSUE THREAD

**Issue by rohitverma007** [ampproject/amphtml#5869] opened 2016-10-28 01:15 UTC
Is there a reason why we need to include a `template` tag under the `submit-success` or  `submit-error` tags in `amp-form`? It is entirely possible that the content within submit-success or submit-error is static and does not require any templating. Moreover, using the template tag requires the addition of the amp mustache javascript file unnecessarily.

**Comment by mkhatib** [comment] 2016-10-28 02:01
Thanks for filing @rohitverma007 

We agree and will be fixing this, dupe of #5619

**Closed by mkhatib** 2016-10-28 02:01 UTC
