### ISSUE TITLE
No Keyboard Accessibility for 'Tab Panels with amp-selector'

### ISSUE THREAD

**Issue by mdvb1001** [ampproject/amphtml#27356] opened 2020-03-23 15:11 UTC
## Describe the new feature or change to an existing feature you'd like to see
The tabs to the tab panels should be navigable with the keyboard arrow keys, as stipulated by W3.org (https://www.w3.org/TR/wai-aria-practices-1.1/#tabpanel)

"When focus is on a tab element in a horizontal tab list:

- Left Arrow: moves focus to the previous tab. If focus is on the first tab, moves focus to the last tab. Optionally, activates the newly focused tab [...].

- Right Arrow: Moves focus to the next tab. If focus is on the last tab element, moves focus to the first tab. Optionally, activates the newly focused tab [...]."

## Describe alternatives you've considered

I could add some custom JS via amp-script, but this is less than ideal as it requires a fair amount of code -- we could hit the size limit imposed by amp-script.

**Comment by dmanek** [comment] 2020-10-22 22:31
Seems like this issue has been fixed or is working as intended. I'm able to use arrow keys to focus on next/prev tabs and use enter/space key to select a tab. By design the currently selected tab does not show the focus outline when focussed.

**Comment by caroqliu** [comment] 2020-10-23 16:08
Closing as we are not able to reproduce the original issue, please re-open if you are still encountering the issue. :)

**Closed by caroqliu** 2020-10-23 16:08 UTC
Labels: Type: Feature Request
