### ISSUE TITLE
Allow for Page Link Copying

### ISSUE THREAD

**Issue by jessanastasio** [ampproject/amphtml#10272] opened 2017-07-05 21:43 UTC
It would be great to have the ability to copy to the clipboard. 

Use case: a link button (that would live with other social share buttons) that would copy the site's URL to the clipboard, which you could pair with an `amp-user-notification` stating something like "Link copied!"

**Comment by jridgewell** [comment] 2017-07-05 21:50
Closing a a duplicate of https://github.com/ampproject/amphtml/issues/4853. We had https://github.com/ampproject/amphtml/pull/7749, but it stalled. /cc @torch2424

**Closed by jridgewell** 2017-07-05 21:50 UTC
