### ISSUE TITLE
[CANARY Error]: Cannot read property '__AMP_TOP' of null

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#11450] opened 2017-09-26 22:47 UTC
```
Error: Cannot read property '__AMP_TOP' of null
    at __AMP_TOP (https://raw.githubusercontent.com/ampproject/amphtml/1506372648650/src/service.js:327:9)
    at getTopWindow (https://raw.githubusercontent.com/ampproject/amphtml/1506372648650/src/service.js:210:8)
    at https://raw.githubusercontent.com/ampproject/amphtml/1506372648650/src/service.js:382:6
    at getAmpdoc (https://raw.githubusercontent.com/ampproject/amphtml/1506372648650/src/service.js:267:17)
    at getServiceForDoc (https://raw.githubusercontent.com/ampproject/amphtml/1506372648650/src/service.js:266:16)
    at https://raw.githubusercontent.com/ampproject/amphtml/1506372648650/src/preconnect.js:322:21
    at getViewer_ (https://raw.githubusercontent.com/ampproject/amphtml/1506372648650/src/preconnect.js:340:32)
    at url (https://raw.githubusercontent.com/ampproject/amphtml/1506372648650/builtins/amp-img.js:73:6)
```

**Comment by jridgewell** [comment] 2017-09-29 21:31
Dupe of https://github.com/ampproject/amphtml/issues/9177.

**Closed by jridgewell** 2017-09-29 21:31 UTC
