### ISSUE TITLE
amp-ad - Uncaught TypeError: Cannot read property 'create' of undefined

### ISSUE THREAD

**Issue by fox94610** [ampproject/amphtml#22726] opened 2019-06-06 17:23 UTC
Directly related to this "closed" issue:
https://github.com/ampproject/amphtml/issues/17997

I know this is a 'silent' error that I guess doesn't have any user facing side effects, but I thought y'all should know it's still out there. Go to this page and you'll see it:
https://www.babycenter.com/amp/0_breastfeeding-exclusively-for-3-months-decreases-risk-of-chr_40005552.bc

If you don't see it the first time, reload browser, it's dependent on what ad is being served.

**Comment by torch2424** [comment] 2019-06-18 00:45
cc @ampproject/wg-ads

**Comment by zhouyx** [comment] 2019-06-18 01:17
cc @jridgewell

**Comment by jridgewell** [comment] 2019-06-18 15:52
Dupe of https://github.com/ampproject/amphtml/issues/17997.

**Closed by jridgewell** 2019-06-18 15:52 UTC
Labels: Category: Ads, Type: Bug
