### ISSUE TITLE
Error: Cannot read property 'contains' of null

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#17838] opened 2018-09-04 06:18 UTC
Error at: go/ampe/CLS27emlybuh5AE
Occurring 4,987 / day, version 1535579255907. 

Stacktrace
```
Error: Cannot read property 'contains' of null
at transferTo (https://raw.githubusercontent.com/ampproject/amphtml/1535579255907/src/service/fixed-layer.js:767)
at (https://raw.githubusercontent.com/ampproject/amphtml/1535579255907/src/service/fixed-layer.js:767)
at setupElement_ (https://raw.githubusercontent.com/ampproject/amphtml/1535579255907/src/service/fixed-layer.js:476)
at registerServiceBuilder (https://raw.githubusercontent.com/ampproject/amphtml/1535579255907/src/service.js:172)
```

Note: this error is new and has not been seen before this release.

**Comment by cathyxz** [comment] 2018-09-04 06:26
/cc onduty @prateekbh @erwinmombay 
This is a new error that has not been seen before release 1535579255907.

**Comment by jridgewell** [comment] 2018-09-05 17:53
Dupe of https://github.com/ampproject/amphtml/issues/17837

**Closed by jridgewell** 2018-09-05 17:53 UTC
Labels: Category: Runtime, P1: High Priority, Type: Bug
