### ISSUE TITLE
`amp-iframe` overflow elements layered behind iframe content

### ISSUE THREAD

**Issue by tonyruscoe** [ampproject/amphtml#7025] opened 2017-01-13 15:22 UTC
When an overflowing resizable [`<amp-iframe>`](https://www.ampproject.org/docs/reference/components/amp-iframe) element is loaded in the viewport, and therefore not resized automatically, I would expect the `overflow` element to be positioned in front of the iframed content so that site visitors are able to easily tap it. Instead, the `overflow` element is currently positioned behind the iframe content.

You can reproduce this using the [Disqus for Accelerated Mobile Pages (AMP)](https://github.com/disqus/disqus-install-examples/tree/master/google-amp) example, modified slightly since their example doesn’t include the required `overflow` element.

Here’s a test page to demonstrate the issue when viewed in a narrowish viewport, e.g. 480px wide, on Chrome, Safari or Firefox for Mac (others may be affected too):

https://amphtml-test.appspot.com/amp-iframe/resizable.html

Screenshot:
![amp-iframe-overflow-bug](https://cloud.githubusercontent.com/assets/1343864/21934933/4ac0addc-d9a3-11e6-86c0-3922931881a4.png)

Please can you confirm whether this is a bug or if there’s something else causing this which can easily be prevented? Thanks!

**Comment by jridgewell** [comment] 2017-01-13 20:16
@dvoytenko: Have some CSS wizardry for this? I noticed that if a reorder the DOM nodes, putting the overflow as the last child, and apply `transform: translateZ(0)` to it everything paints correctly.

**Comment by dvoytenko** [comment] 2017-01-17 17:33
Looks like a bug. I'll take a look.

**Comment by dvoytenko** [comment] 2017-01-17 18:55
@jridgewell We've run into this browser nuance (or bug? can't find evidence one way or the other) before. It's fixed by adding `position:relative` to the div displayed on top of an iframe. PR is on the way.

**Comment by dvoytenko** [comment] 2017-01-17 19:03
Actually, now that I thinking this through - this is an expected behavior. `z-index` requires non-static positioning. So, this is definitely a bug.

**Closed** 2017-01-17 20:54 UTC
Labels: Type: Bug

**Comment by tonyruscoe** [comment] 2017-01-17 21:24
Thanks for tracking down the cause and fixing the issue, @dvoytenko!
