### ISSUE TITLE
[amp-carousel] nav swipe is overridden by top stories carousel

### ISSUE THREAD

**Issue by uuberoy** [ampproject/amphtml#33433] opened 2021-03-23 13:41 UTC
## What's the issue?
The horizontal swipe on our nav gets overridden by the scroll for the `Top Stories` carousel. The nav appears to need the browser's focus for the scroll to work, and this focus is taken by the top stories carousel. Historically, the only way we've been able to get horizontal swiping to work is by implementing our nav with `amp-carousel`. This implementation was working in the `Top Stories` carousel until recently.

## How do we reproduce the issue?

1. On a mobile device or in mobile view on your browser, google `nytimes coronavirus vaccine`.
2. Scroll down till you reach the top stories list.
3. Click into the first story. The `Coronavirus Outbreak` nav should appear on top of the story.
4. Try to swipe horizontally on the nav to view the other menu items. The horizontal swipe will instead take you to the next top story in the carousel.

## What browsers are affected?

Chrome, Safari, Firefox.

## Which AMP version is affected?

This was working until recently (a few weeks ago). We are using the latest version of `amp-carousel` -- https://cdn.ampproject.org/v0/amp-carousel-0.2.js

Slack conversation: https://amphtml.slack.com/archives/C9HPA6HGB/p1616452405064800

**Comment by kristoferbaxter** [comment] 2021-03-23 13:46
Shifting the priority to p0. This is a regression in production.

Likely cause, events are no longer being captured by amp-carousel before bubbling to the viewer level.

**Comment by kristoferbaxter** [comment] 2021-03-23 15:06
Moving this to p1 since it's also present in the LTS branch. It's still high priority, but we can fix forward.

**Closed** 2021-03-23 19:54 UTC
Labels: P1: High Priority, Type: Bug, WG: components
