### ISSUE TITLE
[amp-story] Sound not playing on videos

### ISSUE THREAD

**Issue by cpauwels** [ampproject/amphtml#37882] opened 2022-03-16 11:50 UTC
### Description

There is currently no way to unmute videos in amp stories.

### Reproduction Steps

Example: https://stories.avrotros.nl/missie-1-capture

Tapping the unmute button does not do anything.

### Browser(s) Affected

Chrome, Safari

### OS(s) Affected

All tested

### Device(s) Affected

All tested

**Comment by cpauwels** [comment] 2022-03-16 17:36
After some digging, the presence of a `volume` attribute on an `amp-video` will make the video silent instead of setting the video volume.

Videos without the `volume` attribute will play normally. Videos with `volume="0"` are muted, as expected. But videos with `volume="0.5"` or `volume="1"` are also muted.

**Comment by erwinmombay** [comment] 2023-08-22 00:14
Seems like the issue is resolved. closing issue

**Closed by erwinmombay** 2023-08-22 00:14 UTC
Labels: Type: Bug
