### ISSUE TITLE
[amp-accordion] tap action does not trigger on heading

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#23523] opened 2019-07-25 13:50 UTC
See the following sample:

```html
<amp-accordion>
    <section>
      <h2 on="tap:myElement.toggleVisibility" tabindex=0 role=button>
        Section 1
      </h2>
      <div>
        Content 1
      </div>
    </section>
    <section>
      <h2>
        Section 2
      </h2>
      <div>
        Content 2
      </div>
    </section>
  </amp-accordion>

  <div id="myElement" hidden>
    Hello
  </div>
```

Expected behavior: `myElement` becomes visible when expanding the first section
Actual behavior: `myElement` stays hidden

**Comment by sebastianbenz** [comment] 2019-07-25 14:04
After reading the docs, I realized that I could accomplish this via: `<section on="expand:myElement.show;collapse:myElement.hide">`. 

Not supporting the `tap` event inside an amp-accordion breaks the assumption that the `tap` event is defined for all elements.

**Comment by sparhami** [comment] 2019-07-29 17:28
Dupe of #22381. We could potentially change this, but I do not have the context of why it is the way it is and changing it could break something.

**Closed by sparhami** 2019-07-29 17:28 UTC
Labels: Category: Presentation, P2: Soon, Type: Bug, UI: Customer: DevRel, UI: Customer: Developer, WG: ui-and-a11y
