### ISSUE TITLE
new posts in live list containes new amp modules

### ISSUE THREAD

**Issue by streamgao** [ampproject/amphtml#11979] opened 2017-11-08 02:02 UTC
**Please only file bugs/feature requests for AMP here.**

## What's the issue?
AMP-LIVE-LIST
The issue happens when the new posts contain any new modules.
For example,  the current posts on the page does not contain amp-twitter module,  during the update (click the update button) the new posts been loaded & put on to the page.  If new posts contain amp-twitter module,  the page head will be able to add the corresponding module.
However,  amp is not able to detect the change and dynamically load new modules.
as a result, will get fallback anchors. 

## How do we reproduce the issue?
For example,  the current posts on the page does not contain amp-twitter module,  during the update (click the update button) the new posts been loaded & put on to the page.  If new posts contain amp-twitter module,  the page head will be able to add the corresponding module.
However,  amp is not able to detect the change and dynamically load new modules.
as a result, will get fallback anchors. 

## What browsers are affected?
All browsers

## Which AMP version is affected?

Is this a new issue? Or was it always broken? Paste your AMP version. You can find it in the browser dev tools.

**Comment by aghassemi** [comment] 2017-11-08 22:36
@streamgao we are aware of the issue ( https://github.com/ampproject/amphtml/issues/7231 ) and working on a solution right now ( PR# https://github.com/ampproject/amphtml/pull/9302 ).

For the time-being, you need to include all the extensions you expect to be used in the main page until this issue is resolved soon.

Closing as duplicate of #7231, please subscribe to that issue for updates.

**Closed by aghassemi** 2017-11-08 22:36 UTC

**Comment by streamgao** [comment] 2017-11-09 00:36
thanks!
