### ISSUE TITLE
Pages with html and css only, without any javascript, amp element and forbidden html element should be valid AMP and be cached and indexed as AMP pages on google.

### ISSUE THREAD

**Issue by demil** [ampproject/amphtml#37038] opened 2021-11-23 14:51 UTC
### Description

HTML pages without any JavaScript, amp elements and forbidden html tags should be valid AMP pages. Those pages are basically subset of AMP and they are still best optimized for mobile device and they should be cached with amp cache and indexed as amp pages on google. However simple html/css pages without any forbidden element and JavaScript are not valid AMP pages because they don't utilize AMP script.

### Alternatives Considered

Don't use any amp elements but still load unnecessary amp JavaScript as a excess fat to your simple website.

**Comment by jridgewell** [comment] 2021-11-23 19:17
This appears to be a duplicate of https://github.com/ampproject/amphtml/issues/34027?

**Closed by jridgewell** 2021-11-23 19:17 UTC
Labels: Type: Feature Request
