### ISSUE TITLE
amp-state is not persisted across page reloads or page redirects

### ISSUE THREAD

**Issue by ro2ni3** [ampproject/amphtml#18185] opened 2018-09-19 15:51 UTC
## What's the issue?

When we submit a form and redirect the user away and then the user hits the back button on the browser, the amp state is lost.

I have an option select for selecting numChildren [1-4]. When selecting option 4, 4 more option selects will appear with the childrenAges. If we select childrenAges option selects 1,2,3,4 and then submit the form, when I click back, the state will have been lost. 

When the browser goes back, the numChildren option select will still show 4 (because the browser remembers it), but the amp-state will not be set to 4 (it will be null). This therefore means that the 4 childrenAges option selects won't show on the form.

## What browsers are affected?

All browsers

## Which AMP version is affected?

Version 1809142227020

**Comment by choumx** [comment] 2018-09-19 21:41
Thanks for the report. I think this is a dupe of #12360. We're planning on adding this soon.

**Closed by choumx** 2018-09-19 21:41 UTC
