### ISSUE TITLE
amp-auto-lightbox.js unexpectedly loaded on image-less page

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amphtml#25137] opened 2019-10-18 19:50 UTC
The `amp-auto-lightbox.js` file is unexpectedly loaded from pages that do not directly reference it (or use any images).

To reproduce:

1. Load https://separated-mollusk.glitch.me in Chrome Desktop (also reproduces on Firefox)
2. Open devtools network tab and reload.

Actual:

Three resources are loaded: the HTML (expected), v0.js (expected) and amp-auto-lightbox-0.1.js (unexpected).

<img width="1135" alt="Screenshot 2019-10-18 at 20 47 57" src="https://user-images.githubusercontent.com/51244/67123632-c321f500-f1e8-11e9-963f-e81c19f9b5bc.png">

Expected:

Only two resources are loaded.

**Comment by photocoder** [comment] 2020-02-07 13:08
You can use "data-amp-auto-lightbox-disable" option... But I'm waiting for opt-out possibility by this option: [doc level opt-out of amp-auto-lightbox](https://github.com/ampproject/amphtml/issues/26452)

**Comment by alanorozco** [comment] 2020-02-07 18:31
Yup, loads for every page. Closing as dupe of #26452

**Closed by alanorozco** 2020-02-07 18:31 UTC
Labels: P2: Soon, Type: Bug, UI: Component: amp-lightbox-gallery, UI: Customer: Developer, UI: Type: DevX, WG: ui-and-a11y
