### ISSUE TITLE
AMP VALIDATOR custom css size greater than 50,000 for custom CSS that is less than 50,000

### ISSUE THREAD

**Issue by QES** [ampproject/amphtml#22315] opened 2019-05-15 17:08 UTC
The issue is that the AMP Validator tools when the check the CSS size seem to overestimate the size of the file, I have been checking my CSS and occasionally I go over the 50,000 however quite frequently I check and my CSS is still below 50,000.  In addition, because the Validator doesn't give any feedback on the size of the CSS file until it is too big its hard to track prior to it becoming too big.

**Comment by torch2424** [comment] 2019-05-17 22:21
Triaging to @Gregable , feel free to re-assign 😄 

@QES If I may say though, one thing you might want to confirm is what tool you are using the count the CSS size? As some will count in Kilobytes, others may count in just kibibytes and things like that. Also, you may want to look into minifying your css if you haven't already. As I think the validator includes whitespace in its calculation? 🤔 😄

**Comment by Gregable** [comment] 2019-05-17 23:55
I'm reasonably certain the validator counts correctly here. It's 50,000 bytes - so no 1024's anywhere. It's also not characters, to don't use javascript string length, since that will count utf16 characters.

If you have a specific example to debug, feel free to share and I'll reopen, otherwise I'm going to close this as I can not reproduce.

**Comment by QES** [comment] 2019-05-20 16:10
Hi @Gregable thanks for your comments - I'm using php strlen which says:

strlen() returns the number of bytes

in my checks, I'm already using various tools to compress the CSS file and remove spaces and unrequired characters.

And in general, this works perfectly but I have around 170 pages that show up with the standard css compression as being below 50,000 bytes but which the validator say is more than 50,000.

In addition, I'm performing an offline compression against actual uses css to resolve this but its not perfect and there are still pages that seem to fall into this category temporarily.

Here is an examples:

https://amp.sportsmole.co.uk/football/man-utd/transfer-talk/feature/tuesday-papers-carrasco-mbappe-solskjaer_354410.html

Embeded in comments there is the following:

Before being compressed  : Length:51414:MB:51414: css last updated : 2019-05-17 14:36:17
After basic compression : css len x : 49370:MB:49370

Validator says there are 50333 bytes.

[css example css.txt](https://github.com/ampproject/amphtml/files/3198759/css.example.css.txt)

![image](https://user-images.githubusercontent.com/249748/58035278-519e2780-7b20-11e9-80ec-b313af659df9.png)

when I count in a text file I have 49411 bytes.

The big problem to me is that there is no warning when it gets close only an error when it passes so although I don't know what is being counted exactly.

For example, is the counted css just the amp-custom or do I need to add the amp-bolierplate to the total?

As I mentioned I have a more robust solution but it isn't a real time solutiont I have been using http://rbtech.github.io/css-purge/ in the mode to check the required css against the actual HTML (adding some extra html to the bottom of pages to deal with things that might change on the page) but I can't do this in real time (or haven't found a way to do so).

In an ideal world this would seem like a great use case for Varnish (or similar cache) for AMP for a particular page to throw away the css not used by the page.  


And here are some more pages.

https://amp.sportsmole.co.uk/football/transfer-talk/news/tuesday-papers-rashford-mane-pepe_356400.html

https://amp.sportsmole.co.uk/football/man-utd/transfer-talk/feature/fridays-papers-gareth-bale-ander-herrera-raphael-varane_355994.html

https://amp.sportsmole.co.uk/football/spurs/euro-2020/news/danny-rose-backs-raheem-sterlings-criticism-of-media_353943.html

There are another 170 or so.  I know that my AMP CSS is a bit of a basket case but its the problem of converting a desktop system which was already slightly CSS heavy.  Once of the nice things about CSS Purge is that with an HTML scan I can nearly cut 50% of the size of the CSS but it takes 10 seconds to do so which means it can't be used in real time for serving pages only for creating cached versions of the css for pages.

Anyway if you can help explain the difference with the CSS numbers and the validator it will at least allow me to better track potential issues and process them more promptly to the cached css version.

**Comment by QES** [comment] 2019-05-28 10:35
> I'm reasonably certain the validator counts correctly here. It's 50,000 bytes - so no 1024's anywhere. It's also not characters, to don't use javascript string length, since that will count utf16 characters.
> 
> If you have a specific example to debug, feel free to share and I'll reopen, otherwise I'm going to close this as I can not reproduce.

Hi @Gregable were you able to look at this further - I've now managed to work through the items that were causing problems.

I am using php strlen of everything within the <amp-custom> tag is that is what the validator is counting?

I can reproduce now almost what the validator is doing which is better and much closer.

However, the fact that the validator doesn't report the pending issue when you are just below 50,000 was annoying in this process :)

I have added code to my site to allow me to debug this here is an example and now agree it is probably working:

https://amp.sportsmole.co.uk/american-football/san-francisco-49ers/news/lockette-jenkins-will-surprise-people_85305.html?amp_css_update_css&dynamic

![image](https://user-images.githubusercontent.com/249748/58471068-f29d6b80-813a-11e9-8b14-79ce36f67c2f.png)

Shows the item is 50515 long

And I have also added a CSS header to make debugging this easier:

x-1-css: 50511   :Original:50483:db load:0:

**Comment by Gregable** [comment] 2019-05-28 20:14
Thanks for pinging the thread. I don't think I saw your update last week. Reopening, taking a look.

**Comment by Gregable** [comment] 2019-05-28 20:26
A few quick responses:

> I am using php strlen of everything within the tag is that is what the validator is counting?

Yes, it starts with the byte following `>` in `<style amp-custom>` and ends with the byte before `<` in `</style>`. Including comments, etc.

> However, the fact that the validator doesn't report the pending issue when you are just below 50,000 was annoying in this process :)

Understood. There is no great way for the validator to do so, since it only reports errors/warnings. One possibility would be to add a 50,000 byte comment to your CSS start, and then subtract 50,000 from the reported error.

> I'm already using various tools to compress the CSS file ...

I think you already knew this, but just to be comprehensive, the 50,000 byte limit is based on the uncompressed size. If you minify your CSS before sending to the validator, the validator will run over the minified CSS of course. However, it does not take into account any gzip compression of the document as delivered by an HTTP server. That would make the actual size dependent on other bytes in your document outside of the `<style>` tag which would be difficult to predict.

**Comment by Gregable** [comment] 2019-05-28 20:41
I came up with a ~~hacky~~ clever trick to report the style length even if the page is passing. It requires the author to change `<style amp-custom>` to `<style amp-custom-length-check>`, which has a validator rule allowing no more than `-1` bytes in the style tag contents, meaning it will always report an error with the bytes counted. One can use this while debugging, but will need to set it back when done. Assuming it passes code review, that should help out a little bit.

I downloaded the document at `amp.sportsmole.co.uk/american-football/san-francisco-49ers/news/lockette-jenkins-will-surprise-people_85305.html?amp_css_update_css&dynamic`, manually deleted everything before/after the `<style amp-custom>` and just looked at the file size on linux using `ls -l`. It reported 50515, the same as the validator, so I agree that this is working.

**Comment by QES** [comment] 2019-05-31 11:37
Hi @Gregable thanks for taking a further look at this, my solution was to add the CSS amp-custom length to a header to give me a view into what is going on within pages.

When I try your trick I get:

![image](https://user-images.githubusercontent.com/249748/58703364-5ffe0600-83a0-11e9-9036-bd4cc6035999.png)

On my development server.

As I may have said I suppose having a waring state when you get close to the limit might be useful but my work around for now is creating custom versions of the CSS for pages using http://rbtech.github.io/css-purge/ and the option to check against the actual HTML page to minimise the CSS requirements.

**Comment by Gregable** [comment] 2019-05-31 19:37
Sorry I was not clear. The 'trick' was a proposed change to the validator (see https://github.com/ampproject/amphtml/pull/22542) which ran into some trouble and hasn't landed yet.

As you've mentioned that you have a valid workaround and we've found no actual issue with the byte count in the validator, I'll re-close this issue. Thanks!

**Closed by Gregable** 2019-05-31 19:37 UTC
Labels: Category: Validator, Type: Bug

**Comment by VivianWang1993** [comment] 2019-11-28 08:11
![](https://user-images.githubusercontent.com/34879854/69216216-9b86c980-0ba6-11ea-9356-11c3906df054.png)
![image](https://user-images.githubusercontent.com/34879854/69788568-c520a000-11f9-11ea-9aa9-483adf9cfeab.png)


Actrually, the code between the tag <style amp-custom> is same,
