### ISSUE TITLE
[amp-next-page] [v0.1] Overrides runtime params set by viewer (including paddingTop)

### ISSUE THREAD

**Issue by iingato** [ampproject/amphtml#30953] opened 2020-11-02 18:35 UTC
## What's the issue?

When embedded in a viewer, amp-next-page appears to override [params](https://github.com/ampproject/amphtml/blob/7119dec068d31b26c914535c4653395b901296ce/extensions/amp-viewer-integration/amp-doc-viewer-api.md#amp-runtime-parameters) set by the viewer (in particular [`paddingTop`](https://github.com/ampproject/amphtml/blob/631fb3d6eb4a36e4a988b3dd648165ef4f2b3e92/src/service/viewport/viewport-impl.js#L157)). In our use case, the top padding added to the document body by the viewer is removed and this causes the document body to appear to jump up and behind a fixed header, when amp-next-page is initialized.

This was observed with v0.1 of amp-next-page, but it may also exist with v1.0, since both seem to only set the visibility state viewer param.
[relevant code v0.1](https://github.com/ampproject/amphtml/blob/4a9971b2dd8b37ed0a488bc357d841f640e7f4f1/extensions/amp-next-page/0.1/next-page-service.js#L233)
[relevant code v1.0](https://github.com/ampproject/amphtml/blob/4a9971b2dd8b37ed0a488bc357d841f640e7f4f1/extensions/amp-next-page/1.0/service.js#L594)

## How do we reproduce the issue?

1. Go to https://www.google.com/amp/s/www.forbes.com/sites/rachelsandler/2020/10/30/facebook-temporarily-stops-recommending-political-groups-to-combat-election-misinformation/amp/.
2. Observe that, once amp-next-page successfully bootstraps, the 32px of top padding that had been added to the document body to compensate for the viewer bar is set to 0px and the fixed header at the top of the page hides some of the content. (would recommend setting a breakpoint [here](https://github.com/ampproject/amphtml/blob/631fb3d6eb4a36e4a988b3dd648165ef4f2b3e92/src/service/viewport/viewport-impl.js#L157) to help demonstrate)
3. Observe this does not happen outside a viewer, e.g., https://www.forbes.com/sites/rachelsandler/2020/10/30/facebook-temporarily-stops-recommending-political-groups-to-combat-election-misinformation/amp/.

## What browsers are affected?

Viewers only, Chrome, Pixel 2

## Which AMP version is affected?

Observed October 29 2020, but uncertain if this issue existed prior. AMP version: 2010200130000.

**Comment by demianrenzulli** [comment] 2020-11-02 20:21
Hi @nainar are you know, Forbes is one of the early adopters of <amp-next-page> and they're currently using the latest version of the component.

Nevertheless they are still experimenting this issue in the amp viewer. Any help is highly appreciated!

**Comment by nainar** [comment] 2021-01-11 23:11
@dmanek to take a look

**Comment by dmanek** [comment] 2021-02-03 17:52
Hi @iingato the URL you've added does not have an amp-next-page. Do you another with amp-next-page where this issue is reproducible?

**Comment by dmanek** [comment] 2021-07-07 17:41
Hey @iingato can you respond to my comment above?

**Comment by dmanek** [comment] 2022-04-21 03:56
Closing since there is no update.

**Closed by dmanek** 2022-04-21 03:56 UTC
Labels: Type: Bug, Component: amp-next-page
