### ISSUE TITLE
Strange display styling in amp-user-notification

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#3568] opened 2016-06-13 20:46 UTC
Is [this](https://github.com/ampproject/amphtml/blob/master/extensions/amp-user-notification/0.1/amp-user-notification.js#L283) display unsetting needed?

``` js
this.element.style.display = '';
```

**Comment by erwinmombay** [comment] 2016-06-13 20:57
@jridgewell if i remember correctly this is because `amp-user-notification` starts off as `layout=nodisplay` which sets `display = 'none'` through javascript. any issue? we could move it to css too if that is better

**Comment by adelinamart** [comment] 2017-02-08 00:54
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)

**Closed by adelinamart** 2017-02-08 00:54 UTC
Labels: To be deprecated - FixIt, To be deprecated - Type: Question
