### ISSUE TITLE
New issue: GEONOTPATCHED: amp-geo served unpatched

### ISSUE THREAD

**Issue by adelinamart** [ampproject/amphtml#20392] opened 2019-01-17 01:17 UTC
Error: GEONOTPATCHED: amp-geo served unpatched, ISO country not set
at Error (https://raw.githubusercontent.com/ampproject/amphtml/1901151846530/src/log.js:540)
at apply (https://raw.githubusercontent.com/ampproject/amphtml/1901151846530/src/log.js:244)
at apply (https://raw.githubusercontent.com/ampproject/amphtml/1901151846530/src/log.js:257)
at error (https://raw.githubusercontent.com/ampproject/amphtml/1901151846530/extensions/amp-geo/0.1/amp-geo.js:204)
at findCountry_ (https://raw.githubusercontent.com/ampproject/amphtml/1901151846530/extensions/amp-geo/0.1/amp-geo.js:296)

Service	
default-cdn-1p-canary 
Version	
001901151846530

**Comment by jpettitt** [comment] 2019-01-17 15:58
I'm not seeing this error on amp by example (same canary build).

The error should only happen if `amp-geo` is served unpatched by our serving infrastructure.  Is there any more info on the context you can share with me? (outside github if needed)

**Comment by jpettitt** [comment] 2019-01-17 16:21
Tracked internally as b/123012667

**Comment by jridgewell** [comment] 2019-01-17 19:35
Due to #20015. You've imported a file file (`extensions/amp-geo/0.1/amp-geo.js`) which contains impure code (https://github.com/ampproject/amphtml/blob/master/extensions/amp-geo/0.1/amp-geo.js#L407-L411). That code **will run** in whatever binaries import it.

So, [`amp-consent.js`](https://cdn.ampproject.org/rtv/001901151846530/v0/amp-consent-0.1.js) now contains `amp-geo`'s custom element. `amp-consent.js` also contains `{{AMP_ISO_COUNTRY_HOTPATCH}}`, which won't be hotpached because isn't not the `amp-geo.js` file. Now we have a race to see whether `amp-consent.js` will download first, or `amp-geo.js`.

**Comment by adelinamart** [comment] 2019-01-17 19:48
Please let us know if this is a blocker for next week production. Thanks.

**Comment by jridgewell** [comment] 2019-01-17 20:04
It is, we'll need a new canary cut.

**Comment by adelinamart** [comment] 2019-01-21 06:17
I'm still seeing the issue in the new canary release

**Comment by jpettitt** [comment] 2019-01-22 15:24
Looks like there is a separate, low volume, issue where `amp-geo-latest.js` is not being patched but `amp-geo-0.1.js` is.  This is a serving infrastructure issue.

**Comment by gmajoulet** [comment] 2019-01-22 17:07
Should we wait for this internal CL to be submitted before promoting the canary to prod?

**Comment by jpettitt** [comment] 2019-01-22 17:16
The CL doesn't change anything in the actual build it only changes serving infrastructure.  I don't see a blocker on promoting - @jridgewell do you concur?

**Comment by jpettitt** [comment] 2019-01-22 18:56
Fix is working, there are some lingering cached files which will clear with the new canary build today.

**Comment by jpettitt** [comment] 2019-01-24 14:51
We're no longer seeing this error - closing the issue.  Any recurrence should be treated as a new issue as it will almost certainly have a different root cause.

**Closed by jpettitt** 2019-01-24 14:51 UTC
Labels: Category: Dynamic/Personalized Content, Externally Tracked, P1: High Priority, Type: Bug
