### ISSUE TITLE
[amp-story] Sharing broken in iOS Chrome

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#30596] opened 2020-10-09 19:00 UTC
1. Open any story in iOS Chrome. 
2. Tap on the sharing icon. 

(Expected) Native sharing dialog should pop up.
(Actual) Nothing happens.

@ampproject/wg-stories

**Comment by gmajoulet** [comment] 2020-10-09 19:04
Duplicate of https://github.com/ampproject/amphtml/issues/30302

**Closed by gmajoulet** 2020-10-09 19:04 UTC
Labels: P1: High Priority, Type: Bug, WG: stories
