### ISSUE TITLE
Search Console rendering text

### ISSUE THREAD

**Issue by AcidRaZor** [ampproject/amphtml#20675] opened 2019-02-05 06:54 UTC
## What's the issue?

Google Search Console and testmysite.thinkwithgoogle.com (including some others) does not render a screenshot correctly, shows only text. This causes alerts in search console saying the text is too small (mobile friendliness) and Viewport not set errors.

According to https://github.com/ampproject/amphtml/issues/17516#issuecomment-413355280 this should have been fixed in August already?

## How do we reproduce the issue?

Really not sure. The site is AMP compliant according to the testing tools, looking for advice on how to fix

## What browsers are affected?

Google

## Which AMP version is affected?

Current

**Comment by torch2424** [comment] 2019-02-07 00:44
Triaging to @aghassemi , feel free to reassign 😄

**Comment by aghassemi** [comment] 2019-02-07 01:00
Hi @AcidRaZor I am investigating, will report back. 

(This usually means something in AMP is using a new JS/Web API that older Chrome that indexing renders use don't understand.)

**Comment by aghassemi** [comment] 2019-02-07 19:12
@AcidRaZor Are you using `install-service-worker` by any chance?

**Comment by aghassemi** [comment] 2019-02-07 21:10
@AcidRaZor nevermine, I don't think it is service-wroker. current suspect is fix headers. Do you have fixed headers in your page? (or even better, can you share a Url with us please?)

**Comment by aghassemi** [comment] 2019-02-08 00:13
This so far ( at least for amp-by-example and ampproject.org ) has turned out to be related to `fixed-layer` and pretty much same issue as what @jridgewell talks about here: https://github.com/ampproject/amphtml/issues/14178 unfortunately the workaround done for Safari does not work for Chrome 41 and `transition: none` never goes away messing up everything.

<img width="1381" alt="screen shot 2019-02-07 at 3 49 50 pm" src="https://user-images.githubusercontent.com/2099009/52451293-32403900-2af3-11e9-9d58-64064b52fe19.png">

@AcidRaZor Your case would be caused by something completely different, so please be sure to send us a Url.

**Comment by aghassemi** [comment] 2019-02-08 00:14
@jridgewell Do we really need to apply all the fixed-layer stuff (aside from reparenting) on the non-viewer case? This being broken on Chrome 41 in viewer is fine, but not on origin since that's how crawlers render pages.

**Comment by aghassemi** [comment] 2019-02-08 00:18
lowering priority to P2, it is not a wide spread issue and has certain conditions need to be true to repro.

**Comment by AcidRaZor** [comment] 2019-02-08 16:16
Sorry for the late response. I dont feel comfortable sharing links to the work I am doing. Can I private message you instead? I dont use service workers/fixed layers and what not.

**Comment by AcidRaZor** [comment] 2019-02-08 16:22
Ok I asked the one Director if I can share publically...

https://amp.heycarter.com/Cars/Renault/Clio/66kW-turbo-Authentique/

Note most of it is static html. Similar cars works with amp-list and pulls dynamically from our API

**Comment by aghassemi** [comment] 2019-02-08 17:37
Thanks @AcidRaZor. Always feel free to share Urls privately, either on Slack or emailing me ( `aghassemi`  `at` `google.com`). Nice website by the way! 

Alright, based on my debugging, the server renders the whole page as pure `text` (e.g. it renders the  actual HTML source). Issue is with `content-type` your server is sending. It is sending `content-type: text/html,charset=utf-8` in response headers which is invalid, it needs to be `content-type: text/html; charset=utf-8`.

Looks like the engine used for rendering is not as forgiving as browsers with malformed content-type values and falls back to `text`. (Also not AMP specific, any other HTML page would have behaved this way)

Hope that helps. Please let me know if still an issue after fixing your server.

**Comment by aghassemi** [comment] 2019-02-08 17:38
Closing per comment above.

**Closed by aghassemi** 2019-02-08 17:38 UTC
Labels: P2: Soon, Type: Bug

**Comment by AcidRaZor** [comment] 2019-02-08 18:22
Thanks for the compliment. I generally don't like my own work :)

Having said that, I never set the header to act like that. Could be IIS messing around with me, will have to check. Thank you for helping on this. We did do a whole SEO project, so wondering if there is something set by someone that could act this way.

**Comment by AcidRaZor** [comment] 2019-02-08 18:26
Yep, looks like we added charset=utf-8 and IIS automatically comma separates and appends it to text/html output

**Comment by AcidRaZor** [comment] 2019-02-08 18:32
To anyone that finds this, don't add content-type "charset=utf-8" to the http response headers in IIS, this will add it on comma-separated. You would want to edit the MIME type of the html document to add the utf-8.

Thanks again aghassemi!
