### ISSUE TITLE
Allow `style` in `noscript`

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#20609] opened 2019-01-30 23:55 UTC
Summarizing conversations with @westonruter 

It is common to have CSS rules to target `js` vs `no-js`. Certain components need to become hidden or presented differently in `no-js` case. 

Currently `html:not([amp-version])` is one workaround to set specific `no-js` CSS rules. This works because `v0.js` adds that attribute but it is hacky and if SSR ever decides to add that attribute, it would break the workaround.

Maybe the proper approach is allowing `style` in `noscript` tag. I don't think it needs to fit the 50k limit either.

@westonruter @Gregable @cramforce

**Comment by cramforce** [comment] 2019-01-30 23:58
I'd be OK with that, but with a low KB limit. It would only ever be a little additional styling, and a large noscript-stylesheet would weigh heavily on the default case.

**Comment by aghassemi** [comment] 2019-01-31 00:19
I thought content of `noscript` don't get parsed with JS enabled. My understanding is that it becomes essentially a hidden text node. Limit is good regardless.

**Comment by westonruter** [comment] 2019-01-31 00:20
I think allowing `noscript > style` is one solution, but it would be preferred from a WordPress context if the no-JS rules could be written in the `style[amp-custom]`. In other words, the `html:not([amp-version])` is easier to work with.  As @sebastianbenz suggests in #17832, what if there is a `runtime-ready` classname added to the `html` element?

**Comment by Gregable** [comment] 2019-01-31 00:50
cc @alin04 since this may eventually intersect with the golang packager bug regarding noscript content parsing.

**Comment by jpettitt** [comment] 2019-01-31 16:33
FWIW this is valid html

```
<head>
  <noscript>
    <style> ... </style>
  <noscript>
</head>
```

`<noscript>` can also contain `<link>`.  We could allow a link to a stylesheet and cache the sheet if we need to do so to preserve privacy (may not be needed if it's impossible to pre-render in a non JS environment anyway).  Using a `<link>` would minimize the performance impact on the JS case at the expense of the much less common `<noscript>` case.

**Comment by westonruter** [comment] 2019-01-31 17:06
> FWIW this is valid html

Is it? 

![image](https://user-images.githubusercontent.com/134745/52071137-3a1e3d00-2537-11e9-97f9-557c9fcc6659.png)

I get validation errors when adding:

```html
<noscript>
    <style>body {color:red}</style>
</noscript>
```

**Comment by westonruter** [comment] 2019-01-31 17:14
Sorry. You said _HTML_, not _AMPHTML_.

**Comment by Gregable** [comment] 2020-08-25 17:25
Is there still interest in this request? I don't see a resolution to determine a final implementation plan and interest has died off, so for now I'll just close it and we can re-implement.

**Comment by westonruter** [comment] 2021-08-18 20:52
Reopening since it has re-arisen as a need.

I've been watching a [Gutenberg issue](https://github.com/WordPress/gutenberg/issues/21584) for an Accordion block with the thought that it could be a good fit for the `amp-accordion` Bento component. Three points were raised as requirements (https://github.com/WordPress/gutenberg/issues/21584#issuecomment-900372945):

1. Graceful degradation when JS is not active.
2. Keyboard accessibility.
3. Semantic markup.

The second two points are accounted for in `amp-accordion`. However, it seems the first is not.

If I disable JavaScript and go to https://preview.amp.dev/documentation/components/amp-accordion-v1.0.example.1.html the result is that the first two sections cannot be accessed.

**Comment by westonruter** [comment] 2021-08-18 20:59
Reopening since it has re-arisen as a need.

I've been watching a [Gutenberg issue](https://github.com/WordPress/gutenberg/issues/21584) for an Accordion block with the thought that it could be a good fit for the `amp-accordion` Bento component. Three points were raised as requirements (https://github.com/WordPress/gutenberg/issues/21584#issuecomment-900372945):

1. Graceful degradation when JS is not active.
2. Keyboard accessibility.
3. Semantic markup.

The second two points are accounted for in `amp-accordion`. However, it seems the first is not.

If I disable JavaScript and go to https://preview.amp.dev/documentation/components/amp-accordion-v1.0.example.1.html the result is that the first two sections cannot be accessed.

Seems like there's a need for Bento components (and classic components) to ship with `noscript` styles which can be used to account for this.

For example:

```html
<noscript>
	<style>
		amp-accordion > section:not([expanded]) > :last-child {
			display: block !important;
		}
	</style>
</noscript>
```

See https://bento-amp-noscript-styles.glitch.me/

When JS is enabled | When JS is Disabled
--------------------|----------------------
![image](https://user-images.githubusercontent.com/134745/129970794-7af56081-0770-4cde-8236-20050975c08d.png) | ![image](https://user-images.githubusercontent.com/134745/129970808-c4069670-bada-45f7-b10a-00dd6f734dae.png)

Instead of adding `noscript > style` elements, an alternative would be to make use of the scripting CSS media feature which would allow for no-JS styles to be included in the same stylesheet. Unfortunately, no browser supports this currently: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/scripting#browser_compatibility

So going with `noscript > style`, I think each component can be distributed with a `*-noscript.css` file alongside any `*.css` file.

So the boilerplate HTML the user should include (for Bento) would look like:

```html
<!-- AMP runtime script -->
<script async src="https://cdn.ampproject.org/v0.js"></script>
<!-- Bento component stylesheet -->
<link rel="stylesheet" type="text/css" href="https://cdn.ampproject.org/v0/amp-bento-component-name-1.0.css">
<!-- :sparkles: noscript Bento component stylesheet -->
<noscript>
    <link rel="stylesheet" type="text/css" href="https://cdn.ampproject.org/v0/amp-bento-component-name-1.0-noscript.css">
</noscript>
<!-- Bento component script -->
<script async custom-element="amp-bento-component-name" src="https://cdn.ampproject.org/v0/amp-bento-component-name-1.0.js"></script>
```

For the AMP case, AMP Optimizer should construct this `noscript > style` and populate it with the noscript stylesheets for all components on the page. 

So at the very least we need `noscript > style` to be valid AMP. And once we have this, we can populate it with the Optimizer.

**Comment by Gregable** [comment] 2021-08-18 21:14
> So to start with at very least we need noscript > style to be valid AMP. 

Allowing `<noscript><style amp-custom>...</style></noscript>` is different than allowing an external CSS file. Do we need the custom version or just the external `.css` file?

**Comment by westonruter** [comment] 2021-08-18 21:31
I think the only need is for `noscript > style[amp-custom]`. The Bento example I gave for `noscript > link` would be for hand-authored non-AMP pages so it's not relevant for the validator.

For AMP pages, there is the similar existing Optimizer logic for the runtime CSS. The [`AmpBoilerplateTransformer` adds](https://github.com/ampproject/amp-toolbox/blob/6f465eb24b05acf74d39541151c17b8d8d97450d/packages/optimizer/lib/transformers/AmpBoilerplateTransformer.js#L69-L85) a `style[amp-runtime]` but if fetching `v0.css` fails then it will instead add a `link[amp-runtime]`. Nevertheless, the failure case is not valid AMP as only `style[amp-runtime]` is in the spec:

https://github.com/ampproject/amphtml/blob/fb01d326de149edcab4e45024f7d6c3f45139e82/validator/validator-css.protoascii#L1382-L1404

So I think the Optimizer transformer for component-specific `noscript` CSS can behave similarly: it can try to gather up the proposed `*.noscript.css` files for the components used on the page and add them to a `noscript > style[amp-custom]` element, but if fetching fails it may add (invalid) `noscript > link` elements instead.

Something else to consider is whether there should be a differentiation between user-authored noscript styles and component-specific noscript styles. Should there be separate  `noscript > style[amp-noscript]` (or `noscript > style[amp-runtime]` ) in addition to allowing `noscript > style[amp-custom]`, where the former comes before the latter?

**Comment by honeybadgerdontcare** [comment] 2021-08-24 22:08
In progress. cl/391926674

**Comment by Gregable** [comment] 2021-09-02 22:25
This is fixed and live everywhere.

**Closed by Gregable** 2021-09-02 22:25 UTC
Labels: Type: Feature Request, P2: Soon, WG: caching, WG: bento

**Comment by westonruter** [comment] 2021-09-02 22:32
Confirmed!

Given [example document](https://playground.amp.dev/#share=PCFET0NUWVBFIGh0bWw+CjxodG1sIOKaoT4KICA8aGVhZD4KICAgIDxtZXRhIGNoYXJzZXQ9InV0Zi04IiAvPgogICAgPHRpdGxlPk15IEFNUCBQYWdlPC90aXRsZT4KICAgIDxsaW5rIHJlbD0iY2Fub25pY2FsIiBocmVmPSJzZWxmLmh0bWwiIC8+CiAgICA8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoIiAvPgogICAgPHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT5ib2R5ey13ZWJraXQtYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7LW1vei1hbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aDstbXMtYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7YW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGh9QC13ZWJraXQta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUAtbW96LWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW1zLWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW8ta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUBrZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19PC9zdHlsZT48bm9zY3JpcHQ+PHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT5ib2R5ey13ZWJraXQtYW5pbWF0aW9uOm5vbmU7LW1vei1hbmltYXRpb246bm9uZTstbXMtYW5pbWF0aW9uOm5vbmU7YW5pbWF0aW9uOm5vbmV9PC9zdHlsZT48L25vc2NyaXB0PgogICAgPHNjcmlwdCBhc3luYyBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwLmpzIj48L3NjcmlwdD4KICAgIDxzdHlsZSBhbXAtY3VzdG9tPgogICAgICBib2R5IHsgYmFja2dyb3VuZDogZ3JlZW47IH0KICAgIDwvc3R5bGU+CiAgICA8bm9zY3JpcHQ+CiAgICAgIDxzdHlsZSBhbXAtbm9zY3JpcHQ+Ym9keXsgYmFja2dyb3VuZDogcmVkOyB9PC9zdHlsZT4KICAgIDwvbm9zY3JpcHQ+CiAgPC9oZWFkPgogIDxib2R5PgoJPHA+CiAgICAgIFRoZSBiYWNrZ3JvdW5kIHNob3VsZCBiZSByZWQgd2hlbiBKUyBpcyB0dXJuZWQgb2ZmLgogICAgPC9wPgogIDwvYm9keT4KPC9odG1sPgo=), the `noscript > style[amp-noscript]` is valid:

![image](https://user-images.githubusercontent.com/134745/131924405-fcdae059-b083-49aa-a414-2207cc956ffa.png)

JS Enabled | JS Disabled
-----------|-------------
![js-enabled](https://user-images.githubusercontent.com/134745/131924492-7da7fbe3-fa62-4417-b5c2-3651b885d8f3.png) | ![js-disabled](https://user-images.githubusercontent.com/134745/131924493-c2735271-eda7-4446-aecd-3e227149be29.png)

Thank you!

**Comment by Gregable** [comment] 2021-09-02 22:38
No problem. If you later discover that we need support for additional css rules for each extension as mentioned above, please open a new issue for that.

**Comment by westonruter** [comment] 2021-09-04 19:47
As a few next steps I see, to open in other issues:

1. Add `noscript.css` stylesheets to each component, e.g. for `amp-accordion` to force each collapsed section to be displayed.
1. Create a new optimizer transformer that automatically adds these `noscript` stylesheets into a `noscript > style[amp-noscript]`. (In lieu of the previous point, this could be done initially with a single noscript stylesheet shipped with the optimizers.)
1. Add awareness of the `style[amp-noscript]` to the AMP-WP plugin so that plugin/theme authors can make use of it.
