### ISSUE TITLE
<amp-img> not showing up in print due to them not being lazyloaded in yet.

### ISSUE THREAD

**Issue by SimonHogstromRonbol** [ampproject/amphtml#29075] opened 2020-06-29 08:45 UTC
## What's the issue?

I have a large gallery of images that my client wants to be able to print to paper, and when i use the browsers print function or the print action in amp, the images that havnt lazyloaded in yet, doesnt show up in the print preview.

## How do we reproduce the issue?

I've made a glitch project demonstrating the issue.
https://absorbing-pickled-hellebore.glitch.me/

if you go to your browser options, and press print, you will see that there are a lot of blank pages with no images on them, if you then cancel the print, scroll all the way down the page, and press print again, the images will appear in the print preview as they are supposed to.

## What browsers are affected?

I've tested this in Chrome, Firefox, Edge, and Safari, and this issue occurs on all of them.

## Which AMP version is affected?

i havn't tested this in prior versions of AMP.

@morsssss

**Comment by Ichigo3d** [comment] 2020-06-29 15:36
The issue is repro on 2006180239002 and 2006112352003 cc @jridgewell
<img width="1433" alt="Screen Shot 2020-06-29 at 8 33 35 AM" src="https://user-images.githubusercontent.com/37351864/86025636-4d129680-b9e3-11ea-8bb1-0cb4d0954f17.png">
<img width="1078" alt="Screen Shot 2020-06-29 at 8 30 44 AM" src="https://user-images.githubusercontent.com/37351864/86025674-5439a480-b9e3-11ea-8155-31dafe699f46.png">

**Comment by choumx** [comment] 2020-07-21 03:39
Dupe of #29075.

**Closed by choumx** 2020-07-21 03:39 UTC
Labels: P3: When Possible, Type: Bug, WG: runtime

**Comment by SimonHogstromRonbol** [comment] 2020-11-18 00:02
@choumx you closed this issue cause it was a dupe, but linked this issue, what issue is it duping? i would like to follow that along if i could.

**Comment by morsssss** [comment] 2020-11-18 00:06
Like all issues, it was a dupe of itself! 😈

**Comment by morsssss** [comment] 2020-11-18 00:08
(Actually, it looks like this is a dupe of https://github.com/ampproject/amphtml/issues/10371.)

**Comment by SimonHogstromRonbol** [comment] 2020-11-18 00:09
I'll go ahead and follow that then! thank you @morsssss!
