### ISSUE TITLE
[amp-story-player] starts auto-playing when viewer is now in view-port (way down on the page)

### ISSUE THREAD

**Issue by pshihn** [ampproject/amphtml#31334] opened 2020-11-25 17:24 UTC
## What's the issue?

When amp-story-player is added down the page, when the page loads, it is not in view. It still starts playing the story. My understanding was that it should only auto play when it's in view. 

May or may not be related to https://github.com/ampproject/amphtml/issues/31333

## How do we reproduce the issue?

Create a web page with lots of content before amp-story-player is added. After some time scroll down to the story player and see that it's already playing. 

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 2011070101001

**Comment by gmajoulet** [comment] 2020-11-25 23:43
Duplicate of #29798, this issue will be fix in https://github.com/ampproject/amphtml/pull/31305 where the Story will start playing when ~30% of it is visible in the viewport.

**Closed by gmajoulet** 2020-11-25 23:43 UTC
Labels: Type: Bug

**Comment by pshihn** [comment] 2020-11-25 23:50
@gmajoulet  Will the story pause automatically when it goes away from the viewport after being in the viewport?

**Comment by gmajoulet** [comment] 2020-11-26 00:03
No, it would start playing and not be paused programmatically by the Player.
You could however write your own logic to do so, using the `pause()` and `play()` methods, once we fix the issue you reported with `pause()`.

If you call `pause()` on page load the Player would respect that and not play the Story as it becomes visible, so you'd get total control over the experience, which is I think what you want.
