### ISSUE TITLE
Google AMP for Facebook comments plugin

### ISSUE THREAD

**Issue by tungvn** [ampproject/amphtml#5219] opened 2016-09-26 08:47 UTC
I found [here](https://ampbyexample.com/components/amp-facebook/) for supporting facebook plugins, but I found nothing for facebook comment.

I try using amp-iframe with ex.
`<amp-iframe width="672" height="240"
       sandbox="allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox"
       layout="responsive"
       frameborder="0"
       src="https://facebook.com/">
</amp-iframe>`
The facebook comments show, but can not scroll to view all comments.

How do I add facebook comments with AMP?
I use Firefox 49 and Chrome 51. AMP version: 1474310684773

**Comment by sriramkrish85** [comment] 2016-09-26 18:18
I dont think we have something explicit to support this.
@tungvn try out setting this property on the `amp-iframe`
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe?#attr-scrolling

Let us know if this works for you.

CC @dvoytenko

**Comment by rudygalfi** [comment] 2016-09-26 21:15
Passing over to @ericlindley-g

**Comment by ericlindley-g** [comment] 2016-09-28 23:30
Will be curious to hear if the `attr-scrolling` fix works for you, @tungvn. We can look into a dedicated component for facebook embedded comments, regardless.

**Comment by ericlindley-g** [comment] 2016-09-28 23:42
And you're welcome to contribute code to support embedded facebook comments, as well :)

**Comment by cramforce** [comment] 2016-09-29 02:01
I think the only reasonable way to really do this is an a new feature to `amp-facebook`. We should positively not encourage in-page scrolling.

**Comment by tungvn** [comment] 2016-09-30 04:40
Yeah, the `attr-scrolling` bring scrollbar for me, @ericlindley-g. But I found a bug.
I set my iframe with a fixed height and when a comment/expand sub-comments or something else, the height of box not flexibility change.

`<amp-iframe width="800" height="2000"
    sandbox="allow-scripts allow-same-origin"
    layout="responsive"
    frameborder="0"
    scrolling="auto"
    src="https://www.facebook.com/plugins/feedback.php?href=http://facebook.com/&numposts=5">
</amp-iframe>`

I tried to open the above link on browser, and it hasnt no scrolling 👎 . I think it is a FB bugs, not `amp-iframe`.
So, I think we should have a new feature to `amp-facebook` 💃

**Comment by ghostsurfer** [comment] 2016-12-02 08:36
@sebastianbenz thx for referencing to this task I search really long for a solution like this. 
@tungvn it's not a "bug" from Facebook. A `overflow: hidden;` is on the Body. thats cause in the normal case Facebook loads the iframe via JS and resize it to the content. A scrollbar is in this case not needed. 

So i think we need a `<amp-facebook>` for Comments.

the `attr-scrolling` did not work for me.

**Comment by ahmedkaludi** [comment] 2017-01-31 08:10
Hey @tungvn We're you find a solution for Facebook comments on AMP?

**Comment by ymschaap** [comment] 2017-02-07 12:57
I'm happy to work on this. Should I add it as a feature to the existing `amp-facebook` as `data-embed-as=comment` or create a new `amp-facebook-comments`?

**Comment by cramforce** [comment] 2017-02-07 16:19
@ymschaap I think adding this to `amp-facebook` makes sense since it can do 2 things already.

**Comment by dvoytenko** [comment] 2017-02-07 17:59
@cramforce @ymschaap I think that depends on the pattern we'd choose. If we go down the path of "See comments" button that expands into the full list of comments - I think a separate `amp-facebook-comments` would work better since it'd function significantly different from a post-style facebook embed.

**Comment by ymschaap** [comment] 2017-02-07 18:13
@dvoytenko yes, the comments plugin is very different in functionality compared to embedding facebook posts/videos. But if you look at the way how Facebook approaches this, it is just another (sibling) [social plugin](https://developers.facebook.com/docs/plugins). 

On the technical side, the AMP implementation (see #7398) is a few lines of code on top of existing `amp-facebook`.

**Comment by dvoytenko** [comment] 2017-02-08 20:29
@ymschaap I agree. Logically comments are different enough to warrant a separate extension. If we have a need to reuse the code between these two extensions, we have tools for that.

**Comment by ymschaap** [comment] 2017-02-09 11:03
@dvoytenko if you can point me in the right direction to reuse `amp-facebook` for a new `amp-facebook-comments` in  #7398, I could move forward with that.

**Comment by ahmedkaludi** [comment] 2017-02-09 11:04
@ymschaap Yes, amp-facebook-comments makes much more sense.

**Comment by dvoytenko** [comment] 2017-02-14 00:36
I scheduled this for design review this week. See #7380. Please join if you can.

**Comment by ymschaap** [comment] 2017-02-15 12:09
@dvoytenko I'll be there.

I created a `amp-facebook-comments` in the following commit (no test, or documentation yet):
> https://github.com/ymschaap/amphtml/commit/c25c48d1af7c659d09e7cac3eb7753ac85166f07

It's a new extention, which builds on the existing `3p/facebook.js`.

**Comment by jpettitt** [comment] 2017-02-16 02:20
Follow up from the design meeting today - here is a page with a live Disqus comments shimmed to resize correctly.  http://amp.wrestlinginc.com/wi/news/2017/0214/623260/randy-orton-refuses-wrestlemania-33-wwe-title-shot-video/

**Comment by dvoytenko** [comment] 2017-02-17 01:04
Thanks everyone for your time yesterday. Per discussion:
 1. `amp-facebook-comments` as a separate extension is recommended approach
 2. We need to figure out how to resize? Does Facebook API provide resize events?
 3. We need to find a way to support resize rejection. This can be done either via overflow element or by applying for exception, in which case we'd need to discuss restrictions on where it can be positioned (e.g. close to the bottom of the document).
 4. Post initial merge we will test how well login dialog works for different embedding scenarios.

Thanks!

**Comment by cramforce** [comment] 2017-02-17 03:57
Exception for comments resizing is definitely appropriate.

**Comment by ymschaap** [comment] 2017-02-17 09:57
@dvoytenko I made a PR to show what I have now. I'm very junior in picking up issues for public projects, so apologies if this is not the way it should work.

In reaction to your points above:

1. Done, see PR
2. Given the existing code for`amp-facebook` there is an undocumented FB resize event. The comments plugin uses that same that functions.
3 . I don't know what resize rehection is.
4. I have issues testing their login, possibly caused by FB not supporting authentication and localhost environment.

**Comment by ericlindley-g** [comment] 2017-05-25 15:43
Closing, as there is now support for [Facebook comments](https://github.com/ampproject/amphtml/blob/master/extensions/amp-facebook-comments/amp-facebook-comments.md), but please feel free to open a new issue with additional feature requests if there are any outstanding

**Closed by ericlindley-g** 2017-05-25 15:43 UTC
Labels: Category: Social & Sharing, Type: Feature Request

**Comment by nikoviedo** [comment] 2018-03-14 16:59
Hi! Counter comments?

**Comment by Bonjugal** [comment] 2018-03-15 15:09
How can I add **comment moderation tool** in amp-facebook comments?

**Comment by Serkis** [comment] 2019-04-28 08:43
> How can I add **comment moderation tool** in amp-facebook comments?

I'm wondering about that.

**Comment by thefreeProgrammer** [comment] 2023-08-23 19:38
Hi, to add comment moderation tool in amp-facebook , just add this :
<meta property="fb:app_id" content="{YOUR_APP_ID}" />
For more details :
https://developers.facebook.com/docs/plugins/comments/#moderation-setup-instructions
