### ISSUE TITLE
Error: null is not an object (evaluating 'this.a["helper-iframe-url"].indexOf')

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#11281] opened 2017-09-13 01:48 UTC
https://github.com/ampproject/amphtml/blame/master/extensions/amp-web-push/0.1/web-push-service.js#L203

**Comment by jridgewell** [comment] 2017-09-19 21:32
```
Error: Cannot read property 'indexOf' of null
    at indexOf (https://raw.githubusercontent.com/ampproject/amphtml/1505341213754/extensions/amp-web-push/0.1/web-push-service.js:201:6)
    at installHelperFrame (https://raw.githubusercontent.com/ampproject/amphtml/1505341213754/extensions/amp-web-push/0.1/web-push-service.js:151:30)
    at start (https://raw.githubusercontent.com/ampproject/amphtml/1505341213754/extensions/amp-web-push/0.1/amp-web-push-config.js:142:4)
    at buildCallback (https://raw.githubusercontent.com/ampproject/amphtml/1505341213754/src/custom-element.js:751:16)
    at https://raw.githubusercontent.com/ampproject/amphtml/1505341213754/src/custom-element.js:750:37
    at build (https://raw.githubusercontent.com/ampproject/amphtml/1505341213754/src/service/resource.js:316:11)
    at build (https://raw.githubusercontent.com/ampproject/amphtml/1505341213754/src/service/resources-impl.js:585:20)
```

/cc @jasonpang

**Comment by jasonpang** [comment] 2017-09-19 22:39
@jridgewell I think this is probably a duplicate of https://github.com/ampproject/amphtml/issues/11184. If it was caught 7 days ago, [the fix](https://github.com/ampproject/amphtml/pull/11192) wouldn't have had time to be released to all users.

**Closed** 2017-09-19 22:47 UTC
Labels: Type: Bug
