### ISSUE TITLE
AMP USED BY PHISING WEBSITE

### ISSUE THREAD

**Issue by sriwulan11** [ampproject/amphtml#39573] opened 2023-10-18 23:11 UTC
### Description

This domain uses AMP and is being misused as a phishing site for other people to help get banned on this domain

### Reproduction Steps

https://www.google.com/amp/s/hpdaasroi.ext.hp.com/SEMUTWIN/
 https://www.google.com/amp/s/igwus.miotgw.kubota.com/SEMUTWIN/

### Relevant Logs

```shell
https://prnt.sc/eFx-zBERKvtz
https://prnt.sc/aLdJgK0Y_9MD
```

### Browser(s) Affected

Chrome, Firefox, Safari, Edge, UC Browser

### OS(s) Affected

0

### Device(s) Affected

0

### AMP Version Affected

0

**Comment by erwinmombay** [comment] 2023-10-18 23:19
@sriwulan11 could you expand on which "domain" do they get banned?

**Comment by sriwulan11** [comment] 2023-10-19 21:27
for the domain https://www.google.com/amp/s/hpdaasroi.ext.hp.com/SEMUTWIN/ 

This amp domain is used as a phishing domain, with unknown people

**Comment by sriwulan11** [comment] 2023-10-19 21:27
This is very detrimental to my website, can you help me to ban the domain link so it can't be accessed

**Comment by jonathanliandi24137** [comment] 2023-10-23 05:16
This domain uses AMP and is being misused as a phishing site for other people to help get banned on this domain

### **Reproduction Steps**
(https://www.google.com/amp/s/ps188.world/%3ftunnel=nusa188)

**Relevant Logs**
[https://www.kampus168.org/](url)

![photo_2023-10-23 12 14 02](https://github.com/ampproject/amphtml/assets/148741783/711a2fb5-65bb-4a45-8ac5-ad21ac34d60c)
![photo_2023-10-23 12 15 41](https://github.com/ampproject/amphtml/assets/148741783/7038e1b5-8a30-448b-bd9a-c9b069200b7a)

**Comment by erwinmombay** [comment] 2023-10-26 16:49
dupe of https://github.com/ampproject/amphtml/issues/39572

**Closed by erwinmombay** 2023-10-26 16:49 UTC
Labels: Type: Bug
