### ISSUE TITLE
test-stub-element missing required requires

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#3480] opened 2016-06-07 18:36 UTC
```
Chrome 51.0.2704 (Linux 0.0.0) test-element-stub insert script for amp-ad when script is not included FAILED
	TypeError: element.build is not a function
	    at /tmp/d604d52773fa921a683cdc7505270bc8.browserify:20430:21 <- /usr/local/google/home/dinghongfei/code/amphtml/testing/iframe.js:212:20
Chrome 51.0.2704 (Linux 0.0.0) test-element-stub insert script for amp-embed when script is not included FAILED
	TypeError: element.build is not a function
	    at /tmp/d604d52773fa921a683cdc7505270bc8.browserify:20430:21 <- /usr/local/google/home/dinghongfei/code/amphtml/testing/iframe.js:212:20
Chrome 51.0.2704 (Linux 0.0.0) test-element-stub not insert script when element is not amp-ad amp-embed FAILED
	TypeError: element.build is not a function
	    at /tmp/d604d52773fa921a683cdc7505270bc8.browserify:20430:21 <- /usr/local/google/home/dinghongfei/code/amphtml/testing/iframe.js:212:20
Chrome 51.0.2704 (Linux 0.0.0): Executed 3 of 3 (3 FAILED) ERROR (0.126 secs / 0.096 secs)
```

**Comment by mkhatib** [comment] 2016-06-07 18:59
@lannka Thanks for filing this. This seems to be related to the usage of the `--files` args in the `gulp test` command - one way to fix this is requiring the elements scripts inside the test now.

Will work on debugging this and see if there's a better way to handle this.

**Comment by mkhatib** [comment] 2016-06-07 21:49
@sriramkrish85 just had a similar issue without `--files` being used. The cause was he wasn't importing the correct source file for the extension inside the test. Simialr to what I mentioned above. 

--files should work but you'd need to require or import the source files for the extensions your code is using otherwise the test will never see them.

Will be closing this bug since `--files` is working as intended.

**Comment by mkhatib** [comment] 2016-06-07 21:59
Ok I was gonna file a separate bug, but this is good. We need to import both `amp-analytics` and `amp-ad` inside the `test-element-stub` to allow the tests to load the extensions.

**Closed** 2016-06-07 23:24 UTC
Labels: Related to: Testing
