### ISSUE TITLE
Runtime intermittently fails to create fixed layer leading to jittery scroll on iPhone

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#2977] opened 2016-04-23 03:18 UTC
I've been seeing intermittent jitter scrolling with a fixed layer on safari/iPhone.

Hooking the phone up to my Mac and debugging I see that on the pages where we see jitter the AMP runtime has failed to move the fixed layer outside the `<body>` tag.  When it does manage to move the layer it scrolls jitter free.

Steps to reproduce:

Load this url on an iPhone and try scrolling.  If Keep reloading and about 20% of the time you'll get a jittery version.

https://www.google.com/amp/s/fresnobee.relaymedia.com/amp/sports/college/mountain-west/fresno-state/article73389102.html?client=safari#scso=uid_0:0

Testing on iPhone 6+ running 9.3.1 (13E238)  using Safari with production (as of 2016-04-22) version of AMP.  `Powered by AMP ⚡ HTML – Version 1460655576651` (both cases)

Screen grab of dom - working version

![image](https://cloud.githubusercontent.com/assets/524856/14758957/1662c3bc-08c6-11e6-9896-40b334aa31ce.png)

Screen grab - jittery version

![image](https://cloud.githubusercontent.com/assets/524856/14758964/3da1bdca-08c6-11e6-8324-47cc43c1e543.png)

**Comment by dvoytenko** [comment] 2016-04-25 22:35
@jpettitt thanks for the report! looking...

**Comment by dvoytenko** [comment] 2016-04-26 15:54
This is a bug - due to the fact that `visibility` CSS is inherited. Being fixed in https://github.com/ampproject/amphtml/pull/3008

**Comment by dvoytenko** [comment] 2016-05-13 16:59
Thanks, @jpettitt. Looking.

**Comment by adelinamart** [comment] 2017-02-10 23:40
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)

**Closed by adelinamart** 2017-02-10 23:40 UTC
Labels: Related to: Performance, Type: Bug
