### ISSUE TITLE
Scrolling not working in Google AMP Viewer on IPhone (iOS 12)

### ISSUE THREAD

**Issue by Svenmay** [ampproject/amphtml#18861] opened 2018-10-22 09:08 UTC
## What's the issue?
AMP page (https://pizza.de/amp/lieferservice/hamburg/?city=hamburg) cannot be scrolled in Google AMP Viewer on IPhone (iOS 12). Works fine when viewed on Android (Chrome).

Briefly describe the bug/feature request.
AMP page in Google AMP Viewer cannot be scrolled when opened on an IPhone. The page always bounces back when trying to scroll down. 
This issue seems to happen only on first load, i.e. reloading of the page on IPhone makes the page scroll again, but that is not always working, only sometimes.

Looking a little bit into the source code of the AMP page, then I would say, that  something with the "-webkit-overflow-scrolling" settings seems to be wrong. De-activating and re-activating of the setting makes the page "scrollable" again. Tested this with a real IPhone using remote debugging.

## How do we reproduce the issue?

1. Open "google.com" on an IPhone. Search for "pizza de hamburg".
2. Click on the AMP result ("https://pizza.de"), i.e. https://www.google.de/amp/s/pizza.de/amp/lieferservice/hamburg/%3fcity=hamburg
3. Try to scroll on the landing page.
4. Repeat steps 1-3 in a Chrome browser for comparison. Scrolling on AMP pages works fine there.

## What browsers are affected?
Safari browsers on IPhones (tested on iOS 12).

## Which AMP version is affected?
Current version.
![screenshot 2018-10-19 at 11 22 43](https://user-images.githubusercontent.com/39521568/47285208-6518fc80-d5ea-11e8-9216-80594140f169.png)

**Comment by jridgewell** [comment] 2018-10-24 16:09
Reopening, trying to see if this is something that should be fixed in AMP without workarounds. Just waiting on a reproduction from @Svenmay

**Comment by aghassemi** [comment] 2018-10-24 16:36
@jridgewell this happen in `amp-lightbox` as well which I will be fixing. Root of the issue is basically this:
"If a scrollable container does not initially have enough content to overflow, when it overflows later, it won't be scrollable" 

https://s.codepen.io/aghassemi/debug/pxxaJj

https://bugs.webkit.org/show_bug.cgi?id=158342

One solution is to always make sure initial render is scrollable by injecting a long 1px hidden "expander" div. This will work in the lightbox case but given SSR, may not be a solution for the page level case.

Toggling `webkit-overflow` will also work, but it has to be done after the content resizes enough to overflow.

**Comment by jridgewell** [comment] 2018-10-24 17:15
Can we add a `onMeasureChanged` handler to lightbox?

**Comment by aghassemi** [comment] 2018-10-24 18:10
I will try `onMeasureChanged(toggle(webkit-overflow))` approach. Not sure how expensive `toggle(webkit-overflow)` is, but we can bail out after the first time `scrollHeight > height`. 

In parallel, trying to escalate https://bugs.webkit.org/show_bug.cgi?id=158342

**Comment by dvoytenko** [comment] 2018-10-30 20:32
The #19007 should be a long-term bugfix for this issue.

**Closed by dvoytenko** 2018-10-30 20:32 UTC
Labels: Category: Presentation
