### ISSUE TITLE
Story keyboard navigation broken within a desktop Player.

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#29149] opened 2020-07-06 17:34 UTC
https://www.industrialempathy.com/new-on-the-web/

> The arrow key advance on desktop seems broken. Sometimes it advances pages, sometimes the whole story, and sometimes it doesn't advance at all.

cc @ampproject/wg-stories

**Comment by Enriqe** [comment] 2020-07-07 15:42
Dupe of #28235

**Closed by Enriqe** 2020-07-07 15:42 UTC
Labels: P2: Soon, Type: Bug, WG: stories
