### ISSUE TITLE
validator --update_tests does not seem to work

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#14989] opened 2018-05-01 17:16 UTC
Based on @alanorozco's findings, the `UPDATE_VALIDATOR_TEST` environment that gets set in Python does not stick when the `node` process runs.

/to @honeybadgerdontcare

**Comment by alanorozco** [comment] 2018-05-01 20:39
Just a note: this occurs in my Linux workstation as well.

**Comment by Gregable** [comment] 2018-05-21 23:10
OK, I can't reproduce. Neither can anyone else I've talked to. So, I'm closing this issue.

There is one minor fix regarding changes that modify a specific test file that will get pushed out soon, but in general this seems to work.

**Comment by Gregable** [comment] 2018-05-21 23:10
Please reopen if you run into this issue.

**Comment by aghassemi** [comment] 2018-05-21 23:21
@Gregable This still happens to me in both of the following scenario:
1- updating the `.html` tests file with an existing `.out` file ( `.out` does not get updated )
2- removing the `.out` file first ( `.out` file does not get generated )

I am testing with latest master in Mac running `gulp validator --update_tests`


@alanorozco Does this still happen to you?

**Comment by alanorozco** [comment] 2018-05-22 01:29
@aghassemi I wasn't able to reproduce the issue.

**Closed** 2018-05-22 23:12 UTC
Labels: Category: Validator, P2: Soon
