### ISSUE TITLE
Make media-based auto-advance progress bar animation more smooth

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#13164] opened 2018-01-30 23:50 UTC
Per MDN, the [`timeupdate`](https://developer.mozilla.org/en-US/docs/Web/Events/timeupdate) event is "thrown between about 4Hz and 66Hz", so we may need to do additional transition states on the progress bar segments to make it appear smooth even when we don't know it will be.

**Comment by aghassemi** [comment] 2018-01-31 00:21
haha I was investigating the exact same thing yesterday for #13083 . Doing a read on `.currentTime` every rAF while video is playing will give you high precision. I hope reading `.currentTime` is constant and fast but not sure, didn't test. I assume updating the progress bar is fully hardware accelerated?

**Comment by newmuis** [comment] 2018-01-31 01:06
We are just doing a `transform: scale`, so I think it should be

**Comment by newmuis** [comment] 2018-02-07 14:14
We will evaluate whether changing the easing function is good enough for practical purposes, or whether we need to evaluate a `requestAnimationFrame`-based approach.

**Comment by gmajoulet** [comment] 2018-06-05 14:54
I think we're happy with the current implementation so far, as it has been working as intended. Closing.

**Closed by gmajoulet** 2018-06-05 14:54 UTC
Labels: Category: AMP Story, P2: Soon, Type: Bug
