### ISSUE TITLE
Design Review 2019-12-04 21:00 UTC (Americas)

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amphtml#25447] opened 2019-11-05 21:38 UTC
Time: [2019-12-04 21:00 UTC](https://www.timeanddate.com/worldclock/meeting.html?year=2019&month=12&day=04&iv=0) ([add to Google Calendar](http://www.google.com/calendar/event?action=TEMPLATE&text=AMP%20Project%20Design%20Review&dates=20191204T210000Z/20191204T220000Z&details=https%3A%2F%2Fbit.ly%2Famp-dr))
Location: [Video conference via Google Meet](https://bit.ly/amp-dr)

The AMP community holds weekly engineering [design reviews](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md).  **We encourage everyone in the community to participate in these design reviews.**

If you are interested in bringing your design to design review, read the [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md) and add a link to your design doc or issue by the Monday before your design review.

When attending a design review please read through the designs *before* the design review starts.  This allows us to spend more time on discussion of the design.

We rotate our design review between times that work better for different parts of the world as described in our [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md), but you are welcome to attend any design review.  If you cannot make any of the design reviews but have a design to discuss please let mrjoro@ know on [Slack](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#discussion-channels) and we will find a time that works for you.

**Comment by mrjoro** [comment] 2019-11-05 21:47
The Analytics Working Group will be presenting their [periodic updates](https://github.com/ampproject/meta/wiki/Working-Group-Updates) at this Design Review (10-15 minutes).

/cc @ampproject/wg-analytics @zhouyx

**Comment by honeybadgerdontcare** [comment] 2019-11-06 22:42
@sbenz and I would like to discuss self-hosted runtime #25026

**Comment by sebastianbenz** [comment] 2019-11-06 22:46
//cc @mattwomple

**Comment by danielrozenberg** [comment] 2019-11-15 20:49
@rcebulko and I would like to discuss #25578 and #25616 respectively, two tangentially related but different change proposals to release process, to introduce a stable ("monthly") release flavour and to introduce automated nightly builds (respectively again)

**Comment by wassgha** [comment] 2019-12-02 23:42
Would like to discuss `amp-next-page` v2 (shouldn't take too long)

**Comment by mrjoro** [comment] 2019-12-04 18:54
FYI we're pushing the Analytics WG update to next week. /cc @ampproject/wg-analytics @zhouyx

**Comment by davidstrauss** [comment] 2019-12-04 19:24
> Would like to discuss amp-next-page v2 (shouldn't take too long) #25826

I commented on the issue as well, but can you please make the design document accessible to the public?

**Comment by sebastianbenz** [comment] 2019-12-04 20:06
Links for the AMP Runtime Self-hosting Proposal:

* [I2I](https://github.com/ampproject/amphtml/issues/25873)
* [Design Doc](https://docs.google.com/document/d/1Wv7jlnTlLYgo9b841W88yblcHJjLI7GhdBKF60IWaWc/edit#)
* [Presentation](https://docs.google.com/presentation/d/1wP4XyZ0I1qvN3TDaDByRoHGrXbEfWDR1FCIPD58wnQA/edit)

**Comment by rsimha** [comment] 2019-12-04 21:32
LTS release (led by @rcebulko):

Overview: A slower release cycle, requested by external partners like Ali express. Not meant to supplant existing weekly v0.js release. Websites will request /lts/v0.js instead of v0.js, and will receive a slower updating RTV.

Caching considerations: Google rewrites canonical urls (just v0.js) to RTV prefixed urls (RTV/v0.js) for caching benefits. This will continue to happen with lts as well. External caches do not currently do this for v0.js, but we will make a metadata file available to enable them to do so if they want.

Internal mechanism within Google: A set of bzl files that contain an RTV number for each release flavor are periodically updated. This will go on to include the LTS release as well.

@rcebulko: Weekly stable release has a release candidate that indicates what the upcoming stable release will be to enable folks to test. Do we need to do something like this for LTS as well? Downside: It necessarily means that LTS version is a few weeks (4) old.

@dvoytenko: How will partners use the lts release candidate?
@rcebulko: We can do this with an opt-in cookie, similar to how we opt in to the weekly stable release candidate.

@nainar: If I am a publisher who notices a bug in stable, can I immediately switch my website from stable to lts?
@rcebulko: LTS isn't strictly meant to work as a roll-back mechanism. Our messaging should encourage websites to use one of stable or LTS.

From diagram: With lts-rc, the time offset between code hitting HEAD and getting released could increase from ~2 weeks to ~8 weeks in the worst case.

@cramforce: It could become confusing if we have a heavyweight process to choose an lts-rc build based on a few weeks' build quality. Instead, we should just stick with a well known schedule. Partners care more about when they can do QA for their websites, rather than which build was chosen as rc.

@honeybadgerdontcare: Can we delay it further by a week to give folks time?
@rcebulko: That's basically what the diagram shows. If we aren't adding too much value by the "best release" process, we should just pick a release on a schedule.

@sebastianbenz: How does this affect platform support? Do platforms (like search viewer) now have to potentially support two versions at the same time?
@cramforce: The answer is yes. There will be some version skew, but platforms will have to live with a wider spread of features. Don't expect this to be a problem in practice.

**Comment by rsimha** [comment] 2019-12-04 21:44
Nightly release (led by @danielrozenberg):

**Overview:** AMP is now receiving way more PRs / commits per release than 2 years ago, making it hard to determine the cause of P0 issues when they pop up. Nightly releases are a way of diverting a small amount of traffic to a new release pushed each weekday, and measure things like errors and performance regressions before releasing to stable.

**Note:** This will need CSI data to be available faster than today (3 days, down to a couple of hours)

_<Description of changes to weekly schedule>_

@newmuis: Would it make sense to separate channels based on day of week? (thinking of the opt-in case)
@danielrozenberg: For that, we have a separate way of opting in to a specific RTV (discussed a few weeks ago)

@choumx: There's a recency problem, because P0s take a while to detect.
@danielrozenberg: This will increase the number of days between when code is checked in and when it is released, so we will have more time to detect P0 issues.

Proposal: Divert 1/10 of the amount of traffic that goes to rc to nightly. RC -> 0.5%, nightly: 0.05%.

@dvoytenko: Once we have a nightly, will we still be able to cherry pick changes to it? @danielrozenberg: Unless it's a serious issue, we should prefer to just wait for the next day's release. And if an issue is discovered in canary, we just roll it back to the previous nightly. Finally, the opt-in RTV cookie can help bisect / debug where an issue originated.

@dvoytenko: For P0s, we'll have to CP changes to canary, nightly, and prod.
@danielrozenberg: Yes, for P0s with older causes, we will have to do a triple cherry-pick.

@dvoytenko: In the P0 scenario, we'd have to kill any old nightly releases that don't have the fix.
@danielrozenberg: Gotcha. Will do.

@twifkak: We should document this in a more permanent way than just I2Is.

@dvoytenko: Will nightlies be subject to release freezes?
@danielrozenberg: They're still going to be promoted manually. Other than that, they shouldn't be subject to restriction.

@dvoytenko: Wouldn't mind promoting nightlies automatically.
@rsimha: That'd be good if we don't promote on holidays, and restrict it to just working days.
@danielrozenberg: Can do.

**Comment by rsimha** [comment] 2019-12-04 22:01
Self hosting the AMP runtime (led by @sebastianbenz):

@sebastianbenz: <see intro / motivation / design in attached preso>

@dvoytenko: Is there a reverse look up to ensure the integrity of self-hosted RTV versions?
@twifkak: Downside: Publishers will have to update all their pages if they have to update their version of self-hosted AMP.

@sebastianbenz: <see section on hosting modes in preso>

@alanorozco: With partial RTVs, what are you locking the RTV to?
@sebastianbenz: To whatever RTV the publisher chooses. Missing versions are downloaded from cdn.ampproject.org, and mismatches will be flagged as console errors.

@sebastianbenz: <see section on amp-geo in preso>

@gregable: There's an alternative where the validator can require that amp-geo is not self hosted.
@sebastianbenz; That could work. It'd be nice to have a better solution. European publishers need this for GDPR compliance.

@sebastianbenz: <see section on tool support, open questions in preso>

@choumx: Do you want to allow this on valid AMP? If so, this will allow publisher origins to not be evergreen AMP, and introduce large skew.
@sebastianbenz: Yes, we want this to be valid AMP.
@dvoytenko: We could limit this to a set of versions, maybe.

**Closed** 2019-12-10 19:36 UTC
Labels: Type: Design Review

**Comment by choumx** [comment] 2019-12-23 18:52
wg-amp4email update: https://github.com/ampproject/wg-amp4email/issues/12

Sorry for the delay.
