### ISSUE TITLE
AMP header parsing should be case-insensitive

### ISSUE THREAD

**Issue by Aerlinger** [ampproject/amphtml#12384] opened 2017-12-08 21:32 UTC
If you have a bug or feature request for AMP please fill in the following template.  Delete everything except the headers (including this text).

## What's the issue?

The AMP client uses case-sensitive response header parsing, but per the HTTP spec, HTTP header keys should case-insensitive (https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html).

In other words, sending a response header of `amp-access-control-allow-source-origin: "*"` does not work, however, `AMP-Access-Control-Allow-Source-Origin: "*"` does work.

The issue is with the response header lookup defined in: https://github.com/ampproject/amphtml/blob/3d5d78c55881c26bdbe94000248882f10c49180b/src/service/xhr-impl.js#L400

## How do we reproduce the issue?

1. Step 1 to reproduce
Create an AMP page using a feature that makes an ajax request to some endpoint (E.g. http://jsbin.com/sufokidenu/edit?html,output)

2. In the response to that endpoint use lowercase for the AMP response header:
"amp-access-control-allow-source-origin": "*"

3. The client will fail with the following error on invalid header (despite this being a valid header):
`Response must contain the AMP-Access-Control-Allow-Source-Origin header`

Why does this matter? Some server applications (e.g. flask, http.py) will downcase all headers automatically.

## What browsers are affected?

All browsers

## Which AMP version is affected?

All versions

**Comment by aghassemi** [comment] 2017-12-08 21:49
/to @jridgewell Not sure if native implementation is wrong, our polyfill is wrong o both...

**Comment by jridgewell** [comment] 2017-12-08 22:45
Did you forget to [include](https://github.com/ampproject/amphtml/blob/16e216dd61ab1f0bbdbd6b99306c011e30674224/spec/amp-cors-requests.md#ensuring-secure-responses) `Access-Control-Expose-Headers: AMP-Access-Control-Allow-Source-Origin`? https://jsbin.com/cicoji/edit?html,output

**Comment by aghassemi** [comment] 2018-02-23 02:16
I have verified on https://ampbyexample.com/components/amp-list/ that it is case-insensitive. Likely what @jridgewell mentioned is the root cause of the issue.

Closing, @Aerlinger please feel free to reopen if you believe this is still an issue.

**Closed by aghassemi** 2018-02-23 02:16 UTC
Labels: Category: Runtime, P2: Soon, Type: Bug
