### ISSUE TITLE
Error: null is not an object (evaluating 'a.style')

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#22765] opened 2019-06-10 17:42 UTC
```
Error: null is not an object (evaluating 'a.style')
at style (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/src/style.js:119)
at element (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/src/style.js:157)
at (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/extensions/amp-lightbox-gallery/0.1/swipe-to-dismiss.js:252)
at adjustForSwipePosition_ (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/extensions/amp-lightbox-gallery/0.1/swipe-to-dismiss.js:356)
at (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/src/service/resources-impl.js:1032)
at state (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/src/service/vsync-impl.js:459)
at tasks (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/src/service/vsync-impl.js:417)
```

go/ampe/CLnKvM_Z8pSelwE

**Comment by sparhami** [comment] 2019-06-10 17:48
This is a dupe of #22533

**Closed by sparhami** 2019-06-10 17:48 UTC
Labels: Type: Bug

**Comment by Enriqe** [comment] 2019-06-10 17:50
Oops, thanks @sparhami
