### ISSUE TITLE
layout media attribute does not work in IE 11 

### ISSUE THREAD

**Issue by eike-hass** [ampproject/amphtml#6347] opened 2016-11-25 16:33 UTC
The media attribute does not seem to work on IE 11. Since the Browser is out of scope for AMP this might not be a high priority issue, but it might be worth investigation since IE 11 still has some coverage (especially on corporate machines)

## How do we reproduce the issue?

1. open IE 11
2. visit https://jsbin.com/kohagif/
3. notice all three carousels are shown

## What browsers are affected?

<= IE 11

## Which AMP version is affected?

Version 1478801557976

**Comment by aghassemi** [comment] 2016-11-28 04:22
Related: https://github.com/ampproject/amphtml/issues/2577 

@dvoytenko There seems to be cases where the IE media work-around in #2577 still doesn't fix the wrong IE media evaluations.

**Comment by dvoytenko** [comment] 2016-11-28 18:45
/to @camelburrito to take a look. We did do a pass on fixing media API on IE, but possibly not all cases have been addressed by that.

@eike-hass To clarify: is this Windows desktop or phone?

**Comment by camelburrito** [comment] 2016-11-28 19:08
@mkhatib can you take a look at this and find the cause (i might not have time this week)

**Comment by mkhatib** [comment] 2016-11-29 23:29
Alright. Debugged this, this is not related to media query evaluation in IE. This has to do with a bug in IE 11 that the IE team are not going to fix, `element.classList.toggle` does not support a second `force` parameter and hence AMP runtime is double-toggling the element class `-amp-hidden-by-media-query` ending up removing it on a second call to `applySizesAndMediaQuery`.

Working on a fix now, @dvoytenko, do we want to create a helper `dom.toggleClass` method that polyfill this in IE or should we just use `add/remove` explicitly?

My guess this might affect other parts of AMP, so will do a sweep where are we using toggle with a force param.

**Comment by dvoytenko** [comment] 2016-11-29 23:35
Yes, we have to prohibit `classList.toggle` and instead implement it in `dom.toggleClass` via `has/add/remove`. 

(Having a WAT moment)

**Closed** 2016-12-01 23:26 UTC
Labels: Type: Bug
