### ISSUE TITLE
Autocomplete support for textbox field in AMP forms

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#3403] opened 2016-06-01 20:52 UTC
As a follow on to #3343, which will introduce support for form fields, including text box, let's also consider how to add autocomplete support.

/cc @mkhatib

**Comment by Sungodragon** [comment] 2016-10-22 23:13
Guys what can we do for this in search for products

**Comment by rudygalfi** [comment] 2016-10-24 18:27
@Sungodragon Supporting features like product search is a use case envisioned for a feature like this.

**Comment by heiwen** [comment] 2017-01-16 02:56
+1

**Comment by aghassemi** [comment] 2017-02-12 21:15
closing as duplicate of #6625

**Closed by aghassemi** 2017-02-12 21:15 UTC
Labels: P1: High Priority, To be deprecated - Related to: Content, To be deprecated - Type: Request, Type: Feature Request
