### ISSUE TITLE
Ensure amp-custom is used in all examples and docs for <style> tags

### ISSUE THREAD

**Issue by jmadler** [ampproject/amphtml#532] opened 2015-10-08 15:22 UTC
(other than the opacity one)

**Comment by cramforce** [comment] 2015-10-08 15:24
The right way to ensure this is to add them to the validator test.

**Comment by jmadler** [comment] 2015-10-08 15:28
There's a validator test for documentation?

**Comment by Meggin** [comment] 2015-12-09 21:32
I've done my best to make sure <style> tags are <style amp-custom>. Agree we should automate this in validator. Should I raise a different kind of issue then to make sure this happens? Having worked a bit with the validator for ampproject.org, I've got a few suggestions for the validator, so I'll put together some thoughts on what that might be and create one or more issues for tracking.

**Comment by sriramkrish85** [comment] 2015-12-09 21:44
@Meggin FYI we will be removing amp-custom once the validator for the new amp-boilerplate is ready

**Comment by ericlindley-g** [comment] 2016-02-06 00:37
Can someone speak to whether this can be closed?

**Comment by powdercloud** [comment] 2016-02-06 00:43
Just to clarify, the status quo is that amp-custom is still required, even though we do have the new boilerplate supported at this point.
The dependencies on amp-custom are these two:
- In the validator, the presence of this attribute makes it easier to identify the intended autor stylesheet. So, slightly better error messages especially while both the old and the new boilerplate are allowed.
- In our CDN, a match for the author stylesheet is currently performed as well by looking for this attribute.

**Comment by dvoytenko** [comment] 2016-02-09 23:06
Ideally, eventually, some time in the future, in a galaxy... I'd like `amp-custom` to be gone.

**Comment by bpaduch** [comment] 2017-02-07 15:30
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)

**Closed by bpaduch** 2017-02-07 15:30 UTC
Labels: Great First Issues, Related to: Documentation, To be deprecated - Type: Request, To be deprecated - Type: Task
