### ISSUE TITLE
Going Back functionality on PWAMP

### ISSUE THREAD

**Issue by Amanrazdan** [ampproject/amphtml#22921] opened 2019-06-19 06:41 UTC
As discusses with @westonruter in https://github.com/ampproject/amp-wp/issues/2628 there is a prevailing issue in amp html that involves dynamic back button functionality like browser back button support IOS devices where in PWA on physical amp button is present.

Generally used JS call `<button onclick="goBack()">Go Back</button>

<script>
function goBack() {
  window.history.back();
}
</script>`
but thats not valid JS 

#5225 is the same issue that is still not resolved.

Please guys take it seriously as without back button we wont be able to create PWAMP application for IOS Devices

**Comment by westonruter** [comment] 2019-06-19 12:42
What about `AMP.goBack`? This is supported action: https://amp.dev/documentation/guides-and-tutorials/learn/amp-actions-and-events

**Comment by aghassemi** [comment] 2019-06-19 13:20
To @dvoytenko and @choumx, need for cross doc back functionality has come up a few times and seems important for @Amanrazdan's use case.

**Comment by Amanrazdan** [comment] 2019-06-20 04:16
@westonruter tried using AMP.goBack doesn't work which originally requested at #5225 . This is still not resolved

**Comment by aghassemi** [comment] 2019-06-21 17:38
related: https://github.com/ampproject/amphtml/issues/5225

**Comment by dhruva205** [comment] 2019-06-23 01:14
> What about `AMP.goBack`?

this works as going back with the cases where  pushState() functionality of amp is implemented and also works on navigation applied on amp components (sections) only. It does not effect/work as the back button(go back in history) as the  physical back button of an android mobile (which is not present in ios).

**Comment by choumx** [comment] 2019-06-24 19:19
Looks like a dupe of #5225.

**Closed by choumx** 2019-06-24 19:19 UTC
Labels: Type: Bug
