### ISSUE TITLE
javascript validator allows '*' css selector.

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#4759] opened 2016-08-29 21:09 UTC
Adding `<style amp-custom> * { margin: 0 }</style>` to the base minimum amp doc still passes the JS validator despite the '*' selector being illegal.  

![image](https://cloud.githubusercontent.com/assets/524856/18067560/2397af0c-6df2-11e6-9fd4-c86aa7ef47f7.png)

**Comment by Gregable** [comment] 2016-08-30 20:09
tl;dr: I think the correct solution is to update the spec to remove the constraint.

The problem is that there are plenty of other ways to effectively form a `*` selector, such as `:not(foobar)` or `:nth-child(n)`. Even if we could enumerate all of these, you could then form sets of selectors whose union is the `*` selector.

It's also possible we want to leave this in the spec, but simply not enforce it. @dvoytenko for more thoughts.

**Comment by jridgewell** [comment] 2016-08-30 20:18
Re: https://github.com/ampproject/amphtml/pull/3375

**Comment by Gregable** [comment] 2016-08-30 20:26
Thanks @jridgewell . I'm closing this one in favor of the older issue, since they cover the same concern.

**Closed by Gregable** 2016-08-30 20:26 UTC
