### ISSUE TITLE
AMP Validator does not support option attribute in SVGs

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#29607] opened 2020-07-31 08:17 UTC
Actual behavior: when combining an SVG with amp-selector, the validator does not accept the option attribute:

>  The attribute `option` may not appear in the tag `path`

```
 <svg fill="#7c7c7c" stroke="#fff" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 1360">
      <path option="A" d="M391.5 624.8l-1.8 3.1-.7.8-7.8 2.6-.9.5-.5.4.1.3.6.6 1.4.9.3.4-.1.8-.4 1.1-.4 1.3-.3 1-.1.5-.3 1.1-.5 1.3-.5.8-.5.7-1.2.9-.5.8-.4.8-.5 1.3-.3.6-.4.4-1.4.9-1.4 1.2-.8.6-1.2.4-2.1 1.3-.9 1-.5 1.2-.1.9v.9l-.1.6-.4 1.4-.5.4-1.2-.3-.6.2-3.8 3.1-.5.1h-.9l-4-.8-2.1-1.7-.5-.8-.1-.5.2-1.7.1-.6-.2-1.7-.7-1-.4-.4-.4-.2-.8.1-1.5-.8-2.2-1.6-.9-.5-.7-.2-1.7.9-4.5 1.2-5.6 2.9-.4.4-.4.8-.1.8v.4l.2.7 1 1.3.4.9.1.8.3 2-.1 1.6.1.7.4.2 2.3.4.6.4.3.5v.7l-.3.7-.5 1.5-.4.5-.4.3-4.5.2-1.1.5-2.8 2.1-.8.1-2.3-.7-.5-.3-1.1-.2h-.6l-1.4.2-2.6.9-2.3.3-1.8-.1-.8.2-2.5 1.2-2.1.5-.6.5v.3l-.7 1.1-1.2.7-.9.8-.3 1.2-.3.4-3.6 3.7-2.3 3-.6 1.1-1.1 2.4-.3 1 .1.5.4.4.4.5.7.4.4.4.2.5.2 1.2.2.5.4.4.5.3 1 .1h.5l.6-.3.3-.3.6-1.1.5-.5.5-.2 2.2-.2 2.3-.6 2.4-1.8.5-.2.5-.1.4.2.2.2.1.5v.3l-.4 1.1v.5l1 .5.3.4.5 2.2.2.9.6 2.9.1.8.7 3.5.1 1.1v1.1l-.2.9-3.5 3.9-2.2 3-.2.4-.1.5.2.4.9 1.6.2.4v.9l-.1.4-.2.3-2.8 1.5-1.4 1.2-.3.1h-.5l-3.4-.9-11.2.1-.4 1.4.4.8.4.7.8 1.5.2.8.1.5-.2.7-.1 1 .1 1.1.7 2.4.2 1v.6l-.7 1.3-1.2 1.4-.4 1-.4 1-.6 1.1-.2.7-.3.5-.5.3-.9.2-.7.8-1.3 3.1-1 1.9-.1 1.3v2.7l-.2.7-.3.4h-.3l-1.2-.3h-.6l-1.9 1.3-2.9 2.8-.4.6.1.9v.8l-.3.7-2.2 1.8-.6.3-.5.2-1.5.1-1.5.2-1.8-.3-.6-.5-1-2.2-.3-.4-.4-.2-1.3.1-.7.4-1.4 1.7-4.7 4.2-.6 1.1-.3.3-2.1 1.5-.3.5-.8 2.2-5.2 4.5-.6.7-.1.7.2.5.7.4.1.5v.7l.3.4 2.4 1.9.5.5.3.5.1.6-.6 4.5-.3 1.4-.3.4-.3.3-1.1.2-.8.8-1 2.4-3.1-1.9-1.2-.3h-.6l-2.7 1.3-.6.1-.3-.4-.2-1.3-.3-.9-.2-.6-1.8-3.2-4.6-6-1.1-2.2-.1-.7.1-1.3.3-1.6v-1.5l-.2-1.3-.6-2.8-.4-1.1-.3-.6-.3-.1-.6.1-1.4.7-.7.1-.9-.5-1.2-1-3.3-3.7-.8-.8-2.9-1-1-.6-.4-.4-.2-.6.3-1.5.2-.7.3-.7.5-1.6.4-2.5-6.4-1.7-1.4.4-3.4 3.3-.2.8-.1 1.1.4 4.3.1.8.4 1 .4.3.2.6.2.8.1 1.9-.1.8-.3.5h-.4l-2.5-1-.7.4-1.7 2.1-.6.5-4.1 2.5 2 2.1.5 1 .1.8v1l-.3.8-.3.2-.5.2h-.3l-.4-.4-.3-.5-.6.5-1 1.8-.3.4-.4.2-3.4 1.3-1.1.6-.4.5-.4.6-.4 1.3-.4.5-.4.3-1.9-.4-1.1.1-.9.4-3.4 2.1-9.1 2.5-4.1-.3-2.6.7-.7.9v.2l.4.6v.4l-.1 1.3v.6l.1 1.3-.1.8-.7 1.1-.2.8-.2.7.1 1-.1.5-.2.3-2.9 2.2-.5.2-5 1.5-1.3.2-6.1-.4-.4-.5-.1-.6-.3-.7-.3-.4-.8-.4-.7-.2h-.3l-.3.2-.3.9-.9 2.1-.8.3-2.6 2.8-1.2.3-2.3-.9-.5.1-.3.2-.2.7-.3.7-.6.9-.7.4-.5.1h-.4l-1.7-1-1.4-.1-1.1.4-5.7 4.1-3 1.2-2 .2-.9.3-.6.3-.3.5-.2.5-.7 1.3-1.6 2-2.6.8-.5.6.1.8.2.7.1 1.2.1 1.6-.2 3.4-.8 1.5-.8 1-1 .2h-.5l-.7-.1-.7-.3-.7-.4-.7-.6-.6-1.1-.7-1.3-.1-.5-.7-.1-4.1 1.6-1.8 1.1v.3l.1.8.1.7-.1 1-.6 1.5-.3.9v.6l.1.3.3.3 1.5.6.6.6.3.8-.1 2 .2 1.6.2 1.3.3.7.2.6 1 1.5.3.6.2.6.2 1-.2.7-.2.5-.3.2-2.7.5-5.7 1.9-1.8-.4L92 849l-.7-.7-1.2-.8-.9.1-.6.5-.8.7-1.6.8h-1.1l-.6-.1-.2-.4.2-.4.6-1.2-.3-.6-.7-.6-1.9-1-.9-.3-.5-.1-.8.5-.6.2-4.4.7-.5.2-.2.2-4.9 3.6-1.8.7-.7.2-.4-.3-.4-1.9-.3-.5-.4-.5-1.8-.9-.6-.6-.3-.4-.1-.4-.5-.9-.8-.7-.5-.2-.5.1-.5.5-.2.4.1.9 3.5 5.7.3.6-.1.5-.6.5-2.4 1.1h-2.7l-.1-1.1-3.8-6.6-.1-2 .7-2.3.8-4 .1-2.8-.4-.6-.8-.2-1-1.5-.5-1.8-.4-1.5.3-1.4 1.2-1.2-2-.1L47 826l-1.6-.8-.5-.3-.5.3-3.7 1.2-1.1-.1-.9-.7-.9-1.9-.9-.8.9-1.5-1.3-.1-.9-.4-.1-.8.9-1.3-1.9-2.3 2-3.1 3.5-2.9 2.4-1.5v-.6l1.2-1.5.8-1.5-.2-1-7.6-.2-2.2-1.2-1.3-2.5 1.5-.9-6.6-10.2-2.1-2.1-1.8-.1-4.3 1.2-1.5-.2-.4-1.4.4-1.9-.1-1.6-1.8-1-.1-.3v-.6l.2-.3.2-2.3-.7-1-1.1-.8-.8-1.4-.4-2.2 1.6.4 1.6-1.5.5-2-.2-1.6-.1-1.5 1-1.7 1.5-.9 2.4.2 1.2-1.4.7-1.8v-1.4l-.9-3.5.2-1.2.6-.9.2-.7-3.6-1.2-2.5-1.7-.9-.9-.2-1.3-.2-2.5.4-1.5.7-1.4-.2-.9-3.9.4-2.9-.9-1.5-.2-1.5.4-2.8 1.4-1.5.3-.1-4.4-1.7-4.9-.6-4.1 3-1.6 1.6.9 1.2 1.6 1.5 1.4 2-.2 1.3-1.5 2.1-4.4 1.5-1.7 10.1-7.9 6.2-3.4 1.6-2.2-2.3-2.1 2.5-2.1.9-.5-2.5-.8-5.5 3.7-2.5-1.4-.8-3.2.3-3.9.9-3.5 1.2-1.9 2.3-2.8 5.5-10.3 1.2-1.1 2.7-2 1.1-1.5.6-2.2.3-3.8.7-1.5-1.7-2 .2-3.2.8-3.7.4-3.5-.5-3.2-.8-5.7-4.4-5.1-7.2-10-.5-2.2.6-2.5 1.3-3.9-7.4-3.2-2.5-3.2 1.4-5-1-1.1-2.5-1.9-1.2-.6-3.2.1-1.1-.4.1-1.9L13 606l.1-3.6-1.4-3.4-2.5-1.9.4-1.6 1.8-1.3 4.4-.8 2.2-.9 2.2-1.7 1.6-.8 4.4-1.2 3.5 1 4.3 1.1-1.4-2.4-4.1-4.2-1.3-1.1 3.7-2 3.5 1.7 3.5 2.8 3.7 1.5 3.4-.7.9.1.7.8 1.2 2.1.5.6 4.2.7 1.8 1 .3 2.8 4.1-1.2.4-1.7-.9-4 7 2h2.2l1.8-.8 5.4-4.1 10.8-3.7 9.7-.3 2.9-1.6 2.5-3.1 2.5-4.5.9-1 .8-.1.6-.6.1-2.1-.3-1.2-.5-.9-2.9-3-7.1-4-2.3-.7-1.8-1.2-.2-2.7.8-1.8.9-.5 1.2-.1 1.3-.6.9-1.2.8-2.2.6-1 1.9-1.9 1.7-1 7.1-.8 1.3-1.3 2.4-4.9 2.2-2.2 4.6-2.1 2.2-1.9 2.6-4.2 1.1-1.4 4.9-2.9.3-.9-.3-.6 2.9.2 4.5-1.9 1.5-1.2.8-.8.6-.5 15-.7 4.5-1 5.2-3.6 1.6-1.5.6-.3.4-.3 2.8-.6 1.2-.6.8-.6 5.6-5.7 5-4.3.6-.3 1.5-.3h.7l2.1.4.3-.1.5-.6.5-.9.3-.3.3-.2.5-1.3.7-2.6.4-.9.5-.7.7-.3.1-.3-.2-.4-.8-1-.8-.4-.3-1-.2-.6 1.3-5.7.6-.8.2-.3.5-.2h.4l7.8 2.4.8.7.4.9.3 1 .9 6.1.3.6.4.5 2.7 1 7.4 4.6.3.4 1.2 1.5.7.3.7.1 7.2-2.8h.5l.7.3.5 1 1 1.2 1 .9 1.4 2.1 2.1 3.8 1 1.6.3.5.1.5-.4.3-.4.2-3.3.5-.5.2-.2.4-.1.5.3 1.1.3.9.7 1 .6 1.1v.5l-.2.5-.7 1-2 2.1-.4.6v.6l.3.8.6 1.2.1.5v.5l-.2.7-.7 1.1-1.4 1.6-.4.6v.5l.3.8.5.4.8.3 1 .1 1.1.2.3.8.2 1.1.4.5.5.3h1.4l2-.4 1.3.1 2 .7.5.3.4.3v.7l-.4 1.1-1.1 2.3-.7 2.2v.9l-.3 1-.4.8-1.2.3-1.4.1-2.1.4-2.7 1.3-1.9 1.5-1.3 1.4-.2 1 1 2 .4 1.1.9 2.9.3.2.5.3 3.1 1 1.8 1.1.5.5h.5l.6-.4 4.7-4.5 1.7-.9 3.9-.7 4 1.5 7.6-2.9 2-1.2 1.3-1.2.7-1.2 1.9-2.3 3.5-3.1 13.8 4 .7-.2.6-.4.2-.2.3-.6.9-2.6.3-.8.5-.5 4.4-2.8 1-.9.6-.6.6-.9.6-1.1.5-1.2.2-.7-.1-.4-1.2-1-2.3-1.6-.2-.1-.3-1.7-.2-6.4.2-6.5-.1-3.1-.4-3.1-.7-3-1-2.8-.6-1.3-.8-1-3.2-2.3-7-3.3-.8-1.2-.6-.9-2.2-7.3 2.5.9h2.5l.4.1.8.4 1 .3 6.1-.8 1.9-.9.8-.7.4-.6.2-.6.9-4.4.2-.6.2-.3.7-.6 1-.6 1.2-1 .5-.5 2.2-.3 5.4.1 1.7-.3 5.4-2.7h1.2l1.8.8.9.9.9.7 3 5.5.3 1.6.1 1.1v.7l-.3 1.7v1.6l.2.6.4.8.1.5-.1.6-.3 1.9-.1 1 .1.9.2 1.1.4.7 1.2.3 11.2 1.2 3.5-.4 3.2-1.2.7-.4 7.3-1.6.5-.8.3-.5 1.6-5.1 1.1-2.4.6-.8 2.9-3 6-3.2.5-.2.6.2.6.3 1.5 2.3.6.5.4.3.4.1.9.2.3.3v.6l-.5 1.3-.4.7-.6.5-1 .8-.3.3.2 1.7 1.9 6-3.5 5.8-1.9 4.2-.5.6-1.2.5-.6.3-.9.8-.9.1-2.5-.3-.6.1-.5.2-.4.5-.3.7-.7 1.8-.2 1.2-.4 4.9-.2 1.6-.3 1-.2.6v1l.4.8.3.3.4.3 2 .5 3.6 1.7 2.4.5.7.4-.3.4-2.3 1.7-.8.7-.3.9v.5l.4 1 .4 1 .2 1.5-.2.4-.5.2-2.4-.2-3.4 1 .7 1.8 1 2.4.2.6.2.9v1.2l-.2.4-.5.8-.4 1-.1.5.2.2.6-.1 1.3-.4 1.6-.2 1.4.1 2.2-.3 7.8 1.1.8.5.4.6-.1.8-.6 1.5.1.9.9 1 3 1.3 1.3 1.7.1 1.1v.7l-.1.5-1.2 2.1-.1.6.1.6.9 2.9 1.3 3.1.1.5-.2 1-.4.9-.3.4-.6.5-.7.4-.2.5v.8l-.2.5-.4.4.5.5 1 .7 2.7 1.4 1 .2.5-.2v-.3l.1-.5.4-.7.6-.5.5-.1h1l4.2 1.9.1.4-.1 1-1.2 4.8-.6 1.1-.5.5-.8.8-.2.3.2.2h.6l2.8-.5 1.5.1 2.5 1.3.6.9.4.9.2.9.2 1.3-.2 2-1.6 4.6 1.1.2 1.1-.2 2-.9.6-.1 4.8.2 2.5-.4 1.1-.4.7-.4.6-.2.3.2.4.3-.3 1.1-.3.6-.5 1-1.1 1.3-.1.4v.4l.4.6h.6l.9.3.3.3.1.5-.8.8-.1.6-.1.8.1 1.9-.1 1.4-.7 2.2-1 2.6-.3.5-.6.8-.6.6-1.5.8-.4.5-.3 1.2-.4.9-.7.8-.2.3-.1.8v2.1l.3 2.1.1.9v.5l-.6.8-.1.6.1.8.2 1.3-.1.6-.3.4-.7.5-.3.3-.2.4-.2.6-.1.9v1l.1.6.3.9.3.3 1.6.1 5.1-1.6z" />
      <path option="B" ....
```

Expected behavior: `option` attribute should be allowed on every element.

Example: [Full Code](https://jsbin.com/kuwafavayo/edit?html,output) 

//cc @Gregable

**Comment by honeybadgerdontcare** [comment] 2020-08-25 01:59
@sebastianbenz this is curious. The example given shows that the first `path` with `option="A"` does indeed pass but the rest do not. When tested against an internal C++ version of the validator, all instances of `path` with `option` pass (see cl/328249158). This is most likely due to a difference in the C++/JavaScript versions handling reference points. See that amp-selector allows `option` [attribute](https://github.com/ampproject/amphtml/blob/master/extensions/amp-selector/validator-amp-selector.protoascii#L83).

The expected behavior mentioned above states that the `option` attribute should be allowed on every element. What do you mean by `every element`? All tags? Only SVG tag and their children? Could you point to some standards documentation for `option` as an attribute?

Thanks!

**Comment by sebastianbenz** [comment] 2020-08-25 17:03
In this case I meant all `path` elements. Might be worth checking if this is a systemic problem applying to more SVG specific elements.

**Comment by Gregable** [comment] 2021-01-29 01:26
What's going on is that the javascript validator does not believe you are closing your `<path>` tags. It sees each `<path />` as nested under the previous, despite the trailing `'/>'`.

The second `path` is no longer a child of `<amp-selector>` so the reference point no longer applies, and we use this (https://github.com/ampproject/amphtml/blob/67b2bf1e36a01b5b1d2bb0e176b5fb8939984db5/validator/validator-main.protoascii#L2390) tagspec to match instead, which doesn't allow `option`.

In HTML, the `<path />` syntax has no meaning and the `/` is just a parse error which gets ignored. Inside an SVG, we are no longer parsing HTML, we are parsing SVG, which is an XML syntax so the parse is actually different.

The javascript parser doesn't know how to parse SVG/XML, only HTML, while the C++ parser is more sophisticated.

There is a workaround available (use `</path>`) and this won't affect production, just the validator testing tools.

**Comment by Gregable** [comment] 2022-01-10 21:37
This now works by nature of the Javascript validator being replaced with the C++ one. @caoboxiao fyi

**Closed by Gregable** 2022-01-10 21:37 UTC
Labels: Type: Bug, P3: When Possible, WG: caching, Validator: Type: HTML Parsing
