### ISSUE TITLE
PROD - TypeError: undefined is not an object (evaluating 'id(a).renderStarted') (anonymous function)

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#7803] opened 2017-02-26 08:54 UTC
Looks like this PR is causing the error,
Initial load analytics event (#7312)

Not sure of severity lower as needed.

MAC Os - Safari

**Comment by camelburrito** [comment] 2017-02-26 08:56
<img width="1172" alt="screen shot 2017-02-26 at 12 51 56 am" src="https://cloud.githubusercontent.com/assets/1037311/23338384/5a2c2eb2-fbbe-11e6-9477-8f3d02f8b3d6.png">

**Comment by dvoytenko** [comment] 2017-02-27 19:44
This looks like an unrelated error due to the same-origin iframes that are prohibited by `amp-iframe`.

**Comment by jridgewell** [comment] 2017-02-28 00:05
Closed by #7821?

**Comment by amphtml-team** [comment] 2017-02-28 06:32
No. Mostly unrelated...

**Comment by jridgewell** [comment] 2017-02-28 18:40
Then is this a dupe of 7804?

**Comment by dvoytenko** [comment] 2017-02-28 19:08
Agree. It's a dupe. I'll close this one.

**Closed by dvoytenko** 2017-02-28 19:08 UTC
Labels: Category: Analytics, P1: High Priority, Type: Bug
