### ISSUE TITLE
Error: race condition on customElement stubbing

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#9385] opened 2017-05-16 23:30 UTC
has been reported several times. 

seems to be happening on Chrome 4x and SamsungBrowser only
/to @zhouyx

**Comment by jridgewell** [comment] 2017-05-16 23:58
Any more details?

**Comment by aghassemi** [comment] 2017-05-17 00:02
It's a signal @zhouyx has been monitoring for sticky ad , just wanted to inform her it is being seen.

**Comment by zhouyx** [comment] 2017-05-19 18:52
duplicate of #9126

**Comment by zhouyx** [comment] 2017-05-19 18:53
@aghassemi Thanks of let me know. Will remove in next sprint.

**Closed by zhouyx** 2017-05-19 18:52 UTC
