### ISSUE TITLE
Sticky Ad Won't Close in Google Feed

### ISSUE THREAD

**Issue by joelnagy** [ampproject/amphtml#16740] opened 2018-07-14 21:58 UTC
## What's the issue?

Can't close sticky footer ad while pages are loaded in Google Feed.

## How do we reproduce the issue?

1. Using a Pixel device (Or Android device that uses the Google launcher) slide to the left to the Feed.
2. Open an AMP article (find one with a sticky footer ad)
3. Click the × icon to close - ad won't close.
4. Scroll up to reveal the "VIEW X RELATED PAGES" bar.
5. Click the × icon now and the ad closes.

## What browsers are affected?

In app browser of the Google Feed.

## Which AMP version is affected?

Might depend on sites. I've seen on multiple sites, Gamespot.com is one I saw most recently.

**Comment by jasti** [comment] 2018-07-14 22:31
@joelnagy Thanks for filing the issue. 
Having a hard time reproducing it when I tried it with other sites that load a sticky and have a "View X Related Pages" Widget. 
Assigning it to one of my teammates to see if they can reproduce it. 

In the meantime, if you are able to easily reproduce it and not too much trouble, would appreciate a video.

**Comment by joelnagy** [comment] 2018-07-15 14:38
I can reproduce it every time for any article that has a sticky and the related pages bar. Here's a link to a video I just posted to Dropbox: https://www.dropbox.com/s/3cl2t2jazzh7cbf/20180715_103016_edited.mp4?dl=0

**Comment by jasti** [comment] 2018-07-19 23:52
Looks like this is an issue even on non-AMP pages. Whenever there is a "VIEW X RELATED PAGES", the  bottom X% of the viewport is un-clickable - even links.
We are trying to reach out to an internal team at Google who owns the feature to look into this.

**Comment by zhouyx** [comment] 2018-08-16 17:12
Close as this is not an AMP's issue and has been internally tracked.

**Closed by zhouyx** 2018-08-16 17:12 UTC
Labels: Category: Ads, Internally Tracked, P2: Soon, Type: Bug
