### ISSUE TITLE
Extension does not turn blue if there is an unexpected HTML tag in the head

### ISSUE THREAD

**Issue by mcmd** [ampproject/amphtml#12835] opened 2018-01-15 20:02 UTC
## What's the issue?

The AMP validation extension does not turn blue if there is an expected HTML tag in the head

## How do we reproduce the issue?

[This url ](http://output.jsbin.com/hiqekefiqa/)is a simple piece of code that renders in the browser, but does not trigger the extension to turn blue.

[This other url](http://output.jsbin.com/qahemojoka/) is the same code without the <img> tag in the head. The extension now turns blue.

I've also reproduced with a <div> tag

## What browsers are affected?

I'm on Chrome Version 63.0.3239.132 (Official Build) (64-bit)

## Which AMP version is affected?

I'm on v 1.1.4 of the extension

**Comment by aghassemi** [comment] 2018-01-15 23:55
@mcmd AMP has very restricted rules on what can be inside `<head>` also `<img>` is not allowed anywhere regardless of `<head>` or not. 

Is there a particular reason you believe AMP should support certain tags in `<head>`?

**Comment by mcmd** [comment] 2018-01-16 14:21
Hi,

(Typo: should be "**UNexpected**" in the title)

The issue is for the canonical, non-amp version of a page. For a non-amp page, if there is an AMP version linked in the head with the amphtml link, the extension will turn blue:

![image](https://user-images.githubusercontent.com/868584/34993474-5a40aca2-fac8-11e7-8de4-0a569946ee9f.png)
What I'm saying is that if there is an <img> tag in the head before the amphtml link, the extension won't tell blue (it does turn blue if the <img> tag is after the amphtml link, though).

Thanks!

**Comment by aghassemi** [comment] 2018-01-19 02:24
The `blue` only indicates there is an AMP version of the article (not that this article is AMP itself). Clicking on it will take the user to the AMP version. The way it detects there is an AMP version is it by looking at `link rel="amphtml" ` which is the official way of saying there is a related AMP page. 

Closing the issue as this is working as intended.

**Closed by aghassemi** 2018-01-19 02:24 UTC
Labels: Type: Discussion/Question

**Comment by aghassemi** [comment] 2018-01-19 15:21
@mcmd When there is an `<img>` in `<head>`, although chrome "renders" it also moves `<img>` and everything after it (including the `<link>`) out of head and into the `<body>`, that's why detection does not work. `link` is not in `head` anymore.

We can change the code to what @tomayac suggested but then it will go `blue` if someone puts the `link` in `body`, which is not how other platform detect AMP versions of documents. So one may end up with Extension going blue but a platform not seeing their AMP page which is a bad false positive.

**Comment by tomayac** [comment] 2018-01-19 16:01
Good point about the `<head>`. It can be changed to the below (probably should use a variable to avoid double-checking):
```javascript
return document.head.querySelector('link[rel="amphtml"]') && document.head.querySelector('link[rel="amphtml"]').href || '';
```
