### ISSUE TITLE
Google Analytics 4 for AMP

### ISSUE THREAD

**Issue by aurbanczik** [ampproject/amphtml#32628] opened 2021-02-12 10:47 UTC
Is there a way of including GA4 in Google-Amp ?

**Comment by kristoferbaxter** [comment] 2021-02-12 14:27
Duplicate of https://github.com/ampproject/amphtml/issues/24621

Closing this issue in favor of the one @micajuine-ho and the Google Analytics team provides updates on.

**Closed by kristoferbaxter** 2021-02-12 14:27 UTC
Labels: Type: Discussion/Question
