### ISSUE TITLE
Bug in amp-carousel

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amphtml#5421] opened 2016-10-05 10:38 UTC
In desktop, when scrolling thru amp-carousel slides, the images shimmer vertically.

The best place to view this bug is on https://www.ampproject.org/

Go to "What contributors are saying".

We have dozens of amp-carousels and they all began demonstrating this behavior begining about 2 weeks ago.

The shimmer is more pronounced in Firefox than in Chrome.

---

update:
https://github.com/ampproject/amphtml/issues/5407
seems to identify the same problem

**Comment by ericlindley-g** [comment] 2016-10-05 15:57
Thanks for flagging this— @camelburrito is investigating (closing this and marking as duplicate of #5407

**Closed** 2016-10-05 16:03 UTC
Labels: Closed: Duplicate
