### ISSUE TITLE
Investigate why cleaning up iframes break integration tests on Safari

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#3315] opened 2016-05-24 18:39 UTC
Currently in `_init_tests.js` we remove all test `iframe`s to allow chrome to collect the memory. We only do this on Chrome because tests on Safari seems to break.

**Comment by cramforce** [comment] 2016-07-01 19:45
I think this is because of #3709

**Comment by adelinamart** [comment] 2017-02-08 00:54
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)

**Closed by adelinamart** 2017-02-08 00:54 UTC
Labels: To be deprecated - FixIt, To be deprecated - Related to: Testing
