### ISSUE TITLE
amp-video controls are covered by amp-image placeholder

### ISSUE THREAD

**Issue by jesse** [ampproject/amphtml#540] opened 2015-10-08 17:37 UTC
Adding a placeholder image for an `amp-video` covers up the controls, making the video unplayable.

Sample markup:
```
<amp-video src="https://once.unicornmedia.com/now/od/auto/0c2129c5-42b8-49e0-aa4c-f560c7bc0ba7/af7e1dc1-2f79-49f6-9ebd-9ef0559a1ed5/67217152/content.mp4?&amp;UMPTPARAMcmsid=3424&amp;UMPTPARAMvid=cweGp4dzoAvj1R8JCK5C8jEJUDgiU-YA&amp;UMPTPARAMplayer=brightcove" width="480" height="320" layout="responsive" controls="controls">
  <amp-img width="480" height="320" layout="responsive" src="https://cdn2.vox-cdn.com/thumbor/nAT-TlnnCfO0v4wpEXJSvxsQcbc=/0x1080/assets.volume.voxmedia.com/production/0c58b7912f319797579c2b763aad72b2/SNP_011_thumb.jpg" placeholder="placeholder"></amp-img>
</amp-video>
```
which renders:

![screen shot 2015-10-08 at 1 35 59 pm](https://cloud.githubusercontent.com/assets/5949/10374512/8da36d46-6dc1-11e5-84b2-c00ab4b7226f.png)

Clicking the image does not trigger the play action.

**Comment by dvoytenko** [comment] 2015-10-08 17:40
Thanks for the report. Placeholders in amp-video are definitely currently broken. We'll fix soon.

**Comment by dvoytenko** [comment] 2015-10-08 17:42
Dupe of #406.

**Closed by dvoytenko** 2015-10-08 17:42 UTC

**Comment by jesse** [comment] 2015-10-08 17:44
Thanks @dvoytenko
