### ISSUE TITLE
🌸 Cherry-pick request for #27319 into #27275 (Pending)

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#27353] opened 2020-03-23 04:03 UTC
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #27319 | #27319 |     YES     | NO | NO | #27275                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

Significant jittering on iOS for some domains. See b/149328043 for more details.

# Mini-postmortem

There will be a postmortem in the form of a filed WebKit issue.

## Summary

The new WebKit issue has been filed: https://bugs.webkit.org/show_bug.cgi?id=209486

## Impact

- The set of affected pages is difficult to estimate. Essentially any page overflowing on the X axis can exhibit the flicker.
- The fix is not completely harmless: it's somewhat intrusive. Among other things, it forces a minimal height on the body element.

## Action Items

- Track https://bugs.webkit.org/show_bug.cgi?id=209486
- Engage our partners to see if this can be fixed soon.

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by cramforce** [comment] 2020-03-23 14:08
Wow, I was hoping we didn't need to go there.

Approved.

**Comment by rsimha** [comment] 2020-03-24 00:09
@rcebulko Let’s CP this to beta / experimental first thing tomorrow morning and hold off stable by a few hours / a day until we have error numbers for the new beta release.

**Comment by rcebulko** [comment] 2020-03-24 14:54
Certainly.

**Comment by rcebulko** [comment] 2020-03-24 14:56
Update: The canary is cut based on HEAD at (up to) 11am PST on Tuesday. In other words, this PR is already in the branch that I'm about to cut for canary. Closing this since it doesn't actually require cherry-picking.

**Comment by rsimha** [comment] 2020-03-24 15:03
This needs to be CP'd into last week's beta channel before it goes out to stable this week.

**Comment by rcebulko** [comment] 2020-03-24 15:05
My bad, misread the cherry-pick request

**Comment by dvoytenko** [comment] 2020-03-24 19:22
Post-mortem has been updated. The WebKit issue has been filed: https://bugs.webkit.org/show_bug.cgi?id=209486

**Comment by rcebulko** [comment] 2020-03-24 20:11
This is now in opt-in

**Comment by rcebulko** [comment] 2020-03-25 16:07
This is in 1% since 8PM EST last night.

**Comment by rcebulko** [comment] 2020-03-25 18:32
This is now in Stable. Does it need to be cherry-picked onto LTS? If not, I think we can close this.

**Comment by rsimha** [comment] 2020-03-25 18:49
> This is now in Stable. Does it need to be cherry-picked onto LTS?

Based on https://github.com/ampproject/amphtml/issues/27353#issue-585912861, looks like the answer is no.

**Comment by rcebulko** [comment] 2020-03-25 18:54
> > This is now in Stable. Does it need to be cherry-picked onto LTS?
> 
> Based on [#27353 (comment)](https://github.com/ampproject/amphtml/issues/27353#issue-585912861), looks like the answer is no.

I see that, but I want to verify. LTS was promoted from Stable last week. It seems to me like this is a Safari change, not a bug that we introduced. Given that LTS is new and the cherry-pick process/criteria less clear, I'd like to confirm that this is low enough impact that we're okay with the bug persisting in LTS for a month.

**Comment by dvoytenko** [comment] 2020-03-25 19:13
No need for LTS.

**Closed** 2020-03-25 19:14 UTC
Labels: Cherry-pick: Beta, Cherry-pick: Experimental, Type: Release

**Comment by dvoytenko** [comment] 2020-03-26 00:12
Unfortunately we have a regression on some very specific CSS. We have to roll this feature back :(. I will send cherrypick shortly. Apologies everyone.
