### ISSUE TITLE
AMP-Redirect-To doesnt work anymore?

### ISSUE THREAD

**Issue by baert93** [ampproject/amphtml#25432] opened 2019-11-05 13:20 UTC
Hi, since yesterday no amp redirect via php is working anymore. 
header("AMP-Redirect-To: https://littlehelps.de/index.php");
exit();
I didnt change anything at my code and it worked fine all the time so i assume that you updated something? 

## What browsers are affected?

all browsers on all devices

## Which AMP version is affected?

amp-version="1911042323000"

**Comment by aaron-renovationbrands** [comment] 2019-11-05 15:52
We can confirm the same behavior.

**Comment by aaron-renovationbrands** [comment] 2019-11-06 16:51
Anyone care to comment why this quit working?
Is it related to another issue?

**Comment by nainar** [comment] 2019-11-06 18:24
@aaron-renovationbrands @baert93 can we get a link to a live page that is down?

**Comment by aaron-renovationbrands** [comment] 2019-11-06 18:29
https://www.americantinceilings.com/pattern6/

Not "Add to Cart" here,  the post action is on the slider(interstitial) titled "Skip & Continue To Cart" .
Products add to cart (navigate manually).

**Comment by caroqliu** [comment] 2019-11-06 18:59
Thanks for reporting the issue! This is the PR to revert: #25242

**Comment by nainar** [comment] 2019-11-06 21:57
The fix has landed in master. We are verifying the fix and will be rolling out to production ASAP.

**Comment by caroqliu** [comment] 2019-11-07 16:19
@aaron-renovationbrands @baert93 Can you confirm that the behavior is restored on your respective pages?

**Comment by aaron-renovationbrands** [comment] 2019-11-07 17:18
Working.
Thanks!!

**Comment by caroqliu** [comment] 2019-11-07 17:28
The issue is resolved since #25470 hit production, post mortem on cherry-pick #25473 to follow.

**Closed by caroqliu** 2019-11-07 17:28 UTC
Labels: P0: Drop Everything, Type: Bug, WG: ui-and-a11y

**Comment by baert93** [comment] 2019-11-07 19:48
yeah its working fine, ty for the fast solution!

**Comment by caroqliu** [comment] 2019-11-07 19:59
@baert93 Could you still provide the steps to reproduce on your website? It would be great to have as much information as possible for the post mortem.
