### ISSUE TITLE
prevent clicks on top 80%

### ISSUE THREAD

**Issue by normanfan** [ampproject/amphtml#33030] opened 2021-03-03 11:31 UTC
I found that you have a new feature to prevent clicks on the top 80%. We want add links on the other area of ​​the card besides yop 80%, how can I do it

**Comment by newmuis** [comment] 2021-03-03 20:03
Hi @normanfan, I assume this is relating to stories.

This is actually not a new feature; it's been a format consideration since links were introduced in 2018.  You can, however, use an `<a>` tag anywhere on the screen as a descendant of `<amp-story-grid-layer>`; users will just be presented with a tooltip.

Seems like this is a duplicate of #28620.  Please feel free to reopen if you don't feel the issue has been adequately addressed.

**Closed by newmuis** 2021-03-03 20:03 UTC
Labels: Type: Discussion/Question, WG: stories
