### ISSUE TITLE
Strange tag surfaced by error format code WARNING_TAG_REQUIRED_BY_MISSING

### ISSUE THREAD

**Issue by dandv** [ampproject/amphtml#6968] opened 2017-01-10 20:34 UTC
The error [WARNING_TAG_REQUIRED_BY_MISSING](https://github.com/ampproject/amphtml/blob/master/validator/validator-main.protoascii#L3192) has the following format:

> "The tag '%1' is missing or incorrect, but required by '%2'. This will soon be an error."

In [several](https://github.com/ampproject/amphtml/blob/c44a48fbb1dbd0de0b5a9e20f8f69bb920705dde/extensions/amp-sticky-ad/0.1/test/validator-amp-sticky-ad.out#L2) test [cases](https://github.com/ampproject/amphtml/blob/edaada49213aefdba7fda0f6597d5271fa4dfb45/validator/testdata/feature_tests/mandatory_dimensions.out#L34), `%1` gets expanded to `amp-ad extension .js script` or `amp-video extension .js script`, which don't really look like a tag. What causes that, and can we clarify these errors? A partner is getting the `amp-ad extension .js script` one.

(In other cases, %1 expands correctly to an actual tag, [e.g. amp-carousel](https://github.com/ampproject/amphtml/blob/5c31f4c2d7d84084b1d164be70e695a5f194833a/validator/testdata/feature_tests/spec_example.out#L3).)

**Comment by jridgewell** [comment] 2017-01-10 20:42
Dupe of https://github.com/ampproject/amphtml/issues/6966?

**Closed by jridgewell** 2017-01-10 20:42 UTC

**Comment by Gregable** [comment] 2017-01-10 20:44
Yes.
