### ISSUE TITLE
<amp-img> do not load on scroll horizontally when it is out of initial viewport

### ISSUE THREAD

**Issue by Gaitz** [ampproject/amphtml#25397] opened 2019-11-04 09:10 UTC
## What's the issue?

`<amp-img>` do not load on scroll horizontally when it is out of initial viewport.

## How do we reproduce the issue?

https://gaitz.github.io/AMP-issues/amp-img-load.html

[Source code](https://github.com/Gaitz/AMP-issues/blob/master/amp-img-load.html)

1. Empty cache and hot reload.
2. Scroll first image block horizontally to the end.
3. Scroll vertically to second image block.
4. Scroll second image block horizontally to the end.
5. Will see image # 5 and # 6  are not loaded.
![image](https://user-images.githubusercontent.com/5541565/68109349-4c456580-ff25-11e9-83fd-075b5c0dd3c9.png)

where two image blocks use same image sources.

## What browsers are affected?

Already reproduce on 

1. `https://playground.amp.dev/`
1. Macbook Pro, Mojave Version 10.14.6  
    1. on Google Chrome Version 78.0.3904.70 (Official Build) (64-bit)
    1. on Safari Version 13.0.3 (14608.3.10.10.1)

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 1910302211460

**Comment by sparhami** [comment] 2019-11-04 17:21
This looks to be a duplicate of #24929, which is fixed in the canary release. The demo page works if I join the dev channel via https://cdn.ampproject.org/experiments.html.

**Closed by sparhami** 2019-11-04 17:21 UTC
Labels: Type: Bug

**Comment by Gaitz** [comment] 2019-11-05 06:23
Hi @sparhami, 

I try my demo page on all device I have with Version 1911042323000 today, release just few hour ago and contain pr #25172 which try to solve issue #24929.
However, the same issue still exist.

Am I misunderstanding the release time?

## Snapshots
* Firefox
![image](https://user-images.githubusercontent.com/5541565/68183059-3e9be880-ffd6-11e9-8ad4-894aaf9f7350.png)
* Chrome 
![image](https://user-images.githubusercontent.com/5541565/68183170-891d6500-ffd6-11e9-9099-6c5e8e2f0e76.png)
* Safari
![image](https://user-images.githubusercontent.com/5541565/68183204-a3efd980-ffd6-11e9-91e0-47e701a28083.png)

**Comment by sparhami** [comment] 2019-11-05 19:20
> Hi @sparhami and thanks to your response,
> 
> I try my demo page on all device I have with Version 1911042323000 today, release just few hour ago and contain pr #25172 which try to solve issue #24929.
> However, the same issue still exist.
> 
> Am I misunderstanding the release time?
> 
> ## Snapshots
> * Firefox
>   ![image](https://user-images.githubusercontent.com/5541565/68183059-3e9be880-ffd6-11e9-8ad4-894aaf9f7350.png)
> * Chrome
>   ![image](https://user-images.githubusercontent.com/5541565/68183170-891d6500-ffd6-11e9-9099-6c5e8e2f0e76.png)
> * Safari
>   ![image](https://user-images.githubusercontent.com/5541565/68183204-a3efd980-ffd6-11e9-91e0-47e701a28083.png)

@Gaitz I cannot reproduce the issue myself (it works when I scroll down the page, then horizontally) on Chrome, Safari or Firefox, but looking at the PR that was supposed to fix it, it seems the behavior is behind an experiment flag that has not be launched yet.

I think we should move the discussion to #24929 to keep it all in one place.
