### ISSUE TITLE
Consider abstracting a way to halt element build-layout-cycle at any point

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#3942] opened 2016-07-06 23:22 UTC
Currently the only way to do this is by throwing an error (including using `assert` statements). However, in some cases, throwing an error is not the intended behavior.

We currently add duplicate checks in both `buildCallback` and `layoutCallback`. For example, experiment checking.

``` javascript
  buildCallback() {
    if (!this.isExperimentOn_) {
      user.warn(TAG, `Experiment ${TAG} disabled`);
      return Promise.resolve();
    }
    ...
  }
  ...
  layoutCallback() {
    if (!this.isExperimentOn_) {
      user.warn(TAG, `Experiment ${TAG} disabled`);
      return Promise.resolve();
    }
    ...
  }
```

This become more and more cumbersome the more soft-halts an element need to do depending on different checks.

**Comment by jridgewell** [comment] 2016-07-07 16:45
I believe we can change from `user.warn` to `user.assert`. If you throw during `#buildCallback`, it'll blacklist the element.

**Comment by dvoytenko** [comment] 2016-07-07 16:58
Good point. Blacklisting an element is likely the best option and then no need to duplicate code in `layoutCallback`

**Comment by mkhatib** [comment] 2016-07-07 22:06
This might work for the example above, but some usage we need to try to avoid throwing errors to avoid publishers confusion when they see errors in the console for things that are not actually errors. For example, in `amp-app-banner` depending on the current platform the user is viewing an AMP doc on we might want to halt the element cycle (for example, if on android chrome and not embedded we want the browser builtin banner to kick in), in this case `user.assert` would throw an error - instead I'd rather just have an `[info]` log to explain that this is expected behavior.

**Comment by dvoytenko** [comment] 2016-07-07 23:48
I don't think an error is a huge deal or a warning - since it will give a clear reminder: "do not publish this yet". If you do want a warning, you can throw a dev error and report `user.info`. DEV errors are not reported to the console, I don't believe.

**Comment by adelinamart** [comment] 2017-02-07 21:59
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)

**Closed by adelinamart** 2017-02-07 21:59 UTC
Labels: To be deprecated - Related to: AMP Core, Type: Discussion/Question
