### ISSUE TITLE
Comments in amp-custom style tag can't contain "!important"

### ISSUE THREAD

**Issue by YonahKarp** [ampproject/amphtml#17685] opened 2018-08-23 14:44 UTC
As noted in the [documentation](https://www.ampproject.org/docs/design/responsive/style_pages#disallowed-styles), amp-custom styles aren't allowed to use the "!important" qualifier.

The validator seems to be picking up false positives in comments such as this one:

    /**
     * Some comment about `!important`
     */
    div{
          color: white;
    }

The style itself doesn't use important, but the validator complains:
> "text inside tag 'style amp-custom' contains 'CSS !important', which is disallowed."

Which, I guess, is an accurate representation of the situation, but isn't what the *[documentation](https://www.ampproject.org/docs/design/responsive/style_pages#disallowed-styles)* says is disallowed. Either the documentation or the validator should be updated to match one another.

**Comment by pbakaus** [comment] 2018-10-15 19:34
@Gregable this is really a validator issue, I think referring to `!important` in a comment block should be allowed. Would it be hard to fix this?

**Comment by Gregable** [comment] 2018-10-15 20:15
This is a duplicate of #12651

**Closed by Gregable** 2018-10-15 20:15 UTC
Labels: Category: Validator, P2: Soon, Related to: Documentation, Type: Bug
