### ISSUE TITLE
Autosuggest onblur/loss focus 

### ISSUE THREAD

**Issue by Minx-SigEp** [ampproject/amphtml#14328] opened 2018-03-30 18:43 UTC
## What's the issue?
I spoke with @danielrozenberg at the AMP hackathon in Chicago and he suggested filling a bug for this. There does not appear to be a way to blur/ change focus for the auto-suggest outside of the form containing the auto-suggest field. The expected behavior is for the user to be able to change focus to any other area of the page an have the auto-suggest be hidden as if you clicked in a different field. 

## How do we reproduce the issue?

1. Navigate to https://ampbyexample.com/advanced/autosuggest/preview/
2. In the City text box type "Denver"
3. Click in the "First Name" field. The auto-suggest is hidden 
4. Click in the City textbox again. The auto-suggest will be shown
5. Click on the "Autosuggest" heading at the top of the demo page. The auto-suggest is **NOT** hidden as expected. 

## What browsers are affected?

All browsers

## Which AMP version is affected?

1522350285886

**Comment by cvializ** [comment] 2018-03-30 19:10
Hello! Thanks for reporting this. I believe this is not a bug, and I apologize for any confusion. The ampbyexample.com example is implemented this way because of how the examples there need to be written. The code that closes the autosuggest box `on="tap:AMP.setState({showDropdown:false})"` would be on the `body` tag, or high enough in the DOM tree that the user could comfortably tap out of the box to close it. But in the examples the `body` tag cannot be shown as part of the example code, so I put the code on a wrapper `div` instead.

I'm going to close this issue since it is expected behavior with a solution, but feel free to comment or reopen in you have more questions or disagree.

**Closed by cvializ** 2018-03-30 19:10 UTC
