### ISSUE TITLE
amp-list doesn't fetch when layout="fill" is specified 

### ISSUE THREAD

**Issue by maranag** [ampproject/amphtml#30194] opened 2020-09-11 02:04 UTC
#What's the issue?

amp-list doesn't fetch when layout="fill" is specified 

## How do we reproduce the issue?

Adding layout="fill" on an amp-list component

This was first reported on Aug 3/2020.  Currently can be seen live (https://m.madsister.co.kr/amp/index.html) --> but this link may not last (may be fixed using other/no layout)

Working (not layout=fill)
![image](https://user-images.githubusercontent.com/18673621/92841616-8624a980-f41d-11ea-8157-6ccaba44a432.png)

Not Working (layout=fill)
![image](https://user-images.githubusercontent.com/18673621/92841731-aa808600-f41d-11ea-8470-f4250d8b203f.png)

Network activity shows no fetch performed

Parent element size does not seem to affect this behavior

**Comment by kristoferbaxter** [comment] 2020-09-11 06:10
Added @samouri since this appears to be related to the recent move to IntersectionObserver within Resources.

Can we confirm the fix you landed also covers this case?

**Comment by samouri** [comment] 2020-09-11 14:48
I just verified locally that `amp-list[layout=fill]` hit the same IO bug and that https://github.com/ampproject/amphtml/pull/30167 fixes it.

Note that Just switching the layout type from `fixed-height` to `fill` is not expected to work in the playground. [layout=fill](https://amp.dev/documentation/guides-and-tutorials/learn/amp-html-layout/) requires a parent that is positioned either relative or absolute.

**Comment by maranag** [comment] 2020-09-12 01:13
Appreciate investigating this so quickly, all.

Couple of quick questions:

When is this expected to be in the wild?

Also: do we need better documentation around AMP layouts? The only thing
linked to each component is this:
https://amp.dev/documentation/guides-and-tutorials/learn/amp-html-layout/layouts_demonstrated/?format=websites#fill
.. doesnt capture the nuance above which would be useful (with samples).

**Comment by samouri** [comment] 2020-09-22 18:31
> Also: do we need better documentation around AMP layouts? The only thing
linked to each component is this:

There is also a more detailed [overview of the layout system](https://amp.dev/documentation/guides-and-tutorials/learn/amp-html-layout/) that goes into depth with how to use each layout type. It would probably be good to link to it from the layouts_demonstrated page.

> When is this expected to be in the wild?

The fixes to stable/lts should be going out within the next 24-48 hours

**Comment by maranag** [comment] 2020-09-24 03:17
Looks like the fix has been pushed out - thanks.

Unfortunately, it looks like the bug was pushed out to LTS?  This was working previously and now unfortunately the LTS version is experiencing the same behavior as explained above.  Can someone please confirm?

Thanks.

**Comment by samouri** [comment] 2020-09-24 15:22
@maranag: The bug was pushed out to LTS on 8-29. We are making sure the fix behaves well on stable before pushing it out to LTS. You can track progress here: https://github.com/ampproject/amphtml/issues/30320

**Comment by samouri** [comment] 2020-10-02 19:04
Fix should be in both LTS and stable. Closing, but please comment again if you are still able to reproduce the error!

**Closed by samouri** 2020-10-02 19:04 UTC
Labels: P1: High Priority, WG: runtime
