### ISSUE TITLE
[amp-state] - Conditionally check amp-state for data before XHR

### ISSUE THREAD

**Issue by armandAkop** [ampproject/amphtml#19880] opened 2018-12-14 00:46 UTC
## Describe the new feature or change to an existing feature you'd like to see

Question/Request since I can't find it in the docs. Is there a way to check the AMP state to conditionally decide if I should submit the form? For example

```
<form id="my-form" method="POST" action-xhr="https://example.com/api/create-order"
  <input type="text" name="code" />
  <button on="tap: my-form.submit">Enter</button>
</form>
```

My state...
```
{
 codes: ["abc", "efg123"]
}
```

The user types in "abc" into the input box and hit's enter. I'd like to check (maybe in an event called "should-submit" which returns a boolean), in "codes" array if "abc" already exists, if false then not follow through with the form submission.

## Describe alternatives you've considered

One way to get around this is to have the debounced event do the checking and set a flag in the state, disabling/enabling the Enter button. But just wondering if it is possible to do something like above?

**Comment by torch2424** [comment] 2018-12-14 22:45
Triaging to @choumx 😄 Feel free to re-assign.

**Comment by cathyxz** [comment] 2018-12-28 22:31
@armandAkop can you clarify what you would like the button to do if the submit condition fails? Would you like the button to be disabled, or would you like tapping the enabled button to do nothing? The former should be already doable via the alternative you describe. The latter seems like strange UX to have what's basically a sometimes lying button. Would you need to then trigger some notification or modal or have some alternative action trigger if `should-submit` returns false?

**Comment by choumx** [comment] 2019-01-02 22:57
Closing as a dupe of #14661. 

/cc @cvializ

**Closed by choumx** 2019-01-02 22:57 UTC
Labels: Category: Dynamic/Personalized Content, Type: Feature Request

**Comment by cvializ** [comment] 2019-01-03 14:42
I could see this specific case implemented as a binding to an input's `pattern` attribute. e.g.

```html
<amp-state id="codes"><script type="application/json">["abc", "efg123"]</script></amp-state>
<form id="my-form" method="POST" action-xhr="https://example.com/api/create-order">

  <!-- the pattern matches strings that are not contained in the array `codes` -->
  <input type="text" name="code" pattern=".*" [pattern]="'^((?!' + codes.join('|') + ').)*$'" />

  <button on="tap: my-form.submit">Enter</button>
</form>
```

But since bindings are not applied on page load, this would not be a full solution.

**Comment by choumx** [comment] 2019-01-03 16:45
Neat idea!
