### ISSUE TITLE
amp-bind doesn't change img src

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#7296] opened 2017-02-01 22:46 UTC
Issue first seen here https://github.com/ampproject/amp-by-example/issues/586

It appears that changing the `src` of an `amp-img` does not update the `src` of the `img`.

**Comment by choumx** [comment] 2017-02-03 22:55
Most likely due to stale AMP runtime in SW cache. E.g. My cached version was 1482359659944 which lacked the `mutatedAttributesCallback` method. Can't repro after clearing cache.

Please reopen if still reproducible after clearing cache.

/cc @sebastianbenz Perhaps amp-by-example should change [caching strategy](https://googlechrome.github.io/sw-toolbox/docs/master/tutorial-api) from `cacheFirst` to `fastest` to avoid these types of problems for new/experimental components?

**Comment by sebastianbenz** [comment] 2017-02-06 19:27
I can still reproduce it via this page
https://callous-cheetah.gomix.me/amp-bind-xhr.html (with dev-channel only).

**Comment by cramforce** [comment] 2017-02-09 01:56
This still happens for me. There is an error in the console:

```
cdn.ampproject.org/v0/amp-bind-0.1.js:16 Uncaught (in promise) TypeError: Cannot read property 'enqueue' of undefined _reported_
    at lb (cdn.ampproject.org/v0/amp-bind-0.1.js:16)
    at jb (cdn.ampproject.org/v0/amp-bind-0.1.js:14)
    at cdn.ampproject.org/v0/amp-bind-0.1.js:127
    at Promise (<anonymous>)
    at Tb (cdn.ampproject.org/v0/amp-bind-0.1.js:126)
    at Rb (cdn.ampproject.org/v0/amp-bind-0.1.js:124)
    at cdn.ampproject.org/v0/amp-bind-0.1.js:123
    at <anonymous>
```

**Comment by choumx** [comment] 2017-02-09 15:33
Ah, that's actually the chunk-related bug in 1486166232176 that was fixed in #7374. I'll re-close when I verify the fix is live on this week's canary.

**Comment by choumx** [comment] 2017-02-10 20:07
Verified fixed in new canary 1486754279878.

**Closed by choumx** 2017-02-10 20:07 UTC
Labels: Category: Dynamic/Personalized Content
