### ISSUE TITLE
[amp-stories] page indicator bar progress is misaligned

### ISSUE THREAD

**Issue by karlcow** [ampproject/amphtml#22816] opened 2019-06-13 01:48 UTC
## What's the issue?

Progress indicator are not correctly displayed at the top of the viewport on mobile Firefox.

## How do we reproduce the issue?

1. With Firefox Mobile on Android (at least from version 65 to latest nightly 69) Fresh profile.
2. Visit https://www.washingtonpost.com/graphics/2018/business/amp-stories/self-driving-car-waymo-robo-taxi/?noredirect=on
3. Tap on the right side, multiple times to advance pages

Actual:
The progress indicators are partly colored.

Expected:
The indicator are correctly displayed.
 

[![Screenshot Description](https://webcompat.com/uploads/2018/12/2aea994c-bcd6-413f-9fd1-8a5ca3a09d81-thumb.jpeg)](https://webcompat.com/uploads/2018/12/2aea994c-bcd6-413f-9fd1-8a5ca3a09d81.jpeg)

## What browsers are affected?

Firefox Android 
version 65 to current Nightly 69

## Which AMP version is affected?

N/a

Originally reported on https://github.com/webcompat/web-bugs/issues/22085

**Comment by newmuis** [comment] 2019-06-13 13:36
@Enriqe maybe we can address this when looking into other progress bar changes

**Comment by newmuis** [comment] 2019-07-18 19:10
This is a duplicate of #21898, which was just fixed.

**Closed by newmuis** 2019-07-18 19:10 UTC
Labels: P2: Soon, Type: Bug, WG: stories
