### ISSUE TITLE
AMP Story not opening properly in Desktop Chrome

### ISSUE THREAD

**Issue by psdtomanythings** [ampproject/amphtml#13655] opened 2018-02-25 16:23 UTC
Briefly describe the bug/feature request.

The AMP Stories when opened in Desktop Chrome browser have stories only 50% of the screen height. The issue is because of a <span> tag being added just before the closing body tag. The span tag takes up 50% of the height leaving the rest 50% for Amp story. The issue can be resolved removing the **height:100% !important for "amp-story[standalone]"**

## What browsers are affected?

Google  Chrome

## Which AMP version is affected?

The issue is with the AMP Stories.

![half-height](https://user-images.githubusercontent.com/22929187/36643773-49d9120a-1a76-11e8-87a7-6d7c4c98d09b.jpg)

**Comment by newmuis** [comment] 2018-02-25 19:10
Thanks for the report @psdtomanythings.  Do you have any browser extensions installed?  Does this happen when using a guest profile or incognito window in Chrome?  Does the `<span>` have any ID or classname that may indicate where it is from?

**Comment by psdtomanythings** [comment] 2018-02-26 09:38
@newmuis - There was a span tag before the closing body tag. It had a specific ID. I just did update my chrome and the span tag is gone. The new version is 64.0.3282.167 . All the CSS is loaded from /extensions/amp-story/0.1/amp-story.css

**Comment by psdtomanythings** [comment] 2018-02-26 14:41
So here is the span element "<span id="sbmarwbthv5"></span>". This span tag was may be added by some extension. We are trying to find the extension.

**Comment by QES** [comment] 2018-02-26 16:51
This doesn't seem to be a generic issue it works fine on my amp stories on Chrome (64.0.3282.167)
https://amp.sportsmole.co.uk/stories/

**Comment by newmuis** [comment] 2018-02-26 18:22
This seems like a duplicate of #12140; we should take measures to defend the layout of the page against browser plugins randomly injecting things.  @psdtomanythings please feel free to reopen if you feel this is indeed not caused by a browser plugin.

**Closed by newmuis** 2018-02-26 18:22 UTC
Labels: Category: AMP Story, P2: Soon, Type: Bug

**Comment by natevw** [comment] 2020-07-10 22:33
FWIW, this weird span is apparently from the "Better History" extension. (Credit for tracking down: https://gist.github.com/fbcotter/82d029d781b5b2fc2025cde22daf4f95#gistcomment-2380364)
