### ISSUE TITLE
amp-script Script hash not found or incorrect for amp-script

### ISSUE THREAD

**Issue by HuyetCongTu** [ampproject/amphtml#33340] opened 2021-03-18 02:09 UTC
![image](https://user-images.githubusercontent.com/49687422/111562499-eaf3fe80-87c8-11eb-87ad-4193752e6716.png)

i added google amp's code instruction exactly same but it doesn't work

Although I have added in «head»
`<meta name="amp-script-src" content="sha384-YCFs8k-ouELcBTgzKzNAujZFxygwiqimSqKK7JqeKaGNflwDxaC3g2toj7s_kxWG" />
`
and
`<script async custom-element="amp-script" src="https://cdn.ampproject.org/v0/amp-script-0.1.js"></script>`

**Comment by kristoferbaxter** [comment] 2021-03-23 13:32
Does this sha match the contents of the script element?

**Comment by AaronMLB** [comment] 2021-08-11 13:42
Hi @kristoferbaxter, I'm currently having a huge problem with hashing that looks like it may be similar to @HuyetCongTu's issue.

Firstly, I'm using PHP - although not WordPress - so have taken the hashing function from the official amp-wp helper library: https://github.com/ampproject/amp-wp/blob/2.1.3/includes/amp-helper-functions.php#L1855-L1866

(I have removed my full real script for now and am just using a simple do-nothing test line of code.)

```
function amp_generate_script_hash( $script ) {
	$sha384 = hash( 'sha384', $script, true );
	if ( false === $sha384 ) {
		return null;
	}
	$hash = str_replace(
		[ '+', '/', '=' ],
		[ '-', '_', '.' ],
		base64_encode( $sha384 )
	);
	return 'sha384-' . $hash;
}

$script = 'const message = "hello world";';

$meta = '<meta name="amp-script-src" content="' . amp_generate_script_hash($script) . '">';

echo '<amp-script layout="flex-item" script="xhr-script"></amp-script>
<script id="xhr-script" type="text/plain" target="amp-script">
' . $script . '
</script>';
```

(The JS has to be inline, not from an external .js file, as the real code includes a var set depending on the context of the page.)

The encryption that PHP generates: ```sha384-qSunBbSMWdcE2eZwVfXmDbx_bwqS0Y6k0oDonRt-B-w-9Q0lj5aLGcX-IFIb5FmG```

The encryption AMP says it expects: ```sha384-kJclaAuXKOxfcYGQzjos1Uefz80fQWBJBHXEEEKyNvrWh74pQFsVuz0OUn6tIcDn```

I've been going around in circles for almost 24 hours on this but am completely stumped.

My best guess was something around AMP's utf8Encode() of the original script string was not being matched in PHP, but I've been unable to figure out any other variation of code that does work, and as I say, the PHP I'm using is taken from an official AMP project, so surely it should be fine...?

**Comment by kristoferbaxter** [comment] 2021-08-11 14:00
I'm not well versed on the amp-wp project, so I'll add @westonruter in for thoughts.

**Comment by kristoferbaxter** [comment] 2021-08-11 14:08
Here's the relevant example from the AMP Playground.

```html
<!DOCTYPE html>
<html ⚡>
  <head>
    <meta charset="utf-8" />
    <title>My AMP Page</title>
    <link rel="canonical" href="self.html" />
    <meta name="viewport" content="width=device-width" />
    <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
    <script async src="https://cdn.ampproject.org/v0.js"></script>
    <script async custom-element="amp-script" src="https://cdn.ampproject.org/v0/amp-script-0.1.js"></script>
    <style amp-custom>
      h1 {
        margin: 1rem;
      }
    </style>
    <meta name="amp-script-src" content="sha384-PuXE6zYKxsw748uII1YTQMpHsJLYTsj_nfEQuh9cOxKzdejrnope6irIP1mglDby ">
  </head>
  <body>
    <h1>Hello AMPHTML World!</h1>
    <amp-script layout="flex-item" script="xhr-script"></amp-script>
    
    <script id="xhr-script" type="text/plain" target="amp-script">
	  const message = "hello world";
	</script>
  </body>
</html>
```

Also, while reproducing I noticed this detail: 

https://user-images.githubusercontent.com/61764/129043527-d9031a3a-05b8-4b3f-a360-9c4311f2b7e5.mov

Looking into the implementation now, but I believe the contents of the script as evaluated on the client might be different when you include the extra characters of space surrounding the script content.

Perhaps try removing extra spacing in your script? 

```php
echo '<amp-script layout="flex-item" script="xhr-script"></amp-script><script id="xhr-script" type="text/plain" target="amp-script">'.$script.'</script>';
```

**Comment by kristoferbaxter** [comment] 2021-08-11 14:13
Tested this theory and it appears to be true.

https://github.com/ampproject/amphtml/blob/main/extensions/amp-script/0.1/amp-script.js#L395

JS on the client uses the entire textContents, which includes new line characters and tabs.

<img width="879" alt="Screen Shot 2021-08-11 at 7 10 34 AM" src="https://user-images.githubusercontent.com/61764/129044835-61b25ee9-b170-4a8a-90fb-bc0aca448f3f.png">

In your example, if you remove the extra characters, including carriage returns and tabs in the output, the sha should theoretically match.

**Comment by AaronMLB** [comment] 2021-08-11 15:22
Right! So PHP is stripping out the whitespace before calculating the crypt, whilst JS includes it. Definitely an odd mismatch of behaviours there.

I did have a look at the whitespace earlier this morning but got the impression the hash AMP was showing was _not_ including it.

I've ended up forcing a fix by stripping ```\t``` and ```\r``` from the ```$script``` **before** either echoing it into the ```<script>``` element or generating the hash. (Also removing ```\n``` results in ```[amp-script] Uncaught SyntaxError: Unexpected identifier```)

**Comment by jridgewell** [comment] 2021-08-11 15:59
> I've ended up forcing a fix by stripping \t and \r from the $script before either echoing it into the <script> element or generating the hash. 

This shouldn't be necessary. The only issue is the newlines you had around the `<script>`'s contents:

```php
// Bad
echo '<amp-script …>
' . $script . '
</amp-script>';
```

This is effectively adding `'\n' . $script . '\n'` into the HTML, and the `hash('sha384', $script, true)` will never match that.

**Comment by AaronMLB** [comment] 2021-08-11 16:07
No luck with that I'm afraid @jridgewell. I'd tried earlier today (and again now, to check my sanity) with both new lines and not, and it's not playing ball.

Current code:
```
echo '<script id="xhr-script" type="text/plain" target="amp-script">' . $script . '</script>';
```

AMP:
```
sha384-H-U5XvlrcUnrHxpMavdMO-UagbVshMG8Y5WBPqghfHNkRqwj7tbrYL31LdrIcPYl
```

PHP (without stripping \t or \r):
```
sha384-tdq1a0JSZxCESslsXi7NkOYSnk2yL_QwlHNqduSDKiSOyL3D1wYVE5qY8d0qdWPd
```

**Comment by jridgewell** [comment] 2021-08-11 18:58
I played around with this, and I think I've narrowed it down to just the `\r` char. When HTML is parsing, it normalizes `\r` and `\r\n` into a single `\n` char, which affects the hashing. If I do a `replace(/\r/g, '')` on the script before hashing and printing into the HTML, it works correctly. Sorry for the confusion!

https://glitch.com/edit/#!/sprinkle-intermediate-pawpaw?path=server.js%3A13%3A38

**Comment by kristoferbaxter** [comment] 2021-08-12 01:34
Sounds like we've found the root cause, I'll close this issue but try to update the documentation to call this out more clearly.

**Closed** 2021-08-12 01:35 UTC
Labels: Type: Bug, WG: performance
