### ISSUE TITLE
FR: amp-action-macro

### ISSUE THREAD

**Issue by dritter** [ampproject/amphtml#19189] opened 2018-11-08 11:32 UTC
It would be awesome to be able to set state via an `amp-bind-macro`.

To give an example, imagine we have two navigations on our page, and want to be able to close both by click on a close button and a backdrop. Currently is is necessary to duplicate the state on tap on each button.

```html
<amp-bind-macro id="closeNavigations" expression="AMP.setState({nav1: {open: false}, nav2: {open: false}})"></amp-bind-macro>
<button on="tap:closeNavigations()">&times;</button> 
<div class="backdrop" on="tap:closeNavigations()"></div>
```
This would make it clearer what a button does (naming things), than have to figure it out by looking at the state and increases code-reusability.

As a bonus these could be stacked:
```html
<amp-bind-macro id="closeNav1" expression="AMP.setState({nav1: {open: false}})"></amp-bind-macro>
<amp-bind-macro id="closeNav2" expression="AMP.setState({nav2: {open: false}})"></amp-bind-macro>
<amp-bind-macro id="closeNavigations" expression="closeNav1(); closeNav2()"></amp-bind-macro>
<button on="tap:closeNavigations()">&times;</button> 
<div class="backdrop" on="tap:closeNavigations()"></div>
```

// cc @sebastianbenz

**Comment by choumx** [comment] 2018-11-08 19:32
Oops, closed this prematurely. 

(A) FYI you should be able to do this today:

```html
<amp-bind-macro id="close" expression="{open: false}"></amp-bind-macro>

<button on="tap:AMP.setState({nav1: close(), nav2: close()})">&times;</button> 
<div class="backdrop" on="tap:AMP.setState({nav1: close(), nav2: close()})"></div>
```

(B) The following would be more concise but less readable:

```html
<amp-bind-macro id="closeNavigations" 
    expression="{nav1: {open: false}, nav2: {open: false}}"></amp-bind-macro>

<button on="tap:AMP.setState(closeNavigations())">&times;</button> 
<div class="backdrop" on="tap:AMP.setState(closeNavigations())"></div>
```

(C) We'd need a separate new feature to de-dupe actions:

```html
<amp-action-macro id="closeNavigations" 
    action="AMP.setState({nav1: {open: false}, nav2: {open: false}})"></amp-bind-macro>

<button on="tap:closeNavigations">&times;</button> 
<div class="backdrop" on="tap:closeNavigations"></div>
```

**Comment by dritter** [comment] 2018-11-09 00:44
Well, setting the states inner values (variant A) makes more sense with increasing state complexity. But that helps a bit anyway. Thanks.

Will B or even C supported some day? Writing `AMP.setState({idOfStateContainer: state })` all over is quite cumbersome.

**Comment by choumx** [comment] 2018-11-09 04:01
I think it'd certainly be nice to have. If this issue proves to be a common issue then we can prioritize more aggressively. 

How bad is the code dupe in your use cases?

**Comment by sebastianbenz** [comment] 2018-11-09 09:35
I'd be definitely in favour of (C), I had several situations in the past where I encountered the same problem. 

1) building a stepper:

```
<amp-action-macro id="nextStep" 
    action="AMP.setState({step: step + 1})"></amp-bind-macro>

<div class="step" [hidden]="step != 0">
   <button on=tap:nextStep>Next</button>
</div> 
<div class="step" hidden [hidden]="step != 1">
   <button on=tap:nextStep> Next </button>
</div> 
<div class="step" hidden [hidden]="step != 2">
   <button on=tap:nextStep>Next</button>
</div> 
```

or performing the same action for different elements:

```
<amp-action-macro id="openInLightbox" arguments=itemId
    action="AMP.setState({item: itemId}), itemLightbox.open"></amp-bind-macro>

<ul>
   <li on=tap:openInLightbox(1)>Item 1</li>
   <li on=tap:openInLightbox(2)>Item 2</li>
   <li on=tap:openInLightbox(3)>Item 3</li>
</ul>
<amp-lightbox id=itemLightbox>
   <h [text]=items[item]></h1>
</amp-lightbox>
```

**Comment by dritter** [comment] 2018-11-09 13:56
@choumx We are still at the beginning with amp-state, so the code-dupe is not that bad ATM, but we are planning to expand our app..

@sebastianbenz :+1: Awesome examples!

**Comment by choumx** [comment] 2018-11-13 23:03
@alabiaga This is a good component candidate.

**Comment by choumx** [comment] 2019-01-11 18:54
Closing as dupe of #19494.

**Closed by choumx** 2019-01-11 18:54 UTC
Labels: Category: Runtime, P3: When Possible, Type: Feature Request

**Comment by alabiaga** [comment] 2019-02-13 20:48
@sebastianbenz @dritter The first iteration of the amp-action-macro is now merged. If you guys can check it out and provide some feedback, it would be much appreciated. Thanks
