### ISSUE TITLE
Support providing the client id to the viewer for storage

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#4029] opened 2016-07-12 18:28 UTC
This allows viewers to not have any logic regarding how to generate IDs.

Tracked at Google under b/30089828

**Comment by peleyal** [comment] 2016-07-20 19:11
The use case is as follow:

1) The runtime sends a cid message to get the base cid from the viewer
2) In case the viewer's storage has the cid it returns it 
--- That's exactly how it works today. However,
3) Otherwise (no cid in storage), the viewer returns an empty cid
3.1) When the runtime gets an empty cid, it knows that it has to generate it itself
3.2) The runtime has to send a new message (STORE_CID maybe?) to the viewer to store the new generated cid.

**Comment by lannka** [comment] 2016-07-27 04:11
Instead of sending the new Base CID in a second message, we can also send it as the payload of the first message. This way:
- saves one round trip of window.sendMessage in case viewer doesn't have base CID yet
- as an exchange, adds the cost of generating random base64 to every getBaseCid() call, even when viewer has base CID.
- simplifies code (no nested promises)

@peleyal how does this sound?

**Comment by peleyal** [comment] 2016-07-27 13:18
SGTM.
I like that it saves a round-trip of window.sendMessage.
I don't like that we will generate it anyway... how expensive is it?

How many times we expect the runtime to ask for a clientid?
If I understand correctly it will happen only once, which is why sending and generating it anyway is a good idea.

Let me know.

**Comment by lannka** [comment] 2016-07-27 18:11
Good question. My originally thought was that we cache base CID at our side once retrieved from viewer. 

However, after taking a close look, I found something confusing. ([code](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/cid-impl.js#L252)).

Assume a user visited several amp pages served from cache, the code implies the following behavior.

**1st visit:**
User visited an AMP page via a viewer. AMP runtime asked viewer for base CID. Viewer generated base CID of `12345` and persisted at viewer side.

**2nd visit:**
User visited another AMP page via a viewer. AMP runtime asked viewer for base CID. Viewer  returned the persisted base CID of `12345`.

**3rd visit:**
User visited another AMP page directly (served from cache), since there's no viewer, runtime created a base CID and persisted in local storage `54321`.

**4th visit:**
User visited another AMP page via a viewer, the base CID in local storage is used at this time: `54321`.

As you can see, the 2nd visit is the pivot point. All visits after that will have base CID of `54321`.

@dvoytenko am I missing anything? Is the behavior intended?

**Comment by lannka** [comment] 2016-07-27 23:08
Talked to @dvoytenko. It's working as intended. 
- In frame embed mode (in a viewer), AMP runtime have limited local storage access (iframe limitation), so it has to let viewer to do it.
- In non-embed mode, AMP runtime will create a different ID. This ID will be used for all later visits, even in a viewer, because it is considered more universal (available in different viewers).

@dvoytenko correct me if I have any misunderstanding.

**Comment by dvoytenko** [comment] 2016-07-27 23:20
@lannka Yes. Correct.

RE:reducing number of post messages

My initial sense is that generating base CID for each impression would be more expensive than a post-message roundtrip. Also, we need to look at how likely the second roundtrip would actually be needed. It sounds like it's only needed very rarely.

**Comment by lannka** [comment] 2016-07-27 23:25
To answer @peleyal's question: 
- unfortunately in viewer mode, it will ask for base CID for every page view. 
- Speed wise, I don't have the number yet. Basically it runs through 2 functions, `crypto.getRandomValues()` and `window.atob()`. They're both browser native function, so I assume it's pretty fast. Anyone has experience on it?

The 2 round-trip solution has some other things we need to consider:
- Right now if viewer fails to generate or retrieve a base CID, `viewer.getBaseCid()` returns `null`, and then runtime will throw. But now we want to attach new meaning to `null`, so once a `null` is returned, how do we know if it's actually a failure in viewer, or it is right time to call `viewer.storeBaseCid()`?
- Once viewer expose such an interface as `storeBaseCid()`, does it need to read before write? Or it should just blindly override?

Given those complications, I'm slightly leaning towards to the single round-trip solution. What do you think?

**Comment by dvoytenko** [comment] 2016-07-27 23:38
> unfortunately in viewer mode, it will ask for base CID for every page view.

That's ok. But there's something we can do about it. Since we now always generate CID, we can always try to store it. It won't always work - but when it does - we win on a roundtrip to viewer.

> Basically it runs through 2 functions, crypto.getRandomValues() and window.btoa()

At least `getRandomValues` works on a separate thread, so we are doing context switching anyway.

> how do we know if it's actually a failure in viewer, or it is right time to call viewer.storeBaseCid()

I think our behavior should be the same. If for any reason we couldn't get Base CID from viewer, we need to generate our own and ask the viewer to store it.

> Once viewer expose such an interface as storeBaseCid(), does it need to read before write? Or it should just blindly override?

Blind override.

> Given those complications, I'm slightly leaning towards to the single round-trip solution. What do you think?

Let's try to estimate the cost of `getRandomValues` + `atob` and go from there. I'm still leaning toward two messages. Mostly because the probability of needing to execute the first message is about 100%, while the probability of needed the store message is much much lower. The only argument I see going for one message is simpler protocol.

**Comment by lannka** [comment] 2016-07-27 23:52
I've created a snippet for `getRandomValues + btoa`, run it [here](https://jsfiddle.net/b649kaf7/3/).
On my desktop, it's `15ms` for `1000` sequential runs. `avg = 0.015ms`.
On my nexus 6, it's `72ms` for `1000` sequential runs. `avg = 0.072ms`.

I think it should not be a concern.

**Comment by jridgewell** [comment] 2016-07-28 15:50
And how fast would a second `#postMessage`  be if it were needed? I think this is going to be faster than generating a throw-away cid for the normal case.

> BTW, I don't think getRandomValues is on separate thread. It's a sync call.

Definitely on the same thread.

> Right now if viewer fails to generate or retrieve a base CID, viewer.getBaseCid() returns null, ... But now we want to attach new meaning to null...?

We could just have the viewer send a message back and have it wait for the response before sending back the original?

**Comment by lannka** [comment] 2016-07-28 16:06
> We could just have the viewer send a message back and have it wait for the response before sending back the original?

Didn't quite understand this part. Could you expand?

The point I wanted to make is: having 2 round-trips complicates the APIs and logic at both sides (viewer and runtime). And I think `< 0.1ms` is a neglect-able cost to pay for it.

**Comment by jridgewell** [comment] 2016-07-28 17:46
The `getBaseCid` waits for a response from the viewer. If the viewer doesn't want to generate the cid, it can send `generateBaseCid` to AMP. AMP will then respond with `generatedBaseCid` back to the viewer. Viewer then uses the response from `generateBaseCid` to respond to `getBaseCid`. (Naming all up for debate here)

> The point I wanted to make is: having 2 round-trips complicates the APIs and logic at both sides 

Why ask for a cid if AMP will just generate it in the request? It just seems wrong.

**Comment by lannka** [comment] 2016-07-28 18:07
> The getBaseCid waits for a response from the viewer. If the viewer doesn't want to generate the cid, it can send generateBaseCid to AMP. AMP will then respond with generatedBaseCid back to the viewer. Viewer then uses the response from generateBaseCid to respond to getBaseCid. (Naming all up for debate here)

That is exactly what I called "complicated protocol and logic".

> Why ask for a cid if AMP will just generate it in the request? It just seems wrong.

I don't see anything wrong here. It's a very common protocol: `getOrCreate()`
If you have doubt, we used in everywhere in AMP, the `getService(serviceId, factory|object)`. Though you can argue in most cases we passed a factory which is lazy called.

**Comment by jridgewell** [comment] 2016-07-28 18:21
Also, don't we sha384 the cid, not `btoa`? https://jsfiddle.net/b649kaf7/5/

**Comment by dvoytenko** [comment] 2016-07-28 18:24
@jridgewell Good point. It's indeed sha384.

**Comment by lannka** [comment] 2016-07-28 18:32
Didn't notice that. But why do we take a random number and then hash it? According to the documentation, `getRandomValues()` is a good enough source for randomness.

> The RandomSource.getRandomValues() method lets you get cryptographically random values. The array given as the parameter is filled with random numbers (random in its cryptographic meaning).
> 
> To guarantee enough performance, implementations are not using a truly random number generator, but they are using a pseudo-random number generator seeded with a value with enough entropy. The PRNG used differs from one implementation to the other but is suitable for cryptographic usages. Implementations are also required to use a seed with enough entropy, like a system-level entropy source.

**Comment by lannka** [comment] 2016-07-29 16:57
The thread is quite long now, let me try to summarize. 

In the case viewer doesn't have a CID yet, we are choosing among the following protocols:
1. runtime sends `get-cid` to viewer. viewer returns `null`. runtime send `store-cid` with a newly generated cid. viewer returns the stored cid
2. runtime sends `get-cid` to viewer. viewer sends `generate-cid` to runtime. runtime generates CID and returns to viewer. viewer store the cid and returns back to runtime.
3. runtime sends `get-cid` to viewer together with a new cid. viewer stores the new cid and returns it back to runtime.

Both 1) and 2) need 2 round trips of postMessage. 
1) has some implications that we need to deal with, as discussed in one of my previous post.
2) needs a 2-way communication between viewer and runtime. if we already have such a sophisticated mechanism, 2) is preferable to 1).

3) needs 1 round trip, with the cost of generating a cid for every pageview even when it's not used. However, according to our experiment, the average time of generating such an ID is less than 0.1ms (with [btoa](https://jsfiddle.net/b649kaf7/3/), with [sha384](https://jsfiddle.net/b649kaf7/5/)).

I prefer 3), because
- 0.1ms is a neglectable cost to pay for a simpler protocol between 2 projects (under different code repositories).
- There will be many viewers, including 3P viewers. Simpler protocol means easier integration and future maintenance.
- We actually gain speed on the cases when we do need a new CID to to persisted. we saved the time for a postMessage round trip, and also saved the tiny latency caused by more complicated code.

**Comment by ericfs** [comment] 2016-07-29 17:07
We have 2-way communication [sendMessage()](https://github.com/ampproject/amphtml/blob/master/src/service/viewer-impl.js#L940) can return a Promise which will contain the response from the viewer.

**Comment by ericfs** [comment] 2016-07-29 17:09
From the Viewer side, either a 1 step or 2 step protocol is fine. The handlers will be simple in either case. The one step approach just means there's one less message to document.

**Comment by redSlug** [comment] 2016-07-29 17:23
lannka, do you mean the runtime sends a post message to the viewer with 'cid' as the message name? I'm not if you are suggesting that 'get-cid' should be sent. From the perspective of an AMP Lite viewer I believe it would make sense to keep the strings as short and concise as possible to reduce bytes. 

With regards to the protocols, from an AMP Lite perspective I would prefer option 3) because it requires the viewer code to have less strings in the code that parses the received messages and less back and forth, which could mean less bytes for the viewer and a faster experience for users with low bandwidth.

**Comment by lannka** [comment] 2016-07-29 17:29
> lannka, do you mean the runtime sends a post message to the viewer with 'cid' as the message name? I'm not if you are suggesting that 'get-cid' should be sent. From the perspective of an AMP Lite viewer I believe it would make sense to keep the strings as short and concise as possible to reduce bytes.

I meant `cid`, `get-cid` was to present the meaning.

**Comment by jridgewell** [comment] 2016-07-29 17:47
>  because it requires the viewer code to have less strings in the code that parses the received messages and less back and forth, which could mean less bytes for the viewer and a faster experience for users with low bandwidth.

In the end, we're talking about the difference between:

```js
// I imagine these return promises.
/**
 * Cid generation as a message, option #2.
 */
handleGetCid(payload) {
  return this.sendMessage('gen-cid');
}

/**
 * Cid provided in payload, option #3.
 */
handleGetCid(payload) {
  return Promise.resolve(payload.autogen);
}

**Comment by dvoytenko** [comment] 2016-07-29 18:20
@lannka The 0.1ms will change however if we (a) we continue to use sha384 and (b) we late-load it as we plan to do in the future, right?

**Comment by alf7** [comment] 2016-07-29 18:24
Just my $0.02: From the viewer perspective, I'm not a fan of (2) sending a request back to get fulfil another request. Either (1) or (3) seem fine and keep the API calls much simpler.

**Comment by lannka** [comment] 2016-07-29 18:35
@alf7 (2) has problems like I listed before:

> - Right now if viewer fails to generate or retrieve a base CID, `viewer.getBaseCid()` returns `null`, and then runtime will throw. But now we want to attach new meaning to `null`, so once a `null` is returned, how do we know if it's actually a failure in viewer, or it is right time to call `viewer.storeBaseCid()`?
> - Once viewer expose such an interface as `storeBaseCid()`, does it need to read before write? Or it should just blindly override?

That's to say, if for any reason viewer failed to retrieve a base CID, runtime will call `storeBaseCid()`. Then viewer will blindly override the previous base CID?

@dvoytenko you're right, it will be pretty bad for us to late load sha384 lib for every page view on legacy browsers. However, I had this question before, why do we use sha384 on a good random value?

@jridgewell you made very good point. With `Promise`, the code for (2) doesn't look so bad, though you missed the logic for persisting the CID. So the only thing is whether we want to expose this extra 'gen-cid' API. I'm totally fine with it. So I will leave it to viewer team to decide.

I'm not sure if we already have a developer spec for 3P viewer, if so, we would update it with what we've decided.

**Comment by jridgewell** [comment] 2016-07-29 18:42
> (2) has problems like I listed before:

That's (1), right?

> However, I had this question before, why do we use sha384 on a good random value?

We probably don't need to sha384 values from `Crypto#getRandomValues`.

> though you missed the logic for persisting the CID

I left it out for both options, since it'd be the exact same.

**Comment by ericfs** [comment] 2016-07-29 20:12
Will the runtime will be checking and updating the last accessed time like it does here:
https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/cid-impl.js#L245

If it does, then I think we need two steps since it will need to check the timestamp and then update it.
The viewer could also be responsible for this in which case.

> That's to say, if for any reason viewer failed to retrieve a base CID, runtime will call storeBaseCid(). Then viewer will blindly override the previous base CID?

It depends how we define the API, we could allow that or the viewer could reject any store request that overwrites.

The getBaseCid() can reject instead of just returning null in the case where the viewer had an error accessing localStorage.

**Comment by dvoytenko** [comment] 2016-07-29 20:41
@lannka I believe sha384 was used for legacy browsers without `Crypto.getRandomValues()` it does things like 
```
String(win.location.href + timer.now() +
      win.Math.random() + win.screen.width + win.screen.height)
```

I agree that when `getRandomValues()` is available - we can bypass sha384 and just use base64, which is, of course, a lot faster.

So, the bottom line is how fast can we make the legacy case? And how exactly the latency of late-loading sha384 will hurt us here.

**Comment by lannka** [comment] 2016-07-29 21:15
> It depends how we define the API, we could allow that or the viewer could reject any store request that overwrites.
> 
> The getBaseCid() can reject instead of just returning null in the case where the viewer had an error accessing localStorage.

@ericfs That does resolve my concerns if you agree to refactor the current viewer side implementation to reject the promise on failures.

> So, the bottom line is how fast can we make the legacy case? And how exactly the latency of late-loading sha384 will hurt us here.

@dvoytenko `crypto.getRandomValues()` has [much wider browser support](http://caniuse.com/#feat=getrandomvalues) than `crypto.subtle`. In case it's not available, I think we can just use the `Math.random()` multiple times to provide enough entropy. No sha384 needed at all.

**Comment by lannka** [comment] 2016-07-29 22:27
I know we already had 3 options. But I still think it's worth to add another one from @dvoytenko :

API will be the same as option 3, which accepts an optional `idToStore` in the payload. 
Runtime first calls the API with `idToStore=null`. If it returns `null`, then calls the same API second time with `idToStore=xxxx`.

It keeps the API simple, meanwhile saved the cost for generating the randoms.

**Comment by lannka** [comment] 2016-08-01 17:54
After a meeting with most people on the thread, we agreed on
- Skip sha384 hashing while the random value is generated via crypto.getRandomValues.
- Use single API for read and write.
- Viewer will operate like a dumb storage, all logic (including checking expiration time) will be moved to runtime. This will potentially increase the risk of race condition (multiple AMP page write CID at same time), but we think it's acceptable comparing to the gain (centralized logic).
- To have the expiration check at runtime, the message payload needs to include the timestamp. So there'll be a format change. For backward compatibility, there'll be code at both viewer side and runtime side to handle the old format. @lannka will draft a PR to present the logic. Both legacy code will run on production for a while, until we feel it's safe to remove them.

Let me know if I missed anything.

**Comment by jridgewell** [comment] 2016-08-01 18:05
> Use single API for read and write.

Why did we settle on that? Wouldn't a `get-cid` and `save-cid` (both sent by runtime to the viewer) be better here?

**Comment by lannka** [comment] 2016-08-04 16:34
@jridgewell Regardless of the fact that it is essentially a window.postMessage, the API is like`viewer.cid(opt_cid)`. Semantically, it's a typical get or set method. You can find it anywhere in Javascript world (for example: [JQuery](https://api.jquery.com/data/).

It's not just about less code, as you can see in PR #4366, it made the code to handle backward compatibility much simpler as well (no need to check the existence of new APIs `get-cid` `store-cid`).

**Comment by jridgewell** [comment] 2016-08-04 16:42
> viewer.cid(opt_cid)

And I still hate that API.

> You can find it anywhere in Javascript world (for example: JQuery.

We already have the opposite in our [viewer messages](https://github.com/ampproject/amphtml/blob/fe63400cb62cd132ae279357e6d546fbd9d0010c/extensions/amp-analytics/0.1/storage-impl.js#L348-L358): `LOADSTORE` and `SAVESTORE`.

> it made the code to handle backward compatibility much simpler as well (no need to check the existence of new APIs get-cid store-cid).

There's no need to check for `store-cid` message, it's a save with no necessary result. And the backwards compatibility code will be exactly the same as you've written.

**Comment by lannka** [comment] 2016-08-09 17:03
> And the backwards compatibility code will be exactly the same as you've written.

I'm not sure what's the current behavior of viewer receiving an unsupported message, maybe @peleyal can chime in here. But in worst case, it can ignore the message without a response, then it just doesn't work.

In case viewer rejects unsupported message, we'll have more complicated code with one more round-trip. Viewer can also returns null for unsupported message, then we'll have another different piece of code to handle that.

```
viewer.sendMessage('get-cid')
    .catch(e => {
      return viewer.sendMessage('cid'));
    })
    .then(cid => {
       // do something
    });
```

> We already have the opposite in our viewer messages: LOADSTORE and SAVESTORE.

This is quite semantically different. `cid` is a setter and getter of item named cid. LOADSTORE and SAVESTORE are 2 actions, not specific to any item.

**Comment by ericfs** [comment] 2016-08-09 17:23
> I'm not sure what's the current behavior of viewer receiving an unsupported message,

The viewer will respond with a "no handler" error. This will be translated into a rejection with the error given as the reason.

**Comment by lannka** [comment] 2016-08-09 18:02
Thanks @ericfs 

Worth to mention one more advantage of the single API approach:
No deprecation process needed at viewer side. Once AMP runtime change gets rolled out, viewer can just change the implementation without introducing new API and removing old API at a later time.

**Comment by lannka** [comment] 2016-08-11 02:17
FYI, the PR is merged. It should be backward compatible. Search viewer can start development now, but please deploy to production only when the runtime change is fully live (so that you don't need to handle backward compatibility at your side).

**Closed by lannka** 2016-08-11 02:17 UTC
Labels: Type: Feature

**Comment by ericfs** [comment] 2016-08-11 12:24
Do you have a link to the PR?

**Comment by lannka** [comment] 2016-08-11 16:14
Yes, it is in the thread. But I can link it again: #4366

**Comment by skylinemarketing** [comment] 2016-08-11 16:20
Did it work?

**Comment by lannka** [comment] 2016-08-11 16:23
@skylinemarketing will work until viewer implement their part. But as I said, the change is backward compatible, so it works with current viewer as well.
