### ISSUE TITLE
AMP shadow throws errors with valid AMP documents embeded

### ISSUE THREAD

**Issue by p2er** [ampproject/amphtml#12847] opened 2018-01-16 20:00 UTC
## What's the issue?

The PWA with amp-shadow integration loads valid amp documents but throws errors.

ShadowCSS.js:179 
```
Uncaught Error: No ampdoc found for [object HTMLElement]
    at Aa (log.js:490)
    at ya.f.createError (log.js:263)
    at Mg.getAmpDoc (ShadowCSS.js:180)
    at HTMLElement.b.connectedCallback (resource.js:815)
    at amp-fx-flying-carpet.js:85
    at Array.forEach (<anonymous>)
    at w.push.f.g.buildCallback (amp-fx-flying-carpet.js:85)
    at resource.js:577
    at new Promise (<anonymous>)
    at HTMLElement.b.build (resource.js:575)
```

custom-element.js:189
```
Uncaught TypeError: Cannot read property 'remove' of null
    at HTMLElement.b.disconnectedCallback (custom-element.js:189)
    at amp-fx-flying-carpet.js:85
    at Array.forEach (<anonymous>)
    at w.push.f.g.buildCallback (amp-fx-flying-carpet.js:85)
    at resource.js:577
    at new Promise (<anonymous>)
    at HTMLElement.b.build (resource.js:575)
    at ih.f.build (preconnect.js:191)
    at wj (history-impl.js:821)
    at rj (history-impl.js:817)
```
## How do we reproduce the issue?

1. Open: https://www.bmw.com/en/performance/no-mans-land.pwa.html#development=1
2. Loads:
- valid: https://www.bmw.com/en/performance/no-mans-land.shadowstage.html#development=1
- valid: https://www.bmw.com/en/performance/no-mans-land.shadowcontent.html#development=1
- valid: https://www.bmw.com/en/automotive-life/x3-xtremsportler.shadowstage.html#development=1
3. Throws errors on initial load

Additional documents referenced, but not loaded during initial setup
Scroll down on desktop or swipe sidewards on mobile, loads:
- valid: https://www.bmw.com/en/automotive-life/x3-xtremsportler.shadowcontent.html#development=1
- valid: https://www.bmw.com/en/automotive-life/driving-experience.shadowstage.html#development=1
- valid: https://www.bmw.com/en/automotive-life/driving-experience.shadowcontent.html#development=1
- valid: https://www.bmw.com/en/automotive-life/best-of-drifts.shadowstage.html#development=1
- valid: https://www.bmw.com/en/automotive-life/best-of-drifts.shadowcontent.html#development=1

## What browsers are affected?

Tested on Chrome.

## Which AMP version is affected?

Powered by AMP ⚡ HTML shadows – Version 1515614886756

**Comment by jridgewell** [comment] 2018-03-12 20:50
Closing this as a dupe of #12849. Thanks for reporting both, though!

**Closed by jridgewell** 2018-03-12 20:50 UTC
Labels: Category: PWA, P2: Soon, Type: Bug
