### ISSUE TITLE
Error: Object doesn't support property or method 'match'

### ISSUE THREAD

**Issue by dparikh** [ampproject/amphtml#15755] opened 2018-06-01 21:02 UTC
stack trace:
-----------
Error: Object doesn't support property or method 'match'
at (https://raw.githubusercontent.com/ampproject/amphtml/1527203409437/src/service/viewport/viewport-impl.js:747)
at mutate (https://raw.githubusercontent.com/ampproject/amphtml/1527203409437/src/service/viewport/viewport-impl.js:699)
at (https://raw.githubusercontent.com/ampproject/amphtml/1527203409437/src/service/viewport/viewport-impl.js:726)
at implementation_ (https://raw.githubusercontent.com/ampproject/amphtml/1527203409437/src/custom-element.js:544)
at (https://raw.githubusercontent.com/ampproject/amphtml/1527203409437/build/patched-module/document-register-element/build/document-register-element.node.js:345)
at call (https://raw.githubusercontent.com/ampproject/amphtml/1527203409437/node_modules/promise-pjs/promise.js:502)
at (https://raw.githubusercontent.com/ampproject/amphtml/1527203409437/node_modules/promise-pjs/promise.js:10)
at (https://raw.githubusercontent.com/ampproject/amphtml/1527203409437/build/patched-module/document-register-element/build/document-register-element.node.js:341)
at (https://raw.githubusercontent.com/ampproject/amphtml/1527203409437/src/custom-element.js:543)
at updateInViewport (https://raw.githubusercontent.com/ampproject/amphtml/1527203409437/src/base-element.js:873)

Sample referrer:
----------------
Referrer	
https://www-chicagotribune-com.cdn.ampproject.org/c/www.chicagotribune.com/lifestyles/stevens/ct-life-stevens-wednesday-abby-wambach-barnard-graduation-0523-story,amp.html 
User agent	
Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko 
Service	
default-cdn-1p-canary 
Version	
031527203409437

**Comment by jridgewell** [comment] 2018-06-12 22:30
Dupe of https://github.com/ampproject/amphtml/issues/15769.

**Closed by jridgewell** 2018-06-12 22:30 UTC
Labels: Category: Runtime, P1: High Priority, Type: Bug
