### ISSUE TITLE
Provide a different message when viewport is too small for amp-story on desktop

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#13174] opened 2018-01-31 14:07 UTC
Currently we show the same message on desktop and mobile when the viewport is too small:

![screen shot 2018-01-31 at 9 04 11 am](https://user-images.githubusercontent.com/1651960/35627069-c4edbc22-0665-11e8-83c3-d3edc2669fde.png)

When the story is being viewed in "desktop" mode (indicated by the `desktop` attribute on the `<amp-story>` tag itself, or by the [`isDesktop_()`](https://github.com/ampproject/amphtml/blob/babea2c9a62b68e3bb28acedf38ffbaabda85777/extensions/amp-story/0.1/amp-story.js#L913-L916) function in the `AmpStory` class), we should change the icon and the message to convey "make your window larger" rather than "rotate your device to portrait orientation."

**Comment by cathyxz** [comment] 2018-02-06 23:32
@newmuis how does this feel as a GFI description (feel free to delete this comment after updating)? Should we update the description of this issue, or create a new one linking to it? 


### What you will need to know
- Some basic javascript
- How to build and run this project on your local machine

### Background
[AMP Story](https://github.com/ampproject/amphtml/blob/7bcb8fb01eb56d4e760c5a8d1a7766d39030dedc/extensions/amp-story/amp-story.md) is a new format for displaying visual content that you can assemble into a story-telling experience. 

### The feature
Currently we show the same message on desktop and mobile when the viewport is too small:
![screen shot 2018-01-31 at 9 04 11 am](https://user-images.githubusercontent.com/1651960/35627069-c4edbc22-0665-11e8-83c3-d3edc2669fde.png)
When the story is being viewed in "desktop" mode (indicated by the `desktop` attribute on the `<amp-story>` tag itself, or by the [`isDesktop_()`](https://github.com/ampproject/amphtml/blob/babea2c9a62b68e3bb28acedf38ffbaabda85777/extensions/amp-story/0.1/amp-story.js#L913-L916) function in the `AmpStory` class), we should change the icon and the message to convey "make your window larger" rather than "rotate your device to portrait orientation."

You can test this locally by making use of the sample amp pages in `/examples/amp-story`. For example: http://localhost:8000/examples/amp-story/helloworld.html. You can reproduce the message screen on desktop if you adjust the width of your browser such that the width is much larger than the height. Verify that it shows the desired message. 

### Step by step
- [ ] Claim this issue by adding a comment below.  Please only claim this bug if you plan on starting work in the next day or so.  (If you [join the AMP Project](https://goo.gl/forms/T65peVtfQfEoDWeD3) we'll be able to assign this issue to you after you've claimed it.)
- [ ] If you aren't too familiar with Git/GitHub, see the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub,](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.
- [ ] Follow the instructions for [building AMP](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server).
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [ ] [Sign the Contributor License Agreement](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#contributor-license-agreement) before creating a Pull Request.  (If you are contributing code on behalf of a corporation start this process as early as possible.)

- [ ] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [ ] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork).
- [ ] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review).  Mention `closes Issue #13174` in the description and request a review from @newmuis. 
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).


Once approved, your changes will be merged.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  You'll be able to see it [live across the web soon](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md)!

Thanks, and we hope to see more contributions from you soon.

### Questions?
If you have questions ask in this issue or on your Pull Request (if you've created one) or see the [How to get help](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#how-to-get-help) section of the Getting Started guide.

**Comment by newmuis** [comment] 2018-02-06 23:59
Wow, this is amazing!  Thanks @cathyxz!

**Comment by cathyxz** [comment] 2018-02-07 00:32
I think the only thing that a new contributor would need here is the actual icon that we want for the new message. @newmuis is there something we could direct them to?

**Comment by newmuis** [comment] 2018-02-07 01:07
@hongwei1990 do you have any opinions on what this icon should be for the desktop case?

**Comment by matthewgcallahan** [comment] 2018-02-23 15:07
@newmuis Want to bump this. Any resolution? We're hearing from people in and out of house that this is cropping up and are getting asked questions about it.

**Comment by newmuis** [comment] 2018-02-23 15:55
Tentatively, let's use the string "Expand your window to view this experience" and the white version of this icon :
![icon](https://user-images.githubusercontent.com/1651960/36603118-ca52ac98-1887-11e8-8a4b-2b04e7abbeee.png)

Here's the SVG of the icon:
```html
<svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" viewBox="0 0 24 24" fill="#FFFFFF">
  <path d="M0 0h24v24H0z" fill="none"/>
  <path d="M12.01 5.5L10 8h4l-1.99-2.5zM18 10v4l2.5-1.99L18 10zM6 10l-2.5 2.01L6 14v-4zm8 6h-4l2.01 2.5L14 16zm7-13H3c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h18c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm0 16.01H3V4.99h18v14.02z"/>
</svg>
```

/cc @hongwei1990 Feel free to give input on the choice of icon and the string

**Comment by newmuis** [comment] 2018-02-23 15:56
@sanjsanj or @staceyfenton would this be something you'd be interested in contributing?

**Comment by sanjsanj** [comment] 2018-02-24 17:50
@newmuis Sure let me have a look!  @staceyfenton is off skiing for a week but I'm hoping she'll pick up a GFI when she's back 😄

**Comment by sanjsanj** [comment] 2018-02-26 07:42
@newmuis I've made good progress in the little time I had last night and I think it might be working(ish), I need to have another look tonight and possibly come back with a question.

**Comment by newmuis** [comment] 2018-02-26 15:35
Sounds good!  Thanks @sanjsanj!

**Comment by sanjsanj** [comment] 2018-02-26 19:06
When exactly do we wish to show the desktop size warning?  The description above says to make the width much larger than the height but that doesn't trigger the existing overlay for me.  On desktop only reducing the height of the browser window below the min height of 550px does.

e.g.:

Width just over 550px

![desktop-minwidth](https://user-images.githubusercontent.com/4478671/36689063-3d26da5a-1b26-11e8-8734-124fa534bbec.png)

---

Width over 2600px

![desktop-maxwidth](https://user-images.githubusercontent.com/4478671/36689074-4b616522-1b26-11e8-8250-f9abe0f96088.png)


So basically I'm having trouble replicating the issue.  When the overlay does show on desktop it is quite appropriate because there isn't enough height to display the page, but the `isDesktop_()` method returns `false` in those cases because the size of the window is smaller than the media query.

So do we just want to show this warning on actual desktop devices when the dimensions are too small for an amp-story page?  In which case we can't use the existing `isDesktop_()` I believe?

https://github.com/ampproject/amphtml/blob/699a3b736698aba5a4941a08000c65d8bdcbfbd4/extensions/amp-story/0.1/amp-story.js#L940-L946

**Comment by sanjsanj** [comment] 2018-02-28 17:50
When you have time have a look pls @newmuis cheers!

**Comment by newmuis** [comment] 2018-02-28 19:37
Whoops, sorry!  Missed that notification.  I think there are two criteria that must both be met to trigger this:

1. The width of the viewport must be less than 1024px.
2. The height of the viewport must be less than the width.

I do agree; I think the warning is shown appropriately for those screen sizes, but you're right that we may not be able to use `isDesktop_()` to determine when to change the message.  Maybe for now we can use [isAndroid()](https://github.com/ampproject/amphtml/blob/181eb76daacea608493a2f26696116d9b18cf4dc/src/service/platform-impl.js#L38) and [isIos()](https://github.com/ampproject/amphtml/blob/181eb76daacea608493a2f26696116d9b18cf4dc/src/service/platform-impl.js#L46) and only change the message when we're not on Android or iOS?  I suppose what we're really trying to detect is devices where "rotate your device" doesn't make sense.  I don't think there's any way to really determine that through the [Orientation API](https://developer.mozilla.org/en-US/docs/Web/API/Screen/orientation), so a proxy of Android and iOS may have to suffice.

**Closed** 2018-03-02 18:39 UTC
Labels: Category: AMP Story, GFI Candidate, P3: When Possible, Type: Feature Request
