### ISSUE TITLE
Document how to reference an AMP page from the CANONICAL page

### ISSUE THREAD

**Issue by bryanburgers** [ampproject/amphtml#508] opened 2015-10-07 21:53 UTC
I can't find any information on [ampproject.org](https://ampproject.org) about how to reference an AMP-enabled page from the canonical page.

Everywhere I've looked so far (New York Times, The Guardian), the canonical page seems to be using:

```
<link rel="amphtml" href="[AMP-ENABLED-URL]" />
```

The only documentation I can find on the site is that the AMP-enabled page needs to have a canonical URL, but I don't see information specifying this `rel="amphtml"` link. Is that what providers will use to determine if a page has a corresponding amp-enable page?

**Comment by bryanburgers** [comment] 2015-10-07 21:54
Possible duplicate of #498.

**Comment by cramforce** [comment] 2015-10-07 23:52
Closing as dupe of #498

**Closed by cramforce** 2015-10-07 23:52 UTC
