### ISSUE TITLE
How To Add Sponsored Links To AMP Stories?

### ISSUE THREAD

**Issue by DanielCryptoK** [ampproject/amphtml#30140] opened 2020-09-08 04:43 UTC
I have just downloaded the google amp stories plugin and have created my first story. I have one affiliate link that I have added to it but I can not find anywhere to add the link attribute sponsored?

How do I add sponsored in amp stories or it this not applicable?
![Edit Story ‹ Bitcoin Casino No Deposit Bonus — WordPress (1)](https://user-images.githubusercontent.com/45933242/92433826-592b8900-f1c8-11ea-91d0-4002aff0b7df.png)

**Comment by newmuis** [comment] 2020-09-09 22:30
This feels like feedback for the WordPress plugin; @swissspidy do you know the appropriate place to route this?

**Comment by DanielCryptoK** [comment] 2020-09-10 04:03
No, can you help?

**Comment by newmuis** [comment] 2020-09-10 07:59
Sorry, that comment was intended for @swissspidy 

This repository is for the AMP stories framework, which supports what you're asking for by using the [`rel` attribute](https://support.google.com/webmasters/answer/96569?hl=en), but the WordPress plugin UI would need to add a way to do this.

We don't work on that in this repository, but I was reaching out to @swissspidy who may have information on where you can post this that would get in front of the right people.

**Comment by swissspidy** [comment] 2020-09-10 09:29
Hi @DanielCryptoK,

Thanks a lot for your input! As Jon said, this is not exactly the right place for this request. For the Web Stories WordPress plugin we welcome any feedback over at https://github.com/google/web-stories-wp.

At the moment it is not possible to mark sponsored links as such in the WordPress plugin. However, it's something we will look into. I just went ahead and submitted this as a feature request on your behalf here: https://github.com/google/web-stories-wp/issues/4440

Please follow that issue for any progress on this matter.

Thanks again!

**Comment by newmuis** [comment] 2020-09-10 13:33
Thanks Pascal!

Closing this issue since it's tracked in https://github.com/google/web-stories-wp/issues/4440

@DanielCryptoK feel free to reopen this issue if you feel it has not been completely addressed.

**Closed by newmuis** 2020-09-10 13:33 UTC
Labels: Type: Feature Request
