### ISSUE TITLE
PageSpeed Insights now reporting all AMP scripts as "Unused Javascript"

### ISSUE THREAD

**Issue by stephengardner** [ampproject/amphtml#28638] opened 2020-05-30 22:11 UTC
Reproduction steps:
- run PSI test on "https://amp.dev"
- results: 
![image](https://user-images.githubusercontent.com/7368566/83339881-f4df5c00-a29f-11ea-8798-d7019aa5243f.png)

As an aside, AMP pages across the board seem to be scoring less on the PSI report, and LCP's seem to fail the 2.5s threshold across the board.  Not reporting this LCP note as a bug, but it is relatively alarming to those who spend a lot of time optimizing their pages on AMP.  Google Search Console also seems to report drastically lower LCP results in "Web Vitals" report (2.x seconds as opposed to 4.x when tested directly via PSI).

**Comment by stephengardner** [comment] 2020-05-30 22:25
In an effort not to overload the issues tab, if someone could comment on the fact that the AMP homepage doesn't pass Google's Core Web Vitals assessment, that would be helpful.  As the AMP framework is generally touted as the fast, mobile-friendly and user-first ideal, it would be great to see it as an example of what it preaches.  Of course, PSI is a pretty key benchmark for users across the board (over a billion tests last year), so this is important for both publishers, and customers of AMP-related solutions.  Not saying all AMP pages have to pass, but it's a bit surprising here.
![image](https://user-images.githubusercontent.com/7368566/83340102-425cc880-a2a2-11ea-99a6-d52e1c3ce48b.png)
The AMP optimization tips documented are phenomenal.  Although even with these in place, including SSR, AMP Toolbox optimizer, etc, the LCP issue (at least when testing directly on the PageSpeed Insights tool itself), still remains.
Curious if any other publishers have seen something similar regarding LCP times.

**Comment by kristoferbaxter** [comment] 2020-06-01 04:36
Apologies for the slow response, I’ve been out on paternity leave.

I’m back tomorrow and will make sure this item gets an answer that clarifies things.

**Comment by stylecnc** [comment] 2020-06-02 04:28
I am troubled with the same problems, including unused JavaScript, Total Blocking Time,  and Largest Contentful Paint, the scores always change from 70 to 80, I can not get higher score anymore!
Here is an example:
https://amp.stylecnc.com/cnc-router/

**Comment by stephengardner** [comment] 2020-06-02 22:54
Thank you @kristoferbaxter, is this a confirmed issue now?  Any insight into next steps?

**Comment by kristoferbaxter** [comment] 2020-06-03 15:36
This discussion topic has come up several times over the last few years (with notable higher frequency once Chromium based browsers exposed coverage data from V8 via the Coverage Tab in Developer Tools).

<img width="1480" alt="Coverage report for amp.dev" src="https://user-images.githubusercontent.com/61764/83653925-3e19ff00-a571-11ea-911e-5571e75d3789.png">

Here you can see a Coverage report run on `amp.dev` reporting the same data you're seeing in Page Speed Insights.

It's important to know how Coverage is calculated, and how it pertains to your documents (and the billions of others using AMP). Effectively this is a collection of the executed code versus unexecuted during the recording lifecycle.

<img width="661" alt="Coverage of code executed in blue and unexecuted in red" src="https://user-images.githubusercontent.com/61764/83654537-1d05de00-a572-11ea-8c06-a14a111d06c4.png">

In this example the current browser visiting the document supported `Object.create` directly, so the poorlyfill did not execute.

This pattern is a frequent one in the AMP codebase and many Web Libraries, where support across many user-agent types requires additional complexity and code to ensure all visitors from supported devices get roughly equivalent experiences.

*However*, this report is also flagging specific sections of the AMP codebase as unexecuted for other reasons as well.

<img width="765" alt="Unexecuted Experiment Logic" src="https://user-images.githubusercontent.com/61764/83655174-eed4ce00-a572-11ea-86ef-91f8a877a96a.png">

Here, segments of the code are unexecuted because the document or user is not currently enrolled in any valid experiments. These experiments are used by AMP developers to build new features and roll them out progressively, without their inclusion in the static output there wouldn't currently be a safe way to rollout these changes without impacting all documents.

In general this type of monitoring is intended to be a tool for guiding changes since it cannot truly detect if a codepath is ever executed across all users (its scope is limited to the current execution for a user on a device).

<img width="686" alt="Conditions create branch points in execution" src="https://user-images.githubusercontent.com/61764/83656377-4f183f80-a574-11ea-9a65-c5285ca477fe.png">

Here, the fallback path is also important, but wasn't executed by the current invocation. However, a coverage report would indicate that this code is "unused". The AMP codebase is used in many scenarios and contains fallbacks to ensure the outcome is reached across many paths (some less than ideal).

## What are AMP contributors doing about it?

AMP contributors have been working to eliminate many of the codepaths. Here's an example from the currently experimental `esm` build of AMP that we plan to ship to all transformed documents over the next month.

<img width="603" alt="No Object.create poorlyfill" src="https://user-images.githubusercontent.com/61764/83656885-f6957200-a574-11ea-81b5-fa9f23080d4d.png">

In this example, the codepath for poorlyfilling `Object.create` was omitted, since there is certainty it exists for the loaded `esm` codepath.

Many more examples fall into this category.

## Assistance Welcomed!

If you have ideas about how to improve the Performance of AMP (its runtime, network usage, etc) please join us on the Performance Working group!

**Comment by stephengardner** [comment] 2020-06-03 16:31
Thanks @kristoferbaxter,
So as far as consumers of AMP go, the effective shorthand response is: "the 'Unused Javascript' warning is valid"?  

One issue here is the degree of severity this warning seems to infer.  

You can image a general AMP User, upon adopting AMP: "I have unused javascript! I want it removed! How can AMP be optimized with all these warnings about unused JavaScript?!"

I have three questions around this:

1) It is not clear if these warnings would be reconciled with the aforementioned updates in place.  It seems like there would just be _less_ unused javascript, and the same warning would exist.  Can you clarify if these warnings would still exist? Or if the most likely case is yes?
2) Are these warnings a new addition to the PSI/lighthouse tool?  We did not notice these a month ago.
3) Do you think it's reasonable that a website using any medium to large javascript file of a complexity similar to an AMP component would ever pass this "Unused Javascript" test?  

I'm not sure to what ends AMP really cares about the perceived performance of a user who tries to adopt the framework and sees these warnings, but given that it seems every single AMP script has unused Javascript on it, I'm curious why this is displayed with similar severity as other, actually fixable errors.

Thanks again for your helpful response and attention here

**Comment by kristoferbaxter** [comment] 2020-06-03 18:23
> As far as consumers of AMP go, the effective shorthand response is: "the 'Unused Javascript' warning is valid"?

Some of the warnings are valid, others are not. AMP contributors are working on improvements to reduce the amount of "unused JavaScript" from production documents.

> It is not clear if these warnings would be reconciled with the aforementioned updates in place. It seems like there would just be less unused javascript, and the same warning would exist. Can you clarify if these warnings would still exist? Or if the most likely case is yes?

It's not currently possible to remove _all_ unused JavaScript from a singular session. Bundles and extensions for AMP are used by billions of documents in varying ways, and as a result have differential _unused_ JavaScript given the context of the document's usage and a visitors session.

> Are these warnings a new addition to the PSI/lighthouse tool? We did not notice these a month ago.

Lighthouse and Pagespeed Insights change frequently, but I believe these warnings became more clear with a recent version.

> Do you think it's reasonable that a website using any medium to large javascript file of a complexity similar to an AMP component would ever pass this "Unused Javascript" test?

It's possible to reduce the amount of unused JavaScript, but getting to 0 unused JavaScript has other tradeoffs. I'd hope that in the future AMP's output is far smaller than today and can get as close as reasonable to 0 additional unused code.

**Comment by stephengardner** [comment] 2020-06-03 19:57
Thanks @kristoferbaxter 
>Some of the warnings are valid, others are not. AMP contributors are working on improvements to reduce the amount of "unused JavaScript" from production documents.

What are valid warnings and what are not?  Is this confirmation that some of the warnings in PSI are false positives?  Which ones, for AMP specifically, are false positives?  For example, "AMP components X, Y, Z, contain false positives."  

> It's not currently possible to remove all unused JavaScript from a singular session. Bundles and extensions for AMP are used by billions of documents in varying ways, and as a result have differential unused JavaScript given the context of the document's usage and a visitors session.

So, to be clear, these warnings in PSI _will still exist_ even after the potential upcoming performance updates?

>Lighthouse and Pagespeed Insights change frequently, but I believe these warnings became more clear with a recent version.

Is there a way to get a definitive answer on this?  

These questions and desire for specificity arise due to an abundance of AMP users on our end asking for information about this.  If there are errors in PSI with regards to AMP, it's an issue we are the POC for them.  If new measurement tools arise in PSI that flag AMP warnings, that's a red flag for them.  We're trying to construct the most effective and direct yes or no response to them with regards to their confusion.

**Comment by kristoferbaxter** [comment] 2020-06-03 20:41
Apologies if these responses are not answering your questions. Trying again.

>> Some of the warnings are valid, others are not. AMP contributors are working on improvements to reduce the amount of "unused JavaScript" from production documents.

> What are valid warnings and what are not? Is this confirmation that some of the warnings in PSI are false positives? Which ones, for AMP specifically, are false positives? For example, "AMP components X, Y, Z, contain false positives."

AMP components are designed to be resilient to a few conditions:
1. Many user-agents
2. Many input value types
3. Different experiences per experiment group.
4. Different languages and layout orientations.

Each of these conditions can increase the size of a component given the static nature of the output of AMP JavaScript across billions of documents. To support the many conditions, many codepath permutations are included by default. This is a tradeoff, increasing the number of conditions each component can support with a singular JavaScript payload and decreasing the possibility of needing to communicate with a server for more script to handle one of the permutations not included by default.

When a requested document is "lab tested" in PSI/Lighthouse the conditions a component executes against is a singular value for the many options across each condition. This is a selective view of the total possible codepaths.

**Short version**: Each component is equivalently measured, given the singular input conditions of the scenario the lab test is run under. This means there are no false positives, but the test conditions do not cover the gamut of scenarios the code is expected to handle.

>> It's not currently possible to remove all unused JavaScript from a singular session. Bundles and extensions for AMP are used by billions of documents in varying ways, and as a result have differential unused JavaScript given the context of the document's usage and a visitors session.

> So, to be clear, these warnings in PSI will still exist even after the potential upcoming performance updates?

Likely yes, but end users will recieve less total script to execute on their devices without lowering the number of conditions the library supports.

>> Lighthouse and Pagespeed Insights change frequently, but I believe these warnings became more clear with a recent version.

> Is there a way to get a definitive answer on this?
>
> These questions and desire for specificity arise due to an abundance of AMP users on our end asking for information about this. If there are errors in PSI with regards to AMP, it's an issue we are the POC for them. If new measurement tools arise in PSI that flag AMP warnings, that's a red flag for them. We're trying to construct the most effective and direct yes or no response to them with regards to their confusion.

These tests were previously available in Lighthouse when run via CLI, but were moved to higher prominence in Lighthouse 6.0 which recently released.

**Comment by connorjclark** [comment] 2020-06-03 20:56
> Lighthouse and Pagespeed Insights change frequently, but I believe these warnings became more clear with a recent version.
> Is there a way to get a definitive answer on this?
> These tests were previously available in Lighthouse when run via CLI, but were moved to higher prominence in Lighthouse 6.0 which recently released.

Hi, Lighthouse dev here. Allow me to clear this up. The unused JavaScript audit is new in Lighthouse 6.0, which was released to PSI recently. See this for more: https://web.dev/lighthouse-whats-new-6.0/ .

This is a new feature. Another developer recently addressed similar feedback from the next.js people: https://github.com/vercel/next.js/discussions/13682#discussioncomment-21797

To be clear, these opportunities don't directly impact the score, they are Lighthouse's best guesses as to how to improve the metrics. The score is only based on the metrics. We try to scope our opportunities to what is most likely to have an impact. Sometime, for some pages, it can be wrong, or at the very least may not be as good of an avenue for optimization as the relative "estimated savings" might imply.

**Comment by connorjclark** [comment] 2020-06-03 21:01
I should also point out that Lab tools (such as Lighthouse) are only testing cold loads. Any JS that is behind user interaction will be considered "unused". 

Sometimes, if the code is large enough and structurally isolated from the rest of the app, you can can lazy load that "unused" code. For example, the "Share" modal in Google Docs is ~1.4MB compressed JS. In the case of a framework, as may be the case for AMP (I am no expert), the "unused" code may be too integrated into the code base, and there is no clean place to lazy load anything.

**Comment by stephengardner** [comment] 2020-06-03 21:33
Thank you @kristoferbaxter and @connorjclark 
I do entirely understand that a subset of code will of course not be covered by the "Used javascript" test case, and the javascript which covers user interaction will have an additional likelihood of being flagged as "unused".  Not that this is a bug in PSI, but it's raising some eyebrows from customers who are also simultaneously noticing, either correlated or not, that their scores have dropped in the 6.0.0 release of Lighthouse. 

It looks like #13682 also has some similar score-dropping remarks.  

While I understand it's the nature of PSI to change over time and of course not report identical results with each version release, I suppose from a broader perspective I am also raising a question as to whether or not it is the best idea to have a red error appear for this, since it seems extremely rare, at least at the current point in time, that websites are able to actually resolve this.  It does pop up in the very first "Opportunites" section, beneath their overall page speed timing results, which is unfortunate, at least for anyone in our position, as a publisher of an AMP solution.   

I did run some tests on our Angular (9) codebase, and lazy-loaded modules are not being flagged as Unused Javascript, as one would expect.  Of course, the main bundle is.

Images from https://amp.dev 's lighthouse result:
![image](https://user-images.githubusercontent.com/7368566/83689466-105aa780-a5bd-11ea-81a4-5a5a0e685e01.png)

You can see, it looks like just about every single AMP component is being flagged.  
![image](https://user-images.githubusercontent.com/7368566/83689570-4009af80-a5bd-11ea-9289-638a4ccdd615.png)

Personally, I'm not really bothered by the scores.  But it's my job to make sure adopters of AMP feel they're getting the performance bang-for-their-buck. Trying to convince them that a brand new red error and an "Estimated savings" time value doesn't affect their performance score, or their potential Google ranking, is in some cases a dealbreaker, when AMP is touted as the extremely fast alternative. (I do recognize it's explicitly stated that these "Opportunities" metrics don't affect a performance score.  I believe the overall sentiment is that; well, if there's an "estimated savings" then of course the page should load that much faster if this was implemented "properly", and how could that not affect the overall score?).

I'd like to also point out that I'm extremely thankful for the responses given.

Ultimately, our answer to customers is the following:
"AMP has unused javascript being flagged on what appears to be every individual AMP component, and unfortunately we can't fix this.  The AMP team has plans to mitigate this somewhat, but it's an almost certain guarantee that the 'Remove unused JavaScript' error will never actually disappear from your performance report, despite AMP being implemented perfectly on our end.  It does not affect your performance score, and the drop in your performance as of late is a result of the ever-changing lighthouse algorithm, not this new error."

However disheartening, does this sound accurate?

**Comment by connorjclark** [comment] 2020-06-03 22:02
> It does pop up in the very first "Opportunites" section, beneath their overall page speed timing results, which is unfortunate, 

Agreed–we're considering increasing the threshold to something like 20KB unused per script. For this specific case, it'd cut the estimated savings to a third, which should reduce the implied actionably. 

> "will never actually disappear from your performance report"

might add that Lighthouse may reduce this estimation by raising the threshold. In hindsight, complaining about a few KB of unused JS was a bad idea.

> "it is a result of the ever-changing lighthouse algorithm"

I don't want to minimize the impact changes have on you, I understand it can be frustrating to see scores change over night (we change the scoring every year or so but this is perhaps the most significant so far). We're using the new web.dev/vitals metrics as we collectively all learn how to better measure user experience. The hope is that the score is a better reflection of user experience.

> I'd like to also point out that I'm extremely thankful for the responses given.

Of course, happy to help :)

**Comment by stephengardner** [comment] 2020-06-03 22:58
> > It does pop up in the very first "Opportunites" section, beneath their overall page speed timing results, which is unfortunate,
> 
> Agreed–we're considering increasing the threshold to something like 20KB unused per script. For this specific case, it'd cut the estimated savings to a third, which should reduce the implied actionably.
> 
> > "will never actually disappear from your performance report"
>
> might add that Lighthouse may reduce this estimation by raising the threshold. In hindsight, complaining about a few KB of unused JS was a bad idea.

I think this entire thread can be summed up with these insights.  Thank you.  Is there anywhere we can cast a vote for this to be taken into consideration?  I believe the AMP project as a whole would benefit from this change.

**Comment by connorjclark** [comment] 2020-06-03 23:30
I think we're in agreement, already have a PR up: https://github.com/GoogleChrome/lighthouse/pull/10906

**Comment by ahmedkaludi** [comment] 2020-06-04 09:39
We at AMPforWP have practically 180000 people and possibly billions of AMP pages bothered by this issue, our support has been flooded by this because of the panic created among the people due to the drop in performance.  

One such example: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.saveatrain.com%2Fblog%2Fapps-download-traveling%2Famp


I hope this PR https://github.com/GoogleChrome/lighthouse/pull/10906 will help us fix this problem :)

**Comment by ahmedkaludi** [comment] 2020-06-22 06:36
any movement on this?

**Comment by abukhan** [comment] 2020-06-25 11:49
Eagerly waiting for updates

**Comment by kristoferbaxter** [comment] 2020-06-26 02:52
Looks like this was just merged for the next release of lighthouse.

https://github.com/GoogleChrome/lighthouse/pull/11025

**Comment by connorjclark** [comment] 2020-07-09 23:24
6.1 is in PSI now.

**Comment by geogramdotcom** [comment] 2020-08-06 21:23
Issue for our sites as well. Commented to track. Thanks for all the hard work you dedicate to these issues!

**Comment by connorjclark** [comment] 2020-08-06 21:30
The threshold was lowered with 6.1

**Comment by techzotezo** [comment] 2020-08-24 10:44
Issue in our site as well and due to this core web vitals score is reduced.It should be fixed permanently..

**Comment by ahmedkaludi** [comment] 2020-09-04 15:16
So a default Hello World document from 'https://validator.amp.dev/' shows these two problems on https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fpuddle-like-roar.glitch.me%2F%3F9

This needs to be fixed ASAP. The whole AMP Devs / Webmasters community is stressed out because of this problem. 

Ideally v0.js should not be a 'Core Web Vital' issue, which is the case. 

![image](https://user-images.githubusercontent.com/16532359/92255125-7eca4100-eeef-11ea-9a1c-71f9dc039f90.png)

**Comment by natalienana460** [comment] 2020-09-10 08:39
My website seems also have same problem, always test and shows "Remove Unused Javascript"  Mobile Speed Index 8.1, looks very bad
my website: [humma laser](https://www.hummalaser.com/)
![微信截图_20200910163915](https://user-images.githubusercontent.com/71066652/92702798-31812000-f384-11ea-924d-d08f72bc9b30.png)

**Comment by michalestyle** [comment] 2020-09-18 13:17
I also encountered the same problem and I hope to improve it.
I established this bearing website a year ago, a very good bearing online trading platform, here is the link: [https://www.bearingkingdom.com](https://www.bearingkingdom.com)

**Comment by techzotezo** [comment] 2020-10-12 14:32
I also faced the same issue in my pages https://www.zotezo.com/?amp
How to fix the issue?
Also address this issue here https://github.com/ampproject/amphtml/issues/30336

**Comment by barruka** [comment] 2020-10-17 09:22
Same problem here, changed full project to amp and then all metrics rise up.

Problem with CLS: more than 0,1 (mobile)
Problem with LCP: more than 2,5 s (mobile)

We are wondering to rollback... 

AMP must be cutting-edge web tech but I don't like what it's becoming to.

Production .js cannot be a realm to experiments, it only must contain the minimal code to run.
/v0.js code is growing up every week, this is a total nonsense.

**Comment by kristoferbaxter** [comment] 2020-10-17 17:56
Hi there,

A few comments here have been wondering about the size and efficiency of v0.js (AMP Runtime). We are actively working on reductions to its overall size as previously mentioned in this issue. The rollout of the module version of the AMP runtime is at 50% on the Google AMP Cache, and once complete will be available for valid transformed documents via the AMP Optimizer.

If you're looking for specific advise to understand and improve AMP documents you work on, we recommend trying the AMP Page Experience tool (https://amp.dev/page-experience/). This will give you **real world** metrics for the performance of your documents using Core Web Vitals metrics, and is a better indicator of what real users see when visiting your documents.

Synthetic benchmarks are also used to help drive the recommendations.

If you're having issues meeting Core Web Vitals once all the recommendations have been completed, the tool will provide a link that auto-populates an issue for the Performance Working Group to investigate.

I'll likely not be able to respond much on this issue during the weekend here, but will be able to next week.

**Comment by vko85** [comment] 2020-11-11 13:28
We're using google ad manager on our site and experiencing the same in pagespeed reports. I hope it'll get fixed soon.

**Comment by BuyCNC** [comment] 2020-11-19 01:59
I encountered the same problem, including unused JavaScript, thank you for sharing.
This is an introduction： https://buycnc.com/about-us/

**Comment by MrCsabaToth** [comment] 2020-12-04 21:37
> We at AMPforWP have practically 180000 people and possibly billions of AMP pages bothered by this issue, our support has been flooded by this because of the panic created among the people due to the drop in performance.
> 
> One such example: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.saveatrain.com%2Fblog%2Fapps-download-traveling%2Famp
> 
> I hope this PR [GoogleChrome/lighthouse#10906](https://github.com/GoogleChrome/lighthouse/pull/10906) will help us fix this problem :)

The Chrome issue would only make the warning go away, the amount of JavaScript wouldn't change. Other changes may help with actually decreasing the size and the content of AMP components.

**Comment by MrCsabaToth** [comment] 2020-12-04 21:40
In my case the Unused JavaScript error does not provide any details about which JS asset would cause the actual error:
![Screenshot_2020-12-04_12-50-04](https://user-images.githubusercontent.com/744949/101217253-e484b100-3635-11eb-8f52-3ba1a33bfa73.png)

Back in the early phase of development I may loaded a component when it was not actually used, but I think even the AMP validator picks that up. So I don't think that would be the case. I have a tiny bit of JavaScript in an iframe related to Disqus integration but this error message comes in pages which don't have Disqus (=not actual blog post pages), so it's not what causing these errors.

**Comment by connorjclark** [comment] 2020-12-04 21:44
@MrCsabaToth this is actually Lighthouse's error–can you file an issue here https://github.com/GoogleChrome/lighthouse/issues/ ?

**Comment by suneel-code** [comment] 2020-12-11 16:55
It is November 2020. Till now there are no updates from anywhere regarding how these Core Web Vitals take these unused JS loading times? Our site is showing higher time for LCP. We are unable to solve..
[https://www.examtray.com/python/python-type-casting-or-type-conversion-tutorial?amp](url)

Also, AMP pages do not allow serving font files locally. Fontawesome is slow at times.

**Comment by sebastianbenz** [comment] 2020-12-11 17:03
@suneel-code please take a look at our page experience checker: https://amp.dev/page-experience/?url=https://www.examtray.com/python/python-type-casting-or-type-conversion-tutorial?amp

It'll give you plenty advice on how you can improve your performance. AMP pages also allow you to self-host font files.

**Comment by MrCsabaToth** [comment] 2020-12-11 19:50
> @suneel-code please take a look at our page experience checker: https://amp.dev/page-experience/?url=https://www.examtray.com/python/python-type-casting-or-type-conversion-tutorial?amp
> 
> It'll give you plenty advice on how you can improve your performance. AMP pages also allow you to self-host font files.

1. @suneel-code fonts are one exception and can be hosted by you. I'm using a hybrid approach: self hosting but offering woff2 from CDN.
2. @sebastianbenz this AMP specific page is great. But I'm confused why it does not show the same values for my site regarding LCP and CLS mostly as https://web.dev/measure/ or https://www.webpagetest.org/

My site is https://csaba.page/ (https://gitlab.com/MrCsabaToth/mrcsabatoth.gitlab.io/)

**Comment by sebastianbenz** [comment] 2020-12-11 20:12
re 2.: measuring these things in a consistent manner is hard as connection, server-response times, cpu load etc might vary. They can only give you indication, but the exact numbers might change. Sidenote: amp.dev/page-experience uses https://developers.google.com/speed/pagespeed/insights/ under the hood for measuring the performance.

**Comment by EndiHariadi43** [comment] 2020-12-28 01:11
I have configured my website server with nginx, apache2 and varnish and managed to achieve a decent gtmetrix score.
![Screenshot_2020-12-28-07-53-02-502_com android chrome](https://user-images.githubusercontent.com/59972539/103183089-fa0e9300-48e2-11eb-94c4-9b98836d8cf9.jpg)
However, when tested with webpagetest [.] Org or https://developers.google.com/speed/pagespeed/insights/ speed issues then arise. 
![Screenshot_2020-12-28-07-55-19-614_com android chrome](https://user-images.githubusercontent.com/59972539/103183262-c3854800-48e3-11eb-903f-5d90edca8db6.jpg).

I think my efforts have been maximized, but, until now I can't find a proper reference to solve this problem.

**Comment by nicolasfaurereboot** [comment] 2020-12-30 16:48
> 2. @sebastianbenz this AMP specific page is great. But I'm confused why it does not show the same values for my site regarding LCP and CLS mostly as https://web.dev/measure/ or https://www.webpagetest.org/

Even if you only take the Boilerplate from [AMP.dev](https://amp.dev/boilerplate/), run [AMP optimizer](https://toolbox-optimizer.glitch.me/), and launch simultaneously 6 chrome windows to use the following web vitals measuring tools:
- [Web vitals Chrome Extension](https://chrome.google.com/webstore/detail/web-vitals/ahfhijdlegdabablpippeagghigmibma?hl=en)
- the lighthouse report in Chrome dev tools
- the performance section in Chrome dev tools
- [the AMP page experience](https://amp.dev/page-experience/)
- [Web.dev](https://web.dev/measure/)
- [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/)
- [webpagetest](https://www.webpagetest.org)
the measures will be different.

it's probably more efficient to focus on the speed improvement advices given by these tools (like removing unused javascript to gain hundreds of milliseconds) rather than the measures. 
Because at the end we mainly want to load/render faster the webpage and to get the ['Fast Page' Label](https://blog.chromium.org/2020/08/highlighting-great-user-experiences-on.html) a 'green experience' is enough.

**Comment by linhlanweb** [comment] 2021-02-03 23:13
I was really impressed with AMP from the start. But now (2021), I find it too bad. It's not like before. I had to remove it in order to use the standard web site standards. The speed is much improved.
I'm really sorry to have to quit AMP. Thank Developers!

**Comment by kristoferbaxter** [comment] 2021-02-03 23:34
@EndiHariadi43 AMP's page experience tools have a few suggestions for your site: You can see them here: https://amp.dev/page-experience/?url=https://nickgenom.com/en

**Comment by kristoferbaxter** [comment] 2021-02-03 23:35
@nicolasfaurereboot Agree with your statement, synthetic testing tools like those mentioned are best used as a way to gain insight into improvements not to compare the results against one another.

**Comment by kristoferbaxter** [comment] 2021-02-03 23:37
Since this issue has moved away from its original concerns, I'm going to mark the issue closed.

Efforts are ongoing to reduce the size of AMP's JavaScript payloads, including Bento, AMP Compiler, and Module/NoModule mode.

**Closed by kristoferbaxter** 2021-02-03 23:37 UTC
Labels: Type: Discussion/Question, WG: performance

**Comment by MrCsabaToth** [comment] 2021-02-04 11:17
> Since this issue has moved away from its original concerns, I'm going to mark the issue closed.
> 
> Efforts are ongoing to reduce the size of AMP's JavaScript payloads, including Bento, AMP Compiler, and Module/NoModule mode.

I found referneces to Bento:

* https://amp.dev/community/working-groups/bento/
* https://blog.amp.dev/2021/01/28/bento/
* https://drive.google.com/file/d/1qzO7ZR0W9lFlyBCZKidR3QB8seU2dT0t/view 

What are the best references to AMP Compiler (I found AMP Closure Compiler, but I'm not sure that's what you mean) and the Module/NoModule mode. My web page is Jekyll based, I'll explore how I can take advantage of those.

**Comment by honeybeecnc** [comment] 2021-05-27 12:42
I used the wordpress AMP plug-in and tested AMP, but it feels slow. I don’t know what the problem is? I’m currently switching back to using the theme for mobile adaptive.Here is an example:https://www.honeybeecutting.com/

**Comment by MrCsabaToth** [comment] 2021-05-27 18:26
> I used the wordpress AMP plug-in and tested AMP, but it feels slow. I don’t know what the problem is? I’m currently switching back to using the theme for mobile adaptive.Here is an example:https://www.honeybeecutting.com/

There can be many reasons for a site to feel slow. If you want to be seriously fast then you either want to get closer to the bare metal (a.k.a. use a framework on your own instead of WordPress), or seriously restrict and cherry pick WordPress plugins to cut your footprint, optimize images, etc.
Looks like there's much more than just AMP: https://www.webpagetest.org/result/210527_BiDc1H_9d74899605acf3702cd5517744677128/

**Comment by colorman4** [comment] 2021-12-14 07:28
It fetches the url twice, once with a mobile user-agent, and once with a desktop-user agent. The PageSpeed Insights Score ranges from 0 to 100 points. A higher score is better and a score of 85 or above indicates that the page is performing well.
__________________________
https://coloring-pages.io

**Comment by Haseeb717** [comment] 2022-04-08 21:02
@westonruter any updates on that?

**Comment by westonruter** [comment] 2022-04-09 02:28
@Haseeb717 no. I'm not working on this.

**Comment by EzCad** [comment] 2022-05-05 23:55
I am troubled with the same problems, including unused JavaScript, Total Blocking Time, and Largest Contentful Paint, the scores always change from 70 to 80, I can not get higher score anymore!
Here is an example:

I never noticed this issue until I read this article. I found my pages has similar problems. The score can not be perfect like 90.

Example pages
https://www.laserchina.com/
https://www.laserchina.com/engraver/
https://www.laserchina.com/cleaner/

**Comment by ennkh** [comment] 2023-02-08 10:25
Same issue, I tried many times to improve my score, always got errors,

Remove duplicate modules in JavaScript bundles 1.47 s 
Reduce unused JavaScript 0.87 s 
Reduce initial server response time 0.5 s

the main page https://www.computer-pdf.com/
other pages
https://www.computer-pdf.com/programming/
https://www.computer-pdf.com/programming/802-tutorial-python-tutorial.html

**Comment by EzCad** [comment] 2023-02-08 10:26
邮件已收到。如紧急，请通过电话联系。

**Comment by EzCad** [comment] 2024-04-08 11:10
邮件已收到。如紧急，请通过电话联系。

**Comment by Igoldencnc** [comment] 2025-01-15 05:49
I am troubled with the same problems, including unused JavaScript, Total Blocking Time, and Largest Contentful Paint, the scores always change from 70 to 80, I can not get higher score anymore!
https://www.igolden-cnc.com/
https://www.igolden-cnc.com/product-category/cnc-router/cnc-wood-router/
https://www.jnigolden.com/
https://www.igoldenlaser.com/

**Comment by EzCad** [comment] 2025-01-15 05:49
邮件已收到。如紧急，请通过电话联系。
