### ISSUE TITLE
amp-carousel 0.1 regression in 2102130314004

### ISSUE THREAD

**Issue by dritter** [ampproject/amphtml#33029] opened 2021-03-03 11:20 UTC
Hi there,

we noticed two regressions in the amp-carousel 0.1 (0.2 seems to be clean):

1. It shows initially the last slide (instead of the first one)
    ![image](https://user-images.githubusercontent.com/1544760/109796769-dcc6af80-7c18-11eb-9552-b602c4a6f989.png)

2. it shows the wrong slide on connected carousels after click (seems to be off by one)
    ![image](https://user-images.githubusercontent.com/1544760/109797370-aa698200-7c19-11eb-8985-e6cec260b8f5.png)

I created just one issue, cause the seem strongly related.

Here is a [reproducer in the playground](https://playground.amp.dev/#share=PCFET0NUWVBFIGh0bWw+CjxodG1sIOKaoT4KPGhlYWQ+CiAgICA8bWV0YSBjaGFyc2V0PSJ1dGYtOCIgLz4KICAgIDx0aXRsZT5NeSBBTVAgUGFnZTwvdGl0bGU+CiAgICA8bGluayByZWw9ImNhbm9uaWNhbCIgaHJlZj0ic2VsZi5odG1sIiAvPgogICAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCIgLz4KICAgIDxzdHlsZSBhbXAtYm9pbGVycGxhdGU+Ym9keXstd2Via2l0LWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoOy1tb3otYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7LW1zLWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoO2FuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RofUAtd2Via2l0LWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW1vei1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1tcy1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1vLWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1Aa2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fTwvc3R5bGU+PG5vc2NyaXB0PjxzdHlsZSBhbXAtYm9pbGVycGxhdGU+Ym9keXstd2Via2l0LWFuaW1hdGlvbjpub25lOy1tb3otYW5pbWF0aW9uOm5vbmU7LW1zLWFuaW1hdGlvbjpub25lO2FuaW1hdGlvbjpub25lfTwvc3R5bGU+PC9ub3NjcmlwdD4KICAgIDxzY3JpcHQgYXN5bmMgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC5qcyI+PC9zY3JpcHQ+CiAgICA8c2NyaXB0IGFzeW5jIGN1c3RvbS1lbGVtZW50PSJhbXAtbGlnaHRib3giIHNyYz0iaHR0cHM6Ly9jZG4uYW1wcHJvamVjdC5vcmcvdjAvYW1wLWxpZ2h0Ym94LTAuMS5qcyI+PC9zY3JpcHQ+CiAgICA8c2NyaXB0IGFzeW5jIGN1c3RvbS1lbGVtZW50PSJhbXAtY2Fyb3VzZWwiIHNyYz0iaHR0cHM6Ly9jZG4uYW1wcHJvamVjdC5vcmcvdjAvYW1wLWNhcm91c2VsLTAuMS5qcyI+PC9zY3JpcHQ+CiAgICA8c3R5bGUgYW1wLWN1c3RvbT4KICAgICAgICBoMSB7CiAgICAgICAgICAgIG1hcmdpbjogMXJlbTsKICAgICAgICB9CiAgICAgICAgLm15LXNsaWRlIHsKICAgICAgICAgICAgcG9zaXRpb246IHJlbGF0aXZlOwogICAgICAgIH0KICAgICAgICAuc2xpZGUtaGVhZGVyIHsKICAgICAgICAgICAgYmFja2dyb3VuZDogd2hpdGVzbW9rZTsKICAgICAgICAgICAgcG9zaXRpb246IGFic29sdXRlOwogICAgICAgICAgICB0b3A6IDUlOwogICAgICAgICAgICBsZWZ0OiA1JTsKICAgICAgICAgICAgei1pbmRleDogMTsKICAgICAgICB9CiAgICAgICAgLm5vLW1hcmdpbiB7CiAgICAgICAgICAgIG1hcmdpbjogMDsKICAgICAgICB9CiAgICA8L3N0eWxlPgo8L2hlYWQ+Cjxib2R5Pgo8aDI+CiAgICBDb25uZWN0ZWQgQ2Fyb3VzZWxzIHNlZW0gbm90IHRvIHdvcmsgcHJvcGVybHkgYW55IG1vcmUuCjwvaDI+CjxwPgogICAgVGhlcmUgYXJlIHR3byBQcm9ibGVtczoKPC9wPgo8b2w+CiAgICA8bGk+VGhlIGZpcnN0IEltYWdlIGlzIGFjdHVjYWxseSB0aGUgbGFzdCBpbWFnZS4gSXQgc2VlbXMgbGlrZSB0aGUgaW5kZXggaXMgbm93IDEgYmFzZWQuCiAgICA8L2xpPgogICAgPGxpPklmIHlvdSBjbGljayBvbiB0aGUgaW1hZ2UgdG8gb3BlbiB0aGUgbGlnaHRib3gsIHlvdSBsYW5kIG9uIHRoZSB3cm9uZyBzbGlkZS4gVGhpcyBzaG91bGRuJ3QgaGFwcGVuLCBjYXVzZSB3ZSB1c2UgZ29Ub1NsaWRlKGluZGV4PTEpIChvciB3aGF0ZXZlciB0aGUgaW5kZXggaXMpIGhlcmUuPC9saT4KPC9vbD4KPHA+CiAgICBPdGhlciBvYnNlcnZhdGlvbnM6CjwvcD4KPHVsPgogICAgPGxpPkRvZXMgPHN0cm9uZz5ub3Q8L3N0cm9uZz4gaGFwcGVuIGluIHRoZSBjdXJyZW50IExUUyBWZXJzaW9uICgyMTAxMjMwNDEyMDA2KS48L2xpPgogICAgPGxpPkFsbW9zdCBmaXhlZCwgaWYgd2UgcmVtb3ZlIHRoZSBsb29wIGF0dHJpYnV0ZS4gQWxtb3N0LCBiZWNhdXNlIHRoZSBjbGlja2luZyB0aGUgbGFzdCBzbGlkZSBzdGlsbCBzaG93cyB0aGUgd3Jvbmcgc2xpZGUuPC9saT4KICAgIDxsaT5UaGlzIGhhcHBlbnMgZXZlbiBpZiB0aGUgc2xpZGVzIGRvIG5vdCBjb250YWluIGltYWdlcyAoc28gbm8gbmV0d29yayByYWNlIGlzIGludm9sdmVkIGhlcmUpLjwvbGk+CjwvdWw+Cgo8YW1wLWNhcm91c2VsIGlkPSJvdXRlckNhcm91c2VsIgogICAgICAgICAgICAgIGNvbnRyb2xzCiAgICAgICAgICAgICAgbG9vcAogICAgICAgICAgICAgIHR5cGU9InNsaWRlcyIKICAgICAgICAgICAgICB3aWR0aD0iNDAwIgogICAgICAgICAgICAgIGhlaWdodD0iMzAwIj4KICAgIDxkaXYgb249InRhcDpteUxpZ2h0Ym94Lm9wZW4sbGlnaHRib3hDYXJvdXNlbC5nb1RvU2xpZGUoaW5kZXg9MCkiIHJvbGU9ImJ1dHRvbiIgdGFiaW5kZXg9IjEiIGNsYXNzPSJteS1zbGlkZSI+CiAgICAgICAgPGgyIGNsYXNzPSJzbGlkZS1oZWFkZXIgbm8tbWFyZ2luIj5TbGlkZSAxPC9oMj4KICAgICAgICA8YW1wLWltZyBzcmM9Ii9zdGF0aWMvc2FtcGxlcy9pbWcvaW1hZ2UxLmpwZyIKICAgICAgICAgICAgICAgICBsYXlvdXQ9ImZpbGwiCiAgICAgICAgPjwvYW1wLWltZz4KICAgIDwvZGl2PgogICAgPGRpdiBvbj0idGFwOm15TGlnaHRib3gub3BlbixsaWdodGJveENhcm91c2VsLmdvVG9TbGlkZShpbmRleD0xKSIgcm9sZT0iYnV0dG9uIiB0YWJpbmRleD0iMiIgY2xhc3M9Im15LXNsaWRlIj4KICAgICAgICA8aDIgY2xhc3M9InNsaWRlLWhlYWRlciBuby1tYXJnaW4iPlNsaWRlIDI8L2gyPgogICAgICAgIDxhbXAtaW1nIHNyYz0iL3N0YXRpYy9zYW1wbGVzL2ltZy9pbWFnZTIuanBnIgogICAgICAgICAgICAgICAgIGxheW91dD0iZmlsbCIKICAgICAgICA+PC9hbXAtaW1nPgogICAgPC9kaXY+CiAgICA8ZGl2IG9uPSJ0YXA6bXlMaWdodGJveC5vcGVuLGxpZ2h0Ym94Q2Fyb3VzZWwuZ29Ub1NsaWRlKGluZGV4PTIpIiByb2xlPSJidXR0b24iIHRhYmluZGV4PSIzIiBjbGFzcz0ibXktc2xpZGUiPgogICAgICAgIDxoMiBjbGFzcz0ic2xpZGUtaGVhZGVyIG5vLW1hcmdpbiI+U2xpZGUgMzwvaDI+CiAgICAgICAgPGFtcC1pbWcgc3JjPSIvc3RhdGljL3NhbXBsZXMvaW1nL2ltYWdlMy5qcGciCiAgICAgICAgICAgICAgICAgbGF5b3V0PSJmaWxsIgogICAgICAgID48L2FtcC1pbWc+CiAgICA8L2Rpdj4KPC9hbXAtY2Fyb3VzZWw+CjxhbXAtbGlnaHRib3ggaWQ9Im15TGlnaHRib3giIGxheW91dD0ibm9kaXNwbGF5Ij4KICAgIDxkaXYgY2xhc3M9ImxpZ2h0Ym94Ij4KICAgICAgICA8YW1wLWNhcm91c2VsIGlkPSJsaWdodGJveENhcm91c2VsIgogICAgICAgICAgICAgICAgICAgICAgdHlwZT0ic2xpZGVzIgogICAgICAgICAgICAgICAgICAgICAgY29udHJvbHMKICAgICAgICAgICAgICAgICAgICAgIGxvb3AKICAgICAgICAgICAgICAgICAgICAgIHdpZHRoPSI0MDAiCiAgICAgICAgICAgICAgICAgICAgICBoZWlnaHQ9IjMwMCIKICAgICAgICA+CiAgICAgICAgICAgIDxkaXYgb249InRhcDpteUxpZ2h0Ym94LmNsb3NlLG91dGVyQ2Fyb3VzZWwuZ29Ub1NsaWRlKGluZGV4PTApIiByb2xlPSJidXR0b24iIHRhYmluZGV4PSI0IiBjbGFzcz0ibXktc2xpZGUiPgogICAgICAgICAgICAgICAgPGRpdiBjbGFzcz0ic2xpZGUtaGVhZGVyIj4KICAgICAgICAgICAgICAgICAgICA8aDIgY2xhc3M9Im5vLW1hcmdpbiI+TGlnaHRib3ggU2xpZGUgMTwvaDI+CiAgICAgICAgICAgICAgICAgICAgPGRpdj5DbGljayBpbWFnZSB0byBjbG9zZTwvZGl2PgogICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICA8YW1wLWltZyBzcmM9Ii9zdGF0aWMvc2FtcGxlcy9pbWcvaW1hZ2UxLmpwZyIKICAgICAgICAgICAgICAgICAgICAgICAgIGxheW91dD0iZmlsbCIKICAgICAgICAgICAgICAgID48L2FtcC1pbWc+CiAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICA8ZGl2IG9uPSJ0YXA6bXlMaWdodGJveC5jbG9zZSxvdXRlckNhcm91c2VsLmdvVG9TbGlkZShpbmRleD0xKSIgcm9sZT0iYnV0dG9uIiB0YWJpbmRleD0iNSIgY2xhc3M9Im15LXNsaWRlIj4KICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9InNsaWRlLWhlYWRlciI+CiAgICAgICAgICAgICAgICAgICAgPGgyIGNsYXNzPSJuby1tYXJnaW4iPkxpZ2h0Ym94IFNsaWRlIDI8L2gyPgogICAgICAgICAgICAgICAgICAgIDxkaXY+Q2xpY2sgaW1hZ2UgdG8gY2xvc2U8L2Rpdj4KICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICAgICAgPGFtcC1pbWcgc3JjPSIvc3RhdGljL3NhbXBsZXMvaW1nL2ltYWdlMi5qcGciCiAgICAgICAgICAgICAgICAgICAgICAgICBsYXlvdXQ9ImZpbGwiCiAgICAgICAgICAgICAgICA+PC9hbXAtaW1nPgogICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgPGRpdiBvbj0idGFwOm15TGlnaHRib3guY2xvc2Usb3V0ZXJDYXJvdXNlbC5nb1RvU2xpZGUoaW5kZXg9MikiIHJvbGU9ImJ1dHRvbiIgdGFiaW5kZXg9IjUiIGNsYXNzPSJteS1zbGlkZSI+CiAgICAgICAgICAgICAgICA8ZGl2IGNsYXNzPSJzbGlkZS1oZWFkZXIiPgogICAgICAgICAgICAgICAgICAgIDxoMiBjbGFzcz0ibm8tbWFyZ2luIj5MaWdodGJveCBTbGlkZSAzPC9oMj4KICAgICAgICAgICAgICAgICAgICA8ZGl2PkNsaWNrIGltYWdlIHRvIGNsb3NlPC9kaXY+CiAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICAgIDxhbXAtaW1nIHNyYz0iL3N0YXRpYy9zYW1wbGVzL2ltZy9pbWFnZTMuanBnIgogICAgICAgICAgICAgICAgICAgICAgICAgbGF5b3V0PSJmaWxsIgogICAgICAgICAgICAgICAgPjwvYW1wLWltZz4KICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgPC9hbXAtY2Fyb3VzZWw+CiAgICA8L2Rpdj4KPC9hbXAtbGlnaHRib3g+CjwvYm9keT4KPC9odG1sPgo=).

In my example, I used AMP version `2102130314004` (affected by the regression). The current LTS (`2101230412006`) does not have this bug (See [LTS version in playground](https://playground.amp.dev/#share=PCFET0NUWVBFIGh0bWw+CjxodG1sIOKaoT4KPGhlYWQ+CiAgICA8bWV0YSBjaGFyc2V0PSJ1dGYtOCIgLz4KICAgIDx0aXRsZT5NeSBBTVAgUGFnZTwvdGl0bGU+CiAgICA8bGluayByZWw9ImNhbm9uaWNhbCIgaHJlZj0ic2VsZi5odG1sIiAvPgogICAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCIgLz4KICAgIDxzdHlsZSBhbXAtYm9pbGVycGxhdGU+Ym9keXstd2Via2l0LWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoOy1tb3otYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7LW1zLWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoO2FuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RofUAtd2Via2l0LWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW1vei1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1tcy1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1vLWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1Aa2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fTwvc3R5bGU+PG5vc2NyaXB0PjxzdHlsZSBhbXAtYm9pbGVycGxhdGU+Ym9keXstd2Via2l0LWFuaW1hdGlvbjpub25lOy1tb3otYW5pbWF0aW9uOm5vbmU7LW1zLWFuaW1hdGlvbjpub25lO2FuaW1hdGlvbjpub25lfTwvc3R5bGU+PC9ub3NjcmlwdD4KICAgIDxzY3JpcHQgYXN5bmMgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy9sdHMvdjAuanMiPjwvc2NyaXB0PgogICAgPHNjcmlwdCBhc3luYyBjdXN0b20tZWxlbWVudD0iYW1wLWxpZ2h0Ym94IiBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL2x0cy92MC9hbXAtbGlnaHRib3gtMC4xLmpzIj48L3NjcmlwdD4KICAgIDxzY3JpcHQgYXN5bmMgY3VzdG9tLWVsZW1lbnQ9ImFtcC1jYXJvdXNlbCIgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy9sdHMvdjAvYW1wLWNhcm91c2VsLTAuMS5qcyI+PC9zY3JpcHQ+CiAgICA8c3R5bGUgYW1wLWN1c3RvbT4KICAgICAgICBoMSB7CiAgICAgICAgICAgIG1hcmdpbjogMXJlbTsKICAgICAgICB9CiAgICAgICAgLm15LXNsaWRlIHsKICAgICAgICAgICAgcG9zaXRpb246IHJlbGF0aXZlOwogICAgICAgIH0KICAgICAgICAuc2xpZGUtaGVhZGVyIHsKICAgICAgICAgICAgYmFja2dyb3VuZDogd2hpdGVzbW9rZTsKICAgICAgICAgICAgcG9zaXRpb246IGFic29sdXRlOwogICAgICAgICAgICB0b3A6IDUlOwogICAgICAgICAgICBsZWZ0OiA1JTsKICAgICAgICAgICAgei1pbmRleDogMTsKICAgICAgICB9CiAgICAgICAgLm5vLW1hcmdpbiB7CiAgICAgICAgICAgIG1hcmdpbjogMDsKICAgICAgICB9CiAgICA8L3N0eWxlPgo8L2hlYWQ+Cjxib2R5Pgo8aDI+CiAgICBDb25uZWN0ZWQgQ2Fyb3VzZWxzIHNlZW0gbm90IHRvIHdvcmsgcHJvcGVybHkgYW55IG1vcmUuCjwvaDI+CjxwPgogICAgVGhlcmUgYXJlIHR3byBQcm9ibGVtczoKPC9wPgo8b2w+CiAgICA8bGk+VGhlIGZpcnN0IEltYWdlIGlzIGFjdHVjYWxseSB0aGUgbGFzdCBpbWFnZS4gSXQgc2VlbXMgbGlrZSB0aGUgaW5kZXggaXMgbm93IDEgYmFzZWQuCiAgICA8L2xpPgogICAgPGxpPklmIHlvdSBjbGljayBvbiB0aGUgaW1hZ2UgdG8gb3BlbiB0aGUgbGlnaHRib3gsIHlvdSBsYW5kIG9uIHRoZSB3cm9uZyBzbGlkZS4gVGhpcyBzaG91bGRuJ3QgaGFwcGVuLCBjYXVzZSB3ZSB1c2UgZ29Ub1NsaWRlKGluZGV4PTEpIChvciB3aGF0ZXZlciB0aGUgaW5kZXggaXMpIGhlcmUuPC9saT4KPC9vbD4KPHA+CiAgICBPdGhlciBvYnNlcnZhdGlvbnM6CjwvcD4KPHVsPgogICAgPGxpPkRvZXMgPHN0cm9uZz5ub3Q8L3N0cm9uZz4gaGFwcGVuIGluIHRoZSBjdXJyZW50IExUUyBWZXJzaW9uICgyMTAxMjMwNDEyMDA2KS48L2xpPgogICAgPGxpPkFsbW9zdCBmaXhlZCwgaWYgd2UgcmVtb3ZlIHRoZSBsb29wIGF0dHJpYnV0ZS4gQWxtb3N0LCBiZWNhdXNlIHRoZSBjbGlja2luZyB0aGUgbGFzdCBzbGlkZSBzdGlsbCBzaG93cyB0aGUgd3Jvbmcgc2xpZGUuPC9saT4KICAgIDxsaT5UaGlzIGhhcHBlbnMgZXZlbiBpZiB0aGUgc2xpZGVzIGRvIG5vdCBjb250YWluIGltYWdlcyAoc28gbm8gbmV0d29yayByYWNlIGlzIGludm9sdmVkIGhlcmUpLjwvbGk+CjwvdWw+Cgo8YW1wLWNhcm91c2VsIGlkPSJvdXRlckNhcm91c2VsIgogICAgICAgICAgICAgIGNvbnRyb2xzCiAgICAgICAgICAgICAgbG9vcAogICAgICAgICAgICAgIHR5cGU9InNsaWRlcyIKICAgICAgICAgICAgICB3aWR0aD0iNDAwIgogICAgICAgICAgICAgIGhlaWdodD0iMzAwIj4KICAgIDxkaXYgb249InRhcDpteUxpZ2h0Ym94Lm9wZW4sbGlnaHRib3hDYXJvdXNlbC5nb1RvU2xpZGUoaW5kZXg9MCkiIHJvbGU9ImJ1dHRvbiIgdGFiaW5kZXg9IjEiIGNsYXNzPSJteS1zbGlkZSI+CiAgICAgICAgPGgyIGNsYXNzPSJzbGlkZS1oZWFkZXIgbm8tbWFyZ2luIj5TbGlkZSAxPC9oMj4KICAgICAgICA8YW1wLWltZyBzcmM9Ii9zdGF0aWMvc2FtcGxlcy9pbWcvaW1hZ2UxLmpwZyIKICAgICAgICAgICAgICAgICBsYXlvdXQ9ImZpbGwiCiAgICAgICAgPjwvYW1wLWltZz4KICAgIDwvZGl2PgogICAgPGRpdiBvbj0idGFwOm15TGlnaHRib3gub3BlbixsaWdodGJveENhcm91c2VsLmdvVG9TbGlkZShpbmRleD0xKSIgcm9sZT0iYnV0dG9uIiB0YWJpbmRleD0iMiIgY2xhc3M9Im15LXNsaWRlIj4KICAgICAgICA8aDIgY2xhc3M9InNsaWRlLWhlYWRlciBuby1tYXJnaW4iPlNsaWRlIDI8L2gyPgogICAgICAgIDxhbXAtaW1nIHNyYz0iL3N0YXRpYy9zYW1wbGVzL2ltZy9pbWFnZTIuanBnIgogICAgICAgICAgICAgICAgIGxheW91dD0iZmlsbCIKICAgICAgICA+PC9hbXAtaW1nPgogICAgPC9kaXY+CiAgICA8ZGl2IG9uPSJ0YXA6bXlMaWdodGJveC5vcGVuLGxpZ2h0Ym94Q2Fyb3VzZWwuZ29Ub1NsaWRlKGluZGV4PTIpIiByb2xlPSJidXR0b24iIHRhYmluZGV4PSIzIiBjbGFzcz0ibXktc2xpZGUiPgogICAgICAgIDxoMiBjbGFzcz0ic2xpZGUtaGVhZGVyIG5vLW1hcmdpbiI+U2xpZGUgMzwvaDI+CiAgICAgICAgPGFtcC1pbWcgc3JjPSIvc3RhdGljL3NhbXBsZXMvaW1nL2ltYWdlMy5qcGciCiAgICAgICAgICAgICAgICAgbGF5b3V0PSJmaWxsIgogICAgICAgID48L2FtcC1pbWc+CiAgICA8L2Rpdj4KPC9hbXAtY2Fyb3VzZWw+CjxhbXAtbGlnaHRib3ggaWQ9Im15TGlnaHRib3giIGxheW91dD0ibm9kaXNwbGF5Ij4KICAgIDxkaXYgY2xhc3M9ImxpZ2h0Ym94Ij4KICAgICAgICA8YW1wLWNhcm91c2VsIGlkPSJsaWdodGJveENhcm91c2VsIgogICAgICAgICAgICAgICAgICAgICAgdHlwZT0ic2xpZGVzIgogICAgICAgICAgICAgICAgICAgICAgY29udHJvbHMKICAgICAgICAgICAgICAgICAgICAgIGxvb3AKICAgICAgICAgICAgICAgICAgICAgIHdpZHRoPSI0MDAiCiAgICAgICAgICAgICAgICAgICAgICBoZWlnaHQ9IjMwMCIKICAgICAgICA+CiAgICAgICAgICAgIDxkaXYgb249InRhcDpteUxpZ2h0Ym94LmNsb3NlLG91dGVyQ2Fyb3VzZWwuZ29Ub1NsaWRlKGluZGV4PTApIiByb2xlPSJidXR0b24iIHRhYmluZGV4PSI0IiBjbGFzcz0ibXktc2xpZGUiPgogICAgICAgICAgICAgICAgPGRpdiBjbGFzcz0ic2xpZGUtaGVhZGVyIj4KICAgICAgICAgICAgICAgICAgICA8aDIgY2xhc3M9Im5vLW1hcmdpbiI+TGlnaHRib3ggU2xpZGUgMTwvaDI+CiAgICAgICAgICAgICAgICAgICAgPGRpdj5DbGljayBpbWFnZSB0byBjbG9zZTwvZGl2PgogICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICA8YW1wLWltZyBzcmM9Ii9zdGF0aWMvc2FtcGxlcy9pbWcvaW1hZ2UxLmpwZyIKICAgICAgICAgICAgICAgICAgICAgICAgIGxheW91dD0iZmlsbCIKICAgICAgICAgICAgICAgID48L2FtcC1pbWc+CiAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICA8ZGl2IG9uPSJ0YXA6bXlMaWdodGJveC5jbG9zZSxvdXRlckNhcm91c2VsLmdvVG9TbGlkZShpbmRleD0xKSIgcm9sZT0iYnV0dG9uIiB0YWJpbmRleD0iNSIgY2xhc3M9Im15LXNsaWRlIj4KICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9InNsaWRlLWhlYWRlciI+CiAgICAgICAgICAgICAgICAgICAgPGgyIGNsYXNzPSJuby1tYXJnaW4iPkxpZ2h0Ym94IFNsaWRlIDI8L2gyPgogICAgICAgICAgICAgICAgICAgIDxkaXY+Q2xpY2sgaW1hZ2UgdG8gY2xvc2U8L2Rpdj4KICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICAgICAgPGFtcC1pbWcgc3JjPSIvc3RhdGljL3NhbXBsZXMvaW1nL2ltYWdlMi5qcGciCiAgICAgICAgICAgICAgICAgICAgICAgICBsYXlvdXQ9ImZpbGwiCiAgICAgICAgICAgICAgICA+PC9hbXAtaW1nPgogICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgPGRpdiBvbj0idGFwOm15TGlnaHRib3guY2xvc2Usb3V0ZXJDYXJvdXNlbC5nb1RvU2xpZGUoaW5kZXg9MikiIHJvbGU9ImJ1dHRvbiIgdGFiaW5kZXg9IjUiIGNsYXNzPSJteS1zbGlkZSI+CiAgICAgICAgICAgICAgICA8ZGl2IGNsYXNzPSJzbGlkZS1oZWFkZXIiPgogICAgICAgICAgICAgICAgICAgIDxoMiBjbGFzcz0ibm8tbWFyZ2luIj5MaWdodGJveCBTbGlkZSAzPC9oMj4KICAgICAgICAgICAgICAgICAgICA8ZGl2PkNsaWNrIGltYWdlIHRvIGNsb3NlPC9kaXY+CiAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICAgIDxhbXAtaW1nIHNyYz0iL3N0YXRpYy9zYW1wbGVzL2ltZy9pbWFnZTMuanBnIgogICAgICAgICAgICAgICAgICAgICAgICAgbGF5b3V0PSJmaWxsIgogICAgICAgICAgICAgICAgPjwvYW1wLWltZz4KICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgPC9hbXAtY2Fyb3VzZWw+CiAgICA8L2Rpdj4KPC9hbXAtbGlnaHRib3g+CjwvYm9keT4KPC9odG1sPgo=)).

**Comment by caroqliu** [comment] 2021-03-03 15:28
@dritter Thanks for filing this issue! This sounds like a duplicate of #32920 which was recently fixed, @micajuine-ho can you please confirm?

**Comment by micajuine-ho** [comment] 2021-03-03 15:52
Confirmed it is a dup and that it is solved by https://github.com/ampproject/amphtml/pull/32866. Will CP it into stable.

**Comment by micajuine-ho** [comment] 2021-03-04 15:03
CP is live in release 2102200206005.

**Closed by micajuine-ho** 2021-03-04 15:03 UTC
Labels: Component: amp-carousel, P0: Drop Everything, Type: Bug, WG: components
