### ISSUE TITLE
Error: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#21115] opened 2019-02-26 21:34 UTC
Error: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
at (https://raw.githubusercontent.com/ampproject/amphtml/1902191749350/src/url.js:527)
at ownerDocument (https://raw.githubusercontent.com/ampproject/amphtml/1902191749350/src/layout.js:451)
at (https://raw.githubusercontent.com/ampproject/amphtml/1902191749350/src/service/resource.js:881)
at document (https://raw.githubusercontent.com/ampproject/amphtml/1902191749350/src/focus-history.js:138)
at innerHeight (https://raw.githubusercontent.com/ampproject/amphtml/1902191749350/src/service/viewport/viewport-impl.js:832)
at leaveFullOverlayMode (https://raw.githubusercontent.com/ampproject/amphtml/1902191749350/src/service/viewport/viewport-impl.js:774)

go/amp-error/CJ247oKngbm9lgE

**Comment by mdmower** [comment] 2019-02-27 17:12
Duplicate of #20941 ?

**Comment by jridgewell** [comment] 2019-02-27 17:20
Yup.

**Closed by jridgewell** 2019-02-27 17:20 UTC
Labels: Type: Bug
