### ISSUE TITLE
failing firefox integration tests

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#5061] opened 2016-09-16 18:46 UTC
Firefox 45.0.0 (Linux 0.0.0) Viewer Visibility State Element Transitions in viewer from in the VISIBLE state calls unload when going to INACTIVE FAILED
<details>
    expected unlayoutCallback to have been called at least once, but it was never called
    AssertionError@/home/travis/build/ampproject/amphtml/node_modules/chai/chai.js:5553:18
    [3]</module.exports/Assertion.prototype.assert@/home/travis/build/ampproject/amphtml/node_modules/chai/chai.js:206:1
    sinonProperty/<@/home/travis/build/ampproject/amphtml/node_modules/sinon-chai/lib/sinon-chai.js:73:13
    addProperty@/home/travis/build/ampproject/amphtml/node_modules/chai/chai.js:4240:22
    require<["/home/travis/build/ampproject/amphtml/test/integration/test-visibility-states.js"]</</</</</</<@/tmp/590a2bd76816598a394fdba666c42438.browserify:34312:13 <- /home/travis/build/ampproject/amphtml/test/integration/test-visibility-states.js:245:12

Firefox 45.0.0 (Linux 0.0.0) Viewer Visibility State Element Transitions in viewer from in the VISIBLE state calls pause when going to PAUSED FAILED
    expected pauseCallback to have been called at least once, but it was never called
    AssertionError@/home/travis/build/ampproject/amphtml/node_modules/chai/chai.js:5553:18
    [3]</module.exports/Assertion.prototype.assert@/home/travis/build/ampproject/amphtml/node_modules/chai/chai.js:206:1
    sinonProperty/<@/home/travis/build/ampproject/amphtml/node_modules/sinon-chai/lib/sinon-chai.js:73:13
    addProperty@/home/travis/build/ampproject/amphtml/node_modules/chai/chai.js:4240:22
    require<["/home/travis/build/ampproject/amphtml/test/integration/test-visibility-states.js"]</</</</</</<@/tmp/590a2bd76816598a394fdba666c42438.browserify:34324:13 <- /home/travis/build/ampproject/amphtml/test/integration/test-visibility-states.js:257:12

..
Firefox 45.0.0 (Linux 0.0.0) Viewer Visibility State Element Transitions in viewer from in the HIDDEN state calls unload when going to INACTIVE FAILED
    expected unlayoutCallback to have been called at least once, but it was never called
    AssertionError@/home/travis/build/ampproject/amphtml/node_modules/chai/chai.js:5553:18
    [3]</module.exports/Assertion.prototype.assert@/home/travis/build/ampproject/amphtml/node_modules/chai/chai.js:206:1
    sinonProperty/<@/home/travis/build/ampproject/amphtml/node_modules/sinon-chai/lib/sinon-chai.js:73:13
    addProperty@/home/travis/build/ampproject/amphtml/node_modules/chai/chai.js:4240:22
    require<["/home/travis/build/ampproject/amphtml/test/integration/test-visibility-states.js"]</</</</</</<@/tmp/590a2bd76816598a394fdba666c42438.browserify:34362:13 <- /home/travis/build/ampproject/amphtml/test/integration/test-visibility-states.js:295:12

Firefox 45.0.0 (Linux 0.0.0) Viewer Visibility State Element Transitions in viewer from in the HIDDEN state calls pause when going to PAUSED FAILED
    expected pauseCallback to have been called at least once, but it was never called
    AssertionError@/home/travis/build/ampproject/amphtml/node_modules/chai/chai.js:5553:18
    [3]</module.exports/Assertion.prototype.assert@/home/travis/build/ampproject/amphtml/node_modules/chai/chai.js:206:1
    sinonProperty/<@/home/travis/build/ampproject/amphtml/node_modules/sinon-chai/lib/sinon-chai.js:73:13
    addProperty@/home/travis/build/ampproject/amphtml/node_modules/chai/chai.js:4240:22
    require<["/home/travis/build/ampproject/amphtml/test/integration/test-visibility-states.js"]</</</</</</<@/tmp/590a2bd76816598a394fdba666c42438.browserify:34375:13 <- /home/travis/build/ampproject/amphtml/test/integration/test-visibility-states.js:308:12

Firefox 45.0.0 (Linux 0.0.0) Viewer Visibility State Element Transitions in viewer from in the INACTIVE state calls layout and resume when going to VISIBLE FAILED
    expected layoutCallback to have been called at least once, but it was never called
    AssertionError@/home/travis/build/ampproject/amphtml/node_modules/chai/chai.js:5553:18
    [3]</module.exports/Assertion.prototype.assert@/home/travis/build/ampproject/amphtml/node_modules/chai/chai.js:206:1
    sinonProperty/<@/home/travis/build/ampproject/amphtml/node_modules/sinon-chai/lib/sinon-chai.js:73:13
    addProperty@/home/travis/build/ampproject/amphtml/node_modules/chai/chai.js:4240:22
    require<["/home/travis/build/ampproject/amphtml/test/integration/test-visibility-states.js"]</</</</</</<@/tmp/590a2bd76816598a394fdba666c42438.browserify:34393:13 <- /home/travis/build/ampproject/amphtml/test/integration/test-visibility-states.js:326:12

Firefox 45.0.0 (Linux 0.0.0) Viewer Visibility State Element Transitions in viewer from in the INACTIVE state calls resume when going to HIDDEN FAILED
    expected resumeCallback to have been called at least once, but it was never called
    AssertionError@/home/travis/build/ampproject/amphtml/node_modules/chai/chai.js:5553:18
    [3]</module.exports/Assertion.prototype.assert@/home/travis/build/ampproject/amphtml/node_modules/chai/chai.js:206:1
    sinonProperty/<@/home/travis/build/ampproject/amphtml/node_modules/sinon-chai/lib/sinon-chai.js:73:13
    addProperty@/home/travis/build/ampproject/amphtml/node_modules/chai/chai.js:4240:22
    require<["/home/travis/build/ampproject/amphtml/test/integration/test-visibility-states.js"]</</</</</</<@/tmp/590a2bd76816598a394fdba666c42438.browserify:34407:13 <- /home/travis/build/ampproject/amphtml/test/integration/test-visibility-states.js:340:12

..
Firefox 45.0.0 (Linux 0.0.0) Viewer Visibility State Element Transitions in viewer from in the PAUSED state calls resume when going to VISIBLE FAILED
    expected resumeCallback to have been called at least once, but it was never called
    AssertionError@/home/travis/build/ampproject/amphtml/node_modules/chai/chai.js:5553:18
    [3]</module.exports/Assertion.prototype.assert@/home/travis/build/ampproject/amphtml/node_modules/chai/chai.js:206:1
    sinonProperty/<@/home/travis/build/ampproject/amphtml/node_modules/sinon-chai/lib/sinon-chai.js:73:13
    addProperty@/home/travis/build/ampproject/amphtml/node_modules/chai/chai.js:4240:22
    require<["/home/travis/build/ampproject/amphtml/test/integration/test-visibility-states.js"]</</</</</</<@/tmp/590a2bd76816598a394fdba666c42438.browserify:34446:13 <- /home/travis/build/ampproject/amphtml/test/integration/test-visibility-states.js:379:12

.
Firefox 45.0.0 (Linux 0.0.0) Viewer Visibility State Element Transitions in viewer from in the PAUSED state calls unlayout when going to INACTIVE FAILED
    expected unlayoutCallback to have been called at least once, but it was never called
    AssertionError@/home/travis/build/ampproject/amphtml/node_modules/chai/chai.js:5553:18
    [3]</module.exports/Assertion.prototype.assert@/home/travis/build/ampproject/amphtml/node_modules/chai/chai.js:206:1
    sinonProperty/<@/home/travis/build/ampproject/amphtml/node_modules/sinon-chai/lib/sinon-chai.js:73:13
    addProperty@/home/travis/build/ampproject/amphtml/node_modules/chai/chai.js:4240:22
    require<["/home/travis/build/ampproject/amphtml/test/integration/test-visibility-states.js"]</</</</</</<@/tmp/590a2bd76816598a394fdba666c42438.browserify:34464:13 <- /home/travis/build/ampproject/amphtml/test/integration/test-visibility-states.js:397:12

.......
Firefox 45.0.0 (Linux 0.0.0): Executed 65 of 91 (8 FAILED) (skipped 26) (20.31 secs / 6.444 secs)
</details>

**Comment by erwinmombay** [comment] 2016-09-16 18:48
@dvoytenko you know anyone who can own fixing this?

**Comment by jridgewell** [comment] 2017-02-13 19:38
Dupe of https://github.com/ampproject/amphtml/issues/3461.

**Closed by jridgewell** 2017-02-13 19:38 UTC
Labels: To be deprecated - Related to: Testing, Type: Bug
