### ISSUE TITLE
Datepicker no longer supports "blocked" and "highlighted" attributes in Format shown by example

### ISSUE THREAD

**Issue by p2er** [ampproject/amphtml#27282] opened 2020-03-18 06:10 UTC
## What's the issue?

The amp-datepicker component ignores values given into the `blocked` and `highlighted` attributes.

Even the examples on https://amp.dev/documentation/examples/components/amp-date-picker/ stopped working, e.g.: 
`<amp-date-picker id="simple-date-picker-3"
  type="single"
  mode="static"
  layout="fixed-height"
  height="360"
  on="select:AMP.setState({date3: event.date ? event.date : ''})"
  locale="en"
  format="YYYY-MM-DD"
  highlighted="FREQ=WEEKLY;WKST=SU;BYDAY=TH"
  blocked="FREQ=WEEKLY;WKST=SU;BYDAY=SA,SU">
</amp-date-picker>`

Documentation here (https://amp.dev/documentation/components/amp-date-picker/?format=websites#blocked) states that only ISO 8601 dates separated by spaces are allowed. That does not match the example documentation ( https://amp.dev/documentation/examples/components/amp-date-picker/?format=websites#highlighted-and-blocked-attributes).

External configurations via src attribute are also ignored if given in that format (https://amp.dev/documentation/examples/components/amp-date-picker/?format=websites#external-configuration).

## How do we reproduce the issue?

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

1. open: https://amp.dev/documentation/examples/components/amp-date-picker/?format=websites#highlighted-and-blocked-attributes
2. IS: no date is blocked & no date is highlighted
3. SHOULD: apply config highlighted="FREQ=WEEKLY;WKST=SU;BYDAY=TH" & locked="FREQ=WEEKLY;WKST=SU;BYDAY=SA,SU"

## What browsers are affected?

All

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 2003101714470

**Comment by wassgha** [comment] 2020-03-19 10:10
@caroqliu to verify that this is a duplicate of #24682

**Comment by caroqliu** [comment] 2020-03-19 12:49
Thanks for filing this issue @p2er ! You are right, these have been broken and documented in the previously mentioned issue. Closing this in lieu of the original.

**Closed by caroqliu** 2020-03-19 12:49 UTC
Labels: P2: Soon, Type: Bug, UI: Component: amp-date-picker, WG: ui-and-a11y
