### ISSUE TITLE
Boilerplate style code doesn't verify against Google AMP check

### ISSUE THREAD

**Issue by PepeLopez** [ampproject/amphtml#18462] opened 2018-10-01 08:05 UTC
## What's the issue?

Boilerplate code (https://www.ampproject.org/docs/fundamentals/spec/amp-boilerplate) does not  get verified by google amp check. 

Given error:

> The tag "head > style[amp-boilerplate]" is missing or wrong, but is required by "noscript > style[amp-boilerplate]".

The document itself contains the code, which is placed within the <head> section.

## Solution ##
Add a whitespace after the style tag like this:
`<style amp-boilerplate> body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript> <style amp-boilerplate> body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>`

Now Google Amp check will verify this correctly.

## Note ##
A hint is already given on the page:
> Currently, allowed mutations are: (1) inserting arbitrary whitespace immediately after the style tag opens, and immediately before it closes; (2) replacing any space in the snippet below with arbitrary whitespace.

However, as user I expect a copy-paste code, so please add these two whitespaces into the code.

**Comment by choumx** [comment] 2018-10-01 15:17
Which validation tool is showing you that error? I can't reproduce this on [validator.ampproject.org](https://validator.ampproject.org/).

**Comment by Gregable** [comment] 2018-10-01 21:07
That prefix whitespace is optional, not required. I also cannot reproduce.

**Comment by Gregable** [comment] 2018-10-01 21:08
Closing, but I'm happy to reopen if you provide more information. For example, a publicly accessible URL that I can test out.

**Comment by PepeLopez** [comment] 2018-10-01 21:09
validator.ampproject.org passes the test succesfully, GoogleSearchConsole gives that that error:

> The tag "head > style[amp-boilerplate]" is missing or wrong, but is required by "noscript > style[amp-boilerplate]".

See attached 2 images from GoogleSearchConsole.
The first one is the indexed one - the first fun fact. On the one hand it's indexed, on the other hand the validator says it won't appear in search results.
However, the mentioned error is shown, it will be highlighted in the source code on the right pnael when you click on that error.

![amp_error_1_indexed_without_whitespace](https://user-images.githubusercontent.com/2588312/46315898-ee7e7580-c5ce-11e8-9a82-6080f688619b.png)

The second image shows the very same url by live testing the url. The very only change were the added whitespaces in the boilerplate style code, mentioned in the first post here.
Now, it still has this error, but it can't be displayed/highlighted  in the source code, which _seems_ to refer to kind of a validation bug/error!?

![amp_error_2_live_tested_with_whitespace](https://user-images.githubusercontent.com/2588312/46315899-ee7e7580-c5ce-11e8-9601-4b8a2ff3fdb9.png)

Please understand I can't give out the url for public, I can provide URLs for this issue via private message, mail or however you like.

You see the other errors in that image? As I already stated, validator.ampproject.org passes the test succesfully without errors, GSC throws errors. 
So, the only possibility to report for this bug seems to be here - I'm sorry if it's not the right place :/

**Comment by Gregable** [comment] 2018-10-01 21:14
Can you send me the URL via private message, in https://amphtml.slack.com for example. I have the same username there.

**Comment by PepeLopez** [comment] 2018-10-01 22:29
Thanks - but I can't join there, it's for google members only.

However, I figured it out what happened while writing a reproducable procedure:

* first things first: a serverside plugin generated on each amp page _once a day_ (!) a text output like "1" or "2" in the head section - which is an syntax error. 
* This error disappears on the second call (per day) of that amp site, which causes that GSC throws an error, and a re-validation on ampproject.org succeed.
* This means, at this point **this bug is BOGUS/VOID** and can be closed, **BUT**...
* The GSC validation doesn't report that syntax problem, while validator.ampproject.org DOES - which led to total confusion.

## Reproduce validation problem in GSC ##

As I mentioned, GSC isn't reporting that syntax error correctly, instead, because of this syntax error, the validator runs mad and throws several errors but not the right one. To reproduce try to validate in GSC code like this:
`<!doctype html>
<html amp lang="en">
  <head>
    <meta charset="utf-8">
    <script async src="https://cdn.ampproject.org/v0.js"></script>
    <title>Hello, AMPs</title>
    <link rel="canonical" href="http://example.ampproject.org/article-metadata.html">
    ProblemWasHere_JustSomeText<meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
    <script type="application/ld+json">
      {
        "@context": "http://schema.org",
        "@type": "NewsArticle",
        "headline": "Open-source framework for publishing content",
        "datePublished": "2015-10-07T12:02:41Z",
        "image": [
          "logo.jpg"
        ]
      }
    </script>
    <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
  </head>
  <body>
    <h1>Welcome to the mobile web</h1>
 This site contains syntax errors, which are not correctly shown by GSC, but by validator.ampproject.org
  </body>
</html>`

Thanks for your help anyway, even if it was just kinda [rubberducking](https://en.wikipedia.org/wiki/Rubber_duck_debugging)

**Comment by Gregable** [comment] 2018-10-01 22:47
Got it.

Re slack, it looks like the sign up link is [here](https://docs.google.com/forms/d/e/1FAIpQLSd83J2IZA6cdR6jPwABGsJE8YL4pkypAbKMGgUZZriU7Qu6Tg/viewform?fbzx=4406980310789882877) if you do want to engage in the future.

This makes sense. The Google Search Console shows you issues from the Google crawl, so it's a cached result. Recrawling most sites live when you load the Search Console is not feasible, so at that aggregated level it can only show you cached data. https://validator.ampproject.org/ operates on an URL level so you can iteratively debug.

Glad you were able to sort it.

**Closed by Gregable** 2018-10-01 22:47 UTC
Labels: Category: Validator, Type: Bug
