### ISSUE TITLE
amp-analytics should fire visibility beacon for every element matched by tag/class

### ISSUE THREAD

**Issue by src-code** [ampproject/amphtml#7654] opened 2017-02-18 00:01 UTC
Carryover from discussion in #5721 

Currently the visibility spec for `amp-analytics` will accept a tag name or classname selector, but will only fire a beacon for the first item that becomes visible.  I believe it should instead fire a new beacon for each item that matches as each becomes visible, or at least provide an option for that behavior if not the default.

This should also match new content as it becomes available (e.g., `amp-list` rendered content), which I believe is being handled in #7312?

## How do we reproduce the issue?

Test case:
http://jsbin.com/zecatipipa/edit?html,output

## What browsers are affected?

All browsers

## Which AMP version is affected?

Has always been broken, AFAIK.
Tested with AMP version 1487358851767

**Comment by rudygalfi** [comment] 2017-06-02 16:49
This behavior is by design, but we can take this as a feature request to support multiple things being selectable via a selector.

**Comment by src-code** [comment] 2017-06-02 17:07
Thanks @rudygalfi, it'd be huge to get this use case supported soon.  Very difficult to track things like native ads in a stream of content without it.

**Comment by aghassemi** [comment] 2017-08-14 19:08
@rudygalfi, @koshka also ran into this restriction.

**Comment by rudygalfi** [comment] 2017-08-25 17:10
Yeah, this is something I'd like to address soon.

**Comment by zhouyx** [comment] 2017-09-19 01:41
I have few questions regarding the multi-selector support. For example:
```
{
'request': ...
'on': 'visible',
'selector': ['A', 'B'],
'visibilitySpec': ....
}
```
1. Analytics sends two requests for A and B respectively. Does analytics need to include selector information on the two requests, or two identical requests are fine. 
2. If selector information is required, what kind of info?
3. Are there potential requirements for **AND**/**OR** operator to multi-selector? Say only send request when both A and B are visible.

**Comment by cpapazian** [comment] 2017-12-14 22:30
Will this support matching elements rendered from mustache templates?

**Comment by lannka** [comment] 2017-12-14 23:25
> Will this support matching elements rendered from mustache templates?

Yes, that's part of the requirement.

**Comment by zhouyx** [comment] 2018-01-17 23:36
Will track in #11380. Close this for now.

**Closed by zhouyx** 2018-01-17 23:36 UTC
Labels: Category: Analytics, P2: Soon, Type: Feature Request
