### ISSUE TITLE
Getting error in existing integration test suite for certain "AMP HTML URL Variable" 

### ISSUE THREAD

**Issue by ColombiaOnline** [ampproject/amphtml#35257] opened 2021-07-16 06:18 UTC
### Description

Facing compilation error in existing integration test suite for certain amp variables, which we are trying to add or remove in our defined json, which is as below :-

https://github.com/ampproject/amphtml/blob/main/extensions/amp-analytics/0.1/vendors/colanalytics.json

### Reproduction Steps

Existing amp Integration test suite gives compilation error in below scenarios :--
 
**Scenario 1** - When try to remove the below amp variables -
${zone}
${contentType}
${scrollHeight}
${totalEngagedTime}
${pageLoadTime}

**Scenario 2** - When try to add the below amp variable -

${externalReferrer}

Error logs mentioned in the "Relevant Logs" section.

### Relevant Logs

```shell
geet@TILLT05409:~/DMP/AMP-ANALYTICS/amphtml$ amp integration
[11:42:47] All packages in node_modules are up to date.
[11:42:48] Using task file amphtml/amp.js
[11:42:48] Starting 'integration'...
[11:42:48] Run amp --tasks to see a list of all test flags.
[11:42:48] ⤷ Use --nohelp to silence these messages.
[11:42:48] ⤷ Use --local_changes to run unit tests from files commited to the local branch.
[11:42:48] ⤷ Use --testnames to see the names of all tests being run.
[11:42:48] ⤷ Use --headless to run tests in a headless Chrome window.
[11:42:48] Running tests against minified code.
[11:42:48] Deleted paths:
[11:42:48] 	.babel-cache
[11:42:48] 	build
[11:42:48] 	dist
[11:42:48] 	dist.3p
[11:42:48] Running build. Press Ctrl + C to cancel...
[11:42:48] To skip building during future integration runs, use --nobuild with your amp integration command.
[11:42:48] Building version 2104061329000 of the runtime with the prod AMP config.
[11:42:48] ⤷ Use --config={canary|prod} with your amp build command to specify which config to apply.
[11:42:48] Building all AMP extensions.
[11:42:48] ⤷ Use --core_runtime_only to build just the core runtime and skip other JS targets.
[11:42:48] ⤷ Use --noextensions to skip building extensions.
[11:42:48] ⤷ Use --extensions=amp-foo,amp-bar to choose which extensions to build.
[11:42:48] ⤷ Use --extensions=inabox to build just the extensions needed to load AMP ads.
[11:42:48] ⤷ Use --extensions_from=examples/foo.amp.html to build just the extensions needed to load foo.amp.html.
[11:42:50] Bootstrapped 3p frames into dist.3p/current/ (30 m 1.209 s)
[11:42:53] Recompiled all CSS files into build/ (30 m 4.648 s)
[11:42:53] Compiling JS with esbuild and babel...
[11:42:54] ERROR: Error: Build failed with 1 error:
error: [babel] ENOENT: no such file or directory, open '/home/geet/DMP/AMP-ANALYTICS/amphtml/.babel-cache/0759946294a68d0936faf459bddecdc2.json' 

[11:42:54] ERROR: Error: Build failed with 1 error:
error: [babel] ENOENT: no such file or directory, open '/home/geet/DMP/AMP-ANALYTICS/amphtml/.babel-cache/f6414c71ba3cad11ecfd8f396790e3e9.json' 

[11:42:54] ERROR: Error: Build failed with 1 error:
error: [babel] ENOENT: no such file or directory, open '/home/geet/DMP/AMP-ANALYTICS/amphtml/.babel-cache/c1648f1929680d542aac1d100d4406f7.json' 

[11:42:54] 'integration' errored after 5s
[11:42:54] Error: Could not compile polyfills.js
    at handleBundleError (/home/geet/DMP/AMP-ANALYTICS/amphtml/build-system/tasks/helpers.js:407:20)
    at /home/geet/DMP/AMP-ANALYTICS/amphtml/build-system/tasks/helpers.js:513:21
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async compileUnminifiedJs (/home/geet/DMP/AMP-ANALYTICS/amphtml/build-system/tasks/helpers.js:496:23)
    at async compileJs (/home/geet/DMP/AMP-ANALYTICS/amphtml/build-system/tasks/helpers.js:658:12)
    at async Promise.all (index 0)
    at async compileAllJs (/home/geet/DMP/AMP-ANALYTICS/amphtml/build-system/tasks/helpers.js:204:3)
    at async doBuild (/home/geet/DMP/AMP-ANALYTICS/amphtml/build-system/tasks/build.js:73:5)
    at async buildRuntime (/home/geet/DMP/AMP-ANALYTICS/amphtml/build-system/common/utils.js:45:5)
    at async Runner.maybeBuild (/home/geet/DMP/AMP-ANALYTICS/amphtml/build-system/tasks/integration.js:37:7)
    at async Runner.setup (/home/geet/DMP/AMP-ANALYTICS/amphtml/build-system/tasks/runtime-test/runtime-test-base.js:368:5)
    at async integration (/home/geet/DMP/AMP-ANALYTICS/amphtml/build-system/tasks/integration.js:48:3)
    at async runTask (/home/geet/DMP/AMP-ANALYTICS/amphtml/build-system/tasks/amp-task-runner.js:77:5)
    at async Command.<anonymous> (/home/geet/DMP/AMP-ANALYTICS/amphtml/build-system/tasks/amp-task-runner.js:117:7) {
  showStack: false
}
```

**Comment by rsimha** [comment] 2021-07-16 17:06
I poked around and managed to find the root cause. When `amp integration` is run without any flags, we first compile a fresh copy of the runtime. In order to make sure there are no old artifacts, we invoke `clean()` (part of `amp clean`) as an in-process function call. 

This was all good until caching for babel transforms via the file system was added in #33314. It appears that the cache is being initialized during module load, and the artifacts are being cleaned up _after_ that, resulting in the error you're seeing. Note that if you re-run the same command, the error disappears.

For the time being, a workaround is to build first and then run the tests:

```sh
# Unminified code
amp build --fortesting
amp integration --nobuild

# Minified code
amp dist --fortesting
amp integration --compiled --nobuild
```

I should have a fix ready soon, will post an update here when it's checked in. This is a cool bug, thanks for reporting it @ColombiaOnline!

**Closed** 2021-07-17 01:50 UTC
Labels: Type: Bug, WG: infra
