### ISSUE TITLE
amp-google-doc-embed fails to display multiple documents

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amphtml#35238] opened 2021-07-15 11:45 UTC
### Description

This page is valid: https://afdsi.com/__amp-issues/_google-doc-embed/

It uses `amp-google-doc-embed` to feature PDFs, Google Sheets, and Word (docx) files.

However, only the first instance of `amp-google-doc-embed` works.

All document types work, but only when assigned to the first tab.

Are we doing something wrong, or can only one instance of amp-google-doc-embed be displayed on a page?

### Reproduction Steps

https://afdsi.com/__amp-issues/_google-doc-embed/

### Browser(s) Affected

Chrome, Firefox

**Comment by jaygray0919** [comment] 2021-07-17 21:24
@rebeccanthomas If you use google chrome developer tools to check status, the active tab will open the target document.
However, as you see, only the first tab opens in normal mode.
That behavior suggests to me that the issue is not severe.
Can this problem be resolved in the short term?
We have an iframe solution but would prefer to use a lighter-weight approach as illustrated in the example.
/jay

**Comment by alanorozco** [comment] 2021-07-27 16:27
**This issue is unrelated to `<amp-google-doc-embed>`**

The problem is the AMP runtime not understanding that the tab content is displayed via these CSS rules that toggle the tabs themselves (`#content...` are all `section` as well).

```css
section {
  display: none;
  ...
}

#tab1:checked ~ #content1,
#tab2:checked ~ #content2,
#tab3:checked ~ #content3,
#tab4:checked ~ #content4,
#tab5:checked ~ #content5 {
  display: block;
}
```

1. If I place multiple `<amp-google-doc-embed>` on the same tab, they all render fine.
2. If I place any kind of `<amp-*>` element on the second tab, it never renders.

cc @ampproject/wg-performance since this is a runtime issue.

**Comment by jaygray0919** [comment] 2021-07-27 16:41
I have a different tab scheme from @aghassemi and will experiment with that. Will copy you on that use case when it's ready.

**Comment by jridgewell** [comment] 2021-07-27 22:10
First, we have a requirement that things that are `display: none` do not cause a layout. This is easiest to understand when discussing Ads: if an ad cannot be seen, we cannot make a network request to fill the ad slot. This is both a resource win (less network/CPU usage), and a privacy win.

So, when doing initial detection on the document, we record whether an element is displayable. Ideally, when an element becomes displayed, we want to trigger layout. But it's extremely difficult to detect changes in `display: none`, because there's no Observer in JS that will tell us when computed styles change.

We do have a `MutationObserver` that listens to changes to the `hidden` attribute, which is our approved way to handle this. We can cause mutations of `hidden` via `amp-bind`, or an `on="tap:el.hide` handler on the checkboxes.

**Comment by samouri** [comment] 2021-07-28 16:02
I was able to get this example working by adding `on=tap:sectionN.show` to each of the `<input>` elements. See [here](https://live-amp-bugs.glitch.me/hidden-attr-action.html).

```html
<input id="tab1" type="radio" name="tabs" checked on="tap:content1.show">
<input id="tab2" type="radio" name="tabs" on="tap:content2.show">
<input id="tab3" type="radio" name="tabs" on="tap:content3.show">
<input id="tab4" type="radio" name="tabs" on="tap:content4.show">
<input id="tab5" type="radio" name="tabs" on="tap:content5.show">
```

**Comment by jaygray0919** [comment] 2021-07-28 17:11
Thank you @samouri - we did not know how to do that.

**Comment by samouri** [comment] 2021-07-28 22:30
@jaygray0919, I'm going to close this issue as I believe the issue is resolved. Feel free to comment back if there is something we missed!

**Closed by samouri** 2021-07-28 22:30 UTC
Labels: P2: Soon, Type: Bug, WG: performance

**Comment by jaygray0919** [comment] 2021-07-29 10:06
we're good @samouri thanks again for the solution.
