### ISSUE TITLE
Not able to read from amp state since version 012305051745000

### ISSUE THREAD

**Issue by marcmrf** [ampproject/amphtml#38967] opened 2023-05-17 14:07 UTC
### Description

It looks like we're experiencing some issues reading from AMP state since May 16th, I guess release day for version 012305051745000. 
Under development mode, using `#development=1` together with `AMP.printState()`, we can see state is properly populated. 

However, trying to acess it from amp-script is always returning null.

Changing v0.js script src for using lts version fixes the issue.

### Reproduction Steps

Amp state is populated using a remote endpoint,

```html
<amp-state
        id="flowcardsState"
        src="https://flowcards.mrf.io/json/active?page_technology=1&site_id=1659&client_id=CLIENT_ID(compass_uid)&canonical_url=CANONICAL_URL&hostname=CANONICAL_HOSTNAME&location=CANONICAL_URL&referrer=EXTERNAL_REFERRER&page_view_id_64=PAGE_VIEW_ID_64&scroll_height=SCROLL_HEIGHT&geo=__INJECT_GEO__&cid=_ga:CLIENT_ID(AMP_ECID_GOOGLE,,_ga),comScore:CLIENT_ID(comScore),compass_uid:CLIENT_ID(compass_uid)&version=sha384-hAIbiZrdxhM8FeqN8_RTibnHiVNzYCNbohecvMNstJFsRzNYCq8wVzyv1EImMrk9"
      ></amp-state>
```

Which populates flowcardsState with the following content

```
{
    "active": true,
    "amp": {
        "cid": "_ga:amp-Bf9I0PQTbwK-0c8SGjPGhg,comScore:amp-wFdYHp1nE6MJRB_GIsxOqw,compass_uid:amp-DFfJ8g0S-vpwKGYp71ig-w",
        "hostname": "lxcugy.csb.app",
        "location": "https://lxcugy.csb.app/",
        "referrer": "https://codesandbox.io/",
        "runtimeUrl": "https://flowcards.mrf.io/statics/experience-amp/sha384-hAIbiZrdxhM8FeqN8_RTibnHiVNzYCNbohecvMNstJFsRzNYCq8wVzyv1EImMrk9/flowcards-content.html",
        "siteId": "1659",
        "pageViewId64": "5RIg2DW-GA1hqnVS2zYbuw",
        "scrollHeight": "360"
    }
}
```

Both playgrounds are using flowcardsState.amp.siteId for replacing *will change* text. Only difference between them is v0.js version.

**Playground using master version:** https://codesandbox.io/s/dreamy-water-lxcugy?file=/index.html
**Playground using lts version:** https://codesandbox.io/s/inspiring-darwin-7yr68m?file=/index.html

In addtion,

resources loaded in master version

![master-assets](https://github.com/ampproject/amphtml/assets/9928519/80b04586-191f-4b49-a918-603d63f98377)

resources loaded in LTS version because getState is returning content
![LTS-assets](https://github.com/ampproject/amphtml/assets/9928519/561b247e-3075-4094-995b-891b402da0dc)

### AMP Version Affected

012305051745000

**Comment by erwinmombay** [comment] 2023-05-17 17:18
we've finished the rollback and confirmed the issue is resolved. I'm conducting the investigation on what caused the issue

**Comment by marcmrf** [comment] 2023-05-17 17:53
Thnx :clap:

**Comment by erwinmombay** [comment] 2023-05-17 18:57
issue was caused by https://github.com/ampproject/amphtml/pull/38853 we'll work on fixing worker-dom

**Comment by danielmguerrero** [comment] 2023-05-18 09:04
👏

**Comment by erwinmombay** [comment] 2023-05-24 04:49
Closing this issue but opened #39016 to investigate integration

**Closed by erwinmombay** 2023-05-24 04:49 UTC
Labels: Type: Bug, P0: Drop Everything
