### ISSUE TITLE
Is it possibile with AMP to style video button?

### ISSUE THREAD

**Issue by brusco77** [ampproject/amphtml#2301] opened 2016-02-26 16:21 UTC
Is it possibile with AMP to style video button (I would like to have a play button in the middle), like in html5+javascript?

Thank you

**Comment by dvoytenko** [comment] 2016-02-26 19:43
@brusco77 could you please clarify what you mean by styling the button? Or better yet, do you have a sample html5+javascript page that does it?

**Comment by brusco77** [comment] 2016-02-26 20:27
like these two videos at the middle of the page 
http://www.sorrisi.com/tv/virginia-raffaele-scrive-barbara-durso-ce-posta-per-te/
this is jwplayer, anyway there are simpler ways to do it with css & js. 
I guess this is not possible within AMP...

**Comment by dvoytenko** [comment] 2016-02-26 23:47
@brusco77 If it's possible to customize controls via CSS - it's most likely possible to do so in AMP as well. I'm not aware of such CSS though, so if you have some links, please share.

If it's not possible via plain CSS, it's likely still possible via changes to the `amp-video` extension.

**Comment by rudygalfi** [comment] 2016-02-27 00:14
Another approach would be to stick with jwplayer. There's a pending intent to implement from them here: #2125. I think this would mean the styling question is solved since you'd have jwplayer on both your AMP and non-AMP pages then.

**Comment by dvoytenko** [comment] 2016-02-27 00:47
@rudygalfi Is there a non-flash version of it?

**Comment by rudygalfi** [comment] 2016-03-01 03:30
I believe so. Looking at http://www.sorrisi.com/tv/virginia-raffaele-scrive-barbara-durso-ce-posta-per-te/ in mobile emulation shows a non-flash implementation.

**Comment by adelinamart** [comment] 2017-02-08 02:33
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)

**Closed by adelinamart** 2017-02-08 02:33 UTC
Labels: Category: Audio&Video, To be deprecated - Type: Question
