### ISSUE TITLE
amp-story not usable in version 1.0

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#16680] opened 2018-07-11 16:39 UTC
On desktop, the active page is not shown:

![screenshot of active page missing on amp-story desktop UI](https://user-images.githubusercontent.com/1651960/42586980-679fdd54-8507-11e8-9927-27f64c7c17be.png)
(from https://www.washingtonpost.com/graphics/2018/lifestyle/amp-stories/when-political-spouses-create-controversy/)

On mobile, tapping to the next/previous page does not work.

The combination of these two means that there is no platform on which stories published with amp-story:1.0 can be consumed.

**Comment by Enriqe** [comment] 2018-07-11 16:52
Confirmed in `amp-version`: `1530320824316` both from origin and cache.

**Comment by newmuis** [comment] 2018-07-11 16:55
Also confirmed in `amp-version`: `1531262625717` both on origin and cache.

**Comment by newmuis** [comment] 2018-07-11 16:56
Seems to be working in `amp-version`: `1530567757224` on origin.  I can't get the cache to serve that version.

**Comment by gmajoulet** [comment] 2018-07-11 17:37
I believe it is caused by the `amp-consent` extension [P0 bug](https://github.com/ampproject/amphtml/issues/16671).

Here's what could happen:

- Story is using `amp-consent`
- Story is paused until the `amp-consent` is resolved https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/1.0/amp-story.js#L736
- The consent promise never resolves, and thus the story remains in a paused state, preventing the navigation

**Comment by gmajoulet** [comment] 2018-07-11 17:53
Fixed by #16678

**Closed by gmajoulet** 2018-07-11 17:53 UTC
Labels: Category: AMP Story, P0: Drop Everything, Type: Bug
