### ISSUE TITLE
[amp-ad-custom] Error: null is not an object (evaluating 'a.split')

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#22779] opened 2019-06-11 15:04 UTC
```
Error: null is not an object (evaluating 'a.split')
at split (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/src/url.js:198)
at url (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/src/url.js:624)
at win (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/src/utils/xhr-utils.js:244)
at (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/src/service/xhr-impl.js:108)
at fetchAmpCors_ (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/src/service/xhr-impl.js:165)
at input (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/src/service/xhr-impl.js:139)
at fullUrl (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/extensions/amp-ad/0.1/amp-ad-custom.js:94)
at (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/src/custom-element.js:1162)
at (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/src/utils/promise.js:75)
at (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/src/utils/promise.js:74)
at (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/src/custom-element.js:1162)
at (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/src/service/resource.js:930)
at state (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/src/service/vsync-impl.js:459)
at tasks (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/src/service/vsync-impl.js:417)
```

go/ampe/CMyC6bWN2vrWQw

**Comment by choumx** [comment] 2019-06-24 21:26
This is probably caused by null `data-url` attribute in amp-ad-custom.js: https://github.com/ampproject/amphtml/blob/9c6f331cfb88cd3412afee7b3246b6cccba8bd94/extensions/amp-ad/0.1/amp-ad-custom.js#L93-L95

A lot of misleading type casting to non-nullable string in that file.

@Enriqe FYI check the call stack next time for the original caller:
```
at fullUrl (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/extensions/amp-ad/0.1/amp-ad-custom.js:94)
```

**Comment by choumx** [comment] 2019-06-24 22:30
Dupe of #21314.

**Closed by choumx** 2019-06-24 22:30 UTC
Labels: Category: Ads, Type: Bug

**Comment by Enriqe** [comment] 2019-06-25 12:49
Woops, must've missed that line. Sorry about that and thanks for triaging/closing this @choumx
