### ISSUE TITLE
Anchors linking to `/` are changed to `#` in Google AMP Cache if <base href="/"> is set

### ISSUE THREAD

**Issue by gazs** [ampproject/amphtml#19688] opened 2018-12-06 18:32 UTC
## What's the issue?

If the AMP page has a `<base href="/">` tag in its head, `<a href="/">` will get rewritten to `<a href="#">` when viewing it through the google amp viewer.

The document validates without errors as amphtml.

We could only see the issue on links clicking through from search such as https://www.google.it/amp/s/www.vogue.it/moda/news/2017/10/13/letizia-ortiz-look-piu-belli-della-regina-spagna%3famp and the AMP Test page on search.google.com, so this report may belong to another issue tracker instead of amphtml?

## How do we reproduce the issue?

Reduced test case is available at this url:
- web url: https://tree-crush.glitch.me/
- amp cache preview url: https://search.google.com/test/amp?url=https%3A%2F%2Ftree-crush.glitch.me

## What browsers are affected?

This affects the cache, so I assume all browsers would get the same html.

## Which AMP version is affected?

Reported version is Version 1811272154520

**Comment by torch2424** [comment] 2018-12-08 00:12
Triaging to @Gregable , since I think this is a cache issue? 😄 Feel free to re-assign.

**Comment by Gregable** [comment] 2018-12-10 20:54
Thank you for reporting. I can reproduce. A simpler preview would be:

https://tree--crush-glitch-me.cdn.ampproject.org/c/s/tree-crush.glitch.me/

This is an AMP Cache bug. I'll close it here, but it's being tracked as a Google Product issue as 120788831.

I'll try to update the github issue when it's resolved.

**Closed by Gregable** 2018-12-10 20:54 UTC

**Comment by Gregable** [comment] 2018-12-19 18:47
FYI, just an update. The issue is that the code for determining if a link is document-relative (ie: `<a href=#top>`) vs a navigation was using the base URL of the document to compare to. In most cases base URL == document URL or if not, base URL != the link URL. Either way, it would work fine.

In your case the base URL was the same as the link URL, so this bug triggered and rewrote the link to be document-relative.

This AMP Cache is being updated with the necessary changes, but due to holiday production freezes, this will likely not be rolled out until the new year.

**Comment by Gregable** [comment] 2019-01-18 18:50
This should be resolved now in the AMP Cache.

Existing pages in the AMP Cache may still display the bug until refreshed. Documents are refetched asynchronously on every page load, so this will only effect approximately the first page view.
