### ISSUE TITLE
Images embedded with amp-img are not shown in Safari on iOS

### ISSUE THREAD

**Issue by skydry** [ampproject/amphtml#11411] opened 2017-09-25 11:35 UTC
## What's the issue?

When accessing the AMP-cached version of the following site with Safari on iOS, with amp-img embedded images are not shown.

## How do we reproduce the issue?

1. Access the site's AMP versions via Google SERPs on iOS: Search for "picdx isabelle mathers" on google.com:
<img src="https://user-images.githubusercontent.com/32090571/30803798-418d9a2a-a1eb-11e7-90ba-d9083e624256.PNG" width="200"/>

2. Tap the respective AMP link in the SERPs and you get this:  
<img src="https://user-images.githubusercontent.com/32090571/30806873-bcf56a38-a1f7-11e7-8a64-5f229e0d4013.PNG" width="200"/>

The actual page with amp-img embedded images is https://picdx.com/isabellemathersx
(Besides, the homepage of picdx.com has an image embedded with ```background-image``` which is shown on the AMP version)

## What browsers are affected?

*Affected:*
iOS Safari on an iPhone 7 is affected
iOS Safari in Xcode's Simulator is affected

*Not affected:*
Android Chrome is not affected

## Which AMP version is affected?

1506041909031

**Comment by camelburrito** [comment] 2017-09-25 17:28
@dvoytenko - this could be a P0

**Comment by jridgewell** [comment] 2017-09-25 18:05
What version of safari?

**Comment by camelburrito** [comment] 2017-09-25 18:14
@skydry - Thanks for taking time to report the issue. However i don't see picdx.com show up on SERP. Could you tell me how to reproduce this.

**Comment by jridgewell** [comment] 2017-09-25 18:18
https://www.google.com/amp/s/picdx.com/isabellemathersx produces the error. This looks a publisher CSS error, not an AMP issue.

**Comment by jridgewell** [comment] 2017-09-25 18:32
Dupe of https://github.com/ampproject/amphtml/issues/11253.

**Closed by jridgewell** 2017-09-25 18:32 UTC

**Comment by jridgewell** [comment] 2017-09-25 19:28
To resolve this issue: Remove the `amp-img { z-index: -1 }` style.

**Comment by skydry** [comment] 2017-09-25 19:37
@jridgewell Thank you so much! This was the problem, I just fixed it. The ```z-index -1``` wasn't necessary anyway.

**Comment by bizimunda** [comment] 2018-02-15 09:40
http://www.hochzeitsfotografffm.de/
here is my site and I cannot see images on safari browser. I'm using iphone 7
