### ISSUE TITLE
AMP Carousel jumping to incorrect slides in mobile browser

### ISSUE THREAD

**Issue by merakmarey** [ampproject/amphtml#32785] opened 2021-02-22 13:44 UTC
On swipe AMP Carousel jump slides in mobile.
Last carousel in https://amp.dev/documentation/components/amp-carousel/
(IMPORTANT: SEE IT IN ACTUAL MOBILE DEVICE, NOT DESKTOP EMULATOR)
Swiping from right to left it will skip/jump to another slide

AMP Carousel 0.2 on REAL mobile devices.

**Comment by caroqliu** [comment] 2021-02-22 15:01
Hi @merakmarey, thanks for filing an issue! Can you send a screenshot or describe further what you are seeing when it "skips/jumps" to another slide? Including as much detail as possible would be greatly helpful to reproduce and debug the issue you are describing.

**Comment by merakmarey** [comment] 2021-02-22 16:21
Sure

here's a video of the behavior.
https://www.youtube.com/watch?v=lge7pQMCLmc&feature=youtu.be

To see the bug in action just go to the url provided using a cell phone, and on the last carousel swipe from right to left.
https://amp.dev/documentation/components/amp-carousel/

Let me know if you need more.

Thanks

**Comment by caroqliu** [comment] 2021-02-22 17:44
Thanks for providing the video! It looks like the behavior in the video is on the `amp-carousel` generated by `amp-lightbox-gallery`. I'm unfortunately not able to replicate it on the `amp-carousel` documentation page from Safari on iOS or Chrome on Android, for either version of the `amp-carousel` component. 

Could you provide a small sample of the code you used in your video that includes use of the `amp-lightbox-gallery`?

**Comment by merakmarey** [comment] 2021-02-22 18:25
Hi Caroline

Please before continuing can you explain how come are you unable to reproduce the error?

I have here 3 android devices and I am able to replicate it on all 3, with Chrome on Android..

Again, and this is very important, do not emulators. The error is only present on real mobile devices/browsers.

As I said before, if you go to the official amp.dev website link I provided you, and go to the last carousel (there are 3 of them)
and swipe from right to left, you will see the jump. On the same page you can see the code.

The video I provided was not made by me, it belongs to another dev who found the same issue.

Original issue was reported by me January last year, but it seems like no one paid attention..
https://github.com/ampproject/amphtml/issues/26249

There's a link there with code that will also replicate the error.

Let me know if you still need more.

**Comment by caroqliu** [comment] 2021-02-22 18:46
Ohhh, I see, thank you for providing the other issue for reference! Maybe I was not swiping fast enough on my devices? I did not use an emulator. I'm going to close this issue for now since it is a duplicate to the original.

**Closed by caroqliu** 2021-02-22 18:46 UTC
Labels: Component: amp-carousel, Component: amp-lightbox-gallery, Type: Bug, WG: components

**Comment by micajuine-ho** [comment] 2021-02-23 19:04
hi @merakmarey can you please provide the code that you used in https://www.youtube.com/watch?v=lge7pQMCLmc&feature=youtu.be

in a jsbin? 

This would greatly help our debugging efforts.

**Comment by merakmarey** [comment] 2021-02-23 20:37
Hi Micajuine

This one is closed, lets please continue on https://github.com/ampproject/amphtml/issues/26249#issuecomment-784438645

Thanks
