### ISSUE TITLE
data-amp-replace and data-amp-addparams do not work in 1508794187431

### ISSUE THREAD

**Issue by sarahgriffis** [ampproject/amphtml#11835] opened 2017-10-27 21:22 UTC
## What's the issue?

data-amp-replace and data-amp-addparams do not work in AMP version 1508794187431

## How do we reproduce the issue?

1. Go to https://www.notrayspizza.com/
2. Click the `Order Now on Slice` button

Notice amp-id is not populated in the next page url.
<img width="1291" alt="screen shot 2017-10-27 at 5 01 19 pm" src="https://user-images.githubusercontent.com/8161401/32125350-800673dc-bb39-11e7-9cc9-197e90f3eacb.png">

<img width="1174" alt="screen shot 2017-10-27 at 5 01 27 pm" src="https://user-images.githubusercontent.com/8161401/32125348-7e314636-bb39-11e7-926c-e12c6ee5b320.png">

Our code is `<a href="https://slicelife.com/restaurants/ny/brooklyn/11217/not-ray-s-pizza/menu" data-amp-replace="CLIENT_ID" data-amp-addparams="amp_id=CLIENT_ID(amp_id)">`

## What browsers are affected?

All browsers are affected.

## Which AMP version is affected?

This is a new issue in 1508794187431.  We would love to pin our AMP version to 1507083985898.

**Comment by dvoytenko** [comment] 2017-11-01 21:57
@cvializ @ericlindley-g ptal

**Comment by aghassemi** [comment] 2017-11-01 23:21
I think this is for @zhouyx @rudygalfi

**Comment by zhouyx** [comment] 2017-11-02 00:47
Yeah, looks like the CLIENT_ID() resolves to empty. I'll take a look tomorrow.

**Comment by zhouyx** [comment] 2017-11-02 17:45
Here's what I found. When we try to handle outgoing links with `data-amp-addparams`, we resolve url replacement sync. That say we only try to see if clientId has be requested before, if so get its value. This is not a new issue, I tried with version 1507083985898 and could still reproduce the error.

@sarahgriffis Did you recently remove a pageview analytics or pixel trigger ? That could be a reason why this started to not work recently. 

The fix for AMP can be trying to read cookie when try to resolve clientId sync.

**Comment by sarahgriffis** [comment] 2017-11-04 12:54
@zhouyx No, we actually added some trigger events.

**Comment by rudygalfi** [comment] 2017-11-13 18:22
As @zhouyx said in her last update, the CLIENT_ID substitution will only work if CLIENT_ID has been previously requested, see: https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#substitution-timing.

Is there an example of the before and after configurations? Strictly adding some trigger events doesn't seem like something that would cause this.

**Comment by rudygalfi** [comment] 2018-01-04 18:46
I'm going to close this for now, but please re-open if there's any additional detail we can go off to investigate.

**Closed by rudygalfi** 2018-01-04 18:46 UTC
Labels: Category: Analytics, P2: Soon, Type: Bug

**Comment by dcmoore-gd** [comment] 2020-03-26 20:56
@sarahgriffis I'm running into this problem, did you ever get it resolved?

**Comment by sarahgriffis** [comment] 2020-03-27 15:24
@dcmoore-gd Sorry, I don't remember what we ended up doing as a work around.
