### ISSUE TITLE
amp-inputmask: weird treatment of input mask characters in phone numbers

### ISSUE THREAD

**Issue by andrewwatterson** [ampproject/amphtml#20305] opened 2019-01-14 17:03 UTC
The phone number input mask seems to allow you to "skip" part of the mask by adding one of the punctuation characters before you've added part of a phone number.

1. Type "+1()-"
Expected: This should probably be an illegal value
Actual: I can legally input that and am blocked after four more digits

More realistic example: I am someone who is used to separating my phone numbers with dashes.
1. Type "1 339"
2. Type a dash
3. Type "225-3680"
Expected: My phone number 339-225-3680 appears, maybe slightly reformatted by the mask
Actual: The mask interprets my dash in step 2 as the end of the exchange part of the phone number and limits me to only the next four digits I type in ("+1(339)-2253")

@cvializ

**Comment by aghassemi** [comment] 2019-01-14 17:39
Setting to `P1` and adding to `UI - Recent Launch Support`. Please adjust the priority as needed after triage @cvializ.

**Comment by cvializ** [comment] 2019-01-14 23:12
This is actually expected behavior because I wrote the example wrong. This is fixed by using mandatory numbers with the `0` mask character vs optional numbers with the `9` mask character. 

https://github.com/ampproject/amphtml/tree/master/extensions/amp-inputmask

I vote to close

**Closed** 2019-01-15 00:31 UTC
Labels: P1: High Priority, Type: Bug
