### ISSUE TITLE
Error: undefined is not an object (evaluating 'a.obj')

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#17603] opened 2018-08-20 16:43 UTC
Appears starting in the current opt-in canary release (1534447274459)

Stack trace:
```
Error: undefined is not an object (evaluating 'a.obj')
at getLocalExistingServiceForEmbedWinOrNull (https://raw.githubusercontent.com/ampproject/amphtml/1534447274459/src/service.js:142)
at getRootNode (https://raw.githubusercontent.com/ampproject/amphtml/1534447274459/src/service/ampdoc-impl.js:352)
at (https://raw.githubusercontent.com/ampproject/amphtml/1534447274459/extensions/amp-ad-exit/0.1/filters/click-location.js:82)
at (https://raw.githubusercontent.com/ampproject/amphtml/1534447274459/extensions/amp-ad-exit/0.1/amp-ad-exit.js:410)
at (https://raw.githubusercontent.com/ampproject/amphtml/1534447274459/src/service/resource.js:768)
at (https://raw.githubusercontent.com/ampproject/amphtml/1534447274459/src/base-element.js:466)
at (https://raw.githubusercontent.com/ampproject/amphtml/1534447274459/src/service/resources-impl.js:555)
at (https://raw.githubusercontent.com/ampproject/amphtml/1534447274459/src/service/resources-impl.js:1277)
at (https://raw.githubusercontent.com/ampproject/amphtml/1534447274459/src/service/history-impl.js:499)
at onVisibilityChanged (https://raw.githubusercontent.com/ampproject/amphtml/1534447274459/src/service/resources-impl.js:251)
```

**Comment by lannka** [comment] 2018-08-20 20:04
duplicate of #17345

**Closed by lannka** 2018-08-20 20:04 UTC
Labels: Category: Ads, P2: Soon, Type: Bug
