### ISSUE TITLE
AMP components not working in android & ios webviews

### ISSUE THREAD

**Issue by nightpool** [ampproject/amphtml#26252] opened 2020-01-08 16:33 UTC
## What's the issue?

AMP embedded content (iframes, youtube, some images) doesn't work in android & iOS webviews.

## How do we reproduce the issue?

Requires an android or iOS app that uses a WebView to display an "amp first" web page. I've created a test webpage here that reproduces the issue with very simple code: https://wiggly-pulsar.glitch.me/

## What browsers are affected?

Tested on 
`Mozilla/5.0 (iPhone; CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148`
and
`Mozilla/5.0 (Linux; Android 10; Pixel 2 XL Build/QQ1A.191205.008; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/79.0.3945.93 Mobile Safari/537.36`

## Which AMP version is affected?

tested on `Version 1912201827130`. We noticed the regression in our production app on Friday, January 3rd 2020. Not sure how long the issue has existed, but it was working mid-December before we went on break.

**Comment by nightpool** [comment] 2020-01-08 16:34
seems similar to https://github.com/ampproject/amphtml/issues/24489—does AMP have regression tests that target these browsers?

**Comment by kristoferbaxter** [comment] 2020-01-08 17:37
@Kevinkimball tested this and was unable to reproduce.

**Comment by erwinmombay** [comment] 2020-01-08 17:40
@nightpool would you mind providing more details on how to replicate? 

I tried it on my android device and the `amp-youtube` component seems to be working
![Screenshot_20200108-093921](https://user-images.githubusercontent.com/354746/72001768-f332d000-31fa-11ea-8656-e7ca8c528b32.png)

**Comment by nightpool** [comment] 2020-01-08 17:42
@erwinmombay  the triple dot in the top left corner there makes me think that's an embedded chrome activity (shows "Powered by chrome" and "open in Chrome in the menu"), rather then a WebView.

**Comment by kevinkimball** [comment] 2020-01-08 17:54
I was also unable to reproduce in iOS webview. Here's a screenshot: 
![IMG_1024](https://user-images.githubusercontent.com/6886483/72002741-dbf4e200-31fc-11ea-97b4-42053902f2c9.jpg)

**Comment by nightpool** [comment] 2020-01-08 17:57
okay, will circle back with better reproducion steps and try to figure out
if it's something specific to my app.

**Comment by erwinmombay** [comment] 2020-01-08 18:03
double checked with webview instead of CCT on android
![Screenshot_20200108-100242 (1)](https://user-images.githubusercontent.com/354746/72003397-20cd4880-31fe-11ea-89c4-2a357da179d9.png)

**Comment by erwinmombay** [comment] 2020-01-08 18:04
@nightpool does the reduction work for you though on your device? want to make sure nothing else is interfering like blockers/addons etc

**Comment by nightpool** [comment] 2020-01-08 18:13
@erwinmombay the reduction I posted doesn't work in my app, but I was able to get it to work in https://play.google.com/store/apps/details?id=com.snc.test.webview2. I'm going to dig in to see if there's anything different we need to be doing on our side.

**Comment by erwinmombay** [comment] 2020-01-08 18:21
thanks for confirming @nightpool. let us know if you can find any more details and if theres anything we can help with. closing for now

**Closed by erwinmombay** 2020-01-08 18:21 UTC
Labels: Type: Bug
