### ISSUE TITLE
InternetExplorer is not longer support?

### ISSUE THREAD

**Issue by KnoellMarketing** [ampproject/amphtml#17533] opened 2018-08-16 07:27 UTC
Why the internet explorer isnt working anymore?

It was supported, but now it crashes with the javascript-error: "Das Objekt unterstützt die Eigenschaft oder Methode "assign" nicht" in v0.js (519,398) - translation (maybe not the best): "the object don't know the method "assign".

We've implemented amp by checking everything released the live project in full amp and now we look horrible and get a bad return of the customers with internet explorer.
We are able to add codes only to the internet explorer, maybe you have a fix or something?

thanks!

**Comment by KnoellMarketing** [comment] 2018-08-16 08:39
We just use a fast fix: implementing <script src="//cdn.polyfill.io/v2/polyfill.min.js"></script>, that adds the function (but is of course an AMP error).

**Comment by craigscott29** [comment] 2018-08-16 11:38
Presumably the crawler that detects AMP validation doesn't use IE11, so you could implement this script to (hopefully) protect the AMP validation. We just used it on our site (thanks for post this because we don't routinely check IE11).

```
<?php if (preg_match('~MSIE|Internet Explorer~i', $_SERVER['HTTP_USER_AGENT']) || (strpos($_SERVER['HTTP_USER_AGENT'], 'Trident/7.0; rv:11.0') !== false)) { ?>
	
		<script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
	
<?php } ?>

**Comment by KnoellMarketing** [comment] 2018-08-16 12:13
Thanks, but the correct If-Clause will be:
`if (preg_match('~MSIE|Internet Explorer~i', $_SERVER['HTTP_USER_AGENT']) || ((strpos($_SERVER['HTTP_USER_AGENT'], 'Trident/7.0;') !== false) && (strpos($_SERVER['HTTP_USER_AGENT'], '; rv:11.0') !== false)))`

you need to split the second string, because for example on windows surface you have "..Trident/7.0; Touch; rv:11.0"

**Comment by jridgewell** [comment] 2018-08-16 17:30
Closing this as a duplicate of #17505.

**Closed by jridgewell** 2018-08-16 17:30 UTC
