### ISSUE TITLE
Resources discoverwork tests flaky / broken on master

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#16156] opened 2018-06-19 20:51 UTC
Failed build: https://travis-ci.org/ampproject/amphtml/jobs/394267451
Tracking issue for investigating. 

```
DESCRIBE => Resources discoverWork
  IT => "after each" hook for "should update inViewport before scheduling layouts"
    ✗ Unexpected call: getRect() at setState@/tmp/src/finite-state-machine.js:73:6 <- /tmp/06a5dd42810f96349d72441265e06aad.browserify:66567:15
    Unexpected call: getRect() at setState@/tmp/src/finite-state-machine.js:73:6 <- /tmp/06a5dd42810f96349d72441265e06aad.browserify:66567:15
    Unexpected call: getRect() at setState@/tmp/src/finite-state-machine.js:73:6 <- /tmp/06a5dd42810f96349d72441265e06aad.browserify:66567:15
    Unexpected call: getRect() at setState@/tmp/src/finite-state-machine.js:73:6 <- /tmp/06a5dd42810f96349d72441265e06aad.browserify:66567:15
    Unexpected call: getRect() at setState@/tmp/src/finite-state-machine.js:73:6 <- /tmp/06a5dd42810f96349d72441265e06aad.browserify:66567:15
    Unexpected call: getRect() at setState@/tmp/src/finite-state-machine.js:73:6 <- /tmp/06a5dd42810f96349d72441265e06aad.browserify:66567:15
    Unexpected call: getRect() at setState@/tmp/src/finite-state-machine.js:73:6 <- /tmp/06a5dd42810f96349d72441265e06aad.browserify:66567:15
    Unexpected call: getRect() at setState@/tmp/src/finite-state-machine.js:73:6 <- /tmp/06a5dd42810f96349d72441265e06aad.browserify:66567:15
    Unexpected call: getRect() at setState@/tmp/src/finite-state-machine.js:73:6 <- /tmp/06a5dd42810f96349d72441265e06aad.browserify:66567:15
    Unexpected call: getRect() at setState@/tmp/src/finite-state-machine.js:73:6 <- /tmp/06a5dd42810f96349d72441265e06aad.browserify:66567:15
    Unexpected call: getRect() at setState@/tmp/src/finite-state-machine.js:73:6 <- /tmp/06a5dd42810f96349d72441265e06aad.browserify:66567:15
    Unexpected call: getRect() at setState@/tmp/src/finite-state-machine.js:73:6 <- /tmp/06a5dd42810f96349d72441265e06aad.browserify:66567:15
    Unexpected call: getRect() at setState@/tmp/src/finite-state-machine.js:73:6 <- /tmp/06a5dd42810f96349d72441265e06aad.browserify:66567:15
    Unexpected call: getRect() at setState@/tmp/src/finite-state-machine.js:73:6 <- /tmp/06a5dd42810f96349d72441265e06aad.browserify:66567:15
    Unexpected call: getRect() at setState@/tmp/src/finite-state-machine.js:73:6 <- /tmp/06a5dd42810f96349d72441265e06aad.browserify:66567:15
    Expectation met: getRect([...]) once
    fail@/tmp/node_modules/sinon/lib/sinon/mock-expectation.js:281 <- /tmp/06a5dd42810f96349d72441265e06aad.browserify:48590:34
    verify@/tmp/node_modules/sinon/lib/sinon/mock.js:108 <- /tmp/06a5dd42810f96349d72441265e06aad.browserify:48707:33
    /tmp/test/functional/test-resources.js:1116:4 <- /tmp/06a5dd42810f96349d72441265e06aad.browserify:148053:24
●●●●●●●●●●●●●●●●●●●
DESCRIBE => Resources changeSize
  DESCRIBE => attemptChangeSize rules wrt viewport
    IT => should change size when document is invisible
      ✗ Attempted to wrap getVisibilityState which is already wrapped
      checkWrappedMethod@/tmp/node_modules/sinon/lib/sinon/util/core/wrap-method.js:39 <- /tmp/06a5dd42810f96349d72441265e06aad.browserify:50304:34
      wrapMethod@/tmp/node_modules/sinon/lib/sinon/util/core/wrap-method.js:85 <- /tmp/06a5dd42810f96349d72441265e06aad.browserify:50350:31
      stub@/tmp/node_modules/sinon/lib/sinon/collection.js:119 <- /tmp/06a5dd42810f96349d72441265e06aad.browserify:47610:38
      /tmp/test/functional/test-resources.js:1997:19 <- /tmp/06a5dd42810f96349d72441265e06aad.browserify:148995:19
      --------------
      wrapMethod@/tmp/node_modules/sinon/lib/sinon/util/core/wrap-method.js:110 <- /tmp/06a5dd42810f96349d72441265e06aad.browserify:50375:40
      stub@/tmp/node_modules/sinon/lib/sinon/collection.js:119 <- /tmp/06a5dd42810f96349d72441265e06aad.browserify:47610:38
      /tmp/test/functional/test-resources.js:1450:17 <- /tmp/06a5dd42810f96349d72441265e06aad.browserify:148405:17
●
  IT => "after each" hook for "should change size when document is invisible"
    ✗ Expected getRect([...]) at least once (never called)
    fail@/tmp/node_modules/sinon/lib/sinon/mock-expectation.js:281 <- /tmp/06a5dd42810f96349d72441265e06aad.browserify:48590:34
    verify@/tmp/node_modules/sinon/lib/sinon/mock.js:108 <- /tmp/06a5dd42810f96349d72441265e06aad.browserify:48707:33
    /tmp/test/functional/test-resources.js:1785:4 <- /tmp/06a5dd42810f96349d72441265e06aad.browserify:148787:24
●
IT => "after each" hook for "should change size when document is invisible"
  ✗ You likely forgot to restore sinon timers (installed via sandbox.useFakeTimers).
  /tmp/test/_init_tests.js:479:20 <- /tmp/06a5dd42810f96349d72441265e06aad.browserify:111930:20
[20:24:31] Safari 11.1.0 (Mac OS X 10.13.4): Executed 1760 of 3611 (Skipped 174) 4 FAILED
```

**Comment by choumx** [comment] 2018-06-20 05:55
Thanks for filing this and skipping the flaky tests on Safari. Dupe of #16021.

**Closed by choumx** 2018-06-20 05:55 UTC
Labels: Related to: Flaky Tests
