### ISSUE TITLE
AMP not compatible with IE

### ISSUE THREAD

**Issue by Samreaksa** [ampproject/amphtml#17568] opened 2018-08-17 03:21 UTC
Hi Everyone,

I'm having a problem on amp stand alone website with IE 10, 11 browsers.

https://www.screencast.com/t/xFHVyaOw6Pq

Is there any way to display a browser update message? It should say something like this: Your web browser (Internet Explorer 10, 10...) is out of date.

Is there any way to add some Browser detection code to my website that will prompt the user to update their browser if IE11 is detected with amp like jQuery . . . ?

For example: jQuery Code 

if ( !$.browser.msie || $.browser.version < 12 ) { 
// Add prompt to user here 
} 

I was hoping that you could give me some advise.

Thanks,
Sam

**Comment by jpettitt** [comment] 2018-08-17 13:58
Closing as duplicate of #17505

**Closed by jpettitt** 2018-08-17 13:58 UTC

**Comment by Samreaksa** [comment] 2018-08-20 03:26
@jpettitt 

Is there any way to add Browser detection code on website that will prompt the user to update their browser if IE10, 11 is detected with amp like jQuery . . .  like jQuery?
