### ISSUE TITLE
amp-bind doesn't work on form submit-success event

### ISSUE THREAD

**Issue by meistudioli** [ampproject/amphtml#11693] opened 2017-10-16 06:59 UTC
Hi, To whom it may concern:

I try to add a feature after form submit which is clear **textarea content** when submit-success. So I use amp-bind on **<textarea>** and add submit-success event on **<form>**. But looks lke the binding doesn't work when submit-success occured.

Here comes my code:
```
<form method="post" action-xhr="WS_qna_post_amp.php" target="_top" on="submit-success:AMP.setState({status:{post:random()}})">
    <textarea name="q" [text]="status.post"></textarea>
    <input type="reset"  role="button" tabindex="0" value="cancel" />
    <input type="submit" value="submit" />
</form>
```

Have a nice day.

Paul

**Comment by aghassemi** [comment] 2017-10-16 19:58
@meistudioli I am unable to repro. Please see https://jsbin.com/mevepezoga/edit?html,js,output for a sample that works fine. 

It might be that your XHR endpoint doesn't actually return success?

Closing the issue, feel free to reopen if still a problem.

**Comment by meistudioli** [comment] 2017-10-17 02:08
Hi, @aghassemi :

I check your sample and the problem still happen. Please fill both field (input & textarea) and press "Subscribe" button. You will see the textarea's value can't be modify.

Please check my steps.
[Steps - video](https://youtu.be/IUaZHYG_SDY)

Thanks for concern this issue and have a nice day.

Paul

**Comment by aghassemi** [comment] 2017-10-17 16:59
Interesting! Changing `contextContent` on `TextArea` only works if user has not manually inputted anything... Seems consistent across browsers. Reopening.

**Comment by choumx** [comment] 2017-10-17 18:39
Dupe of #11246.

**Closed** 2017-10-17 18:44 UTC

**Comment by meistudioli** [comment] 2017-10-18 01:34
Hi, @choumx:

Looks like the issue has been fixed. Do you have any idea about when this fixed will release on prod ?

Have a nice day.

Paul

**Comment by choumx** [comment] 2017-10-18 16:27
Should hit prod by middle of next week.

**Comment by varungargofb** [comment] 2018-12-27 07:40
Hi, To whom it may concern:

I want to update the input element value on submit-success of the amp-form using the AMP State which is "isFav"
But it just make the input blank,

<amp-state id="markFavAmpState" class="i-amphtml-element i-amphtml-layout-container" hidden="" aria-hidden="true">
<script type="application/json" data-reactid="204">{"isFav":true}</script>
</amp-state>

Here comes my code:
<form method="post" action-xhr="/fav-tender-form-amp" target="_top" id="ampMarkFavTender" is="true" on="submit-success:AMP.setState({'isFav': event.response.isFavState})" novalidate="" class="i-amphtml-form user-valid amp-form-submit-success">
<input type="hidden" id="tenderAmpVal" name="tenderAmpVal" value="279" class="user-valid valid">
<input type="hidden" id="eventAmpVal" name="eventAmpVal" [value]="isFav" class="user-valid valid" value="">
</form>


Please help.
