### ISSUE TITLE
AMP-Ad for AdSense needs channel parameter

### ISSUE THREAD

**Issue by fletc3her** [ampproject/amphtml#7286] opened 2017-02-01 17:54 UTC
A request to support Google AdSense custom channel parameters. 

Channel targeting allows advertisers to select a published channel on which they want to show ads, e.g. category pages or recipes. Custom reports by channel can be used to perform A/B testing to try out different ad implementations. And other purposes.

The channel can be specified differently depending on whether asynchronous or synchronous ad loading is used. The method for asynchronous loading is to push the channels as part of the "params" object after loading the `adsbygoogle.js` script.

````
    (adsbygoogle = window.adsbygoogle || []).push({
      params: { google_ad_channel: "12345"}
    });
````

Documenation (See "Setting custom channels dynamically" topic): https://support.google.com/adsense/answer/1354736?hl=en

The AMP implementation would support custom channels through the `<amp-ad>` tag using a new parameter `data-ad-channel` which would accept a space separated list of custom channel numbers. These channels would be inserted into the initializer params similar to how `experimentId ` is implemented now.

````
<amp-ad width=436 height=15
      type="adsense"
      data-ad-client="ca-pub-12345"
      data-ad-slot="12345"
      data-ad-channel="54321 67890"
      data-ad-format="link">
 </amp-ad>
````

All browsers

Tested on version 1485231782273

**Comment by jridgewell** [comment] 2017-02-01 19:55
Duplicate of https://github.com/ampproject/amphtml/issues/4464. I'll reopen that one to get a comment.

**Closed by jridgewell** 2017-02-01 19:55 UTC
