### ISSUE TITLE
<amp-*> </amp-*> don't use contents as fallback

### ISSUE THREAD

**Issue by kevinmarks** [ampproject/amphtml#517] opened 2015-10-07 23:57 UTC
specifically

```
<amp-twitter width=390 height=50
    layout="responsive"
    data-tweetid="651787425052692481">
<blockquote class="twitter-tweet" data-conversation="none" lang="en">
<p lang="en" dir="ltr">
<a href="https://twitter.com/kevinmarks">@kevinmarks</a> a documentation bug! Will fix immediately. Related Github issue 
<a href="https://t.co/J8Kglgh2ki">https://t.co/J8Kglgh2ki</a></p>
&mdash; Malte Ubl (@cramforce) <a href="https://twitter.com/cramforce/status/651787425052692481">October 7, 2015</a></blockquote>
</amp-twitter>
```

displays the blockquote fallback under the decorated tweet.

Why not just support the same blockquote markup as using 

```
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script> 
```

does?

**Comment by cramforce** [comment] 2015-10-07 23:59
Should work if you put a placeholder attribute on the blockquote element.

We could introduce some special cases.

In general placeholder content has to adhere to the same sizing constraints as all content to avoid visual jank.

**Comment by cramforce** [comment] 2015-10-08 00:27
As a general explanation: AMP will render a placeholder before it even knows what amp-twitter is (which loads asynchronously), so we need a generic way to find the placeholder content. Since some custom elements use some of their children we cannot just go and use all of them as placeholders.

**Comment by BenWard** [comment] 2015-10-08 05:32
Thanks Kevin.

I'm giving this a fair amount of thought because for our Twitter case especially the fallback content is vitally important. News articles are written about Tweets and they're dependent on the text for context. The widgets are usually content not decoration, so if a Tweet is deleted (or Twitter were to be down at render time, or blocked in the viewer's country) it's important that the article still make sense, even if not rendered as an all-singing, all-dancing widget.

In general for components we need to think about both how to provide placeholder or fallback content, but also where the author is going to get it from. If it adds too much overhead to a writer or editor's workflow it won't get used and article robustness and quality will suffer. In Twitter's case we have a standard oembed API that returns the `blockquote` embed code above, which is usually what's pasted into content editors or pulled in by the CMS from a URL. It might be optimal for writers if an `<amp-` tag could be wrapped around that.

There's also the proposed Web Component `is` attribute, which I know is sitting unadopted by browser vendors at present, but would also work very gracefully with the existing code:

```
<blockquote class="twitter-tweet" is="amp-tweet">…</blockquote>
```

There's a lot of different ways we could go, and I'm looking forward to taking some time to explore them as we develop AMP.

Ben

**Comment by WebReflection** [comment] 2015-10-08 06:42
@BenWard unfortunately the `is=""` part of the specification  didn't make it for Custom Elements `v1` and vendors are still discussing if it's worth the hassle (it is in my opinion).

For consistency sake though it's easier to also explain `<amp-` tags without having dual behavior through the `is` attribute.

If I might suggest a possible workaround for this case, the rule `amp-twitter.-amp-element > blockquote { display: none; }` should do a reasonable job.

**Comment by dvoytenko** [comment] 2015-10-08 18:47
How about we use the "placeholder" system for this? It's still a bit new, but I think it could work very well here. E.g.:
```
<amp-twitter ...> 
  <blockquote placeholder>
  </blockquote>
</amp-twitter>
```

It currently requires the child to have a `placeholder` attribute. The placeholder elements are shown in the "unresolved" and "unbuilt" states automatically. Basically, placeholders are kept around and displayed until the element itself is ready to hide it. It's currently supported in `amp-anim` element, but the idea is to extend this support to all elements and we should be almost there.

**Comment by WebReflection** [comment] 2015-10-09 01:30
what if the fallback is an input with a placeholder which means ... actually, the input placeholder?

**Comment by dvoytenko** [comment] 2015-10-09 02:12
This is a very specific use of a `placeholder` attribute. Only direct children of AMP elements are considered for a placeholder. If there has to be an `input` with a placeholder attribute positioned inside the AMP element, it'd be easy enough to wrap it in a `div`. But it's rather unlikely that someone would want to put an `input` inside a `amp-video` or a `amp-twitter` tag. The ergonomics of `placeholder` attribute and consistency, however, were a rather good trade-off.

**Comment by adactio** [comment] 2015-10-10 18:45
I'm looking at the [custom elements spec](http://w3c.github.io/webcomponents/spec/custom/) and I can't find any mention of a <code>placeholder</code> attribute (which, as others have pointed out, is an already existing attribute on form fields).

@dvoytenko or @cramforce Could either of you point me to some existing documentation for this <code>placeholder</code> attribute? Or is this something that has been invented for AMP? (and if it's the latter, why not use some existing extension mechanism such as the <code>class</code> or <code>data-</code> attribute?)

**Comment by cramforce** [comment] 2015-10-10 19:16
Placeholder is an AMP concept. We are currently working to make it more
generic and upgrade it to be in the main spec as opposed to documented per
element.

We use non-data- attribute for framework attribute because data- attributes
are reserved for the application and extended element configuration.

You could argue for amp-placeholder but that looks noisy.

We generally reserve the right to use bare attributes in AMP. That seems to
be in idiomatic in the web components world. Disagreement should be uttered
there. We just follow precedent because we want to be good citizens.

**Comment by adactio** [comment] 2015-10-10 22:02
Riiiiiight. You just make up attributes. Attributes that already exist in other contexts in HTML. :-/

Um. At some point, you may have to stop referring to AMP HTML as a subset of HTML and just say it's a different language, because, well, if you invent attributes like this, it is.

> We just follow precedent because we want to be good citizens.

I suggest using HTML's existing mechanisms for extension if you plan on being good citizens. You've rejected <code>data-</code> attributes, saying:

> We use non-data- attribute for framework attribute because data- attributes
are reserved for the application and extended element configuration.

...but what you are doing *is* extended element configuration. That is **exactly** what you are doing.

At the very least, you could use <code>class="placeholder"</code>.

> We generally reserve the right to use bare attributes in AMP. That seems to
be in idiomatic in the web components world. Disagreement should be uttered
there.

Citation needed.

**Comment by slightlyoff** [comment] 2015-10-10 22:14
You can _absolutely_ make up attributes. We've been able to do that in HTML since parsers were forgiving which, it turns out, is roughly forever. Attributes are a contextual grammar: they have meaning in the context of the elements for which they're supported. Some attributes are common (e.g. `id`) across all `HTMLElement` subclass instances. Others are more local.

So it has always been. Nothing to see here.

**Comment by adactio** [comment] 2015-10-10 22:15
But <code>placeholder</code> *already* exists as an attribute in HTML, Alex.

**Comment by slightlyoff** [comment] 2015-10-10 22:16
[It's contextual to `<input>`](http://www.w3.org/TR/html5/forms.html#the-placeholder-attribute). It isn't in the root of the inheritance hierarchy. It can have other definitions in other contexts.

Maybe this isn't *wise*, but it clearly isn't verboten for any other reason.

**Comment by adactio** [comment] 2015-10-10 22:22
This is precisely the use-case for which <code>data-</code> attributes exist. A <code>data-placeholder</code> attribute would be far better in this situation: the <code>placeholder</code> is used by browsers (in form fields), while <code>data-</code> attributes are there specifically to be used by scripts like https://cdn.ampproject.org/v0.js

**Comment by cramforce** [comment] 2015-10-10 23:22
Data- is for apps. We use unprefixed names to avoid conflicts with them.
E.g. they are used to configure embeds.

This will not change until maybe in version 2.0 when we found out in
practice that we have a problem.

We can open another bug to rename placeholder to something else like
"instead" or "until-loaded" or whatever. But we will not stop attaching
semantics to custom attribute names for the time being.

**Comment by kevinmarks** [comment] 2015-10-11 00:20
You are an app. You don't work unless your js is included, and your required markup is actively hostile to pages working on their own.

**Comment by cramforce** [comment] 2015-10-11 00:26
I will talk to the polymer team. If they figured out their decisions were
bad I'll change my mind.

Kevin: in AMP no other JS could conflict. Only future extensions to HTML
and arguments to extended components.

**Comment by adactio** [comment] 2015-10-11 00:50
> Data- is for apps.

Whaa..? Where did this come from? And what's the definition of an app?

I'm guessing that something that requires JavaScript in order to parse custom elements in order to display an image leans heavily towards the app end of the spectrum.

You understand that because AMP HTML bans any JavaScript other than its own, there's literally no way that a <code>data-</code> attribute could possibly conflict with anything ("in AMP no other JS could conflict") but then say "Only future extensions to HTML" ...like, what? HTML gaining a <code>placeholder</code> attribute? Which it already has?

That's *exactly* the reason why it's safer **not** to create new attributes willy-nilly.

[Be conservative in what you send](https://en.wikipedia.org/wiki/Robustness_principle).

**Comment by adactio** [comment] 2015-10-11 10:59
If nothing else, how about having a consistent coding style? You've currently got the attribute <code>amp-custom</code> on the <code>style</code> element ...but plain ol' <code>placeholder</code> on other elements. If you're going to mint attributes, how about making them consistent by always having a prefix of <code>amp-</code>:

* <code>amp-custom</code>
* <code>amp-placeholder</code>
* <code>amp-layout</code>
* <code>amp-type</code>
* <code>amp-shortcode</code>

**Comment by amphtml-team** [comment] 2015-10-11 19:33
Jeremy and Keith, taking with html spec people and our users we found that
out attribute semantics are both clear and proper. They also have good
ergonomics. Do you have a good argument why we should change it? We found
that there's no concern of conflicts with input's placeholders. And there's
nothing "data" about these attributes. Also please note that we are getting
rid of "amp-custom" as well.

-d

**Comment by cramforce** [comment] 2015-10-11 21:46
@adactio Yeah, we ned to harmonize coding style!

amp-shotcode will become data-shortcode. We use data- as arguments to embeds. The newer embeds follow this convention. Easy to maintain backwarcd compat.

I'm not a fan of always `amp-` prefix. That is like namespacing the arguments to a function as in

```js
amp.youtube = function(ampLayout, ampPlaceholder, ampType, ampVideoId) {

}
```

Definitely gzips too well :)

**Comment by slightlyoff** [comment] 2015-10-13 04:17
There's zero reason for AMP to prefix its attributes. Again: attributes are a contextual grammar. You could make the case that `HTMLElement` prototype properties perhaps shouldn't be shadowed, or that it might be self-limiting for AMP to not prefix attributes in some specific cases, but there's no case for a blanket rule AFAICT.

This is what Custom Elements are for: letting us evolve the language without fear of conflict. That we create custom contexts by requiring `-` in tag names seems like going plenty far enough.

**Comment by kevinmarks** [comment] 2015-10-13 07:23
There is a particular problem when replacing built in elements with made-up
ones that expected behaviour changes. I was expecting amp-video to show
fallback contents like video does; amp-audio is missing controls and volume
attributes; amp-video is missing poster and has an unclear alternative and
so on.
I get the case for custom elements in general, it's using them to make
inconsistent, less-functional variants of the built-in ones that is the
problem.

**Comment by amphtml-team** [comment] 2015-10-13 07:29
Ask if these will follow in short order.

**Comment by adactio** [comment] 2015-10-13 08:01
> That we create custom contexts by requiring - in tag names seems like going plenty far enough.

@slightlyoff But Alex, in this case, the invented attributes aren't going on custom elements—they're going on existing HTML elements (that sit inside custom elements).

**Comment by jaicab** [comment] 2015-10-13 12:52
I couldn't agree more with @adactio here, using `placeholder` for this would be confusing and totally unnecessary. I am aware that we _can_ make up this attribute, but why use an attribute that already exists and has a meaning (even when it's only contextual) when we can avoid that? 
Since this is an AMP concept and it is to be used on an existing HTML element that sits inside a custom `amp` one, an AMP prefixed attribute would make the most sense to me. It would not only avoid confusion with `placeholder` but also the possible conflicts with already existing `data-` attributes in the site or "app". And more meaningful, as it would relate more the HTML element with the parent custom element.

**Comment by dvoytenko** [comment] 2015-10-13 16:17
I think we about a week or so away to review this part again - there are couple things need to happen in our code to be better prepared to review. That being said, I think we have tried for some time to find a practical reason why `placeholder` and similar attributes would be a bad thing and haven't quite found one yet. It's a rather common practice in HTML. It's not a "no" (at least as far as I'm concerned), but it's "I need to see more of a picture".

What I'd definitely like to put together very soon is a single-page document that summarizes all of the layout rules, including:
- `layout`
- `width`
- `height`
- `placeholder`
- `fallback`

These attributes all have to be considered together - they solve the same goal - providing clear and fully-defined layout and behavior before any JS can be fully downloaded and evaluated. One thing I can say for sure is that these are not CSS classes.

**Comment by dvoytenko** [comment] 2015-10-13 16:28
Adding `media` and `sizes` attributes above and clarified which attributes can actually be used on non-AMP elements.

**Comment by adactio** [comment] 2015-10-13 18:37
@dvoytenko said:

> One thing I can say for sure is that these are not CSS classes.

Well, sure. That's because there's no such thing as CSS classes. There is a CSS class _selector_. There is also an HTML class _attribute_. The HTML <code>class</code> attribute can be used to extend semantics for general-purpose processing by user-agents. Styling (via CSS) is one example of this, but the <code>class</code> attribute is not limited to this use case.

[The value of the <code>class</code> attribute is](http://www.w3.org/TR/html5/dom.html#classes)...

> ...a set of space-separated tokens representing the various classes that the element belongs to.

So if you have an element that needs be demarcated as being a placeholder element, one way of doing that using the existing mechanisms available within HTML would be:

    class="placeholder"

Or perhaps:

    class="amp-placeholder"

As for making up attributes yourself, [the HTML spec has this to say](http://www.w3.org/TR/html5/dom.html#semantics-0):

> Authors must not use elements, attributes, or attribute values that are not permitted by this specification or [other applicable specifications](http://www.w3.org/TR/html5/infrastructure.html#other-applicable-specifications), as doing so makes it significantly harder for the language to be extended in the future.

That's the crux of it. A hasty decision to just throw in a newly-minted <code>layout</code> attribute into AMP HTML today is exactly the kind of thing that causes all sorts of problems for standards bodies tomorrow (and, by extension, browser makers).

Please consider the long-term effects.

> Also, only placeholder and fallback are allowed currently to be placed on non-AMP elements.

Hence my concern. Adding new attributes to custom elements; sure. Adding new attributes to existing elements; nope.

Also, of the list provided...

* <code>layout</code>
* <code>width</code>
* <code>height</code>
* <code>media</code>
* <code>sizes</code>
* <code>placeholder</code>
* <code>fallback</code>

...four of those already exist in HTML and are being used appropriately in AMP HTML so I'm not sure why they're on the list:

* <code>width</code>
* <code>height</code>
* <code>media</code>
* <code>sizes</code>

If we're documenting all attributes that affect layout, then <code>src</code>, <code>srcset</code>, etc. should also be included. If, however, we're documenting which attributes have been invented for AMP HTML, the list is much shorter:

* <code>layout</code>
* <code>placeholder</code> (well, not really, because it already exists in another context)
* <code>fallback</code>

As you say, it is <code>placeholder</code> and <code>fallback</code> that are really of concern because they are being used on *existing* (rather than custom) elements. <code>layout</code> is less of an issue.

**Comment by dvoytenko** [comment] 2015-10-13 20:59
Thanks for the primer. Didn't we agree that `layout` is a non-issue since it's defined exclusively on AMP elements only?

`src` and `srcset` do NOT affect layout.

**Comment by adactio** [comment] 2015-10-13 21:22
@dvoytenko wrote:

> Didn't we agree that layout is a non-issue since it's defined exclusively on AMP elements only?

Yes (hence “<code>layout</code> is less of an issue”).

> <code>src</code> and <code>srcset</code> do NOT affect layout.

I'm confused by this. I'm not sure what the connection is between which attributes do and don't affect layout, and which attributes are being invented from scratch (rather than existing already in HTML). I get that the invented attributes <code>layout</code>, <code>placeholder</code>, and <code>fallback</code> all _happen_ to be related to layout, but that's orthogonal to the issue at hand, which is the larger effects of inventing new attributes (regardless of what those attributes do).

**Comment by adelinamart** [comment] 2017-02-07 20:38
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)

**Closed by adelinamart** 2017-02-07 20:38 UTC
Labels: Type: Discussion/Question
