### ISSUE TITLE
amp-next-page failed in rendering

### ISSUE THREAD

**Issue by xiaotong-z** [ampproject/amphtml#17149] opened 2018-07-27 03:46 UTC
## What's the issue?

Under slow connection or long server response time, the amp-next-page will not render the first ampUrl in pages even with response, and will not send request of the second ampUrl.

## How do we reproduce the issue?

1. add <amp-next-page> with 2 ampUrl in pages to AMP
2. switch the connection to fast 3G or slow 3G
3. reload and scroll to the bottom of AMP page quickly
4. there will be only 1 request for the first ampUrl in pages without rendering response.

**Comment by peterjosling** [comment] 2018-07-27 15:55
This is working as intended for now - we don't want to change the content of the page after the user has already scrolled it into view. There should be a recommendation box displayed containing links to both of the pages in this case, which will also nicely handle cases where users may be offline.

**Comment by aghassemi** [comment] 2018-07-27 16:54
Closing as intended behaviour based on comment above.

**Closed by aghassemi** 2018-07-27 16:54 UTC
Labels: Closed: Intended
