### ISSUE TITLE
nexxtv-player: video interface integration is broken.

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#8264] opened 2017-03-20 19:02 UTC
`nexxtv-player` does not response to any of the post messages sent for `pause`, `play`, etc.. It also does not send any messages back for the events like `playing`

@neko-fire, did anything change with the player? It does not to the commands sent via post message from `amp-nexxtv-player`

**Comment by neko-fire** [comment] 2017-03-21 13:00
Hi @aghassemi,

I'll check internally, since I'm not involved in the player development. But the test cases for postmessages are still fine?

**Comment by aghassemi** [comment] 2017-03-21 17:51
@neko-fire Here is a test page: http://s.codepen.io/aghassemi/debug/MpVJRQ 

The `play`, `pause`, etc.. buttons send the postMessages as coded in the the [amp-nexxtv-player.js](https://github.com/ampproject/amphtml/blob/master/extensions/amp-nexxtv-player/0.1/amp-nexxtv-player.js) but the player does not seem to honour those messages at all (as you see nothing happends).

Also player does not seem to be sending back any event messages back to  [amp-nexxtv-player.js](https://github.com/ampproject/amphtml/blob/master/extensions/amp-nexxtv-player/0.1/amp-nexxtv-player.js when video events happen in the player (e.g. user plays the video)

Could you please look into ensuring the player handles the messages correctly? (when fixed, I will enable integration tests on our side to catch future regressions). As it currently stands, nexxtv-player has broken implementation of the video-interface.

**Comment by neko-fire** [comment] 2017-03-22 10:52
@aghassemi on your testpage` https://cdn.ampproject.org/v0/amp-nexxtv-player-0.1.js` is not found (404). For testing I used the sources from `dist `folder. We did not change the player since then.

**Comment by aghassemi** [comment] 2017-03-24 16:04
@neko-fire I figured out the issue with postMessaging _**into**_ the iframe however I am not seeing any messages being posted back **_from_** the iframe. (e.g. when it is supposed to send messages for events such as user tapping play or pause, etc...) 

So using http://lab.nexx.cloud/postMessage.php:
`window.addEventListener('message', function(data) { console.log(data); } );`
does not log anything.

Would you please look into this?

**Comment by neko-fire** [comment] 2017-03-28 08:26
yes okay.

**Comment by neko-fire** [comment] 2017-03-31 11:36
Hi @aghassemi 

I've looked into this issue - yes indeed we do not send any messages back, but we can develop it.

Questions: 
- what messages shall we send back and how shall we structure it?
- when shall we send back the message - only when the player receive a postmessage or also events from other sources like clicking on the play button in the player

**Comment by aghassemi** [comment] 2017-03-31 15:59
@neko-fire Thanks for looking into it.

We need messages whenever the following events happen in the player (regardless of whether it is performed by the user or programatically):
  - when video starts playing (user taps the play button or `play()` method is called).
  - when video pauses (user taps the pause button or `pause()` method is called).
  - when video is muted (user taps mute button, sets the volume to 0 or `mute()` method is called).
  - when video is unmuted (user taps unmute button, sets the volume to > 0 or `unmute()` method is called).

The structure is up to you, at the end of the day `handleNexxMessages_(event)` receives those messages and needs to digest them and dispatch one of `VideoEvents.PLAY`, `VideoEvents.PAUSE`, `VideoEvents.MUTED`, `VideoEvents.UNMUTED` events in return. (that code already exists in `amp-nexxtv-player.js` by the way, it just does not work)

**Comment by neko-fire** [comment] 2017-04-04 14:22
@aghassemi thanks a lot for!

quick update: we are currently reworking postmessages in our player. For amp-nexxtv-player there is only a small change required. I'll submit a fix when the player is live and working.

**Comment by aghassemi** [comment] 2017-04-04 14:59
Sounds good, thanks!

**Comment by aghassemi** [comment] 2017-07-27 18:23
@neko-fire Any updated on this? Still broken, none of the postMessage commands work.

**Comment by neko-fire** [comment] 2017-07-28 06:12
Hi @aghassemi ,
this issue was fixed in https://github.com/ampproject/amphtml/pull/8932 , but if there is still a problem I can take another look.

**Comment by aghassemi** [comment] 2017-07-31 20:31
@neko-fire still an issue. `autoplay` does not work and all the `play`, `pause`, `mute`, `unmute` actions don't do anything. Here is a sample page: https://codepen.io/aghassemi/pen/LjNjXg

**Comment by alanorozco** [comment] 2018-05-24 16:26
Actually, actions only work after initial playback.

**Comment by neko-fire** [comment] 2018-07-24 10:17
Hi @alanorozco, this is intended behaviour.

**Closed** 2019-06-21 16:16 UTC
Labels: Category: Audio&Video, P3: When Possible, Type: Bug
