### ISSUE TITLE
pushHistory, popHistory errors in prod

### ISSUE THREAD

**Issue by chenshay** [ampproject/amphtml#9548] opened 2017-05-25 16:21 UTC
Our production error reporting reveals errors with pushHistory & popHistory

**Comment by camelburrito** [comment] 2017-09-26 23:25
related to https://github.com/ampproject/amphtml/issues/11448 ?

**Comment by dvoytenko** [comment] 2017-09-26 23:27
Dupe of #8785.

**Closed by dvoytenko** 2017-09-26 23:27 UTC
Labels: Category: Tooling, P2: Soon, Type: Bug
