### ISSUE TITLE
RESIZE_REJECT in console amp-ad

### ISSUE THREAD

**Issue by DenyHF** [ampproject/amphtml#23542] opened 2019-07-26 12:32 UTC
Hello!
After implementing requestResize, errors appeared in the console.
https://prnt.sc/okdgrz
https://prnt.sc/olk5rw
In the screenshot you can see that with each resizing request console.error appears.

**Comment by tomerlevy1** [comment] 2019-07-29 11:37
+1
I also see the same issue with amp-embed

**Comment by choumx** [comment] 2019-08-13 16:11
Duplicate of #23619.

**Closed by choumx** 2019-08-13 16:11 UTC
Labels: Type: Bug
