### ISSUE TITLE
[RC Channel] amp-bind on tap events unable to set amp-state

### ISSUE THREAD

**Issue by candice-womp** [ampproject/amphtml#23329] opened 2019-07-15 19:08 UTC
## What's the issue?

Elements that are direct children of the body or are descendants of direct children of the body are unable to set an amp-state on tap.

## How do we reproduce the issue?

Example URL: https://amp.luckyvitamin.com/
Make sure that RC Channel is active in order to reproduce the issue.

After the page has loaded click on the Menu button in the header. This menu button has two on tap events - one is to set the state and the other is to open an amp-sidebar. The tap event to open the sidebar does work however the tap event to set the state does not. This causes the page to freeze due to the amp-sidebar being activated.

## What browsers are affected?

All browsers.

## Which AMP version is affected?

This is a new issue using Version 1907091704050 via the RC Channel.

**Comment by candice-womp** [comment] 2019-07-15 23:41
We are also seeing issues with amp-bind where bindable attributes are not listening to the amp-state whenever it changes.

Example: predictive search does not work at https://amp.raise.com

**Comment by choumx** [comment] 2019-07-15 23:54
Thanks for the report. I confirmed this is the same root cause as #23281 and is fixed by #23333. We'll patch the RC tomorrow before promoting it to prod.

**Comment by choumx** [comment] 2019-07-16 19:28
Verified this is fixed in [1907152257550](https://github.com/ampproject/amphtml/releases/tag/1907152257550).

**Closed by choumx** 2019-07-16 19:28 UTC
Labels: P1: High Priority, Type: Bug, WG: runtime
