### ISSUE TITLE
[canary error]The object does not support the operation or argument.

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#9748] opened 2017-06-06 21:03 UTC
```
postMessage@[native code]
sendMessage@user-script:2:13:56
W@user-script:2:13:316
v@user-script:2:13:1141
[native code]
Uj@https://cdn.ampproject.org/rtv/011496245713200/v0.js:396:59
sendMessage@https://cdn.ampproject.org/rtv/011496245713200/v0.js:394:489
https://cdn.ampproject.org/rtv/011496245713200/v0.js:269:132
hj@https://cdn.ampproject.org/rtv/011496245713200/v0.js:359:229
Of@https://cdn.ampproject.org/rtv/011496245713200/v0.js:358:190
[native code]
Nb@https://cdn.ampproject.org/rtv/011496245713200/v0.js:247:627
Ue@https://cdn.ampproject.org/rtv/011496245713200/v0.js:247:312
https://cdn.ampproject.org/rtv/011496245713200/v0.js:296:749
```

**Comment by camelburrito** [comment] 2017-06-06 21:04
postMessage@[native code] sendMessage@user-script:1:13:56 W@user-script:1:13:316 v@user-script:1:13:1141 [native code] Xj@https://cdn.ampproject.org/rtv/001496360274808/v0.js:400:59 sendMessage@https://cdn.ampproject.org/rtv/001496360274808/v0.js:398:489 https://cdn.ampproject.org/rtv/001496360274808/v0.js:337:98 kj@https://cdn.ampproject.org/rtv/001496360274808/v0.js:363:229 Uf@https://cdn.ampproject.org/rtv/001496360274808/v0.js:362:190 [native code]
r=
ae=doubleclick [object HTMLUnknownElement]: XHR Failed fetching (https://cdn.ampproject.org/...): Unknown HTTP status 0​​​,The object does not support the operation or argument.,The object does not support the operation or argument.,The object does not support the operation or argument.,The object does not support the operation or argument.
SHORT=1)

**Comment by camelburrito** [comment] 2017-06-06 21:18
http_user_agent: "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) GSA/27.0.155813979 Mobile/14F89 Safari/602.1"

**Comment by jridgewell** [comment] 2017-06-06 22:11
Pantheon id? What's the referrer?

**Comment by cvializ** [comment] 2017-06-06 22:19
I've seen "HTTP Status 0" caused by the browser canceling in-flight XHRs when the user navigates away from a page. Do you think that could be part of what we're seeing here?

**Comment by jridgewell** [comment] 2017-06-06 22:23
Tracked internally at b/37641406.

**Comment by camelburrito** [comment] 2017-06-06 22:25
@jridgewell - i think this is new.

@cvializ - i only found the status 0 one log

**Comment by jridgewell** [comment] 2017-06-06 22:51
It's an issue with recycling webviews in iOS apps. Fixed in iGSA.

**Closed by jridgewell** 2017-06-06 22:51 UTC
Labels: Internally Tracked, Type: Bug
