### ISSUE TITLE
<amp-form> not working after google cache

### ISSUE THREAD

**Issue by Superdrac** [ampproject/amphtml#7868] opened 2017-03-01 17:12 UTC
I made a little amp page with a form on it, and it was just validated today by google and added to his cache.

I had a form on it (amp-form) which work when I reach the website with the direct URL, but which don't work when I access it from the google search result. 

Google return this error: 

> 403 That's an error.
Your client does not have permission to get url /v/s/mywebsitedomain/?amp_js_v=7 from this server.

**Comment by honeybadgerdontcare** [comment] 2017-03-01 17:24
Could you provide the url to the document or the original `<amp-form>` html segment?

**Comment by Superdrac** [comment] 2017-03-01 17:37
My bad, I have the absolute path in the action..

**Comment by honeybadgerdontcare** [comment] 2017-03-01 18:31
The cache won't change amp-form action-xhr urls. So this should work just as intended, unless there's an issue with XHR endpoints. See [CORS Request in AMP spec](https://github.com/ampproject/amphtml/blob/master/spec/amp-cors-requests.md) for more info.

**Comment by Superdrac** [comment] 2017-03-01 19:06
From what I can see, my action-xhr="mydomain" is replaced by action-xhr="#" on google cache ?!

**Comment by honeybadgerdontcare** [comment] 2017-03-01 19:09
That doesn't happen for me. If you could provide your source URL then that would help to look into it.

Original: http://astute-city-159523.appspot.com/files/amp-form.html
AMP Cache: https://cdn.ampproject.org/c/s/astute-city-159523.appspot.com/files/amp-form.html

Note the action-xhr is not changed.

**Comment by Superdrac** [comment] 2017-03-01 19:12
The cached one (it seem that google just deindexed it from amp pages):
https://lmk-li.cdn.ampproject.org/v/s/lmk.li/?amp_js_v=7
The original: 
https://lmk.li/

**Comment by weeblr** [comment] 2017-03-06 08:30
Hi

> From what I can see, my action-xhr="mydomain" is replaced by action-xhr="#" on google cache ?!

While setting up some fomrs my self, I saw that too. It's not the domain that is replaced by a hash character, but the current page (source origin) URL.

It seems to be a rather extreme optimization:

If your source origin is https://example.com/my-page/amp
and it's cached at https://example-com.cdn.ampproject.org/c/s/example.com/my-page/amp

then all instances of "https://example.com/my-page/amp" in href, src, etc are replaced with #, assuming the intent was to stay on the same page.

This is probably not a good idea, as it breaks any "refresh" mechanism (such as "Click here to refresh the page", which is often needed after a form has been filled).

I was not using any action-xhr pointing to the same page (with query vars appended), so I have not experienced this specific replacement, but I have seen it consistently and on multiple occasions on regular href link attributes

I would suggest this optimization is removed, it is unexpected and breaks things. 

Rgds

**Comment by honeybadgerdontcare** [comment] 2017-03-29 17:32
This is being tracked internally as b/36719384.

A temporary work around is to set the form[action-xhr] to a URL that is not the base URL of the page it is on. For your specific case adding another handler on your server for the action-xhr request and linking to that on the root page should avoid this issue.

**Comment by honeybadgerdontcare** [comment] 2017-04-04 18:09
@Superdrac The AMP Cache will no longer make form[action] or form[action-xhr] fragment URLs but always make them absolute to origin site. I've confirmed this is fixed with both a test site and with your site that you mentioned previously.

**Closed by honeybadgerdontcare** 2017-04-04 18:09 UTC
Labels: Category: AMP Caches, P2: Soon, Type: Bug

**Comment by weeblr** [comment] 2017-04-04 18:24
@honeybadgerdontcare action and action-xhr being broken is **not the only thing broken** by this optimization feature. As described in my previous message, you also broke any self-referencing link (required for refreshing the content of a page after posting a comment for instance).
How do you suggest a page reload be implemented if the cache breaks it?

**Comment by honeybadgerdontcare** [comment] 2017-04-04 18:25
@weeblr please create a new issue with that specific case as this issue was for amp-form.

**Comment by weeblr** [comment] 2017-04-05 07:54
@honeybadgerdontcare  I opened #8586
