### ISSUE TITLE
support to show only one item at a time in the carousal.

### ISSUE THREAD

**Issue by yask123** [ampproject/amphtml#4167] opened 2016-07-22 11:26 UTC
## How do we reproduce the issue?

To get this view I have defined width/height to the carousal element.  But this doesn't give users much touch area space to swipe and change the image.

Please post a public URL and ideally post a reduced test case. E.g. on jsbin.com that exhibits only your issue and nothing else.

Here is the demo url
[URL](https://peaceful-peak-42190.herokuapp.com/apple-iphone-6-silver-16-gb/p/itme8dvfeuxxbm4r?pid=MOBEYHZ2NUZGCHKN) 
## What browsers are affected?

All browsers
## Which AMP version is affected?

Is this a new issue? Or was it always broken? Paste your AMP version. You can find it in the browser dev tools.

AMP version: 1468883441627

**Comment by jridgewell** [comment] 2016-07-22 17:28
Have you tried the [`type="slides"`](https://ampbyexample.com/components/amp-carousel/#example8) yet?

**Comment by yask123** [comment] 2016-07-24 17:32
@jridgewell Yes, I have.. But that is not what we want.  We are trying to build AMP pages for Flipkart, thus it should mimic the appearance of the current Flipkart mobile website. Eg:  [iPhone product page url ](https://www.flipkart.com/apple-iphone-6-silver-16-gb/p/itme8dvfeuxxbm4r?pid=MOBEYHZ2NUZGCHKN&lid=LSTMOBEYHZ2NUZGCHKNUJYDRK) (Open in mobile)

**Comment by dvoytenko** [comment] 2016-07-24 17:56
@yask123 Could you please clarify? That page looks like a good fit for `type=slides` carousel: it shows one image at a time and swipes between them.

**Comment by yask123** [comment] 2016-07-24 18:20
@dvoytenko  Yes thats true. The only difference is that when you swipe image in carousal, the previous image moves sideways  and in slides the next image appears on top of the current image.
Although the difference is minor, it'd be great if we could provide the same experience in AMP page and in our mobile website page.

**Comment by yask123** [comment] 2016-07-25 07:09
Also,  in `type="slides"` , the images inside the` <amp-carousel >` takes the dimension of the amp-carousal.
We wanted carousal to have full width (irrespective of the width of the image), so that the user gets more touch space to swipe the image to view the next one.

**Comment by dvoytenko** [comment] 2016-07-25 17:50
@yask123 The top-level elements in the carousel do not have to be images themselves. You can certainly just stick in a DIV and then place an image inside and layout it as you need. Or, you can use `object-fit` CSS to customize the image sizing.

**Comment by shimonenator** [comment] 2016-07-26 04:09
@dvoytenko, this could be another example where a `<amp-scrollable>` paired with css snap points is a more flexible choice.

**Comment by adelinamart** [comment] 2017-02-07 18:44
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)

**Closed by adelinamart** 2017-02-07 18:44 UTC
Labels: To be deprecated - Type: Question
