### ISSUE TITLE
Expose CLS, FCP, FID, and LCP to <amp-analytics>

### ISSUE THREAD

**Issue by patrickkettner** [ampproject/amphtml#27304] opened 2020-03-19 05:30 UTC
## Describe the new feature or change to an existing feature you'd like to see
In order for folks to track their sites RUM performance, it would be great to expose the new user metric APIs, perhaps as a [URL substitution](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md)?

## Describe alternatives you've considered

These are already available in the [amp-performance-extension](https://github.com/ampproject/amphtml/blob/695fd66cfa0da187867890575db167266625235f/testing/amp-performance-extension/measure.js), which is great for local development but does not take real user data into account.

**Comment by sebastianbenz** [comment] 2020-04-16 08:17
//cc @kristoferbaxter @zhouyx

**Comment by zhouyx** [comment] 2020-04-16 20:27
Thank you for creating the issue and pinging us! Yes we definitely want to support this.

**Comment by zhouyx** [comment] 2020-04-16 22:09
#27770

**Comment by zhouyx** [comment] 2020-04-16 22:11
Duplicate of #27770, close this issue. Please track the work there.

**Closed by zhouyx** 2020-04-16 22:11 UTC
Labels: Type: Feature Request, WG: analytics
