### ISSUE TITLE
amp-analytics via gtag: click event doesn't fire

### ISSUE THREAD

**Issue by thedotedge** [ampproject/amphtml#26186] opened 2020-01-02 13:55 UTC
## What's the issue?

I am trying to report anchor click events to Google Analytics and configured `amp-analytics` as documented at https://developers.google.com/analytics/devguides/collection/amp-analytics#measure_events.

Here's the tracking configuration:
```
<amp-analytics type="gtag" data-credentials="include">
                <script type="application/json">
                    {
                        "vars": {
                            "gtag_id": "UA-108809790-1",
                            "config": {
                                "UA-108809790-1": {
                                    "groups": "default"
                                }
                            }
                        },
                        "triggers": {
                            "downloadIos": {
                                "on": "click",
                                "selector": "#download-ios",
                                "vars": {
                                    "event_name": "custom",
                                    "event_category": "AMP - Forsker: – Mild og våt vinter til slutten av mars",
                                    "event_action": "download_ios",
                                    "event_label": "${storyPageId}"
                                }
                            },
                            "downloadAndroid": {
                                "on": "click",
                                "selector": "#download-android",
                                "vars": {
                                    "event_name": "custom",
                                    "event_category": "AMP - Forsker: – Mild og våt vinter til slutten av mars",
                                    "event_action": "download_android",
                                    "event_label": "${storyPageId}"
                                }
                            },
                            "storyProgress": {
                                "on": "story-page-visible",
                                "vars": {
                                    "event_name": "custom",
                                    "event_action": "story_progress",
                                    "event_category": "AMP - Forsker: – Mild og våt vinter til slutten av mars",
                                    "event_label": "${storyPageId}",
                                    "send_to": ["UA-108809790-1"]
                                }
                            },
                            "storyEnd": {
                                "on": "story-last-page-visible",
                                "vars": {
                                    "event_name": "custom",
                                    "event_action": "story_complete",
                                    "event_category": "AMP - Forsker: – Mild og våt vinter til slutten av mars",
                                    "send_to": ["UA-108809790-1"]
                                }
                            },
                            "bookendView": {
                                "on": "story-bookend-enter",
                                "vars": {
                                    "event_name": "custom",
                                    "event_action": "bookend_view",
                                    "event_category": "AMP - Forsker: – Mild og våt vinter til slutten av mars",
                                    "send_to": ["UA-108809790-1"]
                                }
                            }
                        }
                    }
                </script>
                </amp-analytics>

```

The page contains anchor with id `download-ios` and passes AMP validation:
```
<a href="https://itunes.apple.com/app/apple-store/id1300541549?pt=563731&amp;mt=8&amp;ct=AMP%20story%20Op21d1%20download%20tab" id="download-ios" target="_blank"><amp-img src="/static/images/Download_on_the_App_Store_Badge_NO_RGB_blk_100317-v1.svg" width="210" height="70" alt="iOS"></a>
```

## How do we reproduce the issue?

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

1. Open Developer tools in Chrome
2. Click device toolbar and pick `iPhone X`
3. Navigate to https://peil.no/saker/Op21d1#development=1
4. Navigate to the last tab with download button:
![image](https://user-images.githubusercontent.com/227241/71670193-7ec9de00-2d6f-11ea-8a84-cc912a288e02.png)
5. Click `App Store` button

*Expected outcome:* network tab should contain a request to https://www.google-analytics.com/collect with `ea: download_ios`

*Actual outcome:* no request is being fired.

## What browsers are affected?

Reproducible on Chrome Version 79.0.3945.88 (Official Build) (64-bit) 

## Which AMP version is affected?

AMP ⚡ HTML – Version 1912201827130

**Comment by micajuine-ho** [comment] 2020-01-06 19:42
Hi @thedotedge. Thank you for your issue report.

After looking into it, it seems that you are trying to add a click event to an anchor element inside amp-story, and also attach analytics triggers to it.

The correct way to do this is to use [`<amp-story-cta-layer>`](https://amp.dev/documentation/components/amp-story-cta-layer/). An example can be seen [here](https://github.com/ampproject/amphtml/blob/master/examples/amp-story/analytics.html).

A caveat to mention is the following constraint: 
```
If specified, the <amp-story-cta-layer> element must be the last layer within an <amp-story-page>. As a result, effectively every <amp-story-page> can have exactly one or exactly zero of the <amp-story-cta-layer> element.
```
This means that you will not be able to have your `<amp-story-cta-layer>` nested within your `<amp-story-grid-layer>` like you currently have.

As this is not a bug, I am going to close this issue. Feel free to reopen if you have further questions.

**Closed by micajuine-ho** 2020-01-06 19:42 UTC
Labels: Type: Bug
