### ISSUE TITLE
Pinterest amp-social-share pop-ups board list twice on iOS app

### ISSUE THREAD

**Issue by darwing1210** [ampproject/amphtml#12283] opened 2017-12-04 21:08 UTC
## What's the issue?

Taping the Pinterest amp-social-share button pop ups the board list twice on iOS app. [Video example](https://drive.google.com/file/d/1KgiaWzhtAVmBahkmDECyKjW6rCOTNP4t/view?usp=sharing). 

## How do we reproduce the issue?

1. Login on the Pinterest app.
2. Open any page with the amp-social-share pinterest button (Ex. https://ampbyexample.com/components/amp-social-share/)
3. Tap on the share button.

## What browsers are affected?

Tested on Safari iOS 11.2.

## Which AMP version is affected?

Always been broken.

**Comment by nainar** [comment] 2018-07-09 20:34
This is an issue with LinkedIn too #15821

**Comment by nainar** [comment] 2018-07-16 17:24
Dupe of #15821

**Closed by nainar** 2018-07-16 17:24 UTC
Labels: Category: Presentation, P3: When Possible, Type: Bug
