### ISSUE TITLE
Analytics vendor to be added to AMP Project

### ISSUE THREAD

**Issue by SantoshDhanjal** [ampproject/amphtml#3494] opened 2016-06-08 09:45 UTC
Hi,

We currently use IBM Digital Analytics (DA) for our web reporting. DA have not yet integrated with amp project, I have contacted them. Please can I request to add this vendor to the list of analytics that the amp project supports. I have followed the guideline stated in : https://www.ampproject.org/docs/guides/analytics_amp.html  

Thanks
Santosh
Johnston Press Publishing

**Comment by rudygalfi** [comment] 2016-06-08 09:51
IBM would need to add a vendor configuration, so you've done the right thing by contacting them. Perhaps you could reference this issue in your communications with them.

**Comment by SantoshDhanjal** [comment] 2016-06-08 09:56
Hi - I just need to tell IBM to add a vendor configuration? Are there any links I should give them. I think they have been on contact with amp project.

**Comment by rudygalfi** [comment] 2016-06-08 10:02
Best thing would be if they could just reply here.

**Comment by rudygalfi** [comment] 2017-02-08 23:45
I think this is a duplicate of #5447.

**Closed by rudygalfi** 2017-02-08 23:45 UTC
Labels: Category: Analytics, To be deprecated - Type: Request, Type: Feature Request
