### ISSUE TITLE
<amp-consent> not working with dir="rtl"

### ISSUE THREAD

**Issue by MaximePlancke** [ampproject/amphtml#27391] opened 2020-03-24 19:39 UTC
## What's the issue?

`<amp-consent>` doesn't seem to display the content of the iframe when `dir="rtl"` is set on the `<html>` tag. 

## How do we reproduce the issue?

You can add `dir="rtl"` to the `html` tag in a website where `amp-consent` is set. 

Currently, there is a live example here: https://farsi.euronews.com/amp/2020/03/04/nasa-warns-asteroid-approaching-earth (We suggested our client to force `dir="ltr"` on `<amp-consent>` which fixes the issue so this example might be deprecated)

## What browsers are affected?

All browsers that support the `dir` attribute (tested on Chrome 80.0.3987.132 and Firefox 73.0.1)

## Which AMP version is affected?

Version 2003101714470

**Comment by micajuine-ho** [comment] 2020-03-31 22:27
Hi @MaximePlancke, thanks for the issue. The fix here is to add `dir="ltr"` to the amp-consent tag. The issue is that amp-consent and the iframe are not able to communicate properly when under `dir="rtl"`.

Closing this issue, but feel free to reopen if this does not solve it for you.

**Closed by micajuine-ho** 2020-03-31 22:27 UTC
Labels: Component: amp-consent, Type: Bug, WG: analytics
