### ISSUE TITLE
AMP-lightbox-gallery - unable to open the same image twice.

### ISSUE THREAD

**Issue by SimonHogstromRonbol** [ampproject/amphtml#17252] opened 2018-08-02 09:38 UTC
## What's the issue?

When I click to open an image in the amp-lightbox-gallery, everything works as intended, but when I then close the image gallery, and try to reopen the same image, I'm unable to.

Opening new images in the same gallery is not a problem, but if i try to reopen an image i had opened prior, it crashes, and wont let me open any more image in the gallery.

## How do we reproduce the issue?

I've setup this barebones amp-lightbox-gallery to reproduce the error: https://codepen.io/sunturion/pen/djeYEB

1. Click on any image in the gallery to view it in the lightbox
2. Click the X to close
3. Click the same image again, and it will no longer work

-alternatively-
1. Click on any image in the gallery to view it in the lightbox
2. Click the X to close
3. Click on a different image in the gallery to view
4. Click the X to close again
5. Clicking any of the two images opened prior will crash the gallery, opening a third image will procede as normal

## What browsers are affected?

I've run into this problem on both Chrome and Firefox
and on internet explorer it turns the whole screen back when it crashes.

## Which AMP version is affected?

ive tested this in amp version 1531800879103, and i have had a lightbox gallery running on a website for quite some time without me or my client noticing, so it might be a new issue.

**Comment by jpettitt** [comment] 2018-08-02 15:36
Duplicate of #17044 - the fix has been merged but is not yet in production.

**Closed** 2018-08-02 15:36 UTC
Labels: Closed: Duplicate
