### ISSUE TITLE
AMP broken in IE11

### ISSUE THREAD

**Issue by robinac30** [ampproject/amphtml#27775] opened 2020-04-15 06:24 UTC
## What's the issue?

AMP is no longer working in IE11 as of this morning

## How do we reproduce the issue?

View https://amp.dev/ in Internet Explorer v11

## What browsers are affected?

Internet Explorer v11 and below

## Which AMP version is affected?

New issue which was picked up by our visual regression testing.  

Seeing this in console:  

`Could not locate https://raw.githubusercontent.com/ampproject/amphtml/2004142326360/src/polyfills/src/polyfills/custom-elements.js specified in source map https://cdn.ampproject.org/v0.js.map.`

**Comment by 7110** [comment] 2020-04-15 08:15
amp-img can't work on IE by released 2004142326360

I'm rushing to deal with by the way to lock versions of AMP runtime and components
https://twitter.com/innovate_7110/status/1240144750432452609

**Comment by uskay** [comment] 2020-04-15 09:49
+ @choumx This seems urgent. Can we consider a rollback?

**Comment by jkurzend** [comment] 2020-04-15 12:57
seems amp4ads banner ads do not work anymore.  IE11:  up to ~5% marketshare. One could easily make the math. Could'nt you consider a rollback?

**Comment by sebastianbenz** [comment] 2020-04-15 13:08
@7110 it's better to fallback to the LTS version (which is supported by the AMP validator) https://github.com/ampproject/amphtml/blob/master/contributing/lts-release.md

**Comment by rcebulko** [comment] 2020-04-15 13:51
The console error may be unrelated to page breakages; that's a known issue with the source map generation, but it shouldn't impact the runtime files.

**Comment by caroqliu** [comment] 2020-04-15 14:17
These are the errors found when reproducing on amp.dev with IE 11.719:
![image](https://user-images.githubusercontent.com/10456171/79347913-41462680-7f02-11ea-89ed-7305a6d6a96c.png)

The page is missing all of its assets:
![image](https://user-images.githubusercontent.com/10456171/79347930-486d3480-7f02-11ea-8ae9-848830355d8c.png)

**Comment by nainar** [comment] 2020-04-15 16:38
This issue should be fixed in 2004142326360. This is the current stable. 

Please accept my apologies for the inconvenience this issue has caused you all. 

We will be keeping this issue open to track the cause since we have just done a revert for now.

**Comment by jridgewell** [comment] 2020-04-15 19:13
@nainar is correct that 2004030010070 fixes the issue. Unfortunately, LTS is `012004142326360` (the broken version).

**Comment by rcebulko** [comment] 2020-04-15 19:16
We can update LTS to 2004030010070 with minimal impact, usage is still fairly low

**Comment by danielrozenberg** [comment] 2020-04-15 19:16
@jridgewell LTS is at 2004030010070 as well right now - maybe you have the opt-in cookie set? :)

**Comment by jridgewell** [comment] 2020-04-15 19:16
Apologies, LTS is currently 2004030010070. I had an opt-in cookie overriding the LTS version.

**Closed** 2020-04-15 20:59 UTC
Labels: Type: Bug
