### ISSUE TITLE
Travis' JWT plugin deprecation

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#13149] opened 2018-01-30 19:44 UTC
Saw this in the Travis logs:

> JWT addon will be deprecated on April 17, 2018. Please read our announcement at https://blog.travis-ci.com/2018-01-23-jwt-addon-is-deprecated

**Comment by rsimha-amp** [comment] 2018-01-30 19:45
Duplicate of #13047

**Closed by rsimha-amp** 2018-01-30 19:45 UTC
Labels: P2: Soon
