### ISSUE TITLE
Prevent amp carousel [type=slides] from half sliding/swiping

### ISSUE THREAD

**Issue by rajesh1158** [ampproject/amphtml#13209] opened 2018-02-01 10:44 UTC
## What's the issue?
I am able to half scroll/swipe an amp carousel

## Briefly describe the bug/feature request.
In an amp image carousel with type=slides, on a mobile device, when I start the swipe/slide and then stop halfway, I see half of the previous slide and half of the next slide. We should not allow half swipe.

## How do we reproduce the issue?
Head over to https://ampbyexample.com/components/amp-carousel/, and in chrome dev tools, choose a mobile view, choose the environment as 'Mid-tier Mobile' and then scroll down to the 1st slider under the heading `Basic Usage`. Click on the 1st slider and drag it towards the left but stop halfway (or stop at 40% swipe).

## What browsers are affected?
Afaik, latest chrome on android v6 mobile and chrome dev tools in mobile view.

## Which AMP version is affected?
Latest, Version 1516850240342

**Comment by aghassemi** [comment] 2018-02-01 16:29
@rajesh1158 Thanks for reporting, we are working on a fix. Duplicate of https://github.com/ampproject/amphtml/issues/11537 
/cc @camelburrito

**Comment by aghassemi** [comment] 2018-02-01 16:30
closing as dup of https://github.com/ampproject/amphtml/issues/11537

**Closed by aghassemi** 2018-02-01 16:30 UTC
