### ISSUE TITLE
<amp-analytics type="googleanalytics" NOT working

### ISSUE THREAD

**Issue by rrjanbiah** [ampproject/amphtml#27801] opened 2020-04-16 14:38 UTC
## What's the issue?

Below variants of `<amp-analytics type="googleanalytics"` are NOT working (tracking):

1. 
```html
<amp-analytics type="googleanalytics" data-credentials="include">
<script type="application/json">
{
  "vars": {
    "account": "UA-XXX-X"
  },
  "trackPageview": {
    "on": "visible",
    "request": "pageview"
  },
  "tweetClick": {
    "on": "click",
    "selector": "a[href*=\"twitter.com/share\"], a[href*=\"twitter.com/intent\"]",
    "request": "social",
    "vars": {
      "socialNetwork": "twitter",
      "socialAction": "tweet",
      "socialTarget": "${ampdocUrl}"
    }
  },
  "fbShareClick": {
    "on": "click",
    "selector": "a[href*=\"facebook.com/sharer\"]",
    "request": "social",
    "vars": {
      "socialNetwork": "facebook",
      "socialAction": "share",
      "socialTarget": "${ampdocUrl}"
    }
  }
}
</script>
</amp-analytics>
```

2. 
```html
<amp-analytics type="googleanalytics" data-credentials="include">
<script type="application/json">
{
  "vars": {
    "account": "UA-XXX-X"
  }
}
</script>
</amp-analytics>
```

However, below `gtag` variant is working/tracking:

```html
<amp-analytics type="gtag" data-credentials="include">
  <script type="application/json">
    {
      "vars" : {
        "gtag_id": "UA-xxxx-x",
        "config" : {
          "UA-xxx-x": {
             "groups": "default",
             "linker": { "domains": ["example.com"] } 
          }
        }
      }
    }
    </script>
</amp-analytics>
```

## How do we reproduce the issue?

1. ROT13('uggcf://erfgln.pbz/obneq') - not works using `type="googleanalytics"`
2. ROT13('uggcf://erfgln.pbz/pber-wven-fynpx-nygreangvir') - works using `gtag`

## Context

Based on notes from @micajuine-ho in #26691, moved from `type="gtag"` to `type="googleanalytics"`. But, only today noticed that ``type="googleanalytics"`` is NOT working/tracking. 

Also, *somewhat* related #26808

**Comment by micajuine-ho** [comment] 2020-04-16 17:00
Hi @rrjanbiah Can you give a little more insight on why you believe that "googleanalytics" is not working, such as what you expect to happen?

**Comment by rrjanbiah** [comment] 2020-04-16 17:12
@micajuine-ho

1. I can't check realtime users in Google Analytics dashboard
2. I can't see any 'collect' calls in Chrome network console (Chrome/Ubuntu Version 81.0.4044.92 (Official Build) (64-bit))

For the URLs that 'work', above 2 are 'working'

Also, noted another weird thing. In fact, `type="googleanalytics"` is **working along with `<amp-story>`**. Looks like something is broken recently. But, not sure. I noticed today only.

## Reproduce ##

1. ROT13('uggcf://erfgln.pbz/obneq/hfrf/nzc-fgbevrf/uhzna-erfbheprf/')

**Comment by micajuine-ho** [comment] 2020-04-16 20:56
Hi @rrjanbiah , I can confirm that `googleanalytics` is working when I tested and and we are not seeing any spikes in errors related to analytics. This probably means that you might want to double check your configuration (`"vars": {"account": "UA-XXX-X"}`  => are you using the right account number?) or your googleanalytics account.


*Note: to test add this to your inline config and in your dev console you should see the *warning* that the request failed while attempting to be sent:
```
"transport": {
    "image": true
  }
```
Additionally, if you don't want to inline that, you can check your outgoing network requests to see it being sent :)

I am closing the issue now. Feel free to reopen if you find the above to be false.

**Closed by micajuine-ho** 2020-04-16 20:56 UTC
Labels: Component: amp-analytics, Type: Bug, WG: analytics

**Comment by rrjanbiah** [comment] 2020-04-17 08:23
@micajuine-ho 

I appreciate your patience.

Checked closely. And, still it is **NOT working**. Mostly likely something is broken recently. 

## Results of adding `transport` ##
```json
"transport": {
    "image": true
  }
```

**Case**: `<amp-analytics type="googleanalytics" data-credentials="include">`

**Error**: `[AmpAnalytics <unknown id>] Inline or remote config should not overwrite vendor transport settings`

**Outcome**: Came to know that we have to add `id`. So, modified it to:  `<amp-analytics type="googleanalytics" id="googleanalytics" data-credentials="include">`

Now, getting
**Error**: `[AmpAnalytics googleanalytics] Inline or remote config should not overwrite vendor transport settings`

**Note**: Above error message is coming **even** in 'working' pages

## Tested items ##

1. Are you using the right account? - Yes (You can check in below URLs)
2. AMP HTML validation? - Yes (All URLs below are validated)
3. Tested in https://playground.amp.dev/ ? - Yes. Tested with basic skeleton file presented in the editor (added `<amp-analytics>` alone to existing code) - NOT working
4. Checked in Google Analytics dashboard under realtime users? - Yes, NOT working
5. Checked under network requests (Dev console)? - Yes, NOT working

## URLs to Reproduce NOT working case ##

1. ROT13 'uggcf://erfgln.pbz/obneq' - used basic `googleanalytics` type code - NOT working - Check view source
2. ROT13 'uggcf://erfgln.pbz/obneq/srngherf' - slightly extended `googleanalytics` type code - NOT working - Check view source
3. ROT13 'uggcf://erfgln.pbz/obneq/hfrf/nzc-fgbevrf/uhzna-erfbheprf/' - extended `googleanalytics` type code along with `<amp-story>` - Working - Check view source

#### Note ####

1. URLs are ROT13'ed for kinda privacy. May decode them using https://rot13.com/ or so.
2. All above URLs are AMP validated
3. When given `transport` is added, now all pages are showing `[AmpAnalytics googleanalytics] Inline or remote config should not overwrite vendor transport settings` error. **But**, the last URL is 'working'

**Comment by rrjanbiah** [comment] 2020-04-17 17:32
@micajuine-ho Also, FWIW, reporters can't reopen tickets in GitHub

**Comment by micajuine-ho** [comment] 2020-04-17 18:50
@rrjanbiah Hi, thanks for detailing your testing experience. 

> Error: [AmpAnalytics <unknown id>] Inline or remote config should not overwrite vendor transport settings
Error: [AmpAnalytics googleanalytics] Inline or remote config should not overwrite vendor transport settings

FYI: Both of these errors are user errors, they're meant to be informative, but do not limit any actual capabilities of amp-analytics.

Anyways, the config I gave you above doesn't actually produce the network request log in the console (my fault). 
Try this config instead:
```

<amp-analytics type="googleanalytics">
  <script type="application/json">
    {
      "triggers": {
        "testVisible": {
          "on": "visible",
          "request": "host"
        }
      },
      "transport": {"beacon": false, "xhrpost": false, "image": true}
    }
  </script>
</amp-analytics>
```


As you can see, we are importing the googleanalytics config, and creating our own trigger called testVisible that fires on document visible and sends the googleanalytics predefined request `host` (log shown below). 

![image](https://user-images.githubusercontent.com/30711678/79603338-075f5680-80a1-11ea-9b05-2accc9c01f64.png)

The reason why we need to add our own trigger in is because googleanalytics does not work 'out of the box'. Looking at the [googleanalytics config](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/vendors/googleanalytics.json), all of their triggers either have `sampledOn` or `enabled` field defined, which would restrict requests from being sent, without proper configuration. 

This shows that the type=googleanalytics is working within amp-analytics, your inline configuration just has to be changed to fit your needs.

**Comment by rrjanbiah** [comment] 2020-04-17 20:09
@micajuine-ho Thank you so much for your patience. Unfortunately, I can modify that only on Monday and then will update you. Hopefully it will be alright. Thanks again!

**Comment by rrjanbiah** [comment] 2020-04-20 06:36
@micajuine-ho Thank you. It works with `triggers`. Thank you.
