### ISSUE TITLE
Ad when served using layout = responsive doesn't render properly

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#4923] opened 2016-09-12 01:04 UTC
Regular JS version : http://output.jsbin.com/yifodoj
![image](https://cloud.githubusercontent.com/assets/2366341/18422013/588d2f68-7863-11e6-9155-126d06dfa3bf.png)

AMP version : http://output.jsbin.com/mivofa
![image](https://cloud.githubusercontent.com/assets/2366341/18422016/5e0866d8-7863-11e6-8954-633d428959fa.png)

**Comment by zhouyx** [comment] 2016-09-28 00:07
I can't reproduce this bug. I tested several ad with responsive layout, the `amp-ad` element and the child iframe all seem to resize correctly. 
I do find that the first working version of the ad includes an ad script which the AMP version  doesn't. I assume the included ad script will resize the ad image. That's why the real ad image is not resized correctly in the AMP version.

**Comment by zhouyx** [comment] 2017-01-13 00:17
Close this. We can reopen it if it comes back.

**Closed by zhouyx** 2017-01-13 00:17 UTC
Labels: Related to: Ads
