### ISSUE TITLE
Urgent : AMP Unused JS issue

### ISSUE THREAD

**Issue by askmeoffers** [ampproject/amphtml#28621] opened 2020-05-29 08:21 UTC
Hi Team ,

Thanks in advance for building and working on such a great AMP framework and helping us with easy to use wordpress plugin .

Recently I noticed that all AMP java scripts are being flagged as unused for our oyo coupons stores and all other stores as well

https://askmeoffers.com/coupon-deal-offer-promo-store/oyorooms-com/

on google page speed tool
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Faskmeoffers.com%2Fcoupon-deal-offer-promo-store%2Foyorooms-com%2F

Any insight into this ?

Thanks
Team - [askmeoffers.com]

**Comment by wassgha** [comment] 2020-06-02 16:27
Closing as duplicate of #28638 . Let's continue the discussion there.

**Closed by wassgha** 2020-06-02 16:27 UTC
Labels: Type: Bug
