### ISSUE TITLE
Does amp-access authorization endpoint request sends the original reader's user-agent?

### ISSUE THREAD

**Issue by dryleaf** [ampproject/amphtml#20267] opened 2019-01-11 00:55 UTC
Not a well structured ask, but here's my concern in the form of a question.

I am trying to attempt a solution to display ads based on the device type, respectively:
- iOS
- Android

For example if the `amp-access` is as follows:
```
<script id="amp-access" type="application/json">
  {
    "authorization": "https://ampbyexample.com/samples_templates/comment_section/authorization?rid=READER_ID&url=CANONICAL_URL&ref=DOCUMENT_REFERRER&_=RANDOM",
    "noPingback": "true",
    "login": {
      "sign-in": "https://ampbyexample.com/samples_templates/comment_section/login?rid=READER_ID&url=CANONICAL_URL",
      "sign-out": "https://ampbyexample.com/samples_templates/comment_section/logout"
    },
    "authorizationFallbackResponse": {
      "error": true,
      "loggedIn": false
    }
  }
</script>
```
→ reference: https://www.ampproject.org/docs/interaction_dynamic/login_requiring/login

When I receive the `authorization` request on my server, can I be certain that the `user-agent` corresponds to that of the user (accessing the AMP page) and not from some google crawler/bot?

Thanks

**Comment by torch2424** [comment] 2019-01-11 02:36
Triaging to @dvoytenko , feel free to re-assign 😄

**Comment by jpettitt** [comment] 2019-01-11 20:53
Yes the request is directly from the user to the endpoint

**Comment by jpettitt** [comment] 2019-01-11 21:04
I think you can do what you want with CSS - see https://stackoverflow.com/questions/30102792/css-media-query-target-only-ios-devices

**Comment by dryleaf** [comment] 2019-01-11 22:13
@jpettitt
Am I wrong in assuming that the `Authorization` request parameter is the first to be called by amp-html so that the reader is rendered a view of what he is allowed to see according to his permission?
->reference: [Authorization Endpoint](https://www.google.com/amp/s/www.ampproject.org/docs/reference/components/amp-access)
> Doing it with amp-access is a bad idea as is will significantly slow down your ad load due to the extra round trip and as a result reduce CTR.

If I am can be certain that the actual reader's user-agent is sent along with the request to the `Authorization Endpoint` then I could simply add a `"isIOS": boolean` in the `Authorization` response.

**Comment by jpettitt** [comment] 2019-01-11 23:49
You could do that and it would work (you could also use `amp-list`).  However external endpoints are not called until the page is visible so as not to be a privacy leak.  That means your ads will not get rendered until `access_endpoint_latency + ad_latency` ms after the page is visible. That's going to add 500 ms to a second or more to your ad latency for mobile users (possibly way more since there will be a TLS handshake to your endpoint).  There will be a corresponding drop viewability which is not not good in terms of ad CTR.   

If you can articulate a good reason for doing platform specific things that will benefit other publishers I suggest you generate a feature request for us to add a class to the `<body>` eg `amp-platforms-ios`, `amp-platform-android` so you can do it with CSS as it will be much cleaner.

**Comment by jpettitt** [comment] 2019-01-11 23:50
cc @jasti for thoughts on platform specific ads.

**Comment by jasti** [comment] 2019-01-14 23:43
This type of targeting is normally available on the ad server (like Google Ad Manager: https://support.google.com/admanager/answer/2884033?hl=en) which might be a better fit but curious to hear about the usecase.

**Comment by dryleaf** [comment] 2019-01-15 10:07
@jpettitt
I can't get the css solution to work on ads. For other components it seems to work nicely.

@jasti
I wonder why `amp-sticky-ad` does not allow more than one child.

**Comment by zhouyx** [comment] 2019-01-15 17:42
@dryleaf `<amp-sticky-ad>` is designed as a special ad format. So at design time we decided it can only have one child `<amp-ad>`. Please let us know your use case and why you want to allow multiple children in `<amp-sticky-ad>` Thank you.

**Comment by dryleaf** [comment] 2019-01-15 20:43
@zhouyx My goal is to display different ads for `iOS` and `Android`, in this case for example, I would like to display platform specific (iOS & Android) `amp-ad` in `amp-sticky-ad`.

From my solutions for platform specific things (refer to the interactions above), they all work for other components but not for ads. 

How can I achieve this? (Without using the server side ads distribution)

**Comment by dryleaf** [comment] 2019-01-15 22:16
@zhouyx
What about using the `fallback` approach? `fallback` seems to work pretty nicely on `amp-img` for example. Why not allowing `fallback` in `<amp-ad>` too?
- reference: [Placeholders & fallbacks](https://www.ampproject.org/docs/design/responsive/placeholders)
>I see. Allowing two <amp-ad> in the <amp-sticky-ad> isn't the best approach to me. Because we can't guarantee that one of the ad will be hidden by css.

**Comment by jpettitt** [comment] 2019-02-11 15:24
Closing "works as intended"

**Closed by jpettitt** 2019-02-11 15:24 UTC
Labels: Category: Access, Category: Ads, Type: Discussion/Question
