### ISSUE TITLE
Forms with xhr action do not work in IE11 neither get or post

### ISSUE THREAD

**Issue by SashkaDev** [ampproject/amphtml#9078] opened 2017-05-01 22:33 UTC
https://raw.githubusercontent.com/ampproject/amphtml/1493417419433/node_modules/promise-pjs/promise.js element specified in the source map https://cdn.ampproject.org/v0.js could not be found

Try to suscribe in your own example in https://ampbyexample.com/components/amp-form/preview/
The form do nothing.

The same error throws with amp-carousel type slides if in IE11 have enabled the script debugger.

**Comment by aghassemi** [comment] 2017-05-02 04:42
@cvializ let's do a quick test and see how broken form is in IE11, I am worried this might be due to some deeper IE11 regression in the platform. 
/cc @ericlindley-g

**Comment by cvializ** [comment] 2017-05-02 18:12
IE11 is throwing when `amp-form` calls `event-helper.js#createCustomEvent`. IE11 [doesn't support](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent#Browser_compatibility) the `CustomEvent` constructor, and `#createCustomEvent` checks for the presence of `window.CustomEvent`, but IE defines this variable despite not supporting it 😦 

Looks like @camelburrito merged a fix for this in #9053 when resolving the same error in #8916 for the carousel. I'll close this issue.

**Closed by cvializ** 2017-05-02 18:12 UTC
Labels: Category: User Input, P1: High Priority, Type: Bug

**Comment by camelburrito** [comment] 2017-05-02 18:20
Yay!

**Comment by SashkaDev** [comment] 2017-05-02 21:07
Thank you!! But, what about de node_modules/promise-pjs/promise.js  not found??

**Comment by jridgewell** [comment] 2017-05-02 21:31
That's just the stack trace, but not where the error comes from.

**Comment by SashkaDev** [comment] 2017-05-02 21:35
OK, it is another bug?

**Comment by jridgewell** [comment] 2017-05-02 21:49
No
