### ISSUE TITLE
amp-sidebar doesnt work as expected on AMP CDN

### ISSUE THREAD

**Issue by renzit** [ampproject/amphtml#8399] opened 2017-03-25 08:22 UTC
## Description
amp-sidebar doesn't work as expected when content is served from the google cdn on a real mobile device.

## How do we reproduce the issue?
This test was using a Nexus 5 phone, also tested on Samsung phones.
Follow this steps to reproduce this:
1- On your mobile device search in google chrome for amp example and open the link with the thunder that indicates its hosted on AMP CDN.
 (Can find the bug on the cdn amp of another searchs like:
    "amp site:vix.com"
    "amp site:thenextweb.com"
    "amp site:irishtimes.com")

In any of this examples is implemented the amp-sidebar tag. But isnt working as expected, when user click on the <a> with the toggle class is like the transition is broken or maybe is made, but the touch of the device is a lot sensitive so it open and close in milisecond and the user isnt able to interact with the menu and causes a bad UX on a  commonly used component.  

The interesting is that the amp-sidebar works when using the device emulator on the dev tools of chrome desktop. Also works if u go directly to the server and no to the CDN of Google.

Here is a video of the bug.
https://drive.google.com/open?id=0B_Y1gCdy9bBldWxWSnVuaWgtUjFFODE1STZ4NXlTMHpGbXVR

## What browsers are affected?

Browser: Chrome Version 56.0.2924.87
On nexux 5 phone and other devices.

**Comment by NataliaLKB** [comment] 2017-03-27 10:15
We have seen this bug as well for all Guardian pages

**Comment by ericlindley-g** [comment] 2017-03-27 15:03
I can repro on Android (not on iOS) — /cc @aghassemi @muxin @camelburrito , do you have any ideas?

Slotting at P0 for now, but may change based on how widespread this is

**Comment by honeybadgerdontcare** [comment] 2017-03-27 17:01
When directly going to the AMP Cache, I couldn't reproduce this on a [test site](https://cdn.ampproject.org/c/astute-city-159523.appspot.com/files/amp-sidebar.html), but I do see it on [cdn.ampproject.org/c/s/ampbyexample.com](https://cdn.ampproject.org/c/s/ampbyexample.com/components/amp-sidebar/). On a sidebar click, it shows the following in console:

```
Action Error: target not found in [tap:drawermenu.toggle]
Dd @ error.js:128
f.assert @ log.js:301
sg @ action-impl.js:292
f.trigger @ action-impl.js:277
(anonymous) @ action-impl.js:152

Uncaught Error: Action Error: target not found in [tap:drawermenu.toggle]​​​ _reported_
    at na.f.assert (log.js:295)
    at sg (action-impl.js:292)
    at ig.f.trigger (action-impl.js:277)
    at HTMLDocument.<anonymous> (action-impl.js:152)
```

I'm also seeing a different UI for ampbyexample when going directly to the cdn instead of search, not sure if that's a different issue or related.

**Comment by camelburrito** [comment] 2017-03-27 17:07
We have not touched sidebar in a while . Could this be the scroll fix that @muxin did ? Or did actions code have any changes recently ?

**Comment by amphtml-team** [comment] 2017-03-27 17:13
I can repro 8/10 on iOS Chrome but only 1/10 on iOS Safari.

**Comment by aghassemi** [comment] 2017-03-27 17:28
Likely related to use of History API. A few other Sidebar bugs seem to be also related to using history for close/open push: #6512 , #7044. @ericlindley-g and I chatted about this a bit, given that pushing to history is not a common UX pattern for sidebar open/close ( e.g PWA App Shells don't do it) and is causing multiple issues, we may just get rid of it.

**Comment by aghassemi** [comment] 2017-03-27 20:31
@ericlindley-g : Update: It is a viewer regression, @muxin and the viewer team are looking into it.

**Comment by muxin** [comment] 2017-03-27 21:43
b/36654490 is the tracking bug in viewer, both sidebar and lightbox is experiencing the same issue due to history bug.

**Comment by cramforce** [comment] 2017-03-28 03:05
Fix on Google's side is in progress.

**Comment by aghassemi** [comment] 2017-03-28 05:32
The fix is in production and the issue has been resolved. Sorry for the inconvenience.

**Closed by aghassemi** 2017-03-28 05:32 UTC
Labels: Category: Presentation, P0: Drop Everything, Type: Bug

**Comment by NataliaLKB** [comment] 2017-03-28 09:06
Thank you all for finding and fixing this bug!

**Comment by renzit** [comment] 2017-03-29 03:19
Same as NataliaLKB , thank you for the quick fix 👍

I check and everithing is ok , even the bug of the scroll on the sidebar is fixed, all of you rock 🎸
