### ISSUE TITLE
3P iframe ads failed to show on Safari

### ISSUE THREAD

**Issue by anshuman91** [ampproject/amphtml#22042] opened 2019-04-29 07:34 UTC
## What's the issue?

AMP Iframe not loading in salari browsers. 
`Blocked a frame with origin "https://d-27836143831042096785.ampproject.net" from accessing a frame with origin "https://www.aratips.com". Protocols, domains, and ports must match.`
<img width="747" alt="Screenshot 2019-04-29 at 12 56 13 PM" src="https://user-images.githubusercontent.com/3455354/56881524-4b1b1380-6a7e-11e9-9e97-2b3a0fea0d02.png">

## How do we reproduce the issue?
[https://www.aratips.com/amp/technology/11844/أبل-كوالكوم-سامسونج-5g](url)
On checking this url in any salari browser (desktop or mobile) it will throw the blocked iframe error in console without inserting the iframe. 

<img width="450" alt="Screenshot 2019-04-29 at 12 59 54 PM" src="https://user-images.githubusercontent.com/3455354/56881650-b9f86c80-6a7e-11e9-9a1c-43e106e92af4.png">

## What browsers are affected?

Safari - Desktop and Mobile

**Comment by torch2424** [comment] 2019-05-01 02:07
cc @ampproject/wg-ads

**Comment by anshuman91** [comment] 2019-05-02 14:16
I also found the same issue in another site https://www.snawebdevtest.com/amp/sport/1247915-بصورة-واحدة-تشلسي-يوجه-صفعة-لريال-مدريد

**Comment by anshuman91** [comment] 2019-05-02 14:23
Hello @dvoytenko , @zhouyx  , @jridgewell , @jasti  @lannka 

Please check the issue. Ads are working in chrome and firefox but it not loading in Safari. 
Iframe also not appending inside `<amp-embed>`. 

<img width="1002" alt="Screenshot 2019-05-02 at 7 51 47 PM" src="https://user-images.githubusercontent.com/3455354/57082191-db25bb00-6d13-11e9-9950-aa516f09c742.png">

**Comment by torch2424** [comment] 2019-05-03 02:00
I think @calebcordry investigated this, and reasoned that it was not on AMP's side. But possibly on the vendor or something that is blocking your iframes.

Don't let me say too much, as I don't quite remember what they said, so I'll let them reply once they get the chance 😄

**Comment by calebcordry** [comment] 2019-05-03 18:21
@anshuman91 I am not sure that the error messages are related to the ads being broken. The errors are coming from moatad.js which is supplied by [moat](https://moat.com/). I still see the errors when all ads are filled:
![image](https://user-images.githubusercontent.com/16087874/57157383-6d21d800-6d95-11e9-9941-dc8eedb1f81e.png)

However, I do see a lot of broken ads when visiting the page in safari, but I am unclear the root cause. @lannka do you know what is happening here?

**Comment by lannka** [comment] 2019-05-03 21:13
Agree, the error msgs are unrelated. it's just evidences of how various js tried to jail break a cross origin frame.

It's very easy to reproduce a blank ads on Safari. A typical response of the ad request https://googleads.g.doubleclick.net/pagead/ads is like:
```
<!DOCTYPE html><html><head><script>(function(){function a(d,f){try{d.top&&d.top.postMessage&&d.top.postMessage(f,"*")}catch(g){}}var b=["fillNotifier"],c=this||self;b[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+b[0]);for(var e;b.length&&(e=b.shift());)b.length||void 0===a?c[e]&&c[e]!==Object.prototype[e]?c=c[e]:c=c[e]={}:c[e]=a;}).call(this);fillNotifier(window, '{"msg_type":"resize-me","key_value":[{"key":"r_nh","value":"0"},{"key":"qid","value":"CI7D4uWhgOICFfcDrQYd6XcFhQ"}],"googMsgType":"sth"}');</script></head></html>
```

@keithwrightbos @jeffkaufman any insights? is it a response for no-fill?

**Comment by anshuman91** [comment] 2019-05-07 10:43
Hello @lannka @calebcordry @keithwrightbos @jeffkaufman 

After investigating on Safari browser I found `removeElement()` function running two times in safari and when it trigger second time, it removes the iFrame from `<amp-embed>`. 

![Screenshot 2019-05-07 at 3 48 52 PM](https://user-images.githubusercontent.com/3455354/57293320-04629480-70e2-11e9-92f8-5fefc472624c.png)

![Screenshot 2019-05-07 at 3 48 44 PM](https://user-images.githubusercontent.com/3455354/57293321-04fb2b00-70e2-11e9-876a-038f18a63c31.png)


Also, I checked the same in Chrome so I found `removeElement()` function which is coming from dom.js and running one time only. 


`removeElement()` function runs after this `this.element_.appendChild(this.iframe);` and in safari it also removed the iframe. 

![Screenshot 2019-05-07 at 3 51 19 PM](https://user-images.githubusercontent.com/3455354/57293593-c9149580-70e2-11e9-8aaf-beebe7abcc52.png)
![Screenshot 2019-05-07 at 3 51 12 PM](https://user-images.githubusercontent.com/3455354/57293594-c9ad2c00-70e2-11e9-9647-ff58d2992f05.png)

I also checked all ads are loading but in last call of amp iframe get removed from the html (dom). 

Please check the issue. This is urgent for us. 

Live URL - https://www.aratips.com/amp/technology/11844/%D8%A3%D8%A8%D9%84-%D9%83%D9%88%D8%A7%D9%84%D9%83%D9%88%D9%85-%D8%B3%D8%A7%D9%85%D8%B3%D9%88%D9%86%D8%AC-5g

**Comment by anshuman91** [comment] 2019-05-15 12:37
Hello @lannka @calebcordry @keithwrightbos @jeffkaufman,

any update here ?

**Comment by lannka** [comment] 2019-05-15 17:38
@anshuman91 thanks for debugging into this.
I was able to track down the issue and found out that the iframe removal was caused by an unlayout of `amp-embed`, because it has zero height.

The zero height was cause by a `resize` request sent from inside the iframe by some jubna script. In Chrome, the `resize` request has `width=407;height=500`, but for Safari 12.1 the numbers are `width=407;height=0`.  I also tested this under Safari Technology Preview (12.2), the issue seems to be fixed.

I'm not sure what logic did Jubna use to calculate the height, but apparently it might hit some issue on Safari 12.1. It will need to be fixed in Jubna (or waiting for 12.2 to be out).

I suggest you contact Jubna developer team for a fix. Let me know if you have any other findings.

**Comment by lannka** [comment] 2019-05-15 17:40
@keithwrightbos @jeffkaufman  sorry for the noise. I originally thought it was AdSense (many amp-ad type=AdSense on the page) . No further steps needed from your side.

**Comment by anshuman91** [comment] 2019-05-15 19:17
Hello @lannka,
Thank you for your response.

I am using `window.context.requestResize(document.documentElement.clientWidth,document.documentElement.scrollHeight)` to set the container height and width according to size of iframe document. 

And this method is working for all browsers except safari. And it was also working on safari a few days but don't know why it stopped working now. 

Please let me know what action need from my side?

**Comment by lannka** [comment] 2019-05-16 16:07
@anshuman91 oh, are you from jubna?

Are you able to verify if you can get non-zero `document.documentElement.scrollHeight` in the iframe? AMP has [some special logic](https://github.com/ampproject/amphtml/blob/master/src/service/viewport/viewport-binding-ios-embed-sd.js#L111) to handle the scrollHeight in Safari iframe, you might want to do the same. @dvoytenko is the expert on this. Hi Dima, do you have simpler solution for them?

**Comment by lannka** [comment] 2019-05-16 16:10
@anshuman91 while debugging, I also noticed that the requestResize was continuously being called. You should only call the API again when the previous call is rejected.

**Comment by lannka** [comment] 2019-05-16 17:46
@anshuman91 talked with @dvoytenko offline, as an immediate fix, you should read `scrollHeight` from the container div instead of from the document directly.

```
document.selectElementById('c').scrollHeight
```

meantime, to make future work easier, we are thinking of making it as the default behavior when you call the resize API.

**Comment by calebcordry** [comment] 2019-07-02 18:02
> making it as the default behavior when you call the resize API.

@lannka shall we close this issue, or are you using it to track the default behavior change.

**Comment by lannka** [comment] 2019-07-02 21:18
created a separate tracker #23159

**Closed by lannka** 2019-07-02 21:18 UTC
Labels: Category: Ads, Component: amp-ad 3p, P2: Soon, Type: Bug
