### ISSUE TITLE
amp-analytics Content-Type header not set to URL encoded or JSON, set to text/plain;charset=UTF-8

### ISSUE THREAD

**Issue by welkie** [ampproject/amphtml#22167] opened 2019-05-07 02:23 UTC
## What's the issue?

Using amp-analytics with the following config:

```html
<amp-analytics>
  <script type="application/json">
  {
    "requests": {
      "pageview": "http://localhost:3001/analytics"
    },
    "vars": {
      "test": "testValue"
    },
    "triggers": {
      "trackPageview": {
        "on": "visible",
        "request": "pageview"
      }
    },
    "transport": {
      "xhrpost": true,
      "useBody": true
    },
    "extraUrlParams": {
      "test": "${test}"
    }
  }
  </script>
</amp-analytics>
```

I was trying to use Express.js to parse the body, but it always comes in as an empty object.

When inspecting in Chrome dev tools on the AMP page, I saw that the data is in the body, but its `Content-Type` isn't being set to anything that web frameworks can use to parse the body:

![image](https://user-images.githubusercontent.com/7719209/57267028-899b6a00-704c-11e9-9050-6895524f15ca.png)

When I used the officially-recommended `body-parser` NPM package, whether I used `bodyParser.json()` or `bodyParser.urlencoded({ extended: false })`, it was never able to parse the body. I'm afraid to manually do my own body parsing and ignore the `Content-Type` header because as I understand, AMP moves fast, and I don't want to start parsing `amp-analytics` requests in a way that could work differently at any moment.

## How do we reproduce the issue?

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

1. Clone https://github.com/groupby/amp-test.
2. Switch to branch `bug-report-amp-analytics-request`.
3. Run the `store` app and `beacon-consumer` app with `PORT` env vars set to different values.
4. Visit `http://localhost:{store_port}/search?searchterm=test` in your browser, and observe the analytics request sent in the Network tab of the browser dev tools. Note the Content-Type being set to text/plain with some other characters.

## What browsers are affected?

Chrome Version 74.0.3729.131 (Official Build) (64-bit)

## Which AMP version is affected?

1905021827420

Is this a new issue? Or was it always broken?

Unsure.

Paste the version of AMP where you saw this issue. (You can find the version printed in your browser's console.)

1905021827420 (first time trying amp, first time trying amp-analytics, noticed this issue when attempting to parse request on my server)

**Comment by welkie** [comment] 2019-05-15 17:05
Coincidentally, I was learning more about CORS recently and discovered that a POST request from a browser that is of the three whitelisted `Content-Type` values (`application/x-www-form-urlencoded`, `multipart/form-data`, and `text/plain`) without any custom headers does *not* require a CORS preflight request.

Was this a design decision so that beaconing using `<amp-analytics>` would never have to worry about CORS?

**Comment by zhouyx** [comment] 2019-05-17 20:21
Hello @welkie 
Thank you for reporting. You're right, the request header `Content-Type` is set to `text/plain` to avoid the pre-flight HEAD request. 

To solve the parsing issue. I just ran a simple test locally using express and bodyParser, and I am able to parse the incoming request correctly. Here's my code snippet. 

```
app.post('/test/analytics', bodyParser.text(), (req, res) => {
  console.log(JSON.parse(req.body));
});
```

I'm going to close this issue. Please let us know if it still doesn't work for you so that we can reopen. Thank you.

**Closed by zhouyx** 2019-05-17 20:21 UTC
Labels: Category: Analytics, Type: Bug

**Comment by arush123** [comment] 2021-06-07 18:01
Hi @zhouyx,

FYI, we can obviously parse the **text/plain** data to **application/json**, but its an additional process of maintaining multiple API's handling different content type data, as most of the frameworks accept  request content type **application/json** then using 
**"transport": {
        "xhrpost": true,
        "useBody": true
    }**
must set the Request Header **content-type: application/json** instead of **content-type: text/plain**, is this not a bug?

**Comment by mattwelke** [comment] 2021-06-07 19:26
@arush123 

As they stated above, it's not a bug. It's intentional because it gets around some CORS requirements. It avoids the need for pre-flight OPTIONS requests.

**Comment by mattwelke** [comment] 2021-06-07 19:28
In my original report of this, I mentioned that I did have some concern about it:

> I don't want to start parsing amp-analytics requests in a way that could work differently at any moment.

My concern was that AMP wouldn't carefully remember that it would be a breaking API change to change this behavior. It seems for the past few years, they never changed it. It seems stable and well-understood. I wouldn't worry about it.
