### ISSUE TITLE
Allow link rel="mask-icon" in validator

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#2047] opened 2016-02-16 19:08 UTC
mask-icon is used by apple for pinned tabs, it should probably be allowed by the validator.

https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/pinnedTabs/pinnedTabs.html

**Comment by steffenweber** [comment] 2016-02-17 09:53
:+1: 

Would allow me to remove one AMP-specific condition in our header template.

Example markup:
```
<link rel="mask-icon" href="/img/mask-icon.svg" color="#000">
```

**Comment by Gregable** [comment] 2016-02-17 21:39
This is a `<link rel` only attribute right? In other words, it doesn't apply to `<a rel` in any way?

**Comment by steffenweber** [comment] 2016-02-17 22:01
Yes, it is a proprietary attribute value that is only used by Safari (afaik Desktop-only, so the use-case for AMP may currently be non-existent).

Something that just occurred to me: maybe this markup initiates an immediate download in Safari. This would be something that AMP tries to avoid, correct?

**Comment by Gregable** [comment] 2016-02-17 22:39
It would be something we'd want to avoid. Do you have an easy way to test this? I don't have an apple machine handy. If not, I'm happy to add it as it won't hurt anything and may make it easier for some folks to convert documents.

**Comment by cramforce** [comment] 2016-02-17 23:21
The immediate download is fine. But this needs to go onto the AMP-cache-rewrite list.

**Comment by steffenweber** [comment] 2016-02-18 07:43
I've run a test with Safari 9 on OS X El Capitan using BrowserStack: the "mask-icon" is not requested on page-load. It is only fetched when I pin the tab. So it should be safe to whitelist the proposed markup.

**Comment by Gregable** [comment] 2016-02-18 17:57
@cramforce . I have a change for validating this ready to go out, should I hold off until we have rewriting sorted? I'm not sure I understand the requirement.

**Comment by cramforce** [comment] 2016-02-18 18:05
Ship it. Hoping to get rewriting soon enough.

**Comment by Gregable** [comment] 2016-02-20 01:40
This is fixed. Should be rolled out to javascript in an hour or so.

**Comment by steffenweber** [comment] 2016-02-20 07:37
Thanks!

Can we use this feature immediately or should we wait a few days because the AMP validator used by Googlebot lags a little?

**Comment by Gregable** [comment] 2016-02-22 21:19
Good question. The `#development=1` flag should already be happy with it, and your doc will appear on cdn.ampproject.org, however it will probably be another week or two before those docs will be able to appear in google search results. I'll update this issue when that's working.

**Comment by steffenweber** [comment] 2016-02-23 08:17
That's what I suspected. It would be unfortunate to prevent all our pages from appearing in the AMP search results just because of using new AMP markup early. :wink:

This issue (not knowing what AMP markup is accepted by Googlebot / Search Console) is further complicated by the huge lag of the AMP data in the Search Console. The Search Console page "Accelerated Mobile Pages" still says "Status: 2/16/16" for us (i.e. the data is now 7 days old).

**Comment by Gregable** [comment] 2016-02-23 22:01
FYI, as of a couple hours ago, this is live everywhere. Given the impending launch, we are trying to make sure that the version live that googlebot sees is as close as possible to what you are seeing in the javascript console and here in github.

Unfortunately, this still requires waiting until a given document is re-crawled if we have already crawled something with the rel=mask-icon previously.

**Comment by steffenweber** [comment] 2016-02-24 11:08
Thank you! :smiley:

**Comment by steffenweber** [comment] 2016-02-24 14:34
The `development=1` validator still does not like the markup (and gives a strange error message):
> The attribute 'rel' in tag 'link rel=canonical' is set to the invalid value 'mask-icon'.

When I change the value to `mask-icon2` (just for testing purposes) it says:
> The attribute 'rel' in tag 'link rel=' is set to the invalid value 'mask-icon2'.

How to reproduce: add the mentioned markup to `article-json-ld.amp.html`.

**Comment by Gregable** [comment] 2016-02-24 18:07
@steffenweber . Thanks for the report. I added `rel=mask-icon`, but it looks like I missed the color attribute. I will revisit this.

**Comment by Gregable** [comment] 2016-03-02 21:58
Unless you find a new issue, this has been fixed in github and in the cache. I won't be releasing the fix to the javascript validator (#development=1) immediately, but that'll come very soon. In the meantime, just ignore these errors.

**Comment by Gregable** [comment] 2016-03-11 17:54
This is live everywhere. Let me know if you find any further examples of validation issues.

**Closed by Gregable** 2016-03-11 17:54 UTC
Labels: Related to: Validator

**Comment by a701440** [comment] 2017-01-23 22:11
Still get errors: Attribute color not allowed on element link at this point.
<link rel="mask-icon" href="/pinned.svg" color="#FF690F" />

https://yoast.com/dev-blog/safari-pinned-tab-icon-mask-icon/

**Comment by Gregable** [comment] 2017-01-23 22:34
It works for me. Do you have an example document that is failing validation?
