### ISSUE TITLE
userErrors not working for specific end point

### ISSUE THREAD

**Issue by juanchaur1** [ampproject/amphtml#13524] opened 2018-02-16 16:52 UTC
## What's the issue?
When configuring the error trigger as specified [here](https://www.ampproject.org/es/docs/reference/components/amp-analytics#error-trigger) and adding a specific url as [here](https://github.com/ampproject/amphtml/blob/master/examples/analytics-error-reporting.amp.html#L90) the request that fires is to: amp-error-reporting.appspot.com/r

## How do we reproduce the issue?
You can reproduce it with this same file.
https://github.com/ampproject/amphtml/blob/master/examples/analytics-error-reporting.amp.html

## What browsers are affected?
ALL

## Which AMP version is affected?
Last version

**Comment by choumx** [comment] 2018-02-22 17:19
FYI `amp-error-reporting.appspot.com/r` is our error endpoint, so any requests sent there are working as intended.

/cc @lannka

**Comment by juanchaur1** [comment] 2018-02-22 17:23
Correct, but shouldn't it go to the specific url if specified?
Let's say we have
```json
{
            "requests": {
                "error": "https://someUrl?en=${errorName}&em=${errorMessage}"
            },
            "triggers": {
                "userError": {
                    "on": "user-error",
                    "request": "error"
                }
            }
        }
```

**Comment by lannka** [comment] 2018-08-03 17:06
Hi folks, thanks for reporting. The feature is currently behind an experiment flag. 

Please go [here](https://cdn.ampproject.org/experiments.html) and turn on `user-error-reporting` and test it out. Pls report bug if you folks see any.

There is a known issue that all errors on AMP ads on the page will also be reported #10891 .
We were a bit reluctant about making it fully available before resolving it.

If you guys don't care about the bug and want to use the feature, we can have your sites opt-in.

The documentation is misleading, I will fix that.

**Comment by lannka** [comment] 2018-08-03 20:58
Discussed with @choumx offline, we think we might just roll this feature out given it's a pretty safe feature. Given the nature of the feature (error reporting), it's hard to find issues without having people use it. We can fix any issues on an on-going basis.

**Comment by andreyMakahov** [comment] 2018-08-06 02:05
Thank you, I will test the feature on my local computer first.
But it is really great idea to roll the feature out. Looking forward.

**Comment by andreyMakahov** [comment] 2018-08-06 03:52
Tried the feature on my local machine.

I am using the this [example page](https://github.com/ampproject/amphtml/blob/bde01e900a6fdc31c5a477d4ddedaee1cd0baa3b/examples/analytics-error-reporting.amp.html).

What I did:
1. Enabled development mode(added `#development=1` to page url).
2. Enabled test feature in browser console `AMP.toggleExperiment('experiment')`.

I got a lot of errors in browser console, but I didn't get any XHR request with error to the monitoring url.

Could you please help me to understand what I am doing wrong? Thank you in advance!

**Comment by lannka** [comment] 2018-08-06 14:15
@andreyMakahov `development=1` is not needed. Also, you will call `AMP.toggleExperiment('user-error-reporting')`.

Instead, as mentioned above, you could go [here](https://cdn.ampproject.org/experiments.html) and turn on user-error-reporting.

**Comment by andreyMakahov** [comment] 2018-08-07 04:42
@lannka Thank you, it works. Looking forward when you roll the feature out so I will be able to use it online.

**Closed** 2018-08-08 17:39 UTC
Labels: Category: Analytics, P2: Soon, Type: Bug
