### ISSUE TITLE
Support Google AdSense for Search

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#2659] opened 2016-03-21 21:20 UTC
Google AdSense for Search doesn't appear to be supported. This is an issue to request support

@kadmos1 originally reported this in #1286:

> I need to use on an AMP page Google Adsense For Search (AFS) ad units. Is that possible?
> I've read AMP documentation and AFS ads aren't available there. I did some research but haven't found any info on this. I've also posted a question in stackoverflow but haven't received any helpful answer. http://stackoverflow.com/questions/35981279/can-i-use-google-adsense-for-search-afs-ad-units-with-amp/36024593#36024593
> 
> Can anyone help me with this?

@kashyapnitin, can you comment here?

**Comment by rudygalfi** [comment] 2016-03-21 21:27
cc @dvoytenko FYI

**Comment by kadmos1** [comment] 2016-03-22 06:24
Thanks @rudygalfi looking forward to see AFS support on AMP

**Comment by cramforce** [comment] 2016-03-22 16:53
This product? https://support.google.com/adsense/answer/9879?hl=en

How would that apply to AMP?

**Comment by megankj** [comment] 2016-08-23 21:09
I've started working on this.  It will support both AFS (AdSense for Search) and AFSh (AdSense for Shopping) on the CSA (Custom Search Ads) protocol.

**Comment by jasti** [comment] 2016-08-23 21:13
Thanks @megankj ! Assigning to you.

**Comment by j1wilmot** [comment] 2016-11-03 16:47
Any update on when this will be available? Thanks!

**Comment by megankj** [comment] 2016-11-03 20:24
We are targeting 11/18.

**Comment by j1wilmot** [comment] 2016-12-02 15:56
Sorry to be a pest, but any update on when this will be available? I was hoping to make use of this feature before the end of the year -- I've had some issues using an iframe as a workaround. Many thanks!

**Comment by megankj** [comment] 2016-12-02 17:26
Yes, I'm really hoping to get it out by next Friday.  Sorry for all the delays!

**Comment by j1wilmot** [comment] 2017-01-03 17:45
@lannka I'm trying to get a sense of when this feature will be available in production. I see this got merged into master on the 21st, but it looks like it didn't make it into a release. Based on the release guidelines I think this will be available in a dev-channel release this Thursday and then hopefully deployed fully on January 12th, but I wanted to make sure this timeline is accurate. Thanks for the hard work -- looking forward to use this feature!

**Comment by megankj** [comment] 2017-01-06 19:46
Just confirmed that it should available in the dev-channel at the end of today (most likely) and fully deployed next Thursday, January 12.

**Comment by jasti** [comment] 2017-02-02 00:01
Awesome! Closing.

**Closed by jasti** 2017-02-02 00:01 UTC
Labels: 3P, Category: Ads, Type: Feature Request, Type: Request
