### ISSUE TITLE
amp-date-picker readonly input field's custom validation fails  

### ISSUE THREAD

**Issue by ro2ni3** [ampproject/amphtml#17687] opened 2018-08-23 16:04 UTC
## What's the issue?

amp-date-picker fails to display a custom validation message when the user clicks on submit before selecting a date (leaving the amp-date-picker blank) if the amp-date-picker is set to readonly.

The reason why I need a readonly amp-date-picker is so that the user is not able to change the date by typing a new one with the keyboard, but he/she is forced to use the date picker overlay.

## How do we reproduce the issue?

Please refer to this [CodePen](https://codepen.io/ro2nie/pen/WgQvMN) where you can see this happening. Just load it and hit the Search button without selecting a date. 
There are two problems that occur, the date picker overlay will open and the validation message will not appear.
If we remove the 'readonly' attribute from the amp-date-picker, then the validation message will show properly when clicking on Search when the date is left blank.

## What browsers are affected?

All browsers

## Which AMP version is affected?

Version: 1534444305877

**Comment by aghassemi** [comment] 2018-09-05 14:51
Closing this as intended per above.

**Closed** 2018-09-12 22:57 UTC
Labels: Category: User Input, Closed: Intended, Type: Bug
