### ISSUE TITLE
AMP cache is changing the sprite image dimensions

### ISSUE THREAD

**Issue by faelgabriel** [ampproject/amphtml#7158] opened 2017-01-23 18:50 UTC
AMP cache is changing the sprite image dimensions.
I searched and did not find any related problems, also I did not find any documentation related.

Original image: https://www.reservationcounter.com/application/themes/twig_theme/default/images/global.png

AMP cache image: https://cdn.ampproject.org/i/s/www.reservationcounter.com/application/themes/twig_theme/default/images/global.png

That image is only used as css "background-image" and not in amp-img.

I am aware that our sprite is large and we are working on it, but at the moment I needed to use that image.
Is there any size limit or dimension limit that is causing the cache to change it?

Thanks, Rafael.

**Comment by jridgewell** [comment] 2017-01-23 22:59
Internally tracking at b/34625483.

**Comment by adelinamart** [comment] 2017-02-09 00:45
Closing this one and following up internally.

**Closed by adelinamart** 2017-02-09 00:45 UTC
Labels: Category: AMP Caches, Internally Tracked, P2: Soon, Type: Bug

**Comment by Download** [comment] 2017-04-23 20:24
> Original image
That sprite! Transparent pixels are actually pretty 'expensive' in PNG...

**Comment by adelinamart** [comment] 2017-04-24 16:44
Thank you for the comment. The issue is still being tracked internally.
