### ISSUE TITLE
amp-accordion doesn't work

### ISSUE THREAD

**Issue by sascha-hendel** [ampproject/amphtml#2573] opened 2016-03-12 12:46 UTC
Live example: http://eng.archinform.net/projekte/10.amp.htm
Following error in console:
> http://eng.archinform.net/projekte/10.amp.htm:7:0 The attribute 'custom-element' in tag 'amp-access extension .js script' is set to the invalid value 'amp-accordion'. (see https://www.ampproject.org/docs/reference/extended/amp-access.html)

Strange, that the error message is related to amp-access, which isn't used on the page at all...

Other extended component  (amp-carousel) is working.

**Comment by erwinmombay** [comment] 2016-03-12 19:54
not sure if the validator has caught up for amp-accordion

/cc @Gregable @powdercloud @sriramkrish85

**Comment by sascha-hendel** [comment] 2016-03-14 09:08
Noticed right now, that accordion is listed under 
https://cdn.ampproject.org/experiments.html
as experimental, but in the docs at 
https://www.ampproject.org/docs/reference/extended/amp-accordion.html
it is listed as stable ???

**Comment by sascha-hendel** [comment] 2016-03-14 09:12
Ok, if I activate accordion at https://cdn.ampproject.org/experiments.html the error message is still there, but the accordion works!
Is accordion in some kind of transition from dev to stable?

**Comment by pacojerte** [comment] 2016-03-14 09:20
Wyd

**Comment by erwinmombay** [comment] 2016-03-14 09:52
@sascha-hendel yes, from the docs https://github.com/ampproject/amphtml/releases it is still in pre-release. it should go out of canary and into prod on thursday. (might still be invalid per validator but should work w/o turning on experiment opt-in)

**Comment by Gregable** [comment] 2016-03-14 17:55
Validator work is still in progress. This tag has some new requirements on children that are different than other validations we've done in the past.

**Comment by ericlindley-g** [comment] 2016-03-14 19:20
@Meggin , are you able to update the documentation at https://www.ampproject.org/docs/reference/extended/amp-accordion.html to reflect that amp-accordion is still in experimental? Thanks!

**Comment by Meggin** [comment] 2016-03-14 19:41
The spec is updated-- just need to do another reference update. I'll try
and do this today, but it might be tomorrow.

Meggin

**Comment by rudygalfi** [comment] 2016-03-24 00:46
@powdercloud can you update the status of the validator work?

**Comment by powdercloud** [comment] 2016-03-24 08:33
@rudygalfi validation is done and live.
E.g. https://ampbyexample.com/components/amp-accordion/#development=1
I'd like to update the spec slightly (section must have exactly 2 child tags, the first of which must be h1-h6). Will send a pr tomorrow.

**Comment by Gregable** [comment] 2016-03-24 17:14
Github #2061 was tracking the validation, should we rename this issue or dedupe?

**Comment by powdercloud** [comment] 2016-03-24 17:48
I'm in favor of deduping - easier to find discussions later. Last night when I looked at this I only saw your comment on the other one after I commented here.
As for the documentation I sent https://github.com/ampproject/amphtml/pull/2688.

**Comment by rudygalfi** [comment] 2016-03-30 21:51
Dupe of #2061.

**Closed by rudygalfi** 2016-03-30 21:51 UTC
Labels: Related to: Validator, Type: Question
