### ISSUE TITLE
AMP-Carousel - Unable to load image in gallery when the original img contains spaces

### ISSUE THREAD

**Issue by merakmarey** [ampproject/amphtml#23092] opened 2019-06-28 13:17 UTC
Image show as missing on gallery mode if  file name is duplicated, even if path is different.

Image sources on carousel:

/i/images/4/image-1.jpg
/i/images/5/image-1.jpg

Error arrives when setting srcset attribute, the first image will be set to "/i/images/1/image-1.jpg 1x" while the second image "/i/images/2/image-1 - Copy.jpg 1x", rendering the second image missing.

Chrome and possibly all other

AMP Version 1906191709480

**Comment by sparhami** [comment] 2019-06-28 21:10
Do you have an example page where this happens?

**Comment by merakmarey** [comment] 2019-06-28 22:29
Try this, let me know if doesn't work, since its a dev server
https://us.trapichero.com/a/wayne/pennsylvania/buy-or-sell/cells-and-accesories/safgasfgsfgsdgfs/1561593245-68.html

Thanks

Merak Marey
Sr. Software Engineer.
Miami. Florida. USA.LinkedIn : http://www.linkedin.com/in/merakmarey 

    El viernes, 28 de junio de 2019 05:11:14 p. m. EDT, Sepand Parhami <notifications@github.com> escribió:  
 
 
Do you have an example page where this happens?

**Comment by sparhami** [comment] 2019-06-28 22:39
Hmm, the problem seems to be the code doesn't play well with spaces in the filename currently. This works for `src`, but not `srcset`. We can fix this by simply using `src` if we never had a `srcset` to start with or uri-encoding any `src` we convert over to a `srcset`.

**Comment by merakmarey** [comment] 2019-06-28 23:13
I don't think that is the main issue. From my point of view the problem is this...why for the second srcset the "- Copy" is added, when the src uri is different from the first one?

**Comment by sparhami** [comment] 2019-06-28 23:19
I'm not sure how you are generating the page, but the page source, as received from the server has:

```html
        <amp-carousel layout="responsive" width="626" height="417" type="slides" autoplay controls loop delay="6000" id="slider-with-preview">
    
            <amp-img src="/i/images/1/gallery-1-1.jpg" width="626" height="417" layout="responsive" alt="aa" lightbox></amp-img>
    
            <amp-img src="/i/images/2/gallery-1-4-full - Copy.jpg" width="626" height="417" layout="responsive" alt="aa" lightbox></amp-img>
    
            <amp-img src="/i/images/3/gallery-1-4-full.jpg" width="626" height="417" layout="responsive" alt="aa" lightbox></amp-img>
    
            <amp-img src="/i/images/4/gallery-2-1.jpg" width="626" height="417" layout="responsive" alt="aa" lightbox></amp-img>
    
            <amp-img src="/i/images/5/gallery-2-1-full.jpg" width="626" height="417" layout="responsive" alt="aa" lightbox></amp-img>
    
</amp-carousel>
```

The src is then translated into a srcset, which fails to load due to the space. The adding of "- Copy" is prior to the AMP page being loaded, so you may want to look into how the page itself is generated.

As far as AMP itself is concerned, failing to load an image with a space in the name in the gallery seems to be  the only issue.

**Comment by merakmarey** [comment] 2019-06-29 14:27
I see what you mean now, yes, the page is generating the " - Copy". So, only issue would be the treatment of the space in filling the srcset attribute.

**Comment by sparhami** [comment] 2019-07-08 17:17
To recap: the problem is that if a `src` has spaces in it, we carry over the space when we generate a `srcset` from the `src`. This confuses the `srcset` parsing.

A simple change would be to call `encodeURI` when we convert a `src` attribute into a `srcset`, Another option would be to stop operating on `amp-img`, and instead do `img.src` on the internal `<img>`, which will give a URI encoded version.

Looking at the specs, it looks like spaces in URLs are not actually valid though, and may not work in all browsers. Since the original code is not valid, I don't think we should necessarily try to handle it.

Instead, we may want to add a validation rule to make sure src is a valid URL. A valid URL may have leading or trailing spaces, but may not include spaces inside, The rules from the spec make it a bit hard to piece together on what a valid URL is. A complete regex may not be ideal to implement, though there may be an existing library to check without us doing it as a regex. Alternatively, we may be able to simply check that a URI encoded version of all URLs are equivalent to the original URL.

@Gregable Any thoughts on validating this?

**Comment by merakmarey** [comment] 2019-07-08 17:45
encoding works <img class="i-amphtml-lbg-gallery-thumbnail-img" srcset="/i/images/2/gallery-1-4-full%20-%20Copy.jpg 1x">..

**Comment by merakmarey** [comment] 2019-08-31 23:35
Any new development on this?

**Comment by merakmarey** [comment] 2021-02-22 13:25
was this fixed? is AMP still a thing or is discontinued?

**Comment by kristoferbaxter** [comment] 2021-02-22 17:10
I've demonstrated this working as expected in https://github.com/ampproject/amphtml/pull/32790. Closing.

If there is another example we can take a look at please re-open!

**Closed by kristoferbaxter** 2021-02-22 17:10 UTC
Labels: Component: amp-lightbox-gallery, Customer: Developer, P2: Soon, Type: Bug, WG: components
