### ISSUE TITLE
[CANARY Error: ] failed to execute a task:: Request pushHistory failed: e

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#11448] opened 2017-09-26 22:43 UTC
```
Error: failed to execute a task:: Request pushHistory failed: e
at Error (https://raw.githubusercontent.com/ampproject/amphtml/1506372648650/extensions/amp-viewer-integration/0.1/messaging/messaging.js:310)
at (https://raw.githubusercontent.com/ampproject/amphtml/1506372648650/extensions/amp-viewer-integration/0.1/messaging/messaging.js:90)
```

**Comment by dvoytenko** [comment] 2017-09-26 23:27
Dupe of #8785

**Closed by dvoytenko** 2017-09-26 23:27 UTC
