### ISSUE TITLE
Validator gives the wrong error when "amp-custom" is missing

### ISSUE THREAD

**Issue by fstanis** [ampproject/amphtml#15309] opened 2018-05-15 17:15 UTC
## What's the issue?

When the custom CSS part of an AMP page doesn't have the `amp-custom` attribute, i.e. `<style>` is used, the AMP Validator correctly notices there's an issue, but gives a misleading error, it complains about the `amp-boilerplate` bit, which is correct ("The mandatory text inside tag 'head > style[amp-boilerplate] - old variant' is missing or incorrect.").

## How do we reproduce the issue?

Install the Validator and try this page (mostly copied from [AMP by Example](https://ampbyexample.com/introduction/hello_world/)):

```html
<!doctype html>
<html ⚡>
<head>
  <meta charset="utf-8">
  <title>Hello World</title>
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <link rel="canonical" href="https://ampbyexample.com/introduction/hello_world/">
  <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
  <style>h1{color:red}</style>
  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
</head>
<body>
  <h1>Hello World!</h1>
</body>
</html>
```

## What browsers are affected? / Which AMP version is affected?

N/A, issue is with the validator.

**Comment by Gregable** [comment] 2018-05-15 18:02
Thanks. This is a dupe of https://github.com/ampproject/amphtml/issues/4421

Agreed, it needs more attention though.

**Closed** 2018-05-15 18:02 UTC
Labels: Category: Validator, P3: When Possible
