### ISSUE TITLE
Misleading validator error for multiple <style> elements

### ISSUE THREAD

**Issue by jeffreysbrother** [ampproject/amphtml#24359] opened 2019-09-04 17:57 UTC
## What's the issue?

After inadvertently adding a second style tag to an AMP document, the following two errors are produced:

1. The mandatory attribute 'amp-custom' is missing in tag 'style amp-custom'.
2. The tag 'style amp-custom' appears more than once in the document

The first is legitimate, while the second is a false-positive.

## How do we reproduce the issue?

I cannot provide a public URL for this, unfortunately. These are the steps to reproduce:

1. create a valid AMP document which includes one instance of `<style amp-custom>`. Include a couple valid CSS rules.
2. create an _additional_ `style` tag (but with no "amp-custom" attribute). Include a couple valid CSS rules.
3. test the page for AMP validity.

This test should NOT produce the second error message above, since there is only one `<style>` tag with the "amp-custom" attribute.

## Which AMP version is affected?

I am using https://cdn.ampproject.org/v0.js

**Comment by Gregable** [comment] 2019-09-10 19:08
I tried reproducing using:

```
<!doctype html>
<html ⚡>
<head>
  <meta charset="utf-8">
  <link rel="canonical" href="self.html" />
  <meta name="viewport" content="width=device-width,minimum-scale=1">
  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
  <script async src="https://cdn.ampproject.org/v0.js"></script>

  <style amp-custom>.foo {}</style>
  <style>.bar {}</style>

</head><body></body></html>
```
And tested on https://validator.ampproject.org/ which uses the same javascript validator as you did. I think this follows your directions. However, I only see one error:

```
The mandatory attribute 'amp-custom' is missing in tag 'style amp-custom'.
```

**Comment by honeybadgerdontcare** [comment] 2019-09-10 19:17
If one were to invert the order of `amp-custom` then it does have two errors.

```
<!doctype html>
<html ⚡>
<head>
  <meta charset="utf-8">
  <link rel="canonical" href="self.html" />
  <meta name="viewport" content="width=device-width,minimum-scale=1">
  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
  <script async src="https://cdn.ampproject.org/v0.js"></script>

  <style>.bar {}</style>
  <style amp-custom>.foo {}</style>
  
</head><body></body></html>
```

This is an issue worth flagging and we should try to improve these error messages. However it's most likely not a very high priority. If someone is interested in fixing this then please file a I2I or PR with a potential fix.

**Comment by jeffreysbrother** [comment] 2019-09-10 19:19
Interesting!
I wonder what's causing this disparity.

In my case, the erroneous, plain style tag was inserted before the amp-custom style tag. I wonder if you'll see both errors if the illegal tag occurs begore the legal one. I was also inserted before all AMP scripts.

I'm able to reproduce after adding the following Google Optimize snippet in the same place I've mentioned above (before all AMP scripts and before "<style amp-custom>":

```
<!-- Anti-flicker snippet (recommended)  -->
<style>.async-hide { opacity: 0 !important} </style>
<script>(function(a,s,y,n,c,h,i,d,e){s.className+=' '+y;h.start=1*new Date;
h.end=i=function(){s.className=s.className.replace(RegExp(' ?'+y),'')};
(a[n]=a[n]||[]).hide=h;setTimeout(function(){i();h.end=null},c);h.timeout=c;
})(window,document.documentElement,'async-hide','dataLayer',4000,
{'GTM-KSLRTLN':true});</script>
```

**Comment by Gregable** [comment] 2019-09-27 03:43
Good catch on the ordering thing, I know what's going on! The reason for this is the way the validator tries to handle error reporting.

When it encounters the first disallowed <style> tag, it tries to match it to the closest possible rule it can find. In this case, that is the rule for `<style amp-custom>`. It then emits the relevant error and treats the rest of the document as though the tag had been a `<style amp-custom>` tag.

The reason for treating the rest of the document is that this can improve error handling later. Consider a document like:

```
<!doctype html>
<html ⚡>
<head>
  <meta charset="utf-8">
  <link rel="canonical" href="self.html" />
  <meta name="viewport" content="width=device-width,minimum-scale=1">
  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <script custom-element='amp-analytics' src='https://cdn.ampproject.org/v0/amp-analytics-0.1.js'></script>
</head>
<body>
    
  <amp-analytics type=googleanalytics></amp-analytics>
    
</body>
</html>
```

In this case we get the error in the document head:

```
The mandatory attribute 'async' is missing in tag 'amp-analytics extension .js script'.
```


We notably do **not** get the error:

```
The tag 'amp-analytics' requires including the 'amp-analytics' extension JavaScript.
```

This is because we treat the error'ing tag above as a valid version of the nearest matching rule for processing the remainder of the document.



In this case, I think we tweak the validator to not satisfy 'unique' requirements for rules which did not pass.

**Comment by Gregable** [comment] 2020-05-01 22:48
This has been fixed for some time, I forgot to close the issue.

**Closed by Gregable** 2020-05-01 22:48 UTC
Labels: P3: When Possible, Type: Bug, WG: caching
