### ISSUE TITLE
AMP Carousel [slide] binding fails to go back to index 0

### ISSUE THREAD

**Issue by stephengardner** [ampproject/amphtml#25957] opened 2019-12-09 23:54 UTC
AMP Carousel Bug in Version 0.2:

AMP Carousel type="slides" will not be able to go back to slide index 0 if using the [slide] binding.

version 0.2 fails.
version 0.1 succeeds.

Stackblitz reproduction example: https://stackblitz.com/edit/js-yiazgm?file=index.html

**Comment by sparhami** [comment] 2019-12-10 23:09
This looks to be a duplicate of #25723, which should hopefully be fixed in the next release.

**Closed by sparhami** 2019-12-10 23:09 UTC
Labels: Type: Bug
