### ISSUE TITLE
Click tracking support

### ISSUE THREAD

**Issue by pdufour** [ampproject/amphtml#3269] opened 2016-05-19 01:50 UTC
## Short description of your issue:

It would be very useful to have extra amp-analytics vars for the element that was clicked. This would be especially useful for instance if you wanted to track which outbound links were clicked the most. They would be similar to these vars https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/analytics-vars.md#interaction.

My proposal, borrowing from what GTM has in place:
- Click Classes
- Click ID
- Click Target
- Click URL
- Click Hostname
- Click Host
- Click Text

**Comment by rudygalfi** [comment] 2016-05-23 19:27
This seems to overlap with #1298.

**Comment by rudygalfi** [comment] 2016-07-29 19:58
Closing this out as a duplicate of #1298, which is being worked on currently. Please take a look and let us know if that won't address the issue raised here.

**Closed by rudygalfi** 2016-07-29 19:58 UTC
Labels: Related to: Analytics, Type: Request
