### ISSUE TITLE
`should not validate with wrong key` in test-crypto-verifier fails in Safari

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#6162] opened 2016-11-12 01:44 UTC
try `gulp test --files=extensions/amp-a4a/0.1/test/*.js --safari`

fails with
```
Key size is not valid for RS256
	importKey@[native code]
	/var/folders/00/1rjwh000h01000cxqpysvccm00727k/T/101b0ac3ea60260bdb9c4171d9895518.browserify:3216:33 <- /Users/aghassemi/git/amphtml/extensions/amp-a4a/0.1/crypto-verifier.js:54:10
	promiseReactionJob@[native code]

```

**Comment by jasti** [comment] 2017-02-10 06:11
@ampproject/a4a, can someone take a look please?

**Comment by keithwrightbos** [comment] 2017-03-13 17:39
Closing as duplicate of #6900

**Closed by keithwrightbos** 2017-03-13 17:39 UTC
Labels: Category: Ads
