### ISSUE TITLE
Travis build is continuously failing

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#4764] opened 2016-08-29 22:50 UTC
Seems the assert message needs to be updated? `/validator/nodejs/index_test.js` line 122.

![screenshot from 2016-08-29 15 47 24](https://cloud.githubusercontent.com/assets/8496897/18070035/04d3d790-6e00-11e6-9b81-9c19a222e697.png)

**Comment by jridgewell** [comment] 2016-08-29 22:51
Dupe of https://github.com/ampproject/amphtml/issues/4757.

**Closed by jridgewell** 2016-08-29 22:51 UTC
Labels: Related to: Testing
