### ISSUE TITLE
Is there a published way for me to embed AMP pages in my site?

### ISSUE THREAD

**Issue by kevinmarks** [ampproject/amphtml#1050] opened 2015-12-02 21:59 UTC
It's not clear from the docs

**Comment by cramforce** [comment] 2015-12-02 22:20
@kevinmarks Could you elaborate what exactly you mean with embedding an AMP page into a site?

**Comment by kevinmarks** [comment] 2015-12-03 00:16
Clearly I could just iframe it, what I meant is there a documented way to take advantage of the kinds of caching and preloading shown in the google news search demo?

**Comment by cramforce** [comment] 2015-12-03 01:08
@kevinmarks Ah, no because we don't have such a thing yet in a reusable state. It is on our medium term radar to make this available. Working on it as fast as we can.

**Comment by jpettitt** [comment] 2015-12-06 20:59
The logical thing to do is have the AMP page notice if it's framed and if so post a message to the parent frame with the height of the <body> element on initial load and in response to any resize events. This would let the framing page resize the iframe appropriately.

Beyond that it would be nice to allow the framing page to pass in style hints (colors, font metrics, fonts) as #parameters so the AMP page could make itself match the look of the parent.

**Comment by adewale** [comment] 2016-08-10 09:11
See: https://github.com/ampproject/amphtml/issues/3742 and https://github.com/ampproject/amphtml/blob/master/examples/viewer.html

**Comment by bpaduch** [comment] 2017-02-06 15:12
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)

**Closed by bpaduch** 2017-02-06 15:12 UTC
Labels: Category: Viewer, Related to: Documentation, To be deprecated - Type: Question
