### ISSUE TITLE
amp-mustache new version remove the href attribute

### ISSUE THREAD

**Issue by mofidsky** [ampproject/amphtml#18463] opened 2018-10-01 09:40 UTC
amp-mustache-0.2.js automatically remove the href from a tag inside the amp-list

**Comment by choumx** [comment] 2018-10-01 15:46
@mofidsky I can't reproduce this on the [ABE example](https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2Fcomponents%2Famp-list%2Fsource%2F) after changing version to 0.2. Can you provide a URL or code snippet that shows the buggy behavior?

**Comment by mofidsky** [comment] 2018-10-02 07:54
i test it again its doesn't work in local. 
but worked when upload to server...
![mustache](https://user-images.githubusercontent.com/41105577/46335774-7008ee80-c635-11e8-9f5c-61fe50f532b2.png)
but the same code worked in code pen
[codepen](https://codepen.io/mofidsky/pen/zmvzjx)

**Comment by choumx** [comment] 2018-12-04 16:44
Closing since this can't be reproduced.

**Closed by choumx** 2018-12-04 16:44 UTC
Labels: Category: Dynamic/Personalized Content, P2: Soon, Type: Bug
