### ISSUE TITLE
Content Blank when coming through AMP CDN

### ISSUE THREAD

**Issue by ahmedkaludi** [ampproject/amphtml#13366] opened 2018-02-08 14:25 UTC
Hi, I'm one of the lead developers of AMPForWP plugin, we have a unique issue which we just couldn't solve.

## What's the issue?

When coming from the Google AMP CDN, the whole content is blank, Please see this video: http://take.ms/DLAZy

## How do we reproduce the issue?

If this is a bug please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else.  Then provide step-by-step instructions for reproducing the issue:

1. Type: "launcher iphone androidsis" in the Google through iOS and you will see the first result.
2. Upon opening that, you will see that whole page is blank
3. when going through the iOS simulator and debugging, i find that it works if we turn on or off the 
`html.i-amphtml-ios-embed.i-amphtml-ios-overscroll, html.i-amphtml-ios-embed.i-amphtml-ios-overscroll>#i-amphtml-wrapper: -webkit-overflow-scrolling: touch !important;` 

See the video at http://take.ms/DLAZy

## What browsers are affected?

iPhone X and latest iOS devices

## Which AMP version is affected?

It seems it's been a core issue, because We have seen this with few users in the past.

**Comment by aghassemi** [comment] 2018-02-08 17:06
@ahmedkaludi we have seen this a few time, the cause tends to be a GPU bug and only kicks in with rate situations where `overscoll:touch` badly interactions with some other CSS in the page. The solution is normally involving making changes to the CSS. 

The way I recommend debugging this is by inspecting the CSS for the top wrapper elements in your page from Safari's remote debugger and toggling CSS rules, specially the ones around overflow, z-index, transform, until content displays, then you have a candidate

**Comment by aghassemi** [comment] 2018-02-22 23:51
Closing the issue since it's a GPU bug caused by interaction of user-land CSS with `-webkit-overflow-scrolling: touch`. Debugging and fix requires figuring out exactly what user CSS is causing the issue and finding an alternative way of doing the same thing with a different CSS rule.

**Closed by aghassemi** 2018-02-22 23:51 UTC
