### ISSUE TITLE
SlideScroll: Landscape mode displays text incorrectly

### ISSUE THREAD

**Issue by corvusinaloeCMENA** [ampproject/amphtml#5100] opened 2016-09-19 22:10 UTC
After a few swipes, when switching from portrait to landscape modes, the text 
URL used: cdn.ampproject.org/c/www.mundodeportivo.com/elotromundo/actualidad/20160915/41312869196/tiziana-cantone-italia-suicidio-video-porno-ex

1.Enable "amp-slidescroll" and "amp-scrollable-carousel" experiments at https://cdn.ampproject.org/experiments.html
2.Go to cdn.ampproject.org/c/www.mundodeportivo.com/elotromundo/actualidad/20160915/41312869196/tiziana-cantone-italia-suicidio-video-porno-ex
3.Scroll down at the bottom of the page to find the carousel
4. On the carousel, scroll to the right and left
5. Switch to landscape mode
6. The text is broken displayed on both sides of the carousel. 

Samsung Galaxy S5 Chrome 52.0.27

**Comment by corvusinaloeCMENA** [comment] 2016-09-19 22:57
Same issue found on:
Samsung Galaxy S5 Lolipop Stock 2.1.34

**Comment by sriramkrish85** [comment] 2016-09-20 00:17
Duplicate of #5096

**Comment by sriramkrish85** [comment] 2016-09-20 00:21
@corvusinaloeCMENA this url does not work - also assign all carousel bugs to me lets spare @jridgewell some work :)

**Closed** 2016-09-20 17:47 UTC
Labels: Closed: Duplicate, Type: Bug
