### ISSUE TITLE
Error: Unspecified error

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#18486] opened 2018-10-01 21:19 UTC
Error: Unspecified error.
at getLayoutRect (https://cdn.ampproject.org/v0.js:425)
at getLayoutRect (https://cdn.ampproject.org/v0.js:459)
at $b (https://cdn.ampproject.org/v0/amp-ad-latest.js:89)
at onLayoutMeasure (https://cdn.ampproject.org/v0/amp-ad-latest.js:88)
at updateLayoutBox (https://cdn.ampproject.org/v0.js:260)
at measure (https://cdn.ampproject.org/v0.js:238)
at Kk (https://cdn.ampproject.org/v0.js:367)
at h (https://cdn.ampproject.org/v0.js:378)
at setState (https://cdn.ampproject.org/v0.js:340)
at doPass (https://cdn.ampproject.org/v0.js:361)

go/ampe/CMKGmrbZo_esGw

**Comment by choumx** [comment] 2019-01-18 21:12
Dupe of #20438.

**Closed by choumx** 2019-01-18 21:12 UTC
Labels: Category: Runtime, P3: When Possible
