### ISSUE TITLE
Ctrl+F doesn't work on chrome for iOS

### ISSUE THREAD

**Issue by rufioh** [ampproject/amphtml#6492] opened 2016-12-06 10:23 UTC
## Short description of your issue:

Find in page on chrome for iOS doesn't work

## How do we reproduce the issue?

use an iPhone 6s,
Have iOS 10
Open chrome for iOS 
Open a page that uses AMP
Try to "find in page" something you can already see is there
No results will be found

**Comment by rufioh** [comment] 2016-12-06 10:25
Here's an example https://imgur.com/a/5dWiR

**Comment by rufioh** [comment] 2016-12-06 10:27
As you can see in this image https://imgur.com/a/5dWiR, I searched for the first two words on the page and recieved zero results.

**Comment by jridgewell** [comment] 2016-12-06 20:26
/to @dvoytenko 

I know we have a bug for this open already, but I can't seem to find it.

**Comment by dvoytenko** [comment] 2016-12-07 20:35
Yes, this is dupe of #5750. Please ping on the associated webkit bug to improve chances of it being fixed sooner.

**Closed by dvoytenko** 2016-12-07 20:35 UTC
Labels: Type: Bug
