### ISSUE TITLE
Percy take screenshots of dynamic content making it flaky

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#16228] opened 2018-06-21 20:44 UTC
e.g.

https://percy.io/ampproject/amphtml/builds/809266
https://percy.io/ampproject/amphtml/builds/808654
https://percy.io/ampproject/amphtml/builds/808978
https://percy.io/ampproject/amphtml/builds/809472

Some of the Percy pages from ABE include video and iframe components which are dynamic and depending on the exact moment percy takes a screenshot, video might be at a different frame, not started, etc.. same for iframes and other dynamic content

These dynamic areas need to be excluded from the compare.

/cc @rsimha

**Comment by rsimha** [comment] 2018-06-21 20:47
@danielrozenberg is working on initially disabling these tests in #16133. After that, we should come up with a way to add a way to wait until dynamic content has stabilized. And finally, figure out a way to ensure that the test pages look the same across multiple builds.

**Comment by danielrozenberg** [comment] 2018-06-21 20:48
As Raghu said, duplicate of #16133 :)

**Closed by danielrozenberg** 2018-06-21 20:48 UTC
Labels: Category: Tooling
