### ISSUE TITLE
amp-story-interactive components doesn't load sometimes

### ISSUE THREAD

**Issue by saurabh230197** [ampproject/amphtml#31923] opened 2021-01-13 07:31 UTC
## What's the issue?

amp-story-interactive quiz/results components sometimes doesn't load.
Also `Cannot read property 'getLocalizedString' of null` this error appears in console.

https://sports.visualstories.com/quizzes/how-well-do-you-know-sergio-aguero

This story is one of the example. each alternative slide from 3rd slide have quiz component and last slide have results component.

## How do we reproduce the issue?

clean your browser cache and try to reproduce the issue.

![empty_quiz_screenshot](https://user-images.githubusercontent.com/64782640/104419639-c009e600-559e-11eb-831b-6af603c98e8d.PNG)
Attached screenshot is the 3rd slide of https://sports.visualstories.com/quizzes/how-well-do-you-know-sergio-aguero this story which have quiz component but it doesn't load.

note: this issue doesn't appear for every reload.

## What browsers are affected?

specially chrome browser but can't specify is it happening on all browsers. 

## Which AMP version is affected?

This happens always.

**Comment by processprocess** [comment] 2021-01-13 15:42
cc @Enriqe @mszylkowski

**Comment by mszylkowski** [comment] 2021-01-13 15:53
Got it, error seems to be:

<img width="426" src="https://user-images.githubusercontent.com/22420856/104475550-3c93c900-558d-11eb-8ab5-7ec605ad7608.png">

Can reproduce ~20% of times when hard refreshing on mobile UI. Taking a look.

**Comment by mszylkowski** [comment] 2021-01-14 19:05
Problem described by OP should be fixed with #31552, already merged.

The problem I found on the screenshot will be fixed with #31962.

Closing.

**Closed by mszylkowski** 2021-01-14 19:05 UTC
Labels: P1: High Priority, Type: Bug, WG: stories
