### ISSUE TITLE
amp-bind error getDynamicElementContainers

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#8653] opened 2017-04-09 19:22 UTC
When loading [product sample](https://ampbyexample.com/samples_templates/product/preview/)
I get:
bind-impl.js:399 Uncaught (in promise) TypeError: Cannot read property 'getDynamicElementContainers' of null
    at e (bind-impl.js:399)
    at bf.c [as oc] (bind-impl.js:440)
    at cf (chunk.js:179)
    at Ze.Gd (chunk.js:393)
    at chunk.js:408
e @ bind-impl.js:399
c @ bind-impl.js:440
cf @ chunk.js:179
Ze.Gd @ chunk.js:393
(anonymous) @ chunk.js:408

This doesn't always happens though.

@choumx @ericlindley-g

**Comment by choumx** [comment] 2017-04-10 15:47
I think this is a dupe of #8647. /to @kmh287

**Comment by kmh287** [comment] 2017-04-10 16:10
Yes, I think this is a duplicate. I'll have a PR out for this soon.

**Comment by kul3r4** [comment] 2017-04-10 17:18
Thanks!

**Comment by kmh287** [comment] 2017-04-12 19:32
Fixed by #8661

**Closed by kmh287** 2017-04-12 19:32 UTC
Labels: Category: Dynamic/Personalized Content, P2: Soon, Type: Bug

**Comment by ericlindley-g** [comment] 2017-04-18 00:02
@kmh287  —  do you know if this is in canary?
