### ISSUE TITLE
Switching between landscape and portrait mode changes the frame displayed on the carousel

### ISSUE THREAD

**Issue by corvusinaloeCMENA** [ampproject/amphtml#5102] opened 2016-09-19 23:02 UTC
If user is watching frame 3 on portrait mode, switching to landscape changes it to option two without user intervention. 
URL used: cdn.ampproject.org/c/www.mundodeportivo.com/elotromundo/actualidad/20160915/41312869196/tiziana-cantone-italia-suicidio-video-porno-ex

1.Enable "amp-slidescroll" and "amp-scrollable-carousel" experiments at https://cdn.ampproject.org/experiments.html
2.Go to cdn.ampproject.org/c/www.mundodeportivo.com/elotromundo/actualidad/20160915/41312869196/tiziana-cantone-italia-suicidio-video-porno-ex
3.Scroll down at the bottom of the page to find the carousel
4. On the carousel, scroll to the last option.
5.Switch to landscape mode 
Samsung Galaxy S5 Chrome 52.0.27
Samsung Galaxy S5 Lolipop Stock 2.1.34

**Comment by sriramkrish85** [comment] 2016-09-20 00:25
Duplicate of #5096

**Closed** 2016-09-20 17:46 UTC
Labels: Closed: Duplicate, Type: Bug
