### ISSUE TITLE
ObserveIntersection in AMP Flying Carper returns ad visible even when ad is not visible

### ISSUE THREAD

**Issue by guyra1** [ampproject/amphtml#4048] opened 2016-07-13 09:20 UTC
ObserveIntersection object in AMP Flying Carpet ad returns wrong data under intersectionRect
I am getting height 514 also most of the ad is hidden

to reproduce it register to ObserveIntersection under Flying Carpet test page 
https://ampbyexample.com/components/amp-fx-flying-carpet/

window.context.observeIntersection(function(changes) {
                    changes.forEach(function(c) {
                        console.dir(c);
                    });
                });

![image](https://cloud.githubusercontent.com/assets/19712074/16798300/0df3d658-48f4-11e6-8767-628217331254.png)

**Comment by cramforce** [comment] 2016-07-13 14:48
This is in a way a known issue, but also correct with respect to `IntersectionObserver` as it does not account for occlusion and the ad is technically in viewport, just not visible.

We are considering to fix it, though, by instead reporting the intersection with the window.
Not sure what the latest is: @jasti @jridgewell

**Comment by jridgewell** [comment] 2016-07-13 17:30
We need to report the intersection with respect to the `<amp-fx-flying-carpet>`, not the `<amp-ad>`. Should be as simple as changing the [root](https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad/0.1/amp-ad-api-handler.js#L75) to the parent when inside an [allowable fixed-position element](https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad/0.1/amp-ad-3p-impl.js#L30-L34).

**Comment by jasti** [comment] 2016-07-14 23:21
@jridgewell  If it's not too much work, we should go ahead and do it. It'll be required for launch.

**Comment by cramforce** [comment] 2016-07-14 23:32
This is definitely an interesting case, where we can easily do the right thing, but native IntersectionObserver cannot. CC @mpb

**Comment by jridgewell** [comment] 2016-07-15 00:07
> but native IntersectionObserver cannot

Isn't that part of the `IntersectionObserver` spec? It explicitly mentions [`clip-path`](https://github.com/ampproject/amphtml/blob/master/extensions/amp-fx-flying-carpet/0.1/amp-fx-flying-carpet.css#L39-L40) in [Section 3.2.4:3.2](https://wicg.github.io/IntersectionObserver/#calculate-intersection-rect-algo)

**Comment by mpb** [comment] 2016-07-15 00:13
Yes, that was intentionally left out of V1 Intersection Observer.
CC @szager-chromium

**Comment by szager-chromium** [comment] 2016-07-15 00:20
@cramforce Could you explain what IntersectionObserver can't do, that you can do with your existing code?  We want to cover all bases.

**Comment by cramforce** [comment] 2016-07-15 00:24
@jridgewell Could you explain the exact case?

Basically we have a fixed positioned iframe which wants to detect that sometimes something is on top of it. We are using `clip-path` for the occlusion. Example above.

**Comment by jridgewell** [comment] 2016-07-15 00:49
Essentially, we have:

```html
<flying-carpet height="300px">
  <clip css="clip-path: polygon(0px 0px, 100% 0px, 100% 100%, 0px 100%);">
    <container css="position: fixed; top: 0;">
      <amp-ad>
        <iframe src="https://ad.network"></iframe>
      </amp-ad>
    </container>
  </clip>
</flying-carpet>
```

Right now, we use `<amp-ad>` as the `IntersectionObserver` `root`, so it never encounters the clipping element. If instead we set root to be the `<flying-carpet>`, the `IntersectionObserver` would encounter the clipping element, and [hopefully](https://github.com/ampproject/amphtml/issues/4048#issuecomment-232828002) calculate the correct bounds.

**Comment by szager-chromium** [comment] 2016-07-15 10:13
The native IntersectionObserver implementation should honor clip-path correctly.  If it does not, please file a bug at https://crbug.com/new.

The native implementation does not account for paint occlusion, transforms, filters, or opacity.  To my knowledge, there is no existing alternative way to detect those things.

We want to make sure that IntersectionObserver is capable of replacing existing methods for checking visibility without sacrificing any functionality.  So if there is something you can do via other means, but not with IntersectionObserver, please do file a bug.

Thanks,

Stefan

**Comment by jridgewell** [comment] 2016-08-30 19:28
After looking into this, it's a bit more in-depth than I would have liked. This affects `<amp-ad>`, `<amp-iframe>`, and anything that does visibility tracking through `<amp-analytics>`. The proper fix is to implement [layers inside `Resources`](https://github.com/ampproject/amphtml/issues/3434).

We might be able to hack something together using the current `Resource#isFixed`, but we'll need to add some restrictions so that `<amp-lightbox>`, `<amp-sticky-ad>`, and `<amp-fx-flying-carpet>` do not contain one another. But even with the hack, I could very easily trick an element (not an ad) into thinking it's always 100% visible.

@jasti: What's the priority to implement? Can this wait until the (much needed) layering system is done?

**Comment by jasti** [comment] 2016-08-30 19:34
There is not enough demand that we need to hack it, but also can't go live without it. 
What's the rough timeline for getting layers inside resources working?

**Comment by cramforce** [comment] 2016-08-30 23:19
I personally expect the layers work to take up the majority of Q4.

If there is a trickable-but-working-with-honest-players mechanism we can implement quickly, I think we should do that.

**Comment by jridgewell** [comment] 2016-09-21 18:56
Dupe of https://github.com/ampproject/amphtml/issues/3812.

**Closed by jridgewell** 2016-09-21 18:56 UTC
Labels: Type: Bug
