### ISSUE TITLE
Issue using amp-analytics with Shadow DOM

### ISSUE THREAD

**Issue by enzo-giancola** [ampproject/amphtml#20400] opened 2019-01-17 12:29 UTC
Hi,

we are facing errors related to amp-analytics 
raising when AMP code is imported through a shadow dom 
based mechanism (in Polymer).

The problem we noticed:

amp-analytics events are fired within AMP content;
when AMP code is imported through a shadow dom based mechanism (in Polymer) events aren't fired;

How to reproduce:

- URL:
https://rep.repubblica.it/pwa/generale/2019/01/16/news/brexit_ora_i_leader_europei_aspettano_londra-216743076/

- amp-analytics code is like this:

```
<amp-analytics><script type="application/json">
        {
            "requests": {                    
                "host": "https://www.facebook.com",
                "base": "${host}/tr?noscript=1",
                "ViewPaywall" : "${base}&ev=ViewPaywall&id=${pixelId}&cd[meter_count]=0&cd[serviceId]=${serviceId}&cd[variant]=${variant}"
            },
            "vars": {                    
                "pixelId":"SOMEPIXELID",
                "variant": "VARIANT(swg-button-experiment)"
            },
            "triggers": {
                "accessAuthorizationFailed": {
                    "on": "subscriptions-access-denied",
                    "request": "ViewPaywall"
                }
            }
        }
    </script></amp-analytics>
```

Same problem with amp-analytics code like this:
```
<amp-analytics><script type="application/json"> {
            "requests":{
                "host": "https://pubads.g.doubleclick.net",
                "base": "${host}/activity",
                "ViewPaywall" : "${base};xsp=${xsp};ord=1;num=${num}?" 
            },
            "vars":{
                "xsp":"SOMEXSPCODE",
                "num":"RANDOM" 
            },
            "triggers": {
                "accessAuthorizationFailed": {
                    "on": "subscriptions-access-denied",
                    "request": "ViewPaywall"
                }
            },
            "transport": {
               "beacon": false,
               "xhrpost": false,
               "image": true
            }
        }
       	</script></amp-analytics>
```

Could you please check?

Best Regards,
Enzo

**Comment by jpettitt** [comment] 2019-01-17 15:51
If I turn on logging (append `#log=3` to the url above) I see the event being fired by `amp-subscriptions`

![image](https://user-images.githubusercontent.com/524856/51330546-9c057f80-1a2c-11e9-9d38-1b1ad6d40c38.png)

On that basis I suspect the bug is in `amp-analytics` so I'm going to assign it to that team.

**Comment by lannka** [comment] 2019-01-17 16:44
@jpettitt is this blocking anything at the moment? We can prioritize it in the next sprint (starting next week).

**Comment by jpettitt** [comment] 2019-01-18 17:47
Yes it's blocking a publisher launch so next sprint would be good.

**Comment by lannka** [comment] 2019-01-18 18:32
planned for next sprint. @zhouyx

**Comment by zhouyx** [comment] 2019-01-26 01:40
Hello @enzo-giancola, thank you for filing the issue. I looked at the given example page. What I found is that the `<amp-subscription>` and the `<amp-analytics>` are in two different shadow root. In this case, they don't share the same the analytics service, so the custom trigger doesn't propagate to `<amp-analytics>` in another shadow root.

**Comment by jpettitt** [comment] 2019-01-29 15:21
That makes sense, it's not reasonable to expect a top level analytics config to know all the possible triggers a subsequent shadow doc might invoke so the `amp-analytics` tag would need to be scoped to and reside in the same shadow root that the events are originating from.  Thank for debugging this.  @enzo-giancola does this resolve your issue?

**Comment by enzo-giancola** [comment] 2019-01-29 16:46
Hi, let me explain better.

We have the tag amp-experiment scoped to the same shadow root as the amp-analytics one
as you can see on the attached screen capture.

Because of we was unable to resolve VARIANTS runtime variable within the PWA 
we have configured an iframe with a minimal AMP content, in order to resolve runtime variable VARIANTS
duplicating the amp-experiment configuration.
This allows us to set a cookie we are using to customize the look&feel 
based on current treatement on the experiment.

So, the original AMP content has amp-experiment and amp-analytics tags.
They are still available on the same root when loaded into a shadow-dom.

Could you please check?

Best Regards

![amp-experiment_amp-analytics](https://user-images.githubusercontent.com/19192170/51924597-983f0900-23ed-11e9-96a4-82eea49249f5.jpg)

**Comment by zhouyx** [comment] 2019-01-29 17:41
@enzo-giancola I am a bit confused, Could you please clarify what the issue is?

Based on https://github.com/ampproject/amphtml/issues/20400#issue-400255421, the analytics trigger is "subscriptions-access-denied", and that is a signal from the `<amp-subscription>` component. So the `<amp-analytics>` must be placed in the same shadow root with `<amp-subcription>`, not `<amp-experiment>`. 

If I understand it right, you want to collect the `subscripts-access-denied` event and the VARIANTS variable. In that case, could you place have two seperate `<amp-analytics>` in the two different shadow roots. Thank you

**Comment by zhouyx** [comment] 2019-02-07 23:56
@enzo-giancola I'm going to close the issue as the behavior is expected. Please feel free to reopen and let me know if there're more questions. Thank you.

**Comment by enzo-giancola** [comment] 2019-02-08 10:13
@zhouyx, as attached a screen related to the following URL: 

https://rep.repubblica.it/pwa/generale/2019/02/07/news/francia_macron_eliseo_gilet_gialli_m5s_di_maio_conte_mattarella_salvini-218582355/

where as you can see `<amp-analytics>` is placed in the same shadow root with `<amp-subcription>`.

Is this correct?

Thank you

![ampproject-amphtml_20400](https://user-images.githubusercontent.com/19192170/52471962-76cee180-2b92-11e9-9ab4-de8ba3577d9b.jpg)

**Comment by zhouyx** [comment] 2019-02-08 19:45
@enzo-giancola Thank you for the screenshot. So I took a look at the page again. Interesting I found two amp-subscriptions in different shadow roots. And one of them is embedded in nested shadow root. 

first one:
![image](https://user-images.githubusercontent.com/5419904/52501469-49cffe00-2b95-11e9-980a-585d3fae41b3.png)

The one @enzo-giancola referred to, note that it is in a nested shadow root
![image](https://user-images.githubusercontent.com/5419904/52501653-b1864900-2b95-11e9-8e49-c45a43cd9d90.png)

@jpettitt @dvoytenko How do the two amp-subscriptions work together?

**Comment by zhouyx** [comment] 2019-02-08 19:47
And I found the exact `<amp-analytics>` element that is listening to 'subscriptions-access-denied' event. They seem to be placed under subscription guarded section properly. Thoughts?

![image](https://user-images.githubusercontent.com/5419904/52502238-1ee6a980-2b97-11e9-8438-f96ac60134bb.png)

**Comment by enzo-giancola** [comment] 2019-02-11 09:21
Hi @zhouyx, we are using the amp-subscriptions in the first shadow root
to manage the upper right corner login menu.

**Comment by zhouyx** [comment] 2019-02-12 21:16
@jpettitt @dvoytenko I am not familiar with the amp-subscription usage. But analytics custom event trigger works well when I tested with this [example](https://github.com/ampproject/amphtml/blob/master/test/manual/amp-analytics/analytics-shadow-root-2.html) where there're `<amp-carousel>` and `<amp-analytics>` in one shadow doc. 

Do you see any thing from the screenshots? Thank you.

**Comment by jpettitt** [comment] 2019-03-12 14:03
I don't see anything obvious.  If you load an AMP page with #log=3 all am subscriptions analytics events will be logged to the console (even if there is nothing listening for them)

**Comment by enzo-giancola** [comment] 2019-04-02 14:19
Hi all, is there any update on this?
We are still facing the same issue. Thank you.

**Comment by prateekbh** [comment] 2019-06-10 19:21
Hi @enzo-giancola, we recently worked with re.republica highlighting the problems around multiple shadow root in #21902.

I believed it was changed may be to use a single shadow root. Does that effect this issue of yours or are you still using multiple shadow roots?

**Comment by gilbertococchi** [comment] 2019-06-11 13:55
+ @iwoak

I believe Repubblica is still using two Shadow Roots as they need to use it for the outer Login Subscription module within the page.

They did try using v0 and amp-subscription to remove one ShadowRoot but unfortunately it seems like Bento AMP + Shadow AMP approach is not compatible. 

Do you know if this could be solved?

**Comment by gilbertococchi** [comment] 2019-07-10 13:45
Hi all, any Bento AMP approach that will be available for components such as amp-subscription?

Rep Repubblica is measuring a really high TTI especially because of the late triggering of the amp-subscription module via shadow-amp.

**Closed** 2020-03-01 19:20 UTC
Labels: Component: amp-analytics, P2: Soon, Type: Bug, WG: access-subscriptions, WG: analytics
