### ISSUE TITLE
Only allow variable CLIENT_ID replaced in HTTPS URLs

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#5205] opened 2016-09-23 21:16 UTC

**Comment by jpettitt** [comment] 2016-09-24 00:19
Are we talking amp-analytics targets or is this related to #4078

**Comment by cramforce** [comment] 2016-09-26 19:21
For `amp-analytics` this is not a change as it only allows HTTPS in the 1st place.

Yes, this would be for #4078.

But I think this is only one of multiple rules we may need.

**Comment by cramforce** [comment] 2016-10-14 23:30
Duplicate of #4078

**Closed by cramforce** 2016-10-14 23:30 UTC
Labels: Related to: Analytics
