### ISSUE TITLE
Unused 'amp-consent' import throws a validation error, not a warning

### ISSUE THREAD

**Issue by mcmd** [ampproject/amphtml#22583] opened 2019-05-30 10:40 UTC
**Please only file reports about bugs in AMP here.**

## What's the issue?

Importing 'amp-consent' and not using it results in an AMP validation error. The same thing with other components results in a validation warning, which seems like a more appropriate response. I think in this case this should happen too.

## How do we reproduce the issue?

[JSBin](https://jsbin.com/xuyiwoniqo)

Simple code to reproduce the issue:

```
<!doctype html>
<html ⚡>
<head>
  <meta charset="utf-8">
  <title>My AMP Page</title>
  <link rel="canonical" href="self.html" />
  <meta name="viewport" content="width=device-width,minimum-scale=1">
  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <script async custom-element="amp-consent" src="https://cdn.ampproject.org/v0/amp-consent-0.1.js"></script>
  <style amp-custom>
    h1 {
      margin: 1rem;
    }
  </style>
</head>
<body>
  <h1>Hello AMPHTML World!</h1>
</body>
</html>
```

If you run this code through the validator, you'll get a validation error:

> The extension 'amp-consent' was found on this page, but is unused. Please remove this extension.
> AMP_TAG_PROBLEM

## What browsers are affected?

N/A

## Which AMP version is affected?

N/A

**Comment by torch2424** [comment] 2019-05-30 13:52
Making a guess here but, I think this is because `amp-consent` was introduced after the warning was created, as I know the warning states:

`The tag "whatver your tag is" is missing or incorrect, but required by "whatever extension". This will soon be an error.`.

Though personally, I think it should be an error, as the only reason I think it warns for other extensions is not to break older AMP pages.

cc @aghassemi @Gregable

**Comment by aghassemi** [comment] 2019-05-30 14:46
Hi @mcmd, This is by design. We want to avoid unnecessary download and parse of extensions that are not used and error is the best way to enforce that performance rule. 

The reason some other extensions don't do this is historical backward compatibility. This is the way we will be moving forward for new extensions.

**Comment by aghassemi** [comment] 2019-05-30 14:46
Closing per explanation above.

**Closed by aghassemi** 2019-05-30 14:46 UTC
Labels: Type: Bug
