### ISSUE TITLE
ISSUE : Amp validator shows input type="file" as invalid. any alternate method to use type="file" ?

### ISSUE THREAD

**Issue by pratikvc** [ampproject/amphtml#11877] opened 2017-10-31 13:04 UTC
1) If we add <input type="date" ...> in form for choose file button as u can see below.

![img_31102017_184127_0](https://user-images.githubusercontent.com/28097130/32225524-7f5da290-be6b-11e7-8243-037395e639d7.png)

2 ) In AMP validator plugin it shows below error. As type = "file" is stating as invalid value.

![img_31102017_143119_0](https://user-images.githubusercontent.com/28097130/32225217-59bbc298-be6a-11e7-9fa0-2da2ae38adfc.png)

**Comment by honeybadgerdontcare** [comment] 2017-11-01 17:54
This feature has been requested before. See #9791 closing this as dupe of that issue.

**Closed by honeybadgerdontcare** 2017-11-01 17:54 UTC
