### ISSUE TITLE
Request: Allow Legend elements

### ISSUE THREAD

**Issue by EnigmaSolved** [ampproject/amphtml#2025] opened 2016-02-15 21:32 UTC
I totally understand why forms are prohibited. But the fieldset & legend combo is very useful for display purposes, thus it would be nice if it could be allowed. For example, the WordPress plugin *Organize Series* (https://wordpress.org/plugins/organize-series/) defaults to using fieldset/legend in several places (eg, to display the list of posts in the series).

Thanks for your consideration!

**Comment by cramforce** [comment] 2016-02-15 21:42
+1

CC @honeybadgerdontcare

**Comment by EnigmaSolved** [comment] 2016-02-15 22:01
Excellent, thanks! :)

**Comment by Gregable** [comment] 2016-07-01 22:14
Fieldset is now supported as part of the forms validation, but we'll still need to do legend separately. I've updated the issue subject accordingly.

**Comment by honeybadgerdontcare** [comment] 2016-07-01 22:40
The `fieldset` does require amp-form extension script to be included and to be a child of a form element. Should we relax those requirements for both `fieldset` and `legend`?

**Comment by Gregable** [comment] 2016-07-01 22:42
Probably.

**Comment by cramforce** [comment] 2016-07-01 23:35
CC @mkhatib

**Comment by mkhatib** [comment] 2016-07-02 10:23
Let's definitely whitelist `legend` inside `fieldset`.

I am not entirely sure about relaxing supporting fieldset/legend outside of form context. It probably is not harmful and I believe its valid HTML but semantically it doesn't make sense specially that both `fieldset` and `legend` are always described and defined in the context of `form` and its controls. 

I don't feel strongly against it though.

https://www.w3.org/TR/html5/forms.html#the-fieldset-element
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/legend

**Comment by cramforce** [comment] 2016-07-02 16:09
If it is allowed in HTML and the elements do not have harmful side effects, we should allow it.

**Comment by Gregable** [comment] 2016-07-06 16:59
Perhaps, unless you think it's likely to indicate that the developer made an unintentional mistake (ex: indicates that the form was intended, but the page is thus broken in some way).

**Comment by mkhatib** [comment] 2016-07-06 17:30
If we keep the restrictions on input controls to have a form ancestor then we should mitigate that unintentional mistake. Reading online it seems that using legend and fieldset outside of the form context seems to be valid HTML though I haven't tested it. If needed I can test it out.

**Comment by EnigmaSolved** [comment] 2016-07-06 17:40
Running a page with a fieldset-legend combo (without a form tag) through the html5 validator yields no errors related to those tags (though admittedly there's some unrelated errors):
https://validator.w3.org/nu/?doc=https%3A%2F%2Ftransitionsmft.org%2Fblog%2F851%2Fforgiveness-is-the-foundation-for-reconciliation%2F

**Comment by cramforce** [comment] 2016-07-06 18:35
Lets not be stricter than HTML5!

**Comment by Gregable** [comment] 2016-07-06 20:22
Will be in the next validator roll-up.

The direction is confusing though. We are stricter than HTML5 to help folks catch errors in other places (disallowing relative URLs, requiring amp-foo-0.1.js if `<amp-foo>` is present, requiring tabindex for on="tap:", light validation of mustache syntax, etc.)

**Comment by Gregable** [comment] 2016-07-08 22:44
Fixed, will roll out to cdn.ammproject.org soon.

**Closed by Gregable** 2016-07-08 22:44 UTC
Labels: Related to: Validator

**Comment by EnigmaSolved** [comment] 2016-07-09 00:06
Awesome--thanks! :)

**Comment by Gregable** [comment] 2016-07-20 18:11
Should be live on cdn.ammproject.org.
