### ISSUE TITLE
cannot read property 'classList' of null

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#3758] opened 2016-06-23 23:34 UTC
![image](https://cloud.githubusercontent.com/assets/5419904/16323506/24fc259c-3960-11e6-8872-e50b1d14fe1b.png)

**Comment by jridgewell** [comment] 2016-06-24 17:58
Please post the text next time.

```
TypeError: Cannot read property of ‘classList’ of null
  at Object.mutate (https://cdn.ampproject.org/rtv/001466185787499/v0.js:180:289)
  at Je.JSCompier_prototypeAlias.$d (https://cdn.ampproject.org/rtv/001466185787499/v0.js:153:237)
  at jd.oa (https://cdn.ampproject.org/rtv/001466185787499/v0.js:68:567)
  at hd (https://cdn.ampproject.org/rtv/001466185787499/v0.js:68:265)
```

**Comment by jridgewell** [comment] 2016-06-24 18:06
Coming from:

```js
  toggleInputClass_(clazz, on) {
    this.vsync_.mutate(() => {
      this.win.document.body.classList.toggle(clazz, on);
    });
  }
```

Somehow, that `document`'s `body` isn't present yet.

**Comment by erwinmombay** [comment] 2016-06-24 18:11
this should have been fixed in https://github.com/ampproject/amphtml/pull/3647/files i think

**Comment by erwinmombay** [comment] 2016-06-24 18:12
dupe of https://github.com/ampproject/amphtml/issues/3637

**Closed by erwinmombay** 2016-06-24 18:11 UTC
Labels: Type: Bug
