### ISSUE TITLE
Built-in Google Analytics configuration not recording page title correctly

### ISSUE THREAD

**Issue by bdchin** [ampproject/amphtml#1782] opened 2016-02-04 16:29 UTC
The built-in Google Analytics configuration in https://cdn.ampproject.org/v0/amp-analytics-0.1.js is missing an ampersand before the "dt" parameter:

`basePrefix: "v=1&_v=a0&aip=true&_s=${requestCount}dt=${title} ...`

This causes the title to be sent as part of the _s value instead.

**Comment by rudygalfi** [comment] 2016-02-04 17:10
This is a duplicate of #1778

cc @avimehta

**Closed** 2016-02-04 17:10 UTC
Labels: 3P, Closed: Duplicate, Related to: Analytics, Type: Bug
