### ISSUE TITLE
Expose the entire selected item on the autocomplete select event

### ISSUE THREAD

**Issue by JoyceBabu** [ampproject/amphtml#26525] opened 2020-01-28 19:48 UTC
## Describe the new feature or change to an existing feature you'd like to see

When a select event is fired by an autocomplete component, `event.value` contains the value specified in the `data-value` attribute of the selected item. When the source item was an object, there is no option to get the entire original object.

In the following code example, I want to set the value of the `input[name=state]` hidden field to the `state` property of the selected entry. I tried adding an `on="select: AMP.setState({autocomplete: {state: event.value.state}})"`. Unfortunately, this does not work since the event exposes only the value specified in the `data-value` attribute, which in this case is the city name.

```
<form>
  <amp-autocomplete filter="token-prefix" filter-value="city">
    <input type="search" name="city">
    <input type="hidden" name="state" [value]="autocomplete.state">
    <script type="application/json">
      {
        "items": [
          {
            "city": "Albany",
            "state": "New York"
          }, {
            "city": "Annapolis",
            "state": "Maryland"
          }
        ]
      }
    </script>
    <template type="amp-mustache" id="amp-template-custom">
      <div class="city-item" data-value="{{city}}">
        <div>{{city}}, {{state}}</div>
      </div>
    </template>
  </amp-autocomplete>
</form>
```

## Describe alternatives you've considered

I have worked around this by setting `data-value` to `{{city}}|{{state}}`. And then adding a `select` handler to separate the state by splitting `event.value`.

```
on="select: AMP.setState({autocomplete: {city: event.value.split('|')[0], state:  event.value.split('|')[1]}})"
```

But since this was changing the value of the `input[name=city]` too, I had to add a `[value]` bind for that input. This is a complicated work around, and will not work for advanced use cases. Kindly expose the entire source item on the event.

**Comment by GeneGenie** [comment] 2020-07-31 11:55
Hi, is it still relevant ?

**Comment by caroqliu** [comment] 2020-07-31 13:00
Hi @GeneGenie yes this is still a good feature to add to amp-autocomplete.

**Comment by joaopsrleal** [comment] 2020-10-10 16:38
Hi, I've been looking at this issue and I have a solution that works locally. In the next few days I'll be polishing the code and preparing a PR for this.

@caroqliu could we assign this issue to me in the meantime?

**Closed** 2020-10-26 15:49 UTC
Labels: Component: amp-autocomplete, P2: Soon, Type: DevX, Type: Feature Request, WG: components, good first issue

**Comment by devvercer** [comment] 2020-12-15 11:54
I use the workaround with using the split function but this does not work perfectly.

If the same item is selected again then the input shows the full concatenated value.  I think this is because the auto-complete updates the input value, then executes the on select event, and the event updates the state but because the value does not change (the same option was selected) the bound [value] is not updated.

I also see that even when selecting a difference option, the input is very briefly updated to show the full value in data-value before the setState executes and updates the bound value.  So there is a 'flashing' of the value in the text box.

**Comment by joaopsrleal** [comment] 2020-12-15 22:35
Thanks for reporting this.

What you describe seems to be a different feature request than what was original requested here.

The autocomplete component updates the input value based on the content of the data-value field in the specified template, so overriding the [value] attribute of the may lead to unexpected behavior (like the one you're seeing). What you've described seems to be the reason for what you're experiencing, given that as far as I understand the select event is handled at a later point in time than the input value update.

This happens because the input value is updated on the same frame as the input listener (https://github.com/ampproject/amphtml/blob/fe89f720c60314b6b8353ffc32e57e770f908a50/extensions/amp-autocomplete/0.1/amp-autocomplete.js#L1101) and the setState is executed when the event is handled (possibly a separate frame in some occasions). However, as I mentioned above, overriding the [value] attribute of the main input field seems not to be fully supported right now.

If you'd like to request this to be supported, it may be better to file a different feature request so that it can be properly evaluated.

@caroqliu if I said anything incorrect, please correct me :)

**Comment by devvercer** [comment] 2021-01-03 19:49
The solution of exposing the entire option value will solve this issue because the hack of shoving multiple values into the data-value attribute will not be needed.

I was pointing out that the work around does not work so the impact is actually still quite high.

Additionally, using keyboard shortcuts to select an option sets the entire mangled value in the text input.
