### ISSUE TITLE
Embedded story blocks vertical scrolling

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#29935] opened 2020-08-22 08:53 UTC
To repro

- Embed a story further down into a longer article
- Scroll down
- Try scrolling path the Story while touching the Story

Example page: https://thatwebsiteis.me/archives/web-stories/

Observed: User see the education that they should tap, not scroll

Expected: Page should scroll

How to fix:

- Don't block scrolling when embedded into a page that is much taller than the Story
- Potentially provide for a different user education instead.

**Comment by newmuis** [comment] 2020-08-25 15:03
@Enriqe @raovs I think it would be good for us to figure out which milestone a fix for this should land in

**Comment by Enriqe** [comment] 2020-08-25 15:41
Duplicate of #28009

**Comment by gmajoulet** [comment] 2020-08-26 23:28
Enrique could you either triage or close this one if everything is tracked on #28009?

**Closed** 2020-08-28 18:13 UTC
Labels: P2: Soon, Type: Bug, WG: stories
