### ISSUE TITLE
Error: Tried to add display:none element to FixedLayer

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#17349] opened 2018-08-08 01:07 UTC
Sample stack trace:

```
Error: Tried to add display:none element to FixedLayer AMP-STICKY-AD
    at message (https://raw.githubusercontent.com/ampproject/amphtml/1533168552513/src/log.js:528:22)
    at https://raw.githubusercontent.com/ampproject/amphtml/1533168552513/src/log.js:244:43
    at https://raw.githubusercontent.com/ampproject/amphtml/1533168552513/src/log.js:257:36
    at https://raw.githubusercontent.com/ampproject/amphtml/1533168552513/src/service/storage-impl.js:180:13
    at https://raw.githubusercontent.com/ampproject/amphtml/1533168552513/src/service/viewport/viewport-impl.js:149:4
    at https://raw.githubusercontent.com/ampproject/amphtml/1533168552513/extensions/amp-sticky-ad/1.0/amp-sticky-ad.js:154:13
    at https://raw.githubusercontent.com/ampproject/amphtml/1533168552513/src/focus-history.js:107:4
    at useLayers_ (https://raw.githubusercontent.com/ampproject/amphtml/1533168552513/src/service/viewport/viewport-impl.js:560:8)
    at animateScrollIntoViewInternal_ (https://raw.githubusercontent.com/ampproject/amphtml/1533168552513/src/service/viewport/viewport-impl.js:538:2)
```

Looks like this affects any fixed layers:

- `AMP-STICKY-AD`
- `AMP-USER-NOTIFICATION`
- `AMP-SIDEBAR`

**Comment by erwinmombay** [comment] 2018-08-21 01:26
This issue doesn't have a category which makes it harder for us to keep track of it.  Please add an appropriate category.

**Comment by jridgewell** [comment] 2018-08-27 22:32
Closing as a dupe of https://github.com/ampproject/amphtml/issues/15752.

**Closed by jridgewell** 2018-08-27 22:32 UTC
Labels: Type: Bug
