### ISSUE TITLE
Reloading an AMP carousel site makes the carousel disapear 

### ISSUE THREAD

**Issue by corvusinaloeCMENA** [ampproject/amphtml#5322] opened 2016-09-29 23:47 UTC
When on immersive AMP Carousel mode, reloading an article 
1 In Chrome Go to opt into "pan-y" at https://cdn.ampproject.org/experiments.html (this bug is only available when this flag is turned on)
2 In Chrome Go to opt into the "dev-channel" at https://cdn.ampproject.org/experiments.html
3 Go to www.google.com
4 Search for Hillary Clinton
5. When the AMP Carousel is displayed in the search results page, select one of the AMP articles to go into immersive mode.
6 Switch to landscape mode and reload the article (scroll up until the article is reloaded on AGSA)
7 The amp carousel bar at the top disappears, the user is unable to scroll to other articles. 

Chrome 53.0.27 Samsung Galaxy Note 2 JB
Chrome 53.0.27 Galaxy S6 M
Chrome 53.0.27 Galaxy S5 L
AGSA 6.4.31 Galaxy S6 M
AGSA 6.4.31 LG G5 N
Chrome 53.0.27 LG G5 N
![screenshot_2016-09-29-16-45-09](https://cloud.githubusercontent.com/assets/22305326/18976288/9b50b170-8665-11e6-995e-1f72d89cdac2.png)

**Comment by jpettitt** [comment] 2016-09-30 02:35
This happens on regular (non-experiment) amp searches.  It appears to be a feature.  (Google team can you confirm?)

This is why I think it does that: If you share the amp article using the built in share tools in the browser the URL you share will reload just that article and not your entire search result. 

If it did reload the entire carousel that would be a privacy issue because people would be effectively sharing their search terms.  It would also mean that google would have to save the set of pages for every carousel search indefinitely in case somebody had bookmarked or shared the URL and expected it to reload the same carousel.

The url you get when you reload also has another feature - it redirects to the source (non-amp) page if you open it on a desktop or tablet browser.

**Comment by ericlindley-g** [comment] 2016-10-05 22:08
Closing as the intended behavior.

**Closed by ericlindley-g** 2016-10-05 22:08 UTC
Labels: Related To: Google Search, Type: Question
