### ISSUE TITLE
🐛 Google Analytics 4 Related Bug: Custom Parameters are not getting Tracked Properly

### ISSUE THREAD

**Issue by vivekbudania-girnarsoft** [ampproject/amphtml#39297] opened 2023-07-26 08:12 UTC
### Description

We have implemented GA4 amp tracking by using the below sample code.

&lt;amp-analytics type="gtag" data-credentials="include" class="i-amphtml-layout-fixed i-amphtml-layout-size-defined" style="width:1px;height:1px;" i-amphtml-layout="fixed">

    <script type="application/json">
        {
            "vars" : {
                "gtag_id": "G-XXXXXXXXXX",
                "config" : {
                    "G-XXXXXXXXXX": {
                        "groups":"default",
                        "page_type":"ModelPage.OverviewTab.amp",
                        "oemName":"maruti",
                        "modelName":"maruti invicto"
                    } 
                }
            }
        }
    </script>
&lt;/amp-analytics&gt;

But we are facing issues in tracking custom parameters(modeName in the screenshot) as around 50% is getting tracked correctly, but almost all the data is also getting passed into not set.
It is happening with every custom parameter while Google's default dimension(Page Path + Query String in the screenshot) is tracked properly.

### Reproduction Steps

Go to exploration in GA4, select custom dimension & page path + query string from dimensions and total users from metrics.
Add custom dimension in column, page path + query string in rows and total users in values.
When you filter data from page path + query string contains amp you can see that around 50% is getting tracked correctly, but almost all the data is also getting passed into not set.

**Comment by erwinmombay** [comment] 2023-08-30 21:33
@zikas could you help us out with this one? I'm not sure if theres anything I can look into on our end.

**Comment by zikas** [comment] 2023-09-05 17:46
I don't think we received any reports about getting data half the time. 
I wonder if values for the custom dimensions are supplied from a flaky source? Having a minimal setup on [AMP playground](https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fcomponents%2Famp-analytics&_gl=1*exc6iu*_ga*YW1wLUwwQzA0MXBmbUdWYnBpcjBQYl8zdlE.)  that doesn't send a value would be very helpful.

**Comment by erwinmombay** [comment] 2023-09-07 17:45
@zikas by minimal set up AMP playground, do you mean creating some sort of example that triggers a custom dimensions but doesnt send a value? do you mind creating a config example of that? i can make the change on the amp playground

**Comment by zikas** [comment] 2023-09-07 21:21
Sure, somethign like this [page](https://playground.amp.dev/#share=PCEtLQogICMjIEludHJvZHVjdGlvbgoKVGhlIGBhbXAtYW5hbHl0aWNzYCBlbGVtZW50IGNhbiBiZSB1c2VkIHRvIG1lYXN1cmUgYWN0aXZpdHkgb24gYW4gQU1QIGRvY3VtZW50LiBDdXJyZW50bHksIGBhbXAtYW5hbHl0aWNzYCBzdXBwb3J0cyBkaWZmZXJlbnQga2luZHMgb2YgZXZlbnRzOgoKKiBQYWdldmlldwoqIEFuY2hvciBDbGlja3MKKiBUaW1lcgoqIFNjcm9sbGluZwoqIEFNUCBDYXJvdXNlbCBjaGFuZ2VzCiogRm9ybQoKVGhpcyBzYW1wbGUgZGVtb25zdHJhdGVzIHdoaWNoIGV2ZW50cyBjYW4gYmUgbWVhc3VyZWQgYW5kIGhvdyB0aGV5IGNhbiBiZSBjb25maWd1cmVkLiBGb3IgYSBjb21wbGV0ZSBvdmVydmlldyBvZiBhbGwgYXZhaWxhYmxlIG9wdGlvbnMgYW5kIHBhcmFtZXRlcnMsIGhhdmUgYSBsb29rIGF0IHRoZSBbb2ZmaWNpYWwgZG9jdW1lbnRhdGlvbl0oL2NvbnRlbnQvYW1wLWRldi9kb2N1bWVudGF0aW9uL2NvbXBvbmVudHMvcmVmZXJlbmNlL2FtcC1hbmFseXRpY3MtdjAuMS5tZCkuCi0tPjwhLS0gLS0+CjwhZG9jdHlwZSBodG1sPgo8aHRtbCDimqEgbGFuZz0iZW4iPgo8aGVhZD4KPG1ldGEgY2hhcnNldD0idXRmLTgiPgogICAgPHRpdGxlPmFtcC1hbmFseXRpY3M8L3RpdGxlPgogICAgPHNjcmlwdCBhc3luYyBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwLmpzIj48L3NjcmlwdD4KICAgIDwhLS0gIyMgU2V0dXAgLS0+CiAgICA8IS0tICBJbXBvcnQgdGhlIGBhbXAtYW5hbHl0aWNzYCBjb21wb25lbnQgaW4gdGhlIGhlYWRlci4gLS0+CiAgICA8c2NyaXB0IGFzeW5jIGN1c3RvbS1lbGVtZW50PSJhbXAtYW5hbHl0aWNzIiBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwL2FtcC1hbmFseXRpY3MtMC4xLmpzIj48L3NjcmlwdD4KICAgIDwhLS0KICAgIFdlIG5lZWQgYGFtcC1pZnJhbWVgIHRvIGVtYmVkIGFuIGFuYWx5dGljcyBkYXNoYm9hcmQuCiAgLS0+CiAgICA8bGluayByZWw9ImNhbm9uaWNhbCIgaHJlZj0iaHR0cHM6Ly9hbXAuZGV2L2RvY3VtZW50YXRpb24vZXhhbXBsZXMvY29tcG9uZW50cy9hbXAtYW5hbHl0aWNzL2luZGV4Lmh0bWwiPgogICAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCI+ICAgCiAgCTxzdHlsZSBhbXAtYm9pbGVycGxhdGU+PC9zdHlsZT4KICA8bm9zY3JpcHQ+PHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT4KICAgICAgICBib2R5IHsKICAgICAgICAgIC13ZWJraXQtYW5pbWF0aW9uOiBub25lOwogICAgICAgICAgLW1vei1hbmltYXRpb246IG5vbmU7CiAgICAgICAgICAtbXMtYW5pbWF0aW9uOiBub25lOwogICAgICAgICAgYW5pbWF0aW9uOiBub25lOwogICAgICAgIH0KICAgICAgPC9zdHlsZT48L25vc2NyaXB0PgogIDwvaGVhZD4gIAogIDxib2R5PgogICAKICAKICAgCiAgICA8YW1wLWFuYWx5dGljcyB0eXBlPSJndGFnIiBkYXRhLWNyZWRlbnRpYWxzPSJpbmNsdWRlIj4KICAgICAgPHNjcmlwdCB0eXBlPSJhcHBsaWNhdGlvbi9qc29uIj4KICAgICAgICB7CiAgInZhcnMiOiB7CiAgICAiY29uZmlnIjogewogICAgICAiRy0xMTExIjogewogICAgICAgICJjb2xvciI6ICJncmVlbiIKICAgICAgfSAgICAgIAogICAgfQogIH0sCiAgInRyaWdnZXJzIjogewogICAgImV2ZW50X2xldmVsIjogewogICAgICAib24iOiAidmlzaWJsZSIsCiAgICAgICJ2YXJzIjogewogICAgICAgICJhZ2UiOiAzMCwKICAgICAgICAiY29sb3IiOiAicmVkIiwKICAgICAgICAic2l6ZSI6ICJYTCIsCiAgICAgICAgImV2ZW50X25hbWUiOiAiY29udmVyc2lvbiIsCiAgICAgICAgInNlbmRfdG8iOiBbIkctMTExMSJdCiAgICAgIH0KICAgIH0KICB9Cn0KICAgICAgPC9zY3JpcHQ+CiAgICA8L2FtcC1hbmFseXRpY3M+CiAgCjwvYm9keT48L2h0bWw+). So far I cannot reproduce mentioned problem.

**Comment by erwinmombay** [comment] 2023-10-12 19:10
since this is unable to reproduce, going to close this out. feel free to re-open if there is more information so we can investigate

**Closed by erwinmombay** 2023-10-12 19:10 UTC
Labels: Type: Bug, P1: High Priority, WG: components, Component: amp-analytics, Component: GA4
