### ISSUE TITLE
Event Tracking Google Analytics/amp-analytics not working

### ISSUE THREAD

**Issue by Polylike** [ampproject/amphtml#1744] opened 2016-02-02 20:44 UTC
Hey,

Event Tracking doenst work. Trying Example AMP Page from https://developers.google.com/analytics/devguides/collection/amp-analytics/. Page tracking works fine.

Best regards,
Daniel

**Comment by rudygalfi** [comment] 2016-02-02 21:30
@Polylike Can you be more specific on what you tried and what you've observed?

**Comment by avimehta** [comment] 2016-02-02 21:32
Also, a link or html config for the page that is not working?

**Comment by Polylike** [comment] 2016-02-02 21:49
Hey,  i have created a Example AMP Page like https://developers.google.com/analytics/devguides/collection/amp-analytics/  "The following is an example AMP page with Google Analytics pageview and event tracking."  The pageview tracking works fine, but when i click on the section:  <span id="event-test" class="box">
    Click here to generate an event
  </span>

not event is tracked via realtime reports
"eventCategory": "ui-components",
          "eventAction": "click"

Thanks,
Daniel

**Comment by avimehta** [comment] 2016-02-02 22:26
It looks like there is a bug in the documentation. We'll get that fixed. The values for variables have to be in double quotes. 

```
          "eventCategory": "ui-components",
          "eventAction": "header-click"
```

Let me know if this fixes the issue. We'll fix the documentation soon.

**Comment by rudygalfi** [comment] 2016-02-02 22:53
Closing this here. Google Analytics is tracking the documentation update internally.

**Closed by rudygalfi** 2016-02-02 22:53 UTC
Labels: Related to: Analytics, Repro Needed, Type: Bug

**Comment by rudygalfi** [comment] 2016-02-03 01:27
Documentation seems to be updated now.

**Comment by Polylike** [comment] 2016-02-03 08:00
Hey, it looks like there are a other problem. The problems comes with the tricker. I'm trying this:`"link-trigger":{"on": "click", "selector": "a", "request": "event", "vars":{"eventCategory": "Link", "eventAction": "clicked-link"}},`

Works fine and every click gets tracked correct. 

Trying this:
`"span-trigger":{"on": "click", "selector": "#span-intern", "request": "event", "vars":{"eventCategory": "Span", "eventAction": "clicked-span"}}, `

in combination with this

` <span id="span-intern">
    Click here to generate an event
  </span>`

nothing happend. 

Looks like there is a problem with the "selector": "#span-intern".

**Comment by rudygalfi** [comment] 2016-02-03 18:29
I spun off the new issue into #1761.

**Comment by avimehta** [comment] 2016-02-04 06:57
I just commented on #1761. Not sure if @Polylike is subscribed to that issue. Can you take a look? I tried to reproduce the issue but couldn't. Feel free to update https://jsfiddle.net/1ke6kvdd/1/ with the example that doesn't work and I'll address it.
