### ISSUE TITLE
amp-video doesn't play back

### ISSUE THREAD

**Issue by StebneRuslan** [ampproject/amphtml#22690] opened 2019-06-05 07:16 UTC
Hi. we found a new bug with video. app-video doesn't play back
example story:
https://cutnut-tv.cdn.ampproject.org/c/s/cutnut.tv/amp/67d0152f-dc38-45f7-88b9-8bf5112ea7f2

**Comment by newmuis** [comment] 2019-06-05 13:31
It appears the `display: contents` is causing the issue, though I'm not sure why.  I don't believe this is specific to stories, as it also repros with this minimal reproducible example:

```html
<!doctype html>
<html ⚡>
<head>
  <meta charset="utf-8">
  <title>My AMP Page</title>
  <link rel="canonical" href="self.html" />
  <meta name="viewport" content="width=device-width,minimum-scale=1">
  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <style amp-custom>
    h1 {
      margin: 1rem;
    }
  </style>
</head>
<body>
  <amp-video layout="responsive"
             autoplay
             height=720  width=1280
             noaudio
             poster="https://images-cutnut-tv.cdn.ampproject.org/i/s/images.cutnut.tv/l9jAZzjmy3c1QvEey5GdXQMuAxU=/smart/cuts/860aa5bb-48a0-45f5-954b-f4e7e0e8911b/layers/e125c741-a33a-4f4c-b0c8-6e5be2c8d35b/e9910bab-b956-407e-a011-26999b175c7e.png"
             style="display: contents; box-shadow:0px 0px 0px 0px rgba(0,0,0,0.75); opacity: 1;">
    <source src=https://media.cutnut.tv/cuts/860aa5bb-48a0-45f5-954b-f4e7e0e8911b/layers/e125c741-a33a-4f4c-b0c8-6e5be2c8d35b/1c17f7d1-5477-4131-8eb6-4d0b693cfbf8.mp4 type=video/mp4>
    <div fallback>
      <p>This browser does not support the vide o element.</p>
    </div>
  </amp-video>
</body>
</html>
```

**Comment by newmuis** [comment] 2019-06-05 13:33
Triaging to @aghassemi; feel free to reassign!

**Comment by aghassemi** [comment] 2019-06-05 13:39
`display:contents` makes the element disappear per spec and won't work for any `amp-element`. @StebneRuslan please remove it and things should work. If there is use-case that is being solved by display:content, please let us know so we can explore alternatives.

**Closed by aghassemi** 2019-06-05 13:39 UTC
Labels: Category: Audio&Video, Type: Bug

**Comment by ithinkihaveacat** [comment] 2019-06-05 15:03
Is the `display: contents` limitation documented anywhere? The [Supported CSS](https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/style_pages) page doesn't mention it, and it validates and runs without emitting any console warnings.

**Comment by aghassemi** [comment] 2019-06-05 15:08
It's not really a limitation of AMP per say, `display: content` is effectively a `parent: display:none, children: display: block` feature in CSS. I agree it would be nice to document however.

**Comment by aghassemi** [comment] 2019-06-05 15:14
to @alanorozco I think the issue is that `isTrackingIframe` for `amp-video-iframe` runs in `buildCallback` which might be too early as it may race with layout of parents that are container like carousel. `onLayoutMeasure` might be the right place for that check.
