### ISSUE TITLE
Background-audio does only work for 8 pages

### ISSUE THREAD

**Issue by Refurb** [ampproject/amphtml#14624] opened 2018-04-14 13:04 UTC
## What's the issue?

I'm using background-audio in Google AMP Story, it's doing fine in the first 8 pages. But from page 9 it doesn't work anymore.

## How do we reproduce the issue?

Create 9 pages, all with background-audio

## What browsers are affected?

All

## Which AMP version is affected?

1523662348051 

## Note
Is there any other thing I can do? Looks like amp-audio doesn't work too. I was using AMP for a school project and I need audio with all pages. Thanks in advance.

**Comment by newmuis** [comment] 2018-04-16 03:07
Thanks for the report @Refurb!  To clarify, are you using the `background-audio` attribute on the `<amp-story>` element?  Or on multiple different `<amp-story-page>` elements?

**Comment by Refurb** [comment] 2018-04-16 06:06
Multiple amp-story-pages.
All different mp3's. And from amp-story-page #9 the mp3's stop working.

Any idea? :-)

**Comment by newmuis** [comment] 2018-04-16 14:17
This seems like a duplicate of #13476; I will migrate the conversation there.

**Closed by newmuis** 2018-04-16 14:17 UTC
Labels: Category: AMP Story, P2: Soon, Type: Bug
