### ISSUE TITLE
amp-story-bookend - Error fetching bookend configuration Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by bpaduch** [ampproject/amphtml#15669] opened 2018-05-30 18:22 UTC
When I load the bookend I receive the following error in the console:

```
log.js:164 Error fetching bookend configuration Cannot read property 'push' of undefined
```

<img width="450" alt="screen shot 2018-05-30 at 2 05 20 pm" src="https://user-images.githubusercontent.com/1012254/40739623-b06d9274-6414-11e8-9d79-9a0157747815.png">

Tested on Linux and Mac
Sample here: https://bpaduch.github.io/stamp/amp-pets-story-1-0/pets-completed.html 

To resolve:
Need to enable the dev-channel experiment on https://cdn.ampproject.org/experiments.html and reload
(reloading with cmd+shift+R to clear cache).

**Comment by Enriqe** [comment] 2018-05-31 20:03
Since canary was patched I was not able to reproduce or further investigate the issue. But I will keep an eye out if this pops up again.

**Comment by newmuis** [comment] 2018-06-01 19:03
Closing this since it's not present in new builds.

**Comment by Enriqe** [comment] 2018-06-21 21:48
Got this error again when an invalid `component-type` is described in the bookend config. I will be sending a PR shortly to throw a better error.

**Closed** 2018-06-22 21:20 UTC
Labels: Category: AMP Story, P1: High Priority, Type: Bug
