### ISSUE TITLE
Validator: Support "skype:" and other custom protocols

### ISSUE THREAD

**Issue by pbakaus** [ampproject/amphtml#4242] opened 2016-07-27 19:02 UTC
```
<a href="skype:username?call" target="_blank" title="Skype" class="social-icon social-icon-skype"></a>
```

Is a link appearing on many pages (including mine), and the validator doesn't like it.

**Comment by Gregable** [comment] 2016-07-27 19:51
Dupe of https://github.com/ampproject/amphtml/issues/4094 . The fix is in but not yet made it to release.

**Closed by Gregable** 2016-07-27 19:51 UTC
Labels: Type: Request

**Comment by pbakaus** [comment] 2016-07-27 20:42
Ah great thanks!
