### ISSUE TITLE
Getting redirect notice when clicking on the amp URL in the search results.

### ISSUE THREAD

**Issue by CW-prabhupuredla** [ampproject/amphtml#24726] opened 2019-09-25 05:41 UTC
We have implemented signed exchange to show our domain URL in the browser. When I clicked on amp URL in the google search results, redirect notice is being shown every time. Please refer to the image:
![bikewale redirect notice](https://user-images.githubusercontent.com/35324834/65572102-9df0ec80-df84-11e9-9774-ec4a773483f3.PNG)

I checked amp.dev website which is implemented using signed exchanges, I see the same behaviour as in the below image
![ampdev redirect notice](https://user-images.githubusercontent.com/35324834/65572016-5f5b3200-df84-11e9-8bc8-94cb3ec59a2f.PNG)

I am not able to able to replicate the same in other machines

chrome browser version: Version 77.0.3865.90

**Comment by timesalert** [comment] 2019-09-29 14:22
I have also faced same issue after updating latest version amp on My site [https://timesalert.com](timesalert). I have roll backed with old version now issue is resolved

**Comment by nainar** [comment] 2019-10-01 05:50
cc @Gregable

**Comment by Gregable** [comment] 2019-10-01 20:53
```
$ curl -s -H 'AMP-Cache-Transform: google;v=1..2' -H 'Accept: application/signed-exchange;v=b3' https://www.bikewale.com/m/royalenfield-bikes/classic-350/amp/
```

Your site does not appear to respond with a signed exchange when provided with appropriate request headers.

The redirect notice doesn't appear to come from the AMP Cache, but I'd need more information on how to reproduce to debug further.

**Comment by Gregable** [comment] 2019-10-01 20:54
@timesalert If you could provide more information, I'd also be happy to debug further.

**Comment by CW-prabhupuredla** [comment] 2019-10-03 11:18
@Gregable It is happening in only few specific devices. I have seen the redirect notice in `Pixel 2 XL`. We have reverted amp signed exchange since we don't how many users are being shown the redirect notice.

**Comment by cw-ashutoshsharma** [comment] 2019-10-04 06:20
@Gregable I am working with @CW-prabhupuredla on this.
We have reverted amp signed exchange for our amp pages cause of the steep decline in crawled pages from google (We checked the crawl stats on google search console, there were no crawl errors reported.).  The number of crawled pages went down to 120k from 500k per day. It came back to normal after reverting.

We were using amppackager to serve singed exchange.

You can follow our staging URL https://staging.bikewale.com/m/royalenfield-bikes/classic-350/amp/

**Comment by cw-ashutoshsharma** [comment] 2019-10-04 06:37
Thanks @Gregable 
I am working with @CW-prabhupuredla on this.
We have reverted amp signed exchange for our amp pages cause of the steep decline in crawled pages from google (We checked the crawl stats on google search console, there were no crawl errors reported.). The number of crawled pages went down to 120k from 500k per day. It came back to normal after reverting.

We were using amppackager to serve singed exchange.

You can follow our staging URL https://staging.bikewale.com/m/royalenfield-bikes/classic-350/amp/
to get a response with singed exchange

Also `amp-cahce-transform header` value would be `google;v="1..2"` (quotaions)

`$ curl -s -H 'AMP-Cache-Transform: google;v="1..2"' -H 'Accept: application/signed-exchange;v=b3' https://staging.bikewale.com/m/royalenfield-bikes/classic-350/amp/ -I`

**Comment by alef-media** [comment] 2019-11-06 12:12
@Gregable
Every browser in mobile (android one) behave differently.
Chrome: redirect notice.
Firefox: google cache
Opera: direct

**Comment by alef-media** [comment] 2019-11-06 17:14
> @Gregable
> Every browser in mobile (android one) behave differently.
> Chrome: redirect notice.
> Firefox: google cache
> Opera: direct

Strange, I have two mobile (android one) both them are have same version of Chrome the redirect notice appear only with Moto One Vision, the second one has no issue.

Moto One Vision
Chrome V: 78.0.3904.90
Android V: PSAS.29.160-50-2

Moto One:
Chrome V: 78.0.3904.90
Android V: PPKS29.68-16-36-9

**Comment by Gregable** [comment] 2019-11-06 18:02
@alef-media, is this for the same URL that @CW-prabhupuredla was reporting, or a different one?

I've still been unable to reproduce this which makes it difficult to debug. It seems like the previous URL is no longer showing this issue. If you don't want to share the URL, feel free to send me a direct message on Slack.

**Comment by alef-media** [comment] 2019-11-06 19:47
> @alef-media, is this for the same URL that @CW-prabhupuredla was reporting, or a different one?
> 
> I've still been unable to reproduce this which makes it difficult to debug. It seems like the previous URL is no longer showing this issue. If you don't want to share the URL, feel free to send me a direct message on Slack.

Hi @Gregable
![WhatsApp Image 2019-11-06 at 10 25 40 PM (1)](https://user-images.githubusercontent.com/47991689/68331738-8d38a800-00e6-11ea-9f58-a41bbf8e1f84.jpeg)
![WhatsApp Image 2019-11-06 at 10 25 40 PM](https://user-images.githubusercontent.com/47991689/68331752-91fd5c00-00e6-11ea-8a15-8b54080a8904.jpeg)

It seem all amp website with signed exchange show this notice. I saw these on any link under amp.dev and goat.com.au

**Comment by ericfs** [comment] 2019-11-07 01:02
Can you share the full google.com/url you're seeing?

**Comment by ericfs** [comment] 2019-11-07 01:07
Filed internal b/144048906

**Comment by alef-media** [comment] 2019-11-07 10:01
https://www.google.com/url?sa=t&source=web&cd=1&ved=2ahUKEwiW5KqrutXlAhXS4IUKHWe0DgYQFjAAegQICBAC&url=https%3A%2F%2Famp-dev.cdn.ampproject.org%2Fwp%2Fs%2Famp.dev%2F%3Fusqp%3Dmq331AQOKAGYAZPouYLWzsH_jgE%253D&usg=AOvVaw0PSRdfK6IyWpiVMjRT9EDr


https://www.google.com/url?sa=t&source=web&cd=1&ved=2ahUKEwjWxq7L69flAhUSXRoKHZwrCMoQFjAAegQIARAB&url=https%3A%2F%2Fgoat-com-au.cdn.ampproject.org%2Fwp%2Fs%2Fgoat.com.au%2F%3Fusqp%3Dmq331AQNKAGYAfST3aXWv4DpEA%253D%253D&usg=AOvVaw3bRe9adfLXkR-EBS3shi6z

**Comment by ericfs** [comment] 2019-11-07 13:34
Thank you for sharing the links. We're investigating.

**Comment by ericfs** [comment] 2019-11-07 22:48
Does this reproduce in an incognito window?

**Comment by alef-media** [comment] 2019-11-09 14:46
You are welcome,
I just tested with incognito window, there is no redirect notice for both websites apm.dev and goat.com.au

**Comment by ericfs** [comment] 2019-11-11 16:56
Thanks. We haven't figured out the specific cause, but this is a great clue. It seems to be related to some small experiment.

**Comment by ericfs** [comment] 2019-11-14 15:21
This should be fixed now. Thanks again. for the report and the help debugging.

**Comment by alef-media** [comment] 2019-11-18 15:47
Yes It is fixed. You are welcome.

**Comment by ericfs** [comment] 2019-11-18 16:05
Great. @Gregable or someone else, can you please close? I don't have permission. Thank you.

**Closed** 2019-11-18 16:42 UTC
Labels: Type: Bug, WG: caching
