### ISSUE TITLE
[amp-story] Thirds layout broken in Safari

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#19379] opened 2018-11-19 14:50 UTC
...see this page: https://ampbyexample.com/stories/features/layouts/#thirds

<img width="926" alt="screenshot 2018-11-19 at 15 48 29" src="https://user-images.githubusercontent.com/380472/48714275-a2d16b00-ec12-11e8-8b6f-a85ac6aaa22e.png">

Broken Desktop (Version 12.0.1 (14606.2.104.1.1)) & mobile Safari. Works in Chrome.

//cc @newmuis

**Comment by newmuis** [comment] 2018-11-19 16:51
Duplicate of #13433

**Closed by newmuis** 2018-11-19 16:51 UTC
