### ISSUE TITLE
How to Show responsive Ad with Adsense

### ISSUE THREAD

**Issue by gkteck** [ampproject/amphtml#2218] opened 2016-02-23 12:22 UTC
Need to show responsive ads to be displayed on mobile.
Does amp-ad supports  data-ad-format="auto" ?

**Comment by luixxiul** [comment] 2016-02-25 08:15
See: https://github.com/ampproject/amphtml/pull/1851

**Comment by gkteck** [comment] 2016-02-26 09:18
is this fix available ?

The only adsense example I can see is
 <h2>AdSense</h2>
  <amp-ad width=300 height=200
      type="adsense"
      data-ad-client="ca-pub-8125901705757971"
      data-ad-slot="7783467241">
  </amp-ad>

**Comment by rudygalfi** [comment] 2016-03-24 04:20
Closing, as this is a duplicate of #1851.

**Closed** 2016-03-24 04:20 UTC
Labels: Related to: Ads
