### ISSUE TITLE
Opt out of AMP cache for clients that don’t support Signed Exchanges

### ISSUE THREAD

**Issue by DuncanMacWeb** [ampproject/amphtml#22287] opened 2019-05-14 18:06 UTC
Is there any way for publishers who wish to benefit from AMP caches where possible, but need their users to only ever see the **original** URLs of their content, and **never** the [AMP cache or AMP viewer URLs](https://blog.amp.dev/2017/02/06/whats-in-an-amp-url/), to **opt out** of AMP caches serving their content to clients which _do not_ support [Signed Exchanges](https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/signed-exchange?format=websites), yet still benefit from the AMP cache on supporting browsers? If this feature does not exist at present, could it be added?

This should result in **all** users seeing the original URL, with the content served from AMP cache to clients which _do_ support Signed Exchanges/SXG (known as [AMP Real URL](https://blog.cloudflare.com/announcing-amp-real-url/) on Cloudflare). Thus users on supporting browsers would benefit from the AMP cache’s near-instant loading experience but still see the content’s original URL and no AMP viewer URL bar. Users on browsers which _do not_ support Signed Exchanges would **also** see the original URL (as they would be viewing the content from its origin), though in consequence they would experience a somewhat longer load time.

This would help content publishers who need to prioritise publishing and serving their content exclusively from their own domain to adopt AMP by eliminating one of the most obvious drawbacks of the AMP caches.

**Comment by torch2424** [comment] 2019-05-15 01:17
Triaging to @Gregable , feel free to re-assign 😄

**Comment by Gregable** [comment] 2019-05-15 15:58
Hi Duncan,

There is currently no way to indicate that an AMP document should only presented to browsers that accept signed exchanges. 

It's an interesting idea. I think you may be the first to raise it. It's somewhat outside the scope of the AMP Project itself, and is rather a specific feature request for an AMP Cache product. As such, I've filed a matching Google AMP Cache issue to track and will give you updates here. Tracked separately as 132777519. 

If it's something we want to implement, the AMP Project should propose a specific syntax for the publisher to indicate this decision.

Mind if I ask if this is this a speculative question, or if there is a specific use case in mind for you or another publisher? Specific use cases may help motivate developing the feature.

**Comment by DuncanMacWeb** [comment] 2019-05-16 19:18
Hi Greg, thank you for filing that issue, it’s appreciated. Unfortunately I’m not able to go into details about the use case at this time I’m afraid, but hopefully the idea is clear.

**Comment by Gregable** [comment] 2020-08-25 17:27
Dupe of https://github.com/ampproject/amphtml/issues/27011

**Closed by Gregable** 2020-08-25 17:27 UTC
Labels: Type: Feature Request, WG: caching
