### ISSUE TITLE
amp-story: Wrong page transition on back (desktop)

### ISSUE THREAD

**Issue by hongwei1990** [ampproject/amphtml#12227] opened 2017-11-28 18:06 UTC
**Please only file bugs/feature requests for AMP here.**

## What's the issue?

Page transition looked wrong when click to go back. The left page gets dropped instead of fading out. 
But the transition looked perfect if the story is doing auto-advancing.

## How do we reproduce the issue?
instead of drooping off the left page just fade it out. 

cc: @alanorozco @newmuis @choumx @prateekbh

**Comment by alanorozco** [comment] 2017-12-05 17:26
This is possibly caused by how we hide pages to force the runtime to pause/resume the component. They get re-positioned to be N viewports below the fold so that the resource will not be scheduled. We should either:

A. Do a two-step transition: 1. Page slides to the left, out of view. 2. Page moves to below the viewport (not visible).

B. Disable transition when page has to go out of view.

Option B is the easiest but will look jumpy.

**Comment by prateekbh** [comment] 2018-01-08 19:23
@alanorozco can u confirm this was fixed by one of ur PRs and can be closed now

**Closed** 2018-01-12 18:07 UTC
Labels: Category: AMP Story, P3: When Possible, Type: Bug
