### ISSUE TITLE
`amp-story` visual tests are flaky due to moving "Share" button

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#19890] opened 2018-12-14 17:59 UTC
See https://percy.io/ampproject/amphtml/builds/1260087 for example. From what I've noticed, the "Share" button goes back and forth between the two positions across different builds.

Assigning to folks on the stories team to triage.

/cc @danielrozenberg

**Comment by rsimha** [comment] 2018-12-20 19:13
@newmuis @Enriqe Still seeing flakiness with other tests, like `amp-story: sidebar`

https://percy.io/ampproject/amphtml/builds/1276401

/cc @danielrozenberg

**Comment by newmuis** [comment] 2018-12-20 19:51
Yep, those tests are new.

Instead of disabling every perfectly good test that is broken by this feature, I will try to disable this feature in all of those tests.

**Comment by danielrozenberg** [comment] 2018-12-20 19:55
Any ideas why this keeps shifting up and down between tests?

**Comment by newmuis** [comment] 2018-12-20 20:01
No 😦   That's the real fix, but we haven't been able to track that down or reproduce it in a real browser.

**Comment by newmuis** [comment] 2018-12-20 20:12
It should be noted that there was a similar issue that I (supposedly) fixed in #17378.

If you look at [the old diff](https://percy.io/ampproject/amphtml/builds/894594/view/52499859/1440?browser=firefox&mode=diff) vs. [the new diff](https://percy.io/ampproject/amphtml/builds/1260087/view/81168191/1440?mode=diff&browser=firefox&snapshot=81168191), it looks like the old one shows the entire button moving, whereas the new one shows just the label moving.

One thing that we could potentially try is also waiting for the label element.

**Comment by newmuis** [comment] 2018-12-20 20:17
Nevermind -- we tried that on some of the other tests, and they were still flaky 😢

**Closed** 2018-12-20 22:50 UTC
Labels: Related to: Flaky Tests, Type: Bug
