### ISSUE TITLE
Define rules for AMP embedding in Web Views

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#2826] opened 2016-04-06 18:25 UTC
Require a connecting iframe or webview to specify either `viewer` or `viewerUrl`. Also make it logged in error.js. Currently both are done for `viewerUrl`. `viewer` should work the same and fallback to `viewerUrl` origin if not specified.

**Comment by rudygalfi** [comment] 2016-04-13 23:28
Rolling this forward into next milestone.

**Comment by ericlindley-g** [comment] 2016-04-29 23:02
Rolling into the next milestone

**Comment by chenshay** [comment] 2017-03-27 17:46
duplicate of https://github.com/ampproject/amphtml/issues/6066

**Closed by chenshay** 2017-03-27 17:46 UTC
Labels: Category: Viewer, Closed: Duplicate, P1: High Priority, Type: Feature Request
