### ISSUE TITLE
Error: Signing service error for google: Failed to import key 

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#12014] opened 2017-11-10 19:18 UTC
Error: Signing service error for google: Failed to import key ({"alg":"RS256","e":"AQAB","ext":true,"kid":"1","kty":"RSA","n":"z43rjaJ9PLk1FHMEL31_ILXGtUTN03rxJ9amD9y3BRDpbTA-GkUKiQM07xAd8OXPUZRqcjvXQfc7b1RCEtwrcfx9oBRdF78QMA4tLLCqSHP0tSuqYF0fA7-GyTFWDcYzey90jRFNNWxjzKrvSazacE0TvJ8S_AVP4EV67VdbByCC1tpBzLhhy7RFHp2cXGTpWYUqZUAVUdJoeBuCho_zQz2au7c6sDaLiF-uYL9Td9MrZ6tSLo3MeMIZia4WgWqjTDICR0h-zlbHUd0K9CoXbGTt5nvkebXHmbKd99ma6zRYVlYNJTuSqsRCBNYtCTFVHIZeBlkjHKsQ46HTZPexZw"}): The requested operation is unsupported
    at Error (https://raw.githubusercontent.com/ampproject/amphtml/1510180045130/src/log.js:490:16)
    at apply (https://raw.githubusercontent.com/ampproject/amphtml/1510180045130/src/log.js:220:20)
    at apply (https://raw.githubusercontent.com/ampproject/amphtml/1510180045130/src/log.js:234:18)
    at error (https://raw.githubusercontent.com/ampproject/amphtml/1510180045130/extensions/amp-a4a/0.1/signature-verifier.js:409:2)
    at signingServiceError (https://raw.githubusercontent.com/ampproject/amphtml/1510180045130/extensions/amp-a4a/0.1/signature-verifier.js:364:34)

**Comment by jridgewell** [comment] 2017-11-10 21:11
Dupe of https://github.com/ampproject/amphtml/issues/6676.

**Comment by taymonbeal** [comment] 2017-11-10 21:11
Duplicate of #6676. We thought this was a new error in the latest canary, but it turned out to have been going on all along and simply masked in our server-side logging by the GET length limit.

**Comment by lannka** [comment] 2018-03-06 20:44
Still seeing this errors a lot (8k per day):

```
Error: Signing service error for google: Failed to import key ({"alg":"RS256","e":"AQAB","ext":true,"kid":"1","kty":"RSA","n":"z43rjaJ9PLk1FHMEL31_ILXGtUTN03rxJ9amD9y3BRDpbTA-GkUKiQM07xAd8OXPUZRqcjvXQfc7b1RCEtwrcfx9oBRdF78QMA4tLLCqSHP0tSuqYF0fA7-GyTFWDcYzey90jRFNNWxjzKrvSazacE0TvJ8S_AVP4EV67VdbByCC1tpBzLhhy7RFHp2cXGTpWYUqZUAVUdJoeBuCho_zQz2au7c6sDaLiF-uYL9Td9MrZ6tSLo3MeMIZia4WgWqjTDICR0h-zlbHUd0K9CoXbGTt5nvkebXHmbKd99ma6zRYVlYNJTuSqsRCBNYtCTFVHIZeBlkjHKsQ46HTZPexZw"}): The requested operation is unsupported
at Error (https://raw.githubusercontent.com/ampproject/amphtml/1518049180919/src/log.js:504)
at apply (https://raw.githubusercontent.com/ampproject/amphtml/1518049180919/src/log.js:219)
at apply (https://raw.githubusercontent.com/ampproject/amphtml/1518049180919/src/log.js:233)
at error (https://raw.githubusercontent.com/ampproject/amphtml/1518049180919/extensions/amp-a4a/0.1/signature-verifier.js:409)
at signingServiceError(https://raw.githubusercontent.com/ampproject/amphtml/1518049180919/extensions/amp-a4a/0.1/signature-verifier.js:364)
```

**Comment by taymonbeal** [comment] 2018-03-06 20:47
Same set of User-Agents as before?

**Comment by taymonbeal** [comment] 2018-03-06 20:48
Also this is still a duplicate of #6676.

**Closed by taymonbeal** 2018-03-06 20:48 UTC
Labels: Closed: Duplicate, P0: Drop Everything
