### ISSUE TITLE
inabox ads bring down Lighthouse score 

### ISSUE THREAD

**Issue by leoramosgomes** [ampproject/amphtml#25509] opened 2019-11-08 18:59 UTC
Olá,

Após realizar uma auditoria do LightHouse em meu site, encontrei uma lentidão muito grande ao carregar nos anúncios veiculados pelo o google, pois alguns anúncios foram construídos usando o AMP.

Aparentemente os .js do https://amp.dev/ (plataforma para criar anúncios responsivos em html) está demorando para ser carregadas, diminuindo assim a performance do meu site.

Parte do relatório abaixo:

Reduzir o impacto do código de  terceiros - O código de terceiros bloqueou o encadeamento principal por 2.010 ms

Tempo de bloqueio do thread principal
AMP - 155 KB - 1.085 ms
	
URL						     Tempo total de CPU	       Avaliação de Script		
… 011… / amp4ads-v0.js(cdn.ampproject.org) 	1.945 ms 		1.668 ms

**Comment by ssantosms** [comment] 2019-11-08 20:02
Qual o site?
What's the website?

É um site AMP?
Is it an AMP website?

Pode dar mais detalhes?
Can you give more details?

**Comment by nainar** [comment] 2019-11-08 20:56
@lannka could you take a look?

cc @cathyxz

**Comment by cathyxz** [comment] 2019-11-14 23:59
I'll to paste the output from Google Translat-ing this issue here for clarity, since I imagine not everyone on the team understands the original: 

> Hello,
After auditing LightHouse on my site, I found it was very slow to load on ads served by google as some ads were built using AMP.
Apparently the .js from https://amp.dev/ (platform for creating responsive html ads) is taking a long time to load, thus slowing down the performance of my site.
Part of the report below:
Reduce third-party code impact - Third-party code has blocked the main thread for 2010 ms
Main thread lock time
AMP - 155 KB - 1,085 ms
URL Total CPU Time Script Rating
… 011… / amp4ads-v0.js (cdn.ampproject.org) 1,945 ms 1,668 ms

**Comment by powerivq** [comment] 2019-11-16 00:26
Hi.

I assume this is on a non-amp page. Ads are loaded asynchronously, so the performance shouldn't take a hit. Is it your concern that the Lighthouse score is lower because of in-a-box ads, or is it the performance is worse?

**Comment by piotr-galas** [comment] 2019-11-20 21:43
Based on the translation I assumed that the problem is a lower score on the lighthouse.

See my picture below.

![img](https://p48.f4.n0.cdn.getcloudapp.com/items/KouQozle/Screenshot-2019-11-20T21%3A38%3A08.665Z.png?v=1861cb8e748e6c8ecf601f921e0aa4c0)

I am investigate how to fix it because I believe that it has big impact on SEO.

Here is similar question from https://stackoverflow.com/questions/58810097/amp-blocking-the-main-thread.

Is somebody can advice how to fix is I would be grateful :pray:

**Comment by lannka** [comment] 2019-11-25 17:13
@piotr-galas we will take a closer look. thanks for the extra info.

**Comment by morsssss** [comment] 2019-12-23 20:19
@powerivq this sounds just like what we were hearing about in Warsaw from ceneo.pl.

I can ask Piotr to include their data in this issue.

**Comment by morsssss** [comment] 2020-02-28 17:06
Update: people are discussing this...

If you're looking for a solution, please follow this issue!

**Comment by powerivq** [comment] 2020-03-13 18:51
Hi,

We have looked at this with the lighthouse team. For your specific question, AMP ads loads faster, and therefore earns more revenue, because it is loaded on a friendly iframe. The drawback is that lighthouse would have counted it as content and drag down the score a bit.

Forcing all ads in a cross domain iframe would solve the score issue, but the ads load slower and your earning potential is reduced. To do this, see https://support.google.com/admanager/answer/9342115. In the last paragraph, it says you can use `setForceSafeFrame` to force this behavior.

We are doing some other performance benchmarking concurrently. Nevertheless, I am wondering why you have a 1s execution time. Can you provide a link to an example?

**Comment by piotr-galas** [comment] 2020-03-13 19:59
@powerivq 
>  Can you provide a link to an example?

I am not sure if you are asking me or @leoramosgomes 


Since I commented issue I did a lot of improvement on the page. Mostly I reduced CSS from 1,5MB to about 500Kb  so now it looks good in my site.
The site is https://estimoto.pl/

![Selection_051](https://user-images.githubusercontent.com/6728577/76655388-6fd08a80-656d-11ea-946d-8c2f6c78e78a.png)

**Comment by powerivq** [comment] 2020-06-02 12:37
@piotr-galas Look like your problem is subsidized, so I am closing this issue for now. Please see my comment on Mar 13 for a solution to the problem raised here.

If anyone still has unresolved problem related, feel free to reopen.

**Closed by powerivq** 2020-06-02 12:37 UTC
Labels: P2: Soon, Type: Bug, WG: ads
