### ISSUE TITLE
amp-story-player fails to render story

### ISSUE THREAD

**Issue by cpauwels** [ampproject/amphtml#30783] opened 2020-10-21 08:11 UTC
## What's the issue?

The amp-story-player fails to render the story. The error mentioned is 
```
error.js:207 Render timeout waiting for service amp-story-render to be ready.​​​
of @ error.js:207
log.js:727 Uncaught Error: Render timeout waiting for service amp-story-render to be ready.​​​
    at gb (log.js:710)
    at ab.f.createError (log.js:359)
    at timer-impl.js:142
    at timer-impl.js:83
```

## How do we reproduce the issue?

Use the amp-story-player on a page. [Here's an example.](https://stories.sincere-chariot.link/test-1)

## What browsers are affected?

Confirmed failing in Chrome, Firefox and Safari.

## Which AMP version is affected?

Latest player release.

**Comment by rnkimani** [comment] 2020-10-21 10:44
@Enriqe

**Comment by Enriqe** [comment] 2020-10-21 14:22
Taking a look

**Comment by Enriqe** [comment] 2020-10-21 14:48
We're going to rollback the latest AMP prod release.

**Comment by Enriqe** [comment] 2020-10-21 14:57
Can I get approval from @gmajoulet or @cramforce for an AMP production release rollback?

**Comment by Enriqe** [comment] 2020-10-21 15:08
Rollback is in progress. Should be live soon.

**Comment by yuliialunova** [comment] 2020-10-21 15:23
@Enriqe still see an error 
log.js:727 Uncaught Error: Render timeout waiting for service amp-story-render to be ready.​​​
    at gb (log.js:710)
    at ab.f.createError (log.js:359)
    at timer-impl.js:142
    at timer-impl.js:83

**Comment by cramforce** [comment] 2020-10-21 16:01
Verified fixed on https://www.industrialempathy.com/new-on-the-web/

Note, that the change is still rolling out through data centers around the world, and it'll take another roughly 40 minutes to complete. Right now it is still heavily flapping.

@Enriqe Please provide a full post-mortem. We need to ensure that there is proper automated and manual test coverage before the next release. CC @rsimha

**Comment by gmajoulet** [comment] 2020-10-21 16:26
The fact that the story didn't render makes me think it might be a Story iframe position/size issue. A story height of 0px would produce this error. Given we've changed the DOM tree that could be what's causing the issue.

**Comment by Enriqe** [comment] 2020-10-21 20:09
The issue was caused by the introduction of an intermediate element in #30433.

Introducing a new element between the `<amp-story-player>` and the Shadow DOM was meant to fix the responsive behavior in the AMP version of the player. The problem was that I mistakenly added the styles for this intermediate element in our stylesheets for the shadow DOM, not for the light DOM. And because this element is not part of the shadow DOM, it wasn't getting any `height`.

We didn't catch this during manual / QA testing because we were using documents without the `<!DOCTYPE html>` tag, which switches from [quirks mode to standards mode](https://stackoverflow.com/questions/1966300/height-100-is-not-working-in-html-when-using-doctype). In standards mode, the `html` and `body` elements do not default to 100%, but in quirks mode they do. By testing in quirks mode, the intermediate element was actually getting 100% height, which was making it look like it worked properly.

I will update all of our samples to use the `<!DOCTYPE html>` tag. And I will also follow up with integration tests that test different layouts / sizes of the player. 

Very sorry for the inconvenience that this may have caused.

**Comment by cramforce** [comment] 2020-10-21 20:22
Wow, good catch on that quirks mode issue!!

**Closed** 2020-10-21 21:03 UTC
Labels: P0: Drop Everything, Type: Bug
