### ISSUE TITLE
Navigating to AMP-enabled sites on IE/Edge adds "undefined" to the url

### ISSUE THREAD

**Issue by petetnt** [ampproject/amphtml#743] opened 2015-10-24 16:40 UTC
Steps to reproduce:

1. Navigate to https://ampproject.org/ 
2. After loading the page the url / `document.location.href` is now https://ampproject.org/undefined

Tested on Edge, IE11, Windows Phone 8.1 IE11.

This creates some unwanted effects, such as reloading leading to a 404 page.

**Comment by erwinmombay** [comment] 2015-10-24 19:42
thanks for reporting! will take a look

**Comment by erwinmombay** [comment] 2015-10-25 06:13
@petetnt confirmed. ANY amp page right now seems to trigger a url change to /undefined

/cc @cramforce @dvoytenko

**Comment by erwinmombay** [comment] 2015-10-25 09:35
looks like this is caused by https://github.com/ampproject/amphtml/blob/master/src/history.js#L285 (call to the browsers native replace state). unsure yet *why* it's happening

**Comment by erwinmombay** [comment] 2015-10-25 09:54
looks like passing in `undefined` as the `url` (3rd argument), even though its marked as [optional](https://msdn.microsoft.com/en-us/library/hh771932(v=vs.85).aspx), really screws it up. not passing in `undefined` fixes the issue.

**Comment by petetnt** [comment] 2015-10-25 11:32
@erwinmombay cool, I though it could be something that affected all the AMP sites but didn't have the time to check yesterday :+1: 

I noticed something else too: it coerces Booleans to strings too so `replaceState({foo: "bar"}, foo, true})` results in `foo.org/true` :ghost: 

It's not AMP's job to work around browser bugs, but I guess all of those kinds of weird behaviors (like someone accidentally passing `true/false` as an `opt_url` could be avoided by extending https://github.com/ampproject/amphtml/pull/746/files#diff-6d1071e9a4a9346d2d306a79be2de0d1R287 with:

```
if (opt_url && typeof opt_url === "string") {
```

**Comment by erwinmombay** [comment] 2015-10-25 14:37
@petetnt thanks. that scenario should be caught once we get the closure compiler running so the only things that should come through as `opt_url` is of type `{string|undefined}` (on that cause i'll probably change my code to only check for `undefined`)

**Comment by petetnt** [comment] 2015-10-25 15:11
Sounds good to me :+1:

**Comment by erwinmombay** [comment] 2015-10-25 16:03
landed in https://github.com/ampproject/amphtml/commit/f268934d346bd15a59f7eb38902e82f39b5fa3cc 

thanks again @petetnt!

**Closed by erwinmombay** 2015-10-25 16:03 UTC
Labels: bug
