### ISSUE TITLE
[BUG] amp-carousel: images not loading

### ISSUE THREAD

**Issue by anuragphadke** [ampproject/amphtml#20307] opened 2019-01-14 17:33 UTC
Images in amp-carousel are not loading on user scroll.

We are using amp-carousel on our pages and while the page passes AMP-validation, I noticed that the images are not loading once the user scrolls to the left. 

https://amp.paladintrue.com/amp/it-product-Frullatore-a-immersione-12540.html
Scroll to Prodotti Correlati and then try scrolling left/right, only the first three images load.
In actual browser, the images do load if you scroll down quickly, however, try the same on Safari + iOS, load the URL, wait about 3-5 seconds and the scroll, the images don't load.

Safari + iOS

**Comment by aghassemi** [comment] 2019-01-14 17:44
@anuragphadke The issue is that a wrapper div (`products-teaser-list layout-row`) of `amp-carousel` is used for the overflow scroll instead of the carousel itself. For AMP to do its lazy loading, the carousel should be the one overflowing. Essentially you can not have `overflow-x: auto` on anything. 

You can fix this be removing the parent of amp-carousel and ensuring the carousel is the only item that overflows.

Hope that helps.

**Comment by aghassemi** [comment] 2019-01-14 17:45
Closing per comment above.

**Closed by aghassemi** 2019-01-14 17:45 UTC
Labels: Type: Bug, Type: Discussion/Question
