### ISSUE TITLE
amp-bind - feature request

### ISSUE THREAD

**Issue by macaqueio** [ampproject/amphtml#11182] opened 2017-09-06 17:09 UTC
## Using amp-bind with Range Slider

Request to have amp-bind update in real time as range slider is moved. At present, using input-debounced event, the changes to the bound value don't occur until the slider has completed its adjustment. Normal behaviour for a range slider using javascript would be to update the value incrementally as the slider is adjusted.

## How do we reproduce the issue?

You can reproduce this behaviour at https://flexyfinance.co.uk by moving the handle on the range slider. You will note that the figure in the box above does not adjust until the movement has ceased.

## What browsers are affected?

This affects all browsers and all devices

## Which AMP version is affected?

I believe that this is the desired behaviour of the component at present and the above is a feature request. Currently using amp-version 1504040004635

**Comment by jridgewell** [comment] 2017-09-06 18:00
Thanks for the issue. I'm going to close this as a duplicate of https://github.com/ampproject/amphtml/issues/11175, since it's really an action event that's needed (and `<amp-bind>` can take advantage of that).

**Closed by jridgewell** 2017-09-06 18:00 UTC
