### ISSUE TITLE
Not getting amp-pixel calls if ACCESS_READER_ID is included in Palemoon

### ISSUE THREAD

**Issue by hkmaly** [ampproject/amphtml#2822] opened 2016-04-05 19:42 UTC
In Palemoon, when I include ACCESS_READER_ID variable in url for amp-pixel, I never get the call (server log shows that nothing is downloaded). Same amp-pixel WITHOUT the ACCESS_READER_ID variable succeed.

I'm also not getting any pingbacks. I do get the READER_ID on authorization and login calls.

Interesting is that when the amp-access definition was invalid, I DID got the pixel.

## How do we reproduce the issue?

https://www.einpresswire.com/amp/article/319717314/foam-for-wound-dressing-industry-by-companies-country-and-type-2016-to-2021-global-and-chinese-market-research-report

https://cdn.ampproject.org/c/s/www.einpresswire.com/amp/article/319962384/london-app-company-launches-a-new-scheme-making-social-apps-accessible-for-start-ups

1. Implement amp-access.
2. Add amp-pixel.
3. Wonder why they don't work together.
4. Forgot to test ugly browsers because it totally doesn't look as browser-dependend

## What browsers are affected?

At least Palemoon and older Firefox (24.8). Works in chromium and new firefox (45).

## Which AMP version is affected?

You mean the  "Powered by AMP ⚡ HTML – Version 1458844805881" line? I never saw it work, but I'm only working on AMP for few weeks.

**Comment by dvoytenko** [comment] 2016-04-06 22:13
@hkmaly Most likely this is due to the following errors on the page:
```
Uncaught Error: Authorization failed: : Response must contain the AMP-Access-Control-Allow-Source-Origin header​​​
```

The credentialed CORS requests require the following protocol: https://github.com/ampproject/amphtml/blob/master/spec/amp-cors-requests.md

**Comment by dvoytenko** [comment] 2016-04-06 22:13
I'll close this for now, but please reopen if needed.

**Comment by hkmaly** [comment] 2016-04-08 04:18
I'm sorry, this was my incorrect understanding of CORS protocol. I though that when I'm not getting Origin header I'm not supposed to set any of the CORS headers. But when using the direct url the request is not really cross origin right?

When using the CDN url OR http (instead of https) url, I get the Origin header on authorization and it works as I described. Apparently I was testing on http by mistake.

I now changed the code so the Access-Control-Allow-Origin is not set in this case but other headers are, I assume that is the correct behaviour.

(Note: If you get timeout, please try again. Sometimes I don't get under the three seconds.)

On the other hand, as seen in the referred Palemoon bug, seems that the promise support in Palemoon is not "incomplete" but "non-existing". So if amp-access is really using promise no wonder it doesn't work.

**Comment by hkmaly** [comment] 2016-04-08 04:21
PS: ... I think I'm not allowed to reopen the bug by github.

**Comment by dvoytenko** [comment] 2016-04-08 18:02
@hkmaly Could you please clarify the first part? All requests should definitely be directed to "https". Do you mean when you actually do a same-origin request in that case? As in direct, non-cdn AMP access? In this case, I'd still be inclined to require CORS headers. This is because we'd like to ensure transparency: if you tested and it works on your directly-hosted environment - it should also automatically work on CDN. Does it make sense?

RE:promise support
AMP runs in many environments today that do not support Promise. For this reason we polyfill it. If there's some environment where you suspect problems - feel free to send me the details and we'll try to troubleshoot. This in particular is possible when the Promise exists on the platform, but is incomplete - then the things become shady for us since we it's hard to figure out the incomplete delta.

**Comment by dvoytenko** [comment] 2016-04-08 18:02
Likewise, we'll close for now, but will reopen if needed.

**Closed by dvoytenko** 2016-04-08 18:02 UTC
Labels: Related to: Access, Related to: Analytics, Type: Bug

**Comment by hkmaly** [comment] 2016-04-08 18:51
Yes, I mean direct, non-cdn AMP access. I forgot that is an option and wrote the CORS support code in way which made it fail. Should be fixed now. Did you tried to reproduce the original issue again?

I don't know more about promise implementation than what is mentioned on https://github.com/MoonchildProductions/Pale-Moon/issues/360 - which is that it used to work so bad they disabled it.

I was testing the AMP in two versions: PaleMoon/25.7.0 and PaleMoon/26.2.0 - neither worked (I didn't get the pixel call with reader ID on server). 25.7.0 might be having incomplete implementation, but 26.2.0 should have it disabled. Also, it wasn't working in Firefox 24.8.0, which I suppose don't have any promise at all. (Also, firefox 24.8.0 reports "Content Security Policy: Failed to parse unrecognized source https://cdn.ampproject.org/rtv/" when accessing on CDN, but I don't expect that to be fixed ; I'm moving to PaleMoon).

If there is some page for testing promise support I can test it.

**Comment by dvoytenko** [comment] 2016-04-08 19:57
@hkmaly So, right now, the examples that you sent work seemingly well on Chrome: I see both an auth GET and a pingback POST.

RE:CSP
Our CSP is setup definitely correctly w.r.t. cdn.ampproject.org scripts. Are you sure you are looking at a page hosted on CDN?

RE:Promise
Let's see if @jridgewell has a good test page for promise conformance on different browsers.

**Comment by hkmaly** [comment] 2016-04-08 20:16
You should also see two pixels, one with reader ID and one without. While on Palemoon, there is only auth GET and one pixel without reader ID.

RE:CSP: I'm using the https://cdn.ampproject.org/c/s/www.einpresswire.com/amp/article/319962384/london-app-company-launches-a-new-scheme-making-social-apps-accessible-for-start-ups url ; I'm reasonably sure it's CDN hosted page. I suspect that the CSP specification changed since Firefox 24.8.0 - it likely only received bugfixes since September 17, 2013. Although according to https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives most should work since 23.

The complete list of bugs reported on console is:
Content Security Policy: Failed to parse unrecognized source https://cdn.ampproject.org/rtv/
	

...==f.compatMode?f.documentElement:f.body;e=(new w(g.clientWidth,g.clientHeight))....

osd.js (line 26)
Content Security Policy: Failed to parse unrecognized source https://cdn.ampproject.org/v0.js
Content Security Policy: Failed to parse unrecognized source https://cdn.ampproject.org/v0/
Content Security Policy: Failed to parse unrecognized source https://cdn.ampproject.org/viewer/
Content Security Policy: can't use report URI from non-matching eTLD+1: csp-collector.appspot.com

**Comment by dvoytenko** [comment] 2016-04-08 21:10
@hkmaly Yeah, I see both pixels firing in Chrome. Maybe the easier option is to upgrade the Palemoon to a newer Firefox fork?

**Comment by hkmaly** [comment] 2016-04-08 21:42
Palemoon is the newest fork of Firefox. Do not let the relatively low version numbers confuse you. Also, telling any Palemoon user to switch to Firefox is provocation: ALL Palemoon users switched FROM Firefox because they didn't agree with the direction Firefox developement is going to, including but not limited to Australis.

I understand if you don't want to support Firefox 24.8.0: it's old and not supported by its developers anymore. PaleMoon is supported and unlike newer Firefox, it offers the same features Firefox had and more. (Although, apparently, not including promise.)

(BTW, how are you dealing with Opera users? You know, the real Opera ones, before it switched to Webkit.)

**Comment by dvoytenko** [comment] 2016-04-08 21:58
I don't mean switch, but I wonder if some upgrade is possible within Palemoon. Obviously, we can try to find out the delta that's missing from Palemoon to what AMP can polifyll piece by piece, but that might be a pretty long way to do it. Does Palemoon report ES5 compatibility directly? According to http://kangax.github.io/compat-table/es5/ and Firefox 21+ should be ok, but obviously we are running into things.

> BTW, how are you dealing with Opera users? You know, the real Opera ones, before it switched to Webkit.

No

**Comment by hkmaly** [comment] 2016-04-08 22:30
PaleMoon 26.2.0 is from 2016-04-05. I see there is already 26.2.1 from 2016-04-08 but based on release notes I don't believe anything changed: https://www.palemoon.org/releasenotes.shtml

Also, I already referenced the bug about promise support: https://github.com/MoonchildProductions/Pale-Moon/issues/360 ; I believe any progress will be mentioned there.

Just noticed: on https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise there is "Live example", which says (in PaleMoon) "Live example not available as your browser doesn't support the Promise interface."
They are testing by if ("Promise" in window) and both versions of PaleMoon fails that test.

According to https://www.palemoon.org/roadmap.shtml PaleMoon already supports ES5, but some test would be better.

**Comment by hkmaly** [comment] 2016-04-08 22:32
Oh.
Tried  http://kangax.github.io/compat-table/es5/ 
Both PaleMoon 25.7 and PaleMoon 26.2.0: Only thing which didn't pass is the NaN for invalid dates.

**Comment by hkmaly** [comment] 2016-04-09 03:13
Another stuff I noticed: Login window is supposed to autoclose after login is finished, right? It doesn't in Palemoon. And THAT page is small enough I'm sure you are not doing any polyfill stuff: there is just one javascript there and it doesn't define Promise. Actually, unlike the page itself, it throws error "Promise is not defined" (at line 17).

**Comment by dvoytenko** [comment] 2016-04-11 18:24
@hkmaly Could you please confirm the URL of that page? Generally, the login is delegated completely to the publisher, but there might be some stages we are handling as well.

**Comment by dvoytenko** [comment] 2016-04-11 19:31
Found one page that fails to include all polyfills. Fix is in #2865.

**Comment by hkmaly** [comment] 2016-04-12 14:10
Just to confirm, yes, I was speaking about the login done page, like https://cdn.ampproject.org/v0/amp-login-done-0.1.html?url=http%3A%2F%2Fwww.presswire.com%2Famp%2Farticle%2F317551888%2Feventex-ranks-eventscribe-among-the-world-s-best-event-apps#success=true page.

**Comment by hkmaly** [comment] 2016-04-24 03:01
Ok. Now the login-done window closes, but the main window still doesn't refresh.

Is there some way to test the polyfill with some debug on or something in palemoon?

**Comment by dvoytenko** [comment] 2016-04-25 22:11
Yes, with `#log=2` in the main page's URL you will get all of the logs, including internal framework logs.

**Comment by hkmaly** [comment] 2016-04-27 02:15
No I don't. I mean, URL https://www.einpresswire.com/amp/article/320277073/canatu-and-kaga-electronics-sign-distribution-agreement-in-japan#log=2 didn't produced any other log messages than the "Powered by AMP ⚡ HTML – Version 1460655576651" one. Or do you mean something else as "main page's URL"?

**Comment by dvoytenko** [comment] 2016-04-27 23:42
Hmm. Can you try `#log=3` as well? `3` is the absolute maximum for log levels at this time.

**Comment by hkmaly** [comment] 2016-04-28 21:21
Much better
```
8 [Viewer] Viewer params: Object { log="3"}
v0.js (line 6)
16 [Viewer] - runtimeOn: true
v0.js (line 6)
17 [Viewer] - history: false
v0.js (line 6)
19 [Viewer] - visibilityState: visible
v0.js (line 6)
20 [Viewer] - prerenderSize: 1
v0.js (line 6)
21 [Viewer] - viewportType: natural
v0.js (line 6)
22 [Viewer] - viewportWidth: 0
v0.js (line 6)
24 [Viewer] - viewportHeight: 0
v0.js (line 6)
25 [Viewer] - scrollTop: 0
v0.js (line 6)
26 [Viewer] - padding-top: 0
v0.js (line 6)
27 [Viewer] - performanceTracking: false
v0.js (line 6)
29 [Viewer] visibilitychange event: visible
v0.js (line 6)
31 [Viewport] initialized natural viewport
v0.js (line 6)
48 [Input] touch detected: false
v0.js (line 6)
57 [Resources] element added: amp-img#1
v0.js (line 6)
59 [Resources] element added: amp-img#2
v0.js (line 6)
61 [Resources] element added: amp-img#3
v0.js (line 6)
63 [Resources] element added: amp-img#4
v0.js (line 6)
65 [Resources] element added: amp-img#5
v0.js (line 6)
66 [Resources] element added: amp-img#6
v0.js (line 6)
68 [Resources] element added: amp-img#7
v0.js (line 6)
70 [Resources] element added: amp-img#8
v0.js (line 6)
73 [Resources] element added: amp-ad#9
v0.js (line 6)
75 [Resources] element added: amp-pixel#10
v0.js (line 6)
77 [Resources] element added: amp-pixel#11
v0.js (line 6)
87 [Resources] element added: amp-analytics#12
v0.js (line 6)
7 [amp-access] config: Object { type="client", authorization="https://www.einpresswir...EADER_ID&url=SOURCE_URL", pingback="https://www.einpresswir..._URL&ua=VIEWER&_=RANDOM", more...}
amp-access-0.1.js (line 6)
12 [amp-access] Start authorization via https://www.einpresswire.com/amp-ap/access?rid=READER_ID&url=SOURCE_URL
amp-access-0.1.js (line 6)
13 [amp-access] start view monitoring
amp-access-0.1.js (line 6)
Powered by AMP ⚡ HTML – Version 1460655576651
v0.js (line 351)
184 [Resources] PASS: at 1461878366301, visible= true , forceBuild= true , relayoutAll= true , relayoutTop= -1 , viewportSize= 1165 831 , prerenderSize= 1
v0.js (line 6)
GET https://www.einpresswire.com/amp-ap/access?rid=a...source_origin=https%3A%2F%2Fwww.einpresswire.com
	
200 OK
		145ms	
amp-access-0.1.js (line 48)
195 [Resources] schedule: amp-img#1#L at 1461878366312
v0.js (line 6)
195 [Resources] schedule: amp-img#2#L at 1461878366312
v0.js (line 6)
196 [Resources] schedule: amp-img#4#L at 1461878366313
v0.js (line 6)
196 [Resources] schedule: amp-img#6#L at 1461878366313
v0.js (line 6)
196 [Resources] schedule: amp-img#7#L at 1461878366313
v0.js (line 6)
196 [Resources] schedule: amp-img#8#L at 1461878366313
v0.js (line 6)
197 [Resources] schedule: amp-pixel#10#L at 1461878366314
v0.js (line 6)
197 [Resources] schedule: amp-pixel#11#L at 1461878366314
v0.js (line 6)
197 [Resources] schedule: amp-analytics#12#L at 1461878366314
v0.js (line 6)
198 [Resources] inViewport: amp-img#1 true
v0.js (line 6)
198 [Resources] inViewport: amp-img#2 true
v0.js (line 6)
198 [Resources] inViewport: amp-img#4 true
v0.js (line 6)
198 [Resources] inViewport: amp-img#6 true
v0.js (line 6)
199 [Resources] inViewport: amp-pixel#10 true
v0.js (line 6)
199 [Resources] inViewport: amp-pixel#11 true
v0.js (line 6)
199 [Resources] inViewport: amp-analytics#12 true
v0.js (line 6)
200 [Resources] peek from queue: amp-img#1#L sched at 1461878366312 score 0 timeout 0
v0.js (line 6)
201 [Resources] start layout: amp-img#1 count: 0
v0.js (line 6)
204 [Resources] exec: amp-img#1#L at 1461878366317
v0.js (line 6)
204 [Resources] peek from queue: amp-img#2#L sched at 1461878366312 score 0 timeout 0
v0.js (line 6)
205 [Resources] start layout: amp-img#2 count: 0
v0.js (line 6)
207 [Resources] exec: amp-img#2#L at 1461878366317
v0.js (line 6)
207 [Resources] peek from queue: amp-img#4#L sched at 1461878366313 score 0 timeout 0
v0.js (line 6)
208 [Resources] start layout: amp-img#4 count: 0
v0.js (line 6)
210 [Resources] exec: amp-img#4#L at 1461878366317
v0.js (line 6)
210 [Resources] peek from queue: amp-img#6#L sched at 1461878366313 score 1 timeout 0
v0.js (line 6)
211 [Resources] start layout: amp-img#6 count: 0
v0.js (line 6)
212 [Resources] exec: amp-img#6#L at 1461878366317
v0.js (line 6)
213 [Resources] peek from queue: amp-img#7#L sched at 1461878366313 score 1 timeout 0
v0.js (line 6)
213 [Resources] start layout: amp-img#7 count: 0
v0.js (line 6)
215 [Resources] exec: amp-img#7#L at 1461878366317
v0.js (line 6)
215 [Resources] peek from queue: amp-img#8#L sched at 1461878366313 score 1 timeout 0
v0.js (line 6)
216 [Resources] start layout: amp-img#8 count: 0
v0.js (line 6)
218 [Resources] exec: amp-img#8#L at 1461878366317
v0.js (line 6)
218 [Resources] peek from queue: amp-pixel#10#L sched at 1461878366314 score 10 timeout 982
v0.js (line 6)
218 [Resources] queue size: 3
v0.js (line 6)
218 [Resources] exec size: 6
v0.js (line 6)
219 [Resources] next pass: 982
v0.js (line 6)
136 [amp-access] Authorization URL: https://www.einpresswire.com/amp-ap/access?rid=amp-uPReWVKxKFePM8LBpnDWYjq9vdPzcP8LdSNEZLgS47bdRRazQRVavbRwApkfNBVl&url=https%3A%2F%2Fwww.einpresswire.com%2Famp%2Farticle%2F320277073%2Fcanatu-and-kaga-electronics-sign-distribution-agreement-in-japan
amp-access-0.1.js (line 6)
235 [Resources] PASS: at 1461878366352, visible= true , forceBuild= true , relayoutAll= false , relayoutTop= -1 , viewportSize= 1165 831 , prerenderSize= 1
v0.js (line 6)
235 [Resources] peek from queue: amp-pixel#10#L sched at 1461878366314 score 10 timeout 965
v0.js (line 6)
236 [Resources] queue size: 3
v0.js (line 6)
236 [Resources] exec size: 6
v0.js (line 6)
236 [Resources] next pass: 965
v0.js (line 6)
453 [Resources] layout complete: amp-img#2
v0.js (line 6)
455 [Resources] layout complete: amp-img#4
v0.js (line 6)
474 [Resources] PASS: at 1461878366591, visible= true , forceBuild= true , relayoutAll= false , relayoutTop= -1 , viewportSize= 1165 831 , prerenderSize= 1
v0.js (line 6)
478 [Resources] deferred mutates: 2
v0.js (line 6)
480 [Resources] peek from queue: amp-pixel#10#L sched at 1461878366314 score 10 timeout 720
v0.js (line 6)
482 [Resources] queue size: 3
v0.js (line 6)
483 [Resources] exec size: 4
v0.js (line 6)
484 [Resources] next pass: 720
v0.js (line 6)
428 [amp-access] Authorization response: Object { success=true, user=false, data="", more...}
amp-access-0.1.js (line 6)
598 [Resources] PASS: at 1461878366715, visible= true , forceBuild= true , relayoutAll= false , relayoutTop= 34 , viewportSize= 1165 831 , prerenderSize= 1
v0.js (line 6)
602 [Resources] schedule: amp-img#6#L at 1461878366719
v0.js (line 6)
603 [Resources] schedule: amp-img#7#L at 1461878366720
v0.js (line 6)
604 [Resources] schedule: amp-img#8#L at 1461878366721
v0.js (line 6)
606 [Resources] schedule: amp-ad#9#L at 1461878366723
v0.js (line 6)
607 [Resources] inViewport: amp-img#6 false
v0.js (line 6)
608 [Resources] inViewport: amp-ad#9 true
v0.js (line 6)
610 [Resources] peek from queue: amp-img#6#L sched at 1461878366719 score 1 timeout 0
v0.js (line 6)
612 [Resources] peek from queue: amp-img#7#L sched at 1461878366720 score 1 timeout 0
v0.js (line 6)
613 [Resources] peek from queue: amp-img#8#L sched at 1461878366721 score 1 timeout 0
v0.js (line 6)
615 [Resources] peek from queue: amp-pixel#10#L sched at 1461878366314 score 10 timeout 585
v0.js (line 6)
617 [Resources] queue size: 4
v0.js (line 6)
618 [Resources] exec size: 4
v0.js (line 6)
619 [Resources] next pass: 585
v0.js (line 6)
628 [Resources] PASS: at 1461878366745, visible= true , forceBuild= true , relayoutAll= false , relayoutTop= -1 , viewportSize= 1165 831 , prerenderSize= 1
v0.js (line 6)
631 [Resources] peek from queue: amp-pixel#10#L sched at 1461878366314 score 10 timeout 569
v0.js (line 6)
632 [Resources] queue size: 4
v0.js (line 6)
633 [Resources] exec size: 4
v0.js (line 6)
634 [Resources] next pass: 569
v0.js (line 6)
711 [Resources] layout complete: amp-img#8
v0.js (line 6)
834 [Resources] layout complete: amp-img#7
v0.js (line 6)
835 [Resources] layout complete: amp-img#6
v0.js (line 6)
1208 [Resources] PASS: at 1461878367325, visible= true , forceBuild= true , relayoutAll= false , relayoutTop= -1 , viewportSize= 1165 831 , prerenderSize= 1
v0.js (line 6)
1212 [Resources] peek from queue: amp-img#8#L sched at 1461878366721 score 1 timeout 0
v0.js (line 6)
1213 [Resources] exec: amp-img#8#L at 1461878367329
v0.js (line 6)
1215 [Resources] peek from queue: amp-img#7#L sched at 1461878366720 score 1 timeout 0
v0.js (line 6)
1217 [Resources] exec: amp-img#7#L at 1461878367329
v0.js (line 6)
1218 [Resources] peek from queue: amp-img#6#L sched at 1461878366719 score 1 timeout 0
v0.js (line 6)
1220 [Resources] exec: amp-img#6#L at 1461878367329
v0.js (line 6)
1221 [Resources] peek from queue: amp-pixel#10#L sched at 1461878366314 score 10 timeout 991
v0.js (line 6)
1223 [Resources] queue size: 4
v0.js (line 6)
1224 [Resources] exec size: 4
v0.js (line 6)
1225 [Resources] next pass: 991
v0.js (line 6)
1497 [Resources] layout complete: amp-img#1
v0.js (line 6)
1522 [Resources] PASS: at 1461878367638, visible= true , forceBuild= true , relayoutAll= false , relayoutTop= -1 , viewportSize= 1165 831 , prerenderSize= 1
v0.js (line 6)
1525 [Resources] deferred mutates: 1
v0.js (line 6)
1527 [Resources] peek from queue: amp-pixel#10#L sched at 1461878366314 score 10 timeout 0
v0.js (line 6)
1531 [Resources] start layout: amp-pixel#10 count: 0
v0.js (line 6)
1536 [Resources] exec: amp-pixel#10#L at 1461878367644
v0.js (line 6)
1537 [Resources] peek from queue: amp-pixel#11#L sched at 1461878366314 score 10 timeout 0
v0.js (line 6)
1539 [Resources] start layout: amp-pixel#11 count: 0
v0.js (line 6)
1541 [Resources] exec: amp-pixel#11#L at 1461878367644
v0.js (line 6)
1542 [Resources] peek from queue: amp-analytics#12#L sched at 1461878366314 score 10 timeout 0
v0.js (line 6)
1544 [Resources] start layout: amp-analytics#12 count: 0
v0.js (line 6)
1546 [Resources] exec: amp-analytics#12#L at 1461878367644
v0.js (line 6)
1547 [Resources] peek from queue: amp-ad#9#L sched at 1461878366723 score 21 timeout 980
v0.js (line 6)
1549 [Resources] queue size: 1
v0.js (line 6)
1550 [Resources] exec size: 3
v0.js (line 6)
1551 [Resources] next pass: 980
v0.js (line 6)
1577 [Resources] layout complete: amp-analytics#12
v0.js (line 6)
1608 [Resources] layout complete: amp-pixel#11
v0.js (line 6)
POST https://www.google-analytics.com/r/collect?v=1&_...F-8&t=pageview&_r=1&a=1563&z=0.04218396321124418
	
200 OK
		43ms	
amp-an...-0.1.js (line 158)
2589 [Resources] PASS: at 1461878368706, visible= true , forceBuild= true , relayoutAll= false , relayoutTop= -1 , viewportSize= 1165 831 , prerenderSize= 1
v0.js (line 6)
2591 [Resources] peek from queue: amp-ad#9#L sched at 1461878366723 score 21 timeout 0
v0.js (line 6)
2593 [Resources] start layout: amp-ad#9 count: 0
v0.js (line 6)
2595 [Resources] exec: amp-ad#9#L at 1461878368708
v0.js (line 6)
2597 [Resources] queue size: 0
v0.js (line 6)
2598 [Resources] exec size: 2
v0.js (line 6)
2599 [Resources] next pass: 5000
v0.js (line 6)
"NetworkError: 404 Not Found - https://encrypted-tbn3.gstatic.com/favicon?q=tbn:ANd9GcQzphbT4mK3f5qvSNDWIcs3h-rpC2Z0PW4jimRIP_6imy2gaTGaDp_h4HjCmin7NekMXu_Pb46BsxvezmPqj2zjORIP4WfNhojb0z9-kPQ"
favico...0z9-kPQ
4533 [Resources] layout complete: amp-ad#9
v0.js (line 6)
5533 [Resources] PASS: at 1461878371650, visible= true , forceBuild= true , relayoutAll= false , relayoutTop= -1 , viewportSize= 1165 831 , prerenderSize= 1
v0.js (line 6)
5538 [Resources] queue size: 0
v0.js (line 6)
5539 [Resources] exec size: 1
v0.js (line 6)
5541 [Resources] next pass: 5000
v0.js (line 6)
10544 [Resources] PASS: at 1461878376661, visible= true , forceBuild= true , relayoutAll= false , relayoutTop= -1 , viewportSize= 1165 831 , prerenderSize= 1
v0.js (line 6)
10562 [Resources] queue size: 0
v0.js (line 6)
10565 [Resources] exec size: 1
v0.js (line 6)
10566 [Resources] next pass: 12058
v0.js (line 6)
```

**Comment by dvoytenko** [comment] 2016-04-29 16:45
Hmm. This log doesn't look right. There has to be a "Start login" message that's logged at the beginning of the login flow. If you use a message filter, do you see it?

**Comment by hkmaly** [comment] 2016-04-30 00:31
It won't appear until I click on login link. Wait, you wanted log from loging in?
```
17527 [amp-access] Start login: login
amp-access-0.1.js (line 6)
17534 [amp-access-login] Open dialog: https://www.einpresswire.com/login?amp-rid=amp-uPReWVKxKFePM8LBpnDWYjq9vdPzcP8LdSNEZLgS47bdRRazQRVavbRwApkfNBVl&url=https%3A%2F%2Fwww.einpresswire.com%2Farticle%2F320277073%2Fcanatu-and-kaga-electronics-sign-distribution-agreement-in-japan&amp-return=https%3A%2F%2Fcdn.ampproject.org%2Fv0%2Famp-login-done-0.1.html%3Furl%3Dhttps%253A%252F%252Fwww.einpresswire.com%252Famp%252Farticle%252F320277073%252Fcanatu-and-kaga-electronics-sign-distribution-agreement-in-japan https://cdn.ampproject.org/v0/amp-login-done-0.1.html?url=https%3A%2F%2Fwww.einpresswire.com%2Famp%2Farticle%2F320277073%2Fcanatu-and-kaga-electronics-sign-distribution-agreement-in-japan 700 450 610 315
amp-access-0.1.js (line 6)
23861 [Resources] PASS: at 1461975917989, visible= true , forceBuild= true , relayoutAll= false , relayoutTop= -1 , viewportSize= 1165 831 , prerenderSize= 1
v0.js (line 6)
23873 [Resources] queue size: 0
v0.js (line 6)
23875 [Resources] exec size: 1
v0.js (line 6)
23876 [Resources] next pass: 30000
v0.js (line 6)
53879 [Resources] PASS: at 1461975948007, visible= true , forceBuild= true , relayoutAll= false , relayoutTop= -1 , viewportSize= 1165 831 , prerenderSize= 1
v0.js (line 6)
53889 [Resources] queue size: 0
v0.js (line 6)
53890 [Resources] exec size: 1
v0.js (line 6)
53892 [Resources] next pass: 30000
v0.js (line 6)
83894 [Resources] PASS: at 1461975978022, visible= true , forceBuild= true , relayoutAll= false , relayoutTop= -1 , viewportSize= 1165 831 , prerenderSize= 1
v0.js (line 6)
83904 [Resources] queue size: 0
v0.js (line 6)
83907 [Resources] exec size: 1
v0.js (line 6)
83909 [Resources] next pass: 30000
113914 [Resources] PASS: at 1461976008041, visible= true , forceBuild= true , relayoutAll= false , relayoutTop= -1 , viewportSize= 1165 831 , prerenderSize= 1
v0.js (line 6)
113924 [Resources] queue size: 0
v0.js (line 6)
113927 [Resources] exec size: 1
v0.js (line 6)
113929 [Resources] next pass: 30000
v0.js (line 6)
122989 [amp-access-login] MESSAGE: message origin=https://cdn.ampproject.org, data=[object Object]
amp-access-0.1.js (line 6)
122995 [amp-access-login] Received message from dialog: Object { sentinel="amp", type="result", result="#success=true"}
amp-access-0.1.js (line 6)
123001 [amp-access-login] Login done: #success=true undefined
amp-access-0.1.js (line 6)
123041 [amp-access] Login dialog completed: login #success=true
amp-access-0.1.js (line 6)
123044 [amp-access] Start authorization via https://www.einpresswire.com/amp-ap/access?rid=READER_ID&url=SOURCE_URL
amp-access-0.1.js (line 6)
143933 [Resources] PASS: at 1461976038061, visible= true , forceBuild= true , relayoutAll= false , relayoutTop= -1 , viewportSize= 1165 831 , prerenderSize= 1
v0.js (line 6)
143946 [Resources] queue size: 0
v0.js (line 6)
143948 [Resources] exec size: 1
v0.js (line 6)
143950 [Resources] next pass: 30000
v0.js (line 6)
173955 [Resources] PASS: at 1461976068082, visible= true , forceBuild= true , relayoutAll= false , relayoutTop= -1 , viewportSize= 1165 831 , prerenderSize= 1
v0.js (line 6)
173972 [Resources] queue size: 0
v0.js (line 6)
173974 [Resources] exec size: 1
v0.js (line 6)
173976 [Resources] next pass: 30000
```

But I would like to remind that the original reported error is that the pixel with ACCESS_READER_ID and the pingback are never called, because they are postponed after the authorization call and never un-postponed.

On the other hand, it's likely that the page not reloading have same reason, and it has something to do with the polyfills not working properly.

**Comment by dvoytenko** [comment] 2016-05-02 21:43
/cc @jridgewell 

> it has something to do with the polyfills not working properly

Our promise polyfill is fully compliant with ES6 and tested via https://github.com/promises-aplus/promises-tests. I'm not sure how to confirm it in this particular browser though, since there are no errors of any kind that I can see in the logs you sent...

**Comment by jridgewell** [comment] 2016-05-02 22:27
Hi @hkmaly. We use [PJs](https://github.com/jridgewell/pjs) as our Promise polyfill, with the actual polyfil testing happening in [src/polyfills/promise.js](https://github.com/ampproject/amphtml/blob/master/src/polyfills/promise.js). As @dvoytenko mentioned, I've followed and [test against](https://github.com/jridgewell/PJs/blob/master/test/promises-spec.js) the official [A+ test specs](https://github.com/promises-aplus/promises-tests). ES6 specific features (A+ is essentially a subset of ES6 Promises) are [tested](https://github.com/jridgewell/PJs/blob/master/test/promise.js) as well, but there's no standard spec suite.

Further, reviewing the [built login code](https://cdn.ampproject.org/v0/amp-login-done-0.1.js), I can confirm that the Promise polyfill is being installed correctly and it is installed before anything tries to instantiate a Promise. Our polyfill code is definitely not the issue here.

**Comment by hkmaly** [comment] 2016-05-11 23:00
Hello,

I meant that there is something in the promise polyfill which doesn't work in Palemoon, despite not throwing error. I believe it works in node, but that's useless to me.

Hmmm ...

Based on https://nicolas.perriault.net/code/2013/testing-frontend-javascript-code-using-mocha-chai-and-sinon/ I created simple test in browser
{{{
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Cow tests</title>
  <link rel="stylesheet" media="all" href="vendor/mocha.css">
</head>
<body>
  <div id="mocha"><p><a href=".">Index</a></p></div>
  <div id="messages"></div>
  <div id="fixtures"></div>
  <script src="vendor/mocha.js"></script>
  <script src="vendor/chai.js"></script>
  <script src="vendor/sinon-chai.js"></script>
  <script src="vendor/sinon-1.7.1.js"></script>
  <script src="promise.js"></script>
  <script>mocha.setup('bdd')</script>
  <script src="test/promise.js"></script>
  <script src="test/promises-aplus-tests.js"></script>
  <script src="test/promises-spec.js"></script>
  <script>mocha.run();</script>
</body>
</html>
}}}
... I hoped I will get some failure but after I get rid of all requires the first part runs without problems. No idea how to actually run the promises-spec, though, I generated promises-aplus-tests.js with browserify but don't know what to replace the var tests = require('promises-aplus-tests') with. Also, the file starts with warning "THIS IS NOT TESTED NOR LIKELY TO WORK OUTSIDE V8!" ...

Anything else I should test like this?

**Comment by hkmaly** [comment] 2016-05-11 23:54
Another idea: may something taking too long be a problem? Some of those tests takes over 100ms (or at least have red note claiming so).

**Comment by jridgewell** [comment] 2016-05-12 16:25
You'd have to build the PJs test files with browserify, which will in turn build the mocha tests. Then run those through Mocha in the browser.
