### ISSUE TITLE
DFP/AdX for AMP: broken lazy load?

### ISSUE THREAD

**Issue by valalukas** [ampproject/amphtml#13874] opened 2018-03-08 14:39 UTC
Hello,

recently I've come across an unexpected behaviour of a BTF ad unit on AMP.

## What's the issue?

I tested 2 different setups on our AMP pages:

1. AdSense
2. DFP/AdX with 3rd party line items

The problem occurred when I was comparing the performance reports of both setups. In [the AdSense report](https://drive.google.com/open?id=1TvEvVA9AkfTt62GdcEs634Zx8MuqMCeP), you can clearly see the gap between the top (ATF) and the bottom (BTF) unit ad requests, following from the lazy load. Furthermore, all ad requests are filled by impression.

On the other hand, when pulling [the Ad Exchange historical report](https://drive.google.com/open?id=1HtfX1jQVD3B8SCJqQL1A6At6KRgS3dzr), the same ad units apparently fired the same number of ad requests, moreover the fill of impressions is both, lower and unequal. Even when including the 3rd party line items serving on both ad units ([DFP Historical report](https://drive.google.com/open?id=1qaVymbs4YLOC4LFQ11W9gVZT6UoiJu-R)), the ad unit coverage varies significantly: the top unit ad impressions value (ad server+adx) is 112% of the total code served count (which makes no sense) and the bottom unit only 67%.

I addressed this weird occurrences to Google support and they assert the 112% coverage of the ATF ad units is a bug on their side, while the same number of ad requests fired for both, ATF and BTF unit might be caused by a broken lazy loading and encouraged me to reach out to you asking for help.

## How do we reproduce the issue?

1. To see the BTF ad unit with AdSense, please visit any deal page of amp.urlaubspiraten.de, e.g. [this one](https://amp.urlaubspiraten.de/reisen/und-die-suite-ist-inklusive-1-woche-gran-canaria-im-top-4-hotel-ab-499-euro-mit-halbpension_26637).
2. To see the BTF ad unit with DFP/AdX/3rd party demand, please see [this testing URL](https://amp.x-bitbucket-pr-229-hkffliy-eut6osk5pggom.eu.platform.sh/fluge/post-to-test-with-10-flights_26478).

I will be grateful for any feedback.

Lukas

**Comment by valalukas** [comment] 2018-03-15 13:23
Dear all, may I ask you to let me know, if some more informations on the issue should be provided in order to describe it comprehensively or whether this is not a right place to bring it up?

Thank you and Best Regards,

Lukas

**Comment by keithwrightbos** [comment] 2018-03-26 13:05
Hello this is essentially a duplicate of #13898   Fast Fetch (launching in July for AdSense and Doubleclick) allows for sending the ad request independent of render.  For amp-ad type=doubleclick tags this results in the ad request being sent immediately despite slot's location relative to viewport (AdSense actually purposely delays the ad request as well).  However, the creative is not rendered until the slot is within 3 viewports (or 12 if render on idle is eligible, see https://www.ampproject.org/es/latest/blog/faster-ads-with-render-on-idle/).  This delay includes when delayed impressions are fired and so you would expect slots ATF to have near 100% view rate (impressions/matched queries) and the those BTF to be lower depending on the length of your page and how often users scroll.

**Closed by keithwrightbos** 2018-03-26 13:05 UTC
