### ISSUE TITLE
Unnatural touch behavior of amp-carousel in slides mode

### ISSUE THREAD

**Issue by auxsoft** [ampproject/amphtml#7998] opened 2017-03-06 18:40 UTC
In most native interactions (and in other sliders implementations) the swipe gesture isn't finished while the touch continues. That is, while you keep touching the slide it is as if you were holding the slide and you can move it to the right and left. In amp-carousel stopping the movement (but while still touching) causes the slide to snap back to it's original position or to the next slide.

**Comment by muxin** [comment] 2017-03-10 22:51
This issue seems like a duplicate of https://github.com/ampproject/amphtml/issues/5428

**Comment by camelburrito** [comment] 2017-03-11 01:17
Yes it's a dupe

**Closed by camelburrito** 2017-03-11 01:17 UTC
Labels: Category: Presentation, Type: Bug
