### ISSUE TITLE
Amp-slideshow can break on iOS Safari

### ISSUE THREAD

**Issue by robruenes** [ampproject/amphtml#983] opened 2015-11-20 03:29 UTC
For the AMP found at:
https://www.washingtonpost.com/amphtml/opinions/after-paris-we-should-look-to-chris-christie/2015/11/18/9077dbea-8d58-11e5-ae1f-af46b7df8483_story.html

Sometimes (it was flaky, unsure exactly how to re-produce) when this AMP was loaded on iOS Safari, the slideshow on the page would load all of the images and text on top of each other, creating jumbled text, as well as the ability to move the first image over partially and see the image underneath.

![img_0358](https://cloud.githubusercontent.com/assets/2532370/11292108/2afbd454-8f17-11e5-9df1-a6aaa11680cc.jpg)
![img_0359](https://cloud.githubusercontent.com/assets/2532370/11292109/2be47a38-8f17-11e5-8e08-a6d82c2e81f1.jpg)

**Comment by dvoytenko** [comment] 2015-11-20 17:27
Thanks a lot! I'll take a look.

**Comment by dvoytenko** [comment] 2015-11-24 00:22
The problem has been reproduced. This is due to the latent DOM mutations that were unobserved in this case. Fix is in progress.

**Closed** 2015-11-25 08:45 UTC
Labels: Priority: High, Type: Bug
