### ISSUE TITLE
FR: event to trigger/prevent loading for amp-list

### ISSUE THREAD

**Issue by karsten-eger** [ampproject/amphtml#8931] opened 2017-04-25 09:45 UTC
Right now amp-list is only firing the remote request when it is visible in the "scope of amp" itself. I get the idea behind it and it is a great solution for most cases. Unfortunately we stumbled across a case where it would be great to have the option to fire the request even if the list is still not visible.
It doesn't matter if the amp-list is inside a collapsed accordion or if it is hidden via the given attribute. As long as it is hidden via AMP's means it won't load the remote request until visible.

A solution I found/was told was to use the amp-list element twice. Once within the "scope of amp" so AMP is aware of the visibility and once without aka with hidden class (display:none). That way the out-of-scope hidden amp-list fires the request and it is present for the other one since it's cached already.
 
So it would be nice to trigger the loading of the amp-list element. Be it as "loadOnPageLoad" or via triggering an (to  be added) event to be used by other elements via "on".

In #8735 amp-bind changes the src dynamically. What happens in this case if the amp-list is not yet visible?

In our case we wanted to use amp-list to show the content of the users shopping cart on our store. The collapsed cart icon should show the number of items (another issue 😁) in the cart even when the cart was not yet opened.

**Comment by choumx** [comment] 2017-08-04 22:13
Thanks for filing this issue and sorry for the delayed response.

Why is the network request latency unacceptable for your use case? There's a mobile data & battery tradeoff for performing requests that the user may not need.

> In #8735 amp-bind changes the src dynamically. What happens in this case if the amp-list is not yet visible?

The network request would be made even if the amp-list is not yet visible.

> In our case we wanted to use amp-list to show the content of the users shopping cart on our store. The collapsed cart icon should show the number of items (another issue 😁) in the cart even when the cart was not yet opened.

Does the collapsed cart icon/number of items need to be an amp-list here? Server side rendering should work, right?

**Comment by choumx** [comment] 2018-07-09 18:54
Closing. Conservative resource scheduling in AMP is by design though you may be able to hack around this by having the "hidden" amp-list elements displayed on the first viewport with a 1x1 size and then enlarging later.

**Closed by choumx** 2018-07-09 18:54 UTC
Labels: Category: Dynamic/Personalized Content, Type: Feature Request
