### ISSUE TITLE
Self host entire specific runtime

### ISSUE THREAD

**Issue by MadisonMiner** [ampproject/amphtml#34946] opened 2021-06-22 05:01 UTC
### Description

We use AMP across many projects. 

Testing everything with the weekly release, or even monthly with LTS, is challenging.

When using AMP in PWA, we self host the AMP runtime, to ensure a more reliable and stable environment. 

However, even when we self host the runtime and set `<meta name="runtime-host">,` some files (like ww.js) are always served from the AMP cache. 

We would like to ensure that all files are self hosted when we self-host shadow-v0. (We understand why amp-geo would be an exception.)

### Reproduction Steps

Even though we are self hosting, the self hosted shadow-v0 fetches this file from the AMP cache: 
https://cdn.ampproject.org/rtv/012012232217000/ww.js

Tonight the [012012232217000](https://github.com/ampproject/amphtml/releases?after=2012301722001) version of AMP (about 6 months old) started redirecting to: https://cdn.ampproject.org/lts/v0/amp-geo-0.1.js

Since the above link now redirects to amp-Geo, our site went down.

### Browser(s) Affected

Chrome, Firefox, Safari, Edge, UC Browser

### OS(s) Affected

All

### Device(s) Affected

All

### AMP Version Affected

012012232217000

**Comment by rsimha** [comment] 2021-06-22 18:33
@MadisonMiner I suspect this is due to AMP's 6 month retention policy for runtime versions. Any hard links to releases older than that are redirected to the current LTS version. You can find more details at the I2I at https://github.com/ampproject/amphtml/issues/25468, and the design review summary at https://github.com/ampproject/amphtml/issues/27071#issuecomment-600842762. Would it be possible for you to try a newer version of AMP and see if the behavior changes?

Meanwhile, you've raised two interesting questions:

1) Why did the link to the deleted version of `ww.js` redirect to LTS `amp-geo.js`?
2) Why did `shadow-v0.js` fetch `ww.js` from the CDN?

Let me check with the team and get back to you on these two.

**Comment by honeybadgerdontcare** [comment] 2021-06-22 19:13
@sebastianbenz regarding self hosting.

**Comment by MadisonMiner** [comment] 2021-06-22 21:39
@rsimha, we did upgrade to a new version last night. That did correct the issue. Thank you for checking on questions #1 and #2.

**Comment by rsimha** [comment] 2021-06-22 21:53
That's excellent to hear, @MadisonMiner. Thanks for letting us know, and sorry about the additional trouble.

Meanwhile, I do have an update on the questions raised by this bug.
1. We've identified the cause of the incorrect `ww.js` redirect to `amp-geo.js`. It due to how our serving redirections for deprecated AMP /rtv/ requests worked, and a fix has already been checked in. It will be a few days before it makes its way to production (expected in the second half of next week). Special thanks to @danielrozenberg for driving this.
2. We're still trying to understand why `shadow-v0.js` is fetching `ww.js` from the CDN. There is a tracking issue at https://github.com/ampproject/amphtml/issues/34971 where you can find more updates. Thanks to @samouri for investigating this.

**Comment by kristoferbaxter** [comment] 2021-06-22 22:29
It looks like #34971 covers the remaining work on this item. Closing this issue.

@rsimha – Should we add some additional guidance regarding the 6 month timeline for allowed access to releases from the Google CDN?

**Closed by kristoferbaxter** 2021-06-22 22:29 UTC
Labels: Type: Bug, WG: infra

**Comment by MadisonMiner** [comment] 2021-06-22 22:37
@rsimha, can you share any more information regarding fixing ww.js redirecting to amp-geo.js? A link to reference would be helpful. 

Thank you!

**Comment by kristoferbaxter** [comment] 2021-06-24 19:22
@MadisonMiner The redirect issue was an internal Google issue impacting requests for versions >6 months old.

@danielrozenberg might be able to answer additional questions.
