### ISSUE TITLE
Ad loading placeholder stays on top of "subscribe" overlay on NYT

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#7641] opened 2017-02-17 19:10 UTC
See screenshot below. If we can't fix this in AMP, we should reach out to New York Times with a solution.

![0](https://cloud.githubusercontent.com/assets/2099009/23079371/8ecd7f86-f501-11e6-853c-4bb063e639ad.png)

/to @zhouyx 
/cc @jasti @lannka

**Comment by lannka** [comment] 2017-02-17 19:45
[z-index:1](https://github.com/ampproject/amphtml/blob/master/css/amp.css#L273) is the cause. I guess it exists. But let's play with it and see if we can get rid of it.

**Comment by lannka** [comment] 2017-02-17 19:57
After discussion with @zhouyx, we think it should be fixed at publisher side by following the [z-index spec](https://github.com/ampproject/amphtml/blob/master/css/Z_INDEX.md)

**Comment by jasti** [comment] 2017-02-17 21:17
I've notified the account team with the issue reference. Please expect follow up offline.

**Closed by jasti** 2017-02-17 21:17 UTC
Labels: Category: Ads, P1: High Priority, Type: Bug
