### ISSUE TITLE
Add easy way to toggle a class based on user input

### ISSUE THREAD

**Issue by pbakaus** [ampproject/amphtml#3501] opened 2016-06-08 23:54 UTC
A lot of times, I have wanted the ability to toggle a class on an element when a user clicks on something. Here's my proposal:

```
<button on="tap:change-class">Open lightbox</button>

<amp-class-toggler id="change-class" class="class-to-toggle" element="element-id-to-toggle"></amp-lightbox>

<div id="element-id-to-toggle"></div>
```

Of course, this would allow you to arbitrarily alter the layout of the page, but only when triggered by a user action. There's probably opportunity for abuse, but I thought I'd start the conversation.

**Comment by cramforce** [comment] 2016-06-09 13:20
This has been discussed a few times before and is quite the obvious change. No need for a new element, something as imperative as
`<button on="tap:toggle-class('.foo', 'class-name')">Open lightbox</button>`
could work.

The simple reason why I've been reluctant to put this into AMP is that it would immediately be used to build "READ MORE" buttons.

**Comment by pbakaus** [comment] 2016-06-09 16:12
Fair enough. I agree that the bulk of the content probably shouldn't be hidden upon arrival. Tricky problem. We could use some heuristics to see whether there's content in the toggled paragraph, but any such heuristic would be faulty and produce lots of false positives and negatives.

I don't have an immediate solution and my use case isn't strong enough to warrant read more buttons, so feel free to close for now.

**Comment by ericlindley-g** [comment] 2016-06-15 23:42
@cramforce Slotting in backlog, but feel free to correct/update the milestone as needed

**Comment by pbakaus** [comment] 2016-08-11 22:17
@dvoytenko (because we just talked about this in some other context)

**Comment by jridgewell** [comment] 2016-11-21 18:19
Closing as a dupe of https://github.com/ampproject/amphtml/issues/1032.

**Closed by jridgewell** 2016-11-21 18:19 UTC
Labels: Related to: Content, Type: Feature, Type: Request

**Comment by mgunalp** [comment] 2017-12-04 09:20
Hi, 
**this code not working, can you help me?**
<button on="tap:popUp.show,toggle-class('.asdiv', 'popUpBox2')">OPEN</button>

**Comment by cvializ** [comment] 2017-12-04 18:15
I think the above code was "example" code, so it doesn't work in actual AMP. 
You can use [amp-bind](https://www.ampproject.org/docs/reference/components/amp-bind) to implement the functionality you're looking for:

```html
<button
  on="AMP.setState({toggleVar: !toggleVar})"
  [class]="toggleVar ? 'class-one' : 'class-two'"
>Open</button>
```
