### ISSUE TITLE
Add elementId variable to amp analytics visibility trigger

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#3972] opened 2016-07-08 18:22 UTC
Can we an `elementId` variable to the visibility trigger in `amp-analytics`?

Use case - allow tracking visibility of all ads without having to know the id of each one, particularly useful when you have a variable number of ad units depending on content length.

```
"triggers": {
    "adView": {
      "on": "visible",
      "request": "asdView",
      "visibilitySpec": {
        "selector": "amp-ad, amp-embed",
        "visiblePercentageMin": 20,
        "totalTimeMin": 500,
        "continuousTimeMin": 200
      },
      "vars": {
        "element": "elementId",
        "x": "elementX",
        "y": "elementY"
      }
    }
  }

```

**Comment by rudygalfi** [comment] 2016-07-11 21:57
@jpettitt Will #1298 cover this? As https://github.com/ampproject/amphtml/issues/1298#issuecomment-229501177 describes, we're imagining a way for you to have a `data-var-*` attribute on elements which would provide a variable value to analytics.

**Comment by jpettitt** [comment] 2016-07-12 23:59
That would do it.  As long as the selector can match more than one element and the `data-var-*` identifies the element in the output that meets my use case.

**Comment by rudygalfi** [comment] 2016-07-13 23:27
Let's close this and consider a duplicate of #1298.

**Closed by rudygalfi** 2016-07-13 23:27 UTC
Labels: Closed: Duplicate, Related to: Analytics, Type: Enhancement, Type: Request
