### ISSUE TITLE
[CANARY Error]: Signing service error for google: Failed to import key 

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#11451] opened 2017-09-26 22:51 UTC
```
Error: Signing service error for google: Failed to import key ({"alg":"RS256","e":"AQAB","ext":true,"kid":"1","kty":"RSA","n":"z43rjaJ9PLk1FHMEL31_ILXGtUTN03rxJ9amD9y3BRDpbTA-GkUKiQM07xAd8OXPUZRqcjvXQfc7b1RCEtwrcfx9oBRdF78QMA4tLLCqSHP0tSuqYF0fA7-GyTFWDcYzey90jRFNNWxjzKrvSazacE0TvJ8S_AVP4EV67VdbByCC1tpBzLhhy7RFHp2cXGTpWYUqZUAVUdJoeBuCho_zQz2au7c6sDaLiF-uYL9Td9MrZ6tSLo3MeMIZia4WgWqjTDICR0h-zlbHUd0K9CoXbGTt5nvkebXHmbKd99ma6zRYVlYNJTuSqsRCBNYtCTFVHIZeBlkjHKsQ46HTZPexZw"}): Member JsonWebKey.kty is required and must be an instance of DOMString
    at message (https://raw.githubusercontent.com/ampproject/amphtml/1505933541672/src/log.js:490:22)
    at https://raw.githubusercontent.com/ampproject/amphtml/1505933541672/src/log.js:220:43
    at https://raw.githubusercontent.com/ampproject/amphtml/1505933541672/src/log.js:234:36
```

**Comment by zhouyx** [comment] 2017-09-26 23:09
Looks like a `dev().error()` that we expect to throw on signature fail. @taymonbeal

**Comment by taymonbeal** [comment] 2017-09-27 16:19
Duplicate of #11394.

**Closed** 2017-09-27 16:20 UTC
