### ISSUE TITLE
Not recognising SSL

### ISSUE THREAD

**Issue by WTVOX** [ampproject/amphtml#30864] opened 2020-10-26 18:46 UTC
## What's the issue?
Have installed the AMP plugin on a new site we are setting up (https://thevou.com) and it keeps throwing a message stating that there's no SSL. We have installed and reinstalled the plugin several times, it is still unable to recognise the SSL.

## How do we reproduce the issue?
Not sure, see the pics below:
<img width="1321" alt="Screenshot 2020-10-23 at 13 39 18" src="https://user-images.githubusercontent.com/70020782/97214521-214dc480-17bb-11eb-8b6b-d6f3b7bafe3a.png">

<img width="1331" alt="Screenshot 2020-10-26 at 18 45 12" src="https://user-images.githubusercontent.com/70020782/97214724-64a83300-17bb-11eb-93e4-3f31c7b35cef.png">

## What browsers are affected?
All browsers.

## Which AMP version is affected?
Version 2.0.5

**Comment by jridgewell** [comment] 2020-10-26 18:59
Hi @WTVOX, can you reopen this on the [amp-wp](https://github.com/ampproject/amp-wp) repo?

**Comment by WTVOX** [comment] 2020-10-27 12:10
Done, thanks for pointing to the right project. Best

**Comment by jridgewell** [comment] 2020-10-28 20:04
Closing as dupe of https://github.com/ampproject/amp-wp/issues/5544. Thanks!

**Closed by jridgewell** 2020-10-28 20:04 UTC
Labels: Type: Bug
