### ISSUE TITLE
Page not rendering in IE 11 anymore

### ISSUE THREAD

**Issue by sryze** [ampproject/amphtml#17528] opened 2018-08-15 23:44 UTC
## What's the issue?

Until recently our site was working fine in IE 11, but now it doesn't render correctly. I think it might be related to this error:

```
SCRIPT438: Object doesn't support property or method 'assign'
v0.js (519,398)
```

## How do we reproduce the issue?

See https://www.upnest.com/

## What browsers are affected?

Internet Explorer 11

## Which AMP version is affected?

1534366245210

**Comment by cathyxz** [comment] 2018-08-15 23:50
This seems similar to https://github.com/ampproject/amphtml/issues/17505.

**Comment by sryze** [comment] 2018-08-16 13:44
I will try building AMP from git today and check that fixed my issue. Thanks.

**Comment by jridgewell** [comment] 2018-08-16 17:29
Closing as a duplicate of #17505.

**Closed by jridgewell** 2018-08-16 17:29 UTC
