### ISSUE TITLE
Auto height/width insertion support for amp-img tags

### ISSUE THREAD

**Issue by ymotongpoo** [ampproject/amphtml#7024] opened 2017-01-13 08:02 UTC
## Short description of your issue:

Currently, ampporject official repository doesn't provide a tool to convert normal HTML to AMP HTML. Especially one of hardest part is to get height/width property of images. It would be great if there's a tool to fill mandatory attributes for amp-img.

## How do we reproduce the issue?

1. create an AMP HTML page that has `amp-img` tags without height/width attribute.
2. run validation tool.
3. see errors.

It would be great the validation tool can fill the lacking attributes (i.e. height/width) of `amp-img` based the metadata of the files specified in `src` attributes if they are accessible. 

## What browsers are affected?

All browsers

## Which AMP version is affected?

All versions

**Comment by jridgewell** [comment] 2017-01-13 19:51
Duplicate of https://github.com/ampproject/amphtml/issues/2039#issue-134010121. This is something you'll have to solve on the server side, we can't provide a generic solution.

**Closed by jridgewell** 2017-01-13 19:51 UTC
