### ISSUE TITLE
"on":"visible" doesn't take selector for <amp-analytics>

### ISSUE THREAD

**Issue by johnnyshankman** [ampproject/amphtml#2234] opened 2016-02-23 20:38 UTC
Attempting to fire an analytic event when users reach the end of the page with this general code:

```
<amp-analytics type="googleanalytics" id="analytics-scroll-end">
<script type="application/json">
{
  "vars": {
    "account": "..."
  },
  "triggers": {
    "trackScollToBottom" : {
      "on": "visible",
      "selector": "#athing",
      "request": "event",
      "vars": {
        "eventCategory": "AMP",
        "eventAction": "Article Scroll",
        "eventLabel": "End"
      }
    }
  }
}
</script>
</amp-analytics>
```

But no matter what it fires on page load.

If I switch the trigger to `click` it does indeed only fire when I click the element at the bottom of the page.

When I switch it back to `visible` it fires on page load.

I see in the docs that this is only ever used for pageviews, so this might actually be a feature request and not a bug.

**Comment by rudygalfi** [comment] 2016-02-23 20:47
`visible` firing only on page visibility is working as intended. We haven't built a feature to fire requests when elements become visible.

We do have an issue tracking a "first-visible" event: #1305. It's functionally similar to what you describe here, except it would only be intended to fire in the first instance when an element becomes visible.

Supporting firing events anytime a given element is visible may require some further thinking. I'm concerned this would fire too frequently so as to be non-performant. It may be better to solve this through some batched approach where the raw visibility data for page elements is provided on a `timer`.

**Comment by rudygalfi** [comment] 2016-02-23 20:49
I'm going to close this, but @johnnyshankman if you'd like to formally request a feature that provides more visibility information beyond #1305 (just first visible), we can either re-purpose this issue or start a new one.

**Closed by rudygalfi** 2016-02-23 20:49 UTC
Labels: Related to: Analytics, Type: Question

**Comment by wojtekmo** [comment] 2016-02-23 20:52
Hello  Team,
Please remowe my input into "amphtml"
Thank you
Wojyek 

    On Tuesday, February 23, 2016 2:47 PM, Rudy Galfi <notifications@github.com> wrote:
 

 visible firing only on page visibility is working as intended. We haven't built a feature to fire requests when elements become visible.We do have an issue tracking a "first-visible" event: #1305. It's functionally similar to what you describe here, except it would only be intended to fire in the first instance when an element becomes visible.Supporting firing events anytime a given element is visible may require some further thinking. I'm concerned this would fire too frequently so as to be non-performant. It may be better to solve this through some batched approach where the raw visibility data for page elements is provided on a timer.—

**Comment by wojtekmo** [comment] 2016-02-23 20:54
Hello  Team,
Please remowe my input into "amphtml"
Thank you
Wojtek 

    On Tuesday, February 23, 2016 2:49 PM, Rudy Galfi <notifications@github.com> wrote:
 

 Closed #2234.—

**Comment by johnnyshankman** [comment] 2016-02-23 20:56
@rudygalfi I think a "first-visible" event is really what I'm after here anyways. Glad to hear there's an open request/issue.

**Comment by johnnyshankman** [comment] 2016-02-23 20:57
I would not required anything past the scope of #1305 :+1: thanks for the info and I'm totally cool with this being closed

**Comment by wojtekmo** [comment] 2016-02-23 20:57
Hello  Team,
Please remove my input into "amphtml"
Thank you
Wojtek 

    On Tuesday, February 23, 2016 2:56 PM, Johnny Shankman <notifications@github.com> wrote:
 

 @rudygalfi I think a "first-visible" event is really what I'm after here anyways. Glad to hear there's an open request/issue.—
