### ISSUE TITLE
AMP4EMAIL: styles do not apply to the amp-selector option in gmail

### ISSUE THREAD

**Issue by alexandr-kazakov** [ampproject/amphtml#23407] opened 2019-07-18 19:53 UTC
## What's the issue?

Styles do not apply to amp-selector option after being sent to gmail.

## How do we reproduce the issue?

I have prepared an example. It is based on an example from here:  https://amp.dev/documentation/examples/components/amp-selector/?referrer=ampbyexample.com
1. Get this is a fully valid AMP4EMAIL code:
```
<!doctype html>
<html ⚡4email>
<head>
  <meta charset="utf-8">
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <script async custom-element="amp-selector" src="https://cdn.ampproject.org/v0/amp-selector-0.1.js"></script>
  <script async custom-element="amp-form" src="https://cdn.ampproject.org/v0/amp-form-0.1.js"></script>
  <script async custom-element="amp-bind" src="https://cdn.ampproject.org/v0/amp-bind-0.1.js"></script>
  <style amp4email-boilerplate>body{visibility:hidden}</style>
<style amp-custom>
.radio-selector [option][selected] {
  outline: none;
}
.radio-selector [option] {
  display: flex;
  align-items: center;
}
.radio-selector [option]:before {
  transition: background 0.25s ease-in-out;
  content: "";
  display: inline-block;
  width: 24px;
  height: 24px;
  margin: .5rem;
  border-radius: 100%;
  border: solid 1px #005AF0;
}
.radio-selector [option][selected]:before {
  text-align: center;
  content: "✓";
  color: #fff;
  background-color: #005AF0;
}
</style>
</head>
<body>
   <div>
    <amp-selector layout="container" class="radio-selector">
      <div option="a" selected>Option A</div>
      <div option="b">Option B</div>
      <div option="c">Option C</div>
      <div option="d">Option D</div>
    </amp-selector>
  </div>
</body>
</html>
```

2. Paste here: https://amp.gmail.dev/playground/
3. And send it to your gmail.

If you are testing locally or on https://amp.gmail.dev/playground/  the is displayed well:
![chrome_2019-07-18_22-37-39](https://user-images.githubusercontent.com/20513262/61486692-b5bc5b00-a9ac-11e9-9b2b-c26550ebef60.png)

But Gmail doesn't use styles:
![chrome_2019-07-18_22-38-34](https://user-images.githubusercontent.com/20513262/61486737-d4baed00-a9ac-11e9-8887-edc004e66222.png)

This is due to the fact that we write styles on the attribute, something like this:

> .radio-selector [option][selected] {}

I don't know exactly what it's about. My other email doesn't work hover in gmail.
Know that if you write styles for a class, it'll work in gmail styles are applied.
For example, such a style entry per class is applied in gmail::
```
 <!doctype html>
 <html ⚡4email>
 <head>
   <meta charset="utf-8">
   <script async src="https://cdn.ampproject.org/v0.js"></script>
   <script async custom-element="amp-selector" src="https://cdn.ampproject.org/v0/amp-selector-0.1.js"></script>
   <script async custom-element="amp-form" src="https://cdn.ampproject.org/v0/amp-form-0.1.js"></script>
   <script async custom-element="amp-bind" src="https://cdn.ampproject.org/v0/amp-bind-0.1.js"></script>
   <style amp4email-boilerplate>body{visibility:hidden}</style>
 <style amp-custom>
 .radio-selector [option][selected] {
   outline: none;
 }
 .radio-selector [option] {
   display: flex;
   align-items: center;
 }
 .radio-selector .item{
  transition: background 0.25s ease-in-out;
  display: inline-block;
  width: 24px;
  height: 24px;
  margin: .5rem;
  border-radius: 100%;
  border: solid 1px #005AF0;
 }
 
 </style>
 </head>
 <body>
    <div>
     <amp-selector layout="container" class="radio-selector">
       <div class="item" option="a" selected>Option A</div>
       <div class="item" option="b">Option B</div>
       <div class="item" option="c">Option C</div>
       <div class="item" option="d">Option D</div>
     </amp-selector>
   </div>
 </body>
 </html>
```

## What browsers are affected?

Chrome 75.0.3770.142

## Which AMP version is affected?

Version 1906141418310

**Comment by choumx** [comment] 2019-07-18 21:14
Thanks for reporting this. This is a duplicate of #23407 and due to lack of CSS attribute selector support in email providers today.

**Closed by choumx** 2019-07-18 21:14 UTC
Labels: Type: Bug

**Comment by alexandr-kazakov** [comment] 2019-07-18 23:20
@choumx What is a duplicate? You gave me a link to my own message.

**Comment by choumx** [comment] 2019-07-19 15:54
🤦‍♂ it's #22894. Sorry about that.
