### ISSUE TITLE
AMP.setState not working on amp-youtube PLAY event

### ISSUE THREAD

**Issue by SoleSS** [ampproject/amphtml#12165] opened 2017-11-22 12:20 UTC
Steps to reproduce problem:
1. add amp-youtube object
2. add any other object <amp-img src=... [class]="objClass"></amp-img>
3. add on event to amp-youtube
<amp-youtube src=... on="play:AMP.setState({objClass: 'hidden'})"></amp-youtube>

but when you click play button of youtube object - nothing happens... (on="tap:..." - works perfect)

**Comment by choumx** [comment] 2017-11-22 15:10
@SoleSS Can you share the HTML you're using?

**Comment by aghassemi** [comment] 2017-11-22 17:42
@SoleSS `tap` events don't work on any element that is 'iframed` (which includes `amp-youtube`). This is due to browser's security model (browsers will not allow the parent of an iframe now about events in that iframe by design).

If you really need to capture the `tap` event, you can use a custom `click-to-player` overlay on top of the `amp-youtube`. See https://ampbyexample.com/advanced/click-to-play_overlay_for_amp-video/ for a reference implementation.

**Comment by aghassemi** [comment] 2017-11-22 17:43
Closing the issue, please feel free to reopen if the answer does not satisfy your use-case.

**Closed by aghassemi** 2017-11-22 17:43 UTC

**Comment by SoleSS** [comment] 2017-11-23 07:59
here's a full code (tap event was just an example):

<amp-youtube
                    on="play:AMP.setState({prom: 'hidden'})"
                    data-param-controls=0 data-param-rel=0 data-param-showinfo=0 data-videoid="*** SOME VIDEO ID ***" layout="responsive" width="1200" height="550"></amp-youtube>

<div class="width-100pc block-overlay top-20pc absolute" [class]="prom"> *** SOME TEXT *** </div>

idea is: on play button click hide all elements which are positioned above video
