### ISSUE TITLE
AMP validator reports base64 images as invalid, but is supported

### ISSUE THREAD

**Issue by MagsMagnoli** [ampproject/amphtml#38702] opened 2023-03-07 22:39 UTC
### Description

amp-img supports base64 encoded images, however the playground and the amphtml-validator project report errors when doing so.

### Reproduction Steps

Add a base64 image to an `amp-img` in the playground or run the amphtml-validator on one

### Relevant Logs

```shell
"Invalid URL protocol 'data:' for attribute 'src' in tag 'amp-img'."
```

**Comment by newmuis** [comment] 2023-03-07 23:14
I think this may be working as intended?  Encoding the image as base64 means that the image must be served as part of the HTML document, slowing down the initial request (and every subresource, since the HTML is needed to know what subresources to fetch).

Loading the image as a separate asset over http(s) allows lazy-loading the assets.

But, cc @erwinmombay to know whether this is intentional or not, for performance reasons.

**Comment by MagsMagnoli** [comment] 2023-06-05 15:47
@newmuis the documentation shows an example using a base64 encoded image. so if it is working as intended then the documentation should be updated

![Screenshot 2023-06-05 at 11 46 40](https://github.com/ampproject/amphtml/assets/4146037/89d3803a-4183-4e2a-b313-d18289304fa8)

**Comment by powerivq** [comment] 2023-07-27 22:21
Verified that, on the online validator and local amphtml-validator, data url would pass validation. Closing this issue for now.

**Closed by powerivq** 2023-07-27 22:21 UTC
Labels: Type: Bug, P1: High Priority, WG: caching
