### ISSUE TITLE
Video placeholder issue with Safari on iPhone

### ISSUE THREAD

**Issue by egianco73** [ampproject/amphtml#2114] opened 2016-02-18 17:10 UTC
Hi,

we have a problem with video embed into AMP pages delivered by Google CDN with iPhone.
At the first loading of the page, the video placeholder isn't showed (as attached a related screencapture).
When the user tap on the placeholder, the video player is loaded
and the video can play fine.

You can see the page as follows:
1) open with Safari on iPhone the URL: http://g.co/ampdemo/it
2) serach for the string "anonymous"
3) tap on the article of Repubblica.it (title: "Anonymous affina le sue armi contro l'IS. E c'è un software scritto da italiani")

Scrolling the page, you can see the issue on placeholder rendering (as attached).

Using Chrome on Android smartphone, the video placeholder is rendered fine.
Loading the AMP page, directly from Safari on iPhone, the placeholder is rendered correctly.

Here you are the URLs:
- web page:
http://www.repubblica.it/tecnologia/sicurezza/2015/11/16/news/anonymous_guerra_isis-127487066/

- AMP page:
https://www.repstatic.it/cless-mobile/main/amp/2016-v1/test/anonymous_guerra_isis-127487066_amp.html

The validation is correct:
https://www.repstatic.it/cless-mobile/main/amp/2016-v1/test/anonymous_guerra_isis-127487066_amp.html#development=1 --> AMP validation successful

The tag video used is the following one:

    <div class="video-container">
        <amp-iframe height=360 width=640
                    layout="responsive"
                    sandbox="allow-scripts allow-same-origin"
                    src="https://video.repubblica.it/embed/dossie
![placehoder-video-issue](https://cloud.githubusercontent.com/assets/17276617/13151388/36fb01ae-d66a-11e5-88d1-3b1af2c0acad.png)
r/sanremo-2016/si-ride-con-virginia-belen--sanremo-mai-avuti-rapporti-con-lui/228476/227766?adref=http://www.repubblica.it/spettacoli/people/2016/02/17/news/bele_n-133591079/&preview=true&responsive=true&_wt_visit_from=webapp.amp">
            <amp-img height=360 width=640 layout="responsive" src="//www.repstatic.it/video/photo/2016/02/12/302990/302990-thumb-full-raffaelebelen.jpg" placeholder></amp-img>
        </amp-iframe>
        <h1>Si ride con Virginia-Belen:  ''Sanremo? Mai avuti rapporti con lui''</h1>
    </div>

Best Regards

**Comment by egianco73** [comment] 2016-02-18 17:17
Hi,

here you are a new example of amp-iframe used to deliver videos:

              <div class="video-container">
                <amp-iframe height=360 width=640
                  layout="responsive"
                  sandbox="allow-scripts allow-same-origin"
                  src="https://video.repubblica.it/embed/dossier/parigi-sotto-attacco/anonymous-dichiara-guerra-all-is-vi-daremo-la-caccia/218615/217816?adref=http://milano.repubblica.it/cronaca/2015/12/27/news/l_autunno_piu_nero_del_triennio_superata_la_media_annuale_ue-130205652/&amp;preview=true&amp;responsive=true&amp;_wt_visit_from=webapp.amp">
                  <amp-img height=360 width=640 layout="responsive" src="//www.repstatic.it/video/photo/2015/11/16/287494/287494-thumb-full-anonymous_16112015.jpg" placeholder></amp-img>
                </amp-iframe>
                <h1>Anonymous dichiara guerra all'Is: "Vi daremo la caccia"</h1>
              </div>


Best Regards

**Comment by dvoytenko** [comment] 2016-02-18 17:22
@sriramkrish85 please take a look. This seems related to our recent changes to iframe's placeholders.

**Comment by sriramkrish85** [comment] 2016-02-18 21:46
cc @dvoytenko 
@egianco73 I was looking into this issue - 

The reason the placeholder is not being shown is the iframe onload gets triggered way before it can actually show something useful, AMP-IFRAME cleans up the placeholder after the iframe's onload event is fired. 

I also see that the video plays fine after a few seconds (may be a min after the iframe loaded), sometimes it helps if i keep tapping the iframe ;) 

I am closing this for now, let me know if you have any questions.

btw: I see that all the images not being displayed have a http:// you should swap them to use https://.

**Comment by cramforce** [comment] 2016-02-18 21:48
To fix this, please update the iframe to do all relevant work immediately,
so that onload only fires at a meaningful time.

**Comment by egianco73** [comment] 2016-02-19 14:22
Hi, 

we have tried also as follows:

https://video.repubblica.it/static/amp_example.php

************* SOURCE ******************
<!doctype html>
<body style="background-color: red">
	iframe - Click to play
	<script>
	parent./*OK*/postMessage({
	  sentinel: 'amp',
	  type: 'embed-ready'
	}, '*');
	document.addEventListener("DOMContentLoaded", function(event) {
	});
	// Add a few elements below to slow triggering of onload function.
	</script>
		<img src="https://www.repstatic.it/video/photo/2015/11/16/287494/287494-thumb-social-play-anonymous_16112015_1.jpg" id="previewImage" style="width: 100%;"  />		
		
</body>
***************************************

as suggested for a clicktoplay iframe solution: 
https://github.com/ampproject/amphtml/blob/c0c9f8889d6aea0cba4301d24a2ab4b97e59d9c7/test/fixtures/served/iframe-clicktoplay.html

without any success with Safari on iPhone.
Meanwhile with Chrome on Android all works fine.

Exactly what do you suggest as workaround?

Regards

**Comment by egianco73** [comment] 2016-02-19 15:07
Hi,

I'll repeat the URLs where we have done the clicktoplay test.

- AMP page where we have the placeholder issue on iPhone with Safari:
https://www.repstatic.it/cless-mobile/main/amp/2016-v1/test/anonymous_guerra_isis-127487066_amp.html

- the provided AMP page loads the following clicktoplay iframe:
https://video.repubblica.it/static/amp_example.php

Regards

**Comment by cramforce** [comment] 2016-02-19 16:55
Just tried on Chrome and iOS and they look the same to me.

**Comment by kul3r4** [comment] 2016-02-19 17:27
I noticed this happens when visualizing inside the carousel on Safari on iPhone and not when opening the page directly with Safari on iPhone. @cramforce could you try that as well and see if you get the same behaviour?

**Comment by cramforce** [comment] 2016-02-19 17:28
@sriramkrish85 Could you try that? Thanks!

**Comment by justforfun** [comment] 2016-02-19 17:40
Hi, I'm a @egianco73 colleague and I confirm that the problem  happens when visualizing inside the carousel on Safari on iPhone and not when opening the page directly with Safari on iPhone

**Comment by sriramkrish85** [comment] 2016-02-19 18:06
@egianco73 , does the iframe fire it's onload before the video is loaded ?

**Comment by justforfun** [comment] 2016-02-19 18:55
Hi the problem happens even if the iframe code contains the code suggested here:
https://github.com/ampproject/amphtml/blob/c0c9f8889d6aea0cba4301d24a2ab4b97e59d9c7/test/fixtures/served/iframe-clicktoplay.html
You can find this iframe as the last one of the amp page
https://www.repstatic.it/cless-mobile/main/amp/2016-v1/test/anonymous_guerra_isis-127487066_amp.html

**Comment by sriramkrish85** [comment] 2016-02-19 20:02
@justforfun  so the code suggested is being used for unit testing. 

Immediately after you send the `embed-ready` message the `amp-iframe` thinks that the iframe contents are ready for display and hence it deletes the placeholder. 

So you should only be sending that message when you are sure that the contents of the iframe are ready for display (or just defer to the iframe's `onload`).

**Comment by justforfun** [comment] 2016-02-19 22:05
Perhaps there's a misunderstanding.
What's happening to us  is that the image inside the iframe isn't being displayed after the amp-iframe's placeholder has been deleted.
This happens only on iOS and only if the amp page has been loaded via the search carousel.
Moreover the image loaded inside the iframe is not displayed even after a minute, so it isn't a matter of delayed visualization but of missed visualization

**Comment by sriramkrish85** [comment] 2016-02-19 23:05
@justforfun 
I am not sure - what do you mean by `inside the iframe` ? 
I see this in your code
```
<amp-iframe height=360 width=640
                  layout="responsive"
                  sandbox="allow-scripts"
                  src="https://video.repubblica.it/static/amp_example.php">
                  <amp-img layout="fill" src="https://www.repstatic.it/video/photo/2015/11/16/287494/287494-thumb-full-anonymous_16112015.jpg" placeholder></amp-img>
                </amp-iframe>
```
Here the placeholder is 

```
<amp-img layout="fill" src="https://www.repstatic.it/video/photo/2015/11/16/287494/287494-thumb-full-anonymous_16112015.jpg" placeholder></amp-img>
```
And yes we remove this after receiving `embed-ready` or `onload`. 

AMP does not have any control over the contents of the iframe. 

The reason you are not seeing the `<amp-img src='...' placeholder>` is because you are firing `embed-ready` too soon.

My suggestion for you would to to remove the `embed-ready` message in your iframe and see what happens.

You could also ping me on our slack channel. 
https://github.com/ampproject/amphtml/blob/master/DEVELOPING.md

**Comment by justforfun** [comment] 2016-02-20 18:25
I'm sorry we didn't ourselves clear enough.
The matter is not the placeholder of the the <amp-iframe> element that is working fine and disappearing when expected.
The problem is quite different and I try to explain it again.
For instance let's take this page:
https://www.repstatic.it/cless-mobile/main/amp/2016-v1/test/anonymous_guerra_isis-127487066_amp.html

where you can find this <amp-iframe>  element:

`<amp-iframe height=360 width=640
          layout="responsive"
          sandbox="allow-scripts allow-same-origin"
          src="https://login.kataweb.it/static/testcert/test-iframe.html">
          <amp-img height=360 width=640 layout="responsive" src="//www.repstatic.it/video/photo/2016/01/26/299328/299328-thumb-social-play-taxieaerei_1.jpg" placeholder></amp-img>

The iframe's (https://login.kataweb.it/static/testcert/test-iframe.html) HTML code is the simplest you could have:
`<!doctype html>
<body style="background-color: red">
iframe - Click to play
Hello World!
<img src="https://www.repstatic.it/video/photo/2016/02/12/302990/302990-thumb-taboola-2x-raffaelebelen.jpg"></img>
</body>`

Even with this code the content of the iframe is not visible on the AMP page.
This happens only when you access the AMP page from the carousel on Safari on iPhone.
To access the page from the carousel:

1) go to https://g.co/ampdemo/it
2) search for anonymous

**Comment by justforfun** [comment] 2016-02-21 08:41
Hi, we still have the problem even after the fix

**Comment by erwinmombay** [comment] 2016-02-21 09:01
@justforfun howdy, we havent done a release yet. we'll keep you up to date when we do so and it *should* be fixed. feel free to track progress of release here

**Comment by cramforce** [comment] 2016-02-21 20:48
Should be available in [dev channel](https://github.com/ampproject/amphtml#amp-dev-channel) in about 60 minutes

**Comment by cramforce** [comment] 2016-02-21 21:55
Not fixed by patch

**Comment by cramforce** [comment] 2016-02-22 00:51
This is now fixed, but only when Safari DevTools are open. LOL

**Comment by cramforce** [comment] 2016-02-22 04:01
Now fixed on dev channel. Thanks @dvoytenko

**Closed by cramforce** 2016-02-22 04:01 UTC
Labels: Priority: Critical, Type: Bug

**Comment by cramforce** [comment] 2016-02-22 04:44
By the way: It appears your video is broken on Safari. Most likely this is the case because it serves over HTTP.

**Comment by justforfun** [comment] 2016-02-22 06:37
Hi,
on my iPhone Safari I've just switched the dev channel on and now videos
seem to work fine now in La Repubblica AMP pages.
Where did you encounter a broken video?
Thank you
Luigi

**Comment by cramforce** [comment] 2016-02-22 15:03
In the iOS simulator. Great to hear things are working!
