### ISSUE TITLE
AMP analytics support of getTriggerElementAttribute(attribute_name) for triggers with specific element.

### ISSUE THREAD

**Issue by Gueorgi** [ampproject/amphtml#5402] opened 2016-10-04 18:50 UTC
The ebay implementation adding [variables as data attributes](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/analytics-vars.md#variables-as-data-attribute) is good but really limited and requires non-trivial modifications to existing pages. It also makes the whole document larger even when data about common attributes like class & id is sought.

A more generic and better approach could be to introduce a pseudo function (like getClientId one for cookies) getTriggerElementAttribute(attr_name) that can grab any attribute value of an element and thus avoid the need for addtioanl mark-up of all the elements in a page.

As with the variables as data attributes, this pseudo function works only upon click & visible events where there is an element being the target of the event. If the attribute is not found in the current element it can look up the parent one till the dom root to find it.

In future additions can be made like being able to specify couple of attributes to look for in order and return the value of the first one that is found. For example a click may happen on a link, image, button etc. and if the target value is needed the pseudo-function could look like this:
getTriggerElementAttribute([src, href, action])

**Comment by zhouyx** [comment] 2019-07-02 17:56
Duplicate of #5402. Closing

**Closed by zhouyx** 2019-07-02 17:56 UTC
Labels: Category: Analytics, P3: When Possible, Type: Feature Request

**Comment by Gueorgi** [comment] 2019-07-02 23:52
So closing #5402 because it is duplicate of... itself #5402?
@zhouyx can you update the comments to show what other (different then this, i.e. not 5402) issue this was duplicate of?

**Comment by zhouyx** [comment] 2019-07-03 01:19
LOL
@Gueorgi nice catch! I'm sorry, duplicate of #10864
