### ISSUE TITLE
amp-story: Content from other inactive pages is available to screen readers

### ISSUE THREAD

**Issue by TetraLogicalHelpdesk** [ampproject/amphtml#32498] opened 2021-02-08 15:57 UTC
# Content from other inactive pages is available to screen readers

## WCAG Level
Level A

## Priority
High

## Pages/screens/components affected
* [Tooltip](https://www.gstatic.com/amphtml/stamp/qa/tooltip.html)
* [AMP Story Player - Player](https://www.gstatic.com/amphtml/stamp/qa/player.html)

## Description
While generally inactive pages in a story are correctly hidden from assistive technologies, we noted two cases - in [Tooltip](https://www.gstatic.com/amphtml/stamp/qa/tooltip.html) and [AMP Story Player - Player](https://www.gstatic.com/amphtml/stamp/qa/player.html) - where content from other pages was still reachable by assistive technology users.

## User impact
If screen readers are not restricted to reading the contents of the current page in a story, users can easily get lost by navigating into content that is not supposed to be available.

## Required solution
Make sure that content in inactive pages is hidden from all users, including those who use a screen reader.

This solution must be applied to all instances of the issue identified within the test sample, then applied to all other instances of the same issue identified throughout the rest of the website.

## Implementation guidance
In [Tooltip](https://www.gstatic.com/amphtml/stamp/qa/tooltip.html) the embedded tweet content from the first slide remains available to assistive technology users on any subsequent pages.

![Illustration of NVDA's reading focus, showing that the embedded tweet in the previous page of the AMP story is being read out, even though that page is dimmed and inactive](https://user-images.githubusercontent.com/54933393/107245823-81453f80-6a27-11eb-9a24-8a8383e7ad81.png)

In [AMP Story Player - Player](https://www.gstatic.com/amphtml/stamp/qa/player.html), using reading keys, it is possible for an assistive technology user to continue reading beyond the first page and into the next one - this is likely due to the way the story is actually constructed from two separate sub-stories that are being "grafted" together dynamically.

![Screenshot of the story player showing a broken visual layout, with the two stories/pages being shown, when using reading keys in NVDA](https://user-images.githubusercontent.com/54933393/107245918-9ae68700-6a27-11eb-874e-434417b56ccb.png)

In both these cases, make sure that only content from the current active page/story is exposed to assistive technologies.

At a high level, this can be achieved by adding `aria-hidden` on the content (as is already the case in most other samples tested), and dynamically setting this attribute to `true`/`false` when the page becomes active/inactive.

## Test procedure(s)
Use these steps to confirm that the solution has been correctly applied to issues identified within the test sample, and to test the rest of the website for instances of the same issue:
1. Turn on a screen reader.
2. Navigate through each page of the story.
3. On each page, use the up/down arrow keys to navigate through the content.
4. Check that only the currently active/visible content of the page is announced.

### Definition of done
Complete all of these tasks before closing this issue or indicating it is ready for retest:
* All issues identified within the test sample have been resolved.
* The rest of the website has been tested for the same issue.
* All issues identified throughout the rest of the website have been resolved or filed as new issues.

## Related standards
* [WCAG 2.1 Success Criterion 1.3.2 Meaningful Sequence (Level A)](https://www.w3.org/TR/WCAG21/#meaningful-sequence)

## Test data
Test date: February 2021

**Comment by gmajoulet** [comment] 2021-02-22 02:43
Might be a duplicate of #31747

**Comment by processprocess** [comment] 2021-02-23 21:24
> Might be a duplicate of #31747

This is a duplicate of #31747 and contributes to #32506

**Comment by gmajoulet** [comment] 2021-02-26 19:16
Feel free to close it if everything is tracked in these other tickets!

**Comment by gmajoulet** [comment] 2021-03-08 17:32
@processprocess @mszylkowski can this be closed?

**Comment by mszylkowski** [comment] 2021-03-09 14:17
Not sure about the issue with the player, @Enriqe might know. Also `amp-twitter` is not fixed yet

**Comment by mszylkowski** [comment] 2021-04-20 18:23
Update on this issue: `amp-twitter` will be fixed by #33919, now we just need to fix the `amp-story-player` issue.

> In AMP Story Player - Player, using reading keys, it is possible for an assistive technology user to continue reading beyond the first page and into the next one - this is likely due to the way the story is actually constructed from two separate sub-stories that are being "grafted" together dynamically.

@Enriqe do you have this tracked somewhere / did you check this still occurs?

**Comment by Enriqe** [comment] 2021-04-21 12:12
I haven't checked yet. I'll assign myself to this issue and take a look when I get a chance, though.

**Comment by gmajoulet** [comment] 2021-08-05 18:23
Created https://github.com/ampproject/amphtml/issues/35545 to track the Player specific issue, and closing this one as the Stories format is fixed.

**Closed by gmajoulet** 2021-08-05 18:23 UTC
Labels: Type: Bug, Related to: Accessibility, P1: High Priority, WG: stories, Type: Accessibility
