### ISSUE TITLE
Images not loading in <amp-user-notification>

### ISSUE THREAD

**Issue by TH-NK-JamesAllis** [ampproject/amphtml#18923] opened 2018-10-24 14:33 UTC
I'm having an issue with an `<amp-img>` within an `<amp-user-notification>`.  

On my page i have 2 `<amp-user-notification>'s` and if i include an image on the first one then it intermittently will load the image and replace the placeholder, it seems to be tied to the loading of other visible images currently in the viewport.

However, if i add an image to the second `<amp-user-notification>` (which gets displayed when i dismiss the first one) then that image doesn't ever seem to get loaded.

Anyone else had a similar issue?

Thanks in advance,

**Comment by aghassemi** [comment] 2018-10-25 16:38
@TH-NK-JamesAllis Do you have a repro URL?

/to @jridgewell

**Comment by choumx** [comment] 2019-01-07 17:15
@TH-NK-JamesAllis We'll need a URL to a live page that exhibits this error to investigate. Will reopen once it's available.

**Comment by devignerforhire** [comment] 2019-04-29 14:26
@choumx I've noticed this on our site too. You can see this issue here -> https://winefolly.com/tutorial/wine-sweetness-chart/ (scroll down to see the user-notification slide in. If you resize the browser, the image shows up. Any ideas?

**Comment by choumx** [comment] 2019-04-30 15:16
In that case, looks like the amp-img sometimes takes a few seconds to get `layoutCallback` after it animates from off-screen to on-screen position.

@aghassemi Does `amp-animation` ensure that AMP components receive correct lifecycle callbacks during animations? Poked around a bit and didn't find anything obvious.

Possibly related to #15939.

**Comment by aghassemi** [comment] 2019-04-30 17:12
@choumx it is same issue as https://github.com/ampproject/amphtml/issues/19269 and there are some discussions there between me and @jridgewell about potential solutions.

@devignerforhire Using `amp-fx="fly-in-right"` from `amp-fx-collection` extension( https://amp.dev/documentation/examples/components/amp-fx-collection/ ) instead of `amp-animation` would both be lighter and should resolve this issue.

**Comment by choumx** [comment] 2019-04-30 20:58
Thanks. Closing as dupe of #19269.

**Closed by choumx** 2019-04-30 20:58 UTC
Labels: Category: Runtime

**Comment by devignerforhire** [comment] 2019-05-01 05:58
@aghassemi Thanks Ali! I did try the amp-fx="fly-in-right" before, but had some issues getting it working properly. I'll give it another try and let you know how it goes :)

**Comment by devignerforhire** [comment] 2019-05-01 11:26
@aghassemi I updated our staging site to use amp-fx and it's working, but I can't seem to get it to slide in when you reach the bottom of the page and slide when you start scrolling up. Should I be adding a marker to delay triggering the animation?

**Comment by Tymvie** [comment] 2019-06-09 06:24
I have prepared an example that has nothing to do with animations: https://codepen.io/anon/pen/rgXoBM
After dismissing the first notification, the image inside of the second notification does not become visible
