### ISSUE TITLE
[amp-story-player] show and go method does not load story

### ISSUE THREAD

**Issue by edoudou** [ampproject/amphtml#32676] opened 2021-02-16 14:17 UTC
**Critical issue as it make the player with multiple stories barely usable.**

## What's the issue?

When under some precise condition, the `show` or `go` method does not load the stories inside a player.

## How do we reproduce the issue?

Tricky way to reproduce every time :
1. Go on a page with a player containing multiple stories (cf examples)
2. Start on the first and read every stories using swipe / tap to next feature.
3. Refresh the page
4. Try to use the `show` (or `go`) method on one of the last stories (3rd to last seems to do the trick)
In examples below, a button is provided to use the method. 

## What browsers are affected?

Tried on latest version of chrome and FF, but also on android and iOs.

## Which AMP version is affected?

Issue appears on latest stories.

### Code samples
- https://codesandbox.io/s/runtime-pine-jt8zy?file=/index.html
- https://codesandbox.io/s/adoring-flower-rxvpn?file=/index.html

### Live example
- https://www.cdiscount.com/maison/v-117-0.html#nav=Meuble%20D%C3%A9co_txt

**Comment by gmajoulet** [comment] 2021-02-16 16:47
@Enriqe is looking into it and will determine whether this is a P0 or P1

**Comment by Enriqe** [comment] 2021-02-16 17:59
I just spend some time debugging and the issue seems to be gone in the newest pre-release ([2102060044001](https://github.com/ampproject/amphtml/releases/2102060044001)) which is the latest beta and will be released later today to stable.

I’m still not sure what caused the issue but it’s very possible that it’s an issue with the old implementation which didn’t include the newest refactoring.

I’ll keep you updated on the status of the release so you can verify the issue is gone.

**Comment by Enriqe** [comment] 2021-02-17 18:07
New release has been promoted to stable today. I also tried out the samples and confirmed I can't repro the issue anymore.

**Closed by Enriqe** 2021-02-17 18:07 UTC
Labels: P1: High Priority, Type: Bug, WG: stories
