### ISSUE TITLE
validator.validateString() returns RuntimeError: Aborted

### ISSUE THREAD

**Issue by di-ruan** [ampproject/amphtml#38225] opened 2022-05-24 03:52 UTC
### Description

Use the validator.validateString() in a Node.js server endpoint and got the following errors after a few hours.
```
RuntimeError: Aborted(OOM). Build with -s ASSERTIONS=1 for more info.
    at F (evalmachine.<anonymous>:1771:386)
    at dc (evalmachine.<anonymous>:1796:489)
    at sbrk (wasm-function[2497]:0x10002a)
    at dlmalloc (wasm-function[2488]:0xfde86)
    at operator new(unsigned long) (wasm-function[3968]:0x119998)
    at htmlparser::Allocator<htmlparser::Node>::NewBlock() (wasm-function[835]:0x818f9)
    at htmlparser::Document::NewNode(htmlparser::NodeType, htmlparser::Atom) (wasm-function[836]:0x81a27)
    at htmlparser::Parser::AddElement() (wasm-function[406]:0x52b8d)
    at htmlparser::Parser::InBodyIM() (wasm-function[376]:0x4d3e9)
    at std::__2::__function::__func<std::__2::__bind<bool (htmlparser::Parser::*)(), htmlparser::Parser*>, std::__2::allocator<std::__2::__bind<bool (htmlparser::Parser::*)(), htmlparser::Parser*> >, bool ()>::operator()() (wasm-function[448]:0x56a0f)
evalmachine.<anonymous>:1771
g.charCodeAt(++u);x=65536+((x&1023)<<10)|w&1023}z[k>>2]=x;k+=4;if(k+4>l)break}z[k>>2]=0;return k-p}function A(g){for(var k=0,l=0;l<g.length;++l){var p=g.charCodeAt(l);55296<=p&&57343>=p&&++l;k+=4}return k}function I(g){var k=f(g)+1,l=ka(k);l&&e(g,X,l,k);return l}function F(g){if(r.onAbort)r.onAbort(g);g="Aborted("+g+")";aa(g);wa=!0;g+=". Build with -s ASSERTIONS=1 for more info.";g=new WebAssembly.RuntimeError(g);xa(g);throw g;}function M(g){try{if(g==L&&fa)return new Uint8Array(fa);var k=ya(g);if(k)return k;
```

### Reproduction Steps

Start the node js server and notice the OOM issue above after a few hours and won't recover.
```
/**
 * Validation endpoint.
 */
function validate(req, res, next) {
  const result = req.validator.validateString(html);
  res.send(200, result);
  next();
}

/**
 * Main program entry point.
 */
function main() {
  ...
  ampValidator.getInstance().then((validator) => {
    server.on('request', (req, res, route, err) => {
      req.validator = validator;
    });
    return true;
  });

  server.post('/validate', validate);
  ...
```

### Browser(s) Affected

Chrome

### OS(s) Affected

Linux

### AMP Version Affected

1.0.35

**Comment by honeybadgerdontcare** [comment] 2022-05-24 22:37
@amaltas can you look at this and reassign as necessary. note the issue is the node.js server after a few hours runs out of memory

**Comment by amaltas** [comment] 2023-03-02 15:39
Can you please share the HTML that you were trying to validate. Looks like some unicode parsing issue, but cannot debug or reproduce without the actual HTML that is causing this OOM.

**Comment by darbentov** [comment] 2023-07-11 09:36
Hi @di-ruan we faced the same issue as you're facing.. Were you able to overcome it? Can you share your solution if so :) 
Thanks

**Comment by erwinmombay** [comment] 2023-08-21 23:54
closing as stale, but please re-open if you have a reproduction example

**Closed by erwinmombay** 2023-08-21 23:54 UTC
Labels: Type: Bug, WG: caching
