### ISSUE TITLE
Amp-carousel - allow 2 items to loop

### ISSUE THREAD

**Issue by bjalford** [ampproject/amphtml#14049] opened 2018-03-16 15:51 UTC
Currently the amp-carousel wont loop when only 2 items in carousel (requires 3+) . Is there a reason it can't be reduced so two items could loop?

**Comment by cathyxz** [comment] 2018-03-16 21:03
Genius. ^^
I did not think of that.

**Comment by nainar** [comment] 2018-03-16 21:05
Related to #5164

**Comment by cathyxz** [comment] 2018-04-06 17:58
Closing this as a dupe of #5164

**Closed by cathyxz** 2018-04-06 17:58 UTC
Labels: Category: Presentation, Type: Feature Request
