### ISSUE TITLE
Validator fails for mustache template variables inside template node

### ISSUE THREAD

**Issue by src-code** [ampproject/amphtml#2670] opened 2016-03-22 21:37 UTC
The validator as of v1457721872758 fails when including a mustache template inline, such as in an `amp-list`.  For example, the following markup should be valid:

```html
<script async custom-template="amp-mustache" src="https://cdn.ampproject.org/v0/amp-mustache-0.1.js"></script>
...
<amp-list src="https://www.example.com/amp/feed?RANDOM" width="auto" height="200" layout="fixed-height">
  <template type="amp-mustache">
    <amp-img src="{{image.url}}" width={{image.width}} height={{image.height}}></amp-img>
  </template>
</amp-list>
```

The validator produces the following error:

```
The attribute 'width' in tag 'amp-img' is set to the invalid value '{{image.width}}'.
```

cc @dvoytenko @Gregable

**Comment by Gregable** [comment] 2016-03-22 22:02
I can reproduce. The issue is not new and is specific to the tag layout calculation which handles `width`/`height` in a different way that most attributes. `src` is a non-issue, for example. This is a little tricky because it's impossible to determine if layout is legal in the presence of mustache template variables.

**Comment by dvoytenko** [comment] 2016-03-23 00:25
@Gregable I see. In this case, we have to skip this part of validation in template. Perhaps to reduce the negative impact, we can only skip it when width/height/layout and other related values use expressions in them.

**Comment by Gregable** [comment] 2016-03-23 00:28
Agreed.

**Comment by rudygalfi** [comment] 2016-03-30 21:54
Is there an open PR for this?

**Comment by Gregable** [comment] 2016-03-30 21:57
Not yet.

**Comment by rudygalfi** [comment] 2016-03-30 21:58
OK, moving to next milestone. Thanks for the update!

**Comment by rudygalfi** [comment] 2016-04-13 23:26
@Gregable ping? Should we roll into next sprint or into backlog?

**Comment by Gregable** [comment] 2016-04-13 23:36
This one is 'done', I'm working on releasing it to github as we 'speak'.

**Closed** 2016-04-14 00:30 UTC
Labels: Related to: Validator, Type: Bug

**Comment by Gregable** [comment] 2016-04-14 00:34
This will go live to in-browser validation next week most likely.

**Comment by Gregable** [comment] 2016-04-25 21:57
This is live everywhere.
