### ISSUE TITLE
Uncaught Error: failed to call initLogConstructor

### ISSUE THREAD

**Issue by ThongSaltire** [ampproject/amphtml#24469] opened 2019-09-11 18:55 UTC
## What's the issue?

If we place an amp-carousel inside the amp-iframe, the carousel will not work. It produces the error: Uncaught Error: failed to call initLogConstructor. This doesn't happen on the older version of amp.The error just appeared recently with the latest update of amp. So if we use the old version "https://cdn.ampproject.org/rtv/011908201719490/v0.js", the carousel works normally without this error. 

## How do we reproduce the issue?
Test Link:
https://jsfiddle.net/xLutfw46/12/

- We placed a hosted link of our carousel under an iframe, as you can see the carousel doesn't work
- The error Uncaught Error: failed to call initLogConstructor appears on the Console Tab.
- If we change to https://cdn.ampproject.org/rtv/011908201719490/v0.js instead of https://cdn.ampproject.org/v0.js, in the header of rs-recommended.php, the carousel will work

## What browsers are affected?

All browsers

## Which AMP version is affected?
Amp-version: 1909051756330 
This is a new issue. Our site used to work fine before
Before screenshot:
![before](https://user-images.githubusercontent.com/54289781/64726218-01f6b980-d48b-11e9-9436-db69f93c0ca3.PNG)
After screenshot:
![after](https://user-images.githubusercontent.com/54289781/64726223-058a4080-d48b-11e9-8ea5-b3c224308d3d.PNG)

**Comment by choumx** [comment] 2019-09-16 22:56
Looks like a duplicate of #24469 and should be fixed in the latest release.

**Comment by ThongSaltire** [comment] 2019-09-16 22:56
It looks like that it's related to the bug #24454

**Closed by choumx** 2019-09-16 22:56 UTC
Labels: Type: Bug
