### ISSUE TITLE
Improve validation error messagess

### ISSUE THREAD

**Issue by nbeloglazov** [ampproject/amphtml#1366] opened 2016-01-09 01:15 UTC
I'm trying to convert a big html file into AMP-html and using `#development=1` to validate if its correct. But some errors are not very useful, example: `MANDATORY_ATTR_MISSING type`. Error message also provides line/column but when html minified it's hard to understand. I think it would be useful to provide name of the tag that violated requirement. Also I believe most validation errors [provide link](https://github.com/ampproject/amphtml/tree/master/validator) to the specification page but this one didn't have such link which made it harder to debug. 

Thanks,
Nikita

**Comment by cramforce** [comment] 2016-01-10 17:09
Might be a dupe of #1307 (which we are working on).

But @powdercloud @Gregable Could we improve this particular message by including more context information?

@nbeloglazov I recently submitted a change that will make the error messages clickable again in chrome devtools to point to the right tag. This was broken for a while, due to a bug in Chrome DevTools with fragment URLs.

**Comment by Gregable** [comment] 2016-01-11 17:54
I think this is actually a dupe of #246. We still need to decide on a formatting string for that one, but that's a minor detail.

**Comment by nbeloglazov** [comment] 2016-01-11 17:56
Yes,  #246 looks like what I had in mind. Feel free to close as dup.

**Comment by Gregable** [comment] 2016-01-11 18:07
Thanks, closing. I'm unsure if github has an official way to mark as dupe.

**Closed by Gregable** 2016-01-11 18:07 UTC
Labels: Related to: Validator
