### ISSUE TITLE
Embed AMP story player doesn't work on FFox browser MacOS

### ISSUE THREAD

**Issue by Ichigo3d** [ampproject/amphtml#28909] opened 2020-06-16 18:26 UTC
## What's the issue?
Embed AMP story player doesn't work on FFox browser MacOS.
It shows blank screen in embed page.

## How do we reproduce the issue?

1. Go to https://amp.dev/documentation/guides-and-tutorials/integrate/embed-stories/
2. Observe result
## What browsers are affected?

only FFox MacOS

## Which AMP version is affected?
2006050512000
This issue is related to https://github.com/ampproject/amphtml/issues/28777
<img width="959" alt="Screen Shot 2020-06-16 at 11 25 55 AM" src="https://user-images.githubusercontent.com/37351864/84813049-32442900-afc4-11ea-96de-96fae7d92fcb.png">

**Comment by Enriqe** [comment] 2020-06-16 18:52
Duplicate of #28777

**Closed by Enriqe** 2020-06-16 18:52 UTC
Labels: P1: High Priority, Type: Bug, WG: stories
