### ISSUE TITLE
<amp-img> is not loading on Firefox 58

### ISSUE THREAD

**Issue by kenrick95** [ampproject/amphtml#12065] opened 2017-11-15 06:35 UTC
Images on `<amp-img>` is not being loaded on Firefox 58

## What's the issue?

![screen shot 2017-11-15 at 2 31 44 pm](https://user-images.githubusercontent.com/3090380/32822074-bc18a26e-ca11-11e7-9717-9cc99ce14cbb.png)
![screen shot 2017-11-15 at 2 37 42 pm](https://user-images.githubusercontent.com/3090380/32822237-7d81421c-ca12-11e7-9c51-bc825ded193b.png)

## How do we reproduce the issue?

Open https://www-ebay-com.cdn.ampproject.org/c/s/www.ebay.com/b/amp/Camera-Drones/179697/bn_89951 at Firefox 58

## What browsers are affected?

Firefox 58 (currently in Firefox Dev Edition)

Firefox 57 (stable) and Chrome (stable) are not affected.
Firefox 59 (nightly) is also not affected

## Which AMP version is affected?

Version 1510180045130. Not sure about other versions.

**Comment by QES** [comment] 2017-11-15 11:50
Just had a thought have you checked there is no ad blocking solution running by default.  In the last I have seen ad blocking solutions remove all the images on amp sites.  I saw a similar but worse problem on the desktop version of Opera this morning.

**Comment by jridgewell** [comment] 2017-11-15 22:59
I'm unable to reproduce in v58. Do you have an adblocker installed? If so, which? That way we can fix the damn thing.

**Comment by kenrick95** [comment] 2017-11-16 01:41
This is indeed very strange, this only happens at Firefox 58 of my work laptop. I tried on Firefox 58 on my personal laptop and it is working fine. I tried to clear browser cache, disable all addons, disable "Tracking protection", tried in private mode, etc. without any success.

**Comment by choumx** [comment] 2017-12-05 20:31
Might be an enterprise policy browser setting for your work laptop. Closing since this sounds like a one off.

**Closed by choumx** 2017-12-05 20:31 UTC
