### ISSUE TITLE
Error: Cannot read property 'contains' of null

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#21114] opened 2019-02-26 21:31 UTC
Error: Cannot read property 'contains' of null
at scrollHeight (https://raw.githubusercontent.com/ampproject/amphtml/1902191749350/src/service/viewport/viewport-binding-ios-embed-wrapper.js:236)
at getScrollHeight (https://raw.githubusercontent.com/ampproject/amphtml/1902191749350/src/service/viewport/viewport-binding-ios-embed-wrapper.js:235)

go/amp-error/CPqUoPDi2JCAugE

**Comment by jridgewell** [comment] 2019-07-19 21:52
Closing as a dupe of https://github.com/ampproject/amphtml/issues/20691

**Closed by jridgewell** 2019-07-19 21:52 UTC
Labels: Type: Bug
