### ISSUE TITLE
How to display server-side validation errors for amp-forms?

### ISSUE THREAD

**Issue by weeblr** [ampproject/amphtml#6058] opened 2016-11-07 18:45 UTC
Hi

Have done some amp-forms to post comments on CMS, that's working fine. I have a hard time to provide a good workflow to users though.

I have a "standard" markup for the response:

````
<div submit-success>
	<template type="amp-mustache"><div class="wbamp-comment-status">Thanks for leaving a comment!<br />Please refresh the page to view an updated comment list. {{message}}</div>
	</template></div>
<div submit-error>
	<template type="amp-mustache"><div class="wbamp-comment-status">Sorry, there was a problem posting your comment! {{message}}</div>
````

Data is POSTed with ajax (form has action-xhr attribute).

Server side, I am validating the input, and return some json that includes a "message' properties, which is rendered into the mustache template. 

1.  if the input is valid, and response returned is a 200, the "message" property is rendered in the submit-success mustache template, and all is good. Well almost, as the **message seems to be escaped**, which prevents me from returning HTML in the message. Is that expected?

2. If the server does not reply, or reply with a 40X status code, the "submit-error" template is rendered (and no "message" is inserted, as no json response was provided. All good.

3.  If the server replies, but the input was not valid (ie duplicate comment, bad language, etc), the server returns some json with the "message" property filled with a message explaining the reason to refuse that comment.

Now the problem is:

- if the status code is 200, then the "submit-success" template is rendered, while we want to render the "submit-error" template, and keep the input fields visible.
- if the status code is 40X, then the "submit-error" template is indeed rendered, but the "message" property of the json is not inserted in the template. Meaning we cannot tell the user anything else than "Sorry, there was a problem, try again later".

Questions are:

a/ am I missing something?
b/ how should I signal a failure to accept the posted form, while still displaying the error message?

Thanks for any input

Rgds

**Comment by mkhatib** [comment] 2016-11-07 22:01
> as the message seems to be escaped, which prevents me from returning HTML in the message. Is that expected?

Yes, that's the expected behavior from mustache templates. However, you can render limited html tags using the triple-mustache syntax like: `{{{htmlFormattedMessage}}}` 

To answer:
> if the status code is 200, then the "submit-success" template is rendered, while we want to render the "submit-error" template, and keep the input fields visible.

and: 

> b/ how should I signal a failure to accept the posted form, while still displaying the error message?


`submit-error` is strictly rendered when the response from the server is not a success - i.e. not 2xx status. So if you'd like to trigger that path when the input is invalid just update the status the server returns to be 3xx, 4xx or 5xx. If you still want to use a 200 status you can conditionally render an error path inside `submit-success` like:

```html
<div submit-success>
  <template type=amp-mustache>
     {{#error}}
        <div class="alert">{{errorMessage}}</div>
     {{/error}}
     {{^error}} <!-- if not error -->
        <div class="success">{{successMessage}}</div>
     {{/error}}
  </template>
</div>
```

Generally I'd advice to avoid doing this and stick to returning the correct status that reflect the status of the form otherwise `amp-form` would send analytics events and set classes that doesn't really reflect the correct state of the submission - for example it would add `.amp-form-submit-success` class on the `<form>` element but technically the form submission wasn't a success in your case.


> if the status code is 40X, then the "submit-error" template is indeed rendered, but the "message" property of the json is not inserted in the template. Meaning we cannot tell the user anything else than "Sorry, there was a problem, try again later".

Was this `40X` status returned by your server? If yes, then you should still be able to add any fields to the body as JSON and it'll get rendered correctly in `submit-error`, for example, check the `[form.amp.html](https://github.com/ampproject/amphtml/blob/master/examples/forms.amp.html#L208)` ([server handler here](https://github.com/ampproject/amphtml/blob/master/build-system/server.js#L164)) example to see an example of a `500` status, this should also work with a `4XX` status.

```nodejs
app.use('/form/echo-json/post', function(req, res) {
  assertCors(req, res, ['POST']);
  var form = new formidable.IncomingForm();
  form.parse(req, function(err, fields) {
    res.setHeader('Content-Type', 'application/json');
    if (fields['email'] == 'already@subscribed.com') {
      res.statusCode = 403;
    }
    res.end(JSON.stringify(fields));
  });
});
```

```html
    <div submit-error>
        <template type="amp-mustache">
            Oops! {{name}}, We apologies something went wrong. Please try again later.
        </template>
    </div>
```

Hope this answers all your questions, do let me know if something is still unclear, for now closing this as all of this working as intended.

**Closed by mkhatib** 2016-11-07 22:01 UTC
Labels: Type: Discussion

**Comment by weeblr** [comment] 2016-11-08 08:20
Hi @mkhatib 

Thanks for your detailed answer, my question was probably not clear enough. To make it clearer now:

1. I understood all of this, and the server response behaved accordingly (ie 200 response when valid, 403 when comment rejected)
2. It was **not working as intended**: 

- with a 200 response, the template was correctly used by AMP runtime and my success message was inserted
- with a 403 response (tried also with 404 and 500), the template was displayed, but the {{message}} tag was **not** replaced by the message provided in the json response.

After looking more into the response headers this morning, I added a "Content-Type: application/json" to the error response, and that fixed the problem.

So it's working as intended, assuming you have the "application/json" Content-type header. What trumped me is that this header is **not required** for the "Success" response, status 200. With such response, the json in the server response is properly interpreted and inserted in the template.

So the difference in behavior is as follow:

- 200 & Content-type = "text/html" -> template displayed and tags replacement happens normally
- 4XX & Content-type = "text/html" -> template displayed but no tags replacement
- 4XX & Content-type = "application/json" -> template displayed and tags replacement happens normally

Thanks for the {{{}}} mustache syntax tip, I'll try use it today.

Rgds

**Comment by mkhatib** [comment] 2016-11-08 20:24
Aah. Glad you figured it out and sorry about the inconsistencies. Unfortunately you were hitting #3667.

Requiring json content-type is the correct behavior and that issue I linked to is to investigate and see if we can enforce that for 200-status without backward incompatibility issues. Unfortunately if publishers have been sending the wrong content-type changing that now would cause some breakages so we'd have to be careful about it.

I suggest you always return `Content-Type` json to be consistent.

**Comment by weeblr** [comment] 2016-11-09 11:22
Hi @mkhatib 

Thanks for linking to that issue, and I wholeheartedly agree with you that it basically only needs to be documented.

It would only require to add, in a prominent manner that:

- submit-success is for 2XX responses, submit-error is triggered for any other response code
- action-xhr response must have content-type application/json

If you know that, there is no problem anymore.

Rgds

**Comment by sktvl** [comment] 2017-06-16 07:17
Hi @mkhatib,

iam newbie in AMP Form .  how we can show success or error messages in same view.  As soon as possible please describe same code here

**Comment by HimanshuP90** [comment] 2019-02-19 19:58
@aghassemi  @mkhatib 
I have problem with **submit-error**, when I'm submitting form getting error in response like that message1: 'Please enter correct no.', message2: 'Please type correct'.
`on="submit-success:AMP.navigateTo(url=event.response.navigateTo); submit-error:AMP.setState({ message1: event.response.message1, message2: event.response.message2})"`

and showing in two different div(because its need to show for different fileds) like that
` div(submit-error='')
     template(type='amp-mustache')
        | {{message1}}`
and
` div(submit-error='')
     template(type='amp-mustache')
        | {{message2}}`

Problem: only getting one error i.e first one message1.
Why not showing in both div for both message

**Comment by manishd-vc** [comment] 2019-09-26 10:59
hi
