### ISSUE TITLE
AMP is covering up content by moving an element and adding large z index

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#25361] opened 2019-10-31 23:49 UTC
AMP is covering up content due to fixedlayers as you can see here:
![IMG_1779](https://user-images.githubusercontent.com/7919520/67993404-007d7e00-fbfe-11e9-8415-e6e5deadc578.jpg)

![IMG_1781](https://user-images.githubusercontent.com/7919520/67993422-0ecb9a00-fbfe-11e9-9d35-6ed1eeae759f.jpg)

Screenshot of error:
<img width="805" alt="Screen Shot 2019-10-29 at 5 43 08 PM" src="https://user-images.githubusercontent.com/7919520/67993459-27d44b00-fbfe-11e9-940e-6735e6af15f4.png">

Removing the force added Z index fixes the issue.

Repros on iOS devices.

**Comment by virgiltu** [comment] 2019-11-01 05:35
I think i was about to open the same ticket. There is no possible way to get rid of the arrows, they stick over everything.  I set my login div to z-index:9999; and still the arrows z-index:10 are over the content. 
![Opera Snapshot_2019-10-31_223030_127 0 0 1](https://user-images.githubusercontent.com/7761519/68004423-b660c080-fc2e-11e9-8f76-34f99e84fb46.png)

**Comment by sparhami** [comment] 2019-11-01 18:23
For the original bug, here is the cause:

https://github.com/ampproject/amphtml/blob/1cfe92da11547b4e9ffed8dc258224760eceaa30/src/service/fixed-layer.js#L1076-L1080

The above line sets the new `z-index` based on an index, and the previously declared z-index in the page. In this case, we have a DOM structure like:

```html
<button style="z-index: 2"></button>
<div class="title-bar" style="z-index: 1">Title</div>
```

This normally works as the button displays on top of the title bar due to z-index. However, when transferring these over, the fixed layer logic makes the button `z-index: 10002`:

10000 + 0 (`index`) + 2 (`state.zIndex`)

and the title bar `z-index: 10002`:

10000 + 1 (`index`) + 1 (`state.zIndex`)

Since the z-indicies are the same, the title stacks on top since it is later in the DOM. I think this issue can be worked around by placing the button inside the header, or increasing the button `z-index` (say to 3).

**Comment by sparhami** [comment] 2019-11-01 18:24
> I think i was about to open the same ticket. There is no possible way to get rid of the arrows, they stick over everything. I set my login div to z-index:9999; and still the arrows z-index:10 are over the content. The arrows is from a carousel slider.
> ![Opera Snapshot_2019-10-31_223030_127 0 0 1](https://user-images.githubusercontent.com/7761519/68004423-b660c080-fc2e-11e9-8f76-34f99e84fb46.png)

Do you have a link you can share to the page where you see this issue? What browser(s) do you see this in? It is unclear to me whether or not these are the same issues or different.

**Comment by jridgewell** [comment] 2019-11-01 18:29
We no longer do the Safari scroll hack ("in order to improve scrolling performance in safari" message), so I think this will just fix itself.

**Comment by virgiltu** [comment] 2019-11-04 22:49
> For the original bug, here is the cause:
> 
> https://github.com/ampproject/amphtml/blob/1cfe92da11547b4e9ffed8dc258224760eceaa30/src/service/fixed-layer.js#L1076-L1080
> 
> The above line sets the new `z-index` based on an index, and the previously declared z-index in the page. In this case, we have a DOM structure like:
> 
> ```
> <button style="z-index: 2"></button>
> <div class="title-bar" style="z-index: 1">Title</div>
> ```
> 
> This normally works as the button displays on top of the title bar due to z-index. However, when transferring these over, the fixed layer logic makes the button `z-index: 10002`:
> 
> 10000 + 0 (`index`) + 2 (`state.zIndex`)
> 
> and the title bar `z-index: 10002`:
> 
> 10000 + 1 (`index`) + 1 (`state.zIndex`)
> 
> Since the z-indicies are the same, the title stacks on top since it is later in the DOM. I think this issue can be worked around by placing the button inside `.title-bar`, or increasing the button `z-index` (say to 3).

This flexed my issue. Setting anything to z-index: 17 will be on top of the buttons.

**Comment by caroqliu** [comment] 2019-12-20 19:46
Closing this issue as it appears to be resolved.

**Closed by caroqliu** 2019-12-20 19:46 UTC
Labels: Type: Bug, WG: runtime

**Comment by sparhami** [comment] 2019-12-20 20:53
Just to add a note, I believe this issue will still occur on iOS 12 and below (among other issues). For iOS 13, it should no longer occur.
