### ISSUE TITLE
Issue with ad clicking behaviour: target changed from _blank to _top

### ISSUE THREAD

**Issue by suvi-salo** [ampproject/amphtml#40193] opened 2024-10-25 08:06 UTC
Hi,

We have a wide, several GAM networks affected, issue where if you click on an ad on desktop, it opens in the same window instead of a new one. On GAM, all the settings point to _blank but amp-ad-exit mjs changes it to _top. We were in touch with GAM Publisher support and they advised us to contact you here. One of the affected sites is byggebolig.no. Let me know if you need any further information from us.

**Comment by erwinmombay** [comment] 2024-10-30 21:23
heya @suvi-salo . do you happen to have an example to demonstrate the behavior?

**Comment by suvi-salo** [comment] 2024-10-31 07:10
@erwinmombay If you take a look at byggebolig.no and click on any ad, you'll see it opens in the same window rather than in a new tab. 
![image](https://github.com/user-attachments/assets/b0df72d8-b3cf-4020-873e-dfcb059e8b70)
![image](https://github.com/user-attachments/assets/66349d4a-f4e9-49a0-817b-07c392efbe22)

This is what we see in amp-ad-exit-0.1.mjs file, which causes the behaviour: 
![image](https://github.com/user-attachments/assets/720a3648-d71a-4119-bc0b-3eb050fa622e)

**Comment by powerivq** [comment] 2024-11-01 20:51
@suvi-salo Looking at your amp-ad-exit configuration, it specified that the link is to be opened with `_top` (see screenshot below) , and that overrides the `a` tag, so everything is working as intended from AMP's perspective.

<img width="300" alt="image" src="https://github.com/user-attachments/assets/c23fbe1f-dc1e-4ab7-af54-e0ac00334512">

If you have questions about the amp-ad-exit configuration, you would need to contact GAM, as AMP only renders the creative as instructed.

**Comment by erwinmombay** [comment] 2024-11-14 18:34
closing out for now. feel free to re-open if there is any further discussion needed

**Closed by erwinmombay** 2024-11-14 18:34 UTC
Labels: Component: amp-ad-exit, needs sizing
