### ISSUE TITLE
Render timeout waiting for extension amp-subscriptions to be load.

### ISSUE THREAD

**Issue by fadiffxblue** [ampproject/amphtml#25463] opened 2019-11-06 00:19 UTC
## What's the issue?

The amp-pages are partially loading on our production sites. This is happening more often lately. the error msg in console is:

> Uncaught (in promise) Error: Render timeout waiting for extension amp-subscriptions to be load.

## How do we reproduce the issue?

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

1. go to this link https://amp.smh.com.au/politics/federal/barilaro-urges-canberra-to-reconsider-its-position-on-newstart-20191024-p533uw.html
2. in google chrome in the network tab block the loading of the https://cdn.ampproject.org/v0/amp-subscriptions-0.1.js
3. refresh the page. the page should partially load and won't show paywall message if any. check attached screenshot.

<img width="1628" alt="Screen Shot 2019-11-05 at 3 21 16 pm" src="https://user-images.githubusercontent.com/57420902/68257393-351e8900-0087-11ea-9747-26acc5a6e3d0.png">

## What browsers are affected?

All browsers on all devices.

## Which AMP version is affected?

amp-subscriptions-0.1

**Comment by jridgewell** [comment] 2019-11-06 00:51
Thanks for the report, but I think this is a duplicate of https://github.com/ampproject/amphtml/issues/25436? If so, it should be fixed soon.

**Closed by jridgewell** 2019-11-06 00:51 UTC
Labels: Type: Bug
