### ISSUE TITLE
amp-list: use client-side data for render at page load

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#12002] opened 2017-11-09 19:23 UTC
Strawman syntax:

```html
<amp-list src="amp://foo.bar">
<amp-state id="foo">{ bar: ... }</amp-state>
```

**Comment by choumx** [comment] 2018-03-02 20:20
Related: #12372

**Comment by choumx** [comment] 2019-02-14 19:53
Closing as a dupe of #15647.

**Closed by choumx** 2019-02-14 19:53 UTC
Labels: Category: Dynamic/Personalized Content, P3: When Possible, Type: Feature Request
