### ISSUE TITLE
Investigate running of realWin(amp) tests in shadow and non-shadow modes

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#25419] opened 2019-11-04 23:14 UTC
We could try to run `describes.realWin({amp: true})` tests in two modes:
- non-shadow mode (current)
- shadow mode (new approach)

**Comment by Joelsz** [comment] 2019-11-06 19:15
@dvoytenko, I'm going off topic - is shadow mode still "new approach"? If so, when will it be production ready?

Also, where can I track AMP Shadow updates and documentation, for example when is `ampShadow.ampdoc.getBody()` available and when not? Following the blog but there's still a lack of knowledge.

Thanks in advance.

**Comment by nainar** [comment] 2019-11-12 00:17
Hi @Joelsz some developers have had some success with Shadow DOM. However there are currently some issues with the approach highlighted here: https://github.com/ampproject/amphtml/projects/32 which is worth considering as you try it out.

We are trying our best to get to all Shadow AMP related issues. What are the problems you are looking to solve? Feel free to reach out to me on slack "@nainar" and I can help you there

**Comment by choumx** [comment] 2019-11-18 17:32
I believe `describes.endtoend()` by default run on multiple envs (by design), though that doesn't help for existing tests.

/cc @ampproject/wg-infra

**Comment by rsimha** [comment] 2020-05-01 00:46
Given recent discussions around this, I think it makes more sense to migrate existing integration tests that need shadow coverage to the E2E framework. Closing out this issue. (Reopen if you disagree.)

**Closed by rsimha** 2020-05-01 00:46 UTC
Labels: P3: When Possible, Type: Feature Request, WG: infra
