### ISSUE TITLE
IntersectionObserver Flakey Test on Travis

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#4552] opened 2016-08-16 21:17 UTC
```
Chromium 51.0.2704 (Ubuntu 0.0.0) IntersectionObserver "after each" hook for "should send more intersections" FAILED
	Error: Blocked a frame with origin "/tmp/2306bff10ad276edf0f1022f93f707f3.browserify:54795:28 <- node_modules/sinon/lib/sinon/util/core.js:154:0)
	    at each (/tmp/2306bff10ad276edf0f1022f93f707f3.browserify:52294:33 <- node_modules/sinon/lib/sinon/collection.js:34:0)
	    at Object.restore (/tmp/2306bff10ad276edf0f1022f93f707f3.browserify:52314:17 <- node_modules/sinon/lib/sinon/collection.js:54:0)
	    at Object.restore (/tmp/2306bff10ad276edf0f1022f93f707f3.browserify:53582:42 <- node_modules/sinon/lib/sinon/sandbox.js:96:0)
	    at Context.<anonymous> (/tmp/2306bff10ad276edf0f1022f93f707f3.browserify:97598:13 <- /home/travis/build/ampproject/amphtml/test/functional/test-intersection-observer.js:220:12)
```

**Comment by jridgewell** [comment] 2016-10-11 20:51
Dupe of (the latter) https://github.com/ampproject/amphtml/issues/5359. I'm making it the canonical.

**Closed by jridgewell** 2016-10-11 20:51 UTC
Labels: Flaky, Related to: Testing
