### ISSUE TITLE
amp-facebook-comments not working on doc/example page

### ISSUE THREAD

**Issue by ZdejPoham** [ampproject/amphtml#40058] opened 2024-06-17 13:05 UTC
### Description

Facebook comments do not render.

### Reproduction Steps

Open URL: https://amp.dev/documentation/examples/websites/components/amp-facebook-comments/
All the IFRAMES are empty.

### Relevant Logs

```shell
The loading of “https://www.facebook.com/v17.0/plugins/comments.php?app_id=&channel=https%3A%2F%2Fstaticxx.facebook.com%2Fx%2Fconnect%2Fxd_arbiter%2F%3Fversion%3D46%23cb%3Dfd714261bba125983%26domain%3Dd-33972227093184117286.ampproject.net%26is_canvas%3Dfalse%26origin%3Dhttps%253A%252F%252Fd-33972227093184117286.ampproject.net%252Ff4d26bfbfa9d6a2b5%26relation%3Dparent.parent&color_scheme=light&container_width=731&height=100&href=http%3A%2F%2Fwww.directlyrics.com%2Fadele-25-complete-album-lyrics-news.html&locale=en_US&numposts=10&order_by=social&sdk=joey&version=v17.0&width=” in a frame is denied by “X-Frame-Options“ directive set to “deny“. comments.php
```

### Browser(s) Affected

Firefox

### OS(s) Affected

Linux

### Device(s) Affected

PC

### AMP Version Affected

2405300626000

**Comment by erwinmombay** [comment] 2024-06-24 05:18
Hmm im unable to reproduce the bug. I am currently on a Mac. I'll try again during office hours.

**Comment by erwinmombay** [comment] 2024-08-08 18:15
going to close this out, but if you have additional information we're happy to take another look.

**Closed by erwinmombay** 2024-08-08 18:15 UTC
Labels: Type: Bug
