### ISSUE TITLE
AMP Banner does not Show on Opera

### ISSUE THREAD

**Issue by Wleyba** [ampproject/amphtml#10424] opened 2017-07-13 21:42 UTC
What's the issue?
AMP Banner does not show on Opera on origin. (https://ampbyexample.com/components/amp-app-banner/)

AMP Banner appears via AMP Cache (https://ampbyexample-com.cdn.ampproject.org/v/s/ampbyexample.com/components/amp-app-banner/?amp_js_v=0.1)

How do we reproduce the issue?
1.  Open Opera browser
2.  Place origin sandbox link
3.  Observe AMP Banner does not appear

What browsers are affected?
Opera ver 42.7
Nexus 6P N ver 7.1.2

**Comment by muxin** [comment] 2017-08-28 21:52
This is a duplicate of https://github.com/ampproject/amphtml/issues/10376. Working on a fix.

**Closed by muxin** 2017-08-28 21:52 UTC
Labels: Category: Presentation, P2: Soon, Type: Bug
