### ISSUE TITLE
style amp-custom tag in head is reported as being in the body

### ISSUE THREAD

**Issue by lukebjerring** [ampproject/amphtml#3907] opened 2016-07-03 01:48 UTC
If you have 2 style amp-custom tags (illegal), the error message is:

The parent tag of tag 'style amp-custom' is 'body', but it can only be 'head'. (see https://www.ampproject.org/docs/reference/spec.html#stylesheets)

Should be something like

Only one amp-custom style tag is allowed.

**Comment by lukebjerring** [comment] 2016-07-03 01:55
Actually, on removal of the extra tag, I still get the same error. My amp-custom style tag is in definitely in the <head> tag.

**Comment by Gregable** [comment] 2016-07-06 17:10
This error is likely correct, but leading you in the wrong direction. Difficult to tell for sure without seeing an example. The issue is that only certain tags are allowed inside the <head> section of a document. If encountered, these tags result in html5 parsers to close the head and open the <body> section. You likely have a tag before the <style amp-custom> tag in your head which is not allowed in the head. Common examples include amp tags, like <amp-analytics> or text nodes (whitespace and comments are ok).

**Comment by ericlindley-g** [comment] 2016-07-13 23:25
Slotting in backlog for now, but please correct/update as needed

**Comment by Gregable** [comment] 2016-07-15 19:51
Closing. I'm confident my explanation is the correct one, though not certain unless given a reference to the page. If so, https://github.com/ampproject/amphtml/issues/4074 tracks better reporting for this.

**Closed by Gregable** 2016-07-15 19:51 UTC
Labels: Needs Reproduction, Related to: Validator
