### ISSUE TITLE
Problems with amp-facebook-page sizing and not showing the facepile

### ISSUE THREAD

**Issue by GeekTNT** [ampproject/amphtml#13609] opened 2018-02-22 13:43 UTC
## **Problem 1: Sizing**

Here's the sample code:
`<amp-facebook-page width="300" height="300" layout="responsive" data-href="https://www.facebook.com/FileHorse"></amp-facebook-page>` 

The code above renders like this: http://prntscr.com/ii9r8b with the width of 340px instead of 300px as set above: http://prntscr.com/ii9rte . The non-AMP version works just fine.

I have tried changing `layout="fixed"` and that did made it 300px wide but the part of it got cropped: http://prntscr.com/ii9zsa, and digging a bit more shows that the actual size of the element is again 340px: http://prntscr.com/iia0tv but the overflow was just not shown. The only way to make this work was to add attribute `data-adapt-container-width="true"`. 

So, the **data-adapt-container-width fixes the size problem**, but still: why do I declare `width="300"` if the element wont be 300px wide (makes no sense) and why do I need to declare `data-adapt-container-width="true"` when it's default value is true so it should function like that out of the box?

## **Problem 2: Facepile not showing**
To show a Facepile according to [according to the  amp-facebook-page documentation](https://www.ampproject.org/docs/reference/components/amp-facebook-page#data-show-facepile-(optional)), I would need add an attribute `data-show-facepile="true"` but even with it facepile is not shown. Again plain HTML version displays facepile and AMP doesn't.

Code:
`<amp-facebook-page width="300" height="300" layout="fixed" data-adapt-container-width="true" data-show-facepile="true" data-href="https://www.facebook.com/FileHorse"></amp-facebook-page>`

Screenshots:
http://prntscr.com/iiafsn
http://prntscr.com/iiak9h

Am I missing something or what?
Thanks in advance!

**Comment by nainar** [comment] 2018-02-23 00:45
Thanks for filing the issues @GeekTNT! :)

Re: Problem 2 - 
The issue is here: https://github.com/ampproject/amphtml/blob/master/3p/facebook.js#L85
`container.setAttribute('data-show-facepile', data.showFacePile);` should read
`container.setAttribute('data-show-facepile', data.showFacepile);` (note the change in capitalization on `data.showFacepile`)

Fixing this and adding tests. Will look at the first problem right after. 

Sorry for the inconvenience this may cause you!

**Comment by nainar** [comment] 2018-02-23 03:12
Re: Problem 1. 

The 3p plugin isn't propagating the user provided `width` and `height` to the SDK.

**Comment by nainar** [comment] 2018-03-05 17:34
Sorry both the issues should be fixed now - I just forgot to close this issue.

**Closed by nainar** 2018-03-05 17:34 UTC
Labels: Category: Presentation, P2: Soon, Type: Bug
