### ISSUE TITLE
Support for non cache served AMP pages

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#27011] opened 2020-02-27 18:09 UTC
Allow for developers to voluntarily opt out of a valid AMP page being in the cache. This will make personalization and cookie management much easier. 

Proposal in detail here: 
https://docs.google.com/document/d/1uEMpT3r692Sy6qZW7UgYekXaMr7KDTep1D5zMbTAIVI/edit#

cc @sebastianbenz @Gregable @alankent @cramforce

**Comment by morsssss** [comment] 2020-02-27 19:45
Woo!

/cc @demianrenzulli @antoinebisch

**Comment by alankent** [comment] 2020-02-28 01:16
Love it!

**Comment by westonruter** [comment] 2020-03-10 23:25
How does this relate to signed exchanges? I can imaging a case where a site wants to simplify cookie management but _also_ take advantage of signed exchanges. In other words, serve signed exchange from cache if browser supports it, otherwise serve from origin. In other words, never use AMP Cache URLs.

**Comment by alankent** [comment] 2020-03-10 23:39
Is that covered by the `<html amp="no-caching-non-sxg">` example in the proposal doc? "Don't cache non SXG content."

**Comment by westonruter** [comment] 2020-03-11 00:00
Right you are! My bad. I did a find for “signed exchange” but not “SxG”.

**Comment by twifkak** [comment] 2020-08-25 18:21
Dupe of #29296.

**Closed by twifkak** 2020-08-25 18:21 UTC
Labels: P2: Soon, Type: Feature Request, WG: Caching: Triaged, WG: caching
