### ISSUE TITLE
amp-ad: smartadserver plugin doesn't check if the server return empty banner or not

### ISSUE THREAD

**Issue by jansete** [ampproject/amphtml#8695] opened 2017-04-11 13:08 UTC
SmartAdServer plugin doesn't checkif the server return empty banner or not

## Context
https://github.com/ampproject/amphtml/blob/master/ads/smartadserver.js doesn't use global.context.noContentAvailable();

The problem is if the server doesn't give us any advert we can't hide it or use any fallback.

## How do we reproduce the issue?
Using amp-ad with smartadserver type, if the format doesn't have any adverts.

**Comment by jasti** [comment] 2017-04-11 20:53
@GoldenCrystal thoughts on supporting? 
Also, could you support render start if you haven't already? Thanks.

**Comment by GoldenCrystal** [comment] 2017-04-14 09:53
Hello,

I confirmed that this is a regression on our side.
It will be fixed during our next deployment.

**Comment by gitfriend1** [comment] 2017-04-14 11:26
what do about it

**Comment by jasti** [comment] 2017-06-01 21:17
Closing since the issue seems to be on the smart ad server side. Please reopen if the issue persists.

**Closed by jasti** 2017-06-01 21:17 UTC
Labels: Category: Ads, Type: Feature Request
