### ISSUE TITLE
Intent-To-Implement  adding UpScore to the analytics vendors list

### ISSUE THREAD

**Issue by SandiSuran** [ampproject/amphtml#18529] opened 2018-10-03 15:30 UTC
Hi,

We'd like to add UpScore to the analytics vendors list,
[www.upscore.com](url)

**Objective**
Add configuration tag for UpScore.

**Overview**
PR to follow shortly including implementation.

**Proposed Vendor Configuration**

```
<amp-analytics type="upscore">
<script type="application/json">
{
  "vars": {
    "object_id": "foo",
    "object_type":"bar",
    "section":"sport",
    "author":"john suran",
    "creator":"john suran",
    "domain":"clientDomain",
    "pubDate":"01/01/0001"
  }
}
</script>
</amp-analytics>
```

**Comment by mrjoro** [comment] 2019-01-15 20:13
It looks like this is a dupe of #18626 (and the underlying feature was implemented in #18734).

**Closed by mrjoro** 2019-01-15 20:13 UTC
Labels: Category: Analytics, INTENT TO IMPLEMENT
