### ISSUE TITLE
amp-font non supported by shadow dom

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#12098] opened 2017-11-17 14:49 UTC
When using amp-font in AMP pages embedded in a PWA (via shadow dom), the font is not loaded correctly.
For example: [amp-font sample](https://amp-by-example-staging.appspot.com/polymer/detail/components/amp-font/) shows the custom font while the [embedded](https://amp-by-example-staging.appspot.com/polymer/detail/components/amp-font/) version in Polymer pwa amp-font doesn't.

@cvializ FYI

**Comment by cvializ** [comment] 2017-11-17 20:51
Able to reproduce, looks like it's using the top-level document and not yet considering the shadow case. Is this blocking any partners?

**Comment by kul3r4** [comment] 2017-11-18 22:03
Yes.

**Comment by cvializ** [comment] 2017-12-11 21:06
I found a fix for Firefox, but it looks like there's a Chrome bug where `@font-face` declarations are not supported inside `ShadowRoot`s : /
https://bugs.chromium.org/p/chromium/issues/detail?id=336876

**Comment by cvializ** [comment] 2017-12-12 01:39
To clarify, the PR just merged allows the `amp-font` fallback mechanism to work correctly in all browsers, but does not fix `@font-face` in a ShadowRoot in Chrome.

**Comment by gilbertococchi** [comment] 2019-01-21 09:01
Hi all, I am reopening this issue as it's still happening on https://rep.repubblica.it/pwa/generale/2019/01/20/news/cinque_milioni_di_e-fatture_al_giorno_ma_sono_la_dannazione_dei_piccoli-217055626/ where they have been forced to use link=preload to the font files declared in the PWA parent page to preload the fonts in AMP.

**Comment by gilbertococchi** [comment] 2019-01-29 12:40
@rudygalfi can we reopen this issue as @font-face definition is still not propagated to the top level document?

**Comment by rudygalfi** [comment] 2019-01-29 18:01
@cvializ - can you comment here on @gilbertococchi's last comment or re-assign?

**Comment by cvializ** [comment] 2019-01-29 18:13
This is a Chrome browser bug and not a bug within AMP. We could add a workaround to polyfill the bug but it would have a cost of shipping code to browsers that wouldn't be used in a some cases

This issue was originally opened to fix support for amp-font in ShadowDOM and the discussion is shifting toward the Chrome browser bug. I'll open a new FR to work around the browser bug and assign to @prateekbh for prioritization.

**Closed by cvializ** 2019-01-29 18:13 UTC
Labels: Category: PWA, P2: Soon, Type: Bug
