### ISSUE TITLE
AMP Story Video randomly "Failed to load: [object HTMLVideoElement]​​​"

### ISSUE THREAD

**Issue by martinfischerextern** [ampproject/amphtml#24492] opened 2019-09-12 11:02 UTC
We are building AMP Stories with 5-7 Video-Pages, some of the videos-pages have an attachment.
Sometimes we see this error in JS console:
“error.js:202 Failed to load: [object HTMLVideoElement]
Fg @ error.js:202
Promise.catch (async)
h @ resources-impl.js:1821 …”

This happened randomly. Sometimes you need 10 requests to see it one time, sometimes you will get it 10 times in a row.
If you get this error, the first video will not play, but after the advance-time the second video will play and if you go back, the first video plays also. 
Test content you will find here:
https://m.bild.de/amp-story/bild-daily/news/ausgabe-64382772,view=amp.bildMobile.html

Thank you
![Unbenannt](https://user-images.githubusercontent.com/34512062/64779069-7306a180-d55d-11e9-9fa7-457a03c918fe.JPG)

**Comment by newmuis** [comment] 2019-09-15 20:11
Marking as a duplicate of #24414

**Comment by heavyinfo** [comment] 2019-11-02 12:17
This error still occurs in normal AMP pages (non story, AMP only site) on Chromium browser (80.0.3947.0) on desktop.
On other desktop browsers (Chrome, Firefox, Safari) video does play but fallback element also gets called.

**Comment by tarun7886** [comment] 2021-06-25 05:36
Still facing the same issue in normal AMP pages. 
Link https://public.app/amp_video/sp_elvdrim4x2h0s

**Comment by yog3sha** [comment] 2023-06-21 08:47
It's 2023 and this issue still exists! Video loads in the background and poster images overlaps it, showing error "Video failed to play!"
Videos shows when poster image is kept empty but the error message still shows!
Is there any attribute to disable amp validations?

**Comment by yog3sha** [comment] 2023-06-22 05:36
> It's 2023 and this issue still exists! Video loads in the background and poster images overlaps it, showing error "Video failed to play!" Videos shows when poster image is kept empty but the error message still shows! Is there any attribute to disable amp validations?

Found that it happens mostly on the slow internet connections. Is there any way to load the amp-video again when it shows as failed once but the user comes back to it, say for example when used in amp-story -> amp-story-grid-layer ??

**Comment by rdotsmith** [comment] 2023-08-23 21:52
We are experiencing a similar issue. Videos play as expected, but a "Video failed to play!" error shows. This is being reported by our AUNZ Team, and they've been able to reproduce with 4 different users on Chrome desktop and an iPhone. 

**Story URL:** https://gweb-dat-data-shorts-stage.appspot.com/intl/en-aunz/_/ai-marketing-business-success
Screen Recording of the behavior/error: https://www.youtube.com/watch?v=J9gYPjH82B8

The slow internet connection may explain why I can't reproduce the problem in the US, but our AUNZ Team can reproduce it.

**Comment by ychsieh** [comment] 2023-08-24 11:19
I have throttled the browser to 3G but still cannot reproduce this. Could you guys provide other URLs or on which browser?

**Comment by rdotsmith** [comment] 2023-08-24 20:11
The browser where our AUNZ Team was able to reproduce is Chrome 114.0.5735.198 (Official Build) (arm64)

**Comment by yog3sha** [comment] 2023-10-12 06:48
Is there any limit on the minimum duration of the video? Couldn't find any such thing in the official documentation. I see warnings in console saying video should be minimum 5 seconds. For shorter duration videos it is working fine on windows and android but 'failed to play on iOS'.

**Comment by ychsieh** [comment] 2023-10-12 07:09
I believe you are referring to `[video-manager] This video is too short for `video-percentage-played`. Reports may be innacurate. For best results, use videos over 5 seconds long.`. This is only for triggering this specific analytic event, which does not affect any core functionalities for videos in Web Story.

**Comment by yog3sha** [comment] 2023-10-12 07:43
> I believe you are referring to `[video-manager] This video is too short for `video-percentage-played`. Reports may be innacurate. For best results, use videos over 5 seconds long.`. This is only for triggering this specific analytic event, which does not affect any core functionalities for videos in Web Story.

Thank you @ychsieh 
Can you please check if you're able to play all the videos on https://www.garnier.co.uk/super-uv-amp-story on iPhone?

**Comment by yog3sha** [comment] 2023-10-12 08:02
> Reference

Thank you @ychsieh 
Is there any documentation for upgrading AMP? I see the issues regarding video caching and and failures are marked as fixed in the latest update on the roadmap page
https://amp.dev/community/roadmap 
Though I've started using it this year but upgrade, if possible, might help!

**Closed** 2024-03-14 21:12 UTC
Labels: Type: Bug, P3: When Possible, WG: stories, estimate: small
