### ISSUE TITLE
amp-mustache-0.2 fails to render template in nested amp-lists

### ISSUE THREAD

**Issue by mattwomple** [ampproject/amphtml#17561] opened 2018-08-16 21:58 UTC
## What's the issue?

When an amp-list is nested inside another amp-list, and the child amp-list references a template by ID, the child amp-list fails to render the template when amp-mustache-0.2 is used. The same amp-list renders fine when amp-mustache-0.1 is used.

## How do we reproduce the issue?

This is easiest to see with an example:

- https://cmphys.com/amp-mustache-01.html
- https://cmphys.com/amp-mustache-02.html

The only difference between these pages is the version of amp-mustache used (and the title on the page indicating as much). The first page renders both amp-lists fine, whereas the second page renders the parent amp-list fine and the fallback for the child amp-list.

## What browsers are affected?

Tested on the following:

- "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
- Mozilla/5.0 (Linux; Android 7.0; Moto G (5) Plus Build/NPNS25.137-93-14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.91 Mobile Safari/537.36

## Which AMP version is affected?

1534444305877

**Comment by jaygray0919** [comment] 2018-08-17 10:34
When I test on Firefox desktop 61.0.2 (64-bit) the two are identical. When testing on Chrome desktop (Version 68.0.3440.106 64-bit), the reported problem occurs (i.e. `inner template fallback`).

**Comment by choumx** [comment] 2018-08-17 17:28
Thanks for the report, looking at this now.

**Comment by choumx** [comment] 2018-08-17 17:31
This is caused by the removal of the `template` attribute in the rendered output of amp-mustache-0.2. It was fixed by #17434 which is in [dev-channel](https://cdn.ampproject.org/experiments.html) and will be in production by next Wednesday.

Sorry about the bug and thanks for your patience.

**Closed by choumx** 2018-08-17 17:31 UTC
Labels: Category: Runtime, Type: Bug
