### ISSUE TITLE
Dynamic list

### ISSUE THREAD

**Issue by vishalvanpariya** [ampproject/amphtml#27641] opened 2020-04-08 11:58 UTC
Hello,

I am creating a chatbot using AMP.
so in a chatbot, I am fetching data from API.
I showing those data in the list but it should come one by one with user interaction.
and I sending users data to API.

adding one image here:
![Capture](https://user-images.githubusercontent.com/27823328/78781509-04d47100-79be-11ea-888e-30dd4ce17271.PNG)

the chatbot will be like above so please help me with this to create it.

Thanks

Vishal

**Comment by nainar** [comment] 2020-04-08 17:54
Dupe of #27640

**Closed by nainar** 2020-04-08 17:54 UTC
Labels: Type: Feature Request
