### ISSUE TITLE
amp-img doesn't render if initially off-screen and later animated on-screen

### ISSUE THREAD

**Issue by tabjsina** [ampproject/amphtml#11274] opened 2017-09-12 17:43 UTC
## What's the issue?

A page is loaded with an amp-img element off screen, it correctly does not load the image onload. Later, some user-interaction (eg. button press) causes the amp-img element to be animated onto the screen (using transition+transformx), however, even though the image would not be visible to the user, it still doesn't load until the user forces a re-measure (eg. resizing window)

## How do we reproduce the issue?

https://codepen.io/anon/pen/gGOLXP

FYI - The specific use-case is a website that has a left-side menu/drawer. When it is opened, the icons within the drawer list-items do not render.

## What browsers are affected?

I've tried Chrome and Edge, both have this issue.

## Which AMP version is affected?

This is my first AMP page, so I haven't tried this on earlier versions of AMP to be sure

**Comment by jridgewell** [comment] 2017-09-12 17:52
Closing as a duplicate of https://github.com/ampproject/amphtml/issues/10994.

**Closed by jridgewell** 2017-09-12 17:52 UTC
