### ISSUE TITLE
sidebar component produces error in console

### ISSUE THREAD

**Issue by dennyak47** [ampproject/amphtml#19421] opened 2018-11-21 09:22 UTC
## What's the issue?

I use side bar and toggle it, in the first time no problem. But I toggle it again, i can show an error in the chrome console, it says:

Inline styles with `top`, `bottom` and other CSS rules are not supported yet for fixed or sticky elements (#14186). Unexpected behavior may occur. 

I inspect the sideBar element and found:
`<amp-sidebar id="sidebar1" layout="nodisplay" side="left" class="i-amphtml-element i-amphtml-layout-nodisplay i-amphtml-overlay i-amphtml-scrollable i-amphtml-layout" aria-hidden="true" role="menu" tabindex="-1" i-amphtml-fixedid="F0" style="top: calc(0px);" hidden="">`

and there is      style="top: calc(0px);"     in it.

## How do we reproduce the issue?

Same issue happens at 
https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2Fcomponents%2Famp-sidebar%2Fsource%2F&mode=iPhone+6%2F7%2F8
and at
https://ampbyexample.com/components/amp-sidebar/preview/

## What browsers are affected?

All browsers

## Which AMP version is affected?

latest version

there should be no error in the console because it affects my mood of developing

**Comment by torch2424** [comment] 2018-11-21 18:32
Assigning to @choumx as it seems this was introduced by your PR. I noticed this as well in some of my work, so a quick explanation on why this is, I think can resolve this. Thanks!

**Comment by choumx** [comment] 2018-11-26 13:51
Context is the `style="calc(..)"` is added by fixed-layer.js to offset fixed-position elements to account for the viewer header (though this doesn't actually apply to sidebar since we hide the header when it opens). This happens as a result of the `addToFixedLayer()` call in amp-sidebar.js.

Ways to fix this include making sure `addToFixedLayer()` is only called once per sidebar element, or to remove the sidebar element from FixedLayer on close with a corresponding `removeFromFixedLayer()`.

**Comment by torch2424** [comment] 2018-12-26 19:36
@choumx 

Thanks for the thorough explanation!

@dennyak47 

I tried reproducing this in Chrome, Safari, and Firefox, and I couldn't trigger this specific error. I toggled the sidebar a bunch of times, and couldn't get the `style` error.

<img width="1440" alt="screen shot 2018-12-26 at 11 35 28 am" src="https://user-images.githubusercontent.com/1448289/50455366-5f010e00-0902-11e9-91f9-c2ce16ce8abb.png">

Could you test this out, and see if this is still an issue?

**Comment by torch2424** [comment] 2019-05-02 20:49
@choumx @dennyak47 

I'm going to go ahead and close this as a "could not reproduce". As I tried this again on the new amp.dev, and could not get any errors to pop up at all.

Feel free to re-open if this is still an issue 😄

**Closed by torch2424** 2019-05-02 20:49 UTC
Labels: Category: Presentation, P2: Soon, Type: Bug
