### ISSUE TITLE
Cross-Origin-Resource-Policy "cross-origin" not present in v0.js

### ISSUE THREAD

**Issue by arleyandrada** [ampproject/amphtml#33626] opened 2021-04-03 17:54 UTC
Unable to make my website "cross-origin isolated" using COOP and COEP.
https://web.dev/coop-coep/

Resource:
https://cdn.ampproject.org/v0.js

Error:
To use this resource from a different origin, the server needs to specify a cross-origin resource policy in the response headers.

Missing response header:
Cross-Origin-Resource-Policy: cross-origin

**Comment by jridgewell** [comment] 2021-04-05 19:29
Hi @arleyandrada: Thanks for this report. I'm going to close this as a duplicate of https://github.com/ampproject/amphtml/issues/31579, only because that one was opened first. This should be easy to fix, and I'll provide updates in that issue.

**Closed by jridgewell** 2021-04-05 19:29 UTC
Labels: Type: Bug, WG: runtime

**Comment by jridgewell** [comment] 2021-04-06 17:45
This is fixed on our servers.
