### ISSUE TITLE
Error: failed to fetch %s [object URL]: HTTP error 404

### ISSUE THREAD

**Issue by sparhami** [ampproject/amphtml#20937] opened 2019-02-19 20:54 UTC
Error: failed to fetch %s [object URL]: HTTP error 404
at Error (https://raw.githubusercontent.com/ampproject/amphtml/1902151859190/src/log.js:540)
at apply (https://raw.githubusercontent.com/ampproject/amphtml/1902151859190/src/log.js:286)
at (https://raw.githubusercontent.com/ampproject/amphtml/1902151859190/src/service/action-impl.js:665)
at parentElement (https://raw.githubusercontent.com/ampproject/amphtml/1902151859190/src/service/action-impl.js:619)
at Object (https://raw.githubusercontent.com/ampproject/amphtml/1902151859190/src/service/action-impl.js:740)

go/ampe/CP70_9Ps5ond4wE?service=default-cdn-1p-canary&version=001902151859190&time=P1D&project=amp-error-reporting

Low volume - also seems like it may not be an AMP error per-se.

**Comment by choumx** [comment] 2019-05-14 19:06
Closing as dupe of #20638.

**Closed by choumx** 2019-05-14 19:06 UTC
Labels: Type: Bug
