### ISSUE TITLE
Sticky AD Placeholder does not get hidden correctly

### ISSUE THREAD

**Issue by renebaudisch** [ampproject/amphtml#12345] opened 2017-12-07 12:25 UTC
## What's the issue?

Sticky AD Placeholder does not get hidden correctly

## How do we reproduce the issue?

Please visit https://www.google.de/amp/s/www.bildderfrau.de/familie-leben/article212664353/Brueckentage-nutzen.html%3fservice=amp

When scrolling the sticky-ad will be inserted and an ad get's loaded.
Even there is an ad loaded by appnexus and the style on placeholder get's changed to "visibility: hidden;" the ad doesn'T get displayed, the palceholder is still there.
It seems that the browser doesn't recognize this css change and doesn't render it, 
first when editing any of these CSS back and forth the browser renders the css cahnge and displays the ad.

## What browsers are affected?

Maybe all Browsers, testet on Desktop and mobile Chrome and also Opera Desktop

## Which AMP version is affected?

Version 1510956201635

**Comment by lannka** [comment] 2017-12-08 22:18
I don't see the "visibility: hidden;" problem on other browsers expect desktop Chrome. 

I tested on 
Android Chrome 63.0
Safari Desktop 11.0.1

I don't see the placeholder ad icon, but I don't see ads either. It's always an empty creative with only a 1x1 iframe in it.

The way you described seems to be browser bug. Can you confirm what browsers you tested on?

**Comment by renebaudisch** [comment] 2017-12-11 17:41
Strange, it seems to work now.

**Comment by lannka** [comment] 2017-12-11 17:43
Very likely a weird chrome issue that only happens on some special condition :-). Let's keep an eye on it.

**Comment by renebaudisch** [comment] 2017-12-11 20:06
We (me and my colleagues) saw it on different devices and browser, using iphones, androids or desktop windows via emulation, but when not scrolled at all, the devices all had that error. When already scrolled and reloaded page everything was fine all the time. I don't know who changed what, maybe the page devs itself found something, but I cannot reproduce anymore... but THX a lot anyway...

**Comment by renebaudisch** [comment] 2017-12-12 16:05
I found a way to reproduce, open the url is not working to see the bug. But none of our user would just open an url, AMP is accessed through search and that's also the way to reproduze. 

So, please open Google and search for "bild der frau coupons" you will find an entry pointing to https://www.bildderfrau.de/spass-unterhaltung/article208280859/Wir-haben-eine-neue-Rubrik-Sparen-mit-Coupons.html?service=amp.

When you now open this url at least the first and scroll down the problem occurs.

**Comment by lannka** [comment] 2017-12-12 17:49
Thanks Rene. 

Just to confirm, is this what you saw?
<img width="301" alt="screen shot 2017-12-12 at 9 37 08 am" src="https://user-images.githubusercontent.com/8496897/33899375-2b351416-df20-11e7-8edf-a7624fa30ec8.png">

I got this reproduced by directly visiting the link on Chrome Desktop. 

On Android Chrome Mobile, Safari Desktop and Firefox Desktop, I got a blank ads with no loading indicator:

<img width="301" alt="screen shot 2017-12-12 at 9 37 08 am" src="https://user-images.githubusercontent.com/8496897/33899511-929bd82e-df20-11e7-9478-0edb5fb01e89.jpeg">

I also tried to access via Google Search, same result.

So I guess there're 2 issues we are talking about here:

1) On Chrome Desktop, the browser is not hiding the loading indicator, although the visibility is set to hidden. As you mentioned, simply opening the dev console and toggling the "visibility: hidden" CSS rule and then back on would make it work, which really seems like a browser bug.

2) Why is it a blank ad? If it is a no-fill from appnexus?

**Comment by renebaudisch** [comment] 2017-12-13 08:34
THX also, and yes the first screenshot shows the problem. But unfortunatly I do have this effect also on my HTC M9 using Chrome and no plugins or else and our customer also does and isn't happy about it, so I have to find a solution anyway.

![screenshot_20171211-225406](https://user-images.githubusercontent.com/15980546/33929167-c5363586-dfe8-11e7-9bbf-b840efd0667c.png)

**Comment by renebaudisch** [comment] 2017-12-13 15:03
We now also have the issue on another domain, but it's only a dev page at the moment you cannot access it by now http://pv1-4g.finanzen.net/amp/marktverwerfungen-drohen-massive-technische-probleme-beim-handel-mit-bitcoin-kurz-vor-future-start-5857508

![image](https://user-images.githubusercontent.com/15980546/33945365-191a279e-e01f-11e7-9fb3-2ef53066ead2.png)

**Comment by renebaudisch** [comment] 2018-01-23 09:53
Any update on this?

**Comment by lannka** [comment] 2018-02-09 23:07
sorry for the delay. @zhouyx to help

**Comment by zhouyx** [comment] 2018-02-22 22:01
@renebaudisch I tried searching for "bild der frau coupons" on Google, and visiting the page directly. I couldn't reproduce the bug after like 20 times. Could you double check? Thanks!

**Comment by renebaudisch** [comment] 2018-02-23 15:57
This seems not to happen anymore...
Maybe some update the last two weaks affected this and solved this already?

**Comment by renebaudisch** [comment] 2018-03-12 08:34
I now have an other example where this still happens:
https://amp.welt.de/amp/article/171310795

**Comment by zhouyx** [comment] 2018-07-16 18:38
I tried with https://amp.welt.de/amp/article/171310795 a few times. I was able to reproduce. But it's not a browser's bug or sticky ad bug.  The reason is that the appnexus network returned an empty slot ad without telling the AMP runtime that it's a no-fill ad. And there is no way for AMP to collapse. 

This should be fixed from the appnexus ad network side. I'll close the issue for now. Thank you.

**Closed by zhouyx** 2018-07-16 18:38 UTC
Labels: Category: Ads
