### ISSUE TITLE
 amphtml-validator cli not created for macOS

### ISSUE THREAD

**Issue by DamonHD** [ampproject/amphtml#19132] opened 2018-11-04 13:54 UTC
## What's the issue?

macOS version of CLI does not seem to install correctly.

## How do we reproduce the issue?

On RPI (... 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l GNU/Linux):

    sudo npm install amphtml-validator -g
    [sudo] password for XXX: 
    /usr/local/bin/amphtml-validator -> /usr/local/lib/node_modules/amphtml-validator/index.js
    + amphtml-validator@1.0.23
    updated 1 package in 5.69s
    % amp_[TAB]_
    % amphtml-validator

On macOS (... 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64):

the same process does not end up with an executable 'amphtml-validator' on the path, even though other NPM CLI tools work fine this way.

## Which AMP version is affected?

1.0.23

Not been able to make this work at all on macOS, and relevant 'amphtml-validator' script does not seem to be created/installed anywhere, and no obvious errors.

**Comment by DamonHD** [comment] 2018-12-17 16:06
Any idea how long this might take to resolve?  I can't seriously deploy AMP without being able to validate generated pages during build as I do for desktop and (plain HTML5) mobile.

Rgds

Damon

**Comment by uncompiled** [comment] 2018-12-17 19:18
I'm not able to re-create this issue on macOS.

If you run the npm CLI in verbose mode, you can see the result of the `linkBins` step and what's actually happening:

```
npm install -g --verbose amphtml-validator
```

**Comment by DamonHD** [comment] 2018-12-17 19:24
Thanks for that, it thinks that it worked, I think:

% sudo npm install -g --verbose amphtml-validator
Password:
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/lib/node_modules/node/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '-g',
npm verb cli   '--verbose',
npm verb cli   'amphtml-validator' ]
npm info using npm@6.1.0
npm info using node@v10.2.0
npm verb npm-session 581870041fcec60d
npm http fetch GET 200 https://registry.npmjs.org/amphtml-validator 16ms (from cache)
npm timing stage:loadCurrentTree Completed in 298ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 4ms
npm http fetch GET 200 https://registry.npmjs.org/promise 12ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/colors 15ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/commander 18ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/graceful-readlink 3ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/asap 5ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 43ms
npm timing stage:loadIdealTree Completed in 51ms
npm timing stage:generateActionsToTake Completed in 8ms
npm verb correctMkdir /Users/dhd/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /Users/dhd/.npm/_locks/staging-f18d349894eb1580.lock for /usr/local/lib/node_modules/node/lib/node_modules/.staging
npm timing action:extract Completed in 333ms
npm info lifecycle amphtml-validator@1.0.23~preuninstall: amphtml-validator@1.0.23
npm info lifecycle amphtml-validator@1.0.23~uninstall: amphtml-validator@1.0.23
npm verb unbuild rmStuff amphtml-validator@1.0.23 from /usr/local/lib/node_modules/node/lib/node_modules
npm info lifecycle amphtml-validator@1.0.23~postuninstall: amphtml-validator@1.0.23
npm timing action:unbuild Completed in 14ms
npm timing action:remove Completed in 8ms
npm timing action:finalize Completed in 8ms
npm timing action:refresh-package-json Completed in 18ms
npm info lifecycle amphtml-validator@1.0.23~preinstall: amphtml-validator@1.0.23
npm timing action:preinstall Completed in 1ms
npm info linkStuff amphtml-validator@1.0.23
npm verb linkBins [ { 'amphtml-validator': 'index.js' },
npm verb linkBins   '/usr/local/lib/node_modules/node/bin',
npm verb linkBins   true ]
/usr/local/lib/node_modules/node/bin/amphtml-validator -> /usr/local/lib/node_modules/node/lib/node_modules/amphtml-validator/index.js
npm timing action:build Completed in 11ms
npm info lifecycle amphtml-validator@1.0.23~install: amphtml-validator@1.0.23
npm timing action:install Completed in 1ms
npm info lifecycle amphtml-validator@1.0.23~postinstall: amphtml-validator@1.0.23
npm timing action:postinstall Completed in 1ms
npm verb unlock done using /Users/dhd/.npm/_locks/staging-f18d349894eb1580.lock for /usr/local/lib/node_modules/node/lib/node_modules/.staging
npm timing stage:executeActions Completed in 409ms
npm timing stage:rollbackFailedOptional Completed in 0ms
npm timing stage:runTopLevelLifecycles Completed in 770ms
+ amphtml-validator@1.0.23
updated 1 package in 0.773s
npm verb exit [ 0, true ]
npm timing npm Completed in 1284ms
npm info ok 


   ╭───────────────────────────────────────────────────────────────╮
   │                                                               │
   │       New minor version of npm available! 6.1.0 → 6.5.0       │
   │   Changelog: https://github.com/npm/npm/releases/tag/v6.5.0   │
   │               Run npm install -g npm to update!               │
   │                                                               │
   ╰───────────────────────────────────────────────────────────────╯

[DHDMacBook:~/Env] dhd% rehash
[DHDMacBook:~/Env] dhd% amphtml-validator
amphtml-validator: Command not found.
[DHDMacBook:~/Env] dhd%

**Comment by Gregable** [comment] 2019-06-25 19:36
@DamonHD were you ever able to resolve this? We were unable to reproduce at the time, so I'm wondering if this was a unique case or something more general.

**Comment by DamonHD** [comment] 2019-06-25 22:42
I worked round it (in an ugly but apparently robust way), so maybe it's just me.  Dunno.

Rgds

Damon

**Comment by DamonHD** [comment] 2021-01-08 10:26
FWIW this problem persists, but I think it's more likely a general NPM thing, since I have to work around a similar set of issues on Raspbian for example.

Rgds

Damon

**Comment by honeybadgerdontcare** [comment] 2021-01-08 18:08
@DamonHD since we've been unable to reproduce and you've found a work around, I'm going to close this. If you believe there is something we can do then please reopen with details. Otherwise maybe file something to NPM.

**Closed by honeybadgerdontcare** 2021-01-08 18:08 UTC
Labels: P2: Soon, WG: caching
