### ISSUE TITLE
amp-subscriptions: Allow platforms to register on free pages

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#27300] opened 2020-03-19 00:23 UTC
This is the third top error in this week's release (currently in beta): https://github.com/ampproject/amphtml/releases/tag/2003171848440

```
Error: null is not an object (evaluating 'c.l.resolvePlatform')
at resolvePlatform (https://raw.githubusercontent.com/ampproject/amphtml/2003171848440/extensions/amp-subscriptions/0.1/amp-subscriptions.js:222)
```

/cc @ampproject/wg-access-subscriptions

**Comment by rcebulko** [comment] 2020-03-19 03:52
This is effectively a dupe of https://github.com/ampproject/amphtml/issues/27299

**Comment by rcebulko** [comment] 2020-03-31 20:25
While `getEntitlementPromiseFor` error has been resolved, this one is still firing very frequently, and has ramped up with the promotion of 2003262059300 to Stable.

/cc @ChrisAntaki

**Comment by ChrisAntaki** [comment] 2020-03-31 21:07
I'm looking into it now, thanks for the heads up!

**Comment by ChrisAntaki** [comment] 2020-03-31 22:40
Looks like end users aren't affected. It's just `amp-subscriptions-google` can't register itself on free articles, and isn't failing gracefully. I'll start working on a fix!

**Comment by rcebulko** [comment] 2020-03-31 22:49
> Looks like end users aren't affected. It's just `amp-subscriptions-google` can't register itself on free articles, and isn't failing gracefully. I'll start working on a fix!

Nice investigating!

**Closed** 2020-04-06 19:14 UTC
Labels: Component: amp-subscriptions, P1: High Priority, Type: Bug, WG: access-subscriptions

**Comment by juanmadurand** [comment] 2020-04-14 15:06
Hi guys, I'm getting this exact issue on production: 
```amp-subscriptions.js:299 Uncaught (in promise) TypeError: Cannot read property 'resolvePlatform' of null at amp-subscriptions.js:299```
https://amp.pagina12.com.ar/258031-coronavirus-en-argentina-56-muertos-y-1628-infectados

We're using amp-subscriptions as Google Contributions (all our articles are free), and we use this not just to render the "contribute with google button", but also to check if the user is logged in or not. 

Do you have any idea if this fix is already deployed? Thanks!

**Comment by rcebulko** [comment] 2020-04-14 15:49
Howdy @juanmadurand !

If you take a peek at the fix #27556, you should see a label on there **PR Use: In Beta/Experimental**. This label is added automatically, and indicates that the fix is in a release build currently deployed to the Beta and Experimental channels (see [Determining if your change is in a release](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#determining-if-your-change-is-in-a-release)). That build should be promoted to Stable this Wednesday, modulo any regressions or cherry-pick delays.

If you'd like to verify the fix on your site, you can [opt-in to the Beta or Experimental channels](https://github.com/ampproject/amphtml/blob/master/contributing/DEVELOPING.md#opting-in-to-pre-release-channels) and test the new release versions on your site.

**Comment by juanmadurand** [comment] 2020-04-14 17:00
Thanks @rcebulko! I did that, I can see the error is gone but I still have the issue that it's not calling the authorizationUrl configured, which returns the logged status of the user. 

I saw that the fix #27556 disable fetching entitlements on free pages, and that breaks the functionality. So we cannot show/hide elements on free pages (all our pages) depending on the logged status:
```
<span subscriptions-actions subscriptions-display="NOT granted">
  Content for users without entitlements
</span>
<span subscriptions-actions subscriptions-display="granted">
  Premium content for logged users that have valid entitlements
</span>
```

I could use `amp-access` for this, but I should remove `amp-subscriptions` then, because they cannot coexist afaik. Can you reproduce this?

**Comment by ChrisAntaki** [comment] 2020-04-14 17:12
Hey Juan! Would it make sense to mark the article as not free?

**Comment by juanmadurand** [comment] 2020-04-14 17:43
Hi Chris! All our articles are free. We are a newspaper supported by contributions. That's why we're on the Google Contributions program, not subscriptions. Does that make sense?

**Comment by jpettitt** [comment] 2020-04-14 18:00
Short term solution: If you want the auth endpoint to be called you'd need to mark that article as not free, however you don't need to markup any of the content as being protected so you can still grant access without payment.

Longer term we should provide a flag that says signal a free article with a contributions call to action @ChrisAntaki will you open a separate issue for that enhancement and we can discuss the best way to represent it.

**Comment by juanmadurand** [comment] 2020-04-14 18:10
Thanks guys! I'll try that. Marking the article as not free, does it have another implication? 
I mean, could it affect the article indexing or change its visualization on another google product?

**Comment by jpettitt** [comment] 2020-04-14 18:27
As long as your feed to the news app has it in a free section it won't change anything there.  There should be no other implications.
