### ISSUE TITLE
Support branching within stories

### ISSUE THREAD

**Issue by bramanudom** [ampproject/amphtml#20083] opened 2018-12-26 22:31 UTC
Allow publishers to create and users to engage with stories that have non-linear page progressions.

**Comment by cpapazian** [comment] 2019-06-04 15:10
looks like this has been out in experiment for a while. is there an ETA for shipping?

**Comment by swissspidy** [comment] 2019-06-17 08:58
Can #12183 be closed as a duplicate of this? 🤔

**Comment by newmuis** [comment] 2020-04-08 17:18
This was launched with #25728

**Closed by newmuis** 2020-04-08 17:18 UTC
Labels: INTENT TO IMPLEMENT, P1: High Priority, Type: Feature Request, WG: stories
