### ISSUE TITLE
amp-mustache silently removes attribute name="action", not removed if name="a_action" from <input>

### ISSUE THREAD

**Issue by hw-dwalter** [ampproject/amphtml#20528] opened 2019-01-25 10:41 UTC
## What's the issue?

amp-mustache removes attribute `name="action"` but attribute is not removed if `name="a_action"` from <input>.

![image](https://user-images.githubusercontent.com/1303452/51741034-05713800-2096-11e9-8810-f14b7eb943c9.png)

## How do we reproduce the issue?

See https://gist.github.com/hw-dwalter/bf00c5c96640207691b6da63608abd67

**Comment by choumx** [comment] 2019-01-25 19:06
This is a duplicate of issue #17897. 

@hw-dwalter What's the impact of this on your page?

**Comment by choumx** [comment] 2019-02-07 20:08
Closing as a dupe of #17897.

**Closed by choumx** 2019-02-07 20:08 UTC
Labels: Category: Dynamic/Personalized Content, Type: Bug
