### ISSUE TITLE
Sharing Config Options Different in Chrome on Windows

### ISSUE THREAD

**Issue by LuckynaSan** [ampproject/amphtml#35416] opened 2021-07-27 17:45 UTC
### Description

Sharing options are different in Chrome on a Windows device. 

### Reproduction Steps

Steps to reproduce:
1. Open Chrome browser on Windows device
2. Enter Web Stories URL
3. Click on the Sharing button
4. Note the displayed share dialog contains options related to Windows device

Actual results:
The sharing options listed do not appear to be the same as the options listed in Chrome on a different device. 
Example: https://imgur.com/lFANkHC

Expected results:
For the default sharing config to display on Windows device the same as any other device or other browsers.
Example screenshot on Mac: https://jmp.sh/36WFNHm

### Browser(s) Affected

Chrome

### OS(s) Affected

Windows

**Comment by swissspidy** [comment] 2021-07-27 20:34
From what I can tell, this looks like expected behavior.

When you click on the share button, the player tries to invoke the native sharing capabilities of your operating system.

Currently, Firefox does not support this, falling back to that gray-ish dialog in your screenshot.

Chrome however supports it, so it can show the sharing capabilities related to Windows, such as Cortana and OneNote.


https://caniuse.com/web-share

**Comment by processprocess** [comment] 2021-07-28 16:08
Thanks for reporting this @LuckynaSan and thanks for the reply @swissspidy.

@swissspidy is correct, this is expected behavior of the native sharing capabilities of the operating system.

Closing this due to expected behavior but please follow up if you have any other questions :)

**Closed by processprocess** 2021-07-28 16:08 UTC
Labels: Type: Bug, WG: stories
