### ISSUE TITLE
Use Amp List for showing more content when height is not available

### ISSUE THREAD

**Issue by sffriend** [ampproject/amphtml#10462] opened 2017-07-14 23:52 UTC
We want the user to be able to load a amp-list of more comments after the initial page load. We don't know the height of these comments because they can be any length. We can't use the overflow button because we already have our own overflow button whose source is updated on amp-bind.

```<amp-state id="product">
      <script type="application/json">
      {
        "moreCommentsSrc": "/json/comments2.json"
      }
      </script>
    </amp-state>

      <amp-list class="mt1" width="auto" height="600" [height]="comments.moreCommentsSrc == '/json/comments2.json' ? 600 : 1000" layout="fixed-height"
        src="/json/comments2.json"
        [src]="comments.moreCommentsSrc"
        >
        <template type="amp-mustache">
          <div class="flex px1 pt1 depth-{{depth}}">
            <amp-img width="44" height="44" class="mr1 flex-none" alt="user" src="/img/ic_account_box_black_48dp_1x.png"></amp-img>
            <div class="ampstart-card p1 comment">
              <p><span class="user">{{user}}</span> <span class="date">{{datetime}}</span></p>
              <p>{{text}}</p>
            </div>
          </div>
        </template>
      </amp-list>
      <button class="ampstart-btn caps m1 mb3 show" [class]="comments.moreCommentsSrc == '/json/comments2.json' ? 'ampstart-btn caps m1 mb3 show' : 'ampstart-btn caps m1 mb3 hide'" on="tap:AMP.setState({comments: {moreCommentsSrc: '/json/comments3.json'}})">Show more</button>```

**Comment by aghassemi** [comment] 2017-07-15 00:09
+ @choumx

**Comment by ericlindley-g** [comment] 2017-07-15 00:18
Thanks @sffriend ! @choumx, I think this is somewhat similar to the request for resizing when updated through amp-bind, except it's done on the first page load. Would it be possible for amp-list to have container layout for its contents, or is that too risky for page jumps on first load?

**Comment by choumx** [comment] 2017-07-24 15:43
Sorry for the late response!

> Would it be possible for amp-list to have container layout for its contents, or is that too risky for page jumps on first load?

Yea I'd think that's a nonstarter due to content jumping. 

> We can't use the overflow button because we already have our own overflow button whose source is updated on amp-bind.

Why not? I can imagine having a "view all comments" overflow button and a "next page" pagination button. Not as elegant as having a single button but avoids content jumping.

**Comment by ericlindley-g** [comment] 2017-07-24 15:50
Thanks @choumx ! Can you add detail on why content jumping is higher risk in this case than in, say, the case where it resizes based on how many items are returned from the server call?

**Comment by choumx** [comment] 2017-07-24 15:55
Maybe I'm missing something. The latter requires user action while the former doesn't, right?

**Comment by ericlindley-g** [comment] 2017-07-24 16:06
Ah, sorry — momentarily forgot how amp-list worked, so you can disregard my question

**Comment by kul3r4** [comment] 2017-07-25 15:24
@choumx The idea of using 2 buttons doesn't help to keep the current Reddit experience the same.
Currently the mobile page shows, at the bottom: "More comments (number of comment)" and there is no pagination in place. I think having 2 buttons would be confusing.

**Comment by choumx** [comment] 2017-07-25 16:00
@kul3r4 If an amp-list is at the bottom of the page, resizing should be automatic (overflow button won't be displayed). 

@sffriend Can you provide more details on your exact use case? E.g. a sample page.

**Comment by kul3r4** [comment] 2017-07-26 10:23
I was looking at this [page](https://www.reddit.com/r/mildlyinteresting/comments/6pb7yp/this_hotel_rooms_bath_is_built_below_the_floor/) on mobile, it's true that the amp-list would be at the bottom of the page which makes things easier
@sffriend would you like to take a second look at this?

**Comment by devanes** [comment] 2017-09-07 10:37
@choumx 

> If an amp-list is at the bottom of the page, resizing should be automatic (overflow button won't be displayed).

I also read this in the documentation. But I can't get this to actually happen. I have a test page with just an amp-list inside the body tag. But I always get the overflow button. Is there anything specific needed to get this to work?

**Comment by kul3r4** [comment] 2017-09-07 10:57
@devanes Could you share the test page?

**Comment by devanes** [comment] 2017-09-07 11:18
https://bronsvuur.nl/test/test.html

**Comment by devanes** [comment] 2017-09-07 11:21
Note that I set the height of each item to a higher value to make the issue more visible. I can remove this and just add more content or reduce the height of the amp-list to get the same result.

**Comment by kul3r4** [comment] 2017-09-08 12:12
The problem is that your list is not below the first viewport.
Take a look at [this](https://ampbyexample.com/components/amp-list/):

- Load the page the first time and then scroll to the bottom. At the bottom there is an example of overflow button and the button doesn't appear
- Then, without scrolling to the top, reload the page and you will see the button appearing

This is because amp-list will automatically take more space if required (and available) but at the same time it has to be below the first viewport to avoid reflow while the page is loading.

**Comment by kul3r4** [comment] 2017-09-19 11:52
We just published a new [sample](https://ampbyexample.com/samples_templates/product_page/preview/) showing how to implement a load more button

**Comment by devanes** [comment] 2017-09-19 12:13
@kul3r4 That looks interesting. At the moment I have implemented it in a way where using amp-bind the entire contents of the amp-list is replaced with the new batch combined with a scroll to the top of the list, basically previous/next pagination without reload.

**Comment by kul3r4** [comment] 2017-09-19 14:24
@devanes I see, this was the previous approach in the sample as well, but with this new approach you only load the newer items.

**Comment by aadi1295** [comment] 2017-10-22 16:45
@kul3r4 Hi, can you look at this [https://productforums.google.com/forum/#!topic/webmasters/Mf_UPR4dty8;context-place=forum/webmasters](question), I am unable to update amp-state and amp-list with amp-bind. Thanks

**Comment by grahamle** [comment] 2017-11-27 17:31
Highly looking forward the `<amp-list>` to support the scroll event and automatically triggering the request for more items.

**Comment by aghassemi** [comment] 2017-11-27 21:36
@grahamle  We are planning to prioritize this work. Please subscribe to https://github.com/ampproject/amphtml/issues/9423 for updates.

**Comment by haroon8iconglobal** [comment] 2018-01-15 18:56
when you will give this update bothers ~~~

**Comment by aghassemi** [comment] 2018-01-19 02:30
infinite scroll for `amp-list` is planned for this Q1, depending on how far we get with other priorities it may slip into Q2.

**Comment by cathyxz** [comment] 2018-11-21 20:40
Let's track this via the master issue for infinite scroll here:  #14060

**Comment by nainar** [comment] 2019-02-01 17:59
Since this issue is being tracked as part of #14060. Closing this issue as a dupe.

**Closed by nainar** 2019-02-01 17:59 UTC
Labels: Category: Dynamic/Personalized Content, Type: Feature Request
