### ISSUE TITLE
🏗️ Make build artifacts available from master

### ISSUE THREAD

**Issue by taymonbeal** [ampproject/amphtml#19955] opened 2018-12-18 17:14 UTC
For parties (such as my team at Google) that are somehow integrating AMP into their offerings, it's useful to have AMP runtime binaries built from the latest GitHub master available at any given time, so that if a change breaks us we can find out about it immediately, before it's released. We could build it from source, of course, but that requires setting up a bunch of infrastructure and possibly worrying about security-sandboxing the build process since it uses all kinds of packages from npm. Meanwhile, if I understand correctly, Travis is already running the build process on every commit.

I think it should be reasonably straightforward to have Travis, on the conclusion of a successful build from master, upload the resulting build artifacts either to a [GitHub release](https://docs.travis-ci.com/user/deployment/releases/) or to [Google Cloud Storage](https://docs.travis-ci.com/user/deployment/gcs/). Then it would be possible for anyone to download the latest-from-master AMP runtime at any time. Is this something the AMP team could do?

**Comment by torch2424** [comment] 2018-12-19 02:11
Triaging to @erwinmombay or @rsimha 😄

**Comment by rsimha** [comment] 2018-12-19 03:36
@danielrozenberg was talking about doing this, and I believe the reason why this might be hard to do is GitHub's rate limits. Not sure if that's indeed a problem if we associate the artifacts with a release.

**Comment by taymonbeal** [comment] 2018-12-19 04:44
I'm confused about how this could possibly result in a rate-limit problem. According to the Insights tab, there are on the order of 100 commits to master per week, less than one per hour.

**Comment by rsimha** [comment] 2018-12-19 16:19
I may have used the wrong words when I said "rate limits". IIRC, the old discussion was around storing binary files in a separate repository for artifacts under `ampproject`.

Based on my reading of the [Travis](https://docs.travis-ci.com/user/deployment/releases/) and [GitHub](https://help.github.com/articles/about-releases/) documentation around releases, making binaries available certainly looks possible.

@cramforce @mrjoro, is this something we'd like to support? Do you see any downsides?

**Comment by rsimha** [comment] 2019-05-30 23:56
Assigning to @danielrozenberg who is working on automated nightly releases.

**Comment by danielrozenberg** [comment] 2019-06-04 17:48
More-or-less a duplicate of #20142, let's track this feature request there

**Closed by danielrozenberg** 2019-06-04 17:48 UTC
Labels: Category: Tooling, Type: Feature Request
