### ISSUE TITLE
No javascript amp pages

### ISSUE THREAD

**Issue by demil** [ampproject/amphtml#34027] opened 2021-04-27 14:49 UTC
## Why amp validator don't allow no javascript amp pages without any custom amp element and with all css amp guidelines respected

If we have clear html and inline css page with no images or any other custom amp tag, with just text, why we should include amp javascript to make page heavier just to pass amp validation? Amp javascript should be mandatory only if there is need for custom amp elements. When native lazy loading of images lands in all browser then we could have html/css pages with even images that should be completely amp compatible and valid without any javascript loaded on page and with following all css guidelines for amp. Those simple pages should be amp compatible and have benefits of crawling and caching amp pages.

**Comment by Francisco-AM** [comment] 2021-04-29 11:23
First you would lose all the benefits that amp gives you.

asynchronous script loading,
asynchronous iframe loading
asynchronous images and lazy loading
cache in images, scripts and css.
global cdn

The v0.js 80 kb download file will only be uploaded once to the user then it is cached.
page 1 80kb page 2 0kb cache file

amp js is not a validator it is an enhancer.
Scripts do not run in a single thread they run in multi-thread in the browser.
Animations are optimized

If you still don't like this alternative, you can always use bento.

**Comment by demil** [comment] 2021-04-29 11:29
But with:

No scripts
No iframes
No images

Why should my page contain amp js to be cached and amp valid?

**Comment by Francisco-AM** [comment] 2021-04-29 12:21
ok wait and let me explain, watch the first seconds of this video so you can see how the cache works
1:35 to 1:45 
https://youtu.be/vo7X65f2elg?t=97

ok once the script is cached the client will not need to download it again

To take advantage of the maximum power of this behavior you need all your pages and all the navigation in your pages to be amp

If you have two pages amp and 9 pages no amp, you will not be able to take advantage of this behavior.

If you are going to make pages without script, without css and without images, you are still not understanding amp.

amp is first users and seeks maximum user interaction and loyalty.

I am a contributor I hope I have been able to help you.

If you are going to make pages only text by positioning then amp is not for you

**Comment by demil** [comment] 2021-04-29 12:23
You dont get it.

My all pages DOESNT HAVE IMAGES OR JAVASCRIPT, and why should I require v0.js just to be cached on google amp servers when I dont use javascript at all nor images nor iframes, just html and css which follows amp guidelines?

**Comment by Francisco-AM** [comment] 2021-04-29 12:34
If your pages are just text then you don't need amp, your pages are already fast enough and you won't benefit from amp

https://developers.google.com/search/docs/advanced/crawling/overview-google-crawlers?hl=es-419&visit_id=637552963195052049-3212108798&rd=1

Anyway I think you are posing your problem on the wrong site, this git is not for seo or positioning, if you have doubts you can take a look at the google documentation and report there because your pages are not indexed for mobile.

**Comment by demil** [comment] 2021-04-29 12:37
I can benefit from amp with amp cache and if my page is compatible with all amp guidelines it should have benefit of amp cache without including unnecessary script that actualy doesnt do anything on page without amp custom elementa.

**Comment by Francisco-AM** [comment] 2021-04-29 12:50
You for example have it very simple if your pages are so simple you could use amp to create a pwa.

Then you could pre-cache all the documents when a user visited your web page and the navigation would be extremely fast you only need to include amp js and also a service worker.
https://amp.dev/en/documentation/guides-and-tutorials/learn/combine-amp-pwa/

the js of amp I already told you that it is only loaded once in the user's navigation, it makes no sense to continue in that direction, I think I can no longer help you and I unsubscribe from this thread, a greeting

**Comment by demil** [comment] 2021-04-29 13:15
It ia not about loading and local caching, it is about dobt want to use or execute javascript but i want to my pages be cached on AMP CDN. I think that whole this time you dont understand point while in first comment Kristofer agreed that amp scriot should be mandatory only if there is need to use amp custom element. Amp is paradigm and convention, not a javascript framework as you present.

**Comment by kristoferbaxter** [comment] 2021-04-29 16:02
For reference, I've started a PR here for supporting `img` elements within AMP documents so long as they contain either a `loading=lazy` or `loading=eager` attribute.

https://github.com/ampproject/amphtml/pull/34028

**Comment by jridgewell** [comment] 2021-11-23 19:42
Closing as a duplicate of https://github.com/ampproject/amphtml/issues/24232, which is fixed.

**Closed by jridgewell** 2021-11-23 19:42 UTC
Labels: Type: Discussion/Question
