### ISSUE TITLE
Error: Unexpected end of JSON input

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#21110] opened 2019-02-26 21:21 UTC
Error: Unexpected end of JSON input
at (unexpected-end-of-json-input.js:1)

go/amp-error/CK6EmuuQ5vKB3gE

I don't know if this is AMP related or not, feel free to close.

**Comment by jridgewell** [comment] 2019-02-26 21:35
Dupe of https://github.com/ampproject/amphtml/issues/20690

**Closed by jridgewell** 2019-02-26 21:35 UTC
Labels: P2: Soon, Type: Bug
