### ISSUE TITLE
amp-date-countdown example in documentation causes "insufficient trust" error

### ISSUE THREAD

**Issue by fstanis** [ampproject/amphtml#16652] opened 2018-07-10 16:40 UTC
The current example in the `amp-date-countdown` sample relies on `.hide` and `.show` which require user action and thus cause an error (see #16567). 

https://github.com/ampproject/amphtml/blob/703aad74ebe0c045389c69e2d43041ffb2bbe9f8/extensions/amp-date-countdown/amp-date-countdown.md#L177

The sample under `examples` uses `amp-animation` instead:

https://github.com/ampproject/amphtml/blob/703aad74ebe0c045389c69e2d43041ffb2bbe9f8/examples/amp-date-countdown.amp.html#L102

We should either update the documentation to use the same approach as the sample or, preferably, wait until #13973 is done, since (if I understand correctly) this will effectively allow for a less-hacky approach.

**Comment by leonalicious** [comment] 2018-07-11 12:43
omg, sorry for the mistake, i missed out the coding here

**Comment by aghassemi** [comment] 2018-07-16 17:03
Closing since it is by design for `amp-date-picker` and the error message was improved in https://github.com/ampproject/amphtml/pull/16600

**Comment by aghassemi** [comment] 2018-07-16 17:06
reopening since documentation needs updating

**Comment by aghassemi** [comment] 2018-07-16 21:51
I'll take this one

**Closed** 2018-07-17 11:37 UTC
Labels: Category: Presentation, Closed: Intended, Related to: Documentation, Type: Bug
