### ISSUE TITLE
Scrolling issues with iframe in lightbox

### ISSUE THREAD

**Issue by ebbeck** [ampproject/amphtml#6290] opened 2016-11-22 00:14 UTC
I currently have an iframe that is loaded in a lightbox. When the content in the iframe extends the lightbox i can't scroll in ios. When i start scrolling the page content can be seen at the bottom of the screen as it scrolls.

I tried adding -webkit-overflow-scrolling: touch; and it works intermittantly and when you click out of the lightbox then open it again the iframe content is not displayed.

An example can be found here:
https://www.eventbrite.com/e/amp-test-ios-scroll-event-tickets-29597149872/amp

STR
1. go to above url on ios (safari or chrome)
2. click orange tickets button
3. scroll to bottom of iframe

I asked this question on the amphtml slack channel and was sent here to post an issue

any help would be appreciated.

**Comment by ericlindley-g** [comment] 2016-11-26 20:23
Thanks for filing, @ebbeck — I think this is a duplicate of https://github.com/ampproject/amphtml/issues/4274, which addresses the issue of `amp-lightbox` not being scrollable. Tentatively closing this bug, but please feel free to re-open if https://github.com/ampproject/amphtml/issues/4274 doesn't cover what you need.

**Closed by ericlindley-g** 2016-11-26 20:23 UTC
Labels: Closed: Duplicate
