### ISSUE TITLE
Text children node outside of the AMP Story page element

### ISSUE THREAD

**Issue by manisaiprasad** [ampproject/amphtml#21412] opened 2019-03-14 11:23 UTC
In AMP story it's possible to create an amp-story that has text nodes as its immediate children. They are shown outside of any amp-story-page elements. We should remove these, on the build.

**Comment by newmuis** [comment] 2019-03-14 13:36
This is a duplicate of #21346.

**Closed by newmuis** 2019-03-14 13:36 UTC
Labels: Type: Bug
