### ISSUE TITLE
AMP images not loading after few(1000px) from the top of browser

### ISSUE THREAD

**Issue by satishsurve** [ampproject/amphtml#25555] opened 2019-11-12 06:49 UTC
## What's the issue?
AMP Images not loading after the first few hundred pixels from the top of the browser. Initial viewport(top 1000px) sections images are loading correctly but when we scroll down page (after some 1000px) not loading AMP images.

As per my observation after AMP page rendering amp-image tag should be converted to like this -
![image](https://user-images.githubusercontent.com/3388571/68647903-0b60d880-0545-11ea-9216-bc60a879ed3e.png)

but getting AMP image tag like this after top (1000 px) -
image
![image](https://user-images.githubusercontent.com/3388571/68647878-f97f3580-0544-11ea-9bd8-b7b2360c12c9.png)

When we resize the page, AMP images loading correctly.

## What browsers are affected?
Chrome - Version 78.0.3904.97 (Official Build) (64-bit)

## Which AMP version is affected?
using https://cdn.ampproject.org/v0.js

**Comment by alanorozco** [comment] 2019-11-12 21:09
@satishsurve Hi, which runtime version are you running? Your console should print it as part of the first message.

**Comment by satishsurve** [comment] 2019-11-13 06:06
@alanorozco Thanks for your quick response.
We are using runtime version is  - 1911062056110

**Comment by jridgewell** [comment] 2019-11-18 21:35
Do you have a demo page?

**Comment by satishsurve** [comment] 2019-11-21 13:40
@jridgewell  Please find demo on below link

https://satishsurve.github.io/

Just to remind: open above URL in mobile and try to scroll to reproduce the issue.

 Also you can check  source code on below link
https://github.com/satishsurve/satishsurve.github.io/blob/master/index.html


Thanks!

**Comment by jridgewell** [comment] 2019-11-21 22:50
Ahh, I see. You're using an `overflow: scroll` container, which AMP doesn't yet directly support. We have an experimental build that enables the feature, you can see instructions at https://github.com/ampproject/amphtml/issues/24929#issuecomment-555205220.

Closing this a duplicate of https://github.com/ampproject/amphtml/issues/24929.

**Closed by jridgewell** 2019-11-21 22:50 UTC
Labels: Type: Bug, UI: Component: amp-img

**Comment by satishsurve** [comment] 2019-11-22 04:50
Thanks! @jridgewell :)
