### ISSUE TITLE
TypeError: Cannot read property 'createdCallback' of null

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#7652] opened 2017-02-17 23:13 UTC
```
TypeError: Cannot read property 'createdCallback' of null
    at HTMLElement.Lf.b.gc (https://cdn.ampproject.org/rtv/031487358851767/v0.js:150:67)
    at https://cdn.ampproject.org/rtv/031487358851767/v0.js:162:43
```

Seeing this in Android and iOS, so not a nessy.

Original locations are:
```
Cannot read property 'createdCallback' of null
    at HTMLElement.Lf.b.createdCallback (https://raw.githubusercontent.com/ampproject/amphtml/1487358851767/src/custom-element.js:632:7)
    at https://raw.githubusercontent.com/ampproject/amphtml/1487358851767/src/custom-element.js:994:26
```

**Comment by dvoytenko** [comment] 2017-02-21 19:01
This is in fact a user error. It happens because `amp-ad` does not have a `type` attribute. As the result, the element is not routed correctly (nowhere to route really). See [amp-ad.upgradeCallback](https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad/0.1/amp-ad.js#L56).

Since this is a user error - the fix is simply to throw a user error in the same line of code above instead of letting it fail later with dev error.

@Gregable But first I'd like to check why this situation should not be allowed by validator? It seems to be marked as a [mandatory attribute](https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad/0.1/validator-amp-ad.protoascii#L77)?

/cc @tdrl

**Comment by Gregable** [comment] 2017-02-22 19:24
I just tried this out in validator.ampproject.org, using the following test:

```
<!doctype html>
<html ⚡>
<head>
  <meta charset="utf-8">
  <link rel="canonical" href="self.html" />
  <meta name="viewport" content="width=device-width,minimum-scale=1">
  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <script async custom-element="amp-ad" src="https://cdn.ampproject.org/v0/amp-ad-0.1.js"></script>
</head>
<body>
  
  <amp-ad width="300" height="250" data-aax_size="300x250" data-aax_pubname="test123" data-aax_src="302">
  </amp-ad>
  
</body>
</html>
```

The validator is erroring with `The mandatory attribute 'type' is missing in tag 'amp-ad'.`, so it appears to be working as intended. @jridgewell is this happening on an URL in the cache, or at the origin? Does the document validate?

**Comment by jridgewell** [comment] 2017-02-22 19:57
Seems to be both pages shown on SERP through the cache, and origin domains.

- From cache
  - `<amp-ad data-slot height=250 layout=fixed type width=300></amp-ad>`
  - https://amp-tomsguide-com.cdn.ampproject.org/v/amp.tomsguide.com/us/what-is-amazon-prime,news-18041.html?amp_js_v=7
- Origin
  - This crazy mess:

        </tr><tr><td>			<amp-ad class="ampforwp-incontent-ad"></amp-ad></td></tr><tr><td>				type="adsense"</td>
        </tr><tr><td>				width="360"</td>
        </tr><tr><td>				height="280"</td>
        </tr><tr><td>				data-ad-client="ca-pub-1257003064879721"</td>
        </tr><tr><td>				data-ad-slot="9943249892"</td>
        </tr><tr><td>			&gt;</td>

  - Which turns into `<amp-ad class="ampforwp-incontent-ad"></amp-ad>`
  - http://www.upsctoday.com/upsc-syllabus/amp

**Comment by jridgewell** [comment] 2017-02-22 20:00
@dvoytenko If something fails to upgrade, can we default to `ElementStub`?

**Comment by Gregable** [comment] 2017-02-22 21:48
I see. In this case `type` is set, but to the value of empty string. Dima, would disallowing the empty string be sufficient, or are there other cases to worry about, ie: (`type=garbage`)

**Comment by Gregable** [comment] 2017-02-22 23:18
@dvoytenko rather

**Comment by dvoytenko** [comment] 2017-02-24 05:18
It looks like @jridgewell is implementing runtime check. I think we can just require non-empty value. But I wonder how many pages we will invalidate this way. It'd be somewhat unfortunately to invalidate many pages because of ads.

**Comment by Gregable** [comment] 2017-02-24 18:59
@dvoytenko I tested a non-empty check against a sample of 10,000 random documents and found no new failures, so this is a rare case. Given such, and that it's trivial to mandate in validation, should we just go ahead with this?

**Closed** 2017-02-28 00:21 UTC
Labels: Category: Validator, P2: Soon, Type: Bug
