### ISSUE TITLE
Images not loading when a carousel is present inside a lightbox

### ISSUE THREAD

**Issue by supriya-raj** [ampproject/amphtml#9644] opened 2017-05-31 19:45 UTC
## What's the issue?
I have a set of 4 thumbnails shown as preview and 'on tap' of  any of these,I do the following 2 actions:
1. Open a lightbox that has a carousel composed of the same 4 images(however the urls of images used in the carousel are different from the ones used for preview ..for better clarity).
2. Use goToSlide to show the relevant slide in the carousel.

The issue I noticed is that when I click on a thumbnail with index say 2, the images for indexes 1 and 3 (i.e the one preceeding and following) are fetched(saw this in the networks tab).Now when I close the lightbox and tap on the 0th thumbnail, no call is made and hence the image is not displayed i.e the lightbox opens up along with the carousel, and the loader is shown perpetually.

**This does not happen when the carousel is displayed upfront and not inside a lightbox
**This issue is different from #8420 in that the urls of images used in carousel and preview are different in my case

## How do we reproduce the issue?
Code: http://jsbin.com/nizalikevu/edit?html,output

1. Click on the first image
2. Close the lightbox
3. Click on the 3rd or the last image

## What browsers are affected?
all

## Which AMP version is affected?
1496245713200

**Comment by muxin** [comment] 2017-07-11 20:29
@supriya-raj I cannot reproduce anymore. Maybe it already got fixed. Could you check on your side that it is behaving correctly?

**Comment by muxin** [comment] 2017-07-13 20:04
I think this is fixed. @supriya-raj I'm closing the issue. Free feel to reopen it if it happens again.

**Closed by muxin** 2017-07-13 20:04 UTC
Labels: Category: Presentation, P2: Soon, Type: Bug

**Comment by supriya-raj** [comment] 2017-08-01 06:57
@muxin Yes..thanks..it has been fixed now
