### ISSUE TITLE
AMP analytics remote config response with set-cookie header is not working in safari on the google domain.

### ISSUE THREAD

**Issue by jasonconway-williams** [ampproject/amphtml#19634] opened 2018-12-04 20:21 UTC
## What's the issue?

My team recently implemented a change as a workaround to [this issue](https://github.com/ampproject/amphtml/issues/19172). We added a call on the amp-analytics element to retrieve a remote config file. The remote config contains the _ga id to be used on the page. If the request contains a _ga cookie, the content of the cookie is sent back in the response as the cid. If not, a new _ga id is generated and a Set-Cookie header is returned in the response containing the newly created _ga id value. 

It seems that this doesn't work in Safari on mobile for new users where a new _ga id needs to be generated. The response contains the Set-Cookie header as expected but safari does not set the cookie. This causes a broken GA session when the user navigates from the google domain to our domain.

This functionality regarding cross domain cookies in safari is explained in [this stackoverflow issue](https://stackoverflow.com/a/27944986)

## How do we reproduce the issue?

If this is a bug please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else.  Then provide step-by-step instructions for reproducing the issue:

1. On mobile, clear your browser history to ensure that you don't have a pre-existing travelsupermarket _ga cookie.
2. Visit https://www.google.co.uk/amp/s/www.travelsupermarket.com/en-gb/holidays/amp/spain/balearic-islands/ibiza/
3. Inspect the network tab (debugging in the safari console) and apply a filter of "config". The response headers of the https://www.travelsupermarket.com/ga/staging/global/ga-config/v1 request will contain a Set-Cookie header.
4. Scroll down the page to trigger a GA collect call. You will see that the cid value of the call matches the cid returned in the config/v1 call.
5. Perform a search by clicking the search button. This will direct you to the travelsupermarket.com results page.
6. Inspect the cookies for the travelsupermarket domain: The id defined in the _ga cookie will not match the value returned in the config/v1 call on the previous page.
7. Inspect the network tab and look at the cid in the collect calls. The cid will not match the value returned in the config/v1 call  on the previous page.

If this is a feature request you can use this section to point to a prototype/mockup that will help us understand the request.

## What browsers are affected?

Safari, Iphone 5, 6, 7, 8, 10

## Which AMP version is affected?

Version 1811202257200

**Comment by torch2424** [comment] 2018-12-06 02:35
Adding @zhouyx to this issue, and we investigated a similar issue recently?
Is this related to the safari thing where the `sendBeacon` API wasn't working?

@jasonconway-williams Thanks for the issue! Will be sure to bring this up to our team!

**Comment by torch2424** [comment] 2019-05-02 20:46
@jasonconway-williams Is this still an issue for you?

@calebcordry Did you see @jeffjose response? If this is something linker fixes, I think we can point them to the docs and close this issue out 😄 👍

**Comment by calebcordry** [comment] 2019-05-02 20:53
Sorry for the delay, @jeffjose is correct you will need to use linker to decorate links from cache => self hosted. Please see our docs https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/linker-id-forwarding.md to forward this unique id, and https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/linker-id-receiving.md to receive it. Let me know if you have any more questions.

**Comment by torch2424** [comment] 2019-05-02 20:55
Thank you @calebcordry ! I'll go ahead and close this, since the issue is a bit stale. But if this doesn't solve your problem @jasonconway-williams feel free to reply here, and we can re-open. Thank you everyone! 😄

**Closed by torch2424** 2019-05-02 20:55 UTC
Labels: Category: Analytics, P2: Soon, Type: Bug
