### ISSUE TITLE
New amp-carousel jitters when changing slides

### ISSUE THREAD

**Issue by poscar** [ampproject/amphtml#5407] opened 2016-10-04 20:21 UTC
## How do we reproduce the issue?

Observe the carousel included in the following example:
http://output.jsbin.com/mojuqakosu
1. Switch slides by clicking the next or prev buttons.

**Result:** Jitter as slides are transitioned.
**Expected Result:** No jitter.
## What browsers are affected?

Specifically tested:
Chrome: 53.0.2785.116
Safari: 9.0.3 (11601.4.4)
## Which AMP version is affected?

`Powered by AMP ⚡ HTML – Version 1475106123549`

Note that we did not observe any jitter with this same markup under the old `amp-carousel`.  Any ideas?

**Comment by sriramkrish85** [comment] 2016-10-04 20:24
@poscar is this on a linux machine?

**Comment by sriramkrish85** [comment] 2016-10-04 20:27
if this is on a linux machine - possibly a dupe of - https://github.com/ampproject/amphtml/issues/5092

**Comment by poscar** [comment] 2016-10-04 20:31
@sriramkrish85 I'm under MacOS 10.11.3

**Comment by sriramkrish85** [comment] 2016-10-04 20:52
Okay ! Could you upload a video of what you are seeing ? That would be very helpful

**Comment by poscar** [comment] 2016-10-04 21:04
@sriramkrish85 yessir, here it is:
[amp-carousel-jitter.zip](https://github.com/ampproject/amphtml/files/509523/amp-carousel-jitter.zip)

**Comment by sriramkrish85** [comment] 2016-10-04 22:00
Ugh. That looks ugly -  (im still not able to repro on my mac :) )

Chrome: Version 53.0.2785.116 (64-bit)
OSX - 10.11.6 (15G31)

Will dig into this.

**Comment by sriramkrish85** [comment] 2016-10-04 22:21
@poscar i could not see images on your js bin may be thats why im seeing the jitter - could you post a direct url if you have one.

**Comment by poscar** [comment] 2016-10-05 14:45
@sriramkrish85 ah yes, sorry. Here it is: http://www.wmagazine.com/story/why-alice-lancaster-and-other-young-artists-are-making-their-names-with-fashion-collabs-first/amp

**Comment by jaygray0919** [comment] 2016-10-05 16:01
Per previous issue, can also be seen here:
  https://www.ampproject.org/

**Comment by jaygray0919** [comment] 2016-10-05 18:34
Seems to us that this is a severity-level-1 problem. We see this problem on our carousel's, on Google AMP carousels, and on publisher carousels such as the Guardian.

**Comment by camelburrito** [comment] 2016-10-05 18:43
@poscar - https://www.youtube.com/watch?v=NYQvNFiXG7Q - this is what i am seeing on 

Chrome: Version 53.0.2785.116 (64-bit)
OSX - 10.11.6 (15G31)

On an external monitor. Looks like the issue is on smaller screens.

Works perfectly fine on all Cellphones too. 

@jaygray0919 -  this has nothing to do with Google search carousel

Will try and see if can isolate the problem and do a quick fix.
--

**Comment by camelburrito** [comment] 2016-10-05 18:46
Works well on my 13" mac pro - but was able to repro on my colleague's 15" pro. Will keep digging

**Comment by poscar** [comment] 2016-10-05 18:48
@camelburrito 

This is very weird.

I see this: https://youtu.be/dFPX5pQeKOM

**Comment by camelburrito** [comment] 2016-10-05 18:54
@poscar @jaygray0919 can you post your monitor sizes (and makes if using external monitor) and mention if you are using retina displays. 

@poscar could you try this out on some other machine/monitor.

@jaygray0919 -- understood - the issue is with the carousel so we will see it on all sites -- also post your browser/os versions

**Comment by poscar** [comment] 2016-10-05 20:03
@camelburrito it doesn't on my machine happen if I simulate an iPhone 6 with the Chrome Dev Tools.  Leads me to believe that this might some inconsistent animation math within the new `amp-carousel` component.

**Comment by jaygray0919** [comment] 2016-10-05 21:10
Am running dual HP w2007 monitors, Windows 10 Pro. 1050 x 1680 and reverse. Other team members are running smaller external monitors on Windows 7 and Windows 10 platforms - they too see the same problem. One team member runs a MacBook (uncertain version) and does not see the problem.

**Comment by jaygray0919** [comment] 2016-10-05 21:15
We believe this problem began 4 to 6 weeks ago. We know all of our implementations worked before then. We began to see the problem ~ 4 weeks ago but didn't take it seriously. A week ago we revisited previous work and realized we had a problem. When we reproduced the results on Google pages and Guardian pages, we were somewhat relieved because it no longer seemed to be just our problem. No snarking here, just the day-to-day reality of software development.

**Comment by camelburrito** [comment] 2016-10-05 21:24
the only difference i see between the machines is the model of the graphics cards :) This is hard to 

@jaygray0919 - We did launch an improvement on carousels last week (now you can have good swiping experience on your mobile devices and now we can swipe through iframes/embeds). not sure what you saw 4-6 weeks ago.

**Comment by camelburrito** [comment] 2016-10-06 00:23
This will be on prod along with next Week's release

**Comment by jaygray0919** [comment] 2016-10-06 00:31
We're developers. ~6 weeks ago it worked; today it does not. Please roll back to a working version.

**Comment by poscar** [comment] 2016-10-06 16:06
Great, thank you @camelburrito !!

**Comment by eike-hass** [comment] 2016-11-01 08:49
Should the fix have landed by now? We still see that issue

**Comment by poscar** [comment] 2016-11-01 13:36
@eike-hass we haven't seen this issue after the fix went live weeks ago.

**Comment by sebastianbenz** [comment] 2016-11-01 14:15
@eike-hass which platforms/browsers are affected? Which AMP runtime version are you using?

**Comment by cramforce** [comment] 2016-11-01 14:16
@eike-hass Could you make a video of the problem? Seems like this is something else from what @poscar is seeing.

**Comment by eike-hass** [comment] 2016-11-01 14:36
https://gfycat.com/HeartfeltSecondaryGermanpinscher
this is what i am seeing on https://www.ampproject.org/ with Chrome Version 54.0.2840.71 m and AMP Version 1477334765771

**Comment by cramforce** [comment] 2016-11-01 14:41
@eike-hass Wow :)

**Comment by cramforce** [comment] 2016-11-01 14:46
@eike-hass Are you seeing this on other pages? I can repro a less dramatic effect, that seems to be related to buggy `border-radius` render in Chrome (pretty bizarre, compare how the page looks on Safari).

Are you seeing the same problem on other carousels? Just want to make sure this is not just a Chrome bug related to this particular HTML setup.

**Comment by cramforce** [comment] 2016-11-01 15:14
@pbakaus for the `border-radius` Chrome bug. I think we should just remove the radius (it never renders in Chrome anyway), but should likely also file a crbug.com

**Comment by eike-hass** [comment] 2016-11-01 15:53
@cramforce i see the same jittering on https://ampbyexample.com/components/amp-carousel/ on the second and third carousel

**Comment by camelburrito** [comment] 2016-11-01 15:57
What is the OS ?

**Comment by eike-hass** [comment] 2016-11-01 16:04
@camelburrito Windows 10.0.14393

**Comment by eike-hass** [comment] 2016-11-04 14:02
@camelburrito could you reproduce the issue?

**Comment by eike-hass** [comment] 2016-11-10 16:31
The Issue seems to persist with Chrome 56.0.2915.0 canary and AMP 1478272520861 on Windows 10

**Comment by jridgewell** [comment] 2016-11-10 20:13
Ping @camelburrito

**Comment by camelburrito** [comment] 2016-11-11 02:27
@eike-hass - i am running around using different machines to reproduce this - no luck yet - ill fire up my old windows laptop and try it out. So far no luck in reproducing -

**Comment by sebastianbenz** [comment] 2016-11-11 07:01
@eike-hass you've probably done this, but just to be sure: does it still happen if you disable all Chrome extensions, clear all caches and serviceworkers?

**Comment by camelburrito** [comment] 2016-11-11 18:44
I revived my pentium 4 desktop and installed windows7 and latest chrome. I did not see the jitter. 
But when i inspected the page and then went to mobile mode and then came back to desktop mode, i found a visible jitter, and the jitter is gone when i reload the page.

Other than this i did not see jitters anywhere.

**Comment by eike-hass** [comment] 2016-11-12 10:23
I investigated with a different machine and a fresh chrome install. No Jitter. Will report back as soon as i have the "jitter"-machine on my hands again.

**Comment by eike-hass** [comment] 2016-11-16 09:35
Back at the jitter machine. The issue persists in fresh canary install. My best guest is that has something to do with it having "retina" resolution. Will try to verify with another device.

**Comment by eike-hass** [comment] 2016-11-16 13:52
@camelburrito we can reproduce this issue on other windows 10 "retina" devices like the surface pro.

**Closed** 2016-12-02 23:47 UTC
Labels: Type: Production Bug

**Comment by eike-hass** [comment] 2016-12-05 13:45
Tested against latest ´master´. Seems to work great!
