### ISSUE TITLE
Support submitting form with shortcut

### ISSUE THREAD

**Issue by Bill-SnowWolf** [ampproject/amphtml#21120] opened 2019-02-26 21:48 UTC
## Describe the new feature or change to an existing feature you'd like to see

We use <textarea> in a form. It would be nice we can set some shortcut to submit form like using '⌘/Ctrl + Enter'.

**Comment by torch2424** [comment] 2019-03-01 23:18
Triaging to @cvializ , feel free to re-assign 😄

**Comment by cvializ** [comment] 2019-03-04 18:24
@Bill-SnowWolf thanks for the feature request! This would be a great enhancement to add to amp-form. We don't have resources available to work on this now, but it's the perfect size for our next fixit sprint.

**Comment by caroqliu** [comment] 2019-10-03 21:42
Unassigning myself for now in case anyone wants to pick up as a GFI

**Comment by neelgeek** [comment] 2020-10-07 23:11
@caroqliu  I would like to try this.

**Comment by caroqliu** [comment] 2020-10-08 13:22
Apologies, this feature was already introduced by #26152. This issue must have been a duplicate of #26004. Thanks for your enthusiasm! If you would like to make a contribution related to this change, you could update the `amp-form.md` with information about this interaction pattern. :)

**Closed by caroqliu** 2020-10-08 13:22 UTC
Labels: P3: When Possible, Type: Feature Request, UI: Component: amp-form, UI: Customer: Developer, UI: Type: DevX, WG: ui-and-a11y, good first issue
