### ISSUE TITLE
amp-form action-xhr enhancement: save results as part of page state

### ISSUE THREAD

**Issue by unitydynamics** [ampproject/amphtml#8610] opened 2017-04-06 13:13 UTC
I'm using the amp-form module to perform a page updated without a page reload. It's working fine. My search results are displayed to the user via an amp-mustache template. BUT when the user clicks into a result and then later hits the back button the results are gone. I need a way to save the state of the page.

So my question is: how can I make the back button show the same results the user originally had? (hopefully without re-fetching). I looked briefly at amp-bind but it says experimental.  This seems like a **very** common use case for me.  form input for search -> search results in-page -> drill to new page about result -> back to search results.

Also I posed this as a [question on StackOverflow](http://stackoverflow.com/questions/43244276/saving-ajax-xhr-state-in-amp-accelerated-mobile-pages-for-back-button-use/)

And potentially this should be baked into the [Product Listing AMP Example](https://ampbyexample.com/samples_templates/product_listing/preview/).

**Comment by aghassemi** [comment] 2017-04-06 17:42
@unitydynamics We are working on a server-side sort/filter solution (search falls under filter). I have added this requirement to that issue to track so closing this as duplicate of https://github.com/ampproject/amphtml/issues/6054

**Closed by aghassemi** 2017-04-06 17:42 UTC
