### ISSUE TITLE
Q: How to add dots to AMP carousel?

### ISSUE THREAD

**Issue by Siton-Systems** [ampproject/amphtml#5712] opened 2016-10-20 11:53 UTC
Without dots the user have no clue "This is a slider". In most sliders the most basic is - three options: "dots" "arrows" "dots and arrows". 

I saw this issue from feb-2016.
https://github.com/ampproject/amphtml/issues/1963

**Comment by jridgewell** [comment] 2016-10-20 19:14
I don't think we currently have that, just the arrows. @camelburrito?

**Comment by camelburrito** [comment] 2016-10-20 19:26
I think we might have something like this in the next version of carousel
@ericlindley-g might be able to fill-in or point to a roadmap

**Comment by ericlindley-g** [comment] 2016-10-20 23:35
The current plan for the next version of the carousel is to use more of a "film strip" at the bottom of the carousel to indicate the number of items in the carousel, and make it easy to go between them, but I'm not averse to having a "dots" affordance that can be toggled instead. The trouble with "dots" is that it starts to break with many items—but then again, it's standard to have a small number of items in these carousels anyway.

I think we can call this issue a duplicate of #1963, so I'm closing this particular issue, and taking the feedback into consideration in developing the next version of the carousel.

**Closed** 2016-10-20 23:36 UTC
Labels: Type: Question
