### ISSUE TITLE
Lightbox pinch and zoom causes scroll leak on IOS

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#3836] opened 2016-06-29 19:32 UTC
open 
https://www.google.com/amp/www.sfgate.com/news/amp/A-s-reinstate-Josh-Reddick-from-DL-8330664.php?client=ms-android-google#

on IOS Safari, 

Click on the 'Read full caption' link on the carousel -> lightbox opens up , play with pinch and zoom and some how you will be able to scroll the page with the light box on and you will see higher z-indexed items on top of the lightbox.

![img_1436](https://cloud.githubusercontent.com/assets/1037311/16465826/8ec0cc28-3df5-11e6-92a5-ed6ad99fa5fa.PNG)

**Comment by sriramkrish85** [comment] 2016-06-29 19:34
cc @cramforce @dvoytenko @ericlindley-g @rudygalfi

**Comment by adelinamart** [comment] 2017-02-08 00:17
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)

**Comment by ericlindley-g** [comment] 2017-02-13 16:47
Possibly same root cause as #6487

**Comment by aghassemi** [comment] 2017-03-24 18:27
Fixed by: https://github.com/ampproject/amphtml/issues/6487

**Closed by aghassemi** 2017-03-24 18:27 UTC
Labels: Category: Presentation, P2: Soon, Type: Bug
