### ISSUE TITLE
Web Stories Page Attachment Text Does Not Update

### ISSUE THREAD

**Issue by LuckynaSan** [ampproject/amphtml#37487] opened 2022-01-26 16:53 UTC
### Description

The page attachment text does not update or reflect the text set in the editor. See test story: https://testsite.cmsdevrel.com/web-stories/test-cta/

Related WS GH ticket: https://github.com/GoogleForCreators/web-stories-wp/issues/10391
Related WS Support Topic: https://wordpress.org/support/topic/updating-page-attachment-text

### Reproduction Steps

Create a new web story using Web Stories Plugin v1.16.0
Add a page attachment
Add a new story page
Add a page attachment with different text
publish and preview the story.
Note the text on the page attachment does not change

Editor:
<img width="806" alt="Screen Shot 2022-01-26 at 11 32 26 AM" src="https://user-images.githubusercontent.com/66372350/151208994-40844de8-5623-4332-9ed5-1a422a682416.png">
Preview:
<img width="654" alt="Screen Shot 2022-01-26 at 11 32 42 AM" src="https://user-images.githubusercontent.com/66372350/151209008-5a912c71-0501-4ca9-b583-9486514b4647.png">

Editor:
<img width="800" alt="Screen Shot 2022-01-26 at 11 32 20 AM" src="https://user-images.githubusercontent.com/66372350/151209080-d778a532-70aa-419f-be86-59fa7820c4af.png">
Preview:
<img width="688" alt="Screen Shot 2022-01-26 at 11 32 36 AM" src="https://user-images.githubusercontent.com/66372350/151209098-21bc7053-ae10-49f4-bed4-6494c8574293.png">

### Browser(s) Affected

Chrome, Firefox, Safari, Edge

### Device(s) Affected

macOS

**Comment by powerivq** [comment] 2022-01-26 19:18
Thank you for filing the issue. It looks like the issue is a duplicate of https://github.com/GoogleForCreators/web-stories-wp/issues/10391 and there are no actionable items on stories working group, as the issue likely rests in the creator tool. We would close it here and please continue following up at that issue.

**Closed by powerivq** 2022-01-26 19:18 UTC
Labels: Type: Bug, WG: stories

**Comment by LuckynaSan** [comment] 2022-01-28 21:26
@powerivq It appears the page attachment text is updating in the source code correctly, however, it does not render in the story player. Could you please check again if this is because of the AMP output?
