### ISSUE TITLE
amp-carousel / amp-img fallback failure on Safari

### ISSUE THREAD

**Issue by AcidRaZor** [ampproject/amphtml#16615] opened 2018-07-09 09:49 UTC
I have WebP images, with a fallback to JPG on the amp-img within a carousel.

Even though the images load fine the first time (falling back to JPG), when you scroll in the carousel while using Safari on iOS, the images start disappearing/appear broken

**Comment by cathyxz** [comment] 2018-07-09 17:28
I think this is a dupe of https://github.com/ampproject/amphtml/issues/16588, which should be fixed by outstanding PR https://github.com/ampproject/amphtml/pull/16404, hence closing for now in favor of #16588 for tracking.

**Closed by cathyxz** 2018-07-09 17:28 UTC

**Comment by AcidRaZor** [comment] 2018-07-10 06:19
@cathyxz Sorry but this isn't a dupe. If I felt it was, I would have posted a comment on the other thread. The resize is never triggered. When someone scrolls on the amp-carousel, amp-img's (webP with fallback to JPG) shows up as "broken". I've tested multiple browsers now as well on mobile devices (as I don't see this behavior happen on desktop)

So unless the amp-carousel is triggering the srcset for some reason when the browser never resizes and height/width are checked, I don't see how it's 100% correlated/related.

This is now the 2nd production bug introduced by the AMP initiative. We've spend 8 months converting and fine-tuning our site to utilize AMP. I'm pretty confident I can get the same render time/speed benefits by some different means, as it's just too risky implementing anything in AMP, go through QA/UAT and end up 2 months later with an inexplicable bug on production with 0 (zero) manageability from our side to target a previous version of AMP that's not broke AF and would not affect our UX so badly as it did.

I'm officially recommending to my company to switch to something we can control in an environment that won't cost us money, both in revenue and dev time

The project is a good idea, poorly executed and 3 years down the line still too much of an infant to be taken seriously.

I wonder how much the e-commerce sites are affected by each time you push a bug out. Why waste my time, my QA team and UAT process on end-users when it's just going to break for no reason 2 months down the line.

/vent

**Comment by erwinmombay** [comment] 2018-08-21 01:53
This is a high priority issue but it hasn't been updated in awhile. @cathyxz Do you have any updates?

**Comment by bohdan-berezhniy** [comment] 2020-09-22 09:46
Hi, I have reproduced the issue
you should use <amp-carousel with   type="slides" and  layout="responsive"
https://opt.demo.magefan.top/amp-img/amp-img.html
