### ISSUE TITLE
Implement a locale redirect mechanism

### ISSUE THREAD

**Issue by mpatnode-si** [ampproject/amphtml#8084] opened 2017-03-13 16:43 UTC
As a world wide publisher, we often publish the same article in multiple locales.    Many of those locales are variants of the same language (typically English).    When a UK, AU or Middle Eastern IP address comes to an article on our US site, we will redirect them to their geographic locale appropriate site if that same article has already been published there.    In many cases, we are contractually obligated to do so such that the partner who maintains the locale site can serve locale appropriate advertising and maintain a revenue stream for their efforts.

Unfortunately our AMP implementation has been undermining this feature since it's not possible for us to check the IP address location in AMP and redirect the user to the locale specific AMP page (which will exist if the article has been copied).   This is resulting in traffic and revenue reduction for our publishing partners, which, unsurprisingly, is making them unhappy.

In our mobile and desktop version, we leverage the same hreflang mechanism the Google Search engine uses to identify locale specific versions of articles. 

We'd be willing to implement and contribute this mechanism but wanted to first make sure something wasn't already in the works.

**Comment by mpatnode-si** [comment] 2017-03-13 19:26
@rudygalfi Are you working on something like this?

**Comment by aghassemi** [comment] 2017-03-14 22:09
@ericlindley-g @dvoytenko

**Comment by ericlindley-g** [comment] 2017-03-16 02:02
Thanks for reaching out,  @mpatnode-si 

At a page level, I think you could get the result you're looking for by creating separate canonical pages and separate AMP pages for each language, and using hreflang to indicate which version is appropriate for each locale. (This avoids the user experience cost of having a redirect)

We're looking into methods for geo-variation that could apply to more localized parts of each page, but that wouldn't apply to something as broad as the language for the entire page.

**Comment by mpatnode-si** [comment] 2017-03-16 16:24
@ericlindley-g That is what we do today, but in order to help our partner's business to be viable, we also redirect when links are shared on Social Media or elsewhere.   If the post is in the same language, but has been localized to your geography, we redirect you to the local provider of our services.   I can understand your reluctance to allow redirects, but it's a subtle way in which AMP undermines our partner's business.

**Comment by ericlindley-g** [comment] 2017-06-01 16:03
Closing as duplicate of the geo variation work: https://github.com/ampproject/amphtml/issues/826

**Closed by ericlindley-g** 2017-06-01 16:03 UTC
Labels: Category: Framework, Related to: Localization, Type: Feature Request
