### ISSUE TITLE
Amp-iframe resizing postmessage restrictions

### ISSUE THREAD

**Issue by NataliaLKB** [ampproject/amphtml#1408] opened 2016-01-13 12:14 UTC
An enquiry regarding the [resizing](https://github.com/ampproject/amphtml/blob/38fbbdd824ed1887c9258b06627fcc394d6310dd/extensions/amp-iframe/amp-iframe.md#iframe-resizing) of `amp-iframes`.

The postmessage requirements are quite strict. At the moment AMP requires:

``` js
{
  sentinel: 'amp',
  type: 'embed-size',
  height: height
}
```

We have an existing resize postmessage in this format:

``` js
{
   type: 'set-height',
   value: height
}
```

Would you consider adding an optional attributes to amp-iframe to specify the type and value to listen for? An example could be:

``` html
<amp-iframe
  message-type="set-height" 
  message-height-key="value" 
  resizable  
  src=".."
>
```

**Comment by dvoytenko** [comment] 2016-01-13 17:11
@NataliaLKB I actually have no problem supporting a few common formats for resizing. Do you use some library for iframes that comes with this format?

@sriramkrish85 I'll assign this to you.

**Comment by cramforce** [comment] 2016-01-13 17:51
@NataliaLKB Was asking for a declarative approach. If we go there, I think that is better than keeping on hard coding more versions.

Something like

```html
<amp-iframe
  data-resize-message-identification="type=set-height" 
  data-resize-value="value" 
  resizable  
  src=".."
>
```

This definitely feels very feature-creepy.

**Comment by stephanfowler** [comment] 2016-01-13 17:58
It's verbose, but I don't think necessarily it's feature-creepy or complex. The alternative is a ton of work for publishers in revisiting all their embeds (most of which are likely to be legacy docs.)

**Comment by NataliaLKB** [comment] 2016-01-13 18:20
I certainly think that a declarative approach is better. Otherwise you may end up with endless requests for slightly different versions.

I wouldn't define it as "feature-creepy" as it isn't really a new feature, but making the existing component  more adoptable.

**Comment by dvoytenko** [comment] 2016-01-13 18:32
I was asking about iframe library because if there are 2-3 very popular iframe resize libraries that people like to use, I really don't see a reason not to implement them internally. But the `resize` message declaration also seems ok to me.

**Comment by cramforce** [comment] 2016-01-13 18:38
@NataliaLKB Did you volunteer to implement this by any chance? :)

**Comment by NataliaLKB** [comment] 2016-01-15 14:36
If @sriramkrish85 doesn't have time, I can take a look next week.

Regarding resizing of the iframes, even when sending the right postmessage, I can't seem to get an iframe to resize. Do you have an example of this working?

Here is a jsbin to demonstrate: https://output.jsbin.com/nenivehuce

Here is how the iframe should look:
![image](https://cloud.githubusercontent.com/assets/8774970/12355546/49b9af4c-bb95-11e5-8fa0-aa7540ef3312.png)


This is all I can see in this example:
![image](https://cloud.githubusercontent.com/assets/8774970/12355542/4065e956-bb95-11e5-9429-2eb71cd37e05.png)

**Comment by cramforce** [comment] 2016-01-15 15:03
@NataliaLKB I think the problem is that you called JSON.stringify on the postMessage payload while that is not expected. Just passing the bare object should work.

@erwinmombay Are you still looking into more robust AMP document developer facing logging? This is the kind of thing we should really write to the console when in development mode.

For implementing this feature request, we should do something like `const data = typeof event.data == 'string' ? JSON.parse(event.data) : event.data` to also support JSON stringified payloads.

**Comment by erwinmombay** [comment] 2016-01-15 21:39
@cramforce i was. i was mostly just classifying `amp-dev` logging vs `pub-dev` logging to DCE all `amp-dev` logging for prod builds. (of course, all `pub-dev` logging should be outputted to console when in dev mode, or be asserted visually on the element itself)

**Comment by dvoytenko** [comment] 2016-01-15 22:39
I think we can easily start without DCE - just add API and then we can split codebase and ask everyone to run through instances and replace with `publog`

**Comment by NataliaLKB** [comment] 2016-01-18 11:39
@cramforce Thanks! Yes that is the problem.

**Comment by NataliaLKB** [comment] 2016-01-22 14:50
I haven't gotten a chance to look into this now, but will hopefully get a chance this weekend.

**Comment by sriramkrish85** [comment] 2016-01-27 04:12
@cramforce so are we planning to do something like this?
Something like this?

```
<amp-iframe
  data-resize-message-identification="type=set-height" 
  data-resize-value="value" 
  resizable  
  src=".."
>
```

**Comment by NataliaLKB** [comment] 2016-01-27 17:38
Is that better then doing:

```
<amp-iframe
  data-resize-message-type="set-height" 
  data-resize-value="value" 
  resizable  
  src=".."
>
```

**Comment by cramforce** [comment] 2016-01-27 18:26
@NataliaLKB It provides some additional flexibility on messages that can be accepted.

E.g. `{resize: true, value: 123}` or `{message: 'resize': height: 123}`

You could also use two attributes to distinguish key and value for this, of course. My proposal could be extended to be slightly more flexible.

**Comment by adelinamart** [comment] 2017-02-03 21:40
Seems the PR is solving part of this.
Is there anything else left to be here?

**Comment by adelinamart** [comment] 2017-02-07 20:48
@NataliaLKB to reply here. Thanks

**Closed** 2017-02-07 20:59 UTC
Labels: Category: Presentation, To be deprecated - Related to: Content, To be deprecated - Type: Enhancement, To be deprecated - Type: Request, Type: Feature Request

**Comment by NataliaLKB** [comment] 2017-02-08 10:03
@adelinamart No its fine. We have worked around it on our end.
