### ISSUE TITLE
Web Stories not showing Quizzes, Polls and SVGs in Latest Chrome Version

### ISSUE THREAD

**Issue by visualstories** [ampproject/amphtml#39866] opened 2024-02-29 10:38 UTC
### Description

Since the latest Chrome update (Version 122), Web Stories are not showing following elements:

1.  **Quiz**
2.  **Poll**
3.  **SVG**
4.  **Images and videos masked with SVG**

Firefox shows everything correctly.

### Reproduction Steps

Below are some examples; **compare them in Chrome and Firefox** to understand the difference:

- [Web Story](https://adventure.visualstories.com/quizzes/quiz-time-get-to-know-about-mountain-biking)
- [Web Story](https://humor.visualstories.com/tickle-your-funny-bone-with-these-hilarious-cake-memes)
- [Web Story](https://pets.visualstories.com/quizzes/how-well-do-you-know-about-sophisticated-maltese-dog-breed)
- [Web Story](https://adventure.visualstories.com/quizzes/can-you-ace-this-trekking-challenge)
- [Web Story](https://nutrition.visualstories.com/top10-summer-fruits-you-must-add-to-your-diet)
- [Web Story](https://pets.visualstories.com/quizzes/keep-your-guard-up-for-this-doberman-quiz)
- [Web Story](https://healthyliving.visualstories.com/what-happens-when-you-dont-get-enough-sleep)
- [Web Story](https://interiordecor.visualstories.com/bedroom-wall-colors)
- [Web Story](https://food.visualstories.com/quizzes/a-cake-quiz-for-a-true-dessert-fan)
- [Web Story](https://fun.visualstories.com/mind-blogging-types-of-puzzles-for-fun)
- [Web Story](https://beauty.visualstories.com/the-ultimate-guide-to-grow-and-maintain-long-hair)
- [Web Story](https://science.visualstories.com/top3-types-of-forests-in-the-world)
- [Web Story](https://selfimprovement.visualstories.com/perseverance-quotes-to-drive-you-towards-success)

**In Chrome, above stories show empty space in slides where there's SVG, masked image/video, quiz or poll. Make sure to compare with Firefox to understand what element should have shown in slides that show empty space.**

### Browser(s) Affected

Chrome, Edge

### OS(s) Affected

All

### Device(s) Affected

All

**Comment by visualstories** [comment] 2024-02-29 10:48
Please look into this on high priority as it has affected most web stories in our client network.

**Comment by erwinmombay** [comment] 2024-02-29 20:39
@visualstories ill take a look

**Comment by erwinmombay** [comment] 2024-02-29 20:42
i can confirm that i am seeing the bug. trying to see if we can get an easy fix cherry picked

**Comment by erwinmombay** [comment] 2024-02-29 22:01
i've verified that is caused by chrome, but have not found a solution or root issue yet

**Comment by ychsieh** [comment] 2024-02-29 22:26
What 122 version are you on? Is it the latest: 122.0.6261.94? If not, could you provide the right one? It will help us narrow down which Chrome release and its changes break it.

**Comment by ychsieh** [comment] 2024-02-29 22:55
Please remove the `align-self: center;` from you CSS selector `.ly-22`. According to the definition(https://developer.mozilla.org/en-US/docs/Web/CSS/align-self), this attribute only works on Grid or Flex items(parent div is in display: grid or display: flex), whereas amp-story-grid-layer is `display: block;`.

**Comment by visualstories** [comment] 2024-03-01 01:47
@ychsieh and @erwinmombay Thank you so much for your quick response. You've nailed it! Removing the css selector indeed solves the problem. We'll have it in production soon.

**Comment by visualstories** [comment] 2024-03-01 05:42
The problem has been solved. Thank you very much for your help.

This issue can be closed now.

**Comment by ychsieh** [comment] 2024-03-04 16:14
No problem! Glad it resolved. Closing it.

**Closed by ychsieh** 2024-03-04 16:14 UTC
Labels: Type: Bug, P1: High Priority
