### ISSUE TITLE
YouTube Video Not Displaying Full Screen Correctly

### ISSUE THREAD

**Issue by nuclearghost** [ampproject/amphtml#1646] opened 2016-01-28 20:06 UTC
On Mac OS X 10.11.2, Chrome Version 47.0.2526.111 (64-bit)

When trying to watch the YouTube video embedded on this page https://www.ampproject.org/docs/get_started/about-amp.html the video doesn't actually go full screen. 

Here's a screenshot of what the video looks like in full screen.
<img width="1920" alt="screen shot 2016-01-28 at 1 47 45 pm" src="https://cloud.githubusercontent.com/assets/2300108/12657277/2a0fbb9a-c5c8-11e5-80b3-d7dfaee222db.png">

Full screen YouTube works fine on the main site and other embeds on third party sites pointing toward an issue with the `amp-youtube` element.

**Comment by dvoytenko** [comment] 2016-01-29 01:16
/cc @cramforce @pbakaus @Meggin 

This is not due to `amp-youtube`. I just replaced it with a simple youtube iframe and the problem persists. I believe this is due to the following CSS on the page:
```
.main .content {
  will-change: transform;
}
```

My best guess is this is some sort of a bug and/or conflict with layering for hardware acceleration. A bug to Chrome is likely due. PTAL.

**Comment by cramforce** [comment] 2016-01-29 01:24
@dvoytenko Do you want to file. Very nice find!

**Comment by dvoytenko** [comment] 2016-01-29 02:39
I guess I should copy the whole document into JSBIN before it gets fixed...

**Comment by dvoytenko** [comment] 2016-01-29 02:51
Filed https://code.google.com/p/chromium/issues/detail?id=582318

**Comment by cramforce** [comment] 2016-01-29 03:33
Cool bug. I assigned this one to @pbakaus because I think that is his CSS. Might be mistaken, though.

**Comment by adelinamart** [comment] 2017-02-03 19:47
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)

**Closed by adelinamart** 2017-02-03 19:47 UTC
Labels: Category: Audio&Video, Type: Bug
