### ISSUE TITLE
SVG image being mistakenly cached as resource

### ISSUE THREAD

**Issue by caiotomazelli** [ampproject/amphtml#18509] opened 2018-10-02 19:50 UTC
## What's the issue?

SVG image on an AMP page is being cached as a resource instead of image.

## How do we reproduce the issue?

1. Access https://m.posthaus.com.br/amp/ and verify that the logo (posthaus at the center top) is being normally loaded from https://m.posthaus.com.br/assets/icons/ic-posthaus-logo.svg
2. Access the cached AMP page on https://m-posthaus-com-br.cdn.ampproject.org/c/s/m.posthaus.com.br/amp/ and verify the logo is not being rendered. The URL of teh cached image https://m-posthaus-com-br.cdn.ampproject.org/i/s/m.posthaus.com.br/assets/icons/ic-posthaus-logo.svg is responding with 404
3. Verify that the image has been correctly cached as resource in the /r/ path: https://m-posthaus-com-br.cdn.ampproject.org/r/s/m.posthaus.com.br/assets/icons/ic-posthaus-logo.svg

## What browsers are affected?

All

## Which AMP version is affected?
Version 1809142227020

**Comment by Gregable** [comment] 2018-10-11 21:58
Note that caching for images and resources happens on request, not when parsing including documents, so your third point is a red herring.

The real question is why `m-posthaus-com-br.cdn.ampproject.org/i/s/m.posthaus.com.br/assets/icons/ic-posthaus-logo.svg` is 404'ing.

That said, I cannot reproduce. Loading https://m-posthaus-com-br.cdn.ampproject.org/i/s/m.posthaus.com.br/assets/icons/ic-posthaus-logo.svg` returns an SVG for me.

Closing for now, please let me know if you have any further updates and I'm happy to reopen.

**Closed by Gregable** 2018-10-11 21:58 UTC
Labels: Category: AMP Caches, Type: Bug
