### ISSUE TITLE
Iframe refreshes automatically when tab change.

### ISSUE THREAD

**Issue by bluej4ker** [ampproject/amphtml#32487] opened 2021-02-07 21:15 UTC
There has been a change in amp iframe after the last update. Iframe is automatically refreshed when you switch to a different tab on the site with iframe. Do you have a solution to prevent this?

**Comment by kristoferbaxter** [comment] 2021-02-08 15:11
@samouri is this related to https://github.com/ampproject/amphtml/issues/32463?

**Comment by samouri** [comment] 2021-02-08 16:19
@bluej4ker: can you please provide an example reproduction (and especially one where it is undesired). I believe this is the intended behavior for iframes to unload when inactive and then reload when active again

**Comment by bluej4ker** [comment] 2021-02-08 19:07
![wetwetew (1)](https://user-images.githubusercontent.com/33478397/107268794-b9657600-6a59-11eb-944c-cb90406c9609.gif)

Imagine watching a video in a tab. You may experience this problem when we move to a different page. Or imagine that you are opening a pop-up page in iframe, the same problem occurs again.

You may think that we should use different tags for the video, but if we are using our own player system, we have no choice but to use the amp-iframe tag.

**Comment by dvoytenko** [comment] 2021-02-08 20:21
This is being fixed in https://github.com/ampproject/amphtml/pull/32478

**Comment by jridgewell** [comment] 2021-02-08 20:30
Ok, so the from is the same [PR](https://github.com/ampproject/amphtml/pull/31976) that caused #32463. However, #32436 was caused by the interaction with the Owners system leading to an incorrect state.

This seems to be caused because we're interpreting the tab switch (iframes shouldn't unload) the same as a Viewer swipe-to-next-doc (iframes should unload). We'll need to fix this.

**Closed** 2021-02-08 21:06 UTC
Labels: P1: High Priority, Type: Bug, WG: performance
