### ISSUE TITLE
Unable to load custom fonts from google -> site, but able to when you visit site directly

### ISSUE THREAD

**Issue by TheodorGosden** [ampproject/amphtml#12197] opened 2017-11-23 15:41 UTC
Hi AMP,

I'm getting net::ERR_ABORTED for all my fonts when loading my site via https://www.google.dk/amp/www.swipty.dk/ (shown in the picture below), but if I load my site https://www.swipty.dk it loads the fonts fine. I don't think I've done anything wrong in my code, but please enlighten me if that's not the case. I hope you have a solution as my designer thinks it's very important.

`@font-face{
    font-family: 'Raleway';
    font-style: bold;
    font-weight: 700;
    src: url('fonts/Raleway-Bold.ttf') format('truetype');
}

@font-face{
    font-family: 'Raleway';
    font-style: medium;
    font-weight: 500;
    src: url('fonts/Raleway-Medium.ttf') format('truetype');
}

@font-face{
    font-family: 'Raleway';
    font-style: normal;
    font-weight: 400;
    src: url('fonts/Raleway-Regular.ttf') format('truetype');
}

@font-face{
    font-family: 'Raleway';
    font-style: lighter;
    font-weight: 300;
    src: url('fonts/Raleway-Thin.ttf') format('truetype');
}`

![screen shot 2017-11-23 at 16 33 55](https://user-images.githubusercontent.com/19152803/33180274-6d81540a-d06c-11e7-9738-91066d34d7de.png)

![screen shot 2017-11-23 at 16 40 56](https://user-images.githubusercontent.com/19152803/33180483-26044a3c-d06d-11e7-8ecc-14c5187bbc27.png)

**Comment by aghassemi** [comment] 2017-11-27 18:04
@TheodorGosden Looks like AMP cache issue with fonts, we are investigating. I will let you know as soon as I know more.

**Comment by aghassemi** [comment] 2017-11-27 18:04
b/69793233

**Comment by TheodorGosden** [comment] 2017-11-27 22:25
Cool! If it helps, it loaded the fonts on a android one plus 3t in the chrome browser, but didn't on an iPhone of 6 or higher. Tried both chrome and safari.

**Comment by MohammedKaludi** [comment] 2018-03-01 11:37
We are also facing the same issue. Fonts not loading via Google CDN

https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1735

Any update on this issue?
Mohammed Kaludi

**Comment by aghassemi** [comment] 2018-03-02 02:50
@MohammedKaludi I am pinging the folks working on AMP Cache infra, thanks for your patience.

**Comment by aghassemi** [comment] 2018-03-02 03:08
@MohammedKaludi The issue is the `ttf` font on your site is being served with `x-font/ttf` `content-type` which is not whitelisted in our end given it is not standard (but we will add it to the list soon). 

As a workaround please change the `content-type` to `application/octet-stream` and use the [AMP Cache](https://developers.google.com/amp/cache/update-cache) API to refresh the cache for your page

**Comment by aghassemi** [comment] 2018-03-02 03:12
Closing the issue since workaround is documented above and a fix has been done on our end for future cases where non-standard `x-font` content type is used. Fix will take a few weeks to make it to production however.

**Closed by aghassemi** 2018-03-02 03:12 UTC
Labels: Category: AMP Caches, Internally Tracked

**Comment by ahmedkaludi** [comment] 2018-07-19 07:00
@aghassemi Any tips on how to change the content-type of the font?

**Comment by LeandroTk** [comment] 2018-10-16 19:58
Hey @aghassemi, I'm also facing this problem. How and where do I change the `content-type` to `application/octet-stream`?

**Comment by aghassemi** [comment] 2018-10-16 20:37
@LeandroTk would be a serving configuration on the server you are using to serve fonts, how to change this would really depends on the server stack you are using.
