### ISSUE TITLE
amp-live-list examples are not working

### ISSUE THREAD

**Issue by molnarg** [ampproject/amphtml#8150] opened 2017-03-15 10:42 UTC
## Short description of your issue:

The examples linked from https://github.com/ampproject/amphtml/blob/master/extensions/amp-live-list/amp-live-list.md are not working.

## How do we reproduce the issue?

Visit any of the following two demos:
- https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2Fcomponents%2Famp-live-list%2Fsource%2F
- https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2Fsamples_templates%2Flive_blog%2Fsource%2F

Wait some time, then observer the browser console. The update endpoints return a 404 error.

## What browsers are affected?

All browsers

## Which AMP version is affected?

AFAIK, the examples are not versioned.

**Comment by erwinmombay** [comment] 2017-03-15 15:55
@kul3r4 @sebastianbenz did anything change recently? I'll investigate if needed

**Comment by sebastianbenz** [comment] 2017-03-15 16:15
The actual samples work: https://ampbyexample.com/components/amp-live-list/

However, they don't work in the playground - problem is that the embedded playground document has a different URL than the actual one. I've created: https://github.com/ampproject/amp-by-example/issues/699 to track this for ampbyexample.

**Comment by erwinmombay** [comment] 2017-03-15 16:20
ah that makes sense. i believe we have had requests to be able to declare specific url endpoints. I'll have to do some research on feasibility on this when i get a chance.

cc @ericlindley-g

**Comment by sebastianbenz** [comment] 2017-03-15 16:22
That would totally fix our problem. :-)

**Comment by erwinmombay** [comment] 2017-03-15 16:25
its going to be very unlikely currently with the way amp-live-list is designed, since we wouldn't have the invariant of that url endpoint returning a valid AMP document. but I'll start making discussions on these requests

**Comment by ericlindley-g** [comment] 2017-05-25 15:37
Closing as a duplicate of ABE issue https://github.com/ampproject/amp-by-example/issues/699 and potential solution: https://github.com/ampproject/amphtml/issues/7848

**Closed by ericlindley-g** 2017-05-25 15:37 UTC
Labels: Category: Presentation, Type: Bug
