### ISSUE TITLE
amp-ad, amp-iframe element error on data-block-on-consent attribute 

### ISSUE THREAD

**Issue by gopiborra** [ampproject/amphtml#15274] opened 2018-05-14 19:29 UTC
## What's the issue?

We've implemented AMP Geo and Consent components to suppress Medianet RTC calls for EEA users as suggested in https://support.google.com/dfp_premium/answer/7678538 and noticed the following issues. Might be related to https://github.com/ampproject/amphtml/issues/15211 & https://github.com/ampproject/amphtml/issues/15269

Issue 1. error on console - 
```code
can not find policy, do not set value to data-block-on-consent log.js:162 
```

Issue 2. RTC Medianet calls are blocked for US Geo as well.

Below is the configuration:

```code
<amp-ad
    data-npa-on-unknown-consent="true"
    data-block-on-consent
    type="doubleclick"
    width=300
    layout="fluid"
    height="fluid"
    data-multi-size="300x250"
    rtc-config="{
    "vendors": {
    "medianet":{"CID":"xxxxx"}}}"
    data-slot={/000000/nyt/000000}
/>
```

```code
    <amp-iframe
      data-block-on-consent
      src="https://contextual.media.net/checksync.php?cid=xxxxx&cs=7"
      sandbox="allow-scripts allow-same-origin"
      width="1"
      height="1"
    >
      <div placeholder="" />
    </amp-iframe>
```

```code
<amp-geo layout="nodisplay"><script type="application/json">
{
	"ISOCountryGroups": {
		"eea": [
			"at",
			"be",
			"bg",
			"cy",
			"cz",
			"de",
			"dk",
			"ee",
			"es",
			"fi",
			"fr",
			"gb",
			"gr",
			"hr",
			"hu",
			"ie",
			"is",
			"it",
			"li",
			"lt",
			"lu",
			"lv",
			"mt",
			"nl",
			"no",
			"pl",
			"pt",
			"ro",
			"se",
			"si",
			"sk"
		]
	}
}
</script>
</amp-geo>
```

```code
<amp-consent id="gdprConsent" layout="nodisplay">
<script type="application/json">
{
	"consents": {
		"gdpr_consent": {
			"promptIfUnknownForGeoGroup": "eea"
		}
	},
	"policy": {
		"default": {
			"waitFor": {
				"gdpr_consent": []
			},
			"timeout": {
				"seconds": 0,
				"fallbackAction": "reject"
			}
		}
	}
}
</script>
</amp-consent>
```

## How do we reproduce the issue?

Will update steps to reproduce shortly. 

## What browsers are affected?
Reproducible on Safari, Chrome.

## Which AMP version is affected?
1525461683159

**Comment by Aerlinger** [comment] 2018-05-15 00:57
Hey Gopi, thanks for the info. I set up a local test using the code you provided issue and am unable to reproduce the error message you're seeing. That said, I don't have access to a medianet account so am unable to reproduce it fully. Is it possible for you to provide a simple test page that reproduces this issue? 

Also, it looks like you have some imbalanced quotes/parens on the `rtc-config` attribute. This probably isn't the source of the console error you're seeing, but wanted to rule it out.

**Comment by gopiborra** [comment] 2018-05-15 17:27
@Aerlinger , Adding `default` value as to `data-block-on-consent` resolved the console error.

Thanks

**Comment by aghassemi** [comment] 2018-05-15 20:16
Great! Closing the issue as resolved per above.

**Comment by zhouyx** [comment] 2018-05-21 17:21
You don't need to put `default` to `data-block-on-consent`. Though in theory you can do that. 

@gopiborra I tried to reproduce with the example you provided, and couldn't get the error "can not find policy, do not set value to data-block-on-consent log.js:162 ". Could you provide more information to help us figure out the issue here? Thank you.

**Comment by zaletskyi** [comment] 2018-06-20 15:45
Hey there, 

How can I test if serving non-personalized ads to all EEA users works? 
Does it save something in local storage?

  ```
<amp-geo layout="nodisplay">
    <script type="application/json">
      {
        "ISOCountryGroups": {
          "eea": ["at", "be", "bg", "cy", "cz", "de", "dk", "ee", "es", "fi", "fr", "gb", "gr", "hr", "hu", "ie", "is", "it", "li", "lt", "lu", "lv", "mt", "nl", "no", "pl", "pt", "ro", "se", "si", "sk"],
          "world": ["unknown"]
        }
      }
    </script>
  </amp-geo>

<amp-consent id="myUserConsent" layout="nodisplay">
  <script type="application/json">
     {
      "consents": {
        "eu-consent": {
          "promptIfUnknownForGeoGroup": "eea"
        }
      },

     "policy": {
      "default": {
        "waitFor": {
          "eu-consent": []
        },

        "timeout": {
          "seconds": 0,
          "fallbackAction": "reject"
        }
      }
     }
   }
  </script>
</amp-consent>

 <amp-sticky-ad layout="nodisplay">
        <amp-ad data-block-on-consent width=320 height=50 type="adsense" data-ad-client="ca-pub-xxxxx" data-ad-slot=""></amp-ad>
</amp-sticky-ad>
```
Thanks.

**Comment by gopiborra** [comment] 2018-06-20 16:11
@zaletskyi , With the `<amp-consent>` configuration listed above, ad calls will pass `npa=1` parameter.  When `data-npa-on-unknown-consent="true"` attribute is added to `<amp-ad>` component, non-personalized ads are requested. 

More details here - https://support.google.com/dfp_premium/answer/7678538

**Comment by gopiborra** [comment] 2018-06-20 16:31
@zhouyx, Sorry, I missed your comment above earlier. 

We have Medianet header bidder ads implemented on our AMP articles. When `data-block-on-consent` attribute is added to `amp-ad` without `default` value, we are getting the error `"can not find policy, do not set value to data-block-on-consent log.js:162 "`

Below is the AMP consent implementation.

https://www.google.com/amp/s/mobile.nytimes.com/2018/06/19/us/politics/trump-immigration-children-separated-families.amp.html

```
<amp-geo layout="nodisplay">
  <script type="application/json">{"ISOCountryGroups":{"eea":["at","be","bg","cy","cz","de","dk","ee","es","fi","fr","gb","gr","hr","hu","ie","is","it","li","lt","lu","lv","mt","nl","no","pl","pt","ro","se","si","sk"]}}</script>
</amp-geo>

<amp-consent id="gdprConsent" layout="nodisplay">
  <script type="application/json">{"consents":{"gdpr_consent":{"promptIfUnknownForGeoGroup":"eea","promptUI":"consentDialog"}},"policy":{"default":{"waitFor":{"gdpr_consent":[]},"timeout":{"seconds":0,"fallbackAction":"reject"}}}}</script>
</amp-consent>

<amp-iframe data-block-on-consent="default" src="https://contextual.media.net/checksync.php?cid=8CU97SC10&amp;cs=7" sandbox="allow-scripts allow-same-origin" width="1" height="1">

<amp-ad
  data-npa-on-unknown-consent="true"
  data-block-on-consent="default"
  type="doubleclick"
  width="300"
  layout="fluid"
  height="fluid"
  data-multi-size="300x250"
  rtc-config="{
  &quot;vendors&quot;: {
  &quot;medianet&quot;:{&quot;CID&quot;:&quot;8CU97SC10&quot;}}}"
  data-slot="/29390238/nyt/us/politics"
/>
```

**Comment by zaletskyi** [comment] 2018-06-20 17:57
Thanks @gopiborra, Does `data-npa-on-unknown-consent="true"` gonna work just for EEA users in my case?

**Comment by zhouyx** [comment] 2018-06-21 21:23
@gopiborra I tried with the config you provided and have the "default" removed, but couldn't get the error message. 
Did you use `data-block-on-consent=` instead of `data-block-on-consent`. With our implementation `data-block-on-consent='default'`  equals to `data-block-on-consent`, but not `data-block-on-consent=`.

**Comment by zhouyx** [comment] 2018-07-03 20:37
Close the issue for now, since there's no action item here. @gopiborra Feel free to reopen if `data-block-on-consent` still doesn't work for you.

**Closed by zhouyx** 2018-07-03 20:37 UTC
Labels: Category: Ads, Category: Analytics, P2: Soon, Type: Bug
