### ISSUE TITLE
Error: failed to fetch %s [object URL]: HTTP error 404

### ISSUE THREAD

**Issue by estherkim** [ampproject/amphtml#22282] opened 2019-05-14 16:01 UTC
Release error for 1% RC version 031905091827220 seen at [go/ampe/CPnw6Y7bqNzSCQ](go/ampe/CPnw6Y7bqNzSCQ)

```
Error: failed to fetch %s [object URL]: HTTP error 404
at Error (https://raw.githubusercontent.com/ampproject/amphtml/1905091827220/src/log.js:540)
at apply (https://raw.githubusercontent.com/ampproject/amphtml/1905091827220/src/log.js:286)
at createError (https://raw.githubusercontent.com/ampproject/amphtml/1905091827220/src/utils/xhr-utils.js:404)
at call (https://raw.githubusercontent.com/ampproject/amphtml/1905091827220/node_modules/promise-pjs/promise.js:502)
at doResolve (https://raw.githubusercontent.com/ampproject/amphtml/1905091827220/node_modules/promise-pjs/promise.js:35)
at (https://raw.githubusercontent.com/ampproject/amphtml/1905091827220/src/utils/xhr-utils.js:398)
at assertSuccess (https://raw.githubusercontent.com/ampproject/amphtml/1905091827220/src/utils/xhr-utils.js:397)
at (https://raw.githubusercontent.com/ampproject/amphtml/1905091827220/node_modules/promise-pjs/promise.js:422)
at (https://raw.githubusercontent.com/ampproject/amphtml/1905091827220/node_modules/promise-pjs/promise.js:456)
```

Possible duplicate of #20638 and #20937

**Comment by choumx** [comment] 2019-05-14 19:06
Closing as dupe of #20638.

**Closed by choumx** 2019-05-14 19:06 UTC
Labels: Type: Bug
