### ISSUE TITLE
amp-ad: Not working on IE 11 on Windows 7

### ISSUE THREAD

**Issue by eike-hass** [ampproject/amphtml#8694] opened 2017-04-11 12:46 UTC
The amp-ad component seems to be having trouble on IE 11 on older Windows Machines.

1. Open https://ampbyexample.com/components/amp-ad/ with IE 11 on Windows 7
2. Find the Ad-Slot empty

## What browsers are affected?

IE 11.0.9600.18617 on Windows 7 Service Pack 1. IE 11 on Windows 10 works fine.

## Which AMP version is affected?

1491864594241, not sure if this is a new issue.

**Comment by zhouyx** [comment] 2017-04-11 20:49
Hmmmm Window 7. I wonder how can I reproduce it 😕 
@aghassemi you mentioned I can use saucelab? Do you have more info on that? 😄

**Comment by aghassemi** [comment] 2017-04-11 21:14
@zhouyx yea, "Manual Test" on SauceLabs ( https://saucelabs.com/beta/manual ) lets you create a Windows 7 VM with IE 11. (limited to 10 minute sessions though)

**Comment by aghassemi** [comment] 2017-04-26 16:20
@zhouyx could we do a quick triage for this and see if 1- It is reproducible and 2- what the severity is (e.g. reproducible for all ads or just a few).

**Comment by zhouyx** [comment] 2017-04-26 17:22
Hi @eike-hass Thanks for filing the issue! However I am not able to reproduce it. Could you confirm if this is fixed? Or you have more information on how to repro the bug?
I just tested on SauceLabs with Windows 7 and IE 11, and the ad loads for me. Please see the screenshot. 
![image](https://cloud.githubusercontent.com/assets/5419904/25447421/fe1958f4-2a69-11e7-99f1-9cb4d78f75a0.png)

**Comment by eike-hass** [comment] 2017-04-27 09:36
We saw some script errors in a VM
<img width="1158" alt="bildschirmfoto_2017-04-27_um_11 16 18" src="https://cloud.githubusercontent.com/assets/3441319/25477426/c144dab4-2b3d-11e7-8d1c-3983ef7df436.png">

**Comment by jasti** [comment] 2017-05-03 22:06
Closing for now since this has been open for a week. Please feel free to reopen if you have more details.

**Closed by jasti** 2017-05-03 22:06 UTC
Labels: Category: Ads, P2: Soon, Type: Bug
