### ISSUE TITLE
Object.values is not a function

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#10835] opened 2017-08-08 18:05 UTC
> Object.values is not a function. (In 'Object.values(sd)', 'Object.values' is undefined)

Seeing a lot of this in the current 1% canary.

Might be from this PR #10708

**Comment by jridgewell** [comment] 2017-08-08 18:09
Dupe of https://github.com/ampproject/amphtml/issues/10788.

**Closed by jridgewell** 2017-08-08 18:09 UTC
Labels: P0: Drop Everything, Type: Bug
