### ISSUE TITLE
Disappearing body content when linked from Google

### ISSUE THREAD

**Issue by dmarge123** [ampproject/amphtml#8069] opened 2017-03-11 01:13 UTC
We have had to disable our AMP pages as when they are linked to from Google search results no article content displays. 

The pages work perfectly when you go to the URL directly, they give no errors when you run them through google's AMP Test, but when you preview via search result in google search console the article content does not display (same as when in production). 

We use the AMP plugin for WP from Automattic, we have checked for issues with other plugins potentially affecting the content, disabled our DFP served ads in case they were causing the issue, but haven't found anything. 

I have attached a screen grab of how the articles look when linked via google search results, showing where the missing content should be. 

You can see our AMP pages on our staging environment here for e.g. (working fine) 
http://stage.dmarge.com/2016/05/how-to-dress-cocktail-men.html/amp or http://stage.dmarge.com/2016/01/short-mens-hairstyles-haircut-idea-gallery.html/amp

Then add the Google url string and view from mobile device and content goes walkabout.

https://www.dmarge.com/2017/03/coffee-shops-design-inspiration.html/amp

https://www.google.com.au/url?q=https://www.dmarge.com/2017/03/coffee-shops-design-inspiration.html/amp

Has anyone come across this issue or have any suggestions for what we can try to resolve the issue? 

![contentnotdisplayingamp1](https://cloud.githubusercontent.com/assets/26337542/23818899/f769a746-0653-11e7-8d02-9da0723c3ea8.jpg)
![contentnotdisplayingamp2](https://cloud.githubusercontent.com/assets/26337542/23818900/f76d3a6e-0653-11e7-907e-fa85a53a38ea.jpg)

**Comment by aghassemi** [comment] 2017-03-14 22:53
@dmarge123 Could you please provide a few more links to reproduce this? I have not been able to see the problem with the coffe-fshop-redesign article.
https://cdn.ampproject.org/c/s/www.dmarge.com/2017/03/coffee-shops-design-inspiration.html/amp 
https://www.dmarge.com/2017/03/coffee-shops-design-inspiration.html/amp both looks the same.

**Comment by aghassemi** [comment] 2017-03-14 22:54
I also recommend posting this on Automattic's repo as well in case they are aware of the cause and possible solutions.

**Comment by aghassemi** [comment] 2017-04-13 16:40
Closing per previous comments, please feel free to reopen if still having issues.

**Closed by aghassemi** 2017-04-13 16:40 UTC
Labels: Type: Discussion/Question
