### ISSUE TITLE
AMP Google Analytics and AMP Ids do not match

### ISSUE THREAD

**Issue by demianrenzulli** [ampproject/amphtml#34300] opened 2021-05-10 20:09 UTC
## What's the issue?

Forbes reported that sometimes GA client_Id expands to a different value when it gets sent to GA vs DFP.
This is related to FR #25190, which landed in prod earlier this year. 

## How do we reproduce the issue?

@kbarneyforbes could you provide some details around it?

cc // @micajuine-ho

**Comment by micajuine-ho** [comment] 2021-05-10 20:30
A URL exhibiting this behavior would be very helpful.

**Comment by kbarneyforbes** [comment] 2021-05-10 21:31
We are sending client_id both to Google Analytics and DFP. The same ID should be sent to both, but it appears that frequently the IDs don't match. Unfortunately, we can't reproduce this consistently.

For GA, the value is sent as CD43. For DFP it's the fvid key/value in the scp parameter.

We noticed that we are using "CLIENT_ID(_ga)" for DFP and "${clientId}" for GA. We tried changing GA to use "CLIENT_ID(_ga)" too, and both to use "CLIENT_ID(AMP_ECID_GOOGLE)", but were still able to reproduce the issue in our testing environment even after that change.

Below are some screenshots showing the values being sent.

This is the internal testing page where those screenshots came from (where we've been able to consistently reproduce the issue).
https://dev90.simple-site.forbes.com/sites/nathanvardi/2021/03/12/pfizer-ceo-albert-bourla-helped-save-the-world-can-he-save-his-companys-stock/amp/

Prod version of the same page.
https://www.forbes.com/sites/nathanvardi/2021/03/12/pfizer-ceo-albert-bourla-helped-save-the-world-can-he-save-his-companys-stock/amp/

![dev-ga](https://user-images.githubusercontent.com/57414484/117726722-fce49300-b1b4-11eb-9d86-e444f8065c4b.png)
![dev-pubads](https://user-images.githubusercontent.com/57414484/117726723-fce49300-b1b4-11eb-8ddd-b4fbcd284444.png)

**Comment by AndrewKGuan** [comment] 2021-05-11 17:07
Hi Ken,
is the prod version (link in #3) exactly the same as the internal test one?  If so, perhaps Micajuine could try with that one?

**Comment by micajuine-ho** [comment] 2021-05-11 17:44
Yeah, I'm not able to repro with the prod link. Does the page have to be served from the cache for it to occur?

**Comment by micajuine-ho** [comment] 2021-05-12 14:28
I think it's interesting that `fvid=1831....`. If I'm not mistaken, this indicates that its a non-amp generated CID. I'm thinking perhaps Linker/Cookiewriter might be used to propagate an amp-generated CID (maybe from cached page to origin page), but the Cookie already exists on origin, and amp-ad uses it before Linker/Cookiewriter has a chance to update? this could explain why the googleanalytics CID is `amp-...`

**Comment by kbarneyforbes** [comment] 2021-05-12 21:03
The dev90 link is internal only. I figured out a way to reproduce the issue consistently on prod.

1. Open a private window
2. Search on desktop Google for "pfizer ceo albert bourla helped save the world can he save his companys stock"
3. Click on the article
4. Go back to the search results
5. Open up devtools and emulate mobile.
6. Refresh.
7. Click on the amp link to the same article

The IDs I get doing that consistently look like something like this, with only GA/cd43 starting with "amp-".
fvid=0Hypp00QDXip0gfS9355DTI32E_H1m09T3TsaUiZTT0Shjw3hpxxzM2Vxrmeung8
cd43: amp-IYH5u8YoLq-KtotIOPWgCFpwE5lqWKL4oF_TH5CXGWwuld0wO2eaqbNoMHUGpNfp

**Comment by micajuine-ho** [comment] 2021-05-13 15:42
> We noticed that we are using "CLIENT_ID(_ga)" for DFP and "${clientId}" for GA. We tried changing GA to use "CLIENT_ID(_ga)" too, and both to use "CLIENT_ID(AMP_ECID_GOOGLE)", but were still able to reproduce the issue in our testing environment even after that change.

Tracing your code in the prod environment, I'm seeing that both `amp-ad` and `amp-analytics` are using the CLIENT_ID macro and utilizing the GOOGLE_CID_API, with the same scope and apikey. 

Unless the Viewer's GOOGLE_CID_API is returning different things based on identical calls (I don't think that's the case), then something is happening with DFP value.

@calebcordry  After the json targeting is expanded and rewritten:
https://github.com/ampproject/amphtml/blob/8f3d69094bea028caef8f47fb69a42489256c5d0/extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js#L820-L824

is there any reason you can think of why the `fvid=CLIENT_ID(_ga)` could get changed after the promise resolves:
https://github.com/ampproject/amphtml/blob/8f3d69094bea028caef8f47fb69a42489256c5d0/extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js#L826-L831

**Comment by micajuine-ho** [comment] 2021-05-13 20:27
I did some more digging, it looks like `amp-analytics` is using a config from GTM via `config="https://www.googletagmanager.com/amp.json?id=GTM-MNSBDX&amp;gtm.url=SOURCE_URL"`. This config contains `CLIENT_ID(AMP_ECID_GOOGLE,,_ga,true)`

Then within your `amp-ad type="doubleclick"` in the JSON attribute (for RTC callouts) you have "fvid":"CLIENT_ID(_ga)". 

I feel like this maybe the issue? 

@jeffkaufman @calebcordry For pubs with the setup (amp-analytics using a GTM config and doubleclick ads), is there guidance for what scope the CLIENT_ID within the RTC callout should be? Should they both be `AMP_ECID_GOOGLE`?

**Comment by micajuine-ho** [comment] 2021-06-29 19:39
Closing now.

**Closed by micajuine-ho** 2021-06-29 19:39 UTC
Labels: Type: Bug

**Comment by kbarneyforbes** [comment] 2021-07-15 15:16
Did anything happen with this issue? We were still hoping the mismatched IDs could be fixed.
