### ISSUE TITLE
<amp-next-page> does not load amp-img and also it brakes amp-ad when it is loaded from google AMP viewer

### ISSUE THREAD

**Issue by carlosestevezmrf** [ampproject/amphtml#31841] opened 2021-01-07 16:23 UTC
## What's the issue?

I can only reproduce this in AMP documents loaded inside the Google Search results AMP viewer.

This can be reproduced If an amp page has `<amp-next-page>` tag that loads a page with `amp-img` and `amp-ad` tags.

The expected behavior is to load the amp-img a do not move the amp-ads.

I have found that there is an issue related to amp-next-page and amp-viewer-integration library 
![image](https://user-images.githubusercontent.com/57218466/103915917-d2d17600-50d9-11eb-89ea-d792a7565491.png)

## How do we reproduce the issue?

1. Open [this](https://www.google.com/search?q=visao+oeste&prmd=nsvi&source=lnms&tbm=nws&sa=X&ved=2ahUKEwjLqKjvmoruAhXBneAKHYQDA1UQ_AUoAXoECAMQAQ&biw=360&bih=640) URL with a mobile device.
2. Open any article.
3. Scroll down to the amp-next-page element.

This a video of the issue https://gyazo.com/ed4a3aa12520e0c4cd43b95b03b7de46
![image](https://user-images.githubusercontent.com/57218466/103916372-5ab78000-50da-11eb-9352-1ea0da9f18b9.png)

The same document loaded from the original URL works correctly.
https://www.visaooeste.com.br/onde-esta-mc-ryan-jovem-de-itapevi-diz-que-vai-gravar-musica-e-desaparece/amp/

**Comment by a-haan** [comment] 2021-01-08 20:33
I'm having similar issues with my amp-first website, amp-next-page has issues with layout dimensions for images and adverts, most images are showing on amp-next-pages but the dimensions are not correct - the issue only presents in the amp-viewer on mobile and desktop.

Looking at the console I can see the same errors
![image](https://user-images.githubusercontent.com/8811771/104061182-00a8de80-51f0-11eb-9528-42e04497e427.png)

Not having the issue going directly to an article:
https://ahaan.co.uk/article/top_stories/3070-3080-3090-hdmi-2-1-gpu-into-the-living-room

The issue is not presented when viewing an article from the amp CDN:
https://ahaan-co-uk.cdn.ampproject.org/c/s/ahaan.co.uk/article/top_stories/3070-3080-3090-hdmi-2-1-gpu-into-the-living-room

The issue can be replicated on desktop using the structured data preview tool:
https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fahaan.co.uk%2Farticle%2Ftop_stories%2F3070-3080-3090-hdmi-2-1-gpu-into-the-living-room

**Comment by lucamago** [comment] 2021-01-08 23:17
Hi i've got the same problems with many of my sites where i've implemented amp-next-page. Is there a solution to this?

**Comment by davideperfetto** [comment] 2021-01-11 09:23
Hi, same problem here!

**Comment by FrankBeescell** [comment] 2021-01-11 12:07
Same problem for me

**Comment by Cauchon** [comment] 2021-01-11 19:06
We are seeing this as well. Might be the same/related to 30641

**Comment by a-haan** [comment] 2021-01-11 22:05
> We are seeing this as well. Might be the same/related to [30641](https://github.com/ampproject/amphtml/issues/30641)

Yes looks like the same issue!

**Comment by lucamago** [comment] 2021-01-13 10:58
Still no solutions?

**Comment by dmanek** [comment] 2021-01-13 21:13
I'm working with the AMP viewer team to resolve this issue. We're not able to repro it, so it's making it rather challenging.

**Comment by kristoferbaxter** [comment] 2021-01-14 15:19
Closing issue in favor of #31951.

The Google team has temporarily rolled back a release of module scripts from the Google AMP Cache, we'll use #31951 to track fixing the underlying issue.

**Closed by kristoferbaxter** 2021-01-14 15:19 UTC
Labels: Component: amp-next-page, Type: Bug, WG: components
