### ISSUE TITLE
layout="responsive" does not constrain amp-img width correctly when parent height is constrained by max-height

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#2131] opened 2016-02-19 04:32 UTC
Width continues to grow even though height has been limited.

See example http://jsbin.com/zucimuxogu/edit?html,output - vary the browser width to see the effect - the image should be square.

**Comment by luixxiul** [comment] 2016-03-09 02:57
@dvoytenko, it seems to be fixed, doesn't it?

**Comment by dvoytenko** [comment] 2016-03-09 18:22
Not fixed exactly. The `layout=responsive` is defined explicitly as the layout that assigns height based on width. So it's a width-based layout. The reason for this is that this is the only option that can be accommodated via CSS - e.g. both vertical and horizontal `%` measurements are done based on the width, such as `padding-top`. Unfortunately, CSS does not allow to constraint width based on height. If you know of a way, I'd love to hear it.

**Comment by adelinamart** [comment] 2017-02-11 02:06
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)

**Closed by adelinamart** 2017-02-11 02:06 UTC
Labels: To be deprecated - Related to: Content, Type: Bug
