### ISSUE TITLE
AMP-Carousel - Fast swiping cause image to jump/skip on mobile

### ISSUE THREAD

**Issue by merakmarey** [ampproject/amphtml#26249] opened 2020-01-08 04:24 UTC
Open full screen mode, swipe "aggresively" and image will skip.

Chrome mobile/Samsung Mobile

try https://us.trapichero.com/a/miami/florida/housing/houses-for-sale/2034-sw-22-terr-miami-fl-33145-silver-bluff/1578449427-63.html

**Comment by caroqliu** [comment] 2020-01-10 16:01
Hi @merakmarey, thanks for filing the issue! I tried this out on the Chrome mobile app on iPhone X iOS 13.3 and Pixel 3 XL on Android 10 and was not able to reproduce. Can you provide a video of the unexpected behavior you are experiencing?

**Comment by merakmarey** [comment] 2020-01-12 01:04
Video shows that when you swipe faster from right to left the image will skip

Samsung Internet 10.2.00.53 & Chrome 79.0.3945.116

Samsung Galaxy A50, Android 9

[WhatsApp Video 2020-01-11 at 7.42.00 PM.zip](https://github.com/ampproject/amphtml/files/4050101/WhatsApp.Video.2020-01-11.at.7.42.00.PM.zip)

**Comment by merakmarey** [comment] 2020-01-25 04:39
Hi Caroline! No news for this?

**Comment by dvoytenko** [comment] 2020-04-01 00:06
Ping on this as well.

**Comment by alanorozco** [comment] 2020-04-01 18:29
Taking a look.

**Comment by monstermage** [comment] 2020-06-23 03:36
I can't believe this hasn't been addressed by now. I've had this problem with a website I made a long time ago. 

https://baynedg.com if you go to the portfolio page. https://baynedg.com/portfolio on my Pixel 2 it will start skipping images. Just go aggressive and try to view images through the carousel. Even without being aggressive, it will skip here and there. Just start clicking through multiple images. I only bring this topic back up because I'm back working on the site and noticed this is still an issue. I can't recall but I used to be able to crash the entire site by quickly launching the multi-view in the top left on desktop or mobile.

**Comment by merakmarey** [comment] 2020-06-23 04:27
@alanorozco was taking a look at it...maybe he got covid'ed? 😨 Maybe @caroqliu can give some light on it?

**Comment by lucasmodena** [comment] 2020-11-06 10:45
Waiting for this as well. Can't figure out what I'm doing wrong (using Galaxy Note9).
Open carousel, swipe from slide 1 to next. As soon as it finishes sliding to slide 2, it blinks and shows slide 3. Repeat process, as soon as it finishes sliding to 4, it blinks and shows 5, and so on... Interestingly, going backwards works fine.

Here's an example: https://youtu.be/lge7pQMCLmc

**Comment by monstermage** [comment] 2020-11-06 13:34
Yes indeed.

https://aironellc.com is a perfect example.

**Comment by micajuine-ho** [comment] 2021-02-23 19:04
hi @merakmarey can you please provide the code that you used in https://www.youtube.com/watch?v=lge7pQMCLmc&feature=youtu.be

in a jsbin?

This would greatly help our debugging efforts.

**Comment by merakmarey** [comment] 2021-02-23 19:50
Hi Micajuine

Video was not created by me but any carousel will do as good.

Code below was extracted from https://amp.dev/documentation/components/amp-carousel/

If you go to the last carousel and swipe "aggressively" from right to left you will see the issue.

Let me know if you need more.

Thanks

`<amp-carousel type="slides"
  width="450"
  height="300"
  controls
  loop
  autoplay
  delay="3000"  data-next-button-aria-label="Go to next slide"
  data-previous-button-aria-label="Go to previous slide"
  role="region"
  aria-label="Looping carousel">
  <amp-img src="/static/inline-examples/images/image1.jpg"
    width="450"
    height="300"></amp-img>
  <amp-img src="/static/inline-examples/images/image2.jpg"
    width="450"
    height="300"></amp-img>
  <amp-img src="/static/inline-examples/images/image3.jpg"
    width="450"
    height="300"></amp-img>
</amp-carousel>`

**Comment by merakmarey** [comment] 2021-02-23 20:15
Just in case you do need more

https://jsbin.com/simuxixowi

**Comment by micajuine-ho** [comment] 2021-02-24 15:09
This issue only seems to be present in amp-carousel 0.1 @merakmarey

**Comment by merakmarey** [comment] 2021-02-24 15:21
You are correct. Using 0.2 fixes the issue. Great catch! Good job!

**Comment by micajuine-ho** [comment] 2021-02-25 21:33
If 0.2 fixes the issue, I suggest you migrate to using it, since 0.1 support is limited--we are looking to deprecate it soon.

**Closed by micajuine-ho** 2021-02-25 21:33 UTC
Labels: Component: amp-carousel, Type: Bug, Type: UX, WG: components

**Comment by merakmarey** [comment] 2021-02-25 23:32
Awesome.. idea... why not have a latest version link for this and all components? ... like jQuery does?..that way devs don't have to go in and manually update deprecated versions...

**Comment by micajuine-ho** [comment] 2021-02-26 15:42
I'm not sure what `jQuery` does, but the latest support can always be seen on amp.dev: https://amp.dev/documentation/components/amp-carousel/

> that way devs don't have to go in and manually update deprecated versions...

Maybe this is something we can provide as part of the deprecation process of amp-carousel 0.1

**Comment by merakmarey** [comment] 2021-02-27 13:24
what I am saying is that instead of:

<script async custom-element="amp-carousel" src="https://cdn.ampproject.org/v0/amp-carousel-0.2.js"></script>

developers can do:

<script async custom-element="amp-carousel" src="https://cdn.ampproject.org/v0/amp-carousel-latest.js"></script>

where amp-carousel-latest.js will always be a copy of the latest version of the component...0.2..0.3..0.4 and on...

A simpler way to always point to the latest component versions...

**Comment by micajuine-ho** [comment] 2021-03-01 22:26
@alanorozco You mentioned that `*-latest.js` is buggy, could you elaborate on that?

**Comment by egphp** [comment] 2022-03-08 04:58
> You are correct. Using 0.2 fixes the issue. Great catch! Good job!

0.2 fix it , thanks
