### ISSUE TITLE
Ad viewability

### ISSUE THREAD

**Issue by RonanDrouglazet** [ampproject/amphtml#1113] opened 2015-12-09 17:26 UTC
Hi,

At this moment, the API `window.context.observeIntersection` fires callback only on scroll end (but really at the end !)
So we can't get changes with accurately. Actually, the viewability does not fires a lot.. sometime never fire (even if the scroll is ended)

e.g: 
- user never stops scrolling and pass through our ad, we never receive the notification from viewability

- user keeps his finger on screen (scroll not release)

Would it be possible to fire viewability callback more often ? Like onscroll event ? 

Thanks !

**Comment by cramforce** [comment] 2015-12-10 04:02
I'll take a look. We will definitely throttle it, but we do want to send event during scrolling.

**Comment by cramforce** [comment] 2015-12-15 00:09
Dupe of #873

**Closed by cramforce** 2015-12-15 00:09 UTC
Labels: Related to: Ads
