### ISSUE TITLE
<amp-embed> Cannot resize element and overflow is not available

### ISSUE THREAD

**Issue by anshuman91** [ampproject/amphtml#21095] opened 2019-02-26 16:44 UTC
### Description:
I am using `<amp-embed>` to display the ads on publisher's websites. And when I calls your ads resize api `window.context.requestResize` then it never works and throw the error **Cannot resize element and overflow is not available**. I have tried your `overflow` element but nothing seems working to solve this issue. 

When I change the window and paste the same API code in browser console then it get works. I means when i detatch the browser console window and switch the tab then call your resize API `window.context.requestResize(600, 900)` then it works. I also tried `window.context.requestResize(600, 900, true)` `hasOverflow: true` but in this case only warning stop comming but it still doesn't work. 

Ads resizing api is working in my local server (localhost) so by running gulp and calling requestResize always works in localhost. 

Our github code implementation is here https://github.com/ampproject/amphtml/blob/master/ads/jubna.md 

Here I am attatching the screenshots of errrors and warnings. 
<img width="417" alt="screenshot 2019-02-26 at 9 33 32 pm" src="https://user-images.githubusercontent.com/3455354/53429999-ac3d5100-3a13-11e9-9f0d-97d2c65d9098.png">
![screenshot 2019-02-26 at 10 10 55 pm](https://user-images.githubusercontent.com/3455354/53430000-acd5e780-3a13-11e9-9626-3f1a3e972897.png)
![screenshot 2019-02-26 at 9 33 46 pm](https://user-images.githubusercontent.com/3455354/53430002-acd5e780-3a13-11e9-8947-cedb1ececf77.png)

**Comment by anshuman91** [comment] 2019-02-27 12:11
Hello @dvoytenko @zhouyx @jridgewell ,

Please check the issue and let me know what's not working properly.

**Comment by jridgewell** [comment] 2019-02-27 16:52
The "has no overflow" means it has no overflow element: https://github.com/ampproject/amphtml/blob/master/ads/README.md#specifying-an-overflow-element

**Comment by anshuman91** [comment] 2019-02-27 17:01
Hello @jridgewell ,

I also tried to add `<div overflow>Click to resize</div>` inside `<amp-embed>`. And in your documentation link this element is for `<amp-ad>`. So will this also support for `<amp-embed>` ads?

**Comment by jridgewell** [comment] 2019-02-27 17:02
`<amp-ad>` and `<amp-embed>` are the same component underneath, we just expose two different element names. 😉

**Comment by anshuman91** [comment] 2019-02-27 17:04
> `<amp-ad>` and `<amp-embed>` are the same component underneath, we just expose two different element names. 😉

okay thanks a lot. I am trying it again.

**Comment by jjagutzke** [comment] 2019-03-04 09:05
Got that problem as well for amp-ad tag's. Is this a new behavior that we do need to have such overflow containers inside our amp-ad tag? Beforehand it was working without and we've covered this issue last friday.

**Comment by anshuman91** [comment] 2019-03-04 12:14
Hello @jjagutzke,

If you are using `window.context.requestResize` to resize the container element and it's throwing error like `Cannot resize element and overflow is not available`. Then you need to add overflow element `<div overflow>Click to resize</div>` inside `<amp-ad>`.  By adding this, users don't need to click on this to resize your ads and if you see after rendering your widget in browser then this element becomes invisible meas visibility will get hidden by css (amp styling). And by wrapping this overflow element inside your `<amp-ad>` tag, your resize api `window.context.requestResize` start working as expected. 

For detailed information please refeer this url https://github.com/ampproject/amphtml/blob/master/ads/README.md#specifying-an-overflow-element

**Comment by jjagutzke** [comment] 2019-03-04 12:36
Hello @anshuman91 
thank's a lot for your fast reply. Problem is that adding this element into my amp-ad tag leads into a visible "Click here". Clicking on it leads into resizing indeed, but there's no automatic resizing. After rendering our ad we're indeed firering `window.context.requestResize` which leeds into the mentioned error message. I'm a bit confused as this is totally new and adding my amp-ad into a demo page works as expected, the same code integration on the partnersite dosen't.

**Comment by anshuman91** [comment] 2019-03-04 13:58
You can remove the text `Click here` from overflow element and it will still work. So by this this extra div completely hide to your users. Also adding overflow element inside your `<amp-ad>` also fix your dynamic resizing issue. So after implementing overflow div your resize api `window.context.requestResize` start working normally.

**Comment by anshuman91** [comment] 2019-03-04 14:00
And yes, your current implemenntation still work fine in your local server `localhost` but if you don't add it then it will create issue in production.

**Comment by aghassemi** [comment] 2019-06-17 22:13
Closing this as "working as intended" `requestResize` is not guaranteed (per name) if runtime decides resize will cause content reflow, it will be denied and `overflow` element will be shown.

**Closed by aghassemi** 2019-06-17 22:13 UTC
Labels: Type: Bug
