### ISSUE TITLE
local state binding still changes `src` value.

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#12850] opened 2018-01-16 21:27 UTC
When `amp-list`'s local state binding is used (pattern similar to the [demo in AMP by Example](https://ampbyexample.com/samples_templates/product_page/preview/), we find that the `src` attribute in `amp-list`  gets dynamically changed to a meaningless URL like the following: 
https://ampbyexample.com/samples_templates/product_page/preview/[object%20Object],[object%20Object],[object%20Object],[object%20Object],[object%20Object],[object%20Object],[object%20Object],[object%20Object],[object%20Object]

For debugging and cosmetic purposes, we may want to skip updating the src in DOM when local binding is used.

/to @choumx

**Comment by choumx** [comment] 2018-01-16 23:44
Thanks for raising this. Actually a dupe of #11629 -- closing.

**Closed by choumx** 2018-01-16 23:44 UTC
Labels: Category: Framework, P3: When Possible
