### ISSUE TITLE
Outstanding lightbox problem - distort proportion

### ISSUE THREAD

**Issue by Siton-Systems** [ampproject/amphtml#5711] opened 2016-10-20 09:47 UTC
What about this issue?...(click --> zoom + distort proportion)
https://github.com/ampproject/amphtml/issues/5301

I understand their is a lot of issues but this is very **outstanding** bug especially on desktop / big screen.

Its problem to use the lightbox for real clients with this issue. I use modern browsers. For now i disable the lightbox option.

![image](https://cloud.githubusercontent.com/assets/16711871/19554507/9d37d920-96c1-11e6-998d-608d3ea58cf3.png)

**Comment by jridgewell** [comment] 2016-10-20 19:16
Dupe of #5301, as you noted. Please comment on there to ping.

**Closed by jridgewell** 2016-10-20 19:16 UTC
