### ISSUE TITLE
Ads not resizing for multiple sizes

### ISSUE THREAD

**Issue by emphaticsunshine** [ampproject/amphtml#5560] opened 2016-10-12 21:03 UTC
I am working on a prototype and it's still in development so can't post a public url. 
## Problem:

I am specifying `data-multi-size` for DoubleClick ads and have to give primary height to the biggest size. The ad slot doesn't resize once ad size is selected. So if a smaller size is selected so there is lot white empty space around.

Browsers Affected:
- Just looking at Chrome iPhone6 Emulator on Mac.

**Comment by jridgewell** [comment] 2016-10-12 21:22
/to @jasti. Please assign to whoever can look at it.

**Comment by jasti** [comment] 2016-10-12 21:28
@emphaticsunshine  That's the expected behavior if the ad is in the current viewport since AMP doesn't allow resizing iframes that cause a visual reflow of the page.
https://github.com/ampproject/amphtml/blob/master/examples/doubleclick-multisize.amp.html

@glevitzky could you please document this case here? https://github.com/ampproject/amphtml/blob/master/ads/google/doubleclick.md#multi-size-ad
Thanks.

**Comment by emphaticsunshine** [comment] 2016-10-20 16:37
@jasti , that makes a lot more sense. But I have been recently observing that the ads below the fold are not resizing sometimes if ad is not loaded before I scroll to it. Is that an expected behavior too?

**Comment by lannka** [comment] 2016-10-20 16:40
@emphaticsunshine ads starts load when it's within 3 viewports away. Your case can happen if the ad sits at the bottom, and you scroll very fast to it.

**Comment by jasti** [comment] 2016-10-20 16:43
@emphaticsunshine would be great to have a sample page!

**Comment by emphaticsunshine** [comment] 2016-10-20 17:44
@jasti , I will try to get something for you as the stuff I am working is in development phase so it's not public yet. 

@lannka thanks for clarifying it

Can you guys explain the purpose of `prefer-viewability-over-views` value for `data-loading-strategy` as it's documentation on AMP site is not very clear.

**Comment by jasti** [comment] 2017-02-10 06:00
`prefer-viewability-over-views` is similar to lazy loading the ad - therefore leading to better overall viewability.

**Closed by jasti** 2017-02-10 06:00 UTC
Labels: Category: Ads, Related to: Documentation
