### ISSUE TITLE
Error: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#21187] opened 2019-02-28 18:42 UTC
Error: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
at (https://raw.githubusercontent.com/ampproject/amphtml/1902261915030/src/url.js:529)
at setStyles (https://raw.githubusercontent.com/ampproject/amphtml/1902261915030/src/style.js:151)
at (https://raw.githubusercontent.com/ampproject/amphtml/1902261915030/src/service/resource.js:881)
at document (https://raw.githubusercontent.com/ampproject/amphtml/1902261915030/src/focus-history.js:138)

go/amp-error/CPP11r7Mxrm5Ug

**Comment by choumx** [comment] 2019-03-04 16:23
Dupe of #18212.

**Closed by choumx** 2019-03-04 16:23 UTC
Labels: Type: Bug
