### ISSUE TITLE
Allow JSON-LD markup in <body>

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#3455] opened 2016-06-06 08:37 UTC
Currently will give a validation error, as documented here: https://productforums.google.com/forum/#!topic/webmasters/srBTjitFZEU

**Comment by jridgewell** [comment] 2016-06-06 17:25
Dupe of https://github.com/ampproject/amphtml/issues/1976 (which was just fixed).

**Comment by jaygray0919** [comment] 2016-06-06 18:32
Our preference is to be able to position a JSON-LD island near the DIV with which it is associated. We have pages with 10+ JSON-LD islands. Each island is equivalent to a microformats `itemscope itemtype`. In RDFa, an island is equivalent to an `about` a `type`.

**Comment by Gregable** [comment] 2016-06-13 17:09
I will work on changing the JSON-LD to allow it anywhere in the body.

Your comment about the CSS is confusing. The size constraint (50,000 bytes) is on the byte length of the CSS (ie: everything between `<style amp-custom>` and `</style>`). Do you have any example where the CSS length is <= 50,000 bytes, but the validator is failing?

**Comment by jaygray0919** [comment] 2016-06-13 18:12
TY.
I'll need to reconstruct the files that had the problem; we've modified all of them based on your change.
Gimme a day to get back to you on this. We **thought** our problem had to do with the size of `<head>`. When we moved the JSON-LD from `<head>` to `<body>` the validation passed. Perhaps something else was wrong and we didn't get it at the moment

**Comment by Gregable** [comment] 2016-07-01 22:07
This is fixed in github. Will be released to cdn.ampproject.org next week.

**Closed by Gregable** 2016-07-01 22:07 UTC
Labels: Related to: Validator, Type: Enhancement, Type: Request

**Comment by Gregable** [comment] 2016-07-06 19:51
This change is now live on cdn.ampproject.org.
