### ISSUE TITLE
AMPs with large numbers of Twitter embeds fail to render any of the tweets.

### ISSUE THREAD

**Issue by adewale** [ampproject/amphtml#2548] opened 2016-03-11 03:08 UTC
## Short description of your issue:
AMPs with large numbers of Twitter embeds fail to render any of the tweets.

## How do we reproduce the issue?
1. Look at: http://searchengineland.com/google-dance-2016-recap-244051 and notice that all 32 Twitter embeds eventually render. 
2. Look at the AMP: http://searchengineland.com/google-dance-2016-recap-244051/amp and notice that 0 of the Twitter embeds render.

This is a jsbin showing just the relevant markup: http://jsbin.com/yeroqigiwi/edit?html,css,js,console
 I've seen reports of this but it's usually with a smaller number of embeds and thus hard to reproduce. This example is 100% reproducible for me.

## What browsers are affected?
Chrome 49.0.2623.75 on Mac OS X
Safari 9.0.3 (11601.4.4) on Mac OS X

## Which AMP version is affected?
Version 1457112743399 is affected but I believe this issue has been here since the start. I've just never been able to reliably reproduce it before.

**Comment by mkhatib** [comment] 2016-03-11 03:41
I am able to re-produce. Looking into it.

**Comment by mkhatib** [comment] 2016-03-11 03:57
It seems the `tweet-id`s provided are actually not what we usually expect.

Switching normal expected IDs AMP is able to embed tweets correctly, see: 
http://jsbin.com/zokuno/edit?html,console,output

Any idea what IDs is searchenginelands are using for the tweets? Where are they getting these short ids?

**Comment by mkhatib** [comment] 2016-03-11 04:01
It does seem they're using two different IDs on AMP `tweet-id= 2147483647 ` and non-AMP `tweet-id=705219971425574912`. Any idea if they might have messed up their AMP format data? (also note all the amp-tweets are trying to embed the same tweet-id).

**Comment by erwinmombay** [comment] 2016-03-11 04:55
as for the actual error showing up fix for non existent tweets is in canary through https://github.com/ampproject/amphtml/pull/2537

**Comment by erwinmombay** [comment] 2016-03-11 04:58
yeah, it seems they just have incorrect id's for these tweets and are non existent. see https://twitter.com/anyuser/status/2147483647 (this should redirect to the right user/tweet but as you can see it doesnt exist)

**Comment by mkhatib** [comment] 2016-03-11 05:11
@adewale let me know if this is still an issue. Closing for now.

**Closed** 2016-03-11 05:11 UTC
Labels: 3P

**Comment by mkhatib** [comment] 2016-03-14 20:43
@rudygalfi just wondering if we need to follow up with Search Engine Land on this and make sure this is not a bug in their publishing flow.

**Comment by rudygalfi** [comment] 2016-03-14 21:59
Will follow up

**Comment by MLRobbins** [comment] 2016-03-15 00:45
Hi all - I lead tech/dev at Search Engine Land and was notified of this thread by Gary I. at Google. The issue is not that we are publishing incorrect id's.  We publish on WP, and are utilizing the Automattic AMP plugin. 

I've attached a text file containing the WP UI content for the article referenced above. You'll note we let WP auto handle the twitter embeds. Same for the AMP plugin - we're not customizing embed controls. 

[ArticleContent.txt](https://github.com/ampproject/amphtml/files/173080/ArticleContent.txt)

**Comment by mkhatib** [comment] 2016-03-15 01:13
Thanks @MLRobbins for the context! I just filed a bug under amp-wp project for them to fix a bug with converting Twitter IDs

**Comment by MLRobbins** [comment] 2016-03-15 02:21
No problem - thanks for filing that @mkhatib ~ I'll track it over there.
