### ISSUE TITLE
Add customVars option for Analytics to provide pass-through of query string parameters

### ISSUE THREAD

**Issue by jmadler** [ampproject/amphtml#1881] opened 2016-02-09 22:29 UTC
- Add a customVars option for amp-analytics to provide pass-through of query string parameters
- Add a customVarsKeysReplace option for amp-analytics that is an ordered list of arguments to String.replace() to pre-process keys in customVars.

For example:

{
 customVars: {
   's.evar1': 1,
   's.evar2': 2,
 },
 customVarsKeysReplace: [
  ['s.evar', 'v'],
 ]
}

becomes v1=1&v2=2

**Comment by cramforce** [comment] 2016-02-09 22:44
Why not let people just do

```js
customVars: {
  v1: 1,
  v2: 2,
}
```

**Comment by jmadler** [comment] 2016-02-09 22:48
To allow for flexibility for analytics providers.  Happy to spin off into a separate ITI if that's better.

**Comment by cramforce** [comment] 2016-02-09 22:56
Let me understand:

```js
{
customVars: {
's.evar1': 1,
's.evar2': 2,
},
```

Goes into user config.


```js
customVarsKeysReplace: [
['s.evar', 'v'],
]
}
```

Goes into vendor config. Is that the idea?

**Comment by jmadler** [comment] 2016-02-09 23:05
Yes

**Comment by cramforce** [comment] 2016-02-09 23:05
:shipit:

**Comment by rudygalfi** [comment] 2016-02-09 23:30
This seems reasonable to me. Note #1886, which is proposing supporting values being arrays, but I don't think that should preclude doing this.

Would `customVarsKeysReplace` only be able to be specified in a vendor config? If there is not `customVarsKeysReplace` defined for a `customVars` key, does it get ignored, or passed through as a normal `vars`?

`customVars` as a name bugs me as it doesn't seem to add meaning. How about `vendorVars`?

Also, `customVarsKeysReplace` could be replaced by either `customVarsMap` or `vendorVarsMap`.

**Comment by cramforce** [comment] 2016-02-09 23:48
`customVarsKeysReplace` should also take a map. Arrays are awkward for this.

**Comment by jmadler** [comment] 2016-02-11 01:34
Maps in JSON/JS aren't ordered.  So if we'd ever allow for multiple customVarsKeysReplace aliases to apply to the same key, we should probably go the array of arrays route.  Otherwise, map makes the most sense.

Let me know your thoughts but I'll proceed on the AoA path for now.

**Comment by cramforce** [comment] 2016-02-11 02:03
Definitely go with maps.

**Comment by jmadler** [comment] 2016-02-11 02:05
Will do.

As for naming, I think customVars makes more sense as the vars aren't necessarily vendor provided.  Consider for example an id of a particular bucket to store analytics hits into.  

There's no planned enforcement of customVarsKeysReplace being located anywhere specifically.


Malte - thoughts on customVarsKeysReplace or customVarsMap?

**Comment by rudygalfi** [comment] 2016-02-11 02:08
I can live with customVars and would suggest customVarsMap.

Have you confirmed that #1886 won't mess things up?

**Comment by cramforce** [comment] 2016-02-11 02:09
`customVars` is better than `customVarsMap`. Since `customVarsKeysReplace`
will have exactly one user I don't care how we call it.

**Comment by rudygalfi** [comment] 2016-02-11 02:13
Sorry, should have been clearer. I agree with `customVars` for the user-facing name. I'm suggesting `customVarsMap` for the thing that's a map vs. `customVarsKeysReplace`.

**Comment by avimehta** [comment] 2016-02-12 22:24
I believe this can be closed as well. @rudygalfi

**Comment by rudygalfi** [comment] 2016-02-12 22:40
Yes. I noted there were no examples, so spun up #1991 to track adding some. (cc @jmadler)

**Closed by rudygalfi** 2016-02-12 22:40 UTC
Labels: Related to: Analytics, Type: Enhancement
