### ISSUE TITLE
Ad secondary size, when collapsed off screen is left aligned 

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#6166] opened 2016-11-12 17:20 UTC
The ad should be center aligned when a smaller secondary size ad is returned. 
Repro page: http://www.vox.com/platform/amp/culture/2016/11/12/13587268/life-itself-roger-ebert-steve-james-empathy-streaming
How to reproduce - load the page, wait for a couple of seconds and then scroll down, you will see this.
![vox-multi-2](https://cloud.githubusercontent.com/assets/2366341/20239607/2802ccf0-a8d2-11e6-8514-6984646dde11.png)
I'd expect that ad to be center aligned.

Note that this works fine when the primary size is not collapsed to the secondary size. 
![vox-multi-1](https://cloud.githubusercontent.com/assets/2366341/20239615/526ec084-a8d2-11e6-86cc-7c33c39dbac9.png)

**Comment by glevitzky** [comment] 2016-11-12 20:55
After some investigation, I think the left-alignment is due to the CSS added by .-amp-layout-responsive that decorates the amp-ad tag with "display: block;". If this style is removed, then the ad appears exactly as the other ads on the page (which are not responsive).

So I'm not sure if anything here is broken, it's just that the behavior for multi-size responsive ads might not be that well defined.

@jasti given this information, how do you think we should proceed?

**Comment by jasti** [comment] 2016-11-13 14:42
Thanks @glevitzky.
Even the second case where the ad is centered seems to come with "display:block" but something is preventing it from being left aligned. (As I would expect).
We clearly don't want the ad to be left aligned. 
@lannka for thoughts on how to solve it.

**Comment by glevitzky** [comment] 2016-11-14 17:40
In the case where the ad is centered, the amp-ad tag takes on the full width of the column, so even if it is left-justified, the creative will appear centered in the middle. I'll standby for advice on how to approach this.

**Comment by jridgewell** [comment] 2016-11-14 19:03
This is publisher CSS:

```html
<div class="ad-wrapper">
  <amp-ad />
</div>
```

```css
.ad-wrapper {
  margin: 16px -16px;
}
```

Further, they're trying to display a 300px ad in a space that's only 288px. Instead of putting that negative margin on `.ad-wrapper`, they can do:

```css
.ad-wrapper {
  margin: 16px 0;
}

.ad-wrapper amp-ad {
  transform: translateX(calc((288px - 100%) / 2));
}
```

**Comment by lannka** [comment] 2016-11-14 23:48
@glevitzky is right, multi-size responsive ads seems not be well defined.

`layout=responsive` means the ad will always take the full width, and height will be adjusted to match the aspect ratio.

We should either:
1) do not resize, if full width is indeed what pub want. note that doubleclick creative will still be centered.
2) resize and remove layout=responsive

**Comment by lannka** [comment] 2016-11-14 23:54
@jridgewell i think it is on us. pub should not work around our problem.

as I mentioned, the problem is the AMP element has layout=responsive but not taking the full width.

**Comment by glevitzky** [comment] 2016-11-15 15:29
I think the right approach is to drop layout=responsive if resize succeeds, otherwise keep the logic as is.

**Comment by jasti** [comment] 2016-11-15 15:42
I like the approach.
Dumb question - why not scale the response to the width (and therefore the height) available? That is, instead of fixed pixels, you get the ad to scale responsively to the space available.

**Comment by lannka** [comment] 2016-11-15 16:25
@jasti that sounds like my option 1 (no resize)?

**Comment by jridgewell** [comment] 2016-11-15 16:32
> as I mentioned, the problem is the AMP element has layout=responsive but not taking the full width.

It's taking more than full-width... The pub is trying to display a 300px ad in a 288px space. I don't see how we're supposed to handle that.

> I think the right approach is to drop layout=responsive if resize succeeds

We do. When a resize succeeds, we no longer maintain aspect ratios. It effectively becomes `layout=fixed`.

**Comment by glevitzky** [comment] 2016-11-15 18:05
@jridgewell You can expand the width of the column beyond 300px, and still see the issue. I'm not sure if the width of the column matters here.

**Comment by lannka** [comment] 2016-11-15 19:00
@jridgewell i don't see where we change layout after resizing, can you give a code pointer? as what @glevitzky and I observed,  `.-amp-layout-responsive` is still on the class. so it's either we didn't do or we didn't do it properly.

**Comment by jridgewell** [comment] 2016-11-15 19:10
It gets an inline `width` and `height` style, and it's sizer element gets `padding-top: 0`. That's basically `layout=fixed`.

**Comment by lannka** [comment] 2016-11-15 22:39
I think that's not enough, we'll need to also remove CSS class `.-amp-layout-responsive` and add `.-amp-layout-fixed`. @jridgewell WDYT?

**Comment by jridgewell** [comment] 2016-11-15 22:55
Sure.

**Comment by lannka** [comment] 2016-11-17 00:09
After talking to @dvoytenko we think changing CSS here in AMP is kinda dangerous. It leads to an inconsistency between its layout state and CSS class. Also, it might cause page re-layout.

In fact, after taking a closer look, this particular problem is more at pub side. `text-align: center` 
is really an old way to do this job. They have two better ways to center the ad:

```
.ad-wrapper {
    display: flex;
    align-items: center;
    flex-direction: column;
}
```
or 
```
  .ad-wrapper .amp-ad {
    margin: auto;
  }
```

@jasti maybe we can talk about this in the doc of multi-size ad to help pub do the correct centering?

**Comment by jridgewell** [comment] 2016-11-17 19:11
> It leads to an inconsistency between its layout state and CSS class. Also, it might cause page re-layout.

Can you explain?

**Comment by lannka** [comment] 2016-11-17 19:17
@jridgewell like the question I had in the PR: should we change the element.layout_ to fixed as well? Should we just make it like we rendered it as fixed at the beginning? What if the element doesn't support layout=fixed? Would this layout change cause a page re-layout?

**Comment by jridgewell** [comment] 2016-11-17 20:09
> should we change the element.layout_ to fixed as well? Should we just make it like we rendered it as fixed at the beginning?

Yes.

> What if the element doesn't support layout=fixed? Would this layout change cause a page re-layout? 

Let's add code that asserts anything that calls `changeSize` supports `layout=fixed`.

**Comment by lannka** [comment] 2016-11-18 00:26
I ran out of my arguments. @dvoytenko, your turn. You were more nervous about this than I did.

**Comment by dvoytenko** [comment] 2016-11-18 18:27
Ultimately, we cannot change `display:block` to `display:inline-block` just because a height of an element changed. We also don't need to do that. It's better to center `display:block` than `display:inline-block` anyway.

**Comment by lannka** [comment] 2016-11-29 19:28
@jasti Short summary:

publisher should not rely on `text-align` for horizontal centering. Which will not work in this case.

A more serious way to center a div block is to use either
```
.ad-wrapper {
    display: flex;
    align-items: center;
    flex-direction: column;
}
```
or
```
  .ad-wrapper .amp-ad {
    margin: auto;
  }
```

I will close the issue for now.

**Closed by lannka** 2016-11-29 19:28 UTC
Labels: Related to: Ads, Type: Production Bug
