### ISSUE TITLE
Error: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#23177] opened 2019-07-03 20:56 UTC
Error: Cannot read property 'style' of null
at ka (https://cdn.ampproject.org/rtv/001907022322580/v0/amp-twitter-latest.js:12)
at (https://cdn.ampproject.org/rtv/001907022322580/v0/amp-twitter-latest.js:30)
at Yj.a.w.runPromise.mutate (v0.js:331)
at an (https://cdn.ampproject.org/rtv/001907022322580/v0.js:524)
at Xm.f.Qh (v0.js:523)

go/amp-error/CPn-he3v-cCcrgE

**Comment by zhouyx** [comment] 2019-07-03 20:58
cc @ampproject/wg-ui-and-a11y

**Comment by choumx** [comment] 2019-07-08 15:54
Tangent: curious why this stack isn't unminified. @jridgewell

**Comment by sparhami** [comment] 2019-07-08 16:53
Closing as a dupe of #22990

**Closed by sparhami** 2019-07-08 16:53 UTC
Labels: P1: High Priority, Type: Bug
