### ISSUE TITLE
AMP story broken with animations disabled

### ISSUE THREAD

**Issue by architectstyp** [ampproject/amphtml#26582] opened 2020-01-31 23:13 UTC
## What's the issue?

AMP story broken in latest Chrome browser. Specifically, div animation and ability to click on amp-page-story-attachment element. Pages tested work on Microsoft Edge.

Console reports:
Uncaught TypeError: Cannot read property native-web-animation-runner.js:121  'forEach' of null 
    at ub.push.f.r.pause (native-web-animation-runner.js:121)
    at He.push.f.f.pause (animation.js:279)
    at animation.js:485
    at Array.forEach (<anonymous>)
    at Oe.push.f.f.pauseAll (animation.js:485)
    at ig.push.f.f.setState (amp-story-page.js:423)
    at amp-story.js:1971
    at tc.push.f.f.fire (observable.js:81)
    at amp-story-store-service.js:475
    at Array.forEach (<anonymous>)

native-web-animation-runner.js:121 Uncaught (in promise) TypeError: Cannot read property 'forEach' of null
    at ub.push.f.r.pause (native-web-animation-runner.js:121)
    at He.push.f.f.pause (animation.js:279)
    at animation.js:485
    at Array.forEach (<anonymous>)
    at Oe.push.f.f.pauseAll (animation.js:485)
    at ig.push.f.f.setState (amp-story-page.js:423)
    at amp-story.js:1971
    at tc.push.f.f.fire (observable.js:81)
    at amp-story-store-service.js:475
    at Array.forEach (<anonymous>)
push.f.r.pause	@	native-web-animation-runner.js:121
push.f.f.pause	@	animation.js:279
(anonymous)	@	animation.js:485
push.f.f.pauseAll	@	animation.js:485
push.f.f.setState	@	amp-story-page.js:423
(anonymous)	@	amp-story.js:1971
push.f.f.fire	@	observable.js:81
(anonymous)	@	amp-story-store-service.js:475
push.f.uc.dispatch	@	amp-story-store-service.js:468
push.f.f.open	@	amp-story-draggable-drawer.js:452
push.f.f.open	@	amp-story-page-attachment.js:136
(anonymous)	@	amp-story-page.js:1622
Promise.then (async)		
push.f.f.openAttachment	@	amp-story-page.js:1622
(anonymous)	@	amp-story-page.js:1589

## How do we reproduce the issue?
Visit: https://amp.dev/documentation/examples/visual-effects/amp_story_animations/preview/?format=websites
Also: https://architectstyp.com

1. Animations do not appear.
2. On architectstyp.com, click on the page-story-attachment element.

## What browsers are affected?
Windows 10 Chrome Version 79.0.3945.130 (Official Build) (64-bit), Android Chrome.

## Which AMP version is affected?
AMP version 2001251659540

**Comment by newmuis** [comment] 2020-02-01 05:08
I can't repro on Android Chrome 79.0.3945.136 using AMP version 012001251659540.  Would be good to figure out what's causing the discrepancy here.

**Comment by architectstyp** [comment] 2020-02-01 06:07
Hm, interesting. My fiancee reproduced it just now on her machine... Not sure.
Either way, it's affecting our company website!

**Comment by newmuis** [comment] 2020-02-01 15:42
Next step is to try this out on Windows

**Comment by newmuis** [comment] 2020-02-03 16:32
I was also unable to reproduce this on Windows 10 Home, Chrome 79.0.3945.130 on AMP version 2001251659540,  on architectstyp.com.  All animations and both page attachments seem to work fine, and I have no errors in the JavaScript console.

Are you testing using the production code that is live on the site?  Can you try testing in an incognito window to ensure that there are no user settings or Chrome extensions that are causing the behavior?

**Comment by architectstyp** [comment] 2020-02-05 19:34
Resolved:
I discovered this was an OS setting that Chrome must have recently started reading and applying to website animations. 

On Windows 10, Settings > Ease of Access > Show Animations in Windows.
On Android, Settings > Accessibility > Remove Animations.

Thank you, and apologies for the false alarm.

**Comment by newmuis** [comment] 2020-02-05 19:55
@architectstyp to be clear, the animations were shown in their start state and never actually showed up?  And the page attachment did not enter at all?

This might be a change on our side (#26286), and if that's not working properly, we should fix it.

**Comment by architectstyp** [comment] 2020-02-05 20:10
The animations flashed in their start state and immediately jumped to their end state, and remained that way. The page attachment button was visible, but clicking on it would 'freeze' the page: the attachment would not pop-up, and other functions normally working would stop working properly.

After changing both Windows and Android OS settings, the pages are functioning properly. I wonder why Chrome now listens to these OS settings?

**Comment by newmuis** [comment] 2020-02-05 21:42
> I wonder why Chrome now listens to these OS settings?

It's a feature so that webpages can respect user preferences in the same way that applications do.

@gmajoulet can you investigate the page attachment freezing when `prefers-reduced-motion` is set?  I imagine it might also apply to other system UIs with animations

**Comment by gmajoulet** [comment] 2020-02-05 22:08
Ah, it "works on my machine" © (Chrome 80)
I'll try this further on Windows and Android. #26286 only affects publishers provided animations, and should not have any impact on the bookend that's rendered in a shadow DOM tree. Let's find out what happened

**Comment by gmajoulet** [comment] 2020-02-17 21:01
Still can't manage to repro this one. I will try one more time tomorrow on other devices before closing.

**Comment by gmajoulet** [comment] 2020-06-02 15:55
Still can't repro, please re-open if you're experiencing this issue again.

**Closed by gmajoulet** 2020-06-02 15:55 UTC
Labels: P2: Soon, Type: Bug, WG: stories
