### ISSUE TITLE
amp-auto-ads not working on Firefox

### ISSUE THREAD

**Issue by markbiernat** [ampproject/amphtml#16883] opened 2018-07-18 21:10 UTC
@lannka 
I started a new thread to branch from here https://github.com/ampproject/amphtml/issues/16599#issuecomment-406004994 because the issue seems not to be limited to desktop but includes mobile and is OS and Browser specific.

I did more testing. 

I tested two different domains on multiple pages, with different IPs using the AMP lastest JS code here is what I observed:

Andriod OS Chrome - Ads show
Andriod OS Firefox - Ads do not show

iOS - No information

Mac OS Saffari - Ads show
Mac OS Chrome - Ads show

Windows OS Chrome - Ads show
Windows OS Firefox - Ads do not show
Windows OS IE - Ads do not show

Linux OS Chrome - Ads do not show
Linux OS Firefox -  Ads do not show
Linux Opera - Ads show

Therefore, Ads showing is contingent on OS and Browser  rather than simple a desktop issue.

I also noticed on my Google Analytics Ads support for my observation.

Others might have different results but that is why I tested this on different:
 IPs
 VPNs
Computers 
Domains
To confirm what I am observing

Thank you again and I hope I am helping the project.

**Comment by aghassemi** [comment] 2018-07-20 20:31
assigning to @lannka

**Comment by lannka** [comment] 2018-07-27 22:35
woo, I can reproduce this error message consistently on Firefox locally:

```
Missing resource prop on
```

(we disabled dev().assert in prod so we couldn't get the message in the 1st place. @erwinmombay do you recall what was the reason? It's not the first time I hoped the assertion message could be surfaced on prod)

For some reason, all amp-ad inserted by auto-ads are not picked up by resource scheduler.
before I dig more into this @dvoytenko @jridgewell @aghassemi any tips?

@markbiernat thanks again for reporting and debugging. This is not a "Wordpress AMP native" only issue. 
It might have affected all the browsers you listed:
- Andriod OS Firefox - Ads do not show
- Windows OS Firefox - Ads do not show
- Windows OS IE - Ads do not show
- Linux OS Chrome - Ads do not show
- Linux OS Firefox - Ads do not show

**Comment by jridgewell** [comment] 2018-07-27 22:50
Test page?

> For some reason, all amp-ad inserted by auto-ads are not picked up by resource scheduler.
before I dig more into this @dvoytenko @jridgewell @aghassemi any tips?

Is `connectedCallback` being called on the amp-ad instance?

**Comment by dvoytenko** [comment] 2018-07-27 22:52
Hmm. That should be a pretty straightforward part. No idea why these wouldn't be picked up. They should be picked up right at the insertion time. Any possibility they are inserted with a zero size?

**Comment by lannka** [comment] 2018-07-27 23:11
Found the root cause: in FF, attemptChangeSize is executed before connectedCallback.

Is it an FF issue? Did we do anything special? Otherwise, some other things could have been broken.

test page: examples/auto-ads.amp.html
Code: https://github.com/ampproject/amphtml/blob/master/extensions/amp-auto-ads/0.1/placement.js#L185

**Comment by jridgewell** [comment] 2018-07-27 23:18
> Is it an FF issue?

It's a Custom Elements polyfill issue. The microtask for MutationObserver is coming late.

We could just remove the 0 size optimizations? It only leads to bugs.

**Comment by jridgewell** [comment] 2018-07-27 23:36
Not next tick, because you don't know when connectedCallback will be called. Wait for `buildCallback`.

**Comment by dvoytenko** [comment] 2018-07-27 23:36
We could have attemptChangeSize to wait until connected. Or we could see if
we can proactively resize unconnected element?

**Comment by dvoytenko** [comment] 2018-07-27 23:40
We do have build signal so that could work. Something like this:

```
        whenUpgradedToCustomElement(element).then(element =>
element.whenBuilt()).then(() => {
           ....
        });
```

**Comment by lannka** [comment] 2018-07-27 23:47
is the wait for element build necessary?

**Closed** 2018-07-30 21:04 UTC
Labels: Category: Ads, P2: Soon, Type: Bug
