### ISSUE TITLE
[amp-story-player] Player automatically fire noNextStory event on show method called when last story was read until the end witrh autoplay.

### ISSUE THREAD

**Issue by edoudou** [ampproject/amphtml#31953] opened 2021-01-14 09:31 UTC
## What's the issue?

Player automatically fire `noNextStory` event on `show` method called when last story was read until the end witrh autoplay.

## How do we reproduce the issue?

1. Create a story with autoplay on last page.
2. Put it in an amp-story-player.
3. Read the story untill the end (using autoplay on the last page)
4. Try to use `show` and `play`, the `noNextStory` event automatically fires.

**Comment by processprocess** [comment] 2021-01-14 19:10
cc @Enriqe

**Comment by Enriqe** [comment] 2021-01-14 20:47
I'm having reproducing. 

1. You have storyA and storyB
2. Once storyB finishes it dispatches `noNextStory` (working as intended).
3. You take user back to storyA
4. If user navigates back to storyB using `show('storyB')`, the `noNextStory` event is triggered again when the story finishes playing again automatically, which seems to be working as intended.

**Comment by edoudou** [comment] 2021-01-18 14:10
Hi @Enriqe, not sure if you did reproduce this bug or you are having trouble reproducing it : 

The context : 

I am using buttons to show stories in the player.
Initially, the player is hidden.
When clicking a button, I show my player and use the `show` method to show the story linked to the button.
When click on the cross button in the player, or on the `noNextStory` event, I hide the player

What I am doing is :

1) I open the player on the last story.
2) Wait till the end, The player will hide at the end of the story as `noNextStory` will trigger. (intended)
3) I tried to open the player again on the same story (the last one). I instantly receive the `noNextStory` event, and the player go back hiding before I can event see it. (unintended)

Here you can reproduce the bug : https://codesandbox.io/s/bug-nonextstory-i272v

**Comment by Enriqe** [comment] 2021-01-19 16:40
Thank you very much for the elaborate description and the repro case. I'm able to repro using your sample. Taking a look.

**Comment by Enriqe** [comment] 2021-01-19 17:04
I found the issue can be boiled down to this:

1) When getting to the last page of the last story that has auto-advance, it will dispatch the `noNextStory` event once it finishes. (intended)
2) Using the player APIs to call `pause()` and then `play()` again will send again the `noNextStory` event, since the story page has already reached its end of the `auto-advance` and it's trying to advance to the next story (but there's no - hence why it sends the `noNextStory`).

I'm actually not sure this is a "bug" since technically you are already pausing a "finished" story. 

A solution here would be to rewind the story (e.g. writing `player.go(0, -9999)` on line 95 of your sample) when you hide the story. Would this work for your use case?

**Comment by edoudou** [comment] 2021-01-20 10:07
Yes it is indeed a good solution for most cases, but it still doesn't work if the last story is 1 page long :disappointed: 

`player.go(0, -9999)` does not seems to rewind the autoplay if you are on the first page.

Plus I think it would be a great feature for the amp story player to rewind a story when it was readed till the end (or at least to be an option).
I would was looking into doing it myself, but I think I still miss some options : 
- I could rewind the current story when I close the player if it is at the end, but then I would not rewind a story that ended in the same "player session"
- I could rewind stories when I open the player on them, but then I would not rewind the other stories and might end up swiping to them.
- Even combining both, I could have case I don't rewind the story : I read the 3 stories, close on the 3rd, re open on the 1st, and the 2nd wouldn't be rewinded

**Comment by Enriqe** [comment] 2021-01-20 15:28
Got it, that's super helpful input. 

I think we are getting to the point where we are describing the requirements / objectives of a "rewindStory" API. I think we have an existing issue #31424 so I will close this one. But feel free to reopen / comment there if anything is missing.

Thanks again for your contributions :)

**Closed by Enriqe** 2021-01-20 15:28 UTC
Labels: P1: High Priority, Type: Bug, WG: stories
