### ISSUE TITLE
span selector not working in amp-analytics

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#1761] opened 2016-02-03 18:28 UTC
From @Polylike:

> Hey, it looks like there are a other problem. The problems comes with the tricker. I'm trying this:`"link-trigger":{"on": "click", "selector": "a", "request": "event", "vars":{"eventCategory": "Link", "eventAction": "clicked-link"}},`

> Works fine and every click gets tracked correct. 

> Trying this:
`"span-trigger":{"on": "click", "selector": "#span-intern", "request": "event", "vars":{"eventCategory": "Span", "eventAction": "clicked-span"}}, `

> in combination with this

> ` <span id="span-intern">
    Click here to generate an event
  </span>`

> nothing happend. 

> Looks like there is a problem with the "selector": "#span-intern".

**Comment by avimehta** [comment] 2016-02-04 06:55
@polylike, I created https://jsfiddle.net/1ke6kvdd/embedded/result/ and the code snippet you gave seems to be working. Can you help me reproduce the issue? thanks

**Comment by rudygalfi** [comment] 2016-02-04 06:58
Yes, works for me at the jsfiddle link.

**Comment by Polylike** [comment] 2016-02-04 07:13
Okay, here are my Analytics config https://www.wunschtreppenlift.de/include/analytics-config.json 

`<amp-analytics type="googleanalytics" id="analytics" config="https://www.wunschtreppenlift.de/include/analytics-config.json"></amp-analytics>` 

The Spans are included here https://www.wunschtreppenlift.de e.g. `<span id="pflegede">`

No Events get tracked ("selector": "a" works) and im getting crazy .. searching for days.

Thanks,
Daniel

**Comment by avimehta** [comment] 2016-02-04 07:22
So the issue seems to be that the clicks happening on `<a>` tag and the
`id` is on `span` tag. I edited your html and added "treppenlift-zentrum"
id to the `a` tag instead of the parent span tag and the analytics hits
started getting sent.

After the edits, the html snippet looks like this:

```
<span><strong><a href="
https://www.treppenlift-zentrum.de/treppenlift-preisvergleich?a_aid=54a88eb674f5c&amp;a_bid=5ac52052"
target="_blank" title="Treppenlift Verlgeich auf treppenlift-zentrum.de"
rel="nofollow" id="treppenlift-zentrum">
https://www.treppenlift-zentrum.de/Preisvergleich</a></strong></span>
```

Hope this resolves the issue. If a lot of publishers are encountering this
issue, we might want to find a solution for this. FOr now, the workaround
might is pretty simple.

**Comment by avimehta** [comment] 2016-02-04 07:24
So the issue seems to be that the clicks happening on `a` tag and the
`id` is on `span` tag. I edited your html and added "treppenlift-zentrum"
id to the `a` tag instead of the parent span tag and the analytics hits
started getting sent.

After the edits, the html snippet looks like this:

```html
<span>
  <strong>
  <a href="https://www.treppenlift-zentrum.de/treppenlift-preisvergleicha_aid=54a88eb674f5c&amp;a_bid=5ac52052" target="_blank" title="Treppenlift Verlgeich auf treppenlift-zentrum.de" rel="nofollow" id="treppenlift-zentrum">
    https://www.treppenlift-zentrum.de/Preisvergleich
  </a>
  </strong>
</span>
```

Hope this resolves the issue. If a lot of publishers are encountering this
issue, we might want to find a solution for this. For now, the workaround
might is pretty simple.

**Comment by Polylike** [comment] 2016-02-04 07:26
Wow thanks! Working fine!

**Comment by Polylike** [comment] 2016-02-04 07:45
Sorry, last question: What about the iframe: Can a track the clicks? Span doesnt work and when i include the id in the amp-iframe   ```
<amp-iframe height=1060
          sandbox="allow-scripts allow-same-origin allow-forms allow-popups allow-popups-to-escape-sandbox"
          layout="fixed-height"
          frameborder="0"
          id="iframe-intern"
          scrolling="no"
          src="https://www.test.com"> </amp-iframe>
``` same problem.

**Comment by avimehta** [comment] 2016-02-04 07:47
I think clicks inside iframes are not visible to the parent document. This
unfortunately is a limitation of html and can't be fixed in AMP :/

**Comment by Polylike** [comment] 2016-02-04 07:49
Okay, thanks!

**Comment by dvoytenko** [comment] 2016-02-04 23:49
FYI: I think in some cases we are able to determine the clicks on the iframe in general (not inside, but the fact that iframe itself is clicked). However, it's rather flaky and probably not stable enough for analytics. I do have some info how to do this if you are interested.

**Comment by dvoytenko** [comment] 2016-02-04 23:55
Not so fast. @avimehta it looks like you are only matching selectors against the target. I think we need to look into ancestors as well. Consider this:

```
<div id="match-me">
  <a>One</a>
  <a>Two</a>
</div>
```

If I read the code correctly, a click on "#match-me" will match, but a click on one of the `<a>` inside will not. I don't think this is intentional and we need to fix.

/cc @btownsend

**Comment by avimehta** [comment] 2016-02-04 23:58
ack. I marked it as working-as-intended. I am open to revisiting this if there are people who would like to get this fixed. see https://github.com/ampproject/amphtml/issues/1761#issuecomment-179686612 last para.

**Comment by dvoytenko** [comment] 2016-02-05 00:00
I believe we should.

**Comment by rudygalfi** [comment] 2016-02-05 00:06
Could this lead to undesired behavior where you wouldn't want it to account for ancestors?

I guess if we document it plainly enough ("click on the selector or one if its children") then it's expected behavior. Plus, if you want to scope more narrowly you just need to use a different selector.

I think in the spirit of this feature, it makes sense to capture what's happening to children in outer elements that are being tracked, so I'd vote we revisit.

**Comment by avimehta** [comment] 2016-02-05 00:09
sounds good. will work on this then.

**Closed** 2016-02-16 18:17 UTC
Labels: Priority: High, Related to: Analytics, Type: Bug

**Comment by dvoytenko** [comment] 2016-02-16 18:28
The ancestor selectors have been supported now. So, the original example should work as soon as it's deployed (likely tomorrow).
