### ISSUE TITLE
Error: Object [object RegExp] has no method 'match'

### ISSUE THREAD

**Issue by dparikh** [ampproject/amphtml#15767] opened 2018-06-01 22:46 UTC
Stack trace:
------------
Error: Object [object RegExp] has no method 'match'
at (https://raw.githubusercontent.com/ampproject/amphtml/1527816702194/src/service/viewport/viewport-impl.js:747)
at mutate (https://raw.githubusercontent.com/ampproject/amphtml/1527816702194/src/service/viewport/viewport-impl.js:699)
at restoreOriginalTouchZoom (https://raw.githubusercontent.com/ampproject/amphtml/1527816702194/src/service/viewport/viewport-impl.js:727)
at (https://raw.githubusercontent.com/ampproject/amphtml/1527816702194/src/custom-element.js:544)
at (https://raw.githubusercontent.com/ampproject/amphtml/1527816702194/build/patched-module/document-register-element/build/document-register-element.node.js:345)
at call (https://raw.githubusercontent.com/ampproject/amphtml/1527816702194/node_modules/promise-pjs/promise.js:502)
at doResolve (https://raw.githubusercontent.com/ampproject/amphtml/1527816702194/node_modules/promise-pjs/promise.js:35)
at (https://raw.githubusercontent.com/ampproject/amphtml/1527816702194/build/patched-module/document-register-element/build/document-register-element.node.js:343)
at implementation_ (https://raw.githubusercontent.com/ampproject/amphtml/1527816702194/src/custom-element.js:543)
at (https://raw.githubusercontent.com/ampproject/amphtml/1527816702194/src/base-element.js:875)

Sample referrer:
---------------
Referrer	
https://m-vitonica-com.cdn.ampproject.org/v/s/m.vitonica.com/enfermedades/algunos-motivos-por-los-que-el-corazon-aumenta-su-tamano/amp?usqp=mq331AQECAEoAQ%3D%3D&amp_js_v=0.1 
User agent	
Mozilla/5.0 (Linux; Android 4.4.2; G735-L12 Build/HuaweiG735-L12) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36 
Service	
default-cdn-1p-canary 
Version	
001527816702194

**Comment by jridgewell** [comment] 2018-06-14 16:57
Dupe of https://github.com/ampproject/amphtml/issues/15769.

**Closed by jridgewell** 2018-06-14 16:57 UTC
Labels: Category: Runtime, P1: High Priority
