### ISSUE TITLE
 How to define cookies and custom time limit of cookies  for amp  user notification 

### ISSUE THREAD

**Issue by shubha01** [ampproject/amphtml#9710] opened 2017-06-03 13:21 UTC
Hi ,
Task : i have to notify user notification after every 5 to 6 hours 
query : how we define time period for amp-user-notification box or we can say how to  define time for cookies of google amp  user notification 

thanks 
shubha

**Comment by jridgewell** [comment] 2017-06-05 19:49
Closing as a duplicate of https://github.com/ampproject/amphtml/issues/9709.

**Closed by jridgewell** 2017-06-05 19:49 UTC
