### ISSUE TITLE
amp-sidebar: scrolling issue, scroll content below

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#3871] opened 2016-07-01 18:30 UTC
When you scroll and reach the end of the sidebar, the content below scrolls. 

There's another issue caused by this is: when you scroll the body, the top url bar will hide. So after you reach the end of the sidebar and start to scroll the content below, there will be a gap introduced by the disappearance of the top bar.

<img width="394" alt="topbar-no-gap" src="https://cloud.githubusercontent.com/assets/5419904/16530895/04e74f82-3f7f-11e6-9a37-a08e0f9c7f28.png">

<img width="391" alt="gap" src="https://cloud.githubusercontent.com/assets/5419904/16530897/09f51590-3f7f-11e6-8493-9c66ee709e0c.png">

**Comment by rudygalfi** [comment] 2016-07-13 23:15
@sriramkrish85 Can you take a look?

cc @ericlindley-g

**Comment by ericlindley-g** [comment] 2016-07-13 23:18
Possibly related to the scroll leak issue in the lightbox as well?

**Comment by sriramkrish85** [comment] 2016-07-13 23:30
@ericlindley-g yes!

**Comment by sriramkrish85** [comment] 2016-07-13 23:31
@zhouyx can you also add the - device, os (version) and browser version?

**Comment by zhouyx** [comment] 2016-07-14 17:32
I tested on Chrome with a Nexus 6P running Android 6.0.1
But you can also reproduce it on a emulator.

**Comment by zhouyx** [comment] 2016-07-14 21:08
#4073

**Comment by ericlindley-g** [comment] 2017-02-09 23:18
Looks like this is a dupe of https://github.com/ampproject/amphtml/issues/3871 — this issue is earlier, but the other one has more discussion in it, so keeping that one and closing this.

**Closed by ericlindley-g** 2017-02-09 23:18 UTC
Labels: To be deprecated - Type: Production Bug, Type: Bug
