### ISSUE TITLE
AMP Date Picker opens keyboard on iOS 

### ISSUE THREAD

**Issue by tomayac** [ampproject/amphtml#16490] opened 2018-06-30 09:59 UTC
Click a date input field on iOS, the keyboard opens and arbitrary text can be entered. The date picker fully works, but the keyboard should not open (I believe iOS opens it when the input field has the focus, so programmatically unfocusing might work).

![52a73c08-9ca7-46dc-b598-05ec6900068f](https://user-images.githubusercontent.com/145676/42124068-bf4e1132-7c5c-11e8-86c5-eb1cbfdf202d.png)

**Comment by aghassemi** [comment] 2018-06-30 16:20
Thanks @tomayac. Duplicate of https://github.com/ampproject/amphtml/issues/14017 
/cc @cvializ

**Comment by aghassemi** [comment] 2018-06-30 16:20
closing as dup of https://github.com/ampproject/amphtml/issues/14017

**Closed by aghassemi** 2018-06-30 16:20 UTC
