### ISSUE TITLE
getMode().development missing from *.mjs

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#34364] opened 2021-05-13 16:28 UTC
## What's the issue?

Looks like `getMode().development` is missing from `*.mjs` binaries. 

This results in features like AMP story's preview mode being inaccessible on pages that use `*.mjs` binaries.

## How do we reproduce the issue?

Search for "development" in:
- https://cdn.ampproject.org/v0/amp-story-1.0.js
- https://cdn.ampproject.org/v0/amp-story-1.0.mjs

The origin URL (js) triggers AMP story's preview mode, but the CDN (mjs) doesn't:
- https://travel.usnews.com/ampstories/newyorkcity#development=1
- https://travel-usnews-com.cdn.ampproject.org/v/s/travel.usnews.com/ampstories/newyorkcity?amp_js_v=0.1&usqp=mq331AQHKAFQArABIA%3D%3D#development=1

## What browsers are affected?

All browsers.

## Which AMP version is affected?

Not sure if this is a recent regression in MJS build.

**Comment by gmajoulet** [comment] 2021-05-13 17:42
@mszylkowski can you investigate and re-assign to other team(s) if needed?

**Comment by mszylkowski** [comment] 2021-05-13 18:14
Seems like this is the intended behavior, but we want to allow triggering the development mode on mjs as well, so we need to use `win.location.hash` to determine if the development mode is being triggered.

**Comment by rcebulko** [comment] 2021-05-13 18:27
I've poked around in that area, but `mode.js` is a bit of a hairball so I haven't submitted any major changes. I think the crux is that it's compiled away for ESM, which I think is WAI. For now `parseQueryString_(win.location['originalHash'] || win.location.hash)['development'] == '1'` is probably the simplest solution to fetch the hash param independent of `getMode()`. Even better, make it a helper consumed by `mode.js` and eventually it can be made available to `core`

**Comment by kristoferbaxter** [comment] 2021-05-14 15:50
Marking this issue as resolved since it is by design.

**Closed by kristoferbaxter** 2021-05-14 15:50 UTC
Labels: P2: Soon, Type: Bug, WG: infra
