### ISSUE TITLE
Don't publish internal-only tags on ampproject.org API reference

### ISSUE THREAD

**Issue by taymonbeal** [ampproject/amphtml#4965] opened 2016-09-13 16:54 UTC
The `amp-a4a`, `amp-ad-network-adsense-impl`, `amp-ad-network-doubleclick-impl`, and `amp-ad-network-fake-impl` tags are not part of AMP's publisher-facing API, they're implementation details of the runtime. Including them in the API reference isn't necessary and may mislead publishers.

**Comment by lannka** [comment] 2016-09-16 23:27
Are you talking about pages like [this one](https://www.ampproject.org/docs/reference/extended/amp-ad-network-adsense-impl.html)?
If so, I think you can just remove all the md files in those folders, and they should probably disappear.

**Comment by cramforce** [comment] 2016-09-17 03:38
Just mentioned this to @Meggin and @bpaduch today. This is super confusing. CC @pbakaus

**Comment by bpaduch** [comment] 2016-09-20 16:11
If we remove the .md files from the extension's directory (e.g., [amp-ad-network-adsense-impl.md](https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad-network-adsense-impl/amp-ad-network-adsense-impl.md)) then we lose possibly valuable info (even if it's implementation details).

Additionally,  there are other tags that are "in development" or "experimental" (for example, [amp-apester-media](https://www.ampproject.org/docs/reference/extended/amp-apester-media.html), [amp-app-banner](https://www.ampproject.org/docs/reference/extended/amp-app-banner.html),  [amp-share-tracking](https://www.ampproject.org/docs/reference/extended/amp-share-tracking.html), etc.). Is there a way that we can include a category within the .md files that the import_docs.js can read and determine what to include/exclude (ie., include docs with availability = "Stable").

**Comment by lannka** [comment] 2016-09-23 17:28
Seems to me the issue is already resolved. Closing it.

**Closed by lannka** 2016-09-23 17:28 UTC
Labels: Priority: High, Related to: Ads, Related to: Documentation
