### ISSUE TITLE
Bug in amp-carousel 

### ISSUE THREAD

**Issue by rafaelgodinho-wunderman** [ampproject/amphtml#24844] opened 2019-10-01 23:14 UTC
**## What’s the issue?**
We found a bug in the amp-carousel. After a short investigation, I think it could be the same bug founded in the site itself https://amp.dev/.

**## How do we reproduce the issue?**
Using the same steps evidenced on amp site itself in the pages bellow:
http://hml.vivo4g.clientes.ananke.com.br/videos/erro-carousel-iphone.webm
http://hml.vivo4g.clientes.ananke.com.br/videos/erro-carousel-iphone2.webm

**## What browsers are affected?**
It occurs in IPhone X+ using Google Chrome and Safari.

**## Which AMP version is affected?**
1909181902540

**Comment by sparhami** [comment] 2019-10-02 19:36
Duplicate of #24541

**Closed by sparhami** 2019-10-02 19:36 UTC
Labels: Type: Bug, UI: Component: amp-carousel, WG: ui-and-a11y
