### ISSUE TITLE
[amp-story-player] Allow programatic updating of the JSON configuration

### ISSUE THREAD

**Issue by cpauwels** [ampproject/amphtml#32543] opened 2021-02-09 16:26 UTC
## Describe the new feature or change to an existing feature you'd like to see

The JSON Configuration in the player enables many use cases, but it would be amazing if there was a way to programmatically update that configuration. This would make it possible to enable state-based use cases (such as starring a story, with the icon reflecting the starred status).

**Comment by Enriqe** [comment] 2021-03-17 19:22
Duplicate of https://github.com/ampproject/amphtml/issues/31338, closing this one.

**Closed** 2021-03-17 19:23 UTC
Labels: Type: Feature Request, WG: stories
