### ISSUE TITLE
The tag 'script' is disallowed except in specific forms occurs intermittently

### ISSUE THREAD

**Issue by amans1690** [ampproject/amphtml#4066] opened 2016-07-14 09:51 UTC
![screenshot_2](https://cloud.githubusercontent.com/assets/10262551/16835460/70c4a9aa-49d6-11e6-9700-6f07b33ca4a3.png)
![screenshot_1](https://cloud.githubusercontent.com/assets/10262551/16835461/70c50846-49d6-11e6-9aa5-fcc488196ae2.png)

##Issue:
The tag 'script' is disallowed except in specific forms occurs intermittently by the AMP validator. On refresh the validation error doesn't show

## How do we reproduce the issue?
Issue is reproduce able intermittently. Refer the screenshot attached

URL: http://m.timesofindia.com/city/goa/Traffic-snarls-mark-rath-yatra-in-city/amp_articleshow/53088037.cms#development=1
 
## Which AMP version is affected?
Powered by AMP ⚡ HTML – Version 1467308799816

**Comment by rudygalfi** [comment] 2016-07-14 16:04
cc @powdercloud @Gregable

**Comment by powdercloud** [comment] 2016-07-14 18:20
I tried looking at the URL, but it 404s. So I think I'm left with making some guesses for now:
- I think it's very unlikely that the validator code itself would not consistently produce this error message given the same input.
- So I think the input is probably changing. This could be due to a cache or CDN or multiple webservers etc., configured in such a way so that multiple different copies are available. And, the reproduction of this bug would depend on a load balancer or similar making you fetch a different copy every few requests. This could swing back and forth. See for instance https://en.wikipedia.org/wiki/Round-robin_DNS.
- I have been able to confirm that the IP address of this host is changing. Specificially I see this:
$ ping m.timesofindia.com
PING a358.f1.akamai.net (143.215.203.14) 56(84) bytes of data.

$ ping m.timesofindia.com
PING a358.f1.akamai.net (67.135.105.16) 56(84) bytes of data.
...
Hope this explains the problem. Will close this and please come back if you do find that the validator is not consistently producing the same errors for the same input. Thanks!

**Closed by powdercloud** 2016-07-14 18:20 UTC

**Comment by powdercloud** [comment] 2016-07-14 18:25
Update: the original URL 404s intermittently for me; originally I couldn't see the AMP version of the article but after retrying a few times, I actually got to see it. So, there must be something misconfigured at this site or its CDN for sure.

**Comment by amans1690** [comment] 2016-07-15 06:26
URL: http://m.timesofindia.com/city/goa/Traffic-snarls-mark-rath-yatra-in-city/amp_articleshow/53088037.cms#development=1

@powdercloud @Gregable You can open the url on chrome 
1. for opening the url you have to first set the user agent in chrome dev tools to iphone4 or nexus4/5
2. Then try to access the url

**Comment by powdercloud** [comment] 2016-07-15 21:30
@amans1690 Yes. I can see the page and at the moment the error you initially posted doesn't reproduce for me. My theory is still that the flaky behavior has something to do with the server / dns / cdn configuration for m.timesofindia.com, so it may be that the input to the validator changes. Please see my earlier posts.
