### ISSUE TITLE
amp-form (action-xhr) has stopped working in Internet Explorer 11 and below.

### ISSUE THREAD

**Issue by SimonHogstromRonbol** [ampproject/amphtml#21262] opened 2019-03-05 09:11 UTC
## What's the issue?

amp-form is no longer able to submit using action-xhr, i get this error when i try to submit my form:
`object doesn't support this property or method 'forEach'`
in https://raw.githubusercontent.com/ampproject/amphtml/1902271810270/node_modules/promise-pjs/promise.js

this has worked previously, but doesn't anymore.

## How do we reproduce the issue?

1. open internet explorer 11 or below
2. go to https://ampbyexample.com/components/amp-form/ and scroll down to the action-xhr example
3. type in any name or email and click subscribe.
4. nothing happens, and you see the error in the console.

for real world examples you can use eigther:

- https://www.mm-tag.dk/kontakt-erhverv
- https://www.tagmembran.com/tagpap-phoenix

## What browsers are affected?

Internet Explorer 11 and below

## Which AMP version is affected?

this is a new issue, we have only just now had reports about it from our clients, and judging from experience that means the issue is probably around 2 weeks old.

this looks very similar to an issue raised back in september
https://github.com/ampproject/amphtml/issues/18183

and following suggestions from that issue, i have checked wether this was just the tooltip not showing correctly, and it is not.

**Comment by unumbox** [comment] 2019-03-05 10:14
I noticed this a couple of weeks back on a dev site and was hoping there would be a fix by now.

I'm getting the same error in the console

SCRIPT438: Object doesn't support property or method 'forEach'
Promise.js (174,3)

I.E. Version 11.590.17134.0 on Windows 10

**Comment by aghassemi** [comment] 2019-03-05 17:18
/to @cvializ to investigate. Setting as P1 for now, please adjust as needed.

**Comment by cvializ** [comment] 2019-03-05 18:49
Dupe of #21098 which was resolved by #21232

**Comment by cvializ** [comment] 2019-03-05 18:50
@aghassemi should we consider patching the release?

**Closed by cvializ** 2019-03-05 18:49 UTC
Labels: Category: User Input, P1: High Priority, Type: Bug

**Comment by aghassemi** [comment] 2019-03-05 18:54
replied on https://github.com/ampproject/amphtml/pull/21232#issuecomment-469812855
