### ISSUE TITLE
the top part of lightbox is covered by the iframe bar in AMP cache page

### ISSUE THREAD

**Issue by Jade05** [ampproject/amphtml#15626] opened 2018-05-28 09:05 UTC
Environment：
Safari (iPhone; CPU iPhone OS 11_2_6 like Mac OS X) AppleWebKit/604.5.6 (KHTML, like Gecko)

Description:

As below, the top part of lightbox is covered by the iframe bar in AMP cache page.

![66666](https://user-images.githubusercontent.com/5029635/40606936-8dcec8f4-6299-11e8-807f-1459333e41ff.jpeg)

**Comment by aghassemi** [comment] 2018-05-29 19:44
Hi @Jade05, are you using `amp-lightbox` component or just a `position:fixed` element to create the dialog?

/to @cvializ

**Comment by Jade05** [comment] 2018-05-30 03:04
I use amp-lightbox component in a fixed container. @aghassemi

**Comment by cvializ** [comment] 2018-10-09 20:17
@Jade05 I believe this is fixed in the current version and I'm unable to reproduce. If you're still able to reproduce feel free to reopen the issue. Thank you for reporting your issue

**Closed by cvializ** 2018-10-09 20:17 UTC
Labels: Category: Presentation
