### ISSUE TITLE
AMP amp-redirect-to header not honored on Google AMP cache

### ISSUE THREAD

**Issue by Chee32** [ampproject/amphtml#14693] opened 2018-04-18 14:22 UTC
## What's the issue?

I have created a flower shop within a Wordpress site that relies mainly on amp to run quick mobile pages.  When I load the site via the main url it runs smoothly but when I use Google AMP cache the forms to add to cart do not work.  The issue is that it seems that the amp-redirect-to header does not run after the form is submitted.

## How do we reproduce the issue?

The working url is:
https://flowersfaq.com/florida/orlando-florists/?amp

Once you click on a button to buy flowers, you will be sent to the cart.  You can look at the console and see all of the headers that are sent to and from the browser.

The url that is not working is:
https://flowersfaq-com.cdn.ampproject.org/c/s/flowersfaq.com/florida/orlando-florists/?amp

Once you click on a button to buy flowers it should send you to the cart like the non cached url.  However it just keeps up the loader and does not send the user to the cart.  Everything looks fine on the console and all the headers are the same as the working url.

## What browsers are affected?

I have tested on Chrome and Firefox and got the same issue.  I assume however, this is on all browsers.

## Which AMP version is affected?

I just got my site cached so I am not sure which versions are effected.  My current version is  1524001085966

**Comment by aghassemi** [comment] 2018-04-20 18:08
Hi @Chee32, the `access-control-expose-headers` needs to also include `AMP-Redirect-To` per https://www.ampproject.org/docs/reference/components/amp-form#redirecting-after-a-submission. Looking at your site, it currently does not and I believe that's the cause of the issue.

**Comment by aghassemi** [comment] 2018-04-20 18:08
Closing the issue per comment above, if it does not work, please feel free to reopen the issue.

**Closed by aghassemi** 2018-04-20 18:08 UTC
