### ISSUE TITLE
amp-ad multisize option does not resize on page load/reload when advertisement "doubleclick" is in view.

### ISSUE THREAD

**Issue by mehulchauhan** [ampproject/amphtml#21797] opened 2019-04-10 15:39 UTC
## What's the issue?
amp-ad multisize option does not resize on page load/reload when advertisement "doubleclick" is in view.

You can see https://s3.us-east-2.amazonaws.com/f1-amp/en/latest/article.williams-in-2019-best-case-worst-case.6XtWlcZLUi0urIBmGYAmyp.html and scroll down where you will see advertisement just above social sharing buttons.

code we have to handle multisize advertisement is:

```
<div class="f1-article--addunit pattern-carbonBlack f1-DFP--banner">
  <amp-ad width="320" height="600"
          type="doubleclick" 
          data-slot="/21703060983/www_formula1.com/www_formula1.com_article-view_test"
          layout="fixed"
          data-multi-size="300x600,300x250,320x100,320x50"
          data-multi-size-validation="false"
          >
  </amp-ad>
</div>
```

## How do we reproduce the issue?

1) You can see https://s3.us-east-2.amazonaws.com/f1-amp/en/latest/article.williams-in-2019-best-case-worst-case.6XtWlcZLUi0urIBmGYAmyp.html and scroll down where you will see advertisement just above social sharing buttons.
2) keep scroll position intact when the advertisement is in view and try reloading a page
3) we have different sizes but advertisement container does not resize to fit small ads.

## What browsers are affected?

All Browser, we can even reproduce this in a desktop browser.

## Which AMP version is affected?

We use https://cdn.ampproject.org/v0/amp-ad-0.1.js

**Comment by torch2424** [comment] 2019-04-11 01:10
cc @ampproject/wg-ads

**Comment by zhouyx** [comment] 2019-04-16 05:37
@mehulchauhan Thank you for reporting. This is the expected behavior. 

AMP runtime only resizes element when it doesn't cause page jump, or with user interaction. The case you describes doesn't fall into any of these two categories. Thus the resize attempt is denied by the AMP runtime. 

Let me know if this answers your question. Thank you

**Comment by torch2424** [comment] 2019-04-24 20:13
@mehulchauhan Let us know if @zhouyx answered your issue. If so, can we close this? Thanks! 😄

**Comment by calebcordry** [comment] 2019-07-02 18:16
Closing this as it seems to be working as expected. @mehulchauhan let us know if there is still an issue.

**Closed by calebcordry** 2019-07-02 18:16 UTC
Labels: Category: Ads, Type: Bug
