### ISSUE TITLE
AMP-AD sandbox iframe

### ISSUE THREAD

**Issue by mchr3k** [ampproject/amphtml#19078] opened 2018-11-01 15:16 UTC
<amp-ad> should sandbox the ad iframe to protect against forced top level navigation. This was raised back in 2016 and closed because Chrome was deploying an Intervention and Safari didn't support allow-popups-to-escape-sandbox: https://github.com/ampproject/amphtml/issues/5189

Safari added support for allow-popups-to-escape-sandbox in 2017: https://bugs.webkit.org/show_bug.cgi?id=158875. The Chrome intervention only solves top level redirects for Chrome users. Hence, <amp-ad> should sandbox the ad iframe.

**Comment by lannka** [comment] 2018-11-09 21:45
Seems a dupe of #14240 . we plan to launch it to all ad networks in 12/4 stay tuned.

**Closed by lannka** 2018-11-09 21:45 UTC
Labels: Category: Ads
