### ISSUE TITLE
No banner in web search viewer

### ISSUE THREAD

**Issue by testengineer9** [ampproject/amphtml#10429] opened 2017-07-13 22:52 UTC
## What's the issue?
The app-banner has not been seen in web search viewer. 
Please see the screenshot below,
[nobanner_searchviewer](https://user-images.githubusercontent.com/30087065/28190838-c632cc80-67e1-11e7-8a13-265555e55988.PNG)

Screen capture video also can be found below,
[nobanner_searchViewer.zip](https://github.com/ampproject/amphtml/files/1146866/nobanner_searchViewer.zip)

## How do we reproduce the issue?
1. Open the Chrome browser the following link,
    https://search.google.com/test/amp 
2. Enter the following URL in the text box and click on "RUN TEST"
3. Tap on "PREVIEW SEARCH RESULT"
4. Tap on "amp-app-banner-AMP by Example" in the search result

## What browsers are affected?
iPhone6 (iOS v10.3.1)
Chrome (v59.0)

**Comment by ericlindley-g** [comment] 2017-07-18 19:00
Thanks @testengineer9  — it looks like the user interface for https://search.google.com/test/amp has changed, so I'm not sure if it is able to show the banner anymore (will follow up on this separately)

Another option for previewing documents in the viewer would be searching for amp-app-banner through the regular Google Search interface, but for some reason the test page isn't coming up. 

Unless there's a way around this, I think we should wait to test the amp-app-banner feature in the viewer context until we can find a stable way to test in that context.

@sebastianbenz — do you know of any reason why the amp-app-banner wouldn't show up in Search? (specifically, I'm wondering if there's something implemented for that page specifically directing Search not to crawl or index it — if there's an issue with Search we can follow up offline)

/cc @wildflowertester @Wleyba for visibility

**Comment by ericlindley-g** [comment] 2017-07-18 19:02
Actually just realized that testing finished for the banner, so no ned to pause :)  Will follow up with next steps when we have them

**Comment by muxin** [comment] 2017-08-25 20:40
Right now the way to test amp-app-banner in https://search.google.com/test/amp is not reflecting the actual use case. The amp-app-banner in search viewer in prod is working as intended but there's no proper testing environment. Closing the issue since app banner works fine in search viewer.

**Closed by muxin** 2017-08-25 20:40 UTC
Labels: Category: AMP in Google Search, P2: Soon
