### ISSUE TITLE
Webmaster tools showing 3 types of errors on Amp pages

### ISSUE THREAD

**Issue by jattsaini** [ampproject/amphtml#1694] opened 2016-01-31 15:07 UTC
I am using the AMP plugin for my blog timesnews.co.uk and now the google webmaster tools has started showing AMP pages results in the Google WHT.

First how to add a logo to the amp pages?

37 pages indexed and 10 have errors 

**Following errors are developed:**

**Error in schema.org NewsArticle:** http://www.timesnews.co.uk/3695-best-cough-syrups/amp/

**Prohibited attribute error:**
http://www.timesnews.co.uk/6426-zte-blade-l6-listed-by-fcc-images-and-specifications-leaked/amp/
http://www.timesnews.co.uk/7408-philips-xenium-s616-3000-mah-battery-fcc-approved/amp/
http://www.timesnews.co.uk/6611-new-asus-zenfone-zoom-variant-asus_z00xsb-with-4gb-ram-and-5-5-inch-display-certified-at-tenaa/amp/

**Invalid attribute value:**
http://www.timesnews.co.uk/7129-lg-sold-out-450000-units-of-lg-v10-in-just-45-days-in-the-us/amp/
http://www.timesnews.co.uk/7316-iphone-7-plus-rumored-to-launch-with-256gb-variant-and-3100-mah-battery/amp/
http://www.timesnews.co.uk/7417-huawei-honor-5x-now-available-for-pre-orders-in-the-us-for-199/amp/
http://www.timesnews.co.uk/7024-high-end-letv-max4-70-with-6-9-inch-display-hits-gfxbench/amp/
http://www.timesnews.co.uk/7408-philips-xenium-s616-3000-mah-battery-fcc-approved/amp/
http://www.timesnews.co.uk/7349-acer-launches-iconia-one-8-b1-850-tablet/amp/

How to fix these

**Comment by dvoytenko** [comment] 2016-02-01 18:34
@powdercloud , I looked at couple of the pages with `#development=1` and I see no errors there. Could you please take a look?

**Comment by Gregable** [comment] 2016-02-01 18:57
schema.org errors don't appear in AMP Validation as they are a Google specific markup, not AMP related. 

I looked at some of the prohibitied attr errors and see them on javascript:
[first](http://www.timesnews.co.uk/6426-zte-blade-l6-listed-by-fcc-images-and-specifications-leaked/amp/#development=1): 245:0 The attribute 'content_max_width' may not appear in tag 'amp-carousel'.
[second](http://www.timesnews.co.uk/6426-zte-blade-l6-listed-by-fcc-images-and-specifications-leaked/amp/#development=1): The attribute 'content_max_width' may not appear in tag 'amp-carousel'.

These seem to be working as intended.

The invalid attribute ones do seem OK though. The search console (webmaster tools) simply hasn't recrawled these and caught up.

**Comment by jattsaini** [comment] 2016-02-02 03:17
What to do now then to fix these errors?
Any how to add the site logo to amp pages header?

**Comment by Gregable** [comment] 2016-02-02 17:04
You can see the documentation for the `<amp-carousel>` tag [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-carousel/amp-carousel.md). Specifically, you'll need to remove the attribute `content_max_width` from those tags.

If you aren't adding these yourself (you mentioned an AMP plugin), you may want to contact the developer of the plugin and share these errors (or this thread) with those developers. If it is the wordpress AMP plugin, I believe the support pages are [here](https://wordpress.org/support/plugin/amp), but note that that plugin is in early development (version 0.2) and doesn't look to be complete yet.

**Comment by TranslationsCloud** [comment] 2016-04-25 20:52
Hello,

I am having the same problem. With #development=1 I have a successfull validation.. but Google Webmaster tools says:
**Prohibited attribute**

- Prohibited attributes:	"
- Prohibited attributes:	alt

This is really strange :(

**Comment by powdercloud** [comment] 2016-04-25 22:16
@TranslationsCloud Usually this points at some problem with the html syntax. The webmaster tools use a different html parser, so for some edge cases (like, really invalid html syntax) it behaves differently. This has gotten quite rare and we're working on it, so it would be useful to see your example if you can share it.
If not, you could look for " and alt in your document and look whether anything near it is wrong - e.g., a stray or missing quote character in attributes, etc. Or you could use a html5 validator on the doc (https://validator.w3.org/), it would probably find the issues as well (possibly also some other issues / noise).

**Comment by powdercloud** [comment] 2016-07-29 17:43
Both the webmaster console error reports for AMP and the open source validator have improved quite a bit since this bug was opened. So I'll take the liberty and close it and please come back and file a new issue where specific problems remain. Thanks in advance.

**Closed by powdercloud** 2016-07-29 17:43 UTC
Labels: Type: Question
