### ISSUE TITLE
🌸 Cherry pick request for Issue #15907 into Release #15992

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#15991] opened 2018-06-12 19:01 UTC
Issue #15907
PR #15990 
Release Issue #15992
Target release: 1528416097273
Build: https://travis-ci.org/ampproject/amphtml/builds/391445224
# Reasons
https://github.com/ampproject/amphtml/issues/15907 was a regression between 1527816702194 and 1527021682973 that broke multiple people's usage of amp-sidebar with toolbars. 
/cc @cramforce, @aghassemi

**Comment by aghassemi** [comment] 2018-06-12 19:19
Because this is a regression and multiple folks have raised concern about the issue impacting their site, I believe we should cherry pick. It is unfortunate that the current broken behaviour is actually the desired one, but due to backward-compatibility promise, we need to keep the old behaviour.

**Comment by cramforce** [comment] 2018-06-12 20:24
Approved

**Comment by erwinmombay** [comment] 2018-06-12 20:36
cc @adelinamart

**Comment by cathyxz** [comment] 2018-06-13 00:03
Verified that version 1528841168349 fixes bug with regression test https://codepen.io/cathyxz/pen/OEmoWr. Pending deployment to opt-in and production.

**Comment by adelinamart** [comment] 2018-06-13 15:10
Closing this one since this is now in 1528841168349

**Closed by adelinamart** 2018-06-13 15:10 UTC
Labels: P0: Drop Everything, Type: Release
