### ISSUE TITLE
<amp-analytics> "click" trigger not working for <amp-video>

### ISSUE THREAD

**Issue by andrejoblakceltra** [ampproject/amphtml#24542] opened 2019-09-16 09:02 UTC
## What's the issue?
If you put `"click"` trigger on `<amp-video>` element in `<amp-analytics>`, this trigger never gets invoked, when you click on the video.

## How do we reproduce the issue?
https://jsbin.com/toneluqoda/edit?html,output
Observe the provided example. There are two elements inside: `<amp-video>` and `<button>`. `triggers` for both are set up basically identical. If you click on the button, you can see in network tab of developer tools that tracking request gets invoked, but if you click on the video, video starts playing but tracking request doesn't get invoked.

## What browsers are affected?
All browsers

## Which AMP version is affected?
All versions

**Comment by micajuine-ho** [comment] 2019-12-23 19:27
Hi @andrejoblakceltra, thank you for your issue report. 

After some investigating, I found that the issue only occurs when you toggle the device bar on in the developer console (cmd + shft+ m), which leads me to believe that there is something going on with DevTools.

You can also verify that the request is being sent in the jsBin you linked by clicking on the 'console' tab in the jsBin (while keeping DevTools closed) and then clicking on the video.

Additionally, you might want to look into the [predefined video analytics events](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-video-analytics.md), which include events such as `on: video-ended`, `on: video-pause`, etc.

**Comment by andrejoblakceltra** [comment] 2020-01-03 07:44
Hey @micajuine-ho, thanks for looking into the issue

For me the behavior is very different across different browsers. In Firefox clicking on a video pauses / resumes the video, but does not send an analytics event. While in Chrome clicking on the video send the analytics event, but does not pause / resume video. Very inconsistent behavior. That's with dev tools closed at all times.

We already experimented with `video-play` and `video-paused` events, but it's not a viable solution. For example if you have autoplay enabled on the video, clicks will get tracked even though the user didn't click on anything. It's also causing issues when looping is enabled, as `video-play` event gets triggered on each loop.

The optimal solution would be that video element would behave the same as all other elements: when user clicks on it (video area or video controls), it would trigger a `click` event.

**Comment by micajuine-ho** [comment] 2020-01-07 23:51
@andrejoblakceltra thanks for your response. 

The inconsistent results between different browsers is caused by the fact that these videos are natively implemented by each browser. So Chrome and Firefox will have differences in their`<video>` including the look, implementation, and how they handle events. 

So in this example, what's happening is that the `<video>` is receiving the click signal, and in Firefox click means to pause and unpause (so it consumes that signal and pauses/unpauses the video), while in Chrome, clicking doesn't illicit a response, and so it bubbles up the click event and `<amp-video>`  receives it (and then the analytics request gets sent out). 

To solve this, you can and a [pause overlay](https://amp.dev/documentation/examples/multimedia-animations/click-to-play_overlay_for_amp-video/), and then attach the analytics request to the overlay (`<div>`), instead of the `<amp-video>`.

I will add documentation to amp-analytics to describe how to get click events from a video.

**Comment by micajuine-ho** [comment] 2020-01-21 18:57
Closing this issue now. Feel free to reopen if you have any questions or concerns.

**Closed by micajuine-ho** 2020-01-21 18:57 UTC
Labels: Type: Bug, WG: analytics

**Comment by andrejoblakceltra** [comment] 2020-01-22 07:50
@micajuine-ho sorry for late response. Workaround with overlay is not acceptable. In this case the developer has to handle a lot of edge cases. For instance you cannot just assume to display "play button" overlay and replace it with "pause button" overlay on the first click. If video is set to autoplay, it would need to be the opposite. What about if autoplay is blocked by browser? In this case this would need to be detected in the runtime and proper overlay displayed instead. Overlay also should not overlap native video controls, but if user clicks on those, we run into issue of not being able to track clicks again.

**Comment by micajuine-ho** [comment] 2020-01-22 17:22
Hi @andrejoblakceltra, thanks for your follow up. 
> For instance you cannot just assume to display "play button" overlay and replace it with "pause button" overlay on the first click. 

The link provided above demonstrates how you can use an overlay to track clicks. With some minor changes, you can remove the play/pause button, change the overlay to be transparent, and trigger `click` events (i.e. clicking on the video will create an analytics event but also play/pause the video if that is supported natively by the video player). 

Please let me know if I missed anything or if you would like me to create an example for you.
