### ISSUE TITLE
TypeError: Cannot call method 'indexOf' of undefined

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#11045] opened 2017-08-22 23:59 UTC
TypeError: Cannot call method 'indexOf' of undefined
at id (https://cdn.ampproject.org/rtv/011502819823157/v0.js:54)
at (https://cdn.ampproject.org/rtv/011502819823157/v0.js:86)
at (https://cdn.ampproject.org/rtv/011502819823157/v0.js:104)
at String.replace (native)
at af (https://cdn.ampproject.org/rtv/011502819823157/v0.js:104)
at $e.f.expandUrlAsync (v0.js:99)
at $e.f.expandAsync (v0.js:98)
at yc.then.then.then.d (amp-analytics-0.1.js:145)
at (https://cdn.ampproject.org/rtv/011502819823157/v0.js:15)

**Comment by jridgewell** [comment] 2017-08-23 00:18
```
TypeError: Cannot call method 'indexOf' of undefined
    at indexOf (https://raw.githubusercontent.com/ampproject/amphtml/1503083916053/src/url.js:285:17)
    at https://raw.githubusercontent.com/ampproject/amphtml/1503083916053/src/url.js:284:17
    at https://raw.githubusercontent.com/ampproject/amphtml/1503083916053/src/service/url-replacements-impl.js:877:13
    at String.replace (native)
    at replace (https://raw.githubusercontent.com/ampproject/amphtml/1503083916053/src/service/url-replacements-impl.js:850:23)
    at $e.f.expand_ (https://raw.githubusercontent.com/ampproject/amphtml/1503083916053/src/service/url-replacements-impl.js:675:9)
    at $e.f.expandUrlAsync (https://raw.githubusercontent.com/ampproject/amphtml/1503083916053/src/service/url-replacements-impl.js:613:12)
    at yc.then.then.then.expandAsync (https://raw.githubusercontent.com/ampproject/amphtml/1503083916053/extensions/amp-analytics/0.1/amp-analytics.js:592:18)
    at https://raw.githubusercontent.com/ampproject/amphtml/1503083916053/node_modules/promise-pjs/promise.js:422:20
```

**Comment by jridgewell** [comment] 2017-08-23 00:27
Dupe of https://github.com/ampproject/amphtml/issues/9871.

**Closed by jridgewell** 2017-08-23 00:27 UTC
Labels: P1: High Priority, Type: Bug
