### ISSUE TITLE
Preload on link hover

### ISSUE THREAD

**Issue by samthor** [ampproject/amphtml#17112] opened 2018-07-26 03:27 UTC
## What's the issue?

I'd like to have a way to preload future pages based on some conditions. One of those conditions could be the user hovering their cursor over a link. This could create a `<link rel="preload" ... >` and add it to the current page's header.

Maybe this could be configurable or only support URLs on the same domain.

## How do we reproduce the issue?

[Demo here](http://water-minute.glitch.me) showcasing hover preload, see console for progress. Mostly works on Chrome right now—the `<link rel="preload" as="document">` isn't supported in most places, but Chrome will reuse the document (304'ing on clicking to the next page) even if we say `as="fetch"`.

## What browsers are affected?

Browsers that support `<link rel="preload">`.

## Which AMP version is affected?

New issue / FR.

**Comment by choumx** [comment] 2018-07-26 05:46
Might be a nice feature that individual links could opt into, but I wonder how often (and for how long) users let cursors hover over links before clicking in practice. We'd also want to only trigger preload after some small latency to avoid false positives, which reduces the benefit. 

Do you have any data on this? Or case studies, precedence, etc.

**Comment by aghassemi** [comment] 2019-06-19 20:36
@prateekbh this is related to your preloader work.

**Comment by prateekbh** [comment] 2019-06-19 21:55
We are currently discussing a proposal that preloads links as they enter viewport as the mobile traffic does not really have hover.

Although the current blocker are analytics plugins which re-write the URL on click on the link.
These plugins make it hard to re use the prefetched document as the URL is no more the same and thus the navigation request is a fresh http request and not the prefetched one.

**Comment by prateekbh** [comment] 2019-08-06 15:52
Closing as a duplicate of #19905

**Closed by prateekbh** 2019-08-06 15:52 UTC
Labels: P3: When Possible, Type: Feature Request, WG: performance
