### ISSUE TITLE
Fixed layer: Initially hidden elements are not transfered after becoming visible

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#18661] opened 2018-10-10 17:17 UTC
If a fixed element is initially hidden (tried using `hidden`) attribute, it does not get transfered into the fixed layer initially or after it becomes visible again (via bind).

To repro:
Visit: https://s.codepen.io/aghassemi/debug/VEbmwo#development=1&embeded=1 on iOS device or simulator.

Notice the fixed item already visible is transfered to a separate `<body>` elements which is the fixed layer transfer layer.

Now click on "Show Header" which makes an initially hidden item visible. 

Note that it does not transfer to the fixed later.

**Comment by aghassemi** [comment] 2018-10-10 17:19
@jridgewell Is this something we can fix? (either transfer initially hidden fixed items or do it when then become visible via bind) or should we recommend a workaround (with visibility and pointer-events). 

Causing jank in b/116602931

**Comment by jridgewell** [comment] 2018-10-10 17:44
Dupe of https://github.com/ampproject/amphtml/issues/17475. We're already working on this fix.

**Closed by jridgewell** 2018-10-10 17:44 UTC

**Comment by jridgewell** [comment] 2018-10-30 18:03
Confirmed fixed in latest canary. https://output.jsbin.com/sajapul#development=1&embeded=1
