### ISSUE TITLE
amp-img: Image doesn't load when initially hidden

### ISSUE THREAD

**Issue by rowangray** [ampproject/amphtml#8439] opened 2017-03-28 09:54 UTC
Images that are initially hidden are not loaded when displayed. The use case is a menu (containing images) that on desktop is displayed on hover.

http://jsbin.com/cayere/edit?html,output

**Comment by SchnWalter** [comment] 2017-03-28 10:57
I've also encounter this issue. We are gradually transitioning to AMP and one of the first things we did is replace all images on the website with `amp-image` tags. And we saw this issue on narrow devices (`max-width: 1168px` = 73em) where we convert a 2 columns layout into a layout with 2 tabs, you can see the image not being initialized if you scale down your browser and go to: http://bit.ly/DCitizen

**Comment by SchnWalter** [comment] 2017-03-28 11:55
If I remember correctly, I've also encountered this kind of issue with `fallback` elements of [amp-ad](https://www.ampproject.org/docs/reference/components/ads/amp-ad) tags, which are only displayed if the ad-network decided that there is no ad to display.

The example from the documentation is this:
```
<amp-ad width=300 height=250 type="foo">
  <div fallback>Have a great day!</div>
</amp-ad>
```

And I don't see a reason why this should not work:
```
<amp-ad width=300 height=250 type="foo">
  <amp-img fallback width=300 height=250 src="foo.jpg">
  </amp-img>
</amp-ad>
```

or even:
```
<amp-ad width=300 height=250 type="foo">
  <amp-ad width=300 height=250 type="bar">
  </amp-ad>
</amp-ad>
```

P.S. I'll do some more check as soon as I have time and I'll confirm if this is just in my head or the issue exists.

**Comment by aghassemi** [comment] 2017-03-28 19:06
@SchnWalter I can't reproduce the `amp-ad` with `amp-img` fallback issue. Seems to be working fine: http://codepen.io/aghassemi/pen/EWdmxE  If you find the case where it was failing, please file a separate issue for it.

@rowangray Triggering visibility with CSS is not supported for amp-elements yet. It is something we are working on however. But there is a subset of use-cases that we do support: If an element (or parent of it) is hidden using the standard HTML5 `hidden` attribute and then it is made visible using the `show()` AMP action, then things should work  (does not help with your on-hover use-case however). See http://codepen.io/aghassemi/pen/JWmNoB for the case that it can work.

**Comment by aghassemi** [comment] 2017-04-13 16:38
Closing, please feel free to reopen if still having issues.

**Closed by aghassemi** 2017-04-13 16:38 UTC
Labels: Type: Discussion/Question

**Comment by photocoder** [comment] 2020-01-28 01:05
Hello. 
I have this issue. 
I have images hidden in different slides. 
And they don’t appear after slide show. 
Here is you can see my page with this issue: 
dimasfrolov.com
Block with reviews.
