### ISSUE TITLE
Test shards on Travis can get out of sync relative to the build shards

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#21527] opened 2019-03-21 20:15 UTC
e.g., imagine a build stage is based on merging master commit `aaa111` and the pull request, then in the mean time somebody merges another PR and master advances to commit `bbb222` - then the test stage begins and it merges `bbb222` and the pull request, but pulls the compiled build based on `aaa111 + PR`. This could affect multiple factors:
* if `bbb222` adds tests that depend on the same commit, they will fail
* visual diff and bundle size bases are wrong

**Comment by estherkim** [comment] 2019-05-06 14:56
Here's the exact issue that was raised with Travis - https://github.com/travis-ci/travis-ci/issues/5882

I'll try to come up with a workaround for now. The simplest might be to fail the test job immediately and instruct the requester to restart the whole build if a different SHA is detected.

**Comment by danielrozenberg** [comment] 2019-05-06 15:25
That might be too common in real life (during the day developers merge a few dozen PRs, so it's not unlikely that somebody will send a new PR while another gets merged in the ~8 minutes that it takes for the build stage to finish)

**Comment by rsimha** [comment] 2019-05-28 22:22
As @estherkim discovered, this is an issue on Travis' side that several others have run into. See https://github.com/travis-ci/travis-ci/issues/9476 and https://github.com/travis-ci/travis-ci/issues/5882.

It occasionally causes a mismatch between the commits used by the `build` and `test` stages of our Travis CI matrix. For example, [this](https://travis-ci.org/ampproject/amphtml/jobs/538439074#L324) job sees 1 changed file, while [this](https://travis-ci.org/ampproject/amphtml/jobs/538439079#L324-L352) job from a later stage of the same build sees 28 changed files.

I'm not sure what we can do to mitigate this at our end other than asking those who run into this to restart their CI builds.

**Comment by rsimha** [comment] 2019-05-28 22:44
Did some more digging, and this is indeed due to a changing value of `origin/master` caused by new commits being merged to `master`. For example:

1. In the `build` stage of this job, `origin/master` is 2adb37d
![image](https://user-images.githubusercontent.com/26553114/58516886-868d2880-8177-11e9-8a8d-d3e7a5b6c529.png)

2. By the time the `test` stage rolls around, `origin/master` has moved to 2f4630b. Yet, the job seems to be run against the old `origin/master`, which is 2adb37d. Note that the file diffs (incorrectly) show 27 files as having been deleted. (The same 27 files that were added by 2f4630b.) Also note that there is no commit named `origin/master` in the commit logs.
![image](https://user-images.githubusercontent.com/26553114/58516912-9442ae00-8177-11e9-99de-373a306e0258.png)

One workaround for this might be to establish the `origin/master` commit in the `build` stage, write it to a file that's included in the `gulp build` and `gulp dist` artifacts, and use it as the base point in the `test` stage to compute file diffs.

**Comment by rsimha** [comment] 2019-07-22 21:31
Got a [response](https://travis-ci.community/t/origin-master-moving-forward-between-build-stages/4189/2?u=rsimha) from the Travis forums. It turns out we should be using `TRAVIS_COMMIT` (which should be stable across build stages) and not `origin/master` (which is a moving target).

**Comment by rsimha** [comment] 2019-07-22 21:59
Hmm. `TRAVIS_COMMIT` returns the latest commit, including the unmerged commits that are a part of the PR. I've posted a [follow up](https://travis-ci.community/t/origin-master-moving-forward-between-build-stages/4189/5?u=rsimha) question to the Travis forum.

**Comment by rsimha** [comment] 2019-07-23 15:47
Update: I tried using the first half of `TRAVIS_COMMIT_RANGE`, but that didn't work either. In the example below, the first half of `TRAVIS_COMMIT_RANGE` is 5dc1e49, but the test stage includes 4f93227. Therefore, the commit range isn't a good indicator of the latest commit from `master` that is included in the test stage of a PR build.

![image](https://user-images.githubusercontent.com/26553114/61726062-fd413f00-ad3e-11e9-8b7f-7073c8fce1c4.png)

![image](https://user-images.githubusercontent.com/26553114/61726076-05997a00-ad3f-11e9-8c98-44f4b9523bdb.png)

Meanwhile, we have an [approach](https://travis-ci.community/t/origin-master-moving-forward-between-build-stages/4189/6?u=rsimha) recommended by the Travis folks that involves using this command to figure out the latest commit from `master` that's included in a PR build:
```
git merge-base origin/master HEAD
```
Trying that out next.

**Closed** 2019-08-06 16:40 UTC
Labels: P2: Soon, Type: Bug, WG: infra
