### ISSUE TITLE
amp-form POST does not work on ios

### ISSUE THREAD

**Issue by JakePou** [ampproject/amphtml#7170] opened 2017-01-24 01:34 UTC
Without any changes to my website, the search form which uses XHR stopped working 5 days ago.

Just now I realized all of the POST examples on AMP-HTML's website don't work on Safari on desktop nor iPhone. Although they work on every other browser.

Replicate:
1. Browse to: https://ampbyexample.com/components/amp-form/
2. Scroll down past 1st example which uses GET and not POST All the rest do not work and output a general failure error.

**Comment by jridgewell** [comment] 2017-01-24 01:36
Likely a dupe of https://github.com/ampproject/amphtml/issues/7119, which should be fixed now. /to @mkhatib

**Comment by jridgewell** [comment] 2017-01-24 01:45
@choumx: Please close when the new version is live.

**Comment by JakePou** [comment] 2017-01-24 01:47
Thanks J. Do you we have ETA for when the new version will be live? Please let me know if it'll be awhile so I can create an alternative for our users. Our entire site's search feature is currently failing.

**Comment by jridgewell** [comment] 2017-01-24 18:22
It'll be out today.

**Comment by JakePou** [comment] 2017-01-25 00:34
Cheers @jridgewell

**Comment by choumx** [comment] 2017-01-25 00:46
New version with fix is now live.

**Closed by choumx** 2017-01-25 00:46 UTC
