### ISSUE TITLE
Error: Tried to add display:none element to FixedLayer AMP-STICKY-AD

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#17605] opened 2018-08-20 16:49 UTC
Appears starting in the current opt-in canary release (1534447274459)

```
Error: Tried to add display:none element to FixedLayer AMP-STICKY-AD
at Error (https://raw.githubusercontent.com/ampproject/amphtml/1534447274459/src/log.js:528)
at apply (https://raw.githubusercontent.com/ampproject/amphtml/1534447274459/src/log.js:244)
at apply (https://raw.githubusercontent.com/ampproject/amphtml/1534447274459/src/log.js:257)
at Store (https://raw.githubusercontent.com/ampproject/amphtml/1534447274459/src/service/storage-impl.js:175)
at changeObservable_ (https://raw.githubusercontent.com/ampproject/amphtml/1534447274459/src/service/viewport/viewport-impl.js:146)
at addToFixedLayer (https://raw.githubusercontent.com/ampproject/amphtml/1534447274459/extensions/amp-sticky-ad/1.0/amp-sticky-ad.js:165)
at (https://raw.githubusercontent.com/ampproject/amphtml/1534447274459/src/focus-history.js:107)
at (https://raw.githubusercontent.com/ampproject/amphtml/1534447274459/src/service/viewport/viewport-impl.js:560)
at animateScrollIntoViewInternal_ (https://raw.githubusercontent.com/ampproject/amphtml/1534447274459/src/service/viewport/viewport-impl.js:538)
```

**Comment by zhouyx** [comment] 2018-08-20 20:46
This is not a regression. I've been seeing this error for a while. Duplicate of #13327, #15752. 
The behavior can be caused by publishers config, we shouldn't throw dev error.

**Closed by zhouyx** 2018-08-20 20:46 UTC
Labels: Category: Ads, P2: Soon, Type: Bug

**Comment by lannka** [comment] 2018-08-20 21:02
@zhouyx thanks for looking into this. Do you know what bad config can cause this? Should we mention in sticky-ad documentation?

**Comment by zhouyx** [comment] 2018-08-20 21:26
media query for sure. Which is widely used for <amp-sticky-ad>. We can look into the other cases where the error can happen.
