### ISSUE TITLE
amp-user-notiification close button doesn't work when left position is set or when marker is used

### ISSUE THREAD

**Issue by devignerforhire** [ampproject/amphtml#19864] opened 2018-12-13 07:27 UTC
I'm doing the finishing touches to our newsletter signup form that slides in from the right on desktop and fades in from the bottom on mobile, but when I set the amp-user-notification to left: 100% the close button stops working. This is also the case when the marker is used alongside amp-animation.

Does anybody have any ideas? I've tested on chrome and safari on mac and both are the same.

I setup a slimmed down codepen to illustrate the issue here:
https://codepen.io/smokeyfro/pen/roOMmN

**Comment by devignerforhire** [comment] 2018-12-13 07:41
Forgot to add a link to our staging site, where you can see the issue in action:
https://winefolly.staging.wpengine.com/

**Comment by devignerforhire** [comment] 2018-12-13 10:48
I managed to work around the issue by wrapping the close button with a form, which then reloads the current page. It's not elegant by any means, but it'll work as a temp fix until I can figurer out why the close button doesn't work when positioned and the animation marker is used. If anyone has any ideas I'd love to hear them :)

**Comment by jpettitt** [comment] 2018-12-13 15:47
It's not the `position` it's the `amp-animation`  the `visibility: visible` in the animation is overriding the `visibility: hidden` in the dismissed `amp-user-notification ` .  You might try just positioning it off screen and animating  it in rather than toggling visibility.

**Comment by devignerforhire** [comment] 2018-12-13 15:52
Thanks for the explanation John! I'll give that a try on the morrow and report back with my findings :)

**Comment by jpettitt** [comment] 2018-12-13 15:59
OK, I'm going to close this as "works as intended"

**Closed by jpettitt** 2018-12-13 15:59 UTC
