### ISSUE TITLE
Access to font has been blocked when looking at CNN

### ISSUE THREAD

**Issue by diantekyrie** [ampproject/amphtml#24646] opened 2019-09-19 22:15 UTC
## What's the issue?
`Access to font at 'https://www-i-cdn-cnn-com.cdn.ampproject.org/r/s/www.i.cdn.cnn.com/.a/fonts/cnn/3.9.0/cnnsans-light.woff2' from origin 'https://amp-cnn-com.cdn.ampproject.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
`

Briefly describe the bug.
When searching for CNN articles, lots of font errors are displayed

## How do we reproduce the issue?

1. Opt-in Canary/RC
2. Open Java console
3. Search for CNN

## What browsers are affected?
macOSX Chrome: Version 77.0.3865.90

## Which AMP version is affected?
Canary/RC Version: 1909181902540

![Screen Shot 2019-09-19 at 3 13 56 PM](https://user-images.githubusercontent.com/48487406/65285019-250b1400-daf0-11e9-8c9d-d1a8931823c8.png)

@sparhami if this isn't a UI font issue please re-assign.

**Comment by jridgewell** [comment] 2019-09-19 23:13
@Gregable

**Comment by Gregable** [comment] 2019-09-19 23:27
Reported internally as b/141332166

**Comment by jridgewell** [comment] 2019-09-20 00:13
Fix is live.

**Comment by Gregable** [comment] 2019-09-20 00:13
Should be resolved now. Please reopen if you still see the issue after hard reloading.

**Comment by diantekyrie** [comment] 2019-09-20 16:39
@Gregable It seems to still display the error when you select a CNN article. Is the fix suppose to be all CNN or just on the results page?

**Comment by Gregable** [comment] 2019-09-20 16:54
I can't reproduce.

@diantekyrie Can you reproduce in an incognito window? I suspect you are seeing the effect of the browser cache.

**Comment by diantekyrie** [comment] 2019-09-20 17:07
@Gregable I cannot reproduce whole in the incognito window.

**Comment by Gregable** [comment] 2019-09-20 17:09
Closing as WAI. I'm not sure we can do much about clearing out the browser cache for these pages.

**Closed by Gregable** 2019-09-20 17:09 UTC
Labels: P2: Soon, Type: Bug, WG: caching
