### ISSUE TITLE
Twitter timeline doesn't work

### ISSUE THREAD

**Issue by ank-ct** [ampproject/amphtml#39220] opened 2023-07-05 00:38 UTC
### Description

Add code to insert a twitter timeline according to the official documentation but only one line is displayed, the timeline is not displayed

The code we use is:

```
<h2>Timelines</h2>
  <amp-twitter width=486 height=1312
      layout="responsive"
      data-timeline-source-type="profile"
      data-timeline-screen-name="amphtml"
      data-tweet-limit="5">
  </amp-twitter>
```

### Reproduction Steps

The problem can be seen at 
https://playground.amp.dev/?_gl=1*1s5lz6v*_ga*YW1wLVJ1dTBaMXg2eDFJVUZyMERIZHkyT3c.#share=PCFET0NUWVBFIGh0bWw+CjxodG1sIOKaoT4KICA8aGVhZD4KICAgIDxtZXRhIGNoYXJzZXQ9InV0Zi04IiAvPgogICAgPHRpdGxlPk15IEFNUCBQYWdlPC90aXRsZT4KICAgIDxsaW5rIHJlbD0iY2Fub25pY2FsIiBocmVmPSJzZWxmLmh0bWwiIC8+CiAgICA8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoIiAvPgogICAgPHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT5ib2R5ey13ZWJraXQtYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7LW1vei1hbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aDstbXMtYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7YW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGh9QC13ZWJraXQta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUAtbW96LWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW1zLWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW8ta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUBrZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19PC9zdHlsZT48bm9zY3JpcHQ+PHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT5ib2R5ey13ZWJraXQtYW5pbWF0aW9uOm5vbmU7LW1vei1hbmltYXRpb246bm9uZTstbXMtYW5pbWF0aW9uOm5vbmU7YW5pbWF0aW9uOm5vbmV9PC9zdHlsZT48L25vc2NyaXB0PgogICAgPHNjcmlwdCBhc3luYyBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwLmpzIj48L3NjcmlwdD4KICAgIDxzY3JpcHQgYXN5bmMgY3VzdG9tLWVsZW1lbnQ9ImFtcC10d2l0dGVyIiBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwL2FtcC10d2l0dGVyLTAuMS5qcyI+PC9zY3JpcHQ+CiAgICA8c3R5bGUgYW1wLWN1c3RvbT4KICAgICAgaDEgewogICAgICAgIG1hcmdpbjogMXJlbTsKICAgICAgfQogICAgPC9zdHlsZT4KICA8L2hlYWQ+CiAgPGJvZHk+CiAgICA8aDI+VGltZWxpbmVzPC9oMj4KICA8YW1wLXR3aXR0ZXIgd2lkdGg9NDg2IGhlaWdodD0xMzEyCiAgICAgIGxheW91dD0icmVzcG9uc2l2ZSIKICAgICAgZGF0YS10aW1lbGluZS1zb3VyY2UtdHlwZT0icHJvZmlsZSIKICAgICAgZGF0YS10aW1lbGluZS1zY3JlZW4tbmFtZT0iYW1waHRtbCIKICAgICAgZGF0YS10d2VldC1saW1pdD0iNSI+CiAgPC9hbXAtdHdpdHRlcj4KICA8L2JvZHk+CjwvaHRtbD4K

**Comment by erwinmombay** [comment] 2023-07-19 01:24
when i look at the console i see:

```
[Update] There have been recent updates to Embedded Twitter Timelines and supported parameters.	•For more information on what has changed visit: https://twittercommunity.com/t/embedded-timelines-update-parameters-support/177112	•Please submit feedback or report any bugs: https://twittercommunity.com/c/publisher/websites/
```

so it looks like this is caused by a change on twitters end.

there are some other discussions in https://twittercommunity.com/t/twitter-embed-is-not-working-on-my-wix-website-any-tips/199356/3 that twitter timeline embeds no longer work

https://twittercommunity.com/t/again-list-widget-says-nothing-to-see-here-yet-if-logged-out/198782/3

Unfortunately, I dont know if there is anything we can do on our end.

**Comment by erwinmombay** [comment] 2023-07-19 01:25
closing this for now since, but will re-open if anything changes on twitters end

**Closed by erwinmombay** 2023-07-19 01:25 UTC
Labels: Type: Bug
