### ISSUE TITLE
Force protocol-relative URLs in HTTPS-only tags to use HTTPS

### ISSUE THREAD

**Issue by jmadler** [ampproject/amphtml#2495] opened 2016-03-08 04:21 UTC
I've seen some cases where an AMP HTML document is valid when served over HTTP, but invalid when served over HTTPS, because protocol-relative URLs are treated regularly.  

Since AMP HTML should behave the same over HTTP and HTTPS, I propose we force protocol-relative URLs in HTTPS-only tags to be treated as HTTPS, or, alternatively, be considered invalid.

**Comment by jmadler** [comment] 2016-03-08 04:21
cc @Gregable @cramforce

**Comment by cramforce** [comment] 2016-03-08 14:30
@jmadler What you mean is not that it is invalid, but rather that it doesn't work, right?

Requesting `//` has `https://` sounds like a good idea.

**Comment by Gregable** [comment] 2016-03-08 18:10
I think that there are a few options for https-only tags:

1. runtime forces https, validate all
2. validate protocol relative (ex: `//foo.com`), invalidate 'host' relative (ex: `/foo.html`)
3. validate only absolute.

For URLs which can be rewritten in cache by the amp cache and thus forced https, we should do nothing. For example, `<amp-img src=`. At most maybe emit a warning.

For URLs which cannot be rewritten in cache and which amp runtime manages network requests, we should use strategy 1. This includes URLs such as `<amp-video src=`, `<amp-pixel src=`, etc. This is what jordan is suggesting in the issue, I think.

This leaves a URLs which cannot be rewritten in cache and for which amp-runtime does not manage network requests. These include tags inside a `<noscript>` tag: `<img src=`, `<video src=`, `<audio src=`, `<source src=`, `<track src=`. These also may include URLs in custom stylesheets, except for those that can be rewritten in cache. For these we should use strategy 2.

For `<base href=`, when we do eventually validate it at all, we should use strategy 3.

**Comment by cramforce** [comment] 2016-03-08 18:28
We want to invalidate host-relative (and all non-protocol relative URLs) for places where we require HTTPS or protocol-relative. This is already enforced this way by the runtime.

Inside <noscript> we should force HTTPS or protocol relative. These people know what they are doing anyway.

`<base>` on http would be cool. We just cannot allow relative (except protocol relative) URLs when we require https.

**Comment by Gregable** [comment] 2016-03-08 18:41
> We want to invalidate host-relative (and all non-protocol relative URLs) for places where we require HTTPS or protocol-relative.

Even for cache rewritable resources like images?

**Comment by frnco** [comment] 2016-03-08 19:10
I don't get why host relative should be invalid on HTTPS, since if the page was server from HTTPS the host relative resource should also be fetched as HTTPS, but I may be missing some important background on this issue.

Are there any previous issues/discussions that could be referenced to clarify the issues with relative host/protocol?

**Comment by jridgewell** [comment] 2016-03-08 19:35
>  I don't get why host relative should be invalid on HTTPS

I'm curious too.

**Comment by cramforce** [comment] 2016-03-08 23:35
@Gregable Nope only for HTTPS-only resources.

@frnco I think you are right and it could be allowed. The status quo is mostly the way it is because we wanted to avoid the confusion of different errors based on document origin. Otherwise relative URLs are fine if the doc is HTTPS.

**Comment by adelinamart** [comment] 2017-02-11 00:45
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)

**Closed by adelinamart** 2017-02-11 00:45 UTC
Labels: To be deprecated - Type: Task
