### ISSUE TITLE
[Layers] Error: Cannot read property 'ownerDocument' of undefined

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#22823] opened 2019-06-13 14:59 UTC
Seeing about 80k occurrences.

```
Error: Cannot read property 'ownerDocument' of undefined
at ownerDocument (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/src/service/layers-impl.js:1300)
at contains_ (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/src/service/layers-impl.js:713)
at contains (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/src/service/layers-impl.js:747)
at add (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/src/service/layers-impl.js:883)
at getParentLayer (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/src/service/layers-impl.js:1144)
at remeasure (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/src/service/layers-impl.js:915)
at getOffsetFromParent (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/src/service/layers-impl.js:1071)
at getScrolledPosition (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/src/service/layers-impl.js:252)
at getScrolledPosition (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/src/service/resource.js:622)
at getLayoutBox (https://raw.githubusercontent.com/ampproject/amphtml/1906051812580/src/service/resource.js:673)
```

`go/ampe/CPqwy-H735uuMQ`

**Comment by choumx** [comment] 2019-06-24 19:48
Looks like `other` is undefined: https://github.com/ampproject/amphtml/blob/878909e3fa568ff2dceea4589579b76e6b624930/src/service/layers-impl.js#L730

**Comment by jridgewell** [comment] 2019-07-18 22:57
This is because amp-next-page.js includes **all** of v0.js's code, including it's own copy of `Resources` and `Layers`. /cc @peterjosling

**Comment by choumx** [comment] 2019-07-19 15:55
😱

**Comment by jridgewell** [comment] 2019-07-19 21:41
Closing as a dupe of https://github.com/ampproject/amphtml/issues/22357

**Closed by jridgewell** 2019-07-19 21:41 UTC
Labels: P2: Soon, Type: Bug, WG: runtime
