### ISSUE TITLE
Sidebar problem on iOS 8.1.2 (Iphone)

### ISSUE THREAD

**Issue by Publimix** [ampproject/amphtml#17547] opened 2018-08-16 17:46 UTC
Sidebar component doesn't work on Iphone (for at least 2 days) already.

The sidebar on both https://www.ampproject.org and https://ampbyexample.com is not functioning right 
1. Access any of the two sites from Iphone Safari browser
2. The websites load, but after almost 10 seconds (before they loaded almost instantly)
3. The sidebar si loaded expanded with the sandwich icon shown, and without the closing button

Mozilla/5.0 (iPhone; CPU iPhone OS 8_1_2 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12B440 Safari/600.1.4

Safari browser, Iphone 6s.

https://cdn.ampproject.org/v0/amp-sidebar-0.1.js version is affected.
New issue, first spotted on 14th of August, 2018. Happens after device restart, cache wiped clean.

Attached print-screens below:
![img_0800](https://user-images.githubusercontent.com/37850630/44224568-89dc9800-a193-11e8-9b4a-354ab9154979.PNG)
![img_0801](https://user-images.githubusercontent.com/37850630/44224569-89dc9800-a193-11e8-9822-9439c6b00521.PNG)

**Comment by aghassemi** [comment] 2018-08-16 17:58
@Publimix we have identified this having the same root cause as #17505 which we are fixing and patching on production today. 

//details: Object.assign() is supported only on >iOS 9.

closing as dup of #17505

**Closed** 2018-08-16 17:58 UTC

**Comment by Publimix** [comment] 2018-08-16 18:04
Thanks!
