### ISSUE TITLE
Feedback that lazy loading on iOS is sometimes broken

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#10267] opened 2017-07-05 19:25 UTC
I've heard in various places (Twitter, here in bugs) that lazy loading in iOS is sometimes broken. I believe @jpettitt mentioned at some point to have seen this.

We should spend some quality time trying to repro this.

@dvoytenko's font sizing bug could be a candidate, or some other measuring related issue. This seems bad enough to spend a day or 2 investigating.

**Comment by jpettitt** [comment] 2017-07-05 20:30
Subjectively it seems to happen on pages that are not in the browser cache.  I've not been able to generate a solid repro case.

**Comment by aghassemi** [comment] 2017-07-05 21:03
Anyone has one or two Urls that have shown this behaviour?

**Comment by cramforce** [comment] 2017-07-05 21:43
@aghassemi It was reported for https://scotthelme.co.uk/revocation-is-broken/amp/

Testing with empty cache might be a good hint.

**Comment by cramforce** [comment] 2017-07-05 22:03
For reference https://twitter.com/tunetheweb/status/882665318262464517

**Comment by bazzadp** [comment] 2017-07-05 22:13
Seems worse in Twitter app. Loading same URL in Safari often seems to work, though I think I've seen it on Google search results in Safari too (couldn't be 100% certain on that though). Which is weird as I thought all apps on iOS used same rending engine as Safari app?

Twitter now automatically uses AMP URLs when they exist (in mobile only?) even if plain URL was used, so happening a lot more :-( And no link bar as Google cache is not used, so no easy way to revert to non-AMP version (other than click button to load in Safari and then edit URL).

**Comment by bazzadp** [comment] 2017-07-05 22:31
Reproduced repeatedly with that URL (https://scotthelme.co.uk/revocation-is-broken/amp/) on:

iPhone 6s (iOS 10.3.2) in Twitter app. Only first two images load. Cannot reproduce in Safari at the mo.

iPad Air (iOS 10.3.2) in Twitter app. Only first 6 images load. Cannot reproduce in Safari at the mo.

Both on Wifi with good internet connection.

**Comment by aghassemi** [comment] 2017-07-05 22:59
Thanks @bazzadp, very helpful!

**Comment by cramforce** [comment] 2017-07-05 23:37
@dvoytenko Could it be that this was caused by the same underlying cause as #10195

The example page does have a custom font and lots of text.

**Comment by cramforce** [comment] 2017-07-06 00:11
@bazzadp Can you always repro? if you reload the page (via enter in URL bar), does it repro then?

**Comment by aghassemi** [comment] 2017-07-06 00:20
This repros a good 50% of the time for me in Private mode on Safari/iOS 10.3.2. I have also been able to 100% repo using the followin approach:

1- load the url, scroll to the middle 
2- reload, safari maintains the scroll position but now images won't load anymore.

**Comment by cramforce** [comment] 2017-07-06 00:25
Adjusting priority to P0.

**Comment by cramforce** [comment] 2017-07-06 00:36
I think it is a separate issue. 

Forcing relayout when it repros does not fix it.

**Comment by cramforce** [comment] 2017-07-06 00:40
Layout state is `READY_FOR_LAYOUT` and they seem to be measured correctly with repro.

**Comment by aghassemi** [comment] 2017-07-06 00:42
seems font related, removing loading of the custom font (e.g. remove `<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Merriweather:300,700,700italic,300italic|Open+Sans:700,600,400" />`) fixed it.

**Comment by dvoytenko** [comment] 2017-07-06 01:08
Looking. Does seem like it could be font related.

**Comment by aghassemi** [comment] 2017-07-06 01:53
@dvoytenko @cramforce I have been able to repro this using local proxy **_without_** Dima's recent fix for https://github.com/ampproject/amphtml/issues/10195 and **_not_** been able to _repro_ **_with_** Dima's fix. Not 100% sure it is not an unlucky coincidence but I looks like https://github.com/ampproject/amphtml/pull/10221 has fixed this. I suggest we cherry-pick it on Canary (that fix missed the cut by few hours on Friday)

**Comment by cramforce** [comment] 2017-07-06 03:14
Did some more testing. Pretty sure that this would be fixed by #10221. My comment above "Forcing relayout when it repros does not fix it." is wrong. It does fix it, same as resizing the window.

**Comment by cramforce** [comment] 2017-07-06 14:01
I don't have an iPhone with Twitter with me, but the in-app-browser definitely uses storage separate from Safari. The font issue discussed here happens when this is true:

- AMP JS loaded (e.g. it was already in cache)
- `document.readyState` reaches at least `interactive`
- Fonts have not loaded yet

I suspect that differences between WebKit instances are random and just depend on whether they happen to be in the race-state from above or not. iOS 11 fixes the most important underlying bugs.

**Comment by dvoytenko** [comment] 2017-07-06 18:43
For reference, here's the WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=174031. It has already been fixed in Safari nightly. Hopefully it will make it into Safari 11 release. We found a workaround, but it's definitely better with the native fix.

**Comment by cramforce** [comment] 2017-07-06 20:05
This should now be fixed after going to https://cdn.ampproject.org/experiments.html and opting into "Dev Channel".

**Comment by cramforce** [comment] 2017-07-06 20:06
We also patched this into last week's canary, so it will go to everyone soon.

**Comment by cramforce** [comment] 2017-07-06 20:14
@aghassemi Could you make sure it is fixed with the canary?

**Closed** 2017-07-06 21:17 UTC
Labels: P0: Drop Everything
