### ISSUE TITLE
failed fetching with amp-bind in chrome on ios11

### ISSUE THREAD

**Issue by karsten-eger** [ampproject/amphtml#12321] opened 2017-12-06 16:17 UTC
## What's the issue?

amp-bind not working properly on Chrome iOS when testing on a local machine.
It terminates with a fetching error.

## How do we reproduce the issue?

There's no public domain to reproduce this but I try to give as much information as possible.

- We use a virtual machine with a .local TLD
- We use a self signed certifcate on those machines
- The issue is related to the fetching of new data triggered by amp-bind
- The issue occurs on a derivate of this page: https://m.biker-boarder.de/set-to-basket/1_52792__2_52710.html on the above mentioned local machine 
- Due to it being in Chrome on iOS(11) there's no easy way to get the dev tools running
- We redirected console output to the page itself though and we got:
- ``XHR Failed fetching (local url) Type error`` as the only notice

## What browsers are affected?

iPhone with iOS11 and current Chrome

All other tested browsers (Firefox 57, 58, desk and mobile, Chrome 62 desk, safari on iOS11 and MacOS Sierra) are not affected.

Production page - see above - is not affected as well.

## Which AMP version is affected?

1510956201635

We are not quite sure if this is an AMP or a GoogleChrome for iOS bug though.

**Comment by karsten-eger** [comment] 2017-12-06 16:17
cc @sebastianbenz

**Comment by choumx** [comment] 2017-12-06 16:36
Hmm, I can actually reproduce this sporadically on both Chrome and Safari on OS X and iOS. Looks like sometimes `ww.js` is not fetched until `setState()` is called. Investigating -- thanks for reporting this!

**Comment by choumx** [comment] 2017-12-07 17:02
Looks like the linked page isn't valid AMP and contains 3p scripts which may interfere with amp-bind's operation. Can you share the URL with the valid version you mentioned?

**Comment by karsten-eger** [comment] 2017-12-08 13:41
ah well, linked the mobile version instead of the amp version. There you go: https://amp.biker-boarder.de/set-to-basket/1_52792__2_52710.html

As stated above - the problem only happens locally on a .local TLD with chrome on ios. Otherwise it works as intended.

**Comment by choumx** [comment] 2017-12-08 15:49
Do you know which XHR (to what URL) is failing?

**Comment by karsten-eger** [comment] 2017-12-10 15:33
the amp-bind xhr is the one thats failing. The one for the production example would be this one:
https://amp.biker-boarder.de/set-check-avail/1_52792__2_52710--1713069-1712814-none-none-none.html

funnily enough this really only happens when served locally. :(

**Comment by choumx** [comment] 2017-12-10 16:51
One possibility is that the web server isn't configured to support the origin of your local server. AMP adds the `__amp_source_origin` parameter to XHR requests with the serving origin. For example in prod, the full URL is: `https://amp.biker-boarder.de/set-check-avail/1_52792__2_52710--1713067-none-none-none-none.html?__amp_source_origin=https%3A%2F%2Famp.biker-boarder.de`

What is the full XHR URL that is failing in your local testing? See [AMP CORS policy](https://github.com/ampproject/amphtml/blob/master/spec/amp-cors-requests.md#cors-security-in-amp) for more details.

**Comment by choumx** [comment] 2018-01-07 04:49
Closing this since I think this is related to developer config rather than amp-bind. Please reopen with more detail if I'm mistaken.

**Closed by choumx** 2018-01-07 04:49 UTC
Labels: Category: Dynamic/Personalized Content, P2: Soon, Type: Bug
