### ISSUE TITLE
Scroll inertia on iOS

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#5125] opened 2016-09-20 19:35 UTC
I'm seeing people reporting that in viewers (Google Search, News), the scroll inertia feels off on iOS.

Is there anything we can do about that?
@dvoytenko

**Comment by dvoytenko** [comment] 2016-09-21 18:36
@cramforce Any other pointers? Is it in doc-swipe carousel or blue links? The scroll momentum is definitely different due to `overflow-scroll: touch`. But it's not janky and appears to perform well.

**Comment by jridgewell** [comment] 2016-09-21 19:09
> But it's not janky and appears to perform well.

Jank isn't the issue. It's not the normal page weight.

**Comment by michrome** [comment] 2016-09-21 20:11
e.g. https://news.ycombinator.com/item?id=12542171

**Comment by cramforce** [comment] 2016-09-21 20:57
Right, people perceive the page as "too light".

**Comment by dvoytenko** [comment] 2016-09-21 21:25
Well, yeah, unfortunately iOS uses different algo for `body` and `div` scrolling.

**Comment by cramforce** [comment] 2016-09-21 21:26
Is there a webkit bug for this?

**Comment by jridgewell** [comment] 2016-09-21 21:33
Root issue is https://bugs.webkit.org/show_bug.cgi?id=149264. This prevents us from doing anything about Google Search's Viewer.

I'm not sure if this affects the Google Search App or News.

**Comment by dvoytenko** [comment] 2016-09-21 21:38
Basically, it's this: https://medium.com/@dvoytenko/amp-ios-scrolling-and-position-fixed-b854a5a0d451

**Comment by cramforce** [comment] 2016-09-22 16:14
The Google iOS search app should not have this issue.

What I meant is to ask webkit to allow setting scroll inertia via some
proprietary CSS attribute. That is likely easier for them, than fixing the
fundamental bug.

**Comment by dvoytenko** [comment] 2016-09-23 17:59
Filed https://bugs.webkit.org/show_bug.cgi?id=162499

But I'd expect any iOS WebView to have the same problem as well. I believe the difference is specifically in how iOS Safari overrides root scroller.

**Comment by jridgewell** [comment] 2016-09-23 19:19
@dvoytenko: Can you add to our Browser Bugs spreadsheet?

**Comment by dvoytenko** [comment] 2016-09-24 00:23
@jridgewell Done.

**Comment by adelinamart** [comment] 2017-02-14 00:36
Did anyone followed on the external bug lately? Thanks

**Comment by cramforce** [comment] 2017-02-14 15:23
@adelinamart Uhm, yes :)

**Comment by adelinamart** [comment] 2017-05-12 21:11
the referenced bug seems to be fixed :) @dvoytenko can we close this also? Thanks

**Comment by jridgewell** [comment] 2017-05-12 21:18
Will waiting on the [clarification](https://bugs.webkit.org/show_bug.cgi?id=162499#c5).

**Comment by dvoytenko** [comment] 2017-05-15 18:07
I did independently confirmed that this appears to be the direction that's being taken by iOS Safari.

**Closed by dvoytenko** 2017-05-15 18:07 UTC
Labels: Type: Bug
