### ISSUE TITLE
Error: InvalidStateError (DOM Exception 11): The object is in an invalid state

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#16193] opened 2018-06-20 20:26 UTC
Couldn't get the stack trace

Not sure if this is a new error. Feel free to downgrade.

go/amp-error/CLn1pJ2C9MmqLA

**Comment by choumx** [comment] 2018-06-20 21:56
This is a dupe of #16073.

**Closed by choumx** 2018-06-20 21:56 UTC
Labels: P1: High Priority, Type: Bug
