### ISSUE TITLE
'hidden-mutation-observer' breaks amp-lightbox

### ISSUE THREAD

**Issue by zhang-90** [ampproject/amphtml#19136] opened 2018-11-05 11:52 UTC
### bug

- when close `amp-lightbox` with close event can not really close it if the `amp-lightbox` have `position: fixed` 

### reproduce

1. open [detail page](https://m.aliexpress.com/item/32820771289.html)
2. click Free Ship 
![image](https://user-images.githubusercontent.com/13830429/47997219-1022cd80-e136-11e8-9a2c-4104ad9fffaf.png)

3. click Ship To
![image](https://user-images.githubusercontent.com/4065175/47997269-33e61380-e136-11e8-93bc-73984ff467b7.png)
4. and close it
![image](https://user-images.githubusercontent.com/13830429/47996397-617d8d80-e133-11e8-84bd-8242a41810ca.png)
5. Page gets stuck. It has no effect no matter where you click.

### analysis

- ![image](https://user-images.githubusercontent.com/13830429/47996575-f2546900-e133-11e8-9ae4-7513eaf9797f.png)
- because the amp-lightbox have `position: fixed`, so when you click and trigger close event the amp-lightbox not really close, it is just opacity set to 0

### What browsers are affected?

- all browsers, ios and android

### version

- Powered by AMP ⚡ HTML – Version 1811012008580

**Comment by leonalicious** [comment] 2018-11-05 12:06
![image](https://user-images.githubusercontent.com/4065175/47997248-24ff6100-e136-11e8-8fc5-e5252f499f0b.png)
![image](https://user-images.githubusercontent.com/4065175/47997269-33e61380-e136-11e8-93bc-73984ff467b7.png)

**Comment by choumx** [comment] 2018-11-05 14:54
Looks like `transitionend` or `animationend` events are not triggered by [setting the `closedStyle`](https://github.com/ampproject/amphtml/blob/master/extensions/amp-lightbox/0.1/amp-lightbox.js#L446-L447), which means this [collapse callback](https://github.com/ampproject/amphtml/blob/master/extensions/amp-lightbox/0.1/amp-lightbox.js#L428-L435) is never called. Not sure why yet.

Doesn't repro on the ABE example which also uses the `amp-lightbox.close` action.

**Comment by leonalicious** [comment] 2018-11-05 15:04
please try with the sample here : https://github.com/aemsite/ampdemo/blob/master/cant-close-lightbox.html

Basically when the `lightbox` is styled with `position:fixed`, then when users trigger `lightbox.close` actions, the `[hidden]` will not be appended to the `lightbox` anymore.

**Comment by choumx** [comment] 2018-11-05 15:12
Yea, probably related to fixed-layer. Looks like the problematic lightbox is being tracked by `FixedLayer` per its `i-amphtml-fixedid`:

```html
<amp-lightbox id="country-lb" 
    class="float-wrap i-amphtml-element i-amphtml-layout-nodisplay i-amphtml-overlay i-amphtml-scrollable i-amphtml-layout" 
    layout="nodisplay" 
    scrollable="" 
    i-amphtml-fixedid="F10" 
    style="opacity: 0; top: calc(0px);">
```

@leonalicious Adding `position: fixed` and `top` and `bottom` CSS is redundant since amp-lightbox already has it: 
https://github.com/ampproject/amphtml/blob/78e80f1ac5de8ed96d529e54db2da4a064ebb94b/extensions/amp-lightbox/0.1/amp-lightbox.css#L16-L24

**Comment by choumx** [comment] 2018-11-05 15:30
`transitionend` and `animationend` events are not triggered because `FixedLayer` sets `transition: none`.

**Comment by choumx** [comment] 2018-11-05 15:50
Disabling `hidden-mutation-observer` experiment fixes this, which is an easy and low-risk cherry-pick. @cvializ 

One idea to roll-forward is to avoid tracking AMP elements that are known to be fixed-position e.g. amp-lightbox, amp-image-lightbox, etc. A simple early-return in `FixedLayer.setupElement_` appears to work.

**Comment by jridgewell** [comment] 2018-11-05 18:18
The issue is not with `hidden-mutation-observer`, but the experiment surfaced it. This can still happen if a fixed-layer update happens in between the close action and when it actually finishes.

**Comment by choumx** [comment] 2018-11-05 19:15
True but when do fixed-layer updates trigger without the mutation observer? AFAICT only on init and a few special cases (viewer, amp-live-list).

**Comment by choumx** [comment] 2018-11-06 05:13
This is fixed in version 1811051833450. 

#19149 tracks the follow-up work that will allow `hidden-mutation-observer` to roll forward.

**Closed by choumx** 2018-11-06 05:13 UTC
Labels: Category: Runtime, P0: Drop Everything, Type: Bug

**Comment by choumx** [comment] 2018-11-06 05:35
Hmm, works fine for me on iOS Chrome 72 on iOS 12.

**Comment by Hanrui** [comment] 2018-11-06 05:55
> hey, thank you for the prompt fixed , but just FYI, we have tested, it is working fine on Android and iOS safari, but not on iOS Chrome, we are still looking at it...

I think that's a new issue. This time, when you click the close button on the top left corner of the shipping-to country list, the page is not stuck, but you will be brought back to the product list page.

**Comment by leonalicious** [comment] 2018-11-06 12:19
here you go with the UA of Chrome on iOS： 

Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/70.0.3538.75 Mobile/15E148 Safari/605.1

hope it helps.
