### ISSUE TITLE
Page not found in amp.dev

### ISSUE THREAD

**Issue by Stefany93** [ampproject/amphtml#22496] opened 2019-05-24 18:54 UTC
## What's the issue?

Page not found https://amp.dev/documentation/examples/components/amp-accordion/?referrer=ampbyexample.com

## How do we reproduce the issue?

Go here https://amp.dev/documentation/components/amp-accordion and click Annotated code example for amp-accordion

**Comment by tannerbaum** [comment] 2019-05-24 20:20
That is strange, because it works for me. Both by clicking the link up top and following the reproduction steps. 

![Screenshot 2019-05-24 at 16 20 01](https://user-images.githubusercontent.com/1280597/58354544-cd111900-7e3f-11e9-99c2-65440d86bbc7.png)

**Comment by eduardogoncalves** [comment] 2019-05-26 03:54
It works for me too.

**Comment by Stefany93** [comment] 2019-05-27 21:06
^^ Next time I will post a pic so you guys wont think I am gas-lighting you :-) thanks for checking.

**Comment by tannerbaum** [comment] 2019-05-29 12:25
Haha no problem! Maybe @Stefany93 you can close the issue if it is safe to do so?

**Closed** 2019-06-03 19:19 UTC
Labels: Type: Bug
