### ISSUE TITLE
Responsive layout not applied to placeholder image

### ISSUE THREAD

**Issue by rowan-m** [ampproject/amphtml#7690] opened 2017-02-21 17:11 UTC
Using a `placeholder` `amp-img` with a `responsive` layout inside an `amp-iframe` with a `fixed` layout (or other layout as well) results in a stretched image that seems to follow the `fill` layout instead.

## How do we reproduce the issue?
https://merewood.org/placeholders/resizing.html
https://github.com/rowan-m/rowan-m.github.io/blob/master/placeholders/resizing.html

![screenshot from 2017-02-21 17 03 00](https://cloud.githubusercontent.com/assets/108052/23175855/a28f64b2-f858-11e6-870c-7d8238499ca6.png)

## What browsers are affected?

Chrome on desktop and mobile at least.

## Which AMP version is affected?

1487358851767

**Comment by zhouyx** [comment] 2017-02-21 19:05
placeholder will always have `left: 0, right: 0, top: 0, bottom: 0` I think a quick fix on client side would be having another div containing the img. 
What's our approach on having layout responsive placeholder?

**Comment by aghassemi** [comment] 2017-02-21 19:15
@rowan-m placeholders always `fill` otherwise they won't cover the full area of the element they are a placeholder for, so I believe that's by design ( @dvoytenko ? ). 

I recommend having a placeholder image that has the same aspect-ratio as the parent element in which case the image covers the whole area (good UX) and is not distorted (good UX). 

Failing that, you can use `object-fit` and `object-position` CSS to not distort the image ( e.g. `amp-img[placeholder] img { object-fit: cover }`. Using `object-fit: cover` may hide parts of the image but at least it fully covers the parent. Using `contain` will show full image, but won't fully cover the parent leaving blank areas around. Former is a better UX in my opinion.

**Comment by dvoytenko** [comment] 2017-02-21 19:21
`object-fit` is good. Also, the image can be placed into the `<div placeholder>`. `object-fit` works better for height-based responsiveness, which is impossible to otherwise achieve in CSS.

**Comment by camelburrito** [comment] 2017-02-21 20:52
i just do  `postion:absolute;top:0;left:0;right:0;bottom:0;` we could make that the default. This would also help with layering.

**Comment by aghassemi** [comment] 2017-02-22 01:29
@rowan-m Closing this issue based on the workarounds provided above and the fact that this is by design. Feel free to re-open if you disagree.

**Closed by aghassemi** 2017-02-22 01:29 UTC
Labels: Type: Bug, Type: Discussion/Question
