### ISSUE TITLE
on search results in android when clicked in amp page, if app is installed android is requesting to choose which one to open

### ISSUE THREAD

**Issue by mauricionr** [ampproject/amphtml#10641] opened 2017-07-26 12:00 UTC
## What's the issue?

on search results in android when clicked in amp page, if an app is installed, android is requesting to choose which one to open

## How do we reproduce the issue?

1. Have an app related to the site
2. search for an amp page
3. try open the amp page

should open amppage instead request to choose which one to open(amppage or app)?

## What browsers are affected?

native Search results or search results in browser

## Which AMP version is affected?

i guess is note related to amp version

**Comment by dvoytenko** [comment] 2017-07-27 23:24
@ericlindley-g This seems would be very odd if happens in the search results since the user is sent via cache. I don't know if we can affect any other on-origin navigations - they are handled by the browser itself. I suppose we could have a guideline to recommend app manifests to exclude matching AMP URLs? Generally it seems like very publisher elective.

**Comment by ericlindley-g** [comment] 2017-07-27 23:36
@mauricionr  — do you have an example? It would be worth checking out exactly

**Comment by mauricionr** [comment] 2017-07-28 00:00
@ericlindley-g i could send a video? or would like to install the app and reproduce the issue?

**Comment by ericlindley-g** [comment] 2017-07-28 00:06
@mauricionr, if you just have either the URL or domain for the site that would be plenty—thanks!

**Comment by ericlindley-g** [comment] 2017-07-28 00:07
Or let me know if it's happening for all sites :)

**Comment by alf7** [comment] 2017-07-28 12:33
@mauricionr can you also clarify which browser you are using? Are you using Chrome or the Google App?

**Comment by mauricionr** [comment] 2017-07-28 14:52
I'm trying to reproduce in other sites/apps

I'm using android 5.1.1
I could reproduce in google chrome 59 and google app

**Comment by ericlindley-g** [comment] 2017-08-01 21:31
I've been digging into this a bit—@mauricionr, can you still reproduce this behavior? If so, have you disabled or blocked javascript in the contexts where you're having the issue?

**Comment by mauricionr** [comment] 2017-08-01 21:45
@ericlindley-g  I'm still reproducing this issue, on search results in browser and google app.

I'm not blocking or disabling javascript.

**Comment by ericlindley-g** [comment] 2017-08-01 22:18
How strange — thanks for getting back so quickly. I'll keep digging here

**Comment by mauricionr** [comment] 2017-11-09 17:46
#12000 i guess this is related

**Comment by aghassemi** [comment] 2017-11-10 01:27
same issue as #12000 closing this one.

**Closed by aghassemi** 2017-11-10 01:27 UTC
Labels: Category: AMP in Google Search, P2: Soon
