### ISSUE TITLE
Getting 'Wrong parent tag' errors for tags that aren't in the article

### ISSUE THREAD

**Issue by danvisintainer** [ampproject/amphtml#13153] opened 2018-01-30 20:06 UTC
## What's the issue?
A few of our articles throw the ["wrong parent tag"](https://www.ampproject.org/docs/reference/validation_errors) error when validating them, but the errors end up pertaining to tags that the pages don't have. This breaks validation.

## How do we reproduce the issue?
Just view these pages and the error shows immediately in the console.

[https://www.billboard.com/amp/articles/columns/hip-hop/7768251/jay-idk-adult-swim-partnership-interview#development=1]()
[https://www.billboard.com/amp/articles/business/8094083/chapter-verse-hm-apology-monkey-sweatshirt-tone-deaf#development=1]()

Both of these pages throw the error `The parent tag of tag 'FORM > DIV [submit-success]' is 'div', but it can only be 'form'.`, but neither page has divs with those attributes, and neither page has form tags either.

## What browsers are affected?
I can reproduce this with Chrome and Safari, and Google's AMP validator throws these same errors as well.

## Which AMP version is affected?
1516833286380

**Comment by aghassemi** [comment] 2018-01-30 23:29
/to @honeybadgerdontcare This is interesting, there is no `form` or `div [submit-success]`. Worried might be a regression of https://github.com/ampproject/amphtml/pull/12813

**Comment by honeybadgerdontcare** [comment] 2018-01-30 23:50
This isn't a regression due to that PR. This is instead an issue due to poorly selecting the appropriate error message*. A fix for selecting a better error message is in but has not been made it to production yet.

The real reason this document is failing is because it does have a `<div>` that is invalid but for a different reason. On line 212 there is `<div apple color emoji ui notocoloremoji symbol emojisymbols font-size:></div>`. Attributes such as `apple`, `color`, `emoji`, etc are invalid AMPHTML.

* It's selecting this error message because the error has to do with divs, and it finds the div tagspec in #12813 but the better error message would be that this isn't about the tag but really about the attributes missing. In #12956 we introduce a change in preferred error type order where we care more about attribute errors than this type of tagspec error.

**Comment by aghassemi** [comment] 2018-01-30 23:52
Phew, thanks so much for investigating @honeybadgerdontcare.

**Comment by Gregable** [comment] 2018-02-02 00:03
See also https://github.com/ampproject/amphtml/issues/12886 which is the same issue.

Closing since this is fixed @ head, just not released.

**Closed by Gregable** 2018-02-02 00:03 UTC
Labels: Category: Validator, P1: High Priority
