### ISSUE TITLE
Add amp-ad event when ad failes to load

### ISSUE THREAD

**Issue by stomaskov** [ampproject/amphtml#13513] opened 2018-02-15 20:42 UTC
## What's the issue?
Our ads have the "AD" label above them and we need to hide it in case the ad slot is not filled. The `amp-ad` properly collapses but there is no event that we could use to hide the label that is above the ad.

## How do we reproduce the issue?
How it look when the ad loads: http://prntscr.com/if7op7
How it looks when it doesn't: http://prntscr.com/if7psq
We would like to hide the label.
I talked with @choumx and @zhouyx  at AMP conference about it.
Possible solutions discussed were to use `amp-bind` and event when ad doesn't load to enable custom action. Or the ability to hide amp-ad parent element.

Edit: I was asked to provide reason why the label was needed and got the answer:
_"...because we have commited ourselves to Norwegian editorial "ethics" - and that says that commercials should be labeled, so users can know for sure whats an ad or not"_

## What browsers are affected?
All browsers.

## Which AMP version is affected?
AMP Version 1518441587106

**Comment by choumx** [comment] 2018-02-20 16:25
/to @zhouyx 

Another option is to add a feature to `amp-ad` for wrapper markup (so the custom "ad" label is a child element that will also be collapsed). 

@stomaskov Have you tried using CSS for this? E.g. `::before` selector + `content` property?

**Comment by stomaskov** [comment] 2018-02-20 16:40
@choumx Yes we tried using CSS but it didn't hide the label if there was no ad.

Using a wrapper markup would probably work in this case.
I just think some post-load event and amp-bind interaction would give more flexibility.

**Comment by zhouyx** [comment] 2018-02-20 17:31
duplicate of #8941 

`::before` selector won't work, because we force the child iframe to fill the ad component, as well as set `amp-ad` `overflow: hidden !important`

Few thoughts here:
1. Use the `amp-layout` component as the ad wrapper. And collapse the `amp-layout` component if possible. 
2. Have the `amp-ad` component support an inner wrapper to the child iframe. This may cause some visibility tracking issue.
3. Use `amp-bind`, or similar workaround to collapse a parent div when the ad collapse. amp-bind may not be applicable because the ad collapse without user interaction. Another thing is, the attempt to collapse the parent div after the ad collapse could potentially cause page jump, and we need to be carefully about it. 

I like option 1 if that's practical. @aghassemi for more ideas.

@jasti We get at least three requests for this feature. Let's prioritize it.

**Comment by aghassemi** [comment] 2018-02-21 00:55
@zhouyx Ideal fix IMO is for `amp-ad` to officially support the concept of wrappers which it can collapse or just `visibility:hidden` same way it does with ads. (i.e. `<amp-ad wrapper-id="someId"`) runtime would validate wrapper is a ancestor of the ad.

Adding a `collapse` action to `amp-layout` which either `display:none` or `visibility:hidden` depending on whether in the viewport or not is fine, but we would still need a `didNotLoad` low-trust event from `amp-ad`

**Comment by zhouyx** [comment] 2018-02-21 22:50
> Ideal fix IMO is for amp-ad to officially support the concept of wrappers which it can collapse or just visibility:hidden same way it does with ads. (i.e. <amp-ad wrapper-id="someId") runtime would validate wrapper is a ancestor of the ad.

We thought about this approach. The problem here is we really depends on `baseElements` methods when determining whether to collapse or not. For example we use `getLayoutBox` instead of `getBoundingClientRect` for example. We can't do that with any element wrapper. 

That's why I am proposing to only allowing `amp-layout` component as the ad wrapper.  I think we will only need an `attemptToCollapse` event that send from ampAd to ampLayout.

```
if (has wrapper amp-layout as immediate parent) {
  ampLayout.attemptCollapse()
} else {
  ampAd.attemptCollapse()
}
```

**Comment by aghassemi** [comment] 2018-02-22 00:37
Forcing wrapper to be `amp-layout` sounds fine to me. Reaming question is whether to be implicit ( e.g. immediate parent being `amp-layout`) or allow any ancestor with a `wrapper-id="someId"`.  I personally think implicit immediate parent being `amp-layout` is good enough to start width. Just needs some good documentation.

**Comment by lannka** [comment] 2018-03-15 23:26
Issue tracked here: #8941

**Closed by lannka** 2018-03-15 23:26 UTC
Labels: Category: Ads, P2: Soon, Type: Feature Request
