### ISSUE TITLE
Error: viewport has zero dimensions

### ISSUE THREAD

**Issue by dparikh** [ampproject/amphtml#15768] opened 2018-06-01 22:50 UTC
stack trace:
-----------
Error: viewport has zero dimensions
at Error (https://raw.githubusercontent.com/ampproject/amphtml/1527816702194/src/log.js:505)
at apply (https://raw.githubusercontent.com/ampproject/amphtml/1527816702194/src/log.js:221)
at apply (https://raw.githubusercontent.com/ampproject/amphtml/1527816702194/src/log.js:234)
at position (https://raw.githubusercontent.com/ampproject/amphtml/1527816702194/src/service/layers-impl.js:683)
at undefined (https://raw.githubusercontent.com/ampproject/amphtml/1527816702194/src/service/action-impl.js:682)
at meta (https://raw.githubusercontent.com/ampproject/amphtml/1527816702194/src/service/action-impl.js:665)
at type (https://raw.githubusercontent.com/ampproject/amphtml/1527816702194/src/service/action-impl.js:876)
at (https://raw.githubusercontent.com/ampproject/amphtml/1527816702194/src/service/viewer-impl.js:962)
at (https://raw.githubusercontent.com/ampproject/amphtml/1527816702194/src/service/url-replacements-impl.js:914)
at match (https://raw.githubusercontent.com/ampproject/amphtml/1527816702194/src/service/url-replacements-impl.js:1094)

sample referrer:
---------------
Referrer	
https://pagesix-com.cdn.ampproject.org/v/s/pagesix.com/2018/05/31/kesha-sheds-light-on-daca-recipients-with-new-music-video/amp/?amp_js_v=0.1 
User agent	
Mozilla/5.0 (Linux; Android 8.0.0; LG-LS998 Build/OPR1.170623.026; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/67.0.3396.68 Mobile Safari/537.36 
Service	
default-cdn-1p-canary 
Version	
001527816702194

**Comment by jridgewell** [comment] 2018-06-14 16:56
Dupe of https://github.com/ampproject/amphtml/issues/8926.

**Closed by jridgewell** 2018-06-14 16:56 UTC
Labels: Category: Runtime, P1: High Priority
