### ISSUE TITLE
errors in Firefox

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amphtml#31818] opened 2021-01-06 15:17 UTC
we have a valid page featuring a deep SVG where labels are set using `amp-list`. Works fine Chrome, but we see these errors in FF (84.0.1)

for:
`-moz-text-size-adjust`
`-webkit-text-size-adjust`

we see:
`
Error in parsing value for ‘-webkit-text-size-adjust’.  Declaration dropped. index.html:1:237
Elements matching selector: body
NodeList(1)
​
0: <body class="amp-mode-mouse" style="opacity: 1; visibility: …rmal none running none;" data-new-gr-c-s-check-loaded="8.867.0">
​
length: 1
​
<prototype>: NodeListPrototype
`

and

`
Unknown property ‘text-size-adjust’.  Declaration dropped. index.html:1:312
Elements matching selector: body
NodeList(1)
​
0: <body class="amp-mode-mouse" style="opacity: 1; visibility: …rmal none running none;" data-new-gr-c-s-check-loaded="8.867.0">
​
length: 1
​
<prototype>: NodeListPrototype
`

---

also:

`Unrecognized at-rule or error parsing at-rule ‘@-ms-keyframes’`
`Unrecognized at-rule or error parsing at-rule ‘@-o-keyframes’.`

and

`
Ruleset ignored due to bad selector.
html.i-amphtml-singledoc.i-amphtml-embedded {
 -ms-touch-action:pan-y;
 touch-action:pan-y
}
`

any thoughts about what's happening with the amp runtime and Firefox?

**Comment by kristoferbaxter** [comment] 2021-01-06 16:38
Can you provide an example URL?

**Comment by jaygray0919** [comment] 2021-01-06 21:45
Sure: https://afdsi.com/flavonoids/

**Comment by kristoferbaxter** [comment] 2021-01-06 21:53
Apologies, was not able to reproduce. Are there additional steps?

<img width="838" alt="Screen Shot 2021-01-06 at 1 52 27 PM" src="https://user-images.githubusercontent.com/61764/103823233-84af6a80-5026-11eb-9a93-762b4fe1fcb9.png">

**Comment by jaygray0919** [comment] 2021-01-07 00:15
compare it with chrome and you'll see the problem. also check the FF console

**Comment by jaygray0919** [comment] 2021-01-07 00:22
![image](https://user-images.githubusercontent.com/11330577/103835528-1bdae900-504c-11eb-8cdf-c327fdf0917c.png)

**Comment by jaygray0919** [comment] 2021-01-07 13:34
@kristoferbaxter anything more i should do to help here?

**Comment by kristoferbaxter** [comment] 2021-01-07 18:14
I see the issue now (previously had the "CSS" option unchecked. Taking a look.

**Comment by jaygray0919** [comment] 2021-01-07 18:51
Note: the URL works on Edge, as on Chrome. The problem seems to be FF specific.

**Comment by kristoferbaxter** [comment] 2021-01-07 20:30
This appears to be a difference in the rendering output from Chromium and Gecko based browsers.

The `<template>` element is specifying the `width` and `height` of the SVG Element, as seen here:
<img width="377" alt="Screen Shot 2021-01-07 at 12 18 27 PM" src="https://user-images.githubusercontent.com/61764/103940623-7de62d80-50e2-11eb-95ac-eff374faabb0.png">

This would be supplied by the inline AMP State, if it contained the values.
<img width="544" alt="Screen Shot 2021-01-07 at 12 20 15 PM" src="https://user-images.githubusercontent.com/61764/103940769-be45ab80-50e2-11eb-82e2-3faaf392daad.png">

But, as you can see, `width` and `height` are actually properties of the 0th and 1st items in the `items` array. So the template when rendered by mustache generates empty attributes for these attributes in the updated DOM.

These empty values are flagged as invalid by Firefox, and the declarations dropped. 

<img width="469" alt="Screen Shot 2021-01-07 at 12 21 56 PM" src="https://user-images.githubusercontent.com/61764/103940922-f9e07580-50e2-11eb-86cf-d8c35e315401.png">

The same is happening in Chromium based browsers.

<img width="664" alt="Screen Shot 2021-01-07 at 12 22 50 PM" src="https://user-images.githubusercontent.com/61764/103941001-17adda80-50e3-11eb-8e17-09da54ff6ca5.png">

### However, this is where the difference in rendering output occurs.

Chromium based browsers inherit the height of the SVG from the surrounding `amp-list` Element.
<img width="319" alt="Screen Shot 2021-01-07 at 12 24 08 PM" src="https://user-images.githubusercontent.com/61764/103941128-46c44c00-50e3-11eb-9b7f-ea37ed24e315.png">

Whereas, Gecko based browsers do not.
<img width="377" alt="Screen Shot 2021-01-07 at 12 25 45 PM" src="https://user-images.githubusercontent.com/61764/103941291-7d01cb80-50e3-11eb-9dac-895c96bdbed9.png">

### Options for remedying
- If the value of the height and width is intended to be passed into the `<amp-mustache>` render, it needs to be specified differently in the `<amp-state>` object.
<img width="507" alt="Screen Shot 2021-01-07 at 12 27 59 PM" src="https://user-images.githubusercontent.com/61764/103941497-cc47fc00-50e3-11eb-8ef4-321491e51b88.png">

- specify a 100% width and height via CSS.
<img width="1204" alt="Screen Shot 2021-01-07 at 12 30 30 PM" src="https://user-images.githubusercontent.com/61764/103941736-29dc4880-50e4-11eb-987b-d5078217f144.png">

**Comment by kristoferbaxter** [comment] 2021-01-07 20:31
Hopefully this was helpful, I'm going to close this issue as it appears to be working as intended.

**Closed by kristoferbaxter** 2021-01-07 20:31 UTC
Labels: Type: Bug

**Comment by jaygray0919** [comment] 2021-01-07 22:35
@kristoferbaxter thank you for the excellent analysis and detail. i see how to fix this. will also bookmark the process as i see similar problems but did not know how to determine root cause. thanks again ...
