### ISSUE TITLE
amp-accordion header with amp-img -> lightbox image doesn't work

### ISSUE THREAD

**Issue by IamAlta** [ampproject/amphtml#14627] opened 2018-04-15 23:40 UTC
**Please only file bugs/feature requests for AMP here.**
## What's the issue?
amp-accordion header won't allow an image with a tap to enlarge (lightbox).
input type="radio" in the header doesn't work, either.

I tried a very large z-index on the amp-img but it doesn't work.

amp-select won't work because it's used in the second child of the accordion sectio> and amp-select cannot be nested.

## How do we reproduce the issue?
Put a lightbox image inside the accordion 1st child, e.g., header
Put a radio input inside the header.

## What browsers are affected?
All browsers

## Which AMP version is affected?
Powered by AMP ⚡ HTML – Version 1523662348051

**Comment by danielrozenberg** [comment] 2018-04-16 18:39
This seems to be a duplicate of #14642. Please reopen if you think otherwise :)

**Comment by cathyxz** [comment] 2018-04-16 19:59
This is due to the fact that we register a clickHandler on the entire `<header>` section and use that to toggle the collapse / expand of the section. Currently links are special cased. To solve the `amp-img` lightbox issue, we could special case anything with an `on="tap"` to avoid triggering the header toggle. This would solve the issue for anything that the developer chooses to manually set a tap target for. 

@IamAlta would you mind shedding some light on what you are trying to do with the radio buttons and why these are going in the first child of `<amp-accordion>` and not the second child? Ideally, this component was made for collapsable headers, so any main content should really be in the second child and not the first. Theoretically, we could also special case radio buttons, but I'm not sure this component was designed for complex interactivity in the header section. 

Further context: 

```
onHeaderPicked_(event) {
    event.preventDefault(); 
    const header = dev().assertElement(event.currentTarget);
    const section = header.parentElement;
    this.toggle_(section);
  }
```

Example: https://codepen.io/cathyxz/pen/OvKBjX

**Comment by cathyxz** [comment] 2018-04-16 20:02
Oh oops, race condition. Sorry I didn't realize it was a duplicate.

**Comment by IamAlta** [comment] 2018-04-16 22:57
Hi @cathyxz 
Thank you for taking the time for this.

My client sells stuff.
Some products are configurable such as
PRODUCT A
Option A1 has selections that depend on what is selected. When Option A1 is selected, those selections show up. E.g., these are hidden until Option A1 is selected.
  RADIO A1 = Red
  RADIOA2 = Blue

Option A2 has DIFFERENT selections (e.g., list of radio options) that depend on the suboptions. They show up when this is selected and Option A1 is closed and deselected.
  RADIO A1 = Red
  RADIOA2 = Green

See here for a working example at the first set, "*REQUIRED: Configure Your Spout Water Fountain"
https://www.gardecor.com/p-nn-aquitane-monaco-pond
Choose a concrete spout - that's it.
BUT
Choose an Iron Spout and the iron spout choices show up.
Choose  a Brass Spout and the brass choices show up. 
The input value for the type of spout (concrete, iron or brass) AND the input value for the spout style are needed in the form for the cart.

>>I would ultimately like to hide the deselected spouts and show the selected one because the list is so long. Then, have a button to show the spouts in case the customer wants to see them, again.

I have a workaround with .show/.hide and on="change:AMP.setState({ activeDiv: event.value})" and using radio instead of amp-selector (I like the amp-selector effect). 
It took some creativity to figure out which ones are selected because someone may decide to select an iron spout after selecting a brass one. Currently, both show up in the $_GET var even one is hidden. Here is my development page, https://m.gardecor.com/amp.product.php?ref=p-nn-aquitane-monaco-pond

BUT WAIT! There's more. 

>>Customers may close the accordion to clean up the page and hide the one they selected. (Sigh. I wish customers were more like computer programs, but they aren't.) So, I need to have the child spout style  stay selected IFF the parent (concrete, iron, or brass) is selected. I'm having to parse the name/values in the add-to-cart function to figure out which ones are the correct selected items.

>>And more — I'd like the images to enlarge when clicked. They don't on the first page, above, but some will have a larger image.

If you can make this work without the blood, sweat and tears, kudos! Beer's on me. Or, wine and hors d'oeuvre.

**Comment by cathyxz** [comment] 2018-04-16 23:48
Thanks a lot for the context! That helps a lot. Okay, I think there are two separate issues we want to solve here. The first one, allowing lightboxed images to open in lightbox, is easy. We can and should just special-case elements with `on="tap"` defined in `<amp-accordion>`. 

The second issue, nesting collapsable selectors based on user selection, is a bit more complex. Let me first clarify that we're on the same page regarding the problem we're trying to solve. You want to nest selectors like so: 

- Option A
  - Option A.1
  - Option A.2
- Option B 
  - Option B.1
  - Option B.2

and display them in such a way that: 
1. Sub options are only shown for the option after an option has been selected. 
2. We collapse the siblings of any option that has been selected, and only show the selected option/sub-option. 

If I'm interpreting this correctly, I think you can still solve it in `<amp-accordion>` by registering `on="tap"` actions on your radio buttons or a containing div, so long as we let the `tap` action inside `<amp-accordion>` be. So the same solution will still work. 

/cc @cvializ in case I got anything wrong. =)

**Comment by IamAlta** [comment] 2018-04-17 18:04
Hi @CathyXZ, @cvializ,
Cathy, you're good :)

Add to your description to _deselect all sub options under the parent option that is _not selected regardless of the input type of the sub option (radio, amp-select, textbox, textarea, select, etc.).

Also, for the selected parent option, I plan to hide the sub options that are not selected to unclutter the page as the customer goes down the page making more selections. And, add a button to show them. 

Let me try your other suggestions and get back to you. It's a busy day here and I should get to it later today or tomorrow.

Have a nice day!

**Closed** 2018-04-20 04:06 UTC
Labels: Category: Presentation, Type: Feature Request

**Comment by cvializ** [comment] 2018-04-24 17:01
Hi @jaygray0919! Is this related to an amp-accordion issue? If not you should [post in amphtml-discuss](https://groups.google.com/forum/#!forum/amphtml-discuss) or if you think there is a bug you can  [open a separate new issue](https://github.com/ampproject/amphtml/issues/new) instead. This helps us track this discussion better.

**Comment by cathyxz** [comment] 2018-04-24 17:48
Hi @jaygray0919, it would help troubleshooting if you had demos illustrating the issue. Feel free to ping me on slack, or open a new issue re: `<amp-image-lightbox>`. =)

**Comment by jaygray0919** [comment] 2018-04-24 18:08
duh! should have demo'd the problem. will set example and ping on slack (@cathyxz , @cvializ )
