### ISSUE TITLE
Support open graph prefix attribute

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#6852] opened 2017-01-03 07:28 UTC
The AMP validator currently shows a validation error for the [open graph protocol's prefix attribute](http://ogp.me) `<html ⚡  prefix="og: http://ogp.me/ns#">`. This fails validation:

```
<!doctype html>
<html ⚡  prefix="og: http://ogp.me/ns#">
<head>
  <meta charset="utf-8">
  <link rel="canonical" href="self.html" />
  <meta name="viewport" content="width=device-width,minimum-scale=1">
  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
  <script async src="https://cdn.ampproject.org/v0.js"></script>
</head>
<body>Hello, AMP world.</body>
</html>
```

**Comment by Gregable** [comment] 2017-01-03 17:58
This is effectively a dupe of https://github.com/ampproject/amphtml/issues/4919 . It's fixed thanks to @darobin, but the actual change hasn't rolled out yet.

**Closed by Gregable** 2017-01-03 17:58 UTC
