### ISSUE TITLE
Links in amp-sidebar stopped working in Chrome

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#6585] opened 2016-12-09 08:20 UTC
Examples: 

* https://ampbyexample.com
* https://www.webton.be/wie-zijn-wij/?wpamp

Steps to reproduce:

Click on any of the links in the menu in https://ampbyexample.com. The amp-sidebar closes, but doesn't open the link.

Reproduceable in Chrome on Desktop and Android (Version 54.0.2840.98). 
Works in Safari.

This got originally reported here:

https://github.com/ampproject/amp-by-example/issues/521

Update: AMP Version 1481049920709

**Comment by sympile** [comment] 2016-12-09 09:39
About an hour ago, the links in the side-bar just stopped working for my site.

It seemed to have occurred after I had used the AMP Cache URL Format Tool on [AmpbyExample](https://ampbyexample.com/advanced/using_the_google_amp_cache/).  This could be a coincidence. Or not. 

The links had been working properly earlier this evening.

I did notice that if I open the link in a new tab, it will follow the link.

**Comment by oliverini** [comment] 2016-12-09 10:14
Can confirm all sites using amp-sidebar (including the project website - https://ampbyexample.com/components/amp-sidebar/ and all sites using Wordpress Accellerated Mobile Pages plugin ) have stopped working on Chrome today.

**Comment by mkhatib** [comment] 2016-12-09 11:39
This seems like its due to the actual change to close the sidebar when clicking a link.

This is causing a history-pop event and at the same time the browser is trying to navigate away - the navigation gets cancelled by the browser because of history manipulation it seems (it literally says cancelled in the network tab).

I could reproduce something similar in [this jsbin](http://output.jsbin.com/sarobam/quiet) (though admittedly might not be the exact same thing) - but if you open network and preserve logs you'll notice that the `Go to Google` navigation got cancelled.

This might be related to timers firing after a navigation happens and browser not killing them as soon as a navigation happen (this might be the expected behavior not sure).

A quick fix would be to limit the close-sidebar when clicked to local-navigations only (which we handle their history ourselves unlike normal links navigation). This is really what we want with this anyway since the user is navigating away from the document - keeping the sidebar open won't matter. 

I'll have a quick fix tomorrow and cherry pick it - or otherwise we should just rollback this change.

**Comment by sebastianbenz** [comment] 2016-12-09 12:31
How long would it take to rollback?

**Comment by cramforce** [comment] 2016-12-09 16:36
The respective version was rolled back. Confirmed fixed on ABE.

Will keep this open for fix to land.

**Comment by letanure** [comment] 2016-12-09 16:39
Thank you!

**Closed** 2016-12-09 21:30 UTC
Labels: Priority: Critical
