### ISSUE TITLE
Support Beacon API in <amp-analytics> Gtag

### ISSUE THREAD

**Issue by jaswrks** [ampproject/amphtml#23146] opened 2019-07-01 23:18 UTC
It is not currently possible to set the transport type to `beacon` when using Gtag for Google Analytics. Doing so returns an AMP validation error, and also triggers 405 errors (unsupported request method) on some DoubleClick requests used by GA.

I'd like to get this working with Gtag in AMP.

```
"transport": {
    "beacon": true,
    "xhrpost": true,
    "image": true
},
```

**Comment by zhouyx** [comment] 2019-07-02 02:19
@jaswrks thank you for reporting the issue. I'd like to understand why would doing so lead to validation error. Is there a demo page or a demo config that you can share. 
cc @zikas on the gtag support for transport beacon.

**Comment by zikas** [comment] 2019-07-02 19:24
AMP doesn't allow redefining transport inside on-page configuration (although, it looks like it only reports error right now)
https://github.com/ampproject/amphtml/blob/2888ba72742755dcc3de02cd687081dc80845a92/extensions/amp-analytics/0.1/config.js#L334

sendBeacon() always sends POST request which is not supported by Doubleclick. This shouldn't be an issue for UA properties as even when Google Analytics redirects to Doubleclick. 302 will cause browser to change from POST to GET (https://stackoverflow.com/questions/17605915/what-is-the-correct-behavior-expected-of-an-http-post-302-redirect-to-get). 
You might still see 405 if you have doubleclick/ads property configured in gtag.

Why would you like to change the transport type? Current gtag implementation already takes care of the setting correct transport type (most likely it's image)

**Comment by jaswrks** [comment] 2019-07-02 23:59
😄  Thank for the details. Yes, that describes exactly what I am experiencing and the 405's are coming from the doubleclick ads configured in Gtag. The reason for wanting Beacon as the transport is that I'd like to enable click tracking on outbound links and in doing so, there is a race condition between tracking a click and a user leaving the page entirely. The `beacon` API guarantees those clicks will be tracked more accurately, whereas an `image` is not as reliable.

**Comment by zikas** [comment] 2019-10-25 19:13
Unfortunately we're not planning to support sendBecon at this moment (in web or AMP) and not our backends support POST. 
I'm closing the tread right now as intended behavior, feel free to reopen if you believe that this should be prioritized.

**Closed by zikas** 2019-10-25 19:13 UTC
Labels: Component: amp-analytics, P2: Soon, Type: Feature Request, WG: analytics
