### ISSUE TITLE
amp-bind fails to upgrade in Friendly Iframe

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#9395] opened 2017-05-17 15:28 UTC
When `amp-bind` is used in an A4A ad, it fails when ad is rendered in FIE, works in 3p.

in FIE case, error is:

```
amp-ads.firebaseapp.com/dist/amp.js:12415 Uncaught (in promise) Error: amp-bind is not upgraded yet
    at Log.assert (amp-ads.firebaseapp.com/dist/amp.js:12415)
    at Object.upgradeElementInChildWindow (amp-ads.firebaseapp.com/dist/amp.js:5495)
    at amp-ads.firebaseapp.com/dist/amp.js:19105
    at <anonymous>
```

/cc @choumx @dvoytenko

**Comment by choumx** [comment] 2017-05-17 20:01
Blocked by #7779.

**Comment by dvoytenko** [comment] 2017-05-23 18:03
@choumx This looks like a duplicate of  #7779? If so, let's close it out?

**Comment by choumx** [comment] 2017-06-01 21:33
This should work now. Tested on `https://localhost:8000/a4a/examples/bind/basic.amp.html`.

**Closed by choumx** 2017-06-01 21:33 UTC
Labels: Category: Ads, Category: Dynamic/Personalized Content, P2: Soon, Type: Bug
